### ISSUE TITLE
Video is played without image

### ISSUE THREAD

**Issue by Mickoou** [mrdoob/three.js#19901] opened 2020-07-21 17:59 UTC
##### Description of the problem

I think it's related to this issue : https://github.com/mrdoob/three.js/issues/19880
I'm not sure but be free to link mine to it.

When I try (on a http-server like the issue above) to play a video (~18Mb) on a slow network, it plays but without image. We can only hear the sound. 

I get three errors : 
`WebGL: INVALID_VALUE: tex(Sub)Image2D: video visible size is empty`
`[.WebGL-0x556447eedf80]RENDER WARNING: texture bound to texture unit 0 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?`
`[.WebGL-0xe4c99100]GL ERROR :GL_INVALID_VALUE : glCopyTextureCHROMIUM: invalid image size`

I manage to reproduce this bug only in Android Chrome 84 and it's not happening every time. Try to f5 the page if you don't have the "glCopyTextureCHROMIUM" error (on private navigation).

I think it's related to the issue mentioned above but I'm not sure.

![Capture](https://user-images.githubusercontent.com/68600761/88088799-4662e380-cb8b-11ea-8b6a-65fbae6ebef8.png)

Video : 
[black_screen.zip](https://github.com/mrdoob/three.js/files/4955516/black_screen.zip)

JSFiddle to reproduce : https://jsfiddle.net/Mickoou/63z9pth4/43/
PS: it has a click event to play the video.

Thanks !

##### Three.js version

- [x] Dev
- [x] r118
- [ ] ...

##### Browser

- [] All of them
- [x] Chrome 84
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [x] Android
- [ ] iOS

**Comment by Mugen87** [comment] 2020-07-21 18:17
Can't reproduce this on a Pixel 1 with Chrome 84. The video plays after the interaction.

BTW: You want to hide the video element otherwise it appear below the canvas: https://jsfiddle.net/w6cyxsa7/2/

**Comment by Mickoou** [comment] 2020-07-21 18:38
Hey @Mugen87 ,

Thanks for your answer, I updated the JSFiddle. My phone is a Galaxy S8+ with Android9.

I join a video with the bug. The second time I refresh the page, you'll see that the video is playing without image.
[black_screen.zip](https://github.com/mrdoob/three.js/files/4955503/black_screen.zip)

**Comment by Mugen87** [comment] 2020-07-21 18:52
Um, I can't reproduce it on my phone. Do you mind testing with a different Android device?

**Comment by Mugen87** [comment] 2020-07-22 11:04
Besides, please try the latest dev builds since there was a latest change in context of `VideoTexture`s:

https://github.com/mrdoob/three.js/tree/dev/build

**Comment by Mickoou** [comment] 2020-07-23 16:06
Hi @Mugen87,

I tried on a Samsung Note8, with your last dev version, same issue. I confirm that I don't get anymore warnings from #19880 but console still showing glCopyTextureChromium error.

![image](https://user-images.githubusercontent.com/68600761/88294826-fefc6480-ccfc-11ea-8298-65395dd7f434.png)

**Comment by Mugen87** [comment] 2020-07-23 16:12
> I confirm that I don't get anymore warnings from #19880

Good to hear that! :+1:

> but console still showing glCopyTextureChromium error.

Can you please verify if video textures work with BabylonJS? Please try out this demo:

https://www.babylonjs-playground.com/#CHQ4T#1

You have to click on "Run" to start the video.

**Comment by Mickoou** [comment] 2020-07-23 16:18
It's also randomly not playing and when it's happening, my console displays : 
![image](https://user-images.githubusercontent.com/68600761/88311216-e72edb80-cd10-11ea-9492-90210bbd980a.png)

**Comment by Mugen87** [comment] 2020-07-23 16:23
It seems there is an issue with your device. I don't believe this can't be fixed on app or engine level.

Try to upgrade Android if possible. Unfortunately, I can't think of another solution...

**Closed** 2020-07-24 09:02 UTC
Labels: Device Issue

**Comment by phdcoder** [comment] 2020-10-11 00:44
I was experiencing  the same error, resolved this problem by downloading the whole video using  XMLHttpRequest before creating GL context.
