### ISSUE TITLE
Extremely slow performance with specific file

### ISSUE THREAD

**Issue by hybridherbst** [mrdoob/three.js#22785] opened 2021-11-04 21:43 UTC
**Describe the bug**

A specific test file (for color space testing) is causing threejs to become unresponsive and take the entire browser with it.

**To Reproduce**

1. download the attached file
[unlit=color.zip](https://github.com/mrdoob/three.js/files/7478938/unlit.color.zip)
2. open the file in https://threejs.org/editor/
3. zoom out until you can see the content
4. note browser is hanging, changing tabs doesn't change that, have to kill browser

**Expected behavior**

File loads and displays fast, it's pretty small.

**Screenshots**
The file is a test case for textures/colors/vertex colors. It has many small meshes and materials but loads very fast in other systems (e.g. Babylon Sandbox or gltf.report)
![image](https://user-images.githubusercontent.com/2693840/140424265-d1a5fda4-43ea-4a37-ac00-32bf45d95e0b.png)

**Platform:**

 - Device: Desktop
 - OS: Windows 10
 - Browser: Chrome 95.0.4638.69

**Comment by Mugen87** [comment] 2021-11-05 08:48
I can't reproduce this on macOS with Chrome 95.0.4638.69. Viewing the asset in the three.js editor and [gltf-viewer](https://gltf-viewer.donmccurdy.com/) works without performance issues.

On what systems/browser have you tested?

**Comment by Mugen87** [comment] 2021-11-05 09:01
Here is a glitch with your asset for easier testing: https://glitch.com/edit/#!/nebula-lavish-ballcap?path=index.html

**Comment by hybridherbst** [comment] 2021-11-05 10:52
Sorry, should have added - Windows 10, Chrome 95.0.4638.69. I also updated the original post.

**Comment by Mugen87** [comment] 2021-11-05 11:41
Okay, let me check the glitch on Windows later.

**Comment by Mugen87** [comment] 2021-11-05 11:48
This is actually a duplicate of #22758 since your asset contains a lot of sRGB encoded RGB textures. The current workaround is to use `WebGL1Renderer` or by setting the `minFilter` property of all sRGB textures to `THREE.MinFilter`. I've applied this specific fix to the glitch.

**Closed by Mugen87** 2021-11-05 11:48 UTC

**Comment by hybridherbst** [comment] 2021-11-05 13:30
Thanks for verifying.
I believe in this case it's far worse than 10x though, it goes from "instant loading" to "never loading", is there another regression that goes from "constant shader compilation time" to "linear compilation time"?

**Comment by Mugen87** [comment] 2021-11-05 13:39
With duplicate I just mean the problem is caused by the same issue. Let's continue the discussion in #22758.

**Comment by toji** [comment] 2021-11-05 15:55
Something that's interesting to note with this file is that it only contains one texture, which is modestly sized at 1024x1024. (Could be smaller, since it's just solid color blocks, but whatever.) While I would expect it to have a small hitch as it generates the mipmap for that single file, I wouldn't anticipate anything like the freezing behavior that @hybridherbst is describing unless that same texture is being uploaded to the GPU separately for each of the 264 different materials that use the same texture. In which case... 😱

**Comment by Mugen87** [comment] 2021-11-05 16:16
This assets exhibits a long-standing issue in the engine which we have try to solve via #17949.

**Comment by WestLangley** [comment] 2021-11-05 16:24
<img width="336" alt="Screen Shot 2021-11-05 at 12 23 15 PM" src="https://user-images.githubusercontent.com/1000017/140544384-3fa16155-6a92-4a9d-9660-5250c6f5ea38.png">

**Comment by toji** [comment] 2021-11-05 17:13
Ah. Okay then. 😰

**Comment by hybridherbst** [comment] 2021-11-23 21:34
@Mugen87 #22758 has been closed since #22759 has been merged and r134 is released.
Just for clarification, I assume this means that this case and type of files will stay problematic until #22846 makes it into a release?

**Comment by Mugen87** [comment] 2021-11-23 21:53
Yes, `r135` will not solve the texture uploading issue. This requires #22846 or a similar solution.

**Comment by mrdoob** [comment] 2022-02-02 17:28
#22846 solved this.

| Before | After |
| --- | --- |
| <img width="138" alt="Screen Shot 2022-02-02 at 12 27 05 PM" src="https://user-images.githubusercontent.com/97088/152205703-fdf83100-3446-4738-9fe0-f0e9f071e17b.png"> | <img width="138" alt="Screen Shot 2022-02-02 at 12 27 42 PM" src="https://user-images.githubusercontent.com/97088/152205739-1aa1cef9-419c-4f22-9477-ea72a85dde96.png"> |
