### ISSUE TITLE
Unwanted edge rendering

### ISSUE THREAD

**Issue by dericatienza** [mrdoob/three.js#13623] opened 2018-03-18 08:43 UTC
##### Description of the problem

I'm trying to render only the edges of the geometry below but I am getting unwanted edges specifically the ones in violet line. The green lines represent the ones generated by an EdgesGeometry with threshold 1 and the faded grey lines are generated by a WireframeGeometry for examination of the whole geometry of the object.

Green lines:
`  const edgesGeometry = new EdgesGeometry(geometry, 1);
const edges = new THREE.LineSegments(edgesGeometry, this._brickEdgesMaterial);`

Grey lines:
`const wireframeGeometry = new WireframeGeometry(geometry);
const wireframe = new THREE.LineSegments(wireframeGeometry, this._brickWireframeMaterial);`

*Violet lines were edited in

![capture](https://user-images.githubusercontent.com/5621894/37564137-9f437ca8-2aca-11e8-8947-98f2bc2cad81.PNG)

Also. Here's the geometry in json format generated through Geometry.toJSON(). File is in txt format because github does not allow json file uploads.

[geometry.txt](https://github.com/mrdoob/three.js/files/1822495/geometry.txt)

##### Three.js version

- [ ] Dev
- [ ] r91
- [x] r89

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment] 2018-03-18 12:06
I've prepared a fiddle, so it's easier to debug the issue: https://jsfiddle.net/f2Lommf5/3314/

**Comment by Mugen87** [comment] 2018-03-18 12:06
This is actually a duplicate of #10517

**Closed by Mugen87** 2018-03-18 12:06 UTC
