### ISSUE TITLE
is THREE.ObjectLoader friends with LoadigManager?

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#14089] opened 2018-05-18 09:02 UTC
I have a code like this:
```javascript
var manager = new THREE.LoadingManager, loader = new THREE.ObjectLoader (manager), model;
manager.onLoad = function () {
	console.log (model); // log 2
};
loader.load (
	'......json',
	function (result) { model = result; console.log(result) } // log 1
);
```
and log 2 randomly happens before log 1 (logging `undefined` as a result). This never happened with real loaders, what's going on?

**Comment by Mugen87** [comment] 2018-05-18 09:09
I guess the issue might be related to #13177

**Comment by Mugen87** [comment] 2018-05-19 08:59
Yeah, your problem is definitely caused by the mentioned issue. The current implementation of `ObjectLoader` constrains the usage of `LoadingManager`. 

I'm marking this as a duplicate since #13177 is the leading issue for this.

**Closed by Mugen87** 2018-05-19 08:59 UTC
