### ISSUE TITLE
[Editor] Spotlights imported from GLB have their target reset after page reload

### ISSUE THREAD

**Issue by hybridherbst** [mrdoob/three.js#23016] opened 2021-12-13 20:20 UTC
**Describe the bug**

When importing Spotlights from GLB, their target seems to be reset after page reload, resulting in different lighting / broken scene.

**To Reproduce**

1. Go to https://threejs.org/editor/
2. Import [World.zip](https://github.com/mrdoob/three.js/files/7706719/World.zip)
3. Note spotlights shining from above
4. Refresh page
5. Note spotlights all shining towards (0,0,0)

**Expected behavior**

Spotlights still work after page reload

**Screenshots**

_After dropping GLB (and turning physical lighting on)_
![image](https://user-images.githubusercontent.com/2693840/145882393-ab238dce-130a-4259-bc88-f1967d3fe55e.png)

_After page reload_
![image](https://user-images.githubusercontent.com/2693840/145882448-fc0edc86-78a4-4294-9027-d0630d899f26.png)

Note: it seems that generally, when creating a spotlight the target can't be moved in the threejs editor. Is this expected? Should I open a separate issue for this?

**Comment by Mugen87** [comment] 2021-12-14 08:57
Duplicate of #9508.

There is currently not editor support for the `target` property of lights.

**Closed by Mugen87** 2021-12-14 08:57 UTC

**Comment by hybridherbst** [comment] 2021-12-14 09:46
I see how that relates but I feel "a file breaks in the editor" is a separate issue than "there's no support to move the target around".

**Comment by Mugen87** [comment] 2021-12-14 09:57
We use #9508 to track the general lack of support for `target` light properties (in whatever manifestation) in the editor. Meaning `target` can't be transformed in the editor and there is no serialization/deserialization support.

**Comment by Mugen87** [comment] 2021-12-14 10:00
Notice that it is considered to remove the `target` property from lights, see #5079. There is also a respective PR, see #14658.

It probably makes sense to solve #5079 first before considering updates to the editor. I hope we get https://github.com/mrdoob/three.js/pull/14658#issuecomment-666051811 in place at some point.

**Comment by hybridherbst** [comment] 2021-12-14 10:09
+1 from me for removing "target" and fixing some of the weird behaviours of three in regards to "objects that use their position as rotation" as well ;)
