### ISSUE TITLE
refractionRatio has no effect on MeshPhysicalMaterial and MeshStandardMaterial

### ISSUE THREAD

**Issue by ManishJu** [mrdoob/three.js#18093] opened 2019-12-06 17:38 UTC
The refractionRatio has no effect on MeshPhysicalMaterial

In threejs example  https://threejs.org/examples/?q=refract#webgl_materials_cubemap_refraction

replace line 81,82 and 83 with the following:
```js
var cubeMaterial3 = new THREE.MeshPhysicalMaterial( {color: 0xccddff,envMap: textureCube, refractionRatio: 0.90,reflectivity: 0.1,transparent : true,opacity : 0.2,} );
var cubeMaterial2 = new THREE.MeshPhysicalMaterial( { color: 0xccfffd, envMap: textureCube, refractionRatio: 0.985, transparent : true,opacity : 0.2 } );
var cubeMaterial1 = new THREE.MeshPhongMaterial( { color: 0xffffff, envMap: textureCube, refractionRatio: 0.98 } );
```
 
and you will see only the middle model showing refraction effect:

![Capture](https://user-images.githubusercontent.com/24234466/70343309-fb56c300-187c-11ea-9106-b33e9faa99f1.PNG)

##### Three.js version

- [ ] Dev
- [x ] r111
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment] 2019-12-07 10:00
Your issue is actually a duplicate of #14142

**Closed by Mugen87** 2019-12-07 10:00 UTC
