### ISSUE TITLE
The error report is not very friendly if we passed undefined(first parameter) to Mesh Class. 

### ISSUE THREAD

**Issue by jolintsai** [mrdoob/three.js#17967] opened 2019-11-20 09:12 UTC
##### Description of the problem
The error report is not very friendly if we passed undefined(first parameter) to Mesh Class. 

For example, i once made a mistake like below:
        var geometryIsUndefined= undefined; 
        var material = new THREE.MeshLambertMaterial({color: '#ffffff'});
        var mesh= new THREE.Mesh(geometryIsUndefined, material);

The console give me an error :
Cannot read property 'count' of undefined TypeError: Cannot read property 'count' of undefined

Indeed, when i pass undefined geometry to Mesh, the Mesh class set its geometry with default buffergeometry. And the count of index of undefined buffergeometry is undefined. It is very confused for beginners. 

So it is best to have an error report like:
"You should not pass undefined geometry to Mesh Class" if i write code like this:
var mesh= new THREE.Mesh(undefined, material);
 
best regards
kai

##### Three.js version

- [x] Dev
- [x] r110
- [ ] ...

##### Browser

- [] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment] 2019-11-20 09:45
The problem is that it's totally valid to create a mesh without ctor paramters. So if we really implement an undefined check, a lot of existing code would start to throw warnings.

I think your issue is more or less related to: https://github.com/mrdoob/three.js/issues/13601

The problem is that `WebGLRenderer` is not able to process instances of `BufferGeometry` in their initial state. I personally think this behavior needs to be fixed since just creating an instance should not mean it's "incomplete". The renderer should be able to gracefully handle such geometries.

**Comment by Mugen87** [comment] 2019-11-22 11:07
Closing in favor of #13601

**Closed by Mugen87** 2019-11-22 11:07 UTC
