### ISSUE TITLE
Editor GUI options are not enough to build new animations or effects

### ISSUE THREAD

**Issue by KnightCoder** [mrdoob/three.js#19212] opened 2020-04-24 08:17 UTC
##### Description of the problem

ThreeJS editor does not have enough tools to animate or apply effects to the 3D models. Hence, I guess, this might come as a new feature request, to increase the tools/options inside the editor such that almost everything can be performed using the editor's GUI alone. 

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment] 2020-04-24 09:04
This is actually a duplicate of #16234. Please continue the discussion there 👍 .

**Closed by Mugen87** 2020-04-24 09:04 UTC
Labels: Duplicate
