### ISSUE TITLE
Please Support 8-bit Integers

### ISSUE THREAD

**Issue by 0X-JonMichaelGalindo** [mrdoob/three.js#22103] opened 2021-07-08 15:16 UTC
**Is your feature request related to a problem? Please describe.**

My app uses an 8-bit integer layer ID. Every time I pull a new Three.js release, I have to paste-replace this line or my app will break:
```if ( capabilities.isWebGL2 === true && ( type === 5124 || type === 5125 )  ) {```
```if ( capabilities.isWebGL2 === true && ( type === 5124 || type === 5125 || ( type === 5121 && ( ! normalized ) ) )  ) {```

**Describe the solution you'd like**

Can we change that line in the main branch?
All existing working code will work exactly the same.

Explanation:  
JS has no 8-bit floats.  
- ```normalized=true``` if and only if ```float``` array
- ```normalized=false``` if and only if ```int``` array.  

100% unambiguous.  

Right now, normalized=false just breaks Three.js's buffer implementation / corrupted data goes to the shader.

**Describe alternatives you've considered**

Even if I make a fork just for that 1 line, it won't be able to merge cleanly, and I'll still have to go in and copy-paste every time.
There's a related FR about improving integer support, but I think it went nowhere.

**Comment by Mugen87** [comment] 2021-07-09 08:09
Can you please share a complete [live example](https://jsfiddle.net/f2Lommf5/) that shows what you are want to do?

**Comment by 0X-JonMichaelGalindo** [comment] 2021-07-09 19:55
Basically: Three.JS does not support 8-bit integer attributes in shaders (it breaks). I want 8-bit integer attributes in shaders.

Example: [https://jsfiddle.net/c4gjumkr/](https://jsfiddle.net/c4gjumkr/)
The fiddle runs a black screen.
Fix this on line 25 (inside the vertex shader):
```
id2 = id2 + 1; /*<-- Comment me out and Three.js's buffer bug will stop breaking this app! */
```
Comment out the line and re-run the fiddle. The blue cube appears.

---

Why?  
Three.js doesn't support 8-bit integer attributes: It corrupts them, guaranteed. Operations on corrupted data crash a shader.

---

How should Three.js behave?

I want this buffer attribute:
```
new THREE.Uint8ClampedBufferAttribute( myUint8ClampedArray, myElementsPerVertex, normalized=false );
```
To feed this input:
```
attribute int myUint8Attribute;
```
Straight-forward in WebGL2.

---

But, for 8-bit data, Three.js always call the second function here:
```JavaScript
if ( capabilities.isWebGL2 === true && ( type === 5124 || type === 5125 ) ) {
    gl.vertexAttribIPointer( index, size, type, stride, offset );
} else {
    //Uint8 data is type === 5121 aka WebGL2RenderingContext.UNSIGNED_BYTE, always lands here
   gl.vertexAttribPointer( index, size, type, normalized, stride, offset );
}
```
Fails:
![image](https://user-images.githubusercontent.com/7831784/125126658-6c013980-e0c9-11eb-9052-e00b33ba8b7d.png)

---
Same corrupted data issue here [https://github.com/mrdoob/three.js/issues/18341](https://github.com/mrdoob/three.js/issues/18341)
Where the solution was "don't use normalized = false on 8-bit data":
![image](https://user-images.githubusercontent.com/7831784/125128734-71ac4e80-e0cc-11eb-8d74-8502d9361908.png)

8-bit data + normalized = false breaks Three.js.

Instead of "change your code to avoid breaking", I would like Three.js to support 8-bit integer attributes, as WebGL2 does.

It's half-bug, half-feature request.

**Comment by Mugen87** [comment] 2021-07-09 20:17
Thanks for the explanation! This issue is actually a duplicate of #21595. There is already a PR trying to fix this issue.

**Closed by Mugen87** 2021-07-09 20:17 UTC

**Comment by 0X-JonMichaelGalindo** [comment] 2021-07-09 20:21
Thanks! Glad it's being taken care of. PR looks significantly more in-depth than my quick-fix.
