### ISSUE TITLE
Terrible FPS with Chrome 100+ for instancing example.

### ISSUE THREAD

**Issue by CraigglesO** [mrdoob/three.js#24037] opened 2022-05-09 17:16 UTC
**Describe the bug**

Chrome found 0 day bugs for webgl, webgpu, angle, etc.
Interestingly enough some of my instanced code on my own project got absolutely destroyed with FPS for WebGL2. Meanwhile WebGL1 was unfazed. I dig some digging into Three JS to see if chrome impacted your project as well and I noticed instancing with raycast absolutely gets shredded FPS wise. Curious if you guys had any ideas on what is going on? I might have to completely give up on ANGLE longer term.

**To Reproduce**

1. Go to https://threejs.org/examples/?q=instan#webgl_instancing_raycast

***Live example***

https://threejs.org/examples/?q=instan#webgl_instancing_raycast

**Expected behavior**

Standard frame rates.

**Platform:**

 - Device: Desktop
 - OS: MacOS (Monterey)
 - Browser: Chrome (version 100+)
 - Three.js version: latest

**Comment by donmccurdy** [comment] 2022-05-09 18:04
Framerate is smooth 60 FPS for me, could you share more details on what framerate you're seeing and versions of your OS, browser, GPU, etc.?

- Chrome: 101.0.4951.54 (arm64) 
- macOS: 12.3.1 (21E258) (Monterey)
- GPU: M1

**Comment by LeviPesin** [comment] 2022-05-09 18:25
Is this a duplicate of https://github.com/mrdoob/three.js/issues/23821?

**Comment by CraigglesO** [comment] 2022-05-09 18:48
Very interesting M1 doesn't have the same issues. Is a duplicate, I apologize.

**Closed** 2022-05-09 19:14 UTC
