### ISSUE TITLE
.addEventListener('mousedown/mouseup', e => fun(e)) no longer works

### ISSUE THREAD

**Issue by lan23333** [mrdoob/three.js#20489] opened 2020-10-09 18:51 UTC
**Describe the bug**

A clear and concise description of what the bug is. Before submitting, please remove unnecessary sections.

**To Reproduce**

add event listener to a div mounted with three

***Code***

```js
currentMount.addEventListener('mousemove', event => this.onMouseMove(event));
currentMount.addEventListener('mousedown', event => this.onMouseDown(event));
currentMount.addEventListener('mouseup', event => this.onMouseUp(event));

//mousemove works, mouseup and mouse down doesnt
```

**Platform:**

 - Device: Desktop
 - OS: Windows
 - Browser: Chrome
 - Three.js version: r121

**Comment by Mugen87** [comment] 2020-10-09 18:58
Probably duplicate of #20294.

**Comment by DefinitelyMaybe** [comment] 2020-10-09 22:01
If your looking for more help @lan23333, best bet might be to repost onto the [forums](https://discourse.threejs.org/)

**Closed** 2020-10-10 08:36 UTC
