### ISSUE TITLE
Buggy rendering of meshes on iOS 8, iPad

### ISSUE THREAD

**Issue by kfurmann** [mrdoob/three.js#5529] opened 2014-10-28 08:57 UTC
In the following example:
http://threejs.org/examples/#webgl_materials_cars

witness how some meshes, most notably front left wheel, are rendered wrong. Our team has encountered similar looking bugs while rendering our own models. The bug appears consistently while looking at the mesh under certain angles while it's ok under different angles. It also seems that order of adding Objects3D to the scene plays some role here.

Happens on iPad 4, both iOS 8 and 8.1, Chrome and Safari.

I can provide screenshots if necessary.

**Comment by Mugen87** [comment] 2017-04-16 11:31
@kfurmann I know this is an old issue, but did you ever see the mentioned visual error on newer iOS versions? If not, i'd like to close this issue. Thx!

**Comment by Mugen87** [comment] 2017-04-20 14:08
I'm unable to reproduce with an iPad 5 and latest iOS. Closing this for now.

**Closed by Mugen87** 2017-04-20 14:08 UTC
Labels: Bug
