### ISSUE TITLE
PropertyBinding: Consider keeping fallback to root node

### ISSUE THREAD

**Issue by yoshikiohshima** [mrdoob/three.js#26328] opened 2023-06-26 00:14 UTC
### Description

There was a commit around findNode() here:

https://github.com/mrdoob/three.js/commit/5da06be6561a9ced52e98641c141b9c4f82c0b80

and discussion that was a bit ambitious

https://github.com/mrdoob/three.js/pull/25329

In another use case, where popular Ready Player Me avatars are animated with separated animation sequences got broken by incorporating this change.

I cannot tell the original motivation of this fix, as the participants in the pull request #25329 but it is possibly that too eager to incorporate the change for one particular use case.

I could imagine the use case reported there might have some reasons not to fall back on the "rootNode", but the fix was not neutral. It is good to get  some clarity on it, and if that was a legitimate change, I'd like to expand the findNode() to get an extra argument to support the other user case(s).

### Reproduction steps

1.
2.
3.

### Code

```js
// code goes here
```

The separating of the animation rig and animated avatar is implemented here:

https://github.com/croquet/microverse/blob/6302d8d8a1052e3e0ac077386794a9665fbab278/behaviors/croquet/fullBodyAvatar.js#L83C26-L83C26

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/g3atw6k5/)
* [jsfiddle-dev](https://jsfiddle.net/hjqw94c5/)

### Version

152

**Comment by Mugen87** [comment] 2023-06-26 07:57
The fallback to `rootNode` was removed since we were not aware of a use case where it is required. Actually, I've extensively searched the project's history about why this code was added (see https://github.com/mrdoob/three.js/issues/25286#issuecomment-1402075693) but unfortunately there is nothing documented.

Do you mind sharing an glTF asset that demonstrated the issue? Sharing parts of your application is unfortunately insufficient. We need a concrete 3D model that defines animations such that the code in `PropertyBinding` breaks.

**Comment by yoshikiohshima** [comment] 2023-06-26 14:08
Thanks for the replay. The animation sequences are in those files: https://github.com/croquet/microverse/tree/main/assets/avatar-animations

the avatars are such as: 

https://models.readyplayer.me/62f56aaf3e172e00545c2502.glb
and
https://models.readyplayer.me/62f56a0f3e172e00545c12d4.glb

Those are regular Ready Player Me avatars.

I can (and will) set up a test installation to exhibit the error if necessary.

**Comment by yoshikiohshima** [comment] 2023-06-26 15:09
If you open this link:

https://croquet.github.io/microverse/three153/?showSettings=ture

and enter a name and choose an avatar and press Enter. you see errors in console (and the avatar is facing toward you; though it does animate. You can mouse wheel or two finger vertical swipe to see yourself. You can also enter the same session by copying the longer URL that is crated into a new window. (unlike the name suggests, the THREE.js version used in this particular one is 152).

An installation with v149, such as this croquet.io/microverse?showSettings=true works fine.

**Comment by mrdoob** [comment] 2023-06-27 07:27
@hybridherbst any ideas of what should we do here?

**Comment by yoshikiohshima** [comment] 2023-06-29 17:28
Any more comments? We could perhaps have a flag to fall back or not for findNode(), and that can be passed down in some way (not sure how). If fixing our animation files (https://github.com/croquet/microverse/tree/main/assets/avatar-animations) is the way to go, we should be able to do that, as long as there is a way to tell Blender to produce what new Three.js expects.

**Comment by hybridherbst** [comment] 2023-06-29 18:07
I can look into it on Monday. We should definitely _not_ fall back to the root node, the code that did that did literally apply leaf node animations to the root and always resulted in wrong results. 

The case described here sounds like classic remapping of animations - the removed code did not do that! It literally just remapped "some/node/not/found" to "some" which is never desired. If something else broke that may be unintended.

**Comment by hybridherbst** [comment] 2023-06-29 18:24
Found the time now. For me it looks like
- everything is working as intended - matching hierarchies play properly
- additional tracks in leaf nodes that exist in the animation, but not the character, log errors. One course of action here could be downgrading those to warnings.
  - previously, _the animations from those leaf nodes were applied to the root_, resulting in something like `HeadTop_End_end.quaternion` randomly rotating the root node!
- I think in the previous three version this just "accidentally worked" (e.g. the root nodes are rotated 180° and lead to the "looking correct" behaviour).
- the code may need to be adjusted to properly rotate the character so that it looks in the desired direction - I can't find any character rotation in the [linked lines from here](https://github.com/croquet/microverse/blob/6302d8d8a1052e3e0ac077386794a9665fbab278/behaviors/croquet/fullBodyAvatar.js#L128).

**Comment by yoshikiohshima** [comment] 2023-06-29 18:27
The line here: https://github.com/croquet/microverse/blob/6302d8d8a1052e3e0ac077386794a9665fbab278/behaviors/croquet/fullBodyAvatar.js#L71 rotates the avatar (Ready Player Me avatar look to +z direction but it'd have to look -z). So I don't think leaf node's rotation is applied to the root node.

**Comment by hybridherbst** [comment] 2023-06-29 18:31
Rotating on model load is not enough - the tracks in `walking.glb` contain an animation for the Armature node so that will always be reset. You need to either rotate the parent or remove the root rotation track, otherwise that baked-in rotation will be applied each frame.

![image](https://github.com/mrdoob/three.js/assets/2693840/34ff60df-22bb-4636-8486-d19315039e19)

**Comment by yoshikiohshima** [comment] 2023-06-29 18:34
ok.. We'll try that. What about the errors: "THREE.PropertyBinding: Trying to update node for track: RightToe_End_end.quaternion but it wasn't found." what part of system is responsible to surpress the errors?

**Comment by hybridherbst** [comment] 2023-06-29 18:39
See my comment here:
https://github.com/mrdoob/three.js/issues/26328#issuecomment-1613604795

That error literally means that some of the animated tracks in walking.glb can't find matching hierarchies in the model, which is indeed the case - all those _end effectors that Blender exports don't exist as nodes in the character (everything in yellow):
![image](https://github.com/mrdoob/three.js/assets/2693840/ca8b1d57-a279-4108-86fa-07ad6548e0af)

The line logging the error is https://github.com/mrdoob/three.js/blob/edefdc237b2528b9668fb873a1c06cb835840303/src/animation/PropertyBinding.js#L437

**Comment by mrdoob** [comment] 2023-06-30 04:08
Thank you for investigating this 🙏

Downgrading to a warning sounds good to me.

**Comment by hybridherbst** [comment] 2023-06-30 05:53
Ok, I can reword and make a PR

**Comment by yoshikiohshima** [comment] 2023-07-06 19:27
We got around fixing the animation files (https://github.com/croquet/microverse/tree/three153/assets/avatar-animations) and it is now working fine. Thank you for suggestions!

**Comment by takahirox** [comment] 2023-07-15 05:46
So, we may close this issue because the problem seems to be resolved on his end (and keeping the fallback removed sounds good to me)?

**Closed** 2023-07-15 07:55 UTC
Labels: Needs Investigation
