### ISSUE TITLE
FBXLoader: Invalid material indices break raycasting.

### ISSUE THREAD

**Issue by jonnywang** [mrdoob/three.js#24357] opened 2022-07-18 02:06 UTC
**Describe the bug**

I'm not sure if it was the model that caused the mistake

```js
fbxLoader.load(
                '/All.fbx',
                (object) => {
                    this.scene.add(object)

                    object.traverse(( child ) => {
                        if ( child.type == 'Group' && ['NAME'].includes(child.name) ) {
//used three.interactive
                            this.interactionManager.add(child)
                            child.addEventListener('click', () => {
                                 console.log('click')
                            })
                        }
                    })
                },

              ....
```

**Screenshots**

<img width="878" alt="image" src="https://user-images.githubusercontent.com/960982/179435397-100b1ea6-ca13-4dce-8835-1c4a22aa7b00.png">

**Comment by Mugen87** [comment] 2022-07-18 10:54
[As discussed before](https://discourse.threejs.org/t/r139-bug-raycaster-intersectobject-fails-because-groupmaterial-index-is-1-in-imported-fbx-model/36955), this issue is probably related to the FBX exporter producing `All.fbx`. If this is fixed in `three.js`, it has to be done in `FBXLoader`.

**Comment by Mugen87** [comment] 2022-07-18 10:55
@jonnywang Is it possible for you to use glTF instead of FBX?

**Comment by jonnywang** [comment] 2022-07-19 02:13
thanks  @Mugen87   

I will communicate with the designer and verify later

**Comment by Mugen87** [comment] 2022-07-28 08:31
Renamed the issue since this is a problem in `FBXLoader`.

@jonnywang Do you mind sharing `All.fbx` or another small test case so it's possible to reproduce the issue? Right now, we have no asset in the repository that triggers the runtime error.

**Comment by jonnywang** [comment] 2022-08-03 06:25
https://drive.google.com/file/d/1mSisxqra_77ISP3ltLhikw0QCLjUag7n/view?usp=sharing

**Closed** 2022-08-03 11:24 UTC
Labels: Loaders
