### ISSUE TITLE
OrbitControls stays in incorrect state after pointercancel event

### ISSUE THREAD

**Issue by molnarm** [mrdoob/three.js#25505] opened 2023-02-14 09:55 UTC
### Description

Opening a page with OrbitControls on an iPad can result in several errors when moving the scene with two fingers closely pinched together. 

Probably it's the same in any case where `pointercancel` would be fired, but this is the scenario which we can consistently reproduce on multiple devices. Surface tables or Android phones don't fire this event (in this case at least).

### Reproduction steps

1. Open a page with OrbitControls (even [the official example](https://threejs.org/docs/#examples/en/controls/OrbitControls) works) on an iPad (tested on multiple devices, the latest is iOS 16.3 Safari)
2. Add a global error listener (`window.addEventListener('error', e=>{...})`)
3. Start panning the scene with two fingers pinched closely together

The error handler will fire several times.

### Code

The error triggered regardless of user code.

As far as I could tell, the problem is that in `OrbitControls.js`, in `onPointerCancel`, the pointer is removed, but `state` is not changed. So if we were in the middle of a panning or zooming gesture for example (`state = TOUCH_DOLLY_PAN`), the next call to `onPointerMove` will eventually end up in `getSecondPointerPosition`, which will throw when trying to read the position of the nonexistent second pointer.

### Live example

* [jsfiddle-dev](https://jsfiddle.net/0s5f6gqa/)

### Version

r149

### Device

Mobile

### Browser

Safari

### OS

iOS

**Comment by Mugen87** [comment] 2023-02-20 09:45
> with two fingers closely pinched together.

So the `pointercancel` is fired on iOS when two fingers are moved closely together? Does that mean Webkit interprets this setup as a single pointer? Besides, `pointerup` isn't fired in this scenario, right?

I wonder if this issue can be fixed by simply adding `state = STATE.NONE;` in `onPointerCancel()`?

**Comment by Mugen87** [comment] 2023-02-20 10:04
I've added the line to a branch for testing? Can you still reproduce the issue with:

https://rawcdn.githack.com/Mugen87/three.js/d0d953fe1c71ad38a1096b7cd25c00e264bd2f2a/examples/misc_controls_orbit.html

**Comment by molnarm** [comment] 2023-02-20 10:18
**No, that change fixes this issue.** Thanks for the quick response.

As for your questions: I didn't find any specifics on what exactly triggers `pointercancel`, but we can reproduce it this way consistently. It probably happens when the two touches move so close that they "merge" into one, but that's just my guess.

> Besides, `pointerup` isn't fired in this scenario, right?

Yes. In fact, that is my current workaround: trigger a fake `pointerup` when getting `pointercancel`.

> I wonder if this issue can be fixed by simply adding state = STATE.NONE; in onPointerCancel()?

I'm not very familiar with the details of OrbitControls, but probably the other steps taken in `onPointerUp` (removing event listeners, dispatching end event) should be done too, except maybe the pointer capture release?

**Comment by Mugen87** [comment] 2023-02-20 10:28
> I'm not very familiar with the details of OrbitControls, but probably the other steps taken in onPointerUp (removing event listeners, dispatching end event) should be done too, except maybe the pointer capture release?

Yes, that makes sense. We probably can remove the `onPointerCancel()` function and just register the `onPointerUp()` listener for the event. So:
```js
scope.domElement.addEventListener( 'pointercancel', onPointerUp );
```

**Comment by Mugen87** [comment] 2023-02-20 10:40
Update the branch with the suggested fix:

https://rawcdn.githack.com/Mugen87/three.js/c6539da8a70f994c48c9ce472ff82149bb6072f7/examples/misc_controls_orbit.html

**Comment by optimus007** [comment] 2023-02-24 08:56
is this related ?

On android when two fingers are active and i use the third finger to a system action (like pull down notification drawer) orbitcontrols gets stuck in a locked state


https://user-images.githubusercontent.com/6885294/221134018-9d7e26c5-b64e-44ce-ac09-7117a1c20c76.mp4

**Comment by Mugen87** [comment] 2023-02-24 09:21
@optimus007 Does this still happen with: https://rawcdn.githack.com/Mugen87/three.js/dev75/examples/misc_controls_orbit.html

**Comment by optimus007** [comment] 2023-02-24 09:57
Yeah, .. still happens 


https://user-images.githubusercontent.com/6885294/221149116-599c9b7d-297d-43d1-bf28-786689d8ba14.mp4

**Comment by Mugen87** [comment] 2023-02-24 10:00
Then this seems to be a different issue.

**Closed** 2023-02-24 10:00 UTC
Labels: Bug
