### ISSUE TITLE
Serializing any Object3D with nested NodeMaterial throws error

### ISSUE THREAD

**Issue by emilwidlund** [mrdoob/three.js#21352] opened 2021-02-24 13:49 UTC
**Describe the bug**

As the `toJSON` method on a THREE Node expects a `nodes` field in the meta object, it throws an error if the meta comes from an Object3D which never supplies that field. 

**To Reproduce**

1. Setup a simple THREE project
2. Add a mesh to the scene with a NodeMaterial
3. Serialize scene using `scene.toJSON()`

***Live example***

[See Sandbox example](https://codesandbox.io/s/new-snow-0nn7s?file=/src/index.ts)

**Expected behavior**

Object3D should serialize just fine. Solution would be to include a `nodes` field in the default meta-object.

**Platform:**

 - Device: [Desktop, Mobile]
 - OS: [Windows, MacOS, Linux, Android, iOS]
 - Browser: [Chrome, Firefox, Safari, Edge]
 - Three.js version: 0.125.2

**Comment by Mugen87** [comment] 2021-02-24 14:51
Let's say #21353 would be merged. How would you deserialize the resulting JSON?

The problem is that `NodeMaterial` is currently no part of the core and `Object3D.toJSON()` as well as `ObjectLoader` only support core features right now. Meaning classes present in the `src` directory.

**Comment by emilwidlund** [comment] 2021-02-24 15:08
@Mugen87 Ah, thanks for pointing that out.
Is there a plan to move Node-functionality into the core features, in a foreseeable future?

**Comment by Mugen87** [comment] 2021-02-24 15:21
The new `WebGPURenderer` is using node materials by default. However, there is no roadmap for `WebGLRenderer` and the core. Node material was considered to be experimental for a long time. Now, the project tries to makes the integration more mature. The next step for this is #21117 which changes the way how node materials will be integrated into the renderer. If this solved, there might be a solution for your issue by enabling `MaterialLoader` to handle custom materials, see #21265.

**Comment by emilwidlund** [comment] 2021-02-25 14:18
@Mugen87 Thanks for clarifying. I managed to get an alternative workflow up and running using the NodeMaterialLoader.
However, TypeScript definitions for NodeMaterialLoader seem to be missing. Let me know if you want me to track that separately.

**Comment by Mugen87** [comment] 2021-02-25 14:21
It would be great if you could contribute them. 

BTW: `d.ts` files are managed at `three-ts-types`. Indeed, it seems the declaration for the loader is missing.

https://github.com/three-types/three-ts-types/tree/master/types/three/examples/jsm/loaders

**Comment by Mugen87** [comment] 2021-02-28 12:33
Merging this issue into #16440.

**Closed by Mugen87** 2021-02-28 12:33 UTC
Labels: Enhancement
