### ISSUE TITLE
CSS2DObject - potential rendering issue in Safari MacOS

### ISSUE THREAD

**Issue by simondate** [mrdoob/three.js#21415] opened 2021-03-05 14:38 UTC
**Describe the bug**

Our team has used Three.JS to create a Virtual Tour content type that allows content authors to create interactions which enables the user to navigate around a scene, click on interactions and change to different scenes.

We've recently updated our this content type to work with labels which are 2d objects. However after testing in Safari we started to notice that lines would be drawn all over the scene from our labels. These lines go away when you hover over a label again however they keep on coming back and look quite distracting for a user.

**Potential fix**

I found that by using whole numbers, rather than decimal numbers, for the pixel position of the buttons (which the labels that cause the issue are a child of). This would be done by adding `Math.round` [twice on this line](https://github.com/mrdoob/three.js/blob/a543c8170cdaa32b635be97bec59fe2db76cdc78/examples/js/renderers/CSS2DRenderer.js#L96). I've made the change on [our fork ](https://github.com/h5p/h5p-three-js/blob/release/three.min.js#L1398)of the Three.JS library and it has has issue has been gone since.

I was wondering if anyone had noticed any issue like this and if this fix is valid? Or if it's instead caused by another change we made somewhere. 

***Code***

https://github.com/h5p/h5p-three-image/tree/release
https://github.com/h5p/h5p-three-js
https://github.com/h5p/h5p-three-sixty/tree/release

***Demo***

https://staging.h5p.org/node/622030

**Screenshot and video**

https://www.screencast.com/t/1J7ZjSWc

![Screenshot 2021-03-05 at 14 06 20](https://user-images.githubusercontent.com/1676635/110128427-0f160f80-7dc7-11eb-8e9e-52f975c53bfe.png)

**Platform:**

 - Device: [Desktop]
 - OS: [MacOS]
 - Browser: [Safari]
 - Three.js version: [Not sure, but was updated Feb 2019]

**Comment by mrdoob** [comment] 2021-03-05 14:50
Seems like Safari invalidation code is buggy...

I'm curious to see what the side effects of adding this workaround are. Could you do a Pull Request with the change?

**Comment by Mugen87** [comment] 2021-03-05 14:58
Maybe https://bugs.webkit.org/show_bug.cgi?id=215590?

In this case the issue is a duplicate of #19854?

**Comment by Mugen87** [comment] 2021-03-05 15:12
It still seems that the problem with Safari is caused by the same issue. Meaning Safari is rounding during the translation step, see https://github.com/mrdoob/three.js/pull/20069#issuecomment-674271161.

**Comment by mrdoob** [comment] 2021-03-05 15:18
I don't think it's the same issue.
I think #20069 is about WebKit rounding numbers internally.
This issue is about WebKit not invalidating the drawn area correctly so it leaves trails.
Chrome used to have this issue years ago.

**Comment by simondate** [comment] 2021-03-12 11:09
@elalish I can't replicate in your demo either.

I'm not entirely sure if the fact it's a scene being rotated instead of an object that is being viewed that would make a difference?

**Closed** 2021-03-18 14:22 UTC
Labels: Browser Issue

**Comment by r00ster91** [comment] 2022-02-24 20:48
Apologies if I'm missing something but shouldn't this branch be removed now that this issue linked in the comment in this branch is fixed?
https://github.com/mrdoob/three.js/blob/ba4b34cd5969168be450c094c33d58559454c2a9/examples/jsm/renderers/CSS2DRenderer.js#L128

**Comment by mrdoob** [comment] 2022-02-24 21:46
Where does it say it has been fixed?

**Comment by native1989** [comment] 2022-04-29 05:00
This fix creates a new problem, now labels is shaking in safary :(

**Comment by mrdoob** [comment] 2022-04-30 02:54
@native1989 can you share a screen recording?

**Comment by fanciful-marmot** [comment] 2022-05-17 22:30
@mrdoob

Close up video of jitter from rounding on Safari: 

https://user-images.githubusercontent.com/3170456/168922570-f6544631-9fa5-440f-99be-ad4bbfe5acbc.mov

Comparison on Chrome:

https://user-images.githubusercontent.com/3170456/168922597-45d9e65e-4bde-4765-aad8-1730b5e6df7b.mov

Here's the codesandbox used in the videos: https://codesandbox.io/s/exciting-lederberg-f0uu78?file=/src/index.js

The red square is rendered with CSS2DRenderer

**Comment by mrdoob** [comment] 2022-05-19 04:56
> I'd be happy to open a PR removing the rounding if it's not needed any more

Yeah, lets try removing it 👍
