### ISSUE TITLE
Spot & Directional targets are redundant

### ISSUE THREAD

**Issue by QuaziKb** [mrdoob/three.js#5870] opened 2015-01-07 22:02 UTC
why do spot and directional lights have a particular object they point towards at all times, instead of use their own transform? It's strange that spot and directional lights use Object3D, yet their rotation is completely useless, and they opt instead to have an extra positioned object. If the goal was to make positioning / pointing the lights simpler, it didn't really work, since Object3D can already easily point towards a position using lookAt. 

This is not truly an issue, but weird from an api standpoint, and makes adding a spotlight as something like a headlight extra annoying. Of course there are probably workarounds like adding the target to the light object but it just always seemed strange, and more complex than it could ever make something simpler.

**Comment by WestLangley** [comment] 2015-01-08 00:27
For reference, and some history on this issue, see: #2251, #3497, #4261, #5079, and #5555.

**Comment by mrdoob** [comment] 2015-01-08 09:26
Totally agreed. We're in the process of removing those targets.
I think @gero3 tried some time ago but the PR was unfinished.

**Comment by looeee** [comment] 2016-12-15 21:31
@mrdoob is there still an intention to remove these targets?

In the meantime information on how they currently work has been added to the docs.

**Comment by mrdoob** [comment] 2016-12-16 01:55
> @mrdoob is there still an intention to remove these targets?

Yep!

**Comment by donmccurdy** [comment] 2018-08-04 20:51
Closing as duplicate of https://github.com/mrdoob/three.js/issues/5079.

**Closed by donmccurdy** 2018-08-04 20:51 UTC
Labels: Suggestion
