### ISSUE TITLE
Some areas of meshes does not move with corresponding bones when using GLTF 

### ISSUE THREAD

**Issue by skalexey** [mrdoob/three.js#10549] opened 2017-01-10 10:01 UTC
##### Description of the problem 
I have a 3D model exported from Blender to Collada and then converted to GLTF using collada2gltf converter. I have already fully described the problem here:
[https://github.com/KhronosGroup/COLLADA2GLTF/issues/13](https://github.com/KhronosGroup/COLLADA2GLTF/issues/13)
Please, read this at first.
As figured out this is a problem somewhere in Three.js. May be in GLTF Loader, may be in GLTF Shader or somewhere else.
The problem is that vertices of some areas on mesh are not properly bound to corresponding
 bones.
##### Three.js version
- [x] r76

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by takahirox** [comment] 2017-01-12 16:16
Does this problem still occur on the latest revision r84 dev?

**Comment by skalexey** [comment] 2017-01-25 15:40
Yes. The problem is still occur in revision 84dev. 
[gltf_three_js_84dev_bugreport.mov.zip](https://github.com/mrdoob/three.js/files/730128/gltf_three_js_84dev_bugreport.mov.zip)
You can see how it works in the attached zipped .mov file. The mesh behaves differ than in the corresponding .dae file.

**Comment by donmccurdy** [comment] 2017-01-26 01:16
There could be more going on, but most of the problem is #10366. Several KeyframeTrack instances are failing to validate because of '.' characters in the node names. Example track name: `ICE.010.position`. More discussion in that bug.

**Comment by takahirox** [comment] 2017-01-26 20:06
Hm, it looks that the gun position should correspond to the guy's right hand's/back's(before he hands it) but it doesn't...

**Comment by takahirox** [comment] 2017-01-27 08:50
Does this model work on other libraries?

I doubt if the conversion from Collada to glTF has done correctly
because Armature_GUN_pose_matrix-output-array parameter in glTF looks weird...

On .dae the translation value of that parameter changes
while the value won't cahnge on .gltf

**Comment by skalexey** [comment] 2017-01-27 17:21
I have not tried to use another libraries, but collada2gltf team have:
https://github.com/KhronosGroup/COLLADA2GLTF/issues/13
Now it looks more like in JglTF and Cesium in the related issue.
Thanks a lot to donmccurdy for the explanation of the problem. I have replaced dots by slashes in names of all bones in blender project of the model and got the result maximally close to expectations:
[gltf_shooter_in_three_js_r84dev.mov.zip](https://github.com/mrdoob/three.js/files/735844/gltf_shooter_in_three_js_r84dev.mov.zip)

**Comment by takahirox** [comment] 2017-01-27 18:33
Well, you mean replacing dots with slashes in the original project have fixed the gun transformation issue?
I (and probably @donmccurdy) edited them directly in .gltf but the gun transformation issue wasn't fixed.

So, it means the transformation issue was caused by converter, not Three.js?

**Comment by donmccurdy** [comment] 2017-01-27 18:39
Cool. I think the converter got something wrong in the texture as well, at least when I ran it.

We'll be fixing #10366 in any case, that issue keeps coming up. I worked around this by trying one (of several) fixes for that issue rather than editing the file, but finding the right fix for that is a bit harder.

**Comment by skalexey** [comment] 2017-01-27 19:28
Underscores. Sorry). Yes. It looks like the problem of the gun is caused by collada2gltf. What about texture - it is composed of two problems: firstly Blender put old texture to .dae file after exportation which is already removed from the project and secondly - collada2gltf set that old texture as a texture by default.

**Comment by donmccurdy** [comment] 2017-06-23 03:53
I believe this is now fixed. Importing your COLLADA file into Blender and exporting with the [glTF-Blender-Exporter](https://github.com/KhronosGroup/glTF-Blender-Exporter/), I get a correctly-animated result:

![d0a1932b-29c5-4ebc-adf5-af6960327639-37566-00008676735b272d](https://user-images.githubusercontent.com/1848368/27466068-afd4d268-578c-11e7-89fa-1d72d25c2362.gif)

Note that the materials may take some tuning in Blender... there are particular material settings that the exporter needs.

**Closed** 2017-06-27 00:46 UTC
