### ISSUE TITLE
SVGRenderer does not call onBeforeRender/onAfterRender

### ISSUE THREAD

**Issue by rishihahs** [mrdoob/three.js#17897] opened 2019-11-08 21:28 UTC
##### Description of the problem

`Object3D.onAfterRender` and `Object3d.onBeforeRender` is correctly called upon by [WebGLRenderer](https://github.com/mrdoob/three.js/blob/dev/src/renderers/WebGLRenderer.js#L1159) but *not* by [SVGRenderer](https://github.com/mrdoob/three.js/blob/dev/examples/jsm/renderers/SVGRenderer.js).

##### Three.js version

- [x] Dev
- [ ] r110
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by mrdoob** [comment] 2019-11-08 21:35
What's your use case?

**Comment by rishihahs** [comment] 2019-11-08 23:40
I'd like a way to be notified in an animation when an object pops into view. This functionality is given by `onAfterRender` when using a WebGLRenderer. However, it would also be nice to have it in SVGRenderer which I use when webgl is not available (e.g. in jsdom).

**Comment by Mugen87** [comment] 2020-02-20 14:09
After `Object3D.onAfterRender` and `Object3d.onBeforeRender` was added to the CSS renderers, I've had a look at the source code of `SVGRenderer`. Unlike the other renderers, `SVGRenderer` does not render the scene object by object. Instead, it uses `Projector` to produce an array of renderable elements (`THREE.RenderableSprite`, `THREE.RenderableLine` and `THREE.RenderableFace`). The problem is that the order of elements is not the same as the order of objects. Meaning it's not possible to trigger `Object3D.onAfterRender` and `Object3d.onBeforeRender` like in the other renderers. 

Well, it is possible to call `Object3d.onBeforeRender` for all renderable objects, then perform the rendering of all renderable elements and finally call `Object3D.onAfterRender` for all objects. However, the timing when the callbacks are executed is now different compared to other renderers. The code would look like so:

```js
for ( var r = 0, rl = _renderableObjects.length; r < rl; r ++ ) {

	var object = _renderableObjects[ r ].object;
	object.onBeforeRender( _this, scene, camera );

}

// render elements (code not posted)

for ( var r = 0, rl = _renderableObjects.length; r < rl; r ++ ) {

	var object = _renderableObjects[ r ].object;
	object.onAfterRender( _this, scene, camera );

}
```
If this code is acceptable I can make a PR with the change.

**Comment by mrdoob** [comment] 2020-02-21 00:43
> Unlike the other renderers, `SVGRenderer` does not render the scene object by object. Instead, it uses `Projector` to produce an array of renderable elements (`THREE.RenderableSprite`, `THREE.RenderableLine` and `THREE.RenderableFace`). 

True! Forgot about that.... I'm inclined to go with `Won't fix` on this one...

**Comment by Mugen87** [comment] 2020-02-22 13:09
> I'm inclined to go with Won't fix on this one.

I vote for doing this since I can't see a way to properly implement this feature request.

**Closed** 2020-02-22 17:36 UTC
Labels: Feature Request
