### ISSUE TITLE
Feature request: Parameters checks and Validation

### ISSUE THREAD

**Issue by Itee** [mrdoob/three.js#12578] opened 2017-11-04 23:39 UTC
Next to #12231 and #12574 part 3

The main idea is to check if parameters are valid in ctor, setters and public methods in development environment. This will allow a big benefits during dev and will make a safer library. All asserts could be easily removed when building for production using: [rollup-plugin-strip](https://github.com/rollup/rollup-plugin-strip)

The assert could use a Validator like in ObjLoader2 for common validation like: isString, isArray, isMatrix4 etc...

An example:

```javascript
getWorldPosition: function ( target ) {

        assert( target !== undefined, 'THREE.Matrix4.getWorldPosition: Missing required target.' );
        assert( Validator.isVector3( target ), 'THREE.Matrix4.getWorldPosition: Invalid argument, expected THREE.Vector3.' );

	this.updateMatrixWorld( true );

	return target.setFromMatrixPosition( this.matrixWorld );

},
```

**Comment by Itee** [comment] 2017-11-12 01:04
/ping @mrdoob So what is your opinion ?

**Comment by mrdoob** [comment] 2017-11-22 10:49
If we start doing this, it'll be difficult to know where to draw the line of what to check and what not. This is basically fighting against JavaScript. I would rather move to TypeScript than going down this path...

**Comment by Itee** [comment] 2017-12-21 09:48
I not agree with that: 

> This is basically fighting against JavaScript

 because currently it is: 

> Fighting against Three because i don't know what and where it is wrong in my code. And the error i got is completely out of place. (Ex: The "position" attribute is likely to have NaN values.)

Lot of the biggest libraries in JavaScript already use this type of assert in development environment to help their developers. If the biggest think it's a good solution maybe it's a good solution ?

And i know your aversion about TypeScript so...

**What can we propose to the developers to help them to know what mistake they do, and prevent them to search during hours an error that could easily be catch with a simply assert against parameters ?**

I see 3-4 options:

- Add asserts like i propose, with good performance in dev, a performance gain in prod, based on a contract about which could be like null, undefined and the type.
- Use TypeScript
- Use Flow
- Do nothing and continue in this wrong way

So please, tell me what can we do ? Have you a better solution about this concern ?

**Comment by looeee** [comment] 2017-12-21 10:16
@Itee there is a third path: expect developers to learn how to debug their code properly.

This is a vital skill and not actually that hard. Even using the most basic technique of following through the flow of your code and putting in console or debug statements will quickly lead you to the source of the error, then you can see for example that you are passing in the wrong argument to a function, or  that NaN values are being generated and passed as position attributes at this point.

Of your your options:

* asserts: if this was done all over the library it would be a considerable increase in code size and complexity and I think probably a performance drop too. Are you aware of any other large JS libraries that use this approach?
* Typescript: I don't really have any strong opinion here, except that it would make three.js less accessible for non TS developers, which is most of the JS community
* Flow: This is non-trivial to set up and puts an nonviable expectation on the development environment that people use 
* Do nothing and continue in this ~wrong~ way, expecting people to learn how to debug their code properly 

The last one seems reasonable to me at least - although I think it should be combined with a strong effort to keep the documentation clear and up to date.

**Comment by Itee** [comment] 2017-12-21 11:25
@looeee It's a beautiful dream ! 😄

About:

- TypeScript: i totally agree with you
- Flow: totally agree too
- People to learn how to debug: a nice dream
- asserts: If we had a simple assert for all arguments all over the library it will increase the size by maybe 1000-2000 lines (not so big, and only in dev) ? The complexity... I'm not really sure that add an assert will increase the complexity of the code, on the contrary it will clarify the intent, will allow to prove that the function do exactly what it should do using unit test with, and help the dev to understand what is his mistake !

Finally,

> Even using the most basic technique of following through the flow of your code and putting in console or debug statements will quickly lead you to the source of the error

Debug with console is totally insane and time consumer ! Using the debug tool with breakpoints is better, but can take a while, and/or just be unable to use in case of unreproductible/random bug. **Instead of got immediately why and where it's broken ???** 
At last, using assert will allow to catch tone of bug that are currently in the library but hidden (IMO: I talk about experience when upgrading base code with this type of protect pattern who raised a ton of bugs. )

Check user input on the public interfaces is not a good practice, but a need !

**Comment by looeee** [comment] 2017-12-21 13:13
OK, although I'm wondering now why you are suggesting options that you don't agree with. 

Regarding asserts, as I asked above, do you know whether any other large JS libraries use this technique to validate parameters?

**Comment by Itee** [comment] 2017-12-21 14:38
If you want specifically about assert i don't really know, but about parameters check almost all ?!? With their own implementation using personal logger, throwing error, what ever they need to do the job !

- npm
- bower
- react
- blocky
- closure-library
- etc...

Ok before go further in the discussion, did you read this #12231 ?

Next, i will clarify some points. 

> why you are suggesting options that you don't agree with.

I agree with this options (except the last of course 😄), but they have pro/con like you list it previously.
TypeScript or Flow allows to check if parameters are correct in a certain way ! And will avoid some headache during development.

The assert part is IMO most powerful than the others, because it will provide a very fast feedback about what is the problem. Require very few characters to be useful. Can be deleted easily in production using rollup-plugin-strip.

My goal is (like i said in first place):

> The main idea is to check if parameters are valid in ctor, setters and public methods in development environment. This will allow a big benefits during dev and will make a safer library.

The method to do it, is the question. I think assert or equivalent javascript check using a Validator are the best to do. But any options that do the job is ok for me ! 

**But currently i want to know which option we will use to do that !** To apply it on future code refactoring.

I hope i'm clear 😟 It's not really easy to me to explain some abstract meaning due to my poor vocabulary in English, or bad sentences construction...

For example when i'm talking about asserts, it is more like any javascript line code that allow to check parameters validity and tell what's wrong to the user.

the 

```javascript
assert( target !== undefined, 'THREE.Matrix4.getWorldPosition: Missing required target.' )
```

was just an example taken from #12231

**Comment by looeee** [comment] 2017-12-21 15:29
> Ok before go further in the discussion, did you read this #12231 ?

Yes, I've read over that thread. I would say it's very far from conclusive that this won't have a large performance impact based on that thread. At the very least we would need to make certain of that before going further with this.

>If you want specifically about assert i don't really know, but about parameters check almost all ?!?

Can you provide some specific examples? I just had a (very quick) look through the source of a couple of libraries (lodash, jQuery ) and it looks to me like they take very similar to what we do here - that is, set up default values where neccessary, but otherwise assume that the correct type of object is being passed in, except for a few cases where they are using "typeof" and sending a message to the console if it's the type of incorrect.

**Comment by Itee** [comment] 2017-12-21 15:59
The performance impact will only appear on development, and if disable it will just cost a boolean check. Which have not really impact. In case you're in debug mode the impact is acceptable due to the state, aka development.

About examples:

1. npm:
   - [adduser](https://github.com/npm/npm/blob/latest/lib/adduser.js)
2. bower:
   - [home](https://github.com/bower/bower/blob/master/lib/commands/home.js)
   - [update](https://github.com/bower/bower/blob/master/lib/commands/update.js)
3. jQuery:
   - [data](https://github.com/jquery/jquery/blob/master/src/data.js)
4. lodash:
   - [createPadding](https://github.com/lodash/lodash/blob/master/.internal/createPadding.js) - With additional doc for IDE !

I just picked up some file randomly and find params check every where. Not for all of course because it will required a more deep reading of this library. But you can be sure that all their inputs are check somewhere and could be afterware use in a safe way !

**Comment by mrdoob** [comment] 2017-12-21 18:38
> The performance impact will only appear on development

So we can't expect people to learn how to debug but we can people to know how to develop in debug mode and release mode? 🤔

> I just picked up some file randomly and find params check everywhere.

You should compare this with other graphics-related libraries. The ones you picked are not so focused on performance.

**Comment by Itee** [comment] 2017-12-21 18:51
> So we can't expect people to learn how to debug but we can people to know how to develop in debug mode and release mode?

Toggling a Boolean value in constant file for example is (i hope) much easier for a beginner than run through chrome debug tool in a new and unknown big library like three ? About the debug learning... Catching error early against wrong params will, on the contrary, help a lot beginner to understand what happen in the code base, and what they do wrong, no ? That allow them to become better quickly.

> You should compare this with other graphics-related libraries. The ones you picked are not so focused on performance.

I think there is something that i don't fully understand here... 

What is the problem to make a relative ( to define, but tiny ) performance impact in development environment under debug mode on, and virtually no impact when off. And absolutely no impact in production environment ???

lodash i think is about performance ( but not graphical of course ).

**Comment by mrdoob** [comment] 2017-12-22 01:18
> Toggling a Boolean value in constant file 

But that assumes the user is using a build system. An easier approach would be to have more builds... three.release.min.js, three.debug.min.js, ... But, either way, I guarantee you that tons of people will publish the debug version.

> What is the problem to make a relative ( to define, but tiny ) performance impact in development environment under debug mode on, and virtually no impact when off. And absolutely no impact in production environment ???

The problem I have is forcing users to node/webpack/build... development workflows. I understand the benefits, but I also understand that it makes the experience less fun. It is important for me to keep the experience fun.

**Comment by looeee** [comment] 2017-12-22 02:22
Going over your examples:

### lodash.createPadding

This example is not doing type checking - it takes 2 arguments, `length` and `chars`. 

If you fail to enter `length` it will crash and burn by the look of it - certainly if you enter a string or NaN or something instead of a number you'll get weird results. 
Iif you fail to enter `chars` then it gets set to a default value, which is something we already do in most cases here. 

## jQuery.data

```js
function getData( data ) {
	if ( data === "true" ) {
		return true;
	}

	if ( data === "false" ) {
		return false;
	}

	if ( data === "null" ) {
		return null;
	}

	// Only convert to a number if it doesn't change the string
	if ( data === +data + "" ) {
		return +data;
	}

	if ( rbrace.test( data ) ) {
		return JSON.parse( data );
	}

	return data;
}
```

There's no parameter checking here either - if you enter anything other than a string it's just going to get returned to you unchanged, which is probably going to cause weird errors if that's not what you expect. 

NPM and Bower are not really relevant here since they are intended to be run on your local PC or server and don't have to worry about performance to the same degree. 

I would agree with @mrdoob that only other libraries focused on performance to the same degree as three.js are relevant here. Although I think lodash is a good example, and it looks like it doesn't do any more checking than we do.

**Comment by looeee** [comment] 2017-12-22 12:24
Holy wall of text, batman! 

Do you really expect people to read all of that? 

But focusing on your response to my point above:

>Maybe i don't take best examples, but the idea is they check user inputs

In your examples, they _don't_ validate function parameters.

**Comment by Itee** [comment] 2017-12-22 12:50
I hope they will ! Because i explain lot of things about this concern. And personally i take the time to read some block of text when the topic is interesting. But i can split this response in 4-5 comment more digest, but the size will be the same.

> they don't validate function parameters.

So, they should ! 😄

But to the contrary, why should we not validate function parameters ? What are the gain ?

**Comment by looeee** [comment] 2017-12-22 13:38
> I hope they will 

The problem is, that no matter how much you hope, they really won't. Personally I got to the story about Johnny web developer and his divorced wife and gave up. 

But anyway, back on topic:

This would be quite a major change to the library, and I'm not convinced that it's neccessary - especially since, from the examples of other libraries we have seen so far, the level and type of validation we are currently doing seems pretty standard in JavaScript. 

But if we do go ahead, we'd need to make sure at least

* that this doesn't favour any particular way of using the library - nothing specific to node, webpack, rollup, including via script tags or imports statements or anything else (so no `NODE.env` or other environment variables). 
* must be beginner friendly
* minimal performance impact in dev 
* very close to zero impact in production
* minimal impact on code complexity

The only way I see to satisfy all of these would be to add an extra build target `three.debug.js` - and I don't think it's unreasonable to expect people to switch to `three.min.js` in production. I'm not sure how this would work for people that are using build tools though.

**Comment by Itee** [comment] 2017-12-22 14:51
Under tl;nr is just extra stuff that is not 'required'. And i rarely make so big text in fact because it take lot of time to me. I will be more concise now. But thank for reading !

> This would be quite a major change to the library

Yes

> I'm not convinced that it's neccessary

I am, but the real gain will come after the implementation.

> currently doing seems pretty standard in JavaScript

We can do better than standard

> that this doesn't favour any particular way of using the library - nothing specific to node, webpack, rollup

Thank to point this, you're totally right ! I will think about a non specific way to achieve this.

> must be beginner friendly

That the purpose ! To help beginner to debug easily their code in fast and lighter way than currently.

> minimal performance impact in dev

Need a benchmark, but should be minimal this cost just an boolean check per methods under dev when debug off.

> very close to zero impact in production

It is not very close, it is zero impact due to the removal of the code line during bundling using rollup-plugin-strip (if we go this way)

> minimal impact on code complexity

This will improve code readability ! In that way you will be able to know which type of the param should be, and you will be sure that you cannot get crappy undefined or null values ( if the param is required of course ! )

> an extra build target three.debug.js

Why ? What is the purpose of three.js and three.min.js if it is not for dev (aka debug) and prod env ??? For fun ?

> I don't think it's unreasonable to expect people to switch to three.min.js in production

This is the only goal of this file, no ?

> I'm not sure how this would work for people that are using build tools though.

What do you mean by build tools ? Rollup or webpack ? In this case see tl;nr section above.

**Comment by Mugen87** [comment] 2018-02-17 09:47
I agree with @mrdoob and @looeee . I suggest to close this issue and focus on other topics instead.

**Closed** 2018-02-17 17:24 UTC
