### ISSUE TITLE
Even when disabled, orbitcontroller.update() performs its calculation

### ISSUE THREAD

**Issue by optimus007** [mrdoob/three.js#22845] opened 2021-11-16 13:04 UTC
**Describe the bug**

i have orbitcontroller.update() in the animate loop for damping 
and
after doing orbitcontroller.enabled=false , i still cant tilt the camera,

my guess is , the update logic to prevent the camera from tilting /going upside down is still running
**Expected behavior**
maybe in the update function when orbitcontroller.enabled=false , return early ?

https://github.com/mrdoob/three.js/blob/0d7fb8d74f3c4d4e465b5a92ada65e1c789708e1/examples/jsm/controls/OrbitControls.js#L154

**Platform:**

 - Device: [Desktop, Mobile]
 - OS: [Windows]
 - Browser: [Chrome]
 - Three.js version: [dev]

**Comment by Mugen87** [comment] 2021-11-16 13:24
Duplicate of #19917.

**Comment by Mugen87** [comment] 2021-11-16 13:24
@optimus007 Please search for existing issues and PRs before opening a new discussion. This is not the first time you have filed a duplicate.

**Closed by Mugen87** 2021-11-16 13:24 UTC

**Comment by optimus007** [comment] 2021-11-16 14:04
oh shizz! , my bad , was searching only the open issues .

To anyone who faces this problem, 
one easy solution is removing and adding the `orbitcontroller.update()` function call from the render loop dynamically using another function 

```

//when ON
let updateOrbit=()=>{
    orbitcontroller.update()
}


//when off
let updateOrbit=()=>{
    //empty
}


//in the animate loop
animate(){
    updateOrbit()
    ....do other stuff
}
```
