### ISSUE TITLE
CSS3DRenderer projection matrix bug in Chrome for Windows

### ISSUE THREAD

**Issue by jocabola** [mrdoob/three.js#20392] opened 2020-09-22 09:56 UTC
**Since latest two updates of Chrome, CSS 3D rendering has several clipping and rendering issues**

We realized that a project were we have a CSS 3D renderer synchronized with a WebGL one started rendering wrongly in Chrome since latest browser updates.  We can't share link at this point but the issue also happens with [this page](http://jeromeetienne.github.io/videobrowser4learningthreejs/).

**To Reproduce**

This is happening to me on Windows currently in Version 85.0.4183.121 (Official Build) (64-bit) but with the one before that as well.It didn't happen back in August with an earlier version.

1. Go to [http://jeromeetienne.github.io/videobrowser4learningthreejs/](http://jeromeetienne.github.io/videobrowser4learningthreejs/)
2. You should see an iFrame matching the TV screen in the 3D WebGL scene
3. Instead you will see the pink background. Try resizing window sometimes you might see parts of the iFrame.

If you use the inspector, you'll see that the iFrame is correctly placed but it is not rendering as if it would be clipped (you see the background instead). Changing the overflow of the renderer's dom element to `visible` doesn't fix the issue.

***Live example***

* [http://jeromeetienne.github.io/videobrowser4learningthreejs/](http://jeromeetienne.github.io/videobrowser4learningthreejs/)

**Expected behavior**

![image](https://user-images.githubusercontent.com/124143/93867157-f1496800-fcc8-11ea-94db-a1c95c02b9e2.png)

**Wrong Behaviour**

![image](https://user-images.githubusercontent.com/124143/93867222-0625fb80-fcc9-11ea-89d0-1e13adde73a8.png)

**Platform:**

 - Device: Desktop
 - OS: Windows 
- Browser: Chrome Version 85.0.4183.121
 - Three.js version: That example showed here runs on top of a very old version of threeJS but is happening to us with latest r120. We believe it could be a browser bug.

**Comment by Mugen87** [comment] 2020-09-22 10:02
Three is already a Chromium issue for this:

https://bugs.chromium.org/p/chromium/issues/detail?id=1128636

**Comment by Mugen87** [comment] 2020-09-22 11:12
@jocabola Consider to star the issue at `bugs.chromium.org` to raise its priority.

**Comment by jocabola** [comment] 2020-09-22 12:09
Done @Mugen87 Thank you!

**Comment by Mugen87** [comment] 2020-10-13 20:47
The issue is fixed now and will be available with Chrome 87.

**Closed by Mugen87** 2020-10-13 20:47 UTC
Labels: Browser Issue
