### ISSUE TITLE
Hide `THREE.WebGLRenderer 84` console log

### ISSUE THREAD

**Issue by elliott-impression** [mrdoob/three.js#15337] opened 2018-11-28 11:44 UTC
Hello,

I've came to notice that I have the following console log:
`THREE.WebGLRenderer 84`

I haven't found any issues, however, it is mandatory that this specific site does not have any console logs.

Is it possible to hide/disable this log?

I've noticed other issues where people have had the same log (suggesting the log is related to Chrome or graphics cards), although I haven't seen any solutions.

Thank you.

**Comment by Mugen87** [comment] 2018-11-28 12:04
Duplicate of #5835

**Closed by Mugen87** 2018-11-28 12:04 UTC

**Comment by WestLangley** [comment] 2018-11-28 16:03
@elliott-impression `r.84` is nearly 2 years old. I suggest you upgrade to the current release.
