### ISSUE TITLE
InstancedMesh with multiple materials looks broken

### ISSUE THREAD

**Issue by dm-gh** [mrdoob/three.js#20882] opened 2020-12-11 15:29 UTC
**Describe the bug**

InstancedMesh with simple geometry and multiple materials doesn't render correctly

This is probably hardware specific or OS specific issue, because it is reproducible on my macOS machine, but not on my Windows machine   

**To Reproduce**

1. Create InstancedMesh with BoxGeometry and an array of MeshBasicMaterial
2. Render
3. See weird behavior

or alternatively check live example

***Code***

```js
    const materialA = new THREE.MeshBasicMaterial({ color: 0x0000ff });
    const materialB = new THREE.MeshBasicMaterial({ color: 0xff0000 });
    const boxG = new THREE.BoxGeometry(10, 10, 10);
    boxG.faces.forEach((face, i) => {
      face.materialIndex = i % 2;
    });

    const mesh = new THREE.InstancedMesh(boxG, [materialA, materialB], 1);
    const dummy = new THREE.Object3D();
    dummy.position.set(-20, 0, -20);
    dummy.updateMatrix();
    mesh.setMatrixAt(0, dummy.matrix);
    mesh.instanceMatrix.needUpdate = true;
    scene.add(mesh);
```

***Live example***

https://jsfiddle.net/khjownq1/4/

**Expected behavior**

Code from *Code* section should produce a box with red and blue faces

**Screenshots**

initial position of camera
<img width="561" alt="Screenshot 2020-12-11 at 16 01 41" src="https://user-images.githubusercontent.com/36445024/101920201-94c95b00-3bdc-11eb-8b61-3f29b0856165.png">

when rotated there is some weirdness
<img width="575" alt="Screenshot 2020-12-11 at 18 11 37" src="https://user-images.githubusercontent.com/36445024/101920228-9c88ff80-3bdc-11eb-8941-60a819a6c4ae.png">

gif with scene rotation
![Screen Recording 2020-12-11 at 17 49 43](https://user-images.githubusercontent.com/36445024/101921209-cabb0f00-3bdd-11eb-810b-1e9d28ff6b8d.gif)

**Platform:**

 - Device: Desktop
MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)
Processor 2,3 GHz Dual-Core Intel Core i5
Memory 8 GB 2133 MHz LPDDR3
Graphics Intel Iris Plus Graphics 640 1536 MB
 - OS: MacOS Catalina version 10.15.6
 - Browser: 
Google Chrome Version 87.0.4280.88
Firefox 82.0.3 (64-bit)
Safari Version 14.0
(identical behavior)
 - Three.js version: r123

**Note:**
It works as expected on Windows machine
- Device: Desktop
 - OS: Windows 10 64-bit
 - Browser: Google Chrome Version 87.0.4280.88
 - Three.js version: r123

screenshot of expected behavior
![Capture](https://user-images.githubusercontent.com/36445024/101921775-6b113380-3bde-11eb-89fa-a25f6efb9f13.PNG)

**Comment by Mugen87** [comment] 2020-12-11 17:17
> It works as expected on Windows machine

Indeed. I can't reproduce this on my Windows 10 notebook. I'll try it tomorrow on my iMac.

**Comment by Mugen87** [comment] 2020-12-11 17:19
It's actually a duplicate of #17223.

**Closed by Mugen87** 2020-12-11 17:19 UTC

**Comment by mrdoob** [comment] 2020-12-21 22:24
I don't think we can add multi-material support to `InstancedMesh`. Probably better to update docs and d.ts to clarify.

**Comment by Mugen87** [comment] 2020-12-22 10:15
Um, i guess it would be necessary to revert #19502 then which probably brings TS compilation errors back.

>  don't think we can add multi-material support to InstancedMesh.

https://github.com/mrdoob/three.js/issues/19500#issuecomment-636311754

**Comment by mrdoob** [comment] 2020-12-22 10:37
It does work? Surprising... 😅
