### ISSUE TITLE
Three.js doesn't support SVG with url

### ISSUE THREAD

**Issue by ZhangGuangXin** [mrdoob/three.js#28732] opened 2024-06-24 08:30 UTC
### Description

I use SVGLoader to load a SVG data, three.js output message: SVGLoader: url access in attributes is not implemented. 
The SVG contains content: fill="url(#gridpattern)"

### Reproduction steps

I use the usage in SVGLoader document

### Code

    private svgTest() {
        // instantiate a loader
        const loader = new SVGLoader();
        let self = this;
        // load a SVG resource
        loader.load(
            'http://localhost:9000/examples/resources/svg/method-draw-image.svg',
            // called when the resource is loaded
            function (data) {

                const paths = data.paths;
                const group = new Group();
                let svgPoint = new Point(121.97978, 40.75601, 0, Const.EPSGType.EPSG84).toEPSGWeb();
                group.position.copy(svgPoint);

                for (let i = 0; i < paths.length; i++) {

                    const path = paths[i];

                    const material = new MeshBasicMaterial({
                        color: path.color,
                        side: DoubleSide,
                        depthWrite: false
                    });

                    const shapes = SVGLoader.createShapes(path);
                    for (let j = 0; j < shapes.length; j++) {

                        const shape = shapes[j];
                        const geometry = new ShapeGeometry(shape);
                        const mesh = new Mesh(geometry, material);
                        group.add(mesh);

                    }

                }

                let scene = self.app.three.scene;
                scene.add(group);

            },
            // called when loading is in progresses
            function (xhr) {

                console.log((xhr.loaded / xhr.total * 100) + '% loaded');

            },
            // called when loading has errors
            function (error) {

                console.log('An error happened');

            }
        );
    }

### Version

r165

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by Mugen87** [comment] 2024-06-24 11:22
Duplicate of #21330-

**Closed by Mugen87** 2024-06-24 11:22 UTC
