### ISSUE TITLE
Water Example Doesn't Render in Chrome on macOS

### ISSUE THREAD

**Issue by jak2030** [mrdoob/three.js#16041] opened 2019-03-22 18:18 UTC
##### Description of the problem

No errors or warnings in the console (some discrepancy in the shader code for my old computer's gpu?), and no water:

<img width="1272" alt="Screen Shot 2019-03-22 at 2 16 09 PM" src="https://user-images.githubusercontent.com/1641058/54844342-11036880-4cad-11e9-92dd-7e681e55718b.png">

It renders fine in other browsers.

##### Three.js version

Viewed from the latest website examples (https://threejs.org/examples/?q=water#webgl_water)

##### Browser

Chrome, Version 73.0.3683.86 (Official Build) (64-bit)

##### OS

macOS 10.14.1

##### Hardware Requirements (graphics card, VR Device, ...)

MBP 15-inch Late 2013
GPU: Intel Iris Pro 1536 MB

**Comment by Mugen87** [comment] 2019-03-22 19:51
I'm unable to reproduce this with Chrome 73.0.3683.86 on macOS 10.14.3.

**Comment by jak2030** [comment] 2019-03-22 20:37
Every example I've checked works as expected except for `webgl_water` and `webgl_water_flowmap`,both of which use Reflector/Refractor/Water2.

FWIW, I see the same issue (missing water) on a  different computer, another MBP which runs with the same GPU (Intel Iris Pro 1536 MB) but on a different version of Chrome (Version 72.0.3626.121 (Official Build) (64-bit))

**Comment by Mugen87** [comment] 2019-03-22 20:57
Can you try to update to the latest macOS version? A system update might also update the graphics driver which could be responsible for this issue.

**Comment by jak2030** [comment] 2019-03-22 22:06
I still have the issue after updating to the latest macOS verison (10.14.3)

**Comment by Mugen87** [comment] 2019-03-23 10:28
Um, without any warnings or errors it will be hard to investigate the issue. Especially since I can't reproduce the issue on any of my devices.

**Comment by Mugen87** [comment] 2019-03-24 10:32
Can you please check if the problem still appears with Chrome Canary?

https://www.google.com/intl/en_ALL/chrome/canary/

**Comment by jak2030** [comment] 2019-03-24 21:14
Unfortunately the issue is still the same in Chrome Canary.

**Comment by mrdoob** [comment] 2019-03-26 20:34
So I guess this is an issue with `Intel Iris Pro 1536 MB`?

**Comment by jak2030** [comment] 2019-03-26 21:48
That's been my guess, but one wrinkle is that I can see the issue in Browserstack as well, using the latest Chrome and running with High Sierra. (I tried googling around but I'm not sure what Browsertack's Mac computer hardware actually runs with...):

<img width="1680" alt="Screen Shot 2019-03-26 at 5 46 10 PM" src="https://user-images.githubusercontent.com/1641058/55035719-10d9d480-4fef-11e9-8889-869503f81c27.png">

(I tried a Windows computer and an iPhone within Browserstack, both on Chrome, and both worked as expected).

**Comment by Fasani** [comment] 2019-04-01 10:14
I do not have the issue on my machine:
Chrome Version 73.0.3683.86 (Official Build) (64-bit)
Mac: Mojave 10.14.3
GPU: Intel Iris Plus Graphics 640 1536 MB

But I do have BrowserStack and can confirm I see an issue when:
Chrome 74 Dev on macOS Mojave
Chrome 74 Beta on macOS Mojave (even more issues, Black background, no wooden floor)
Chrome 73 on macOS Mojave
Chrome 72 on macOS Mojave
Chrome 71 on macOS Mojave

Chrome 74 Dev on macOS High Sierra
Chrome 74 Beta on macOS High Sierra (even more issues, Black background, no wooden floor)
Chrome 73 on macOS High Sierra
Chrome 72 on macOS High Sierra
Chrome 71 on macOS High Sierra

I do not have the issue when:
Chrome 73 on macOS Sierra
Chrome 72 on macOS Sierra
Chrome 71 on macOS Sierra
Chrome 73 on OS X El Capitan
Chrome 72 on OS X El Capitan
Chrome 71 on OS X El Capitan

No console issues or warnings in any test.

**Comment by Mugen87** [comment] 2019-04-01 10:20
@Fasani Do you see any errors or warnings in the browser console?

**Comment by Fasani** [comment] 2019-04-01 10:30
@Mugen87 No, except 404 for fav icon.

**Comment by Mugen87** [comment] 2019-04-01 12:01
I have create a free account at Browserstack and tested the macOS Mojave instance with Chrome 72 and Firefox 66. The water example does work in Firefox but not in Chrome. No errors or warnings are logged. 

However, one test of the [WebGL conformance tests](https://www.khronos.org/registry/webgl/sdk/tests/webgl-conformance-tests.html) failed at Browserstack which worked on my iMac. 

https://www.khronos.org/registry/webgl/sdk/tests/conformance/rendering/canvas-alpha-bug.html

The test cases exposes an alpha blending bug in Intel drivers on macOS. It could be responsible for the issue. Related bug: https://bugs.chromium.org/p/chromium/issues/detail?id=886970

@jak2030 Can you please verify if the mentioned test fails on your computer?

**Comment by jak2030** [comment] 2019-04-02 14:46
Yes, looks like that test fails on my computer. The output reads:

```
Exposes alpha blending bug in Intel drivers on macOS - see https://crbug.com/886970

On success, you will see a series of "PASS" messages, followed by "TEST COMPLETE".

FAIL should be 0,255,0,255
at (0, 0) expected: 0,255,0,255 was 255,0,0,255
PASS successfullyParsed is true

TEST COMPLETE
```

For reference, here are the results for the entire suite:

[webgl-conformance-1.0.4 (beta).txt](https://github.com/mrdoob/three.js/files/3034498/webgl-conformance-1.0.4.beta.txt)

**Comment by WestLangley** [comment] 2019-04-02 14:53
Resolved. Closing.

**Closed by WestLangley** 2019-04-02 14:53 UTC
Labels: Browser Issue, Device Issue

**Comment by mrdoob** [comment] 2019-04-02 19:12
FYI @kenrussell

**Comment by kenrussell** [comment] 2019-04-04 23:03
Thanks for the heads up and sorry for the difficulty. There's very little we can do about low-level graphics driver bugs such as this one.

**Comment by andremichelle** [comment] 2019-05-30 11:38
> There's very little we can do about low-level graphics driver bugs such as this one.
We got similar reports from our users at audiotool.com. Unfortunately we have no machine that can reproduce it, but we let users make this test: https://www.khronos.org/registry/webgl/sdk/tests/conformance/rendering/canvas-alpha-bug.html
It looks like that Firefox found a way to workaround this, since the test passes there. It is probably time to write a chromium bug report. We are still collecting more data.
