### ISSUE TITLE
Restrict axis/plane in TransformControls

### ISSUE THREAD

**Issue by neeravbm** [mrdoob/three.js#7879] opened 2015-12-29 23:33 UTC
In my application, I would like to restrict the movement and rotation to XZ plane. I don't think TransformControls allows for that as of now. I can add the logic if someone can guide me on the easiest way to add that logic.

**Comment by vincecampanale** [comment] 2017-01-30 20:17
Any progress on this? I'm having the same issue.

**Comment by lionbe** [comment] 2017-02-20 19:11
I have a posible solution, i needed control the maximum position en "limitInfY" this works for me in x,y,z
var limitInfY = 0;
transformControls.addEventListener('change', render);

function render() {
    if (transformControls.position.y < 0) {
            // meanwhile you move the obj, it can be move until -0.023xxxx or something minor
            transformControls.position.y = 0;
            object.position.y = 0;    
        }
    }
}

**Comment by arodic** [comment] 2018-08-21 06:12
This is a duplicate of #11340 and should be closed now.

However,  transform limit is not implemented @lionbe and I'm not sure TransformControls is the best place to do it.

**Closed** 2018-08-21 09:04 UTC
Labels: Duplicate, Feature Request
