### ISSUE TITLE
Bounding box is not properly calculated for the InstancedMesh objects in Box3.expandByObject 

### ISSUE THREAD

**Issue by Fang3s** [mrdoob/three.js#18643] opened 2020-02-16 09:36 UTC
##### Description of the problem

Just as the issue title indicated, I create an InstancedMesh with more than one instances at different positions, but it's just the Box3 result of the Geometry attached to it. After reading the code, I have made a fix.

```js
var _box = new THREE.Box3();
var _vector = new THREE.Vector3();
THREE.Box3.prototype.expandByObject = function (object) {

    // Computes the world-axis-aligned bounding box of an object (including its children),
    // accounting for both the object's, and children's, world transforms

    object.updateWorldMatrix(false, false);

    var geometry = object.geometry;

    if (geometry !== undefined) {

        if (geometry.boundingBox === null) {

            geometry.computeBoundingBox();

        }

        if (object.isInstancedMesh) {
            var matrixWorld = object.matrixWorld,
                matrix4Array = object.instanceMatrix.array,
                arrayLength = matrix4Array.length;
            for (var posOffset = 12; posOffset < arrayLength; posOffset += 16) {
                _vector.set(matrix4Array[posOffset], matrix4Array[1 + posOffset], matrix4Array[2 + posOffset]);
                _box.expandByPoint(_vector);
            }
        } else {
            _box.copy(geometry.boundingBox);
        }
        _box.applyMatrix4(object.matrixWorld);

        this.expandByPoint(_box.min);
        this.expandByPoint(_box.max);

    }

    var children = object.children;

    for (var i = 0, l = children.length; i < l; i++) {

        this.expandByObject(children[i]);

    }

    return this;
}
```
See also:
* [Box3.expandByObject](https://github.com/mrdoob/three.js/blob/master/src/math/Box3.js)
* [Box3.setFromObject](https://https://threejs.org/docs/index.html#api/en/math/Box3.setFromObject)
* [InstancedMesh.instanceMatrix](https://threejs.org/docs/index.html#api/en/objects/InstancedMesh.instanceMatrix)
* [BufferAttribute.getX](https://github.com/mrdoob/three.js/blob/master/src/core/BufferAttribute.js)
* [Matrix4.setPosition](https://github.com/mrdoob/three.js/blob/master/src/math/Matrix4.js)

Please also include a live example if possible. You can start from these templates:

* [jsfiddle](https://jsfiddle.net/fang3s/Lb814th5/39/) (dev branch 39)
* [jsbin](https://jsbin.com/honeji/edit?html,css,js,output) (latest release branch)
* [codepen](https://codepen.io/kekkou/pen/GRJZrYw?editors=1010)(latest release branch)

##### Three.js version

- [ ] Dev
- [x] r113
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment] 2020-02-16 10:06
Duplicate of #18334

**Closed by Mugen87** 2020-02-16 10:06 UTC

**Comment by Saltallica** [comment] 2021-02-02 15:27
@Fang3s A huge thank you to providing this code. InstancedMeshes are cumbersome to work with and miss a lot of the practical methods and abilities of normal geometry - I hope that changes over time!
