### ISSUE TITLE
https://threejs.org/examples/#webgl_instancing_performance: naive performs better

### ISSUE THREAD

**Issue by jonas-db** [mrdoob/three.js#23195] opened 2022-01-10 11:56 UTC
The naive version runs at 60fps, while the instanced runs at 50 fps. Possibly the order of the select options is wrong or there is a bug?

**To Reproduce**

Open https://threejs.org/examples/#webgl_instancing_performance
Also observed by people on Discord

***Live example***

**Expected behavior**

Instanced should be more performant

**Platform:**

 - Device: Desktop
 - OS: MacOS
 - Browser: Chrome 96
 - Three.js version: latest

**Comment by Mugen87** [comment] 2022-01-10 12:43
Probably caused by this browser issue:

https://crbug.com/1245448

**Comment by looeee** [comment] 2022-01-11 05:20
I get lower FPS with the naive setting  (~80fps naive vs 120fps for instanced/merged, Chrome on Windows) so I guess this bug may be Mac only? 

Slightly off topic - it might be worth increasing the max instances here. I hit my monitor refresh rate (120hz) with the slider maxed on both instanced and merged so it's not possible to test which is better.

**Comment by Mugen87** [comment] 2022-01-11 08:47
> I get lower FPS with the naive setting (~80fps naive vs 120fps for instanced/merged, Chrome on Windows) so I guess this bug may be Mac only?

Yes. The Chromium issue states this is a macOS issue.

**Comment by Mugen87** [comment] 2022-01-11 08:48
Closing then. It's better to follow this bug at the Chromium bug tracker.

**Closed by Mugen87** 2022-01-11 08:48 UTC
Labels: Browser Issue
