### ISSUE TITLE
problem suspend OrbitControls

### ISSUE THREAD

**Issue by alexan0308** [mrdoob/three.js#6093] opened 2015-02-17 17:51 UTC
If at the time of stop control `controls.enabled = false;`, and then turn `controls.enabled = true;` on the scene abruptly jerks due to changes in the position of the mouse. I Founded approximate solution, but it would be better:

```
    this.suspend = function () {

        this.enabled = false;
        this.target0.copy( controls.target );
        this.position0.copy( controls.object.position );

    };

    this.resume = function () {

        state = -1;
        this.target.copy( this.target0 );
        this.object.position.copy( this.position0 );
        this.update();
        this.enabled = true;

    };
```

**Comment by Mugen87** [comment] 2018-03-19 19:46
I've tested this today but i get a slightly different behavior. You can reproduce it with this example: https://jsfiddle.net/f2Lommf5/3446/

- hold down the mouse button (you have to do this in the first two seconds while the controls are enabled) and change the camera
- when the controls are disabled, release the mouse button
- after two seconds, the controls are enabled again. You can still change the camera.

The problem is that disabled `OrbitControls` don't process the `mouseup` event. This leads to a situation where the controls are somewhat out of sync with the input device. Should we maybe perform some kind of reset when the controls are disabled?

**Comment by WestLangley** [comment] 2018-03-19 21:00
I expect this will work:
```javascript
controls.enabled = false;
controls.dispose();
```
.. but the use case seems unusual to me.

**Comment by Mugen87** [comment] 2018-03-20 11:01
> .. but the use case seems unusual to me.

Yeah it feels a little bit...artificial.

> controls.dispose();

If I call `.dispose()` and then enable the controls again, i'm unable to control the camera like before. I think it's because `.dispose()`removes all event listeners and there is no mechanism that restores the setup.

**Comment by WestLangley** [comment] 2018-03-20 11:18
I do not think we need to worry about a use case in which the controls are being programmatically disabled while the user is interacting with it.

**Comment by Mugen87** [comment] 2018-03-20 11:36
Okay, i think we can close the issue then. If users ever complain again, then at least we know where the problem is 😊

**Closed** 2018-03-20 11:39 UTC
Labels: Suggestion
