### ISSUE TITLE
Skeleton clone references same bones as original skeleton

### ISSUE THREAD

**Issue by TyLindberg** [mrdoob/three.js#15144] opened 2018-10-26 22:31 UTC
When cloning a skeleton, the bones and boneInverses arrays of the cloned skeleton still reference the arrays from the original skeleton. Hence when the original skeleton is animated, the bones on the cloned skeleton are also affected. Is this the intended behavior?

https://github.com/mrdoob/three.js/blob/c0dbf052eb276e407a0d2ea881b010303859d9cd/src/objects/Skeleton.js#L153

**Comment by donmccurdy** [comment] 2018-10-26 23:33
Related to PR https://github.com/mrdoob/three.js/pull/14494 and bugs https://github.com/mrdoob/three.js/issues/5878, https://github.com/mrdoob/three.js/issues/11574.

Whether it's intended behavior or not is a complicated question... you could, for example, clone a SkinnedMesh for which some bones are siblings (not children) of the mesh, such that some bones have two instances after the cloning is complete, and others have only one shared instance.

Closing this as a duplicate of https://github.com/mrdoob/three.js/issues/5878, just to keep conversation in one place.

**Closed by donmccurdy** 2018-10-26 23:33 UTC
Labels: Duplicate
