### ISSUE TITLE
Audio Context Bug on Immersive Enviroments on AVP

### ISSUE THREAD

**Issue by mannomion** [mrdoob/three.js#29646] opened 2024-10-14 08:10 UTC
### Description

When i use this code

import { AudioContext, AudioListener } from 'three';

 const context = AudioContext.getContext();
          console.log('----starting---');
          await context.resume();
          console.log('----end---');
          
 I debug when I enter the button immersive on AVP, I still wait to allow permissions for 10 seconds. after allowed, the console.log "----end---" not showing, just starting mabe it delay for promise.
 
 but with the case i allow button immersive within 3seconds, it work well

### Reproduction steps

1. Going to a website immersive audio by AVP
2. Enter immersive button
3. Safari throw 2 dialogs to allow permission
4. wait 10 seconds and enter allows
5. audio disappear.

### Code

```js
// code goes here
```

### Live example

* [jsfiddle-latest-release WebGLRenderer](https://jsfiddle.net/3mrkqyea/)
* [jsfiddle-dev WebGLRenderer](https://jsfiddle.net/gcqx26jv/)
* [jsfiddle-latest-release WebGPURenderer](https://jsfiddle.net/8L2jkmx7/)
* [jsfiddle-dev WebGPURenderer](https://jsfiddle.net/L3n1w4yh/)

### Version

0.164.1

### Device

Headset

### Browser

Safari

### OS

MacOS

**Comment by Mugen87** [comment] 2024-10-14 10:24
Is that maybe a duplicate of #27779?

**Closed** 2024-10-15 08:40 UTC
Labels: Device Issue
