### ISSUE TITLE
initMaterial called each time render is called on a material used on two scenes

### ISSUE THREAD

**Issue by DennisBengs** [mrdoob/three.js#14477] opened 2018-07-14 20:24 UTC
##### Description of the problem

I noticed that there was a significant slowdown in the app I'm developing. I narrowed it down to being caused by initMaterial being called each frame under certain very specific conditions

. The minimum requirements to reproduce the bug (afaik) are:

- Create two meshes which share the same MeshLambertMaterial.
- Create two scenes and add the meshes to them.
- Create a single DirectionalLight in one of the scenes, not both.
- Create an OrthographicCamera overlooking the objects (not a perspective camera).
- Call render twice, once for each scene.

If you don't notice the slowdown, use the performance tab in Firefox to measure the performance and you should see WebGLShader at the top of the call tree.

* [Live sample](https://codepen.io/Donitz/pen/BPjyJN)

##### Three.js version

- [x] Dev

##### Browser

- [x] Firefox

##### OS

- [x] Windows

**Comment by WestLangley** [comment] 2018-07-14 22:37
Hmm... If a material is shared between two scenes, `initMaterial()` is called with each use because:
```javascript
materialProperties.lightsHash !== lights.state.hash
```
The hash is defined as:
```javascript
state.hash = state.id + ',' + directionalLength + ... etc...
```
Even if the numbers and types of lights are the same in both scenes, `state.id` is different.

So, sharing a material between scenes will not be performant.

The work-around is to clone the material.
```javascript
var mesh1 = new THREE.Mesh( geometry, material );
var mesh2 = new THREE.Mesh( geometry, material.clone() );
```

I guess I would call this a limitation.

And a duplicate of #14121.

**Closed** 2018-07-15 07:57 UTC
Labels: Duplicate

**Comment by Mugen87** [comment] 2018-07-15 16:41
In general we avoid multiple issues about the same topic. Since #14121 is the leading issue, you transfer the workaround to this discussion.

**Comment by WestLangley** [comment] 2018-07-15 20:13
OK. Perhaps we can close duplicates like so:

_Closing as a duplicate. Please continue the discussion in #14121._

**Comment by Mugen87** [comment] 2018-07-16 09:53
Sounds good!
