### ISSUE TITLE
Theree.js contests / grants with OpenCollective fund

### ISSUE THREAD

**Issue by munrocket** [mrdoob/three.js#19670] opened 2020-06-16 07:41 UTC
I am suggesting to create opencollective and spent this money to contests and grants.

For example:
* grant for new Three.js UI
* contest with particles
* etc.

**Comment by makc** [comment] 2020-06-16 08:29
FYI #11318

**Comment by Mugen87** [comment] 2020-06-16 08:38
Yes, this is actually a duplicate of #11318.

**Closed by Mugen87** 2020-06-16 08:38 UTC

**Comment by munrocket** [comment] 2020-06-16 08:43
> Yeah, I wouldn't know how to distribute the money..

I am suggested how to spend it.
