### ISSUE TITLE
USDZLoader: TypeError: target is undefined

### ISSUE THREAD

**Issue by jeffzhkw** [mrdoob/three.js#28631] opened 2024-06-11 23:31 UTC
### One-line Description of the Bug:

In `USDZLoader.js` , line 61. target is undefined when loading certain usdz files.

### Detail Description

These usdz files:

- contain `.usda` underneath
- are converted from the itself but with `.usdc` underneath.
  - [OpenUSD](https://github.com/PixarAnimationStudios/OpenUSD) toolset is used to do the conversion. Toolset documentation [here](https://openusd.org/release/toolset.html#). Conversion between `usdc` and `usda` documentation [here](https://openusd.org/release/tut_converting_between_layer_formats.html).

The conversion should work, as verified by opening the file in Reality Composer Pro, Reality Converter, and `usdview` from OpenUSD toolset. 
Here is a converted usdz file ([Google Drive Link](https://drive.google.com/file/d/1jXjo7Th3HwSxYBcz5XectdMtIobEf4LD/view?usp=sharing))that I created using steps above. It has `.usda` underneath. The source usdz with usdc underneath is from Apple, [3D models](https://developer.apple.com/augmented-reality/quick-look/) .

However, the file shared in google drive will not get loaded in Three.js. 

To be more specific, I utilized the source code of [Three.js USDZLoader Example](https://threejs.org/examples/?q=usdz#webgl_loader_usdz) by cloning the three.js repository from dev branch. I put the file under `examples/modes/usdz/` and modified line 66 in `examples/webgl_loader_usdz.html`  to corresponding file name. Refreshing the page will see the console log error. 

### Some Preliminary Debugging and insights

I printed out the index for `lines` variable, and added a `debugger` statement at line. It seems like the error occured around line 50 of `sneaker_airforce.usda`. 

```
43       ...0.918676)] (
44            customData = {
45                dictionary Maya = {
46                    token name = "map1"
47                }
48            }
49            interpolation = "faceVarying"
50        )
51        int[] primvars:st:indices = [13876, 13893, 13...
```

**In other words, it seems like there is a prasing logic error for the case when parenthesis `(...)`happend after a square brackets`[..., ...]`, and when there are multiple lines inside the parenthesis.** 

Here is another case: 

```
36        color3f[] primvars:displayColor = [(1, 1, 1)] (
37            customData = {
38                dictionary Maya = {
39                    bool generated = 1
40                }
41            }
42        )
```

As I manually edit the `sneaker_airforce.usda` to keep a single line in that parenthesis, re-zipped it into `usdz` and loaded into three.js. Additional error occured at around line 117 of the `usda` file: 

```
114                float4 inputs:fallback = (0.5, 0.5, 0.5, 1)
115                asset inputs:file = @0/baked_mesh_ao0.png@ (
116                    colorSpace = "Raw"
117                )
118                token inputs:sourceColorSpace = "raw"
```

After remove the parenthesis from 115-117, I re-zipped the usda file again and tested in three.js. The model is loaded but undesirable: there is no texture or material and it's huge in size. See screenshot below for reference.

### Reproduction steps

1. Get the error USDZ model from here: ([Google Drive Link](https://drive.google.com/file/d/1jXjo7Th3HwSxYBcz5XectdMtIobEf4LD/view?usp=sharing))
2. Use USDZLoader().loadAsync() to load the the model. You can use [three.js USDZLoader example]() as a template for quick start
3. See the error message in the console. 
4. Optional: unzip the `.usdz` file and inspect `.usda` using any text editor.

### Code
`USDZLoader.js`
```js
					stack.push(group);

					target[lhs] = group;
					target = group;
				} else {
                                          // Here `target` is undefined at `line == 50` 
					target[lhs] = rhs;
				}
			} else if (line.endsWith('{')) {
```

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/g3atw6k5/)
* [jsfiddle-dev](https://jsfiddle.net/hjqw94c5/)
Not applicable: Need local test with the file loading. Didn't find a way to upload file to jsfiddle runtime file system. 

### Screenshots

**Converted .usdz file in Reality Converter:** 
<img width="887" alt="Screenshot 2024-06-11 at 19 30 37" src="https://github.com/mrdoob/three.js/assets/30642720/7e8d4ef3-7970-42e1-b4af-27acea440162">
**Modified the converted .usdz file that managed to show something in Three.js:**
<img width="1246" alt="Screenshot 2024-06-11 at 19 19 01" src="https://github.com/mrdoob/three.js/assets/30642720/880fde13-617f-46d1-a428-a78e38a2abe3">

### Version

166dev

### Device

Desktop

### Browser

Firefox

### OS

MacOS

**Comment by Mugen87** [comment] 2024-06-12 09:07
I can reproduce the parsing error. Considering this as a bug.

**Comment by Mugen87** [comment] 2024-06-12 09:54
It seems there is a fundamental issue in the loader that breaks this mesh. The existing mesh in [webgl_loader_usdz](https://threejs.org/examples/webgl_loader_usdz) is also affected by the bug but the loader actually applies workaround that overshadows the bug.

The loader maintains an internal stack to track the current hierarchy of the parsed asset. This hierarchy gets corrupted when meta data are defined for vertex data. E.g. in `saeukkang.usdz` there is a typical `texCoord2f[] primvars:st =` statement but it ends with a `(` statement to introduce meta data definition. The problem is the loader does not detect this and adds the meta data to the wrong place in the target object. Moreover, when it detects the closing `)`, it corrupts the stack and adds the `int[] primvars:st:indices` data to the wrong place as well.

The following code section tries to fix these malformed definitions by just moving the data to the correct spot:

https://github.com/mrdoob/three.js/blob/4fdc32283d7aa0502889e8bde57221bb4b69feeb/examples/jsm/loaders/USDZLoader.js#L308-L332

This code section should not be required if the loader correctly parses the data in the first place. 

In the issue's asset `sneaker_airforce_a.usdz` the meta data are more complex and further corrupt the stack until there is no target to write data anymore (`undefined`).

TBH, the line-by-line parsing is okay for simple loaders but we start to see the same issues as with the former `VRMLLoader` implementation. Using a lexer + parser approach based on a lib like chevrotain would be an ideal long-term solution since it completely eliminates such issues. As a quick fix, we can maybe just ignore the meta data for vertex data for now and ensure they are written at the right location of the result object.

**Closed** 2024-06-13 08:49 UTC
Labels: Bug, Loaders
