### ISSUE TITLE
PMREMGenerator: instances share context across multiple renderers

### ISSUE THREAD

**Issue by treyenelson** [mrdoob/three.js#18976] opened 2020-03-25 18:35 UTC
##### Description of the problem

Using `PMREMGenerator.fromEquirectangular`  in multiple simultaneous three.js renderers causes only the last renderer to have a correctly functioning texture (at least for use as an envMap)
This happens even when each renderer has its own instance of `pmremGenerator` and calls `dispose` after use.

Here's a fiddle: [https://jsfiddle.net/h37k2ztv/10/](https://jsfiddle.net/h37k2ztv/10/)

I would expect that initializing a different `pmremGenerator` for each renderer should be sufficient, but I had to work around it by reinstantiating and recompiling the `pmremGenerator` immediately before each time it is used (uncomment lines 63 and 64 in the fiddle to do this)

Issue #18842 reports this same issue, but perhaps even without multiple renderers.
[This merge request](https://github.com/mrdoob/three.js/pull/15330) may have introduced the unexpected behavior.

##### Three.js version

- [x] Dev
- [ ] r115
- [ ] ...

##### Browser

- [ ]  All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [ ] macOS
- [x] Linux
- [x] Android
- [ ] iOS

**Comment by makc** [comment] 2020-03-26 01:01
Just to be clear, the #18842 was happening when you used a single instance per renderer multiple times. If you create new instance every time you need to make a texture, the issue is not in the way, which is why I did not press them to fix it.

**Comment by treyenelson** [comment] 2020-03-26 01:21
@makc actually, it appears that the single instance per renderer multiple times case should work.

I modified my fiddle from above: https://jsfiddle.net/kpfr7zv9/1/
It successfully loads two textures for the second renderer using the same instance of `pmremGenerator`, but the first renderer (which does the same with its own instance) still has the original problem.

**Comment by makc** [comment] 2020-03-26 04:25
@treyenelson ha, I did not test something like this. In my case I had to set same map in both renderers.

**Comment by Mugen87** [comment] 2020-03-27 10:32
That happens because PMREMGenerator saves the reference to its renderer as well as other entities in a module scope variables. Hence, creating multiple generators with different renderers will overwrite the existing module scope variables with new values.

I do not vote to support the 1:n relationship (1 generator, multiple renderers). However, a 1:1 relationship is something that one could expect to work.

**Comment by Mugen87** [comment] 2020-04-01 15:26
@treyenelson #19011 should fix your posted fiddle. Can you also give it a try please?

**Comment by treyenelson** [comment] 2020-04-01 16:06
@Mugen87 I tried out the fiddle with three.js built from your fork and it worked like a charm!

The merge request that I believe introduced this bug (https://github.com/mrdoob/three.js/pull/15330) intended to solve a memory leak, so I briefly attempted to recreate that test, but it's out-of-date enough that it might not be worth the hassle.
It's a lot more reasonable in any case to fix the problem outlined in this issue, rather than a memory leak that arises from reinstantiating the loaders / generators every time that a texture is updated.

Should I close this issue now, or does it get closed when the merge request is accepted?

**Comment by Mugen87** [comment] 2020-04-01 16:21
AFAICT, when `dispose()` is properly used, there should be no memory leak. 

> Should I close this issue now, or does it get closed when the merge request is accepted?

This happens automatically as soon as the PR is merged. Hence, I would leave it open for now.

Thank you for verifying the PR!

**Closed** 2020-04-02 09:15 UTC
