### ISSUE TITLE
Crash When ObjectLoader parse EdgesGeometry

### ISSUE THREAD

**Issue by DJoeyZhang** [mrdoob/three.js#26425] opened 2023-07-14 08:34 UTC
### Description

Crash When ObjectLoader parse Json file which including EdgesGeometry 

### Reproduction steps

1.prepare a file including EdgesGeometry
2.de-serialized using ObjectLoader::parse 
3.crash

### Code

```js
geometry.uuid = data.uuid;

if ( data.name !== undefined ) geometry.name = data.name;
if ( data.userData !== undefined ) geometry.userData = data.userData;

geometries[ data.uuid ] = geometry;
```

				

### Live example

[jsfiddle-latest-release](https://jsfiddle.net/g3atw6k5/)
[jsfiddle-dev](https://jsfiddle.net/hjqw94c5/)

### Version

r154

### Device

Desktop

### Browser

Chrome

### OS

MacOS

**Comment by Mugen87** [comment] 2023-07-14 09:12
Duplicate of #16340.

**Closed by Mugen87** 2023-07-14 09:12 UTC
