### ISSUE TITLE
Editor: loading previously exported JSON scenes fails

### ISSUE THREAD

**Issue by maciejzasada** [mrdoob/three.js#7212] opened 2015-09-22 14:10 UTC
Hi,

**Description of issue:**
When trying to load (in the editor) a just exported (via the editor) JSON scene I get the following exception:
```
Uncaught TypeError: Cannot read property 'length' of undefined @ three.min.js:292
```
NOTE: Loading the JSON scene normally in a project with ObjectLoader works fine.

**Gravity:**
Blocker. Cannot collaborate on JSON scenes because once downloaded, it is impossible to edit them next time.

**Steps to reproduce:**
1. Go to http://threejs.org/editor/
2. File/New
3. Add/Box
4. File/Export Scene
5. File/New
6. Drag and drop the downloaded scene.json onto the editor or use File/Import
7. Observer nothing happens.
8. Check the JS console to see the mentioned exception.

**Tested on:**
Mac OS X 10.10 Chrome 45

**Comment by htdt** [comment] 2015-09-22 14:21
I also have this error,
Mac OS X 10.10 Chrome 47

**Comment by elephantatwork** [comment] 2015-09-22 16:13
Same here.

The error occurs in the JSONLoader.parse() where it doesn't find vertices.
<img width="997" alt="screen shot 2015-09-22 at 17 48 37" src="https://cloud.githubusercontent.com/assets/1109692/10023772/e997d9fe-6153-11e5-9490-ac2f00531c14.png">

**Comment by Samsy** [comment] 2015-09-22 16:41
Same here.

<img width="706" alt="screen shot 2015-09-22 at 5 40 51 pm" src="https://cloud.githubusercontent.com/assets/3786958/10024882/1c7b8120-6151-11e5-977b-288973728aa3.png">

**Comment by elephantatwork** [comment] 2015-09-22 17:14
<img width="1347" alt="screen shot 2015-09-22 at 18 21 03 copy" src="https://cloud.githubusercontent.com/assets/1109692/10025609/6666fe52-615d-11e5-95e5-bf47bd61a2c1.png">

I found the issue. the .json is badly formated

**Comment by dforrer** [comment] 2015-09-22 17:20
[/editor/js/Loader.js](https://github.com/mrdoob/three.js/blob/a48f24579a3ca01b8a2b519ab8ee6e0413db46b8/editor/js/Loader.js#L358-L376) must be adjusted to the new way how Object3D.toJSON() exports the scene.

As elephantatwork said:

The problem is that the **metadata-attribute** no longer is at the top level of the JSON, but rather behind the **object-attribute**. Because of this *Loader.js* assumes that the imported JSON is of type "geometry".

**Comment by elephantatwork** [comment] 2015-09-22 19:00
Ok I fixed the issue:

I added those two lines to the [/editor/js/Loader.js](https://github.com/mrdoob/three.js/blob/a48f24579a3ca01b8a2b519ab8ee6e0413db46b8/editor/js/Loader.js#L358-L376).

<img width="596" alt="screen shot 2015-09-22 at 20 57 59" src="https://cloud.githubusercontent.com/assets/1109692/10028425/c6a68c56-616c-11e5-833b-34cddf645da0.png">


It's kind of hacky just put the metadata back to it's original place but I guess that's not intended?

**Comment by mrdoob** [comment] 2015-09-22 22:58
Sorry about that guys!
Should be fixed now (updated `master` and the live editor).
Thanks @tschw!

**Closed by mrdoob** 2015-09-22 22:58 UTC
