### ISSUE TITLE
InstancedBufferGeometry should check type before copy the instanceCount

### ISSUE THREAD

**Issue by lzoia-bc** [mrdoob/three.js#22176] opened 2021-07-23 09:50 UTC
**Describe the bug**

When you use the copy method from the InstancedBufferGeometry the instanceCount attribute is copied by defualt. This could lead to errors, since the copy method accepts any kind of geometry and for this reason the instanceCount could be set to undefined. 

**To Reproduce**

call InstancedBufferGeometry .copy passing a BufferGeometry of a Geometry and the instanceCount  will be set to undefined

**Expected behavior**

The copy method should check the type of the geometry passed as input and only if it is an InstancedBufferGeometry the instanceCount should be copied.

**Platform:**
 - All
 - Three.js version: [master]

**Comment by Mugen87** [comment] 2021-07-23 10:39
Duplicate of #22151.

**Closed by Mugen87** 2021-07-23 10:39 UTC
