### ISSUE TITLE
Removing map from material

### ISSUE THREAD

**Issue by joaocraveiro** [mrdoob/three.js#8903] opened 2016-05-17 15:58 UTC
##### Description of the problem

I am trying to remove the texture applied to a material. When I set the material map property to null the object seems to somehow get the first texture I loaded (and applied to another object) mapped.
##### Three.js version
- [ ] Dev
- [ ] r76
- [x] r73
##### Browser
- [ ] All of them
- [x] Chrome
- [x] Firefox
- [ ] Internet Explorer
##### OS
- [ ] All of them
- [x] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment] 2016-05-17 17:29
Can you create a jsfiddle?

**Comment by tentone** [comment] 2016-05-18 01:10
Maybe you are forgetting to set "needsUpdate" true? Something like
```
material.map = null;
material.needsUpdate = true;
```

**Comment by joaocraveiro** [comment] 2016-05-18 15:43
needsUpdate does the trick but this behavior does seem weird.

Here goes a fiddle: https://jsfiddle.net/JoaoCraveiro/dy9roz6x/2/

**Comment by mrdoob** [comment] 2016-05-19 02:37
What's weird about it?

**Comment by joaocraveiro** [comment] 2016-05-19 10:58
Wrong version of the fiddle. Basically when you press the button it sets the texture of the bigger box to null but it maps the texture assigned to the smaller box.

**Comment by WestLangley** [comment] 2016-05-19 16:59
Fiddle without errors: https://jsfiddle.net/dy9roz6x/7/

This seems to be the issue:
```javascript
document.getElementById( "btn1" ).onclick = function () {

    //mesh.material.map = trigger.material.map; //works

    mesh.material.map = null; mesh.material.needsUpdate = true; // needsUpdate required

}
```

Note: the textures are solid green and solid purple in the fiddles.

**Comment by joaocraveiro** [comment] 2016-05-19 17:38
Fiddle has no errors. It's to illustrate a weird behavior when you set map to null without the needsUpdate true.

**Comment by WestLangley** [comment] 2016-05-19 18:17
@jonnenauha When I run your fiddle

    1285(index): Uncaught ReferenceError: stats is not defined

I simply cleaned up and removed the extraneous code from your fiddle to make it easier for others to follow.

**Comment by WestLangley** [comment] 2016-06-10 19:46
@mrdoob To summarize, the issue here is:

    mesh.material.map = mesh2.material.map; //works w/o setting needsUpdate

    mesh.material.map = null; mesh.material.needsUpdate = true; // works with needsUpdate set

    mesh.material.map = null; // assigns some other map as the texture

See fiddle above.

**Comment by Mugen87** [comment] 2019-09-10 11:42
I've recently came across this issue. The problem is that removing a map (setting `Material.map` to `null`) means the respective map uniform becomes obsolete, too. Without setting `Material.needsUpdate` to `true`, it's not possible to reset the uniforms list and the define `USE_MAP`. 

It's a different use case when an existing texture is replaced with another one. In this context, no change of the shader program is required. 

Since there is no easy way to consistently solve this issue for all use cases, I vote to close the issue and mark it as `Won't fix`.

**Comment by WestLangley** [comment] 2019-09-10 19:03
> I vote to close the issue and mark it as Won't fix.

Well, closing is fine, but "Won't fix" means there is something defective. There is nothing defective here -- setting the needs update flag is required in this case.

---

Use this pattern when removing a map and setting `material.map` to `null`:

```js
mesh.material.map = null;
mesh.material.needsUpdate = true; // required
```

**Comment by Mugen87** [comment] 2019-09-10 19:53
> but "Won't fix" means there is something defective.

At least according to my practical experience it's common to use this label for situations like that. In the sense of the reported "faulty" behavior is not going to be changed.

**Comment by mrdoob** [comment] 2019-09-11 02:28
One way would be by adding this [here](https://github.com/mrdoob/three.js/blob/dev/src/renderers/WebGLRenderer.js#L1629):

```js
if ( material.map !== materialProperties.map ) {
    materialProperties.map = material.map;
    material.needsUpdate = true;
}
```

But then we would have to do the same for every property...

**Comment by Mugen87** [comment] 2019-09-11 08:43
> But then we would have to do the same for every property...

I have the feeling this will unnecessarily blow up the code. And make it more complex.

**Comment by EliasHasle** [comment] 2019-09-11 17:40
Why not just pass the `null` value to `texImage2d`? Quoting the [WebGL 1.0 specification](https://www.khronos.org/registry/webgl/specs/latest/1.0/#5.14.8):
> If pixels is null, a buffer of sufficient size initialized to 0 is passed.

**Closed** 2019-09-18 13:54 UTC
