### ISSUE TITLE
"Uncaught TypeError" with bufferGeometry, LineBasicMaterial, and lights:true

### ISSUE THREAD

**Issue by dcromley** [mrdoob/three.js#14690] opened 2018-08-10 22:42 UTC
##### Description of the problem
The fiddle is https://jsfiddle.net/dcromley/g791otyp/  
This draws a line using bufferGeometry with  
`    LineBasicMaterial( { vertexColors:THREE.VertexColors, lights:false }`
As it is, it gives a correct red to blue line.  
By changing "lights:false" to "lights:true", it gives the error:  
    

> Uncaught TypeError: Cannot set property 'value' of undefined

It does not give this error using Revision 73.  
Maybe, "Who would want to do this"?  But I stumbled across this error.  
My thanks to all.  Let me know how I can conform better to the threejs society.
##### Three.js version
- [x] r95
##### Browser
- [x ] Chrome Version 68.0.3440.106 (Official Build) (64-bit)
##### OS
- [x ] Windows

**Comment by WestLangley** [comment] 2018-08-10 22:54
Essentially a duplicate of #10491.

**Comment by dcromley** [comment] 2018-08-11 01:36
"Essentially a duplicate of #10491."  
I looked, but didn't find.  I am closing.  (Who-all can close?)

**Closed** 2018-08-11 01:36 UTC
