### ISSUE TITLE
VisualResponse objects get created over and over when WebXR hands are entering/leaving the view

### ISSUE THREAD

**Issue by hybridherbst** [mrdoob/three.js#24071] opened 2022-05-16 14:35 UTC
**Describe the bug**

VisualResponse objects get created over and over when WebXR hands are entering/leaving the view. This leaves many "little spheres" all over the place in all the hand input demos.

**To Reproduce**

1. Go to https://threejs.org/examples/?q=hand#webxr_vr_handinput_pointerdrag on Hololens 2 or another device that has hand tracking with hands properly being connected and disconnected when they enter/leave (e.g. NOT Quest 2)
2. Enter VR or AR session
3. Put your hands in front of you and turn your head back/forth so the hands enter/leave the view
4. Note that VisualReponse sphere + pinch objects are spawned over and over

***Live example***

https://threejs.org/examples/?q=hand#webxr_vr_handinput_pointerdrag

**Expected behavior**

VisualResponse objects are either only created once and reused or are properly destroyed on hand disconnect

**Screenshots:**
![20220511_012208_HoloLens](https://user-images.githubusercontent.com/2693840/168617618-3581ade0-2e92-4233-bd67-8a850694e7fb.jpg)

**Platform:**

 - Device: Hololens 2
 - OS: Windows Holographic
 - Browser: Edge
 - Three.js version: r140 + dev and probably earlier

cc @cabanier I think this will happen on Quest 2 as well once it properly connects/disconnects hands upon leaving the view.

**Comment by LeviPesin** [comment] 2022-05-16 14:39
Is this a duplicate of https://github.com/mrdoob/three.js/issues/24055?

**Comment by hybridherbst** [comment] 2022-05-16 14:40
Just saw that! Seems I'm late reporting, found this last week and just submitted the issue. Might well be!
I'm not entirely sure though - maybe there's separate issues with "hand leaving the field of view and coming back" and "pinching"?

**Comment by hybridherbst** [comment] 2022-05-16 14:42
Also it seems this happens in all the hand input examples, not just one in particular.

**Comment by Mugen87** [comment] 2022-05-16 16:36
Let's track the issue in #24055. This one can be reopened if it turns out to be something unrelated.

**Closed by Mugen87** 2022-05-16 16:36 UTC
