### ISSUE TITLE
CircleGeometry shows multiple intersects when using raycaster

### ISSUE THREAD

**Issue by andrewplummer** [mrdoob/three.js#18101] opened 2019-12-07 12:23 UTC
##### Description of the problem

This might be something I'm misunderstanding but if I set up a simple CircleGeometry and a basic Raycaster (all from the examples), using the raycaster to get the intersects will often result in multiple faces intersecting. If the coordinates were exactly zero this might be understandable, but this happens even with a slight offset, which doesn't seem like it should be possible. I've set up a simple example here:

https://jsfiddle.net/andrewplummer/up5yqvbc/5/

The example shows some null faces intersecting (which I don't know should be possible or not), however in a more complex example I have different faces are shown as intersecting. Creating a sphere or extruded mesh doesn't seem to have this problem. Any ideas?

Thank you!

##### Three.js version

- [ ] Dev
- [x] r111
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment] 2019-12-07 12:31
Are you aware that your fiddle produces intersections with the axes helper?

https://jsfiddle.net/f6xyhwLc/

When commenting out the helper, there is only a single intersection.

**Comment by andrewplummer** [comment] 2019-12-07 15:14
Ah ok damn... this one is tricky to reproduce. At the very least I can get it reproduced locally in a pruned down project using the exact center of the circle, which I'm not sure is expected. In a larger project I was seeing many faces of the circle intersect. Changing it to CylinderGeometry made these problems go away... here is the code for that if it helps though:

```js

// Scene
const scene = new THREE.Scene();
scene.add(new THREE.AmbientLight(0x404040));
scene.add(new THREE.DirectionalLight(0xffffff, .5));

// Camera
const ratio = window.innerWidth / window.innerHeight;
const camera = new THREE.PerspectiveCamera(45, ratio, 1, 10000);
camera.position.add(new THREE.Vector3(0, 10, 0));

// Renderer
const renderer = new THREE.WebGLRenderer();
renderer.setSize(window.innerWidth, window.innerHeight);
document.body.appendChild(renderer.domElement);

// Controls
const controls = new THREE.OrbitControls(camera, renderer.domElement);

// Animation
function render() {
  renderer.render(scene, camera);
  //requestAnimationFrame(render);
}

// Interaction

const raycaster = new THREE.Raycaster();

// Test
const group = new THREE.Group();
scene.add(group);

const geometry = new THREE.CircleGeometry(1, 32, 32 );
const material = new THREE.MeshBasicMaterial( {color: 0xffff00} );
const mesh = new THREE.Mesh( geometry, material );
group.add(mesh);
group.rotateX(-Math.PI / 2);

render();

raycaster.setFromCamera({ x: 0, y: 0 }, camera);
const intersects = raycaster.intersectObject(scene, true);
console.info(intersects);
```

**Comment by Mugen87** [comment] 2019-12-07 16:14
Thanks for sharing your code! However, as long as it's not possible to reliably reproduce the issue with a live example, I will be hard to find the root cause. 

I'm a bit surprised about this issue in general since I would rather expect the opposite behavior. Meaning raycasting can fail because of floating point inaccuracies, see #11449

**Comment by Mugen87** [comment] 2019-12-11 15:17
Closing. Feel free to reopen the issue if you can reproduce the glitch with a fiddle.

**Closed by Mugen87** 2019-12-11 15:17 UTC

**Comment by andrewplummer** [comment] 2019-12-11 15:57
Thanks for your attention here... I've been starting to use cylinder geometry now anyway as it looks better for what I'm doing so likely I won't be able to repro this soon... it could easily have been something I was doing wrong as well. 👍
