### ISSUE TITLE
Raycaster slowdown in chrome on poor Vector3 creation

### ISSUE THREAD

**Issue by dnkorbut** [mrdoob/three.js#15595] opened 2019-01-16 12:30 UTC
##### Description of the problem
Works only in Chrome

If I use Raycaster to IntersectObject I can experience some unpredictable problem in extream slowdown of the raycasting.

To reproduce that problem you should somewhere in the code declare Vector3 with strings in it's properties. Just create such Vector3 not use it:
**var test = new THREE.Vector3("foo", "bar", "baz")**

* [jsfiddle](https://jsfiddle.net/dnkorbut/8guscodm/1/) (reproduced problem)
1) Try to move your mouse around to see your FPS while moving the mouse
2) Click "slowdown" button at the top right corner
3) Move your mouse again to see huge performance drop

In real life we do not put strings to Vector3 properties but sometime people can get some poor JSON output or some other issues where the problem will be revealed only when you trying to use Raycaster and those not easily fixed. Vector3 works well with strings like "1.234" but Raycaster will be slowed down in such cases. So the problem can be seamless. You should always parseFloat before you put values to Vector3

##### Three.js version

- [x] Dev
- [x] r100
- [x] ...

##### Browser

- [] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment] 2019-01-16 12:36
Sorry, but this is clearly an app-level problem. For performance reasons, `three.js` does not perform type-checking and casting of parameters.

**Comment by nahashsvb** [comment] 2019-01-16 13:00
@Mugen87 Hmm. But created Vector3 wasn't used inside raycasting. 
You can create global variable of Vector3 type, assign to the x/y/z some string values, and it breaks the raycasting performance. I did such test and fps was dropped from 80-120 to the 7-15.
I agree that it is app-level problem, if vectors with wrong values will be used inside raycasting.
But no, it's just a global variable that never used. And it effects raycasting process.
It's not app-level problem IMO. Tell me if I'm wrong.

**Comment by Mugen87** [comment] 2019-01-16 13:05
If it only happens in Chrome, I suggest you try to isolate the issue and report it to the Chromium issue tracker:

https://bugs.chromium.org/p/chromium/issues/list

Otherwise ensure the app has to ensure that no `Vector3` with strings are created. I don't think there is anything meanigful we can do.

**Comment by Mugen87** [comment] 2019-01-16 13:06
Oh, this seems to be a duplicate of #12957

**Closed** 2019-01-16 13:06 UTC
Labels: Duplicate
