### ISSUE TITLE
mesh both receive and cast shadow seems odd

### ISSUE THREAD

**Issue by leoboboyan** [mrdoob/three.js#13610] opened 2018-03-16 06:26 UTC
##### Description of the problem

This form is for three.js bug reports and feature requests only.

This is NOT a help site. Do not ask help questions here.
If you need help, please use the [forum](https://discourse.threejs.org/) or [stackoverflow](http://stackoverflow.com/questions/tagged/three.js).

Describe the bug or feature request in detail.

Always include a code snippet, screenshots, and any relevant models or textures to help us understand your issue.

Please also include a live example if possible. You can start from these templates:

* [jsfiddle](https://jsfiddle.net/s3rjfcc3/) (latest release branch)
* [jsfiddle](https://jsfiddle.net/ptgwhemb/) (dev branch)
* [codepen](https://codepen.io/anon/pen/aEBKxR) (latest release branch)
* [codepen](https://codepen.io/anon/pen/BJWzaN) (dev branch)

##### Three.js version

- [ ] Dev
- [x] r91
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

Here is an example, export from threejs.org/editor

[scene.json.zip](https://github.com/mrdoob/three.js/files/1818130/scene.json.zip)

thanks!

**Comment by donmccurdy** [comment] 2018-03-16 06:40
This shadow doesn't look unreasonable to me, what part seems odd?

![screen shot 2018-03-15 at 11 39 11 pm](https://user-images.githubusercontent.com/1848368/37507077-29a4e1a2-28aa-11e8-8c01-e9684fbbb0c9.png)

**Comment by leoboboyan** [comment] 2018-03-16 06:53
there are so many dark streaks on the object.

when set receive shadow to false, it's gone.

**Comment by Usnul** [comment] 2018-03-16 08:39
In short:
- shadow acne (https://computergraphics.stackexchange.com/questions/2192/cause-of-shadow-acne)

Problems:
- shadow mapping algorithm is rather simple, more complex algorithms address this issue to some degree
- shadowmap resolution is too low in the acne region. This can be addressed by increading resolution or tightening the shadow camera frustum
- normals on the cylinder are not "smooth", this causes each face to be shaded as an individual surface, resulting in unpleasant artifacts when combined with shadow acne.

I suggest you research a bit into shadowmapping - it will help you understand problems like this in the future and how to deal with them better.
You might find a discussion here useful: https://github.com/mrdoob/three.js/issues/5554

**Comment by leoboboyan** [comment] 2018-03-16 09:15
thanks a lot! @Usnul

**Closed** 2018-03-16 14:45 UTC

**Comment by WestLangley** [comment] 2018-03-16 15:41
Those are artifacts caused by self-shadowing, and the question has been answered on [stackoverflow](https://stackoverflow.com/questions/48938170/three-js-odd-striped-shadows/48939256#48939256).
