### ISSUE TITLE
Chrome Text Distortion When New Elements Are Added

### ISSUE THREAD

**Issue by csimlinger** [mrdoob/three.js#28469] opened 2024-05-23 09:37 UTC
### Description

The issue surfaces when we employ FontLoader and introduce another element. Portions of the font undergo complete distortion. It operates smoothly until additional elements are introduced to the scene. This glitch appears to impact multiple tabs concurrently. Thus, if it manifests on one tab, it influences all fonts across every tab, regardless of their prior functionality. I also tried different three.js versions - same issue every time.

### Reproduction steps

1. Update Chrome to latest version (on MacOS, not sure if it happens on Windows)
2. Run the Code (it should work fine), remove comment from line 44: Bug should appear

### Code

```js
import * as THREE from "https://esm.sh/three";
import { FontLoader } from "https://esm.sh/three/examples/jsm/loaders/FontLoader.js";
import { TextGeometry } from "https://esm.sh/three/examples/jsm/geometries/TextGeometry.js";

window.addEventListener('DOMContentLoaded', init);
function init() {
    const scene = new THREE.Scene();
    const camera = new THREE.PerspectiveCamera(75, window.innerWidth / window.innerHeight, 0.1, 1000);
    camera.position.z = 40;
    const renderer = new THREE.WebGLRenderer();
    renderer.setPixelRatio( window.devicePixelRatio );
    renderer.setSize(window.innerWidth, window.innerHeight);
	renderer.setClearColor( 0x2B2B2B, 1 );
    document.body.appendChild(renderer.domElement);

    const ambientLight = new THREE.AmbientLight(0xffffff, 0.5);
    scene.add(ambientLight);

    const directionalLight = new THREE.DirectionalLight(0xffffff, 0.5);
    directionalLight.position.set(1, 1, 1).normalize();
    scene.add(directionalLight);

    const loader = new FontLoader();
    loader.load('https://raw.githubusercontent.com/mrdoob/three.js/dev/examples/fonts/helvetiker_regular.typeface.json', function (font) {
        const textGeometry = new TextGeometry('Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore', {
            font: font,
            size: 1,
            height: 0.1
        });
        const material = new THREE.MeshBasicMaterial({ color: 0xffffff, transparent: true, opacity: 1 });
        const textMesh = new THREE.Mesh(textGeometry, material);
        scene.add(textMesh);

        textGeometry.computeBoundingBox();
        textMesh.position.x = -0.5 * (textGeometry.boundingBox.max.x - textGeometry.boundingBox.min.x);
        textMesh.position.y = -0.5 * (textGeometry.boundingBox.max.y - textGeometry.boundingBox.min.y);
    });

    const material = new THREE.MeshBasicMaterial({ color: 0xFF0000 });
    const geometry = new THREE.BoxGeometry( 1, 1, 1 ); 
    const cube = new THREE.Mesh(geometry, material);
    cube.position.x = 0;
    cube.position.y = 0;
    cube.position.z = 10;
    //scene.add(cube);

    function onWindowResize() {
        camera.aspect = window.innerWidth / window.innerHeight;
        camera.updateProjectionMatrix();
        renderer.setSize(window.innerWidth, window.innerHeight);
    }
    window.addEventListener('resize', onWindowResize, false);

    function animate() {
        requestAnimationFrame(animate);
        renderer.render(scene, camera);
    }
    animate();
}
```

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/clmsvie/od94w0yj/7/)

### Screenshots

![image](https://github.com/mrdoob/three.js/assets/66367108/92a16932-fe11-42f2-b74e-89f9c4acc90e)

### Version

r164.1

### Browser

Chrome

### OS

MacOS

**Comment by Mugen87** [comment] 2024-05-23 09:45
I'm unable to reproduce on macOS 14.4.1 and Chrome 125.0.6422.77. This is how the scene looks with and without the red cube.

<img width="1478" alt="image" src="https://github.com/mrdoob/three.js/assets/12612165/8aaf7a69-d920-4e86-aab7-dbd826f5ee99">


<img width="1475" alt="image" src="https://github.com/mrdoob/three.js/assets/12612165/be871c2f-56e0-4753-bfc0-67cb50847927">

This issue might be device-related so please try to reproduce it on other systems.

**Comment by csimlinger** [comment] 2024-05-23 09:47
I tried it on four different macs. The issue occurred on three of these four.

**Comment by Mugen87** [comment] 2024-05-23 09:48
Have you tried different browsers as well? What happens in Firefox and Safari?

**Comment by csimlinger** [comment] 2024-05-23 09:56
Here is the GPU Report: https://pastebin.com/cTeNs0m4

Strangely it worked for 10 minutes on another computer, without us changing anything.
Problem happens now again all the time on 3 of 4 computers.

**Comment by Mugen87** [comment] 2024-05-23 10:23
> Strangely it worked for 10 minutes on another computer, without us changing anything.

Do all affected macs use Intel+AMD? Can you also reproduce on a mac with M processor?

If the issue might temporarily disappear, I wonder if it makes a difference if the discrete AMD GPU is used or the integrated Intel graphics (in your case UHD Graphics 630). Since you are using a MacBook, this depends on battery usage and system settings.

I'm not sure this is works anymore but it was possible in the past to go in "System Preferences" - "Energy Saver" and disable "Automatic graphics switching". This should force the usage of a discrete GPU.

**Comment by csimlinger** [comment] 2024-05-23 10:38
I was able to disable the "Automatic graphics switching", the problem still occurs.
Unfortunately we don't have any M1 Mac here right now...

**Comment by Mugen87** [comment] 2024-05-23 14:15
It seems this is a GPU related issue. Unfortunately, there is nothing what we can do on our side. The problem should be reported to the Chromium bug tracker (https://issues.chromium.org/issues).

Please report the issue there including the live example, the GPU report as a txt file attachment and the findings from this discussion (the rendering issue happens exclusively with Chrome on macOS with Intel+AMD).

I could imagine that the live example is still too complex as a reproduction case for the Chromium team so I wonder if we can break it further down. Do you ass any rendering issues with examples from the official website? https://threejs.org/examples/

There are some font/text examples that might show glitches on your hardware similar to your fiddle. Besides, it would be interesting to know if affected devices have issues with non-text related examples as well.

**Comment by csimlinger** [comment] 2024-05-23 18:03
Oh... thanks for the info, I will report it.

Regarding glitches of the examples, looked trough many of them and I encounter these (not 100% sure if they are supposed to look like that, but I guess they are supposed to look differently):

<img width="998" alt="image" src="https://github.com/mrdoob/three.js/assets/66367108/ae492b9a-ee49-487e-83fd-21b5ce7fc86c">
<img width="1357" alt="image" src="https://github.com/mrdoob/three.js/assets/66367108/2637dceb-8080-4a56-9a4a-33fe84e96fb7">
<img width="1054" alt="image" src="https://github.com/mrdoob/three.js/assets/66367108/b1932ec4-d741-461b-ba3e-9f9e2e213d66">
<img width="1033" alt="image" src="https://github.com/mrdoob/three.js/assets/66367108/22d39d02-6472-493d-89cb-bc19e653d2e0">

**Comment by Mugen87** [comment] 2024-05-23 18:42
The first and last two are definitely wrong. The logarithmic depth buffer demo shows glitches on the left side which is intended.

So there seems to be a more general GPU driver related issue on these devices. The root cause is not necessarily related to text rendering. It seems the 3MF demo (the one with the vehicle) could be a good reproduction test case since does not involve font or text related components.

**Comment by Mugen87** [comment] 2024-05-24 09:33
Closing. This needs to be reported to the browser vendor.

**Closed by Mugen87** 2024-05-24 09:33 UTC
Labels: Device Issue
