### ISSUE TITLE
ParticleCanvasMaterial 用哪个方法代替了？？？

### ISSUE THREAD

**Issue by 15026522974** [mrdoob/three.js#17090] opened 2019-07-25 08:25 UTC
##### Description of the problem

This form is for three.js bug reports and feature requests only.

This is NOT a help site. Do not ask help questions here.
If you need help, please use the [forum](https://discourse.threejs.org/) or [stackoverflow](http://stackoverflow.com/questions/tagged/three.js).

Describe the bug or feature request in detail.

Always include a code snippet, screenshots, and any relevant models or textures to help us understand your issue.

Please also include a live example if possible. You can start from these templates:

* [jsfiddle](https://jsfiddle.net/3foLr7sn/) (latest release branch)
* [jsfiddle](https://jsfiddle.net/qgu17w5o/) (dev branch)
* [codepen](https://codepen.io/anon/pen/aEBKxR) (latest release branch)
* [codepen](https://codepen.io/anon/pen/BJWzaN) (dev branch)

##### Three.js version

- [ ] Dev
- [ ] r106
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment] 2019-07-25 09:27
According to the translator, it seems your question is duplicate of #16925

Hint: `ParticleCanvasMaterial` was only intended for `THREE.CanvasRenderer` which was also removed from the library with `R98` (see #15029).

**Closed by Mugen87** 2019-07-25 09:27 UTC
