### ISSUE TITLE
webgl_camera_logarithmicdepthbuffer lighting seems to be wrong on very high sizes

### ISSUE THREAD

**Issue by gero3** [mrdoob/three.js#8825] opened 2016-05-06 11:20 UTC
##### Description of the problem

as you can see the dot of gargantuan is blue, dot of ludicrous is white. But the dot of mind boggling is black while the text is red.
...
![image](https://cloud.githubusercontent.com/assets/155535/15071543/c10a6efc-138c-11e6-9300-248527bb4b30.png)
##### Three.js version
- [x] Dev
- [x] r76
- [ ] ...
##### Browser
- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer
##### OS
- [ ] All of them
- [x] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by bhouston** [comment] 2016-05-06 12:45
IT would be cool to add this to example a mode where you can see the depth buffer in some way - such as it showed a grayscale limited to a near/far that one specifies -- so one can zoom into distance ranges and ensure that it is correct.

**Comment by Mugen87** [comment] 2024-03-07 15:41
In the meanwhile, the sphere isn't black anymore. You can see the effect of the scene's ambient light but not of the directional light. Since this effect is the same for both sides, the issue is unrelated to depth precision. Here is a more isolated test case for reproduction:

https://jsfiddle.net/Lpb31oaf/1/

Using `1e18` instead of `1e19` as the mesh's scale restores the effect of the directional light with out without enabled logarithmic depth buffer. 

I suspect the issue is that with such large numbers `highp` doesn't provide enough precision for the decimals which breaks the lighting calculation. In this case, it's probably best to mark the issue as a `Won't fix` and close it.

**Comment by gero3** [comment] 2024-03-09 15:34
@Mugen87 I agree.

**Closed** 2024-03-09 17:16 UTC
Labels: Needs Investigation
