### ISSUE TITLE
102 breaks makeTextSprite

### ISSUE THREAD

**Issue by sanjaysk2000** [mrdoob/three.js#16048] opened 2019-03-24 09:04 UTC
##### Description of the problem
I'm using makeTextSprite from stemkoski examples. I found this problem in 102 as shown in the following fiddles.

[Fiddle showing problem with 102](https://jsfiddle.net/sanjaysk/c9nt80oh/)

[Fiddle with 101, no problem](https://jsfiddle.net/sanjaysk/7v0ep1kb/)

This form is for three.js bug reports and feature requests only.

This is NOT a help site. Do not ask help questions here.
If you need help, please use the [forum](https://discourse.threejs.org/) or [stackoverflow](http://stackoverflow.com/questions/tagged/three.js).

Describe the bug or feature request in detail.

Always include a code snippet, screenshots, and any relevant models or textures to help us understand your issue.

Please also include a live example if possible. You can start from these templates:

* [jsfiddle](https://jsfiddle.net/3foLr7sn/) (latest release branch)
* [jsfiddle](https://jsfiddle.net/qgu17w5o/) (dev branch)
* [codepen](https://codepen.io/anon/pen/aEBKxR) (latest release branch)
* [codepen](https://codepen.io/anon/pen/BJWzaN) (dev branch)

##### Three.js version

- [ ] Dev
- [x] r102
- [ ] ...

##### Browser

- [] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by looeee** [comment] 2019-03-24 09:34
It says at the top of stemkoski examples page:

> Last updated: 23 August 2013. Compatible with Three.js version 60.

You should not expect them to work straight away with newer versions. If you need more help with this, please ask over on the [forum](https://discourse.threejs.org/)

**Comment by Mugen87** [comment] 2019-03-24 10:29
Another duplicate of #15896 😞

**Closed by Mugen87** 2019-03-24 10:29 UTC
