### ISSUE TITLE
WebGLLights state and its hashing produce unintended material reinitialization

### ISSUE THREAD

**Issue by Usnul** [mrdoob/three.js#14121] opened 2018-05-23 14:05 UTC
`WebGLLights` is used to store lighting state.
`WebGLLights.hash` property is used to determine whether or not a material needs to be re-built.

https://github.com/mrdoob/three.js/blob/bd63a6cc8dd7fe11b530410fab9f67a9de359be8/src/renderers/WebGLRenderer.js#L1479-L1482

The way `hash` is built, it includes unique reference to `WebGLLights` instance:
https://github.com/mrdoob/three.js/blob/efeb95f10790ab4755171584139d5344177f2713/src/renderers/webgl/WebGLLights.js#L319

constructor:
https://github.com/mrdoob/three.js/blob/efeb95f10790ab4755171584139d5344177f2713/src/renderers/webgl/WebGLLights.js#L103-L111

this means that if you have 2 instances of `WebGLLights` and they are identical, except for `id` - you will end up rebuilding materials as you switch between these instances - inefficient.

Another problem with the current approach is that it is probabilistic, it's possible that `hash` remains the same even though lighting has changed.

I propose following:
* remove `id` from `hash` calculation
* use a fast hashing function to compute 64bit hash(javascript `number` is IEEE 64-bit Float) instead of using a string
* pass more than just number of lights into the `hash` (as long as that makes sense).

**Comment by mrdoob** [comment] 2018-05-23 19:54
> this means that if you have 2 instances of `WebGLLights` and they are identical,

When would that happen? 2 different WebGLRenderers rendering the same scene?

**Comment by Usnul** [comment] 2018-05-23 23:18
not quite, it depends on `scene.id` and `camera.id` 
Here:
https://github.com/mrdoob/three.js/blob/bd63a6cc8dd7fe11b530410fab9f67a9de359be8/src/renderers/webgl/WebGLRenderStates.js#L71-L86

**Comment by Usnul** [comment] 2018-05-23 23:32
lets say you want to render the same scene from 2 points of view. A simple example would be Mirror class. But there are a lot of other examples where having multiple cameras could be useful. Scene ID makes me skeptical also, the fact that scene ID is the same means very little for the content of that scene between frames, or indeed having two scenes that use the same materials and lighting setup.

**Comment by WestLangley** [comment] 2018-07-15 20:33
>or indeed having two scenes that use the same materials and lighting setup.

This is the use case in #14477.

In that case, the work-around is to clone the material, and not share it:
```javascript
var mesh1 = new THREE.Mesh( geometry, material );
scene1.add( mesh1 );

var mesh2 = new THREE.Mesh( geometry, material.clone() );
scene2.add( mesh2 );
```

This is either a limitation or a bug. If we consider this a limitation, we should document both the limitation and the work-around somewhere.

I'm thinking it would be preferable to consider this a bug.

**Comment by Mugen87** [comment] 2018-07-16 09:58
Avoiding calls of `initMaterial` would be nice but the flexibility of `three.js` makes it hard to provide an approach that works without causing fatal rendering problems like mentioned in #12883. I'm not sure how such a solution could look like.

I personally consider this issue as a limitation of `three.js` in order to ensure correct rendering.

**Comment by Mugen87** [comment] 2018-07-16 10:05
BTW: The root cause of the issue is the fact that it's possible to perform nested render calls via hooks like `onBeforeRender()`. The current implementation of `WebGLRenderer` ensures a correct result for this kind of rendering.

**Comment by Usnul** [comment] 2018-07-16 11:55
@Mugen87 
The hashing is bogus. If you generate a unique ID and hash that too - what's the point really? I'm not sure who wrote that hashing function but it could use some improvements.

**Comment by Mugen87** [comment] 2018-07-16 13:55
>  I'm not sure who wrote that hashing function but it could use some improvements.

I suggest you do a PR that demonstrates a concrete improvement. Make sure to check all examples that utilize `onBeforeRender()` before submitting.

**Comment by carstenschwede** [comment] 2020-06-15 12:29
Do I understand correctly that this applies to a simple CubeCamera-setting as well, i.e. in a scene with only light-based material and a cube-camera ([jsFiddle](https://jsfiddle.net/zkc918od/)):

This won't cause light state changes (and calls to `.initMaterial()`) at every frame:

```
function animate() {
    requestAnimationFrame( animate ); 
    renderer.render( scene, camera );
}
```

But this does:

```
function animate() {
    requestAnimationFrame( animate ); 
    cubeCamera.update( renderer, scene );
}
```

because of CubeCamera rendering 6 different PerspectiveCameras? However, this is not the case for ArrayCamera. Are ArrayCameras exempt because their cameras are assumed to be

- close to each other
- pointing in similar direction

and thus are less susceptible to missing light updates? I think I still have troubles understanding why `.initMaterials()` calls are needed for some camera updates but not for others - if they are in general, is there an option to make hash calculation faster? `.cloneUniforms()` is really dragging my fps.

**Comment by Mugen87** [comment] 2020-06-15 13:57
> and thus are less susceptible to missing light updates?

The problem is that each camera has a different view matrix and thus affecting light computations.

**Comment by carstenschwede** [comment] 2020-06-15 14:53
Exactly. So the light calculations in the THREE.ArrayCamera are actually wrong? Cause there are no calls to `.initMaterial()` for THREE.ArrayCamera even though they all have different view matrices.

**Comment by Mugen87** [comment] 2020-06-15 14:57
> Cause there are no calls to .initMaterial() for THREE.ArrayCamera even though they all have different view matrices.

I don' think this is true. The array camera itself is not used for rendering.

https://github.com/mrdoob/three.js/blob/92ad8c5f4e8a4aa666343ab92b3fd6260fe9e4ce/src/renderers/WebGLRenderer.js#L1427-L1449

And the render state is set in `renderobject()`.

https://github.com/mrdoob/three.js/blob/92ad8c5f4e8a4aa666343ab92b3fd6260fe9e4ce/src/renderers/WebGLRenderer.js#L1464

**Comment by Mugen87** [comment] 2020-06-15 14:58
Any chances to demonstrate this with a fiddle?

**Comment by carstenschwede** [comment] 2020-06-15 15:08
Thanks for taking a look at this. I ran the [THREE.js ArrayCamera example](https://threejs.org/examples/?q=array#webgl_camera_array) and my performance log doesn't show repeated calls to `.initMaterial()` which is why I wondered why they are required for CubeCamera but not for ArrayCamera. (`.initMaterial()` is slow for my app due to `.cloneUniforms()`).

**Comment by Mugen87** [comment] 2020-06-15 15:19
> .initMaterial() is slow for my app due to .cloneUniforms()

Can you please show the code or call stack that triggers `cloneUniforms()` from `initMaterial()`?

**Comment by carstenschwede** [comment] 2020-06-15 17:16
The [example](https://jsfiddle.net/zkc918od/) from above exhibits this.

Call stack is `.initMaterial()`->`.getParameters()`->`.getShaderObject()`->`.cloneUniforms()`

**Comment by Mugen87** [comment] 2020-06-16 09:22
Many thanks for sharing the performance data. I've thought about this issue and come up with a potential improvement: #19673

**Comment by Mugen87** [comment] 2020-06-16 09:36
See #19673.

**Comment by Mugen87** [comment] 2020-06-16 10:57
Technically, comparing `CubeCamera` with `ArrayCamera` right now is like comparing apples and oranges. The problem is that `CubeCamera` has to perform calls of `WebGLRenderer.render()` for each camera since it has to alter the destination render target for each camera. This is not true for array camera which needs only a single call of `WebGLRenderer.render()` since it's explicitly designed for single-pass rendering.

That said, there is still room for performance improvements for `CubeCamera` since redundant logic is executed when producing the cube render target.

@mrdoob Have you ever considered to derive `CubeCamera` form `ArrayCamera`?

**Comment by carstenschwede** [comment] 2020-06-16 12:37
This would be awesome if `ArrayCamera` had the option to not only render to different viewports, but to different CubeFaces.

Devil is probably in the details, e.g. `ArrayCamera` currently only has one frustum and would need frustum updates before rendering subcameras.

I wonder if this is the reason why `StereoCamera` is not derived from  `ArrayCamera`? I.e. you would have to set a larger combined frustum on the `ArrayCamera` to make sure the subcameras do not cull differently.

**Comment by Mugen87** [comment] 2020-06-16 15:32
> Devil is probably in the details, e.g. ArrayCamera currently only has one frustum and would need frustum updates before rendering subcameras.

Yeah, the problem is you still need a specific view frustum culling per sub camera. On the other hand, other tasks are redundant like updating the world matrices of the scene graph or recomputing shadow maps per sub camera.

**Comment by Mugen87** [comment] 2020-06-16 15:39
Anyway, I have the feeling this discussion went a bit off-topic. Besides, the implementation of `WebGLLights` has slightly changed. It does not compare hashes anymore (`materialProperties.lightsHash !== lights.state.hash`) anymore but just a single version number. 

I actually like the idea of making `initMaterial()` faster when no shader compilation is required. Such optimizations might be valuable for  #15047.

**Comment by Mugen87** [comment] 2021-02-26 09:59
The renderer has changed at various places since this issue was originally reported. The performance of `initMaterial()` was improved via #19673, render states (and lists) are only created per scene now (#20422, #21254) and light uniforms can now be updated without triggering `initMaterial()` via `WebGLLights.setupView()`. `WebGLLights` also performs no string concatenation anymore (#14588) and simplified the usage of the internal hash (#16581).

Overall I think it's best to close the issue and open a new one if there are still performance issues.

**Closed by Mugen87** 2021-02-26 09:59 UTC
Labels: Suggestion
