### ISSUE TITLE
Hope to add the function of lofting entities through curve groups.

### ISSUE THREAD

**Issue by zgpnuaa** [mrdoob/three.js#24507] opened 2022-08-17 03:55 UTC
Lofting is a important function of 3d modeling.
![image](https://user-images.githubusercontent.com/38033949/185031296-e00659da-c70e-4a5f-9e96-d4379987c44f.png)
![image](https://user-images.githubusercontent.com/38033949/185031331-d9a7971e-bca2-43df-852a-81663609c58c.png)

**Comment by Mugen87** [comment] 2022-08-17 10:09
This feature is a modeling technique used in CAD programs. TBH, it feels a bit out of scope that add something like this to repository.

**Comment by LeviPesin** [comment] 2022-08-17 10:19
But we already have things like ExtrudeGeometry and ParametricGeometry, wouldn't this be a nice addition to them?

**Comment by Mugen87** [comment] 2022-08-17 10:35
There is only very limited support for freeform surface modelling via the `NURBS` classes. `ExtrudeGeometry`, `LatheGeometry`, and `ParametricGeometry` do not really belong to this area. Like CSG, freeform surfaces are a very specific topic and I see related logic in third party projects.

**Comment by mrdoob** [comment] 2022-08-17 22:50
If anyone is up for doing a `LoftGeometry`... we could just keep it in examples.

**Comment by donmccurdy** [comment] 2022-12-09 18:54
Is this a duplicate of the issue below?
- https://github.com/mrdoob/three.js/issues/23708

**Comment by Mugen87** [comment] 2022-12-09 18:56
Good catch! This issue is indeed a duplicate!

**Comment by Mugen87** [comment] 2022-12-09 19:09
Merging into #23708.

**Closed by Mugen87** 2022-12-09 19:09 UTC
Labels: Examples
