### ISSUE TITLE
Bad stuttering in webaudio_orientation on Chrome

### ISSUE THREAD

**Issue by looeee** [mrdoob/three.js#15739] opened 2019-02-08 02:49 UTC
The [webaudio_orientation](https://threejs.org/examples/#webaudio_orientation) example has extremely bad stuttering on Chrome for Android.

The example seems fine on Edge and Firefox (desktop) and Firefox (Android). Other audio examples are not stuttering on Chrome, that I noticed. 

Chromium bug report: https://bugs.chromium.org/p/chromium/issues/detail?id=930005

Browsers: 
Chrome Android 72.0.3626.96 
Chrome Desktop  72.0.3626.96 (Official Build) beta (64-bit)

**Comment by Mugen87** [comment] 2019-02-08 10:43
After testing on my Pixel 1 and Chrome (72.0.3626.96) I've only noticed two or three times a stuttering sound when entering/leaving the directional cone. In all other cases, the audio sounds fine. Maybe the stuttering depends a bit on the hardware?

**Comment by arpu** [comment] 2019-02-09 01:25
looks likle revert https://github.com/mrdoob/three.js/commit/e5e4cf05c88af1fa5d4af366b5d5e3599f1dc000#diff-cbc8b9ecf23d32d7a41d8ddab76a8f0c 
solved it for me

**Comment by Mugen87** [comment] 2019-02-09 09:32
It seems @looeee 's Chromium bug report was actually classified as a bug. So this issue might get fixed on the browser side.

**Comment by hoch** [comment] 2019-02-13 23:39
Sorry for the late response. Do you all believe this is a regression? Then we need to find the offending revision.

/cc @rtoy

**Comment by Mugen87** [comment] 2019-02-14 10:59
> Do you all believe this is a regression?

Um, I'm not sure. But I can't remember such a stuttering when implementing `webaudio_orientation` last summer (#14243) and when we introduced the usage of `linearRampToValueAtTime()` via see #14393

BTW: The stuttering also happens in Chrome 72.0.3626.109 on macOS 10.14.3 when you move some time the camera in `webaudio_orientation`.

**Comment by hoch** [comment] 2019-02-26 18:35
@Mugen87 Could you file a bug with a simple repro case on crbug.com? Here's a shortcut for the [webaudio bug template](https://bugs.chromium.org/p/chromium/issues/entry?components=Blink%3EWebAudio).

**Comment by Mugen87** [comment] 2019-02-26 19:11
@hoch There was already file a bug by @looeee right here:

https://bugs.chromium.org/p/chromium/issues/detail?id=930005

**Comment by hoch** [comment] 2019-02-26 19:21
Thanks! Will look into it soon!

**Comment by looeee** [comment] 2019-04-27 05:25
Hmm, this was closed as "won't fix" 🙁 
If anybody else can test it and still gets the same behaviour, please report that on the Chromium bug linked above. Otherwise, we may be stuck with this for some time.

**Comment by mrdoob** [comment] 2019-04-27 07:50
Just added a couple of comments 🙂

**Comment by mrdoob** [comment] 2019-04-27 07:50
@Mugen87 Just to confirm, when the camera is behind the wall, we shouldn't hear any sound, correct?

**Comment by yomboprime** [comment] 2019-04-27 08:23
> @Mugen87 Just to confirm, when the camera is behind the wall, we shouldn't hear any sound, correct?

I still hear it, though attenuated, on FF desktop.

**Comment by Mugen87** [comment] 2019-04-28 12:11
> @Mugen87 Just to confirm, when the camera is behind the wall, we shouldn't hear any sound, correct?

No, you should still hear the sound very quietly(with 0.1 volume).

**Comment by Mugen87** [comment] 2019-12-09 11:00
I'm not able to reproduce this issue on Android with Chrome 78.0.3904.108. Closing for now.

**Closed by Mugen87** 2019-12-09 11:00 UTC
Labels: Browser Issue

**Comment by looeee** [comment] 2019-12-09 15:10
Yup, seems to be fixed! 😁
