### ISSUE TITLE
Face visibility based on attribute value support

### ISSUE THREAD

**Issue by HasanAyan** [mrdoob/three.js#9394] opened 2016-07-23 15:30 UTC
##### Description of the problem

I am working on a Three.js project which requires thousands of unique meshes to be rendered. Since number of objects have big impact on rendering performance I merged those objects into single mesh (manually, not using geometry.merge() function) and created "pseudo objects" which keeps parent mesh reference and index data (faceIndexStart, faceIndexEnd) so that I can manipulate color and position of individual objects using those references. (I could not find a built in way to do that, please let me know if there is one). At the end I achieved a super performant scene.

However, I would like to manage visibility of those individual objects, too. I know I can use multimaterial but this will increase number of drawcalls which will have random effect on the performance.

For example; let's say I have a model with 10000 individual objects and I create single mesh by merging  position and index vectors and create 10000 pseudo objects which just keep a reference to this mesh and information about this individual objects face indices. If I use multimaterial and hide 2000 of these objects during runtime. In the best case scenario those objects will be continuous in my buffers and I will have just one more draw call but if they are at random places I can have  up to 1+2000*2 draw calls. One may suggest sortByMaterial function in that case but than it will mess up with order of my buffer attributes and my pseudo objects will be useless. (Not sure, correct me if I am wrong);
##### Suggestion

Three.js already supports everything neccessary to create single mesh out of lot's of meshes and pseudo meshes to manipulate position data of every single mesh. I can also manipulate color of those individual objects using vertex colors. It would be really helpful if materials could have THREE.faceVisibility or THREE.vertexVisibility as a value for visibility property and shader code to include logic to discard fragments based on "visibility" attribute value if one of those values I suggested passed on visibility property of a material.

Currently I am overriding MeshPhong shader code by string replacements to achieve this desired solution and it feels dirty/hacky. This suggestion seems to me easy to implement and doesn't seem to have any downsides.

EDIT: Here is the ugly/hacky thing I do:

``` javascript
var vert = THREE.ShaderChunk['meshphong_vert'];

        THREE.ShaderChunk['meshphong_vert'] = `attribute float hidden;
varying float vhidden;
` + vert.replace('void main() {', `void main() {
vhidden=hidden;`);

        var frag = THREE.ShaderChunk['meshphong_frag'];
        THREE.ShaderChunk['meshphong_frag'] = `varying float vhidden;
` + frag.replace('void main() {', `void main() {
if(vhidden>0.0)
{
    discard;
}`);


        THREE.ShaderLib['phong'] = {

            uniforms: THREE.UniformsUtils.merge([

                THREE.UniformsLib['common'],
                THREE.UniformsLib['aomap'],
                THREE.UniformsLib['lightmap'],
                THREE.UniformsLib['emissivemap'],
                THREE.UniformsLib['bumpmap'],
                THREE.UniformsLib['normalmap'],
                THREE.UniformsLib['displacementmap'],
                THREE.UniformsLib['fog'],
                THREE.UniformsLib['lights'],

                {
                    "emissive": { value: new THREE.Color(0x000000) },
                    "specular": { value: new THREE.Color(0x111111) },
                    "shininess": { value: 30 }
                }

            ]),

            vertexShader: THREE.ShaderChunk['meshphong_vert'],
            fragmentShader: THREE.ShaderChunk['meshphong_frag']
        };
```

**Comment by HasanAyan** [comment] 2016-07-25 07:34
I can implement my suggestion and do a pull request if someone is interested in helping me.

**Comment by HasanAyan** [comment] 2016-07-25 11:32
Here is what I need; The code piece below is from meshphong_vert.glsl; 
```
#ifndef FLAT_SHADED
	varying vec3 vNormal;
#endif
```

```
and, for example, I need to add following to meshphong_vert.glsl
...
#ifndef PER_FACE_VISIBILITY
        attribute float hidden;
	varying float vHidden;
#endif
...
void main(){
vHidden = hidden;
...
}
```


but what does actually "ifndef PER_FACE_VISIBILITY mean?" I could not find what controls the value of it....

And note; the reason I wanted to use "hidden" flag is to provide ease of initialization of the attribute. This way you can just initialize the array and if you don't assign a value it will be all zeros so everything will be visible unless it's overridden later on.

Can you help me @mrdoob ?

**Comment by Mugen87** [comment] 2019-12-28 13:47
Closing. The idea is to use `InstancedMesh` if you have to render multiple unique meshes. You can then use instanced attributes like `color` or `visibility` to add further per-mesh information. [Material.onBeforeCompile()](https://threejs.org/docs/index.html#api/en/materials/Material.onBeforeCompile) provides one way to enhance the built-in materials with additional logic will be necessary if you want to use/evaluate additional attributes. 

Check out #18256 for a complete example.

**Closed by Mugen87** 2019-12-28 13:47 UTC
Labels: Suggestion

**Comment by donmccurdy** [comment] 2019-12-28 19:56
> The idea is to use InstancedMesh if you have to render multiple unique meshes

Well, with the caveat that if the meshes are _fully_ unique this won't work... they'd need to at least share base geometry. But transform, color, UV offsets etc. could all be modified in a shader, so I do think many users could go that route.

As written, this is effectively a duplicate of https://github.com/mrdoob/three.js/issues/16403, so agreed that we can close it.

That said... if you can group or reorder your mesh indices carefully, I suspect you could get better performance by hiding things with drawRange or dynamic attribute updates, rather than fragment shader discards.

**Comment by Mugen87** [comment] 2019-12-29 09:17
Yes, sorry. I totally forgot to mention that having a shared geometry is necessary for using instanced rendering.
