### ISSUE TITLE
CanvasRenderer "me.isEmpty" is not a function

### ISSUE THREAD

**Issue by verybigelephants** [mrdoob/three.js#8154] opened 2016-02-17 11:03 UTC
when trying to swap the webgl renderer for a canvasRenderer i get this error `Uncaught TypeError: me.isEmpty is not a function(…)` when calling `.render(scene, camera)` on the renderer 

example code:

```
    var scene=null;
    var renderer=null;
    var camera=null;
    var controls=null;
    var container=$("#some_container");

    // set the scene size
    var WIDTH = container.width(),
        HEIGHT = container.height();
    // set some camera attributes
    var VIEW_ANGLE = 45,
    ASPECT = WIDTH / HEIGHT,
    NEAR = 1,
    FAR = 10000;
    renderer = new THREE.CanvasRenderer({ alpha:true });
        renderer.setSize(WIDTH, HEIGHT);
    container.append(renderer.domElement);

    camera = new THREE.PerspectiveCamera(  VIEW_ANGLE, ASPECT, NEAR, FAR  );  //THREE.PerspectiveCamera( 45, window.innerWidth / window.innerHeight, 1, 1000 );
        camera.position.z = 50;

    controls = new THREE.TrackballControls( camera, renderer.domElement );
        controls.minDistance = 40;
        controls.maxDistance = 100;

    scene = new THREE.Scene();
        scene.add(camera);
    var ambientLight = new THREE.AmbientLight( 0x404040 );
        scene.add(ambientLight);
    var pointLight = new THREE.PointLight( 0xFFFFFF );
        pointLight.position.x = 10;
        pointLight.position.y = 50;
        pointLight.position.z = 130;
        scene.add(pointLight);

    //try rendering
        renderer.render( scene, camera );
```

**Comment by mrdoob** [comment] 2016-02-17 11:38
Can you provide a working jsfiddle that shows the error?

**Comment by Mugen87** [comment] 2018-02-07 21:13
Closing. We can reopen if the issue is demonstrated in a [live example](https://jsfiddle.net/f2Lommf5/).

**Closed by Mugen87** 2018-02-07 21:13 UTC

**Comment by verybigelephants** [comment] 2018-02-24 20:39
i'm sorry i am writing this late but i totally forgot about it in my bookmarks

here https://jsfiddle.net/f2Lommf5/1879/

when you swap canvas renderer for webgl renderer it throws that error

**Comment by Mugen87** [comment] 2018-02-24 20:56
Update your fiddle: https://jsfiddle.net/f2Lommf5/1885/

`Projector` needs to be included separately now.

**Comment by verybigelephants** [comment] 2018-02-26 09:32
ah, thank you! it's kind of strange you have to include a class called `Projector` separately when you want to work with `CanvasRenderer` and not with `WebGLRenderer`. i mean, i wouldn't have guessed that

**Comment by looeee** [comment] 2018-02-26 10:15
@verybigelephants always check the official examples for details on how to use things. 

If you look through the [canvas renderer examples](https://threejs.org/examples/?q=canvas), you'll see that `Projector.js` is always included alongside the `CanvasRenderer.js`.

**Comment by verybigelephants** [comment] 2018-02-28 09:48
"\o_O/" just saying from a generic user's point of view
