### ISSUE TITLE
Node order changes at each gtlf load

### ISSUE THREAD

**Issue by ketourneau** [mrdoob/three.js#22863] opened 2021-11-19 13:32 UTC
**Describe the bug**

Node order changes at each gtlf load.
If 2 objects with 2 different material colours are at the same position, the rendering changes at each loading.

**To Reproduce**

1. Go to [codepen gltf loader](https://codepen.io/blocovin/pen/vYJPNbm)
2. Reload the page
3. Observe visual differences between each load

or

1. Go to [ThreeJS editor](https://threejs.org/editor/)
2. Import [draco.gltf](https://blocinbloc-development-file-service-v2.s3.fr-par.scw.cloud/draco-debug.gltf)
3. Observe node order changes

**Expected behavior**

The order of the objects must respect the one defined in the gltf file.

**Screenshots**

First load (codepen):
<img width="830" alt="first_load" src="https://user-images.githubusercontent.com/39763266/142625650-58e510d4-5394-4704-8d0c-6cc4a071b20a.png">

Second load (codepen):
<img width="834" alt="second_load" src="https://user-images.githubusercontent.com/39763266/142625675-c8fcbffb-3c3e-484d-a489-945171a53bc4.png">

First load (threejs editor):
<img width="433" alt="FirstLoad" src="https://user-images.githubusercontent.com/39763266/142630624-1fb4661a-a825-462d-ab28-b9f555a3b448.png">

Second load (threejs editor):
<img width="260" alt="SecondLoad" src="https://user-images.githubusercontent.com/39763266/142630688-632ef1b7-d080-4b3a-b6da-cf2be0b84c11.png">

**Platform:**

 - Device: [Desktop]
 - OS: [MacOS]
 - Browser: [Chrome 96, Firefox 94]
 - Three.js version: [r134]

**Comment by Mugen87** [comment] 2021-11-19 14:43
I guess this is a duplicate of #18774.

**Closed** 2021-11-21 09:17 UTC
Labels: Duplicate
