### ISSUE TITLE
Console warnings in Firefox 49

### ISSUE THREAD

**Issue by mrdumb** [mrdoob/three.js#9966] opened 2016-10-29 06:44 UTC
All the Three.js samples involving at least a texture have this issue:

**Error: WebGL: texImage2D: Chosen format/type incured an expensive reformat: 0x1908/0x1401**

**Comment by mrdumb** [comment] 2016-10-29 09:49
In Firefox Nightly 52:

**Error: WebGL: texImage2D: Incurred CPU pixel conversion, which is very slow.three.min.js:118:508
Error: WebGL: texImage2D: Chosen format/type incurred an expensive reformat: 0x1908/0x1401**

**Comment by Mugen87** [comment] 2016-10-29 12:39
Duplicate of #9109

**Closed** 2016-10-31 15:59 UTC
Labels: Duplicate
