### ISSUE TITLE
 value was not null but undefined  in some env

### ISSUE THREAD

**Issue by allrightzhu** [mrdoob/three.js#19824] opened 2020-07-10 02:27 UTC
such as ：
 extensions.get( 'OES_vertex_array_object' )  undefined
_canvas.getContext( “webgl2”, contextAttributes )  undefined

then the code got error.

**Comment by donmccurdy** [comment] 2020-07-10 03:22
You'll need to provide more details for us to reproduce this error. As it is we cannot debug the issue. From the "new issue" template, please notice:

***

Describe the bug or feature request in detail.

Always include a code snippet, screenshots, and any relevant models or textures to help us understand your issue.

Please also include a live example if possible. You can start from these templates:

* [jsfiddle](https://jsfiddle.net/hyok6tvj/) (latest release branch)
* [jsfiddle](https://jsfiddle.net/c5m1kazu/) (dev branch)

**Comment by Mugen87** [comment] 2020-07-10 09:20
Be aware that extensions test that worked with WebGL 1 won't work with WebGL 2 (since they are enabled by default).

**Comment by allrightzhu** [comment] 2020-07-10 09:44
> Be aware that the extension test for `OES_vertex_array_object` that worked with WebGL 1 won't work with WebGL 2 (since it is enabled by default).

I know, _gl = _canvas.getContext( “webgl2”, contextAttributes ) ;  _gl was undefined, not null,  the code if(_gl == null) was false,   then the program got  an error;
 so I just passed context  to the WebGLRenderer constructor,
then the value extension = extensions.get( 'OES_vertex_array_object' ) was  undefined,  if(extension == null) was false,
the program got  an error.

**Comment by allrightzhu** [comment] 2020-07-10 09:45
> You'll need to provide more details for us to reproduce this error. As it is we cannot debug the issue. From the "new issue" template, please notice:
> 
> Describe the bug or feature request in detail.
> 
> Always include a code snippet, screenshots, and any relevant models or textures to help us understand your issue.
> 
> Please also include a live example if possible. You can start from these templates:
> 
> * [jsfiddle](https://jsfiddle.net/hyok6tvj/) (latest release branch)
> * [jsfiddle](https://jsfiddle.net/c5m1kazu/) (dev branch)

Ok, I will try my best to do this.

**Comment by Mugen87** [comment] 2020-07-14 08:39
Closing for now until a live example is provided.

**Closed by Mugen87** 2020-07-14 08:39 UTC
