### ISSUE TITLE
DeviceOrientationControl does not work on Firefox mobile

### ISSUE THREAD

**Issue by copyhold** [mrdoob/three.js#5947] opened 2015-01-20 22:02 UTC
Seems like axes are mixed up and screen orientation not identified as well.

**Comment by WestLangley** [comment] 2015-01-20 22:39
Can you provide a test case, along with the information requested in "How to report a bug" in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md)?

**Comment by copyhold** [comment] 2015-01-21 05:08
Mobile LG G2, Firefox 35.0, three.js v0.0.70
running misc_controls_deviceorientation.html
in portrait all works good but in landscape scene terns in wrong directions  when turning the device and also scene is not rotated to be in normal plane.
h
![2015-01-21-070737](https://cloud.githubusercontent.com/assets/42069/5831480/5140e81c-a13c-11e4-961a-0f52ea78e2f4.jpg)

**Comment by mrdoob** [comment] 2015-01-21 13:20
This also happens in Chrome.
I think the solution is to use `screen.orientation.lock( 'any' )`.

**Comment by copyhold** [comment] 2015-01-21 13:42
could you explain, please

**Comment by mrdoob** [comment] 2015-01-21 15:28
Oh really?! Meh...

**Comment by mjsibbald** [comment] 2015-07-13 20:28
Did anybody ever fix this? Still having this problem in Firefox (Android). Tried the lock thing but  ended up with a black screen.

**Comment by Cy-Bo-Rg** [comment] 2015-07-13 21:08
It works on my android device , GT-P3110 , with stock browser 4.1.2 with rev72dev and it works with Firefox Beta 40 (which is the latest version, try to update it) , same revision.

**Comment by mjsibbald** [comment] 2015-07-13 21:18
Really? Just tested the example and it has this weird effect when I put it in landscape.... it's all off.
Beta 40: http://threejs.org/examples/#misc_controls_deviceorientation
Same effect copyhold was describing.

**Comment by mjsibbald** [comment] 2015-07-13 21:18
note 4 btw, lollipop

**Comment by Cy-Bo-Rg** [comment] 2015-07-13 21:23
http://image.slidesharecdn.com/gyroscopeaccelerometer-120513150504-phpapp02/95/better-motion-control-using-accelerometergyroscope-sensor-fusion-9-728.jpg?cb=1336921613

http://www.reddit.com/r/GoogleCardboard/comments/2k73gz/combating_gyro_drift_with_a_complementary_filter/

that's common; some engineers say that the combination of gyroscope and accelerometer together may help to prevent such problems.

**Comment by mjsibbald** [comment] 2015-07-13 21:30
I think we misunderstand eachother. It's al working just fine in Chrome 44 and 45. But in firefox even in beta 40. when you rotate to landscape. The webgl/canvas is not rotated, and the deviceorientation is all still thinking the webgl is in portrait.

**Comment by Cy-Bo-Rg** [comment] 2015-07-13 22:07
I've understood your problem now; the demo isn't supposed to be used with "screen orientation" activated, which destroys the current rendering view and prevents that it gets updated further.
That might be considered an issue to some extent, but imagine a flight simulator as an example; would you prefer to have a fixed view when using the gyroscope as a controller or would you like it to accidentally rotate your view when you rotate +90°/-90° ? I'll prefer to keep my view as it is while the world rotates.

**Comment by mjsibbald** [comment] 2015-07-13 22:12
ok lets presume you are right. There is still a difference between Chrome and Firefox. And how would one get the same response in both browsers. Thats all I'm after. As mr.doob labeled this as an bug, I was just wondering if somebody fixed it. 

Thanks for thinking with me, dont get me wrong.

**Comment by Cy-Bo-Rg** [comment] 2015-07-13 22:16
I'm with you,the rendering problem is an issue for sure,but that's a problem in the code of the demo which can be fixed easily.

**Comment by Cy-Bo-Rg** [comment] 2015-07-13 22:25
for example, I've just fixed it partially and I've only looked for a sec to the code.
Remove the last renderer.setSize( window.innerWidth, window.innerHeight ); and it works with "screen rotation" activated , even though the height is stretched, but , as I said, I've just started reading the code. :P

**Comment by Cy-Bo-Rg** [comment] 2015-07-13 23:10
update: you should move the entire **window.addEventListener('resize', function()** out of  			
**(function() {
  "use strict";**
to avoid the skewing problem. It's still half the size of the screen , but I'm almost there. ^.^"

**Comment by Cy-Bo-Rg** [comment] 2015-07-14 02:12
my fault,  in landscape it starts rotated by 90°.
sorry :P I just considered it normal considering that the values are taken straight from the gyro and that aren't updated constantly.

**Comment by Cy-Bo-Rg** [comment] 2015-07-14 13:43
It looks like in DeviceOrientationControls.js a "switch case" for the various rotations is missing.
It also misses a check to see if the device has support for DeviceOrientation events,which *may* be not present on some devices which only have the accelerometer.
Again, I apologize for my stupidity... :P

**Comment by mjsibbald** [comment] 2015-07-14 13:45
Yeah I've working on it. And got the orientation working now. left right is working and watching down from the center also, but when I look up the world flips upside down!.

**Comment by Villmer** [comment] 2015-09-16 14:33
I have also posted about this bug.
https://github.com/mrdoob/three.js/issues/6607

This appears to be an Android issue as iOS 8+ does not encounter the problem.
The DeviceOrientationControls.js class get 'confused' and begins to act strangely. 

I have a demo showing this problem (on Android): http://villmer.com/tests/orient.html
This is a simple 360° photograph using the DeviceOrientationControls.js class. 
On Android (in Firefox and Chrome), it doesn't work correctly.

I had hoped the recently released Version 72 would have resolved this... but no.

**Comment by Villmer** [comment] 2015-09-16 14:41
I'm testing my demo on Android in Full Screen / Landscape
• the x-axis rotation (up and down) work fine (I can "tilt" the device up and down to look around)
• the z-axis rotation (roll) does not work at all!
• the y-axis rotation actually rotates the view on the z-axis (roll)
  (meaning, when I "pan" the device to the left and right, it rotates view on the z-axis)

**Comment by Villmer** [comment] 2015-09-16 14:41
Again, iOS 8 works fine. Is there a parameter I can set in my Javascript or in the DeviceOrientationControls.js class to make this work for both iOS and Android?

**Comment by mrdoob** [comment] 2015-09-16 16:45
I have just tried in Firefox mobile and it sure is buggy. It's fine in Chrome though...


/ping @richtr

**Comment by Villmer** [comment] 2015-09-16 16:54
For me, it doesn't work in Chrome (45.0.2454) on Android (5.1.1) either.

**Comment by MasterJames** [comment] 2015-09-16 23:18
Android 5.0 Samsung Note3
Chrome is fine
Firefox 40.0.3 seems a bit jerry but Chrome beats firefox for WebGL enough that it's not a browser I use anymore.
It seems like their framerate for GUI updates is performing at only half  speed or slower.
Anyway for me it's not a three js problem.

**Comment by Villmer** [comment] 2015-09-17 08:40
The bottom line is that the DeviceOrientationControls.js class is not functioning consistently across Android and iOS. I, for one, don't care about Firefox (either on the desktop or mobile). Chrome is, by far, the most advanced browser out there and should be the target of most tests. With Crosswalk, mobile applications can now be build using the Chromium engine - which makes Chrome even more important to focus on. 

I digress.

The DeviceOrientationControls.js class needs to be fixed. Not sure how but its a fact.

**Comment by MasterJames** [comment] 2015-09-17 09:03
Maybe it can, or should be also opened as a ticket with Firefox at https://bugzilla.mozilla.org/ ?
I unfortunately don't have a demonstration of what I noticed prior but it seems to stutter it's GUI input in comparison. 
...or maybe that's a hint to where the problem lies in THREEjs when on Firefox?!
Maybe there's a way to increase the rate of events firing for this?, but I think it's on the firefox side? or at least that's my initial assessment of the problem based more on my other experience, and somewhat what I'm seeing in this example.

**Comment by Villmer** [comment] 2015-09-17 09:06
I personally could care less about Firefox. For me, if it works on Chrome, it works. Right now, I don't see it working Chrome for Android.

**Comment by Villmer** [comment] 2015-09-17 17:50
I've had someone tell me that the orientation worked on his Galaxy S6. So, this bug appears to have preferences on when it bites (or doesn't)

**Comment by richtr** [comment] 2015-09-17 18:07
So the problem is that Firefox does something weird with the `gamma` value
in deviceorientation.

I've written about this before. I will try to find a link.

**Comment by Villmer** [comment] 2015-09-22 10:12
Just tested this on my older Galaxy Tab 7 (2011) running Android 4.1.2 and Chrome Dev (47.0) and the DeviceOrientationControls.js class works perfectly!

It did NOT, however, work in the current stable release of Chrome (45.0).

**Comment by nexero** [comment] 2015-11-18 06:44
This is the corresponding bug filed for mozilla:
https://bugzilla.mozilla.org/show_bug.cgi?id=1073224

Still not beeing worked on, though...

**Comment by richtr** [comment] 2015-11-18 08:00
I did some digging and it looks like the last significant update to DeviceOrientation in Firefox was in [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=938035) (link to that bug's 'fix' [here](https://bug938035.bmoattachments.org/attachment.cgi?id=8338236)).

From that bug:
> "the orientation data we get from Android HAL didn't match the W3C spec"

They still don't :(

That is partly because Firefox is still using the Android ORIENTATION sensor data to compute deviceorientation values. That sensor was officially [deprecated in Android Level 8](https://developer.android.com/reference/android/hardware/Sensor.html#TYPE_ORIENTATION). Mozilla should really be computing deviceorientation data from Android's [ROTATION_VECTOR](https://developer.android.com/reference/android/hardware/Sensor.html#TYPE_ROTATION_VECTOR) sensor type.

The problem's being experienced with three.js's DeviceOrientationControls lie within Firefox's implementation rather than three.js. I think we would all prefer to see Mozilla fix this within Firefox than placing a temporary band-aid on three.js's `DeviceOrientationControls`. I'm not even sure what that band-aid should look like to be honest.

**Comment by danrossi** [comment] 2016-01-13 14:03
Hi guys what is the status of this you think considering they fixed the bug in firefox but not released yet ? Would it require implementing this orientation library into the controls instead to handle quirks with Firefox ? I believe there is extra requirements needed for IOS also I believe. 

https://github.com/adtile/Full-Tilt/blob/master/src/Euler.js#L91-L148

**Comment by danrossi** [comment] 2016-01-13 14:35
I've made a request that the ubuntu package get updated but there might be a need to still deliver the binary directly ? 

I need it specifically to work on embedded NAS systems like the synology and it seems if its the same arch , the ubuntu binary will run on it. 

https://answers.launchpad.net/ubuntu/+source/libsndfile/+question/280926

**Comment by richtr** [comment] 2016-01-13 15:11
I haven't tried the fix in https://bugzilla.mozilla.org/show_bug.cgi?id=1073224 yet but if it matches the values returned by iOS and Chromium-based Android browsers this should fix the issue without any further changes needing to be made.

> Would it require implementing this orientation library into the controls instead to handle quirks with Firefox ?

Could you explain what you mean here?

> I believe there is extra requirements needed for IOS also I believe.

Could you be more specific about any extra requirements needed here?

> It would be good to get this working because ironically. Android chrome does not work whatsoever with video texture.

Is there an issue for this bug?

**Comment by danrossi** [comment] 2016-01-13 18:38
This is what I was going on about with IOS and if "webkitCompassHeading" was still needed. 

http://ariya.github.io/device/compass/
https://gist.github.com/mattdsteele/5615925

```
  if (typeof e.webkitCompassHeading !== 'undefined') {
                direction = e.webkitCompassHeading;
                if (typeof window.orientation !== 'undefined') {
                    direction += window.orientation;
                }
            } else {
                // http://dev.w3.org/geo/api/spec-source-orientation.html#deviceorientation
                direction = 360 - e.alpha;
            }
```

There is many bug reports in regards to the Chrome webGL video texture bug but I didn't know which one to update as some were marked as complete but re-updated. There was too many. No responses it seems. It seems it was a regression also. So only Firefox is fully working on Android right now apart from this orientation api bug.

**Comment by danrossi** [comment] 2016-01-14 15:22
The Tilt functions seem to work around issues with Firefox Im not across how it conforms the differences but pans around properly in Firefox. At intervals it's jerky though like it's resetting to 0 when moving left or right. With DeviceOrientationControls it seems to stay in portrait mode or it's angle is wrong.

**Comment by danrossi** [comment] 2016-01-14 17:00
Confirming all the bits in the Tilt method are working in Firefox Android apart from where at a particular value it seems to reset itself back to a setting and will try and move right while moving right then move back to the left very jerky. I'm unsure where the differences are. It doesn't need any of the promise code just

```
controls = new FULLTILT.DeviceOrientation({ type: "world" });
controls.start();
````

```
	// Computed device orientation rotation vector
			var orientationQuat = new THREE.Quaternion();

			// World frame transform (- PI/2 around the x-axis)
			var worldQuat = new THREE.Quaternion( - Math.sqrt( 0.5 ), 0, 0, Math.sqrt( 0.5 ) );

			// Render three.js world
			function draw() {

				var quat = controls.getScreenAdjustedQuaternion();

				orientationQuat.set( quat.x, quat.y, quat.z, quat.w );

				// IMPORTANT! set deviceorientation camera to three.js world frame
				// (i.e. make camera look out the back of the screen by rotating the camera x-axis by -PI/2)
				camera.quaternion.multiplyQuaternions( worldQuat, orientationQuat );
				//controls.update();
				// Render scene
				renderer.render( scene, camera );

				// Re-draw at next browser paint
				requestAnimationFrame( draw );

			}
```

**Comment by danrossi** [comment] 2016-01-25 18:20
I believe there may still be a problem with FullTilt I'm just trying to work it out. 

However I am also seeing the same problem when using the Cardboard sensor when Webvr is enabled. It's like the starting point is incorrect and so the picture is sideways. I am locking the screen in place in landscape mode first with this

```
screen.lockOrientationUniversal = screen.lockOrientation || screen.mozLockOrientation || screen.msLockOrientation || (screen.orientation && screen.orientation.lock);
```

```
screen.lockOrientationUniversal("landscape");
```

**Comment by danrossi** [comment] 2016-02-04 15:49
Confirming Firefox orientation data is borked in FullTilt also. Its facing 90 degrees to the left counter clockwise so basically where the video should be facing at the bottom is facing to the right. If that is an easy description ?  

Perhaps it's as easy as adding in an offset for Firefox ? There is the added problem where it seems to reset at regularly intervals when rotating around so causes the display to jerk.

**Comment by danrossi** [comment] 2016-02-04 15:57
A fix seems to have been made in version 46 and this ticket is closed. There is no version 46 , Firefox beta is version 45 so checking in Nightly which is version 47.

**Comment by danrossi** [comment] 2016-02-04 16:16
Confirming Firefox Android Nightly 47 fixes this problem. Hopefully it can make the playstore soon ?

**Comment by danrossi** [comment] 2016-02-04 17:01
Confirming it is working in my test in WebVR cardboard sensor and device orientation controls on Firefox nightly.

**Comment by danrossi** [comment] 2016-02-05 03:48
It will be released and updated in Firefox beta in 6 weeks according to an update in their ticket.

**Comment by mrdoob** [comment] 2016-02-07 07:28
Yay! Just took them 1 year 😁

**Closed by mrdoob** 2016-02-07 07:28 UTC
Labels: Bug

**Comment by danrossi** [comment] 2016-02-08 05:40
Yep. Have a look at the webkit CORS mess. that has been broken for years and they are still refusing to add it in. The ticket is there but no movement. It has disabled webgl completely :)

**Comment by danrossi** [comment] 2016-02-08 18:08
This is what I meant about the CORS issue on webkit making WebGL completely unusable on IOS. still nobody even assigned to it while apple is trying to market VR hahaha. 

I am still trying to work with chromium on the Android video texture problem but it's been hard work and I can't believe out of thousands of people working on this I have to be the one to do it haha. 

https://bugs.webkit.org/show_bug.cgi?id=135379

**Comment by danrossi** [comment] 2016-11-16 14:03
I believe the orientation changes have been broken completely in Firefox Android. They've done something I get zero values now.
