### ISSUE TITLE
CSS3D object position is wrong when the browser zoom is not 100% and not full screen under the window system

### ISSUE THREAD

**Issue by muuyao** [mrdoob/three.js#25460] opened 2023-02-07 04:20 UTC
### Description

CSS3D object position is wrong when the browser zoom is not 100% and not full screen under the window system

### Reproduction steps

1. open the demo
2. check the location

### Code

```js
    const geometry = new THREE.BoxGeometry(1, 10, 10);
    const material = new THREE.MeshBasicMaterial({ color: 0x999999 });
    const cube = new THREE.Mesh(geometry, material);
    cube.scale.set(0.5, 0.5, 0.5);

    const x = 0;
    const y = 0;
    const z = 0;
    cube.position.set(x, y, z);
    const el = document.querySelector(`.board-info`);
    if (el) {
      const boardInfo = new CSS3DObject(el as HTMLElement);
      boardInfo.position.set(x, y, z);
      boardInfo.scale.set(0.05, 0.05, 0.05);
      boardInfo.rotateY(Math.PI / 2);
      scene.add(boardInfo);
      scene.add(cube);
    }
```

### Live example

* [codesandbox](https://codesandbox.io/p/github/muuyao/three-css3d/main?file=%2Fsrc%2FuseThree.ts&selection=%5B%7B%22endColumn%22%3A6%2C%22endLineNumber%22%3A141%2C%22startColumn%22%3A5%2C%22startLineNumber%22%3A124%7D%5D&workspace=%257B%2522activeFileId%2522%253A%2522cldtpxqrt000ifqijbe6k9k0x%2522%252C%2522openFiles%2522%253A%255B%2522%252FREADME.md%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522spaces%2522%253A%257B%2522cldtpxu96000x3b6jpwh9nnte%2522%253A%257B%2522key%2522%253A%2522cldtpxu96000x3b6jpwh9nnte%2522%252C%2522name%2522%253A%2522Default%2522%252C%2522devtools%2522%253A%255B%257B%2522key%2522%253A%2522cldtpxu97000y3b6jyc9faxk6%2522%252C%2522type%2522%253A%2522PROJECT_SETUP%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522key%2522%253A%2522cldtpxyjj00833b6jcyb3bmdk%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522key%2522%253A%2522cldtpxws000683b6j1f7tjkrt%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D%257D%252C%2522currentSpace%2522%253A%2522cldtpxu96000x3b6jpwh9nnte%2522%252C%2522spacesOrder%2522%253A%255B%2522cldtpxu96000x3b6jpwh9nnte%2522%255D%252C%2522hideCodeEditor%2522%253Afalse%257D)
* [demo](https://rduzx4-3000.preview.csb.app/)

### Version

0.149.0

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by Mugen87** [comment] 2023-02-07 09:51
Duplicate of #3225.

To clarify, this issue is not Windows related, it happens everywhere. This is how your demo looks like on macOS with 25% zoom level.

<img width="843" alt="Bildschirm­foto 2023-02-07 um 10 49 43" src="https://user-images.githubusercontent.com/12612165/217210798-787421f8-ad8e-4d33-b9f7-03dcfe5c6849.png">

The CSS renderers only support 100%.

**Comment by muuyao** [comment] 2023-02-07 09:59
> Duplicate of #3225.
> 
> To clarify, this issue is not Windows related, it happens everywhere. This is how your demo looks like on macOS with 25% zoom level.
> 
> <img alt="Bildschirm­foto 2023-02-07 um 10 49 43" width="843" src="https://user-images.githubusercontent.com/12612165/217210798-787421f8-ad8e-4d33-b9f7-03dcfe5c6849.png">
> 
> The CSS renderers only support 100% browser zoom.

Sorry, I missed the point

On the window system, when the screen is zoomed, even if the browser does not zoom, the position is wrong

**Comment by Mugen87** [comment] 2023-02-07 10:00
> when the screen is zoomed

So you mean zooming with the mouse wheel, right?

**Comment by muuyao** [comment] 2023-02-07 10:05
> > when the screen is zoomed
> 
> So you mean zooming with the mouse wheel, right?

![image](https://user-images.githubusercontent.com/5389932/217213952-4776232e-e705-41bb-be21-aea349c92312.png)
I mean this,  for example, I set it to 125%

**Comment by Mugen87** [comment] 2023-02-07 10:16
Interesting. AFAICS, the display scale settings also affects websites and thus CSS renderers. It's essentially the same problem like with browser scale.

**Comment by Mugen87** [comment] 2023-02-07 10:18
I have filed a PR to document the limitation of CSS renderers. Closing, since this is still a duplicate.

**Closed by Mugen87** 2023-02-07 10:18 UTC
Labels: Duplicate
