### ISSUE TITLE
Fly controls free camera - unintended roll

### ISSUE THREAD

**Issue by scones** [mrdoob/three.js#8979] opened 2016-05-24 12:16 UTC
##### Description of the problem

The fly controls perform an unintended roll, when the user does circle movements with the mouse (pitch and yaw).
The bigger the circle, the bigger the effect.
##### File

https://github.com/mrdoob/three.js/blob/master/examples/js/controls/FlyControls.js
##### Three.js version
- [x] Dev
- [x] r77
##### Browser
- [x] All of them
##### OS
- [x] All of them

**Comment by JamesHealdUK** [comment] 2017-03-13 16:51
I too have been able to replicate it, any progress on this issue at all? Would be nice to have it fixed!

**Comment by Mugen87** [comment] 2018-02-20 13:27
I'm unable to reproduce on my iMac. I perform circle movements with my mouse using this [example](https://threejs.org/examples/misc_controls_fly.html) but i can't see the mentioned roll.

Can somebody provide a gif or a video that shows the unintended behavior?

**Comment by mrdoob** [comment] 2018-03-14 05:46
Closing until then...

**Closed by mrdoob** 2018-03-14 05:46 UTC
Labels: Bug
