### ISSUE TITLE
documentation deadlink

### ISSUE THREAD

**Issue by andrevenancio** [mrdoob/three.js#7399] opened 2015-10-22 04:43 UTC
FontUtils http://threejs.org/docs/#Reference/Extras/FontUtils
when you try to click over source, there's a dead link.

**Comment by pieteradejong** [comment] 2015-11-03 22:27
tagging @TatumCreative on this since this seems relevant to issue #5411.  

On FontUtils and many other pages, it seems any link to 'Object' or 'Array' or 'string' or 'number' does not actually go anywhere, whereas links to e.g. 'Texture' actually goes to that page.

For reference, each link calls this function goTo():

https://github.com/mrdoob/three.js/blob/317d6f66542ab63323c5dab6c7a4e9d08c07ca05/docs/index.html#L364

the function goTo() returns null if the first arg ('section') is not found as the key in the 'nameCategoryMap' object. 

I see two possible solutions:
1) at this location, only add an anchor tag if 'section' is not in ['Object', 'number' etc.] -- see here:
https://github.com/mrdoob/three.js/blob/317d6f66542ab63323c5dab6c7a4e9d08c07ca05/docs/index.html#L270
2) add  sections for the Object, number etc.

@TatumCreative thoughts?

**Comment by TatumCreative** [comment] 2015-11-03 23:42
I'll have to check this out next week sometime. I'll let you know then unless someone else chimes in first :)

**Comment by pieteradejong** [comment] 2015-11-03 23:52
@TatumCreative Thanks! I just started contributing - any other issues I might look at, whether docs or other?

**Comment by TatumCreative** [comment] 2015-11-03 23:59
Sure! On the docs side the individual pages could all use usage examples and linking to relevant examples. There are a bunch that don't have that yet.

**Comment by pieteradejong** [comment] 2015-11-04 00:09
@TatumCreative just so I'm clear, what individual pages are you referring to?

are there relevant todo's on this page:
https://github.com/mrdoob/three.js/issues/5411

**Comment by TatumCreative** [comment] 2015-11-04 00:27
#5411 Hasn't been updated in awhile. I should probably do that or maybe start fresh. It might take a little digging to find some good pages to do that for. For a quick search:

http://threejs.org/docs/#Reference/Extras.Helpers/DirectionalLightHelper

That has no code sample or link to an example.

**Comment by pieteradejong** [comment] 2015-11-04 00:33
Thanks will check it out. Any suitable pages where it would be easy to create a simple code sample if I'm just starting out with three.js?

re: this issue, anyone else in particular who might be able to help?

thanks for your quick responses btw!

**Comment by pieteradejong** [comment] 2015-11-19 17:08
@TatumCreative any news on both this specific issue, as well as the todo's in the link above?

**Comment by TatumCreative** [comment] 2015-11-19 17:21
I'll try and get to it this weekend :) I've been out travelling recently but I'm just about caught up where I can help on this type of stuff agian.

**Comment by pieteradejong** [comment] 2015-11-19 17:27
@TatumCreative thanks!

**Comment by looeee** [comment] 2016-12-15 16:36
Another duplicate of #9411

**Closed** 2017-04-06 18:39 UTC
