### ISSUE TITLE
MorphTargets - morphTargetInfluences in Safari not transforming mesh object

### ISSUE THREAD

**Issue by sbkeep** [mrdoob/three.js#23063] opened 2021-12-21 22:43 UTC
**Describe the bug**

Following the [Live Morph Example](https://threejs.org/examples/webgl_morphtargets.html), should be able to add spherical vertices to boxGeometry and transform by updating the `morphTargetInfluences` on the mesh object

View on Chrome/FireFox for correct behavior
View on Safari for bug behavior

Bug seems specific to Safari on macOS < 12, using WebGL2.  

**To Reproduce**

1. Go to https://threejs.org/examples/webgl_morphtargets.html in `Safari`
2. Update `Morph Targets` gui sliders for `Spherify` and/or `Twist`
3. See mesh object move around instead of transform

***Code***
https://github.com/mrdoob/three.js/blob/master/examples/webgl_morphtargets.html

***Live example***
https://threejs.org/examples/webgl_morphtargets.html

**Expected behavior**

Mesh object transforms (Chrome behavior) instead of moving around the screen

**Screenshots**

Safari (bug):
![safari_morph](https://user-images.githubusercontent.com/6200826/147149868-f757fb33-d976-4984-922a-89c0d41a89ee.png)

Chrome (expected):
![chrome_morph](https://user-images.githubusercontent.com/6200826/147149875-db0e8ef9-91af-4086-a210-e2a6605948b7.png)

**Platform:**

 - Device: Macbook Pro i7
 - OS: MacOS 11.6.2
 - Browser: Safari 15.2
 - Three.js version: master

**Comment by Mugen87** [comment] 2021-12-22 12:43
I've tested the example with iPadOS 15.2 and can't reproduce. It works as expected.

Unfortunately, I can't test on macOS with Safari 15.2. Maybe someone else can verify if `webgl_morphtargets` is actually broken.

**Comment by sbkeep** [comment] 2021-12-22 20:00
@Mugen87 Yes also seeing this work correctly on iPhone 15.2 so it does appear to be a desktop issue. I added a screenshots comparing the difference to safari/chrome on mac

**Comment by WestLangley** [comment] 2021-12-22 21:06
I am unable to reproduce this behavior on M1 iMac macOS 12.0.1 Safari 15.1.

**Comment by mrdoob** [comment] 2021-12-22 23:53
I can reproduce on MacBook Pro 2016 (Intel) macOS 11.16.1 Safari 15.2.

Maybe macOS 12 comes with a driver fix for this?

**Comment by Mugen87** [comment] 2021-12-23 09:41
A workaround for this issue could be the usage of `WebGL1Renderer`. I assume this only happens with WebGL 2.

**Comment by sbkeep** [comment] 2021-12-23 16:50
Interesting, yes confirmed locally it works properly with WebGL1.  Tested by removing `antialias` param when creating renderer.

**Comment by mrdoob** [comment] 2021-12-23 19:13
> Tested by removing antialias param when creating renderer.

🤨

**Comment by sbkeep** [comment] 2021-12-23 20:01
Ok I see that `WebGLRenderer` uses webgl2 by default as per [docs](https://threejs.org/docs/#api/en/renderers/WebGL1Renderer), and confirmed in both cases that `WebGLRenderer.capabilities.isWebGL2` is `true`.  So it seems that it is not webgl1 vs webgl2, but rather the context/params passed to webgl2

**Provided Example**
Bug behavior
```
renderer = new THREE.WebGLRenderer({ antialias: true });
```

Correct behavior
```
renderer = new THREE.WebGLRenderer();

```

**My implementation**
I've been creating renderer by passing in `webgl2` context

Bug behavior
```
const canvas = document.createElement('canvas');
const context = canvas.getContext('webgl2');
renderer = new three.WebGLRenderer({ canvas, context });
```

Correct behavior
```
renderer = new three.WebGLRenderer();
```

or
```
const canvas = document.createElement('canvas');
const context = canvas.getContext('webgl');
renderer = new three.WebGLRenderer({ canvas, context });
```

**Comment by mrdoob** [comment] 2021-12-23 21:13
I can confirm that setting `antialias: false` fixes the issue 🤨

```js
renderer = new THREE.WebGLRenderer( { antialias: false } );
```

**Comment by Mugen87** [comment] 2022-04-02 08:09
@sbkeep @mrdoob Can you still reproduce the issue on your devices? My hope is that #23727 fixes this issue as well 🤞 .

**Comment by mrdoob** [comment] 2022-04-05 23:21
Hmm, I recently replaced that Intel MacBook Pro with a M1 MacBook Pro... I think we can close this.

@sbkeep Let us know if it's still not fixed and we can reopen.

**Comment by mrdoob** [comment] 2022-04-06 17:26
I remembered I still have a Intel MacBook Air and I can still reproduce some glitchiness.
I'll investigate a bit.

**Comment by mrdoob** [comment] 2022-04-08 17:33
Seems to be a bug in Safari indeed.

@sbkeep could you report the issue on their bug tracker instead?

**Closed by mrdoob** 2022-04-08 17:33 UTC
Labels: Device Issue

**Comment by sbkeep** [comment] 2022-04-08 20:05
@mrdoob appreciate the followup, agree this can be closed.  Can confirm this still occurs on intel macs, worth mentioning that at one point I also reproduced on chrome/firefox but it was glitchy, distorting between correct/buggy behavior (could not pin down to performance/integrated gpu).  Can try to capture but since primarily an issue with safari, will direct to them.
