### ISSUE TITLE
GPGPU birds were not able to fly, after r76.

### ISSUE THREAD

**Issue by cx20** [mrdoob/three.js#8809] opened 2016-05-05 08:42 UTC
##### Description of the problem 

GPGPU birds were not able to fly, after r76.
...

##### Three.js version

- [X] Dev
- [X] r76
- [ ] ...

##### Browser

- [ ] All of them
- [X] Chrome
- [X] Firefox
- [X] Internet Explorer
- [X] Edge

##### OS

- [ ] All of them
- [X] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

##### Hardware Requirements (graphics card, VR Device, ...)

PC1) ThinkPad X201 + Win10 + Intel(R) HD Graphics 
PC2) Desktop + Win7 + Intel(R) HD Graphics 3000

- r76
https://cdn.rawgit.com/mrdoob/three.js/r76/examples/webgl_gpgpu_birds.html
![image](https://cloud.githubusercontent.com/assets/1833979/15039373/7df12c78-12e7-11e6-9148-964d29d0f482.png)

- r75
https://cdn.rawgit.com/mrdoob/three.js/r75/examples/webgl_gpgpu_birds.html
![image](https://cloud.githubusercontent.com/assets/1833979/15039363/705b9da0-12e7-11e6-9472-c1b4c4d3651b.png)

**Comment by mrdoob** [comment] 2016-05-05 19:50
Hmm, they do work here... Intel HD Graphics 6000 (OSX)

**Comment by antont** [comment] 2016-05-06 10:26
Here not, with Intel HD 4000 on Win 10.

Is like with OP for me too: works in r75, not in r76. My favourite example too!

**Comment by Mugen87** [comment] 2016-05-06 13:28
I've tested with Chrome 50, Firefox 46.0.1 and Safari 9.1 on OSX 10.10.5 and a AMD Radeon R9 M295X . Everything works fine. But on my Windows 10 VM and Chrome, i have the same behavior like @antont and @cx20.

Maybe the changes in this PR #8415 cause the problems...

**Comment by antont** [comment] 2016-05-06 13:52
reverting #8415 did not fix it for me. am pushing the result of my revert but gtg for a bit now, will give the link later

**Comment by SuberFu** [comment] 2016-05-06 16:26
Seems to be a Windows issue (maybe something with the ANGLE implementation of webgl?).
It doesn't work on my window machine, but works in OSX.
Perhaps the changes used something that's not available in ANGLE?

**Comment by Mugen87** [comment] 2016-05-06 16:39
I also have the problem with Ubuntu 15.10 and Chromium 49.0.2623.108. Doesn't seem to be Windows exclusive...

**Comment by Mugen87** [comment] 2016-05-07 13:18
/ping @tschw @bhouston for opinion

We had some changes to `WebGLRenderTarget` in R76. Do you think these changes could affect  `SimulationRenderer` and the way it evaluates data from `DataTexture`?

**Comment by tschw** [comment] 2016-05-07 15:30
Where it worked, did by coincidence: The vertex shader of the geometry had incomplete uniforms.

**Comment by Mugen87** [comment] 2016-05-07 15:43
@tschw Hey, thanks for the fix! Can you explain why the implementation suddenly needs this enhancement?

**Comment by tschw** [comment] 2016-05-07 16:30
@Mugen87 
> Can you explain why the implementation suddenly needs this enhancement?

...and I was hoping I could spare you my usually unpopular opinion :laughing: 

It might have been missing all along.

The `currentPosition` and `currentVelocity`properties were exposed from `SimulationRenderer`, so it was either just simply forgotten to ever wire them up, or the code that did so got sliced away at some point.

It worked because of another apparently open (didn't we fix that?!) bug: A `samplerUniform.value === null` should probably just give you an empty texture, not random results based on previous rendering.

So there is no enhancement. Instead, I fixed a bug previously hidden by another one. That other bug still exists, but its effect changed. Internal changes of the renderer affecting the allocation order of texture uniforms let the ticking time bomb encoded in the example go off.

**Comment by mrdoob** [comment] 2016-05-07 17:02
@cx20 do you mind verifying that this is now fixed in `dev`?

**Comment by cx20** [comment] 2016-05-07 23:46
@mrdoob 
I confirmed fixed in the following environment. 

PC1) ThinkPad X201 + Win10 + Intel(R) HD Graphics 
PC2) Desktop + Win7 + Intel(R) HD Graphics 3000

- 77dev 

https://cdn.rawgit.com/mrdoob/three.js/dev/examples/webgl_gpgpu_birds.html
![image](https://cloud.githubusercontent.com/assets/1833979/15095219/7ba636cc-14f7-11e6-87f0-22f8587668bc.png)

Thank you everyone!

**Comment by mrdoob** [comment] 2016-05-08 00:13
Sweet! Thanks guys!

**Closed by mrdoob** 2016-05-08 00:13 UTC

**Comment by WestLangley** [comment] 2016-05-08 03:30
@tschw Nice. [We were so confused](http://stackoverflow.com/questions/22713403/threejs-gpgpu-rtt-example-redundant-lines/22715587#22715587) about this one... : - )

**Comment by tschw** [comment] 2016-05-08 03:49
Reading that SO post, seems the code was not so redundant, after all. Or actually was, but not on the basis of behavior one should rely upon.

What's the history of the `texture.value === null` issue that's made it fail to fail? Is it a regression? I think we should ensure an empty texture is used in this case. As we can see here, it can hide programming/editing errors that then pop up out of nowhere at some later point in time.

**Comment by Mugen87** [comment] 2016-05-08 15:58
@tschw Many thanks for your explanations 👍
