### ISSUE TITLE
VTKLoader: Extend vtp file parse

### ISSUE THREAD

**Issue by Mt-Youya** [mrdoob/three.js#28813] opened 2024-07-05 11:01 UTC
### Description

vtp file load in official docs:
 `format=”appended” — The data are stored in the appended data section. Since many DataArray elements may store their data in this section, the offset attribute is used to specify where each DataArray’s data begins. This format is the default used by VTK’s writers.` [docs here](https://docs.vtk.org/en/latest/design_documents/VTKFileFormats.html#unstructuredgrid)

so, VTKLoader should be parse default format , but i cant load my vtp model.

### Reproduction steps

[editor](threejs.org/editor)

import this [file](https://github.com/Mt-Youya/vanilla-oral/blob/main/public/assets/models/user-appendedData.vtp)

I got a Error 

### Code

no code

### Live example

no 

[editor](threejs.org/editor)

### Screenshots

![image](https://github.com/mrdoob/three.js/assets/57708498/aab99728-9431-422f-8255-3d613173d049)

### Version

latest

**Comment by Mugen87** [comment] 2024-07-05 11:07
Duplicate of #13386.

**Closed by Mugen87** 2024-07-05 11:07 UTC

**Comment by Mt-Youya** [comment] 2024-07-05 12:21
Hey! @Mugen87 , I added some code so that VTKLoader can parse vtp files in AppendedData format.
Can I submit a PR?
