### ISSUE TITLE
VTKLoader for data from Paraview not shown

### ISSUE THREAD

**Issue by simwes** [mrdoob/three.js#16527] opened 2019-05-22 23:33 UTC
Hello,

I am trying to load vtk files in three.js using the VTKLoader. The vtk files are produced by paraview. However, the loader fails silently and no vtk data is shown on the browser.
Any suggestion?
Thank you!

**Comment by Mugen87** [comment] 2019-05-23 08:23
`VTK` is an extensive standard and `VTKLoader` supports only a single out of five dataset formats (see https://github.com/mrdoob/three.js/issues/13386#issuecomment-367426666). Can you please share one of your `VTK` files for testing?

**Comment by simwes** [comment] 2019-05-24 00:08
Hi, thank you for your message. In the this [link](https://drive.google.com/open?id=1PjmfmOCSPNvBgtTUHzyO-ROEfJl8QJlh) you can find a vtk file I am trying to load in threejs.
I am learning about the VTK loader but I still do not understand why it does not work.

**Comment by Mugen87** [comment] 2019-05-24 15:05
Your file has a dataset if type `UNSTRUCTURED_GRID` which is not supported by `VTKloader`. Hence, your issue is a duplicate of #13386. However, #16550 ensures throw an error if an invalid dataset is found. 

BTW: If I load your file on my computer Chrome hangs up after a while since `VTKloader` infinitely executes a `while` loop. The new PR prevents this behavior.

**Closed** 2019-05-24 18:55 UTC
Labels: Duplicate, Loaders
