### ISSUE TITLE
nPOT textures can be swapped during the uploading process if the textures were already in Browser Cache.

### ISSUE THREAD

**Issue by eXponenta** [mrdoob/three.js#13659] opened 2018-03-21 23:03 UTC
##### Description of the problem

nPOT textures can be swapped during the uploading process if the textures were already in Browser Cache.

##### Repeating of the problem
 - Open [this link](https://exponenta.github.io/ThreeJsBug/) in Chrome on Android device.
 - Toilets must be bottom of screen, baths must be on top of screen.
 - Reload some page
 - Now bath and toilets mixed on both sides (or may be only baths, or only toilets)

##### Simple fix 

Adding `var _canvas` in [this line](https://github.com/mrdoob/three.js/blob/dev/src/renderers/webgl/WebGLTextures.js#L59) fixes it.

One more possible (unconfirmed) fix: use `createImageBitmap` on Image before doing the resize.

It seems that `texImage2d` somehow doesnt get update from that canvas in time.

##### Three.js version

- [x] Dev

##### Browser

- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [x] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

Device: Huawei Nova
Android 7.0
Chrome 65.0.3325.109

Second Device: Meizu M2 Note
Android 5.1.1
Chrome 65.0.3325.109

##### Proofs
PC (as reference)
![PC](https://github.com/eXponenta/ThreeJsBug/raw/master/sreens/pc.jpg)

Mobile (Huawei Nova) (bug)
![Mobile bug](https://raw.githubusercontent.com/eXponenta/ThreeJsBug/master/sreens/mobile1.png)

Mobile (Huawei Nova) (bug)
![Mobile bug](https://raw.githubusercontent.com/eXponenta/ThreeJsBug/master/sreens/mobile2.png)

**Comment by looeee** [comment] 2018-03-22 00:18
Confirmed on my Moto G

**Comment by Mugen87** [comment] 2018-03-22 09:35
> It seems that texImage2d somehow doesn't get update from that canvas in time.

I'm not sure that is a `three.js` bug. When the call `texImage2d()` returns, WebGL ensures that you can reuse the given image/buffer without affecting the upload. If this is not the case there is maybe a problem in the browser implementation.

BTW: I can't reproduce the error in Firefox (Android). 

The implementation of `makePowerOfTwo()` was changed because it was not memory efficient to create a new canvas for each texture resize. So reintroducing `var` will also reintroducing the former memory related problems.

**Comment by looeee** [comment] 2018-03-22 10:01
I can also reproduce this on windows with Chrome 66, but not with Firefox or Edge. Perhaps it's a bug in Chrome?

**Comment by Mugen87** [comment] 2018-03-22 10:17
I think so. The behavior in Chrome does not conform to the standard. At least from my point of view...

**Comment by eXponenta** [comment] 2018-03-22 11:40
Yep, this is Chrome bug, and was represented in raw openGl.
Test link: https://jsfiddle.net/6nLucq2y/9/, perhaps it's bug in GPU memory.

**Comment by Mugen87** [comment] 2018-03-22 11:44
Can you please file a bug at? https://bugs.chromium.org/p/chromium/issues/list

You've already prepared a nice test case 😇

**Comment by ivanpopelyshev** [comment] 2018-03-28 22:41
Ok, they fixed it even before we reported, its a duplicate of https://github.com/mrdoob/three.js/issues/13379

**Closed** 2018-03-29 08:36 UTC
Labels: Browser Issue
