### ISSUE TITLE
OrbitControls: Panning/Dollying does not end when mouse button is released outside of viewport

### ISSUE THREAD

**Issue by Tinoooo** [mrdoob/three.js#24933] opened 2022-11-10 09:10 UTC
**Describe the bug**

Whenever I pan or dolly using my mouse, the dollying continues when I release the respective mouse button outside of the viewport. See the gif below. Please notice, that no mouse button is touched in the end of the sequence (no circle around mouse cursor).

**To Reproduce**

1. Go to [the OrbitControls example page](https://threejs.org/examples/#misc_controls_orbit)
2. right-click the canvas and move your mouse cursor outside the viewport
3. release the mouse button
4. move your mouse cursor back inside the canvas
5. move you mouse inside the canvas

***Live example***

* [OrbitControls example page](https://threejs.org/examples/#misc_controls_orbit)

**Expected behavior**

The pan/dolly event should end when the cursor reenters the canvas (reproduction step number 4) without the respective mouse button being pressed.

**Screenshots**
![Kapture 2022-11-10 at 10 01 34](https://user-images.githubusercontent.com/17991193/201048209-ed2d16d4-7ab0-48c9-ad0e-8e1def5e7ac4.gif)

**Platform:**

 - Device: Desktop
 - OS: MacOS
 - Browser: Chrome
 - Three.js version: r146

**Comment by Mugen87** [comment] 2022-11-10 18:28
Duplicate of #24566.

**Comment by Mugen87** [comment] 2022-11-10 18:29
Can you please verify if https://github.com/mrdoob/three.js/issues/24566#issuecomment-1273399805 would fix the issue on your system?

**Closed by Mugen87** 2022-11-10 18:28 UTC

**Comment by Tinoooo** [comment] 2022-11-11 16:06
Sorry for creating a duplicate issue 😬.

@Mugen87 
The suggested fix posted there is not a solution in my case, as it would require overriding OrbitControl. I found a workaround. I posted it [here](https://github.com/mrdoob/three.js/issues/24566#issuecomment-1311891636).

**Comment by Mugen87** [comment] 2022-11-11 18:52
> The suggested fix posted there is not a solution in my case, as it would require overriding OrbitControl.

The idea was to make a PR with that fix 😉 . I just wanted to ensure it worked for everybody.

**Comment by Tinoooo** [comment] 2022-11-14 09:53
I see. The solution you suggested in #24566 would lead to a behavior in which the panning would end once the mouse exited the canvas (please correct me if I'm wrong here). I think that would lower the usability of OrbitControl and would make using it feel less natural. Maybe there should be a check when reentering the viewport (not canvas/domElement) on whether the respective mouse button is still being clicked. Only if this is not the case, the panning should be ended.
