### ISSUE TITLE
Orbit control in cssRenderer not work

### ISSUE THREAD

**Issue by edboxin** [mrdoob/three.js#7090] opened 2015-09-02 17:24 UTC
Thank you for support.

The controls not work when use orbit controls without canvas or webgl renderer.  I need to use the compiled version for cssRenderer only, but i need put this lines:

renderer = new THREE.WebGLRenderer();
renderer.setSize( window.innerWidth, window.innerHeight );
document.body.appendChild( renderer.domElement );

Example working
http://jsfiddle.net/edboxin/vmypaqt2/

Not working
http://jsfiddle.net/edboxin/pm080m2s/

Why orbit have troubles with only cssRenderer?

**Comment by WestLangley** [comment] 2015-09-02 18:16
Hmm. Passing `renderer.domElement` to the controls fixes the fiddle, although we do not seem to require doing so in http://threejs.org/examples/css3d_sandbox.html -- even when `TrackballControls.` is replaced with` OrbitControls`.

    controls = new THREE.OrbitControls( camera, cssRenderer.domElement );

Updated fiddle: http://jsfiddle.net/vmypaqt2/1/

three.js r.71

**Comment by edboxin** [comment] 2015-09-03 01:20
Ohhh WestLangley, Thank you so much !!! Quick and easy.

**Comment by Mugen87** [comment] 2018-03-08 17:20
I think the problem is related to the following line of code in `OrbitControls`.
```js
var element = scope.domElement === document ? scope.domElement.body : scope.domElement;
```
If we don't pass `cssRenderer.domElement` to the constructor, `scope.domElement` is the `document` element of the HTML page. So `scope.domElement.body` is assigned to `element`.

The problem is now that the container element of CSS3DRenderer has a `position` value of `absolute` which means, the height of `scope.domElement.body` element is zero. Because of this, subsequent access to `element.clientHeight` returns a value of `0`.

I'm not sure now if this is a problem of `OrbitControls` or `CSS3DRenderer` :thinking:

**Comment by mrdoob** [comment] 2018-03-09 02:17
Oh. Interesting finding... It's `CSS3DRenderer` problem.

**Comment by Mugen87** [comment] 2018-03-09 12:24
Okay. Removing the following code from the fiddle seems to solve the problem.
```js
cssRenderer.domElement.style.position = 'absolute';
cssRenderer.domElement.style.top = 0;
```
http://jsfiddle.net/vmypaqt2/29/

So it's not a problem inside `CSS3DRenderer`. But i've noticed that some examples set these style elements although it's not necessary. I guess only need `position:absolute` if you want to overlay the DOM element of `CSS3DRenderer` on top of a canvas (like in `css3d_sandbox`).

**Comment by Mugen87** [comment] 2018-03-09 21:00
Do you think we can close the issue now? I would say the code in the fiddle caused the actual problem.

**Closed** 2018-03-09 23:14 UTC
Labels: Bug
