### ISSUE TITLE
Incorrect handling of zero-filled accessors when morph animations are present

### ISSUE THREAD

**Issue by Aloalo** [mrdoob/three.js#24999] opened 2022-11-21 14:13 UTC
_Requsted to be filed here from the model-viewer repo: https://github.com/google/model-viewer/issues/3946_

**Describe the bug**

The attached file is valid GLB with morph animations. It is modified version of the MorphStressTest glTF sample asset.

In the original sample asset, the scene contains only one mesh with 2 primitives. The "floor" primitive doesn't morph, which is achieved by accessors for all morph targets being zero explictly.

In the modified asset the same is true, but the targets don't state the NORMAL attribute and the POSITION attribute doesn't have a bufferView which means it should be read as all zeros. Both of these are allowed by the spec:
https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#:~:text=Attributes%20present%20in,sets%20of%20attributes.
https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#:~:text=The%20index%20of%20the%20buffer%20view.%20When%20undefined%2C%20the%20accessor%20MUST%20be%20initialized%20with%20zeros

The attached asset has no validation issues and loads and plays animations correctly in Blender and Babylon.js.

[morphTest.zip](https://github.com/mrdoob/three.js/files/10057173/morphTest.zip)

**To Reproduce**

1. Go to https://modelviewer.dev/editor/ or https://gltf-viewer.donmccurdy.com/
2. Upload the attached glb
3. The model doesn't load correctly despite being a valid asset

**Expected behavior**

The model should load and animate correctly.

**Platform:**

 - Device: Desktop
 - OS: Windows
 - Browser: Chrome,  Edge
 - Three.js version: r146

**Comment by Mugen87** [comment] 2022-11-21 14:25
We have lately added #24904 so this should be fixed.

You can verify it yourself by using this link: https://raw.githack.com/mrdoob/three.js/dev/editor/index.html

**Comment by Mugen87** [comment] 2022-11-21 14:27
Duplicate of #24838.

**Closed** 2022-11-21 14:26 UTC
Labels: Loaders
