### ISSUE TITLE
Normal maps with side: THREE.DoubleSide don't work in Android Chrome

### ISSUE THREAD

**Issue by nbilyk** [mrdoob/three.js#21042] opened 2021-01-09 22:11 UTC
Using a tangent space normal map and DoubleSide phong material doesn't show lighting effects on Android Chrome.  (Desktop Chrome seems to be fine, changing to FrontSide also works)

**Code**

https://gist.github.com/nbilyk/809fc2a3fc1644a72048038e01ac6468

```
const planeGeo = new THREE.PlaneBufferGeometry(planeSize, planeSize);
const planeMat = new THREE.MeshPhongMaterial({
	map: groundTex,
	side: THREE.DoubleSide, // DoubleSide causes lighting not to be seen on android. FrontSide works fine.
});

const groundNormalText = textureLoader.load('./assets/groundNormalMap.jpg');
groundNormalText.wrapS = THREE.RepeatWrapping;
groundNormalText.wrapT = THREE.RepeatWrapping;
groundNormalText.magFilter = THREE.LinearFilter;

planeMat.normalMap = groundNormalText;
planeMat.normalMapType = THREE.TangentSpaceNormalMap;
planeMat.normalScale = new THREE.Vector2(0.8, -0.8);  // Negative scaling - normal map written for a different coordinate system.

const mesh = new THREE.Mesh(planeGeo, planeMat);
mesh.receiveShadow = true;
mesh.rotation.x = Math.PI * -.5;
scene.add(mesh);
```

**Expected:**

![image](https://user-images.githubusercontent.com/589193/104109409-263af400-5293-11eb-8b4c-0ca65588d508.png)

**Actual:**

![image](https://user-images.githubusercontent.com/589193/104109421-38b52d80-5293-11eb-9349-1636a8bf7b17.png)

**Platform:**

 - Device: Pixel 2
 - OS: Android
 - Browser: Chrome 87.0.4280.141
 - Three.js version: r124

**Comment by Mugen87** [comment] 2021-01-10 10:29
Possible duplicate of #20997. Do you mind testing if https://github.com/mrdoob/three.js/issues/20997#issuecomment-754568017 solves your issue. Notice that you have to use `MeshStandardMaterial` since `MeshPhongMaterial` has no `vertexTangents` property.

> Three.js version: r142

I don't think we are that far yet^^.

**Comment by nbilyk** [comment] 2021-01-10 12:50
> I don't think we are that far yet^^.

:)  Oops, I meant r124, not 142.  I'm not using code from the future. 

Confirmed, the following code works on Android Chrome:

```
const planeGeo = new THREE.PlaneBufferGeometry(planeSize, planeSize);
const planeMat = new THREE.MeshStandardMaterial({
	map: groundTex,
	side: THREE.DoubleSide,
	vertexTangents: true
});
BufferGeometryUtils.computeTangents(planeGeo);
```

**Closed** 2021-01-10 13:04 UTC
Labels: Duplicate
