### ISSUE TITLE
Shadow problem with logarithmic depth buffer

### ISSUE THREAD

**Issue by 1147079942** [mrdoob/three.js#17525] opened 2019-09-18 07:11 UTC
use the `logarithmicDepthBuffer` cause shadow problem, use threejs r108dev
this is the example link
https://raw.githack.com/1147079942/three.js/dev/examples/webgl_shadowmap_viewer.html

##### Three.js version

- [x] Dev
- [x] r108
- [x] r107

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

**Comment by 1147079942** [comment] 2019-09-18 07:20
[problems arising from actual use](https://github.com/mrdoob/three.js/issues/17476#issue-492654943)

**Comment by Mugen87** [comment] 2019-09-18 11:56
Here is your code slightly modified as an interactive live example:

https://jsfiddle.net/yqxencra/

Indeed, it looks like a bug when rendering shadows with `logarithmicDepthBuffer`.

**Comment by WestLangley** [comment] 2019-09-18 23:05
>this is the example link
>https://raw.githack.com/1147079942/three.js/dev/examples/webgl_shadowmap_viewer.html

That branch is 722 commits behind mrdoob:dev.

This issue was likely fixed in #17441.

**Comment by 1147079942** [comment] 2019-09-19 01:37
i guess i know the reason, hope it can help. the meshDepthMaterial not use the logarithmicDepthBuffer extend. make meshDepthMaterial use the extend, if can set this parameter for meshDepthMaterial by custom could be better, it will affect my old function.
https://github.com/mrdoob/three.js/pull/17174#discussion_r312306578

**Comment by WestLangley** [comment] 2019-09-19 03:01
@1147079942 @Mugen87 Please try the current  dev branch `r.109dev`.

/ping @gkjohnson for your opinion

**Comment by gkjohnson** [comment] 2019-09-19 05:16
If I'm thinking about it correctly then what could be happening here is that because the directional light uses an orthographic camera the generation of the shadow map is being plagued by the depth buffer issues illustrated in #9108. While the values output to the shadow map are _not_ logarithmic the depth buffer is which results in an unexpected and incorrectly formed shadow map.

If that's what is causing the problem then I believe #17442 should have addressed this, as well. It would be good to test this on latest dev.

This issue also sounds like #7815 so that can probably also be closed if this is proven to have been fixed.

**Comment by Mugen87** [comment] 2019-09-19 07:24
> This issue was likely fixed in #17442.

Looks good: https://jsfiddle.net/qa53t8dm/

**Closed by Mugen87** 2019-09-19 07:24 UTC
Labels: Bug

**Comment by 1147079942** [comment] 2019-09-19 09:08
the shadow looks good, but what happen to that outside look.i will prefer not use the logarithmicDepthBuffer

**Comment by Mugen87** [comment] 2019-09-19 09:14
> but what happen to that outside look

Can you please explain what you mean by that?

**Comment by 1147079942** [comment] 2019-09-19 09:17
i can't up load the picture, it looks  not correct. the object's face is break.

**Comment by 1147079942** [comment] 2019-09-19 12:03
> > but what happen to that outside look
> 
> Can you please explain what you mean by that?

![image](https://user-images.githubusercontent.com/44154716/65242412-821ac000-db18-11e9-839a-5f3db3518248.png)

**Comment by Mugen87** [comment] 2019-09-19 12:06
Um, I don't see this artifacts on my computer. Can you please share your system specs? Besides, what browser are you using?

**Comment by 1147079942** [comment] 2019-09-19 12:11
> Um, I don't see this artifacts on my computer. Can you please share your system specs? Besides, what browser are you using?

system：mac

browser：chrome 76.0.3809.132 （all extend set is default）

**Comment by Mugen87** [comment] 2019-09-19 12:14
Can you please share the CPU and GPU model, too?

**Comment by 1147079942** [comment] 2019-09-19 12:18
> Can you please share the CPU and GPU model, too?

cpu : 17
gpu: NVIDIA GeForce gtx760

it's has problem with any browser and system here

**Comment by mrdoob** [comment] 2019-09-19 12:57
@1147079942 what version of MacOS?

**Comment by 1147079942** [comment] 2019-09-19 13:39
@mrdoob  10.13

**Comment by 1147079942** [comment] 2019-09-20 01:57
> what version of MacOS
![image](https://user-images.githubusercontent.com/44154716/65293226-13c41500-db8d-11e9-8676-b2cf898f58fa.png)

**Comment by 1147079942** [comment] 2019-09-20 02:04
![image](https://user-images.githubusercontent.com/44154716/65293275-42da8680-db8d-11e9-8abb-67723697eeca.png)
what's the truly reason cause that.

**Comment by WestLangley** [comment] 2019-09-20 02:49
Is this the test case you are using? https://jsfiddle.net/qa53t8dm/

**Comment by 1147079942** [comment] 2019-09-20 03:23
> https://jsfiddle.net/qa53t8dm/

![image](https://user-images.githubusercontent.com/44154716/65296997-fdbc5180-db98-11e9-9408-808e016b6fc8.png)

**Comment by WestLangley** [comment] 2019-09-20 03:29
Did you clear your cache first?

Do the artifacts appear when `logarithmicDepthBuffer` is `false`?

**Comment by 1147079942** [comment] 2019-09-20 03:37
> Did you clear your cache first?
> 
> Do the artifacts appear when `logarithmicDepthBuffer` is `false`?
of course and i has update the chrome to the newest version. this test code look good on my phone. but i try a lots of computer in my company, no one can render it correct.
when logarithmicDepthBuffer is false the picture looks ok.

**Comment by 1147079942** [comment] 2019-09-20 03:44
![21568951055_ pic_hd](https://user-images.githubusercontent.com/44154716/65297900-06625700-db9c-11e9-98ef-6aa35d7e63ce.jpg)
on the render picture on ipad looks object is right, but shadow is wrong

**Comment by WestLangley** [comment] 2019-09-20 03:57
Renders correctly on MacOS High Sierra 10.13.6 AMD Radeon HD 6750M, Chrome, FF, and Safari.

**Comment by 1147079942** [comment] 2019-09-20 04:16
> Renders correctly on MacOS High Sierra 10.13.6 AMD Radeon HD 6750M, Chrome, FF, and Safari.

some laptop is good. all the pc has same problem.
will you fix this compatibility of this problem? @Mugen87 @1147079942 @mrdoob

**Comment by Mugen87** [comment] 2019-09-20 08:50
> will you fix this compatibility of this problem?

If it's a hardware or driver issue, there is in general not much we can do. The problem is that I and the others can't reproduce the issue. That makes any kind of investigation more complicated.

> may i get some article or explain about this problem, thanks.

TBH, I have no idea what's going wrong. Does it work if you update the macOS version to the latest on (10.14.6)? Update the OS also updates system drivers.

**Comment by 1147079942** [comment] 2019-09-20 09:55
> > will you fix this compatibility of this problem?
> 
> If it's a hardware or driver issue, there is in general not much we can do. The problem is that I and the others can't reproduce the issue. That makes any kind of investigation more complicated.
> 
> > may i get some article or explain about this problem, thanks.
> 
> TBH, I have no idea what's going wrong. Does it work if you update the macOS version to the latest on (10.14.6)? Update the OS also updates system drivers.

I test so many personal computer, many windows system has the same problem, I don't think update the system or hardware can solve this very well.I afraid I need learn more about the shader now, wish me luck.

**Comment by WestLangley** [comment] 2019-09-20 16:46
I am not able to reproduce the artifacts, either.

@1147079942 I suggest you avoid using logarithmic depth buffer.
