### ISSUE TITLE
VR not working on Vive device

### ISSUE THREAD

**Issue by JeffesJiang** [mrdoob/three.js#18566] opened 2020-02-07 01:13 UTC
##### Description of the problem

All official vr examples show webxr not avaiable on my vr device, but the examples on the a-frame and immersiveweb.dev webpages are normal, using Google Chrome and the firefox reality browser available in the viveport store.

Hope to resolve

##### Three.js version

- [ ] Dev
- [x] r113
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [x] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [x] Android
- [ ] iOS

**Comment by mrdoob** [comment] 2020-02-07 03:20
Can you visit https://immersive-web.github.io/webxr-samples/ in the device and see if you have this message?

![Screenshot 2020-02-06 at 19 19 22](https://user-images.githubusercontent.com/97088/73998165-99b2e380-4915-11ea-85da-8c986422d03f.png)

Three.js removed WebVR support in December.

**Comment by JeffesJiang** [comment] 2020-02-07 06:03
> Can you visit https://immersive-web.github.io/webxr-samples/ in the device and see if you have this message?
> 
> ![Screenshot 2020-02-06 at 19 19 22](https://user-images.githubusercontent.com/97088/73998165-99b2e380-4915-11ea-85da-8c986422d03f.png)
> 
> Three.js removed WebVR support in December.



> Can you visit https://immersive-web.github.io/webxr-samples/ in the device and see if you have this message?
> 
> ![Screenshot 2020-02-06 at 19 19 22](https://user-images.githubusercontent.com/97088/73998165-99b2e380-4915-11ea-85da-8c986422d03f.png)
> 
> Three.js removed WebVR support in December.

My headset is an all-in-one device with built-in Android system, chrome and firefox reality provided by the Vive Store. After testing, it does not support xr, but it supports vrapi. Does the official document have corresponding operations? I am in China, and the corresponding documents and information are not easy to find.

**Comment by JeffesJiang** [comment] 2020-02-07 06:04
My headset is an all-in-one device with built-in Android system, chrome and firefox reality provided by the Vive Store. After testing, it does not support xr, but it supports vrapi. Does the official document have corresponding operations? I am in China, and the corresponding documents and information are not easy to find.

**Comment by JeffesJiang** [comment] 2020-02-07 06:07
> Can you visit https://immersive-web.github.io/webxr-samples/ in the device and see if you have this message?
> 
> ![Screenshot 2020-02-06 at 19 19 22](https://user-images.githubusercontent.com/97088/73998165-99b2e380-4915-11ea-85da-8c986422d03f.png)
> 
> Three.js removed WebVR support in December.

My headset is an all-in-one device with built-in Android system, chrome and firefox reality provided by the Vive Store. After testing, it does not support xr, but it supports vrapi. Does the official document have corresponding operations? I am in China, and the corresponding documents and information are not easy to find.

**Comment by mrdoob** [comment] 2020-02-07 06:11
I don't know about Chrome but I think Firefox Reality will support that device once they enable WebXR.

/cc @fernandojsg

**Comment by JeffesJiang** [comment] 2020-02-07 06:29
> I don't know about Chrome but I think Firefox Reality will support that device once they enable WebXR.
> 
> /cc @fernandojsg

The firefox reality browser on my device has been tested by the test webpage you gave me, and it shows that it does not support webxr. But support for using vrapi, need to use polyfill simulation. All the examples in the webpage https://immersive-web.github.io/webxr-samples/ will not run properly without polyfill, and projects that use polyfill will run normally, it is not clear whether it is my browsing Browser version, but this is the latest version of firefox reality 7.1 2020.1.8 provided by the store of my device. I want to know how to use polyfill simulation in threejs project, because it is no longer in the latest official document.

**Comment by Mugen87** [comment] 2020-02-25 14:33
Closing. Since WebXR is not supported by the device, the issue is not related to `three.js`. Consider to use the [forum](https://discourse.threejs.org/) if you have more questions about WebXR since github is for bugs and feature requests only.

**Closed by Mugen87** 2020-02-25 14:33 UTC
Labels: Browser Issue
