### ISSUE TITLE
Resized WebGLTextures are rotated 180 degrees

### ISSUE THREAD

**Issue by mghini** [mrdoob/three.js#16024] opened 2019-03-20 10:32 UTC
##### Description of the problem

When using a texture as a map for any kind material, if the texture is not a power of two it looks rotared 180 degrees

To reproduce the problem use the Editor, add a plane or a cube and assigna map to the attached material. If the texture is not a power of two you will see the texture image upside-down.
Strangely, It is working on Firefox.

##### Three.js version

- [ ] Dev
- [x] r102
- [ ] ...

##### Browser

- [] All of them
- [x] Chrome
- [ ] Firefox
- [x] Edge

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment] 2019-03-20 11:09
Duplicate of #15896.

The issue is already fixed in `dev` 👍

**Closed by Mugen87** 2019-03-20 11:09 UTC
