### ISSUE TITLE
GLTFLoader: Unable to load some SkinnedMesh objects in r148

### ISSUE THREAD

**Issue by Samsy** [mrdoob/three.js#25332] opened 2023-01-25 15:50 UTC
### Description

GLTFLoader did load correctly with this file before the GLTFloader optimisations : 
https://github.com/mrdoob/three.js/pulls?q=is:pr+GLTFLoader+is:closed+milestone:r148+in:title

File : 
https://res.cloudinary.com/oncyber-io/image/upload/v1666818159/assets/WorkerBot_Posed_10_24_1_eyoaob.glb

Recursive errors on it on threejs editor loader

<img width="464" alt="Screenshot 2023-01-25 at 16 37 39" src="https://user-images.githubusercontent.com/3786958/214606633-0ed27d55-c026-4978-9173-21e8ba9385f6.png">

### Reproduction steps

1. Go to threejs editor
2. Drap and drop glb
3.

### Code

```js
// code goes here
```

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/g3atw6k5/)
* [jsfiddle-dev](https://jsfiddle.net/hjqw94c5/)

### Version

last

**Comment by donmccurdy** [comment] 2023-01-25 16:05
It looks like our (refactored) loading process does not correctly handle this case:

1. Node 0 is the root node of the scene, and an ancestor of Node 5
3. Node 5 has a skinned mesh, for which Node 0 is both a joint and the skeleton root
4. `loadNode( index )` does not resolve until all node dependencies are resolved, so we hit an infinite loop

/cc @takahirox

**Comment by takahirox** [comment] 2023-01-26 04:55
Thanks for reporting the issue and investigation.

Yes, as @donmccurdy explained, loadNode - loadSkin - loadNode can cause "wait each other". Sorry for the regression. I will look into how to resolve. Perhaps skins need to be processed after building a scene graph (resolving all nodes) as we did before.

**Comment by Samsy** [comment] 2023-01-26 11:53
It's not the only case I guess : 

Before : 

<img width="745" alt="Screenshot 2023-01-26 at 12 34 53" src="https://user-images.githubusercontent.com/3786958/214828458-8eb06770-5022-4e96-9486-bd8845899f5d.png">

Now : 
its also looking like this in threejs.

![Uploading Screenshot 2023-01-26 at 12.34.53.png…]()


Note : model is displayed with an envmap here, but shows black in threejs editor

**Comment by arpu** [comment] 2023-01-26 13:27
> It's not the only case I guess :
> 
> Before :
> 
> <img alt="Screenshot 2023-01-26 at 12 34 53" width="745" src="https://user-images.githubusercontent.com/3786958/214828458-8eb06770-5022-4e96-9486-bd8845899f5d.png">
> 
> Now :
> 
> <img alt="Screenshot 2023-01-26 at 12 49 57" width="683" src="https://user-images.githubusercontent.com/3786958/214829199-d0f04ad4-28c9-42ef-9d40-b2c887e6f70c.png">
> 
> Note : model is displayed with an envmap here, but shows black in threejs editor
> 
> Model link :
> 
> https://openseauserdata.com/files/45645ed933109a4a5703bacffdf231ea.glb

this looks to a different Problem, this model use deprecated KHR_materials_pbrSpecularGlossiness

**Comment by donmccurdy** [comment] 2023-01-26 14:59
I've shared some file conversion options to upgrade spec/gloss materials to metal/rough materials in this thread: https://github.com/mrdoob/three.js/pull/24950#issue-1447274773

**Comment by takahirox** [comment] 2023-01-30 07:02
Progress...

https://github.com/takahirox/three.js/blob/FixGLTFLoaderNodeParse/examples/jsm/loaders/GLTFLoader.js

![image](https://user-images.githubusercontent.com/7637832/215409264-3e13716a-9a19-462a-a95c-b72fad730800.png)

**Closed** 2023-02-02 03:10 UTC
Labels: Regression, Loaders
