### ISSUE TITLE
Oculus Touch position is off after library update

### ISSUE THREAD

**Issue by autuus** [mrdoob/three.js#13657] opened 2018-03-21 20:28 UTC
oculus touch controller position is off around y + 1.65 after updating from r89 to r90, the issue is present in r91

**Comment by Mugen87** [comment] 2018-03-22 11:42
Can you please show your code?

BTW: Have you scene these changes: https://github.com/mrdoob/three.js/commit/cfd22c2c4f4621d770f3a5af68b0533e69af5959#diff-eb152a516883cb17690e595058479f49

I guess these PR also affects your application.

**Comment by Mugen87** [comment] 2018-03-29 12:46
Closing. We can reopen the issue if @autuus provides more information.

**Comment by autuus** [comment] 2018-04-23 22:37
Oh, sry, automails get lost in mail filters sometimes. So:
```
        var position = [
            controller.pose.position[0],
            controller.pose.position[1]+1.65,
            controller.pose.position[2]
        ]
 
```

Gamepad data from navigator
```

        this.gamepads = navigator.getGamepads()
 
        for (var i = 0; i < this.gamepads.length; i ++) {
            if (this.gamepads[i].id == "Oculus Touch (Right)") {
```

If someone wants to integrate Oculus Touch to threejs, and make a demo app and contribute it, would be appriciated.

Heres the rest of the controller code:
[https://pastebin.com/fwMNRRvs](https://pastebin.com/fwMNRRvs)

**Comment by autuus** [comment] 2018-04-23 22:44
So looks like threejs is compensating to an arbituary  height value there.

**Comment by autuus** [comment] 2018-06-25 09:01
As you can see, 
            controller.pose.position[1]+1.65, is a hack or a fix for this.

**Comment by mrdoob** [comment] 2018-08-30 03:12
I'm unable to reproduce this with the current examples:
https://threejs.org/examples/?q=webvr

**Closed by mrdoob** 2018-08-30 03:12 UTC
