### ISSUE TITLE
FBXLoader fails on animated custom attributes

### ISSUE THREAD

**Issue by charlesfleche** [mrdoob/three.js#13264] opened 2018-02-06 22:00 UTC
The FBXLoader fails for animated custom attributes, as they can be of type `P`, not handled by the regex. `curveNode` is then `undefined` and `curveNode.id` fails.

https://github.com/mrdoob/three.js/blob/608fb12d7cdb7d9bdce193d9c9e63fa082b8de81/examples/js/loaders/FBXLoader.js#L2189

FBX export: 
[scene.ascii.fbx.zip](https://github.com/mrdoob/three.js/files/1700960/scene.ascii.fbx.zip)

**Comment by looeee** [comment] 2018-02-06 22:16
This is already fixed in the dev branch. `curveNodesMap.set` is only called if the type is `S`, `R`, or `T`, otherwise the `curveNode` is ignored. 

I haven't considered whether it is desirable / possible to actually parse animated custom attributes however...

**Comment by charlesfleche** [comment] 2018-02-07 22:17
Is it possible to retrieve custom attributes at all from an FBX ? Are they supposed to be displayed in the `userData` block ?

**Comment by looeee** [comment] 2018-02-08 00:33
I'm not sure, I haven't considered any files with custom attributes. Certainly animating them will be a bit of work, but making them available to the user should be OK. 

What is the custom attribute in the file you shared?

**Comment by charlesfleche** [comment] 2018-02-08 07:21
```
        Model: 2325235904320, "Model::cube", "Mesh" {
                Version: 232
                Properties70:  {
                        P: "RotationActive", "bool", "", "",1
                        P: "InheritType", "enum", "", "",1
                        P: "ScalingMax", "Vector3D", "Vector", "",0,0,0
                        P: "DefaultAttributeIndex", "int", "Integer", "",0
                        P: "currentUVSet", "KString", "", "U", "map1"
                        P: "custom_object_attribute", "Number", "",
"A+U",0.324712644004659,0,1
                }
                Shading: T
                Culling: "CullingOff"
        }
```

The custom attribute is `custom_object_attribute`

**Comment by looeee** [comment] 2018-02-08 07:30
I saw that 😛 

Sorry, I should have been clearer. What I want to know is, what's your use case for custom attributes? Why do you need them to be added to the loader? 

If I can see how people are using these, and what they can can consist of, then I can figure out the best way of dealing with them.

**Comment by charlesfleche** [comment] 2018-02-08 08:11
I'm working on a WebVR scene where some objects can be marked interactive:
when activated, the animation (baked from Maya) of all the objects under a
root (also marked as custom attribute) will be played.

They are other ways to achieve this (naming conventions, scene structure /
hierarchy conventions), but custom attributes seemed like a good, flexible
way, especially if it tuns out that we need more of those flags as the
project grows.

**Comment by looeee** [comment] 2018-02-10 04:59
Can you share one of those files? Or a stripped down version that has the same custom attribute structure set up?

**Comment by charlesfleche** [comment] 2018-02-10 10:05
You mean, a Maya scene ? Yes I'll do asap

**Comment by looeee** [comment] 2018-02-10 11:11
I meant an FBX file, but a Maya scene is fine too as long as it's Maya 2017 or less.

**Comment by charlesfleche** [comment] 2018-02-11 19:55
Here is a very simple scene with just a locator at the origin. This locator has a custom attribute of each types allowed by Maya: `custom_attribute_integer`, `custom_attribute_vector`, etc.

I can't share a production scene, because I'm still sorting out our pipeline, so nothing is set in stone at the moment. However, should importing custom attributes to THREE works, I'll certainly have a bool `is_interactive` for the objects that will be interactive in the browser.

[custom_attribues.zip](https://github.com/mrdoob/three.js/files/1714778/custom_attribues.zip)

**Comment by looeee** [comment] 2018-03-07 10:35
I've had a look at this and I don't think we should support these custom attributes.

The model has the following data once parsed:

```
custom_attribute_boolean :{type: "Bool", type2: "", flag: "A+U", value: "0"}

custom_attribute_enum: {type: "Enum", type2: "", flag: "A+U", value: "0,_"EnumValue1~EnumValue2~EnumValue3"}

custom_attribute_float : {type: "Number", type2: "", flag: "A+U", value: 0}

custom_attribute_integer: {type: "Integer", type2: "", flag: "A+U", value: "0,0,1"}

custom_attribute_string : {type: "KString", type2: "", flag: "U", value: ""}

custom_attribute_vector : {type: "Vector", type2: "", flag: "A+U", value: "0,0,0"}
```

The problem is that this is Maya specific code and so far we've (nearly entirely) avoided bloating the loader with any app specific code. For example, 3DS Max adds lots of non-standard attributes prefixed with "3DSMAX" regarding things like physical materials and it all gets silently ignored. 

@charlesfleche it should be fairly straightforward to make a custom version of the loader if you still need this.

**Comment by looeee** [comment] 2018-03-07 10:35
Closing for now

**Closed by looeee** 2018-03-07 10:35 UTC
Labels: Loaders
