### ISSUE TITLE
glTF conformance: khronos-RecursiveSkeletons

### ISSUE THREAD

**Issue by elalish** [mrdoob/three.js#22484] opened 2021-09-01 21:58 UTC
This test looks almost correct, but there's some baseline shift. Not sure if this is  related to one of the other open skeleton bugs (we do use SkeletonUtils to clone everything in MV, so it could be specific to the cloning step). https://modelviewer.dev/fidelity/#khronos-RecursiveSkeletons

**Comment by donmccurdy** [comment] 2021-09-02 04:40
Do you see the baseline shift in https://github.com/cx20/gltf-test? 

There is the issue of calculating a bounding box correctly for a SkinnedMesh as well; that seems like the more likely cause if the viewport is off center.

**Comment by Mugen87** [comment] 2021-09-02 09:46
Related #21507.

The same approach from the PR could be used for `SkinnedMesh`.

**Comment by Mugen87** [comment] 2021-09-03 09:14
If the wrong bounding box of the skinned mesh is the root cause, this issue can be merged in #14499.

**Comment by elalish** [comment] 2021-09-03 15:49
That does seem likely.

**Comment by Mugen87** [comment] 2021-09-03 20:47
Merging into #14499 then 👍 .

**Closed by Mugen87** 2021-09-03 20:47 UTC
