### ISSUE TITLE
.basis and .ktx2 textures working intermittently on Safari

### ISSUE THREAD

**Issue by igghera** [mrdoob/three.js#19717] opened 2020-06-23 08:37 UTC
##### Description of the problem

While testing the official example for the BasisTextureLoader on my devices (iPhone X, MacBook Pro 16) I noticed that sometimes the texture did not appear and the cube remained white.

At first I thought of a network error or similar, so I started digging.

- No error happens on the Network, no error in the console. 
- The loading progress is logged in the console and it's ok.

I have uploaded a screen capture of the whole thing [here](https://drive.google.com/file/d/1lWv8HNVNOFR-3mtf0fwIrWh15AFvyBfI/view).

The link to the official example is this: https://threejs.org/examples/?q=basis#webgl_loader_texture_basis

Not sure if it helps, but these guys here use the .basis format in this demo and that seems to work fine on Safari even after 50 page reloads: https://demo.shapespark.com/naniby-apartment-basis/
Maybe it's just a bug that has been introduced in a recent version? 

I really hope so :) I've just discovered the basis format and I'm looking forward to using it into my projects.

I'll try to go through the source code of the BasisTextureLoader myself and see if I can debug it. Being intermittent makes it really hard. 

Thanks for the great work to everyone!

##### Three.js version

- [ ] Dev
- [x] r117
- [ ] ...

##### Browser

- [x] Safari
- [x] iOS Safari

##### OS

- [ ] All of them
- [ ] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [x] iOS

**Comment by mrdoob** [comment] 2020-06-23 16:11
It may be worth reporting the issue to basis directly:
https://github.com/BinomialLLC/basis_universal

**Comment by igghera** [comment] 2020-06-23 16:24
I thought about it, then I went to their [examples page](https://github.com/BinomialLLC/basis_universal/blob/master/webgl/README.md) and I could not reproduce the bug even after refreshing the page 100 times, hence I thought it could be an issue with the three.js loader. 

But I'm not sure whether my logic makes sense or not.

The thing that baffles me the most is this one:

> Not sure if it helps, but these guys here use the .basis format in this demo and that seems to work fine on Safari even after 50 page reloads: https://demo.shapespark.com/naniby-apartment-basis/

If their version works fine, what is the difference there? The version of three.js? 
Although if I log THREE.revision it says "71" and I don't understand how that's possible.

Anyhow, @mrdoob if you think it makes sense I can open an issue on basis' repo

**Comment by JordyvanDortmont** [comment] 2020-06-24 13:03
We're currently having an issue with loading our own **recently compressed** basis textures as well. Our (probably separate) issue occurs on Chromebooks Google Chrome OS, Version 83.0.4103.112. The basis texture does not load anymore and loading the same basis texture worked on a previous Chrome OS build. 

This is relevant, because we discovered that the three.js example loads a basis texture that hasn't been re-compressed since June 2019. The basis texture example still works for the Chrome OS build that does not load our recently compressed basis texture. It might be a good idea to re-compress the basis texture of the example and check if it works consistently for Safari.

**Comment by igghera** [comment] 2020-06-29 13:31
@JordyvanDortmont I don't have any machine to run Chrome OS, but I'd be curious to see if the issue with Safari happens with your textures, both the recently compressed and the old ones. 

I have looked into the three.js BasisTextureLoader but I have no idea how to solve the problem. It doesn't throw an error, it only happens sometimes... I'm stuck.

Out of curiosity, do you guys use any special parameter when using the basis universal codec? I simply run `basisu image.jpg` with no special inputs

**Comment by JordyvanDortmont** [comment] 2020-06-29 15:39
> Out of curiosity, do you guys use any special parameter when using the basis universal codec? I simply run basisu image.jpg with no special inputs

@igghera it might be the mipmaps! Maybe you can try `basisu -mipmap image.jpg`.

**Comment by JohannesDeml** [comment] 2020-06-29 16:15
@JordyvanDortmont @igghera I'm using basis textures with mipmaps which are created with version 1.12 (latest version as of now). I didn't find the described problems. Tested on Chrom+Firefox on Windows and Safari on iOS. Here is a simple example scene with the latest threejs version: https://rawcdn.githack.com/JohannesDeml/three.js/37a8f7fd309b15900c624252147cbbec70bcc6eb/examples/webgl_loader_gltf_basis.html
Can you reproduce your problem in this minimal setup?

**Comment by donmccurdy** [comment] 2020-06-29 17:29
^This example is working consistently in Safari on macOS 10.15.5 for me.

**Comment by JordyvanDortmont** [comment] 2020-06-30 09:26
Can confirm this works consistently on Safari on iOS 12.4.6 @JohannesDeml.

@igghera the issue that the textures only load intermittently and the cube remains white also occurs on Windows 10 Chrome for [this example](https://raw.githack.com/dialoguetrainer/three.js/master/examples/webgl_loader_texture_basis.html). Although I can't reproduce it on my own device. Maybe it has something to do with https://github.com/mrdoob/three.js/pull/19541?

The example of @JohannesDeml turns black on Windows 10 Chrome, because of the `ImageBitmapLoader` bug that was fixed in r118.3 (https://github.com/mrdoob/three.js/pull/19738).

**Comment by JohannesDeml** [comment] 2020-06-30 09:36
> The example of @JohannesDeml turns black on Windows 10 Chrome, because of the `ImageBitmapLoader` bug that was fixed in r118.3 (#19738).

Oh, you're right, I posted the link I used for the bug report, here is the new one that works in chrome as well: https://rawcdn.githack.com/JohannesDeml/three.js/2ac64131c77a82a86b0726845e5d83450b2f7898/examples/webgl_loader_gltf_basis.html

**Comment by JordyvanDortmont** [comment] 2020-06-30 11:02
Alright that works on Windows 10 Chrome! Thanks for updating your example. I checked our example again and the issue was that we didn't use the `rawcdn`, so I fixed the link in my previous comment.

**Comment by JordyvanDortmont** [comment] 2020-07-01 22:13
Update on the issue I mentioned here https://github.com/mrdoob/three.js/issues/19717#issuecomment-648806402:
https://bugs.chromium.org/p/chromium/issues/detail?id=1100834

**Comment by wrr** [comment] 2020-07-03 14:48
> https://demo.shapespark.com/naniby-apartment-basis/

We had a similar problem on Safari with a code that runs this demo. We've managed to figure out that workers on Safari were silently dying while decoding Basis textures. We haven't managed to figure out what is causing this and added a workaround to disable decoding in workers on Safari. Our code doesn't use examples/jsm/loaders/BasisTextureLoader.js, but because this loader also uses workers, this can be the same issue.

**Comment by donmccurdy** [comment] 2021-03-18 00:14
Seeing the same issue with KTX (which relies on BasisTextureLoader) too apparently. :( 

https://threejs.org/examples/?q=ktx#webgl_loader_texture_ktx2

**Comment by lexaknyazev** [comment] 2021-03-18 13:46
@donmccurdy 
>https://threejs.org/examples/?q=ktx#webgl_loader_texture_ktx2

That demo works for me in Safari 14.0.3 / macOS 11.2.3

**Comment by donmccurdy** [comment] 2021-04-01 02:58
Same versions and OS here (Safari 14.0.3 / macOS 11.2.3) but still broken. Note that it does work most of the time, but within a few page reloads will fail.

Additional details: MacBook Pro (15-inch, 2018), Radeon Pro 555X 4 GB.

**Comment by lexaknyazev** [comment] 2021-04-01 04:14
I can confirm that the demo fails after the page is reloaded on Safari 14.0.3 as well as on Safari Technology Preview 122 (Safari 14.2, WebKit 16612.1.6.2).

MacBook Air (M1, 2020).

**Comment by Mugen87** [comment] 2021-08-31 09:48
I've tested this issue today on an iPad (8th generation) and iPadOS 14.7.1. The issue still appears with `webgl_loader_texture_basis`. In 1 out of 10 reloads, the plane is white and no texture is applied.

I was not able to reproduce the problem on Windows or Android. On macOS, it only happens in Safari but not with Chrome.

Considering this and https://github.com/mrdoob/three.js/issues/19717#issuecomment-653581829, it clearly looks like a WebKit issue. Probably best to report it at: https://bugs.webkit.org/.

**Comment by Mugen87** [comment] 2021-08-31 10:25
I've filed https://bugs.webkit.org/show_bug.cgi?id=229706

**Closed** 2021-08-31 10:25 UTC
Labels: Browser Issue

**Comment by reececomo** [comment] 2025-02-17 06:41
For future readers (me): **Avoid most issues: only use Power of Two (POT) dimensions and limit textures to ≤2048px**

Sadly, even in 2025.

- iOS Safari unpacks basis/ktx2 textures to **ETC1/ETC2** or **ASTC**
  - ✅ ASTC has good support for NPOT textures
  - ⚠️ ETC1/ETC2 has mixed support for NPOT textures
- iOS Safari officially supports **4096^2** on modern devices
  - in practice, it very much does not enjoy anything above 2048 for us (crashes, losing webgl context, etc.)

In most cases you can just pad textures to nearest pow2 (e.g. `512x256px`), and voila, iOS Safari should start working _flawlessly_† 💅

```sh
copy_to_pow2() {
    local input="$1"
    local output="${input%.*}.pow2.${input##*.}"

    magick "$input" \
        -background none \
        -extent "%[fx:2^ceil(log(w)/log(2))]x%[fx:2^ceil(log(h)/log(2))]" \
        "$output" \
        > /dev/null
}
```

```sh
# take an image with odd dimensions:
copy_to_pow2 ./image.png

# pad it out:
# ./image.pow2.png
```

<sub>†To the maxmimum extent that iOS Safari can work flawlessly. Good luck staying under the memory limit</sub>
