### ISSUE TITLE
Support for up to 64 GPU blendshapes/morphTargets required for Pro-Level Facial Animation

### ISSUE THREAD

**Issue by bhouston** [mrdoob/three.js#21636] opened 2021-04-12 12:30 UTC
**Is your feature request related to a problem? Please describe.**

High fidelity facial animation requires a lot of blend shapes.  For example, here is a standard blend shape set from Apple for facial animation that they can extract from their cameras.  It has 57 blend shapes.

https://developer.apple.com/documentation/arkit/arfaceanchor/blendshapelocation

It was utilized in this demo that drove a ReadyPlayerMe avatar in Three.js via the Apple ARFaceAnchor blend shapes:

https://twitter.com/seflless/status/1381313468926676997

You can see here that Three.js currently limits morphTargets (a less common name for blend shapes) to just 4:

https://github.com/mrdoob/three.js/blob/dev/src/renderers/shaders/ShaderChunk/morphtarget_vertex.glsl.js 

**Describe the solution you'd like**

It would probably be best to look are removing a hard upper limit to the number of blend shapes, or to bring it to 64 (which seems like a safe number.)

**Describe alternatives you've considered**

We have currently implemented unlimited blend shapes via the CPU rather than the GPU.  This allows for unlimited number of blend shapes but it is significantly slower.

**Additional context**

I've asked @selfless to join this conversation to describe how he implemented it so his approach could inform how this will become standard in the library.

**Comment by Mugen87** [comment] 2021-04-12 12:39
Some code for this was once shared here in https://github.com/mrdoob/three.js/issues/15556#issuecomment-478161986

**Comment by bhouston** [comment] 2021-04-12 12:49
Here are some options:
* Have a scheme that can calculate the blend shapes on the CPU.  Basically an option to switch to CPU blend shape evaluation.
* I think the GPU limitations are severe and could not scale up to 64 vertex and normal attributes.  This means that there may need to be a way around using attributes for these.

Methods around the GPU limitation on attribute numbers:
* Use a data texture: https://www.robg3d.com/projects/texture-based-blendshapes-in-dx9/. Probably requires an FP32 or FP16 texture extension?
* Doing some research I see this paper from NVIDIA that uses the "StreamOut" feature of DirectX 10 to do this: https://developer.nvidia.com/gpugems/gpugems3/part-i-geometry/chapter-3-directx-10-blend-shapes-breaking-limits. I am unsure if there is an equivalent in WebGL -- but I doubt it.
* Could one do a special pre-render loop where one updates the blend shape geometries using a transform feedback shader?  One could have a vertex shader that could run multiple times, say with 8 or 16 vertex blend shapes each time and it would accumulate the results?  This would be a transform feedback shader: https://developer.mozilla.org/en-US/docs/Web/API/WebGLTransformFeedback. This is just a idea -- I haven't seen evidence it can work, but it may.  Transform Feedback shaders are only available in WebGL2.

**Comment by bhouston** [comment] 2021-04-12 14:19
@selfless has replied and said that he based his unlimited blend shape method on data textures:

https://twitter.com/BenHouston3D/status/1381585681286377474

**Comment by mattrossman** [comment] 2021-04-12 14:20
BabylonJS 5.0 also implemented infinite blend shapes using a texture array, with support limited to WebGL2. See their "how it works" video: https://www.youtube.com/watch?v=LBPRmGgU0PE

**Comment by Francois-Laberge-Bose** [comment] 2021-04-12 14:37
Here's my code for reference, including warts and all. I'll come back with clearer code later, at work now. Again, no support on at least iOS because of the lack of support for float textures (`THREE.RGBFormat, THREE.FloatType`). 

Note: I was focused on getting ReadyPlayerMe avatars running in browser. You'll see the number 63 hardcoded in this one, but that's unnecessary obviously. [See video of current demo (Twitter)](https://twitter.com/seflless/status/1381313468926676997)



https://user-images.githubusercontent.com/34040155/114412476-2214c000-9b7b-11eb-8574-2c4dc48000f0.mov

```js
const loader = new GLTFLoader();
// Load a glTF resource
loader.load(
    // resource URL
    avatarURL,
    // called when the resource is loaded
    function(gltf) {
        avatar.current = gltf
        scene.add(avatar.current.scene);

        changeToTextureBasedMorphTargets(avatar.current.scene.getObjectByName("Wolf3D_Head"));
        changeToTextureBasedMorphTargets(avatar.current.scene.getObjectByName("Wolf3D_Teeth"));

        /* Modifications to do
            1. Create texture of all morphTarget points
            2. Remove existing morphtarget related attributes
            3. Disable all morphTarget logic by setting appropriate flags
            4. Replace existing vertex shader morphTarget declarations with our own
          */
        function changeToTextureBasedMorphTargets(skinnedMesh) {
            // Create morphTarget positions texture
            let size = 4096 * 4096;
            let data = new Float32Array(3 * size);
            let vertIndexs = new Float32Array(skinnedMesh.geometry.attributes.position.count);
            //Loop over each original vertex
            let stride = 0;
            let vertexId = 0;
            let min = Number.MAX_VALUE;
            let max = Number.MIN_VALUE;
            for (let v = 0; v < skinnedMesh.geometry.attributes.position.array.length; v += 3) {
                //Loop over all blendshapes
                for (let i = 0; i < skinnedMesh.geometry.morphAttributes.position.length; i++) {

                    let morphAttr = skinnedMesh.geometry.morphAttributes.position[i];

                    //checkMinMax(morphAttr.array, v);

                    //Copy x, y, and z for the given vertex
                    data[stride] = morphAttr.array[v];
                    data[stride + 1] = morphAttr.array[v + 1];
                    data[stride + 2] = morphAttr.array[v + 2];

                    stride += 3;
                }

                vertexId++;
                //Also set vertIndex at v to v which is the vert index
                vertIndexs[vertexId] = vertexId;
            }
            console.log("min: ", min, "max: ", max);

            function checkMinMaxComponent(value) {
                if (value < min) {
                    min = value;
                }
                if (value > max) {
                    max = value;
                }
            }

            function checkMinMax(array, startIndex) {
                checkMinMaxComponent(array[startIndex]);
                checkMinMaxComponent(array[startIndex + 1]);
                checkMinMaxComponent(array[startIndex + 2]);
            }

            // Remove existing morph target code related attributes
            skinnedMesh.geometry.deleteAttribute("morphTarget0");
            skinnedMesh.geometry.deleteAttribute("morphTarget1");
            skinnedMesh.geometry.deleteAttribute("morphTarget2");

            // Add new vert index attribute
            skinnedMesh.geometry.addAttribute('vertIndex', new THREE.BufferAttribute(vertIndexs, 1));

            //CREATE DATA TEXTURE AND PLACE ON SHADER MAT
            let dataTexture = new THREE.DataTexture(data, 4096, 4096, THREE.RGBFormat, THREE.FloatType);
            dataTexture.needsUpdate = true;

            //Disable all morphTarget logic by setting appropriate flags
            skinnedMesh.material.morphTargets = false;
            skinnedMesh.material.morphNormals = false;

            const morphTargetDeclarations = `
            //Data texture
            uniform sampler2D texture0;
            //Blendshape influences
            uniform float morphTargetInfluences[63];
            //Current vertex index
            attribute float vertIndex;
            `;
            const morphTargetVertexShaderCode = `
            
            //Offset used for fixing the x y coordinates on the data texture
            float offset = vertIndex * 63.;
            //Loop over every blendshape
            for(int i=0; i<63; i++) {
              float iFloat = float(i);
              //If influence is 0, lets not waste GPU processing, move on
              if(morphTargetInfluences[i] == 0.) {
                continue;
              }
              //Find the x and y position of the vertex data based on vertex index and blendshape index
              float x = mod(offset + iFloat, 4096.);
              float y = ((offset + iFloat) / 4096.);
              
              //Grab the data at x and y
              vec2 texCoord = vec2(x / 4096.,y / 4096.);
              vec4 data = texture2D(texture0, texCoord);
              
              //Modify the current vertex position with the data found in the texture and the current blendshape influence
              transformed.x += data.x * morphTargetInfluences[i];
              transformed.y += data.y * morphTargetInfluences[i];
              transformed.z += data.z * morphTargetInfluences[i];
            }
          `


            // Replace all existing morph target vertex shader code with our own
            skinnedMesh.material.onBeforeCompile = function(shader) {
                // Add new necessary uniforms
                shader.uniforms.texture0 = {
                    type: 't',
                    value: dataTexture
                };
                // Now when we change the morphTargetInfluences it's linked to show up in the 
                // vertex shader
                shader.uniforms.morphTargetInfluences = {
                    value: skinnedMesh.morphTargetInfluences
                };

                // Replace morphTarget code declarations with our own
                shader.vertexShader = shader.vertexShader.replace(
                    "#include <morphtarget_pars_vertex>",
                    morphTargetDeclarations
                );

                shader.vertexShader = shader.vertexShader.replace(
                    "#include <morphtarget_vertex>",
                    morphTargetVertexShaderCode
                );
            };
        }
    },
    // called while loading is progressing
    function(xhr) {
        console.log((xhr.loaded / xhr.total * 100) + '% loaded');
    },
    // called when loading has errors
    function(error) {
        console.log('An error happened');
    }
);```

**Comment by Francois-Laberge-Bose** [comment] 2021-04-12 14:44
Some thoughts on what's next:

 - Try encoding the points in regular textures instead
   - This is a challenge as with only 256 bits per channel, if you encode say [-0.5m, 0.5m] from that you get 1m/256 = 7.8mm of resolution, that's almost a centimeter, and artifacts will be noticeable for things like facial animation.
   -  I was starting to look at encoding for the exact range of values that were in my readyplayerme avatar, which is much less than a meter. So you could make the encoding be based on the actual value range in a particular model, but this means two passes over the blendshapes to first calculate min/maxes. Again, pre generating get away from that, but then you are dealing with non standard glb files. Perhaps an extension or something special can be put in the file that three.js or others are aware of. 
 - Make sure texture size is the minimal it can be
 - (Optional) Come up with script to pre-process a glb you know you are going to load, to pre-generate the lookup texture and strip out the morphTarget points from the file

**Comment by seflless** [comment] 2021-04-12 14:55
A little self promotion here, but if you are interested in an upcoming tool/app for streaming iOS/standalone-VR to the web, follow this account, where I'll be sharing the progress, and announcements about the beta. The above was created for this work:
https://twitter.com/keypoints_app
<img style="width: 64px" src="https://user-images.githubusercontent.com/1845/114415160-6dc86900-9b7d-11eb-9b0d-b75b44c4c4e2.jpeg"/>

**Comment by bhouston** [comment] 2021-04-12 15:06
@seflless very awesome!  You said that iOS doesn't support float textures, but my iPhone does.  it supports OES_texture_float, OES_texture_half_float.  But can it access them in the vertex shader?  Also Safari supports these extensions.  I believe that nearly every modern device supports these two extensions now - or they support WebGL2 which requires these extensions I believe.

**Comment by seflless** [comment] 2021-04-12 15:13
I'm going to have to rerun my app and debug it to share the error. I swear I also confirmed it was not going to be supported on iOS. I could not find any links in my notes about this though. Looks like I broke the code I deployed, so I'm going to have to fix something before I can show a reproduce-able error.

**Comment by bhouston** [comment] 2021-04-12 15:14
I ran the web app here because you shared the URL in the video.  I got XR errors on attempt to load in Safari anywhere.  It worked on Chrome because it supports the XR interfaces.

**Comment by Francois-Laberge-Bose** [comment] 2021-04-12 15:16
Yeah, I'm deploying a fix for that. I wasn't checking for the existence of navigator.xr before calling it. I'm supporting WebXR previewing of the stream, and using VR for head+hand tracking capture.

**Comment by seflless** [comment] 2021-04-12 15:41
Ok the unrelated bug is fixed, I get the following error:
```js
THREE.WebGLRenderer: EXT_color_buffer_float extension not supported.
```
More about what the EXT_color_buffer extension gets you: https://developer.mozilla.org/en-US/docs/Web/API/EXT_color_buffer_float

This is why I believed it wasn't posssible:
https://developer.mozilla.org/en-US/docs/Web/API/EXT_color_buffer_float#browser_compatibility


<img width="1680" alt="Screen Shot 2021-04-12 at 11 35 29 AM" src="https://user-images.githubusercontent.com/1845/114421603-7623a280-9b83-11eb-8e70-f0bc0b70eb78.png">



Ok, here you go to see for yourself:
http://keypoints.vercel.app/

**Comment by seflless** [comment] 2021-04-12 15:47
Note: while you don't have the unreleased iOS app to get a live blendshape stream, you can press the `Play / Pause` button to see the blend shape anima
![Screen Shot 2021-04-12 at 11 47 06 AM](https://user-images.githubusercontent.com/1845/114423072-d1a26000-9b84-11eb-83dd-8159ad5c4e03.png)
tion in action.

**Comment by bhouston** [comment] 2021-04-12 15:52
I think you do not need EXT_color_buffer_half_float or EXT_color_buffer_float because I believe these are only needed if you want to **render** to a float or half_float render target.  In this case you want to **read** from a texture that is float or half_float.  This only requires the extensions I mentioned earlier right?  Or am I missing something.

**Comment by seflless** [comment] 2021-04-12 16:02
I haven't read and tried things enough about the different extensions to understand the difference in functionality and support. Just reporting what I know and notes for my interpretation. If anyone wants to figure out why I'm getting that error in iOS safari and what the solution is, be my guest. Any help is appreciated. Peak at the code in the mean time if you'd like.

**Comment by JosephCoppola-FW** [comment] 2021-04-12 19:58
I just want to note that the solution @Francois-Laberge-Bose attached above is how our production app solves this issue with our face rig that has 137 blendshapes. This solution proves to work effectively for our use case, where we are driving 137 blendshapes in realtime from raw mocap data.

**Comment by seflless** [comment] 2021-04-12 20:04
@JosephCoppola-FW which app? Excuse the confusion. But I was using my work email. I'm @Francois-Laberge-Bose, but this @seflless is my personal github.

**Comment by JosephCoppola-FW** [comment] 2021-04-12 20:07
@seflless https://www.youtube.com/watch?v=mfAmZ-Y3Dk4. 

This video shows the realtime retargeting of facial tracking data to a rig in three js, animating far more than the base supported blendshapes. The rig is loaded into a webview of our app, and the shader is applied. From there, we can set the morph target influences and the shader handles the rest! It was funny to see the above code you wrote, as I had to work on this issue nearly 2 years ago over in #15556.

**Comment by Francois-Laberge-Bose** [comment] 2021-04-12 20:46
@JosephCoppola-FW Yeah, I should say. Your work was definitely what got me started. I just had to figure out how to hook into the vertex shaders post GLB load, for my use case. Thanks for your sharing!

**Comment by JosephCoppola-FW** [comment] 2021-04-12 20:57
@Francois-Laberge-Bose You are most welcome! It is why I shared in the first place, this is a complex issue! Credit to @jspdown for the original idea and the help implementing. They originally came up with the original solution in #6465, a whole 5 years ago!

**Comment by ManishJu** [comment] 2021-07-08 16:07
@Francois-Laberge-Bose When using low size textures like 4096x4096 I get anomalies like single vertices being left out from the whole mesh and not experiencing any pull from the morph targets. Any reason for the code to produce such anomalies in meshes with vertices around 5500 :

https://user-images.githubusercontent.com/24234466/124955415-ef118980-e00e-11eb-92ba-48b750dd24c2.mp4

**Comment by Francois-Laberge-Bose** [comment] 2021-07-08 16:19
@ManishJu  I can't think of any reason off of the top of my head. Make sure you have a big enough texture or weird stuff is definitely going to happen. This needs to be true: 4096*4096 >= vertexCount*blendShapeCount. I can't tell if you have only 21 blendShapes above, 21*5500 = 115500 is definitely than 4096x4096 = 16777216

**Comment by ManishJu** [comment] 2021-07-08 16:59
Yes have only 22 blend shapes, unfortunately the texture I need to use is 12288 x 12288 in order to avoid any of those anomalies which is quite big and requires 1811.939328 mb of space 😐.

**Comment by Francois-Laberge-Bose** [comment] 2021-07-08 17:04
That is very odd. Good luck figuring it out, I can't really help you without digging into code, and I'm swamped with work right now.

**Comment by ManishJu** [comment] 2021-07-23 12:06
Just for the update :

You can remove the spikes if you are using single mesh with single geometry by the following line in shader :

//Find the x and y position of the vertex data based on vertex index and blendshape index
```
float x = mod(offset + iFloat, 4096.);
float y = ((offset + iFloat) / 4096.);
```
              
to 
```

float x = floor(mod(offset + iFloat, 4096.));
float y = floor(((offset + iFloat) / 4096.));

```
and have the optimized texture size  using : 

```

let lengthOfPositionAttributes = skinnedMesh.geometry.attributes.position.array.length;
let lengthOfMorphAttributes = skinnedMesh.geometry.morphAttributes.position.length;
let textureWidthAndHeight = Math.ceil(Math.sqrt((lengthOfPositionAttributes * lengthOfMorphAttributes / 3)));
```

**Comment by ManishJu** [comment] 2021-07-23 12:39
In general the above script now fully automated, you just need to pass the above calculated texture size & number of shape keys as a uniform to the shader and use it. There would be no change required when loading any kind of mesh except that the size of the mesh(x3) should not exceed the Float32Array limit and the texture size cannot go beyond 16k ( webgl 2 limit)

**Comment by bhouston** [comment] 2021-07-23 12:42
Any way we can get this merged into Three.js?  This is amazing stuff and widely needed.

**Comment by ManishJu** [comment] 2021-07-23 12:53
@mrdoob  @Mugen87 can tell better. Is anything else is of concern in this which I missed  ?

**Comment by Mugen87** [comment] 2021-07-23 13:18
A first step for implementing a built-in solution would be an animated glTF asset for testing. Can somebody recommend a model that we can safely use in the official examples? An animated face like above would be a nice showcase.

**Comment by seflless** [comment] 2021-07-23 13:26
If it's not considered uncool to end promoting a company indirectly, definitely the ReadyPlayerMe models are awesome, which is what the above is. Many people would love to have easily accessible/popular avatars the RPM are killing it. I am in no associated with them, by the way. If you want to do that, you can just go to https://readyplayer.me/, use their avatar creator, and download the glTF file they generate at the end to get a file you could commit. Their models have a lot of blendshapes and vertices, which is why I needed this functionality in the first place.

It's a contributor's call, I'm not attached to the above happening or not.

**Comment by mattrossman** [comment] 2021-07-23 14:18
I'm also a fan of RPM. Note from their download dialog:

![firefox_61e6dvYFjV](https://user-images.githubusercontent.com/22670878/126795027-f8c0f4af-fef6-4e33-ae9c-c5be18e95f19.png)

which links to [this page with licensing info.](https://creativecommons.org/licenses/by-nc-sa/4.0/) Sounds like as long as attribution is provided and the license is included it would be fine.

**Comment by mattrossman** [comment] 2021-07-23 14:24
It would be funny to get the avatar Ricardo uses in his Twitter profile as tribute 😅 

![mrdoob-avatar](https://pbs.twimg.com/profile_images/1264791071038435329/qVBo7vx7_400x400.jpg)

**Comment by seflless** [comment] 2021-07-23 14:41
@ManishJu So the bug was basically that texture interpolation was causing the issue, as in without that floor, accuracy or some other bug was cause sampling the vertex texture could end up sampling across up to 4 vertices instead of being snapped to 100% be the value it's supposed to be?

Also, shouldn't this change:

```
float x = floor(mod(offset + iFloat, 4096.));
float y = floor(((offset + iFloat) / 4096.));
```

should have 4096 replaced with the appropriate dynamic value to be generalized as you say? Mind posting the final total code including that a fix for this? It would be much appreciated for the record.

**Comment by ManishJu** [comment] 2021-07-23 14:55
yes and yes, as I mentioned you can pass the texture size to the shader as I am doing in my code right now. Yes I will post the final code eod today hopefully or tomorrow morning.

**Comment by ManishJu** [comment] 2021-07-23 16:20
Here is the final piece :

```
const loader = new GLTFLoader();
const url = "models/gltf/suz5.glb";

loader.load(url, function (gltf) {

    mesh = gltf.scene.children[0];
    scene.add(mesh);
    mesh.material.wireframe = true;
    changeToTextureBasedMorphTargets(mesh);


    /* Modifications to do
        1. Create texture of all morphTarget points
        2. Remove existing morphtarget related attributes
        3. Disable all morphTarget logic by setting appropriate flags
        4. Replace existing vertex shader morphTarget declarations with our own
    */
    function changeToTextureBasedMorphTargets(skinnedMesh, textureSize) {

        let lengthOfMorphAttributes = skinnedMesh.geometry.morphAttributes.position.length;

        //4 morph attributes are already supported by webgl2. No need of this shader code
        if (lengthOfMorphAttributes > 4) {

            let vertIndexs = new Float32Array(skinnedMesh.geometry.attributes.position.count);
            let stride = 0;
            let vertexId = 0;
            let min = Number.MAX_VALUE;
            let max = Number.MIN_VALUE;
            let lengthOfPositionAttr = skinnedMesh.geometry.attributes.position.array.length;

            let exactTextureSizeNeeded = Math.ceil(Math.sqrt((lengthOfPositionAttr * lengthOfMorphAttributes / 3)));

            //if you are not happy with the texture size or want to speed up you can pass the texture size into this function
            let textureSizeUsed = textureSize || exactTextureSizeNeeded;

            // not to go above the limit of webgl2 
            textureSizeUsed = Math.min(16384, textureSizeUsed);

            let size = textureSizeUsed * textureSizeUsed;
            data = new Float32Array(3 * size);

            for (let v = 0; v < lengthOfPositionAttr; v += 3) {
                //Loop over all blendshapes
                for (let i = 0; i < lengthOfMorphAttributes; i++) {

                    let morphAttr = skinnedMesh.geometry.morphAttributes.position[i];

                    checkMinMax(morphAttr.array, v);

                    //Copy x, y, and z for the given vertex
                    data[stride] = morphAttr.array[v];
                    data[stride + 1] = morphAttr.array[v + 1];
                    data[stride + 2] = morphAttr.array[v + 2];

                    stride += 3;
                }

                vertexId++;
                //Also set vertIndex at v to v which is the vert index
                vertIndexs[vertexId] = vertexId;
            }

            // Remove existing morph target code related attributes
            skinnedMesh.geometry.morphTargetsRelative = false
            skinnedMesh.geometry.morphAttributes = null;

            // Add new vert index attribute
            skinnedMesh.geometry.addAttribute('vertIndex', new THREE.BufferAttribute(vertIndexs, 1));
            skinnedMesh.geometry.addAttribute('dataForMorphing', new THREE.BufferAttribute(data, 1));
            //CREATE DATA TEXTURE AND PLACE ON SHADER MAT
            let dataTexture = new THREE.DataTexture(data, textureSizeUsed, textureSizeUsed, THREE.RGBFormat, THREE.FloatType);
            dataTexture.needsUpdate = true;

            //Disable all morphTarget logic by setting appropriate flags
            skinnedMesh.material.morphTargets = false;
            skinnedMesh.material.morphNormals = false;

            const morphTargetDeclarations = `
            //Data texture
            precision highp sampler2D;
            precision highp float;
            uniform sampler2D texture0;
            uniform float textureSize;
            uniform int numberOfShapeKeys;
            uniform float morphTargetInfluences[2048];
            attribute float vertIndex;

            attribute float dataForMorphing;
            `;
            const morphTargetVertexShaderCode = `
            
            //Offset used for fixing the x y coordinates on the data texture
            precision highp float;
            float offset = vertIndex * float(numberOfShapeKeys);
            //Loop over every blendshape
            for(int i=0; i<numberOfShapeKeys; i++) {
                float iFloat = float(i);
                //If influence is 0, lets not waste GPU processing, move on
                if(morphTargetInfluences[i] == 0.00000000000000) {
                    continue;
                }
                //Find the x and y position of the vertex data based on vertex index and blendshape index
                float x = mod(offset + iFloat, textureSize);
                float y = floor((offset + iFloat) / textureSize);
                
                //Grab the data at x and y
                vec2 texCoord = vec2(x / textureSize,y / textureSize);
                vec4 data = texture2D(texture0, texCoord);
                
                //Modify the current vertex position with the data found in the texture and the current blendshape influence
                transformed.x += data.x * morphTargetInfluences[i];
                transformed.y += data.y * morphTargetInfluences[i];
                transformed.z += data.z * morphTargetInfluences[i];
            }
        `
            // Replace all existing morph target vertex shader code with our own
            skinnedMesh.material.onBeforeCompile = function (shader) {
                // Add new necessary uniforms
                shader.uniforms.texture0 = {
                    type: 't',
                    value: dataTexture
                };
                // Now when we change the morphTargetInfluences it's linked to show up in the 
                // vertex shader
                shader.uniforms.morphTargetInfluences = {
                    value: skinnedMesh.morphTargetInfluences
                };

                shader.uniforms.textureSize = {
                    value: textureSizeUsed
                }


                shader.uniforms.numberOfShapeKeys = {
                    value: lengthOfMorphAttributes
                }

                // Replace morphTarget code declarations with our own
                shader.vertexShader = shader.vertexShader.replace(
                    "#include <morphtarget_pars_vertex>",
                    morphTargetDeclarations
                );

                shader.vertexShader = shader.vertexShader.replace(
                    "#include <morphtarget_vertex>",
                    morphTargetVertexShaderCode
                );
            };


            skinnedMesh.material.needsUpdate = true;
            data = [];
            data = null;
        }
    }


});

```

**Comment by yaroslavnikiforov** [comment] 2021-07-31 12:24
Hi @ManishJu, which version of three did you test this code. I get such an error with 0.130.0:

<img width="768" alt="Screenshot 2021-07-31 at 15 04 59" src="https://user-images.githubusercontent.com/42115630/127739554-cb015463-7626-4dd6-af08-8fa5ac318b04.png">

And such error with 1.131.0:

<img width="772" alt="Screenshot 2021-07-31 at 15 11 56" src="https://user-images.githubusercontent.com/42115630/127739564-d92503c3-6787-43ca-ab08-a5cf3a5322a2.png">

How I use it:
```
...

function loadModelAsync() {
  return new Promise((resolve, reject) => {
    const loader = new GLTFLoader()

    loader.load(
      'assets/models/model.glb',
      gltf => {
        model = gltf.scene

        const mesh = model.getObjectByName('body')

        mesh.material.wireframe = true
        changeToTextureBasedMorphTargets(mesh)

        resolve(gltf)
      },
      null,
      error => reject(error)
    )
  })
}

... 

const model = await loadModelAsync()
scene.add(model)
```

**Comment by ManishJu** [comment] 2021-08-02 17:45
Sorry I tested with version 128 only, I will get back with 131 as soon as I can....

**Comment by tiivik** [comment] 2021-08-05 14:47
> A first step for implementing a built-in solution would be an animated glTF asset for testing. Can somebody recommend a model that we can safely use in the official examples? An animated face like above would be a nice showcase.

Hey @Mugen87, Rainer from @readyplayerme here. We're happy to contribute the asset!

Leaving one here, let me know if there's a better place to do that. It has 63 blend shapes:

[readyplayerme-avatar.zip](https://github.com/mrdoob/three.js/files/6939492/readyplayerme-avatar.zip)

![image](https://user-images.githubusercontent.com/14925757/128370215-494e2206-4f87-480c-af51-067fd32dc06d.png)


PS. any additional avatars could be exported via https://demo.readyplayer.me, they come with https://creativecommons.org/licenses/by-nc-sa/4.0/ license.

**Comment by srcnalt** [comment] 2021-08-06 09:21
I took @ManishJu's code and used it here to craft this example: https://codesandbox.io/s/blendshape-test-fhf8m
The example iterates over blendshapes and sets the values to 1. You can go over `<Avatar use={true} />` component and set use value to `false` to see how it would work without it (it'll get stuck without it after several blend shapes) 

For me it works fine on Chrome, Firefox and Opera however on Brave browser I see vertex artefacts.

![image](https://user-images.githubusercontent.com/3163281/128488095-f78b24b3-0352-4fe3-837a-d2b4fb42e3fb.png)

@tiivik also told me on a MacOS device he is getting the `too many uniforms` issue.
![image](https://user-images.githubusercontent.com/3163281/128488591-cc950718-d222-4201-a91b-8601d4f89b68.png)

**Comment by Mugen87** [comment] 2021-08-06 12:16
@tiivik Thanks for sharing! I've just checked out the asset and realized there are a bunch of animation clips. Does one of these clips also use the morph targets for a facial animation? 

I was hoping for something like that since the Miku asset in https://threejs.org/examples/webgl_loader_mmd_pose already provides a set of ca. 30 morph targets. However it is not animated and I was hoping for an asset that performs an animation with more than 8 morph targets.

**Comment by srcnalt** [comment] 2021-08-06 12:53
Updated the example to play a short recording.

https://user-images.githubusercontent.com/3163281/128512129-5561357d-6cc7-4f8a-858d-d5239d660ee9.mp4

Hi @Mugen87 yes seems like the model is coming with animations for VR hand gestures and eyes.

![image](https://user-images.githubusercontent.com/3163281/128513138-a9af9e32-37bb-4ac9-9b89-08fefef1e766.png)

**Closed** 2021-09-07 13:57 UTC
Labels: Enhancement

**Comment by TomDadongHu** [comment] 2021-09-18 20:52
> > A first step for implementing a built-in solution would be an animated glTF asset for testing. Can somebody recommend a model that we can safely use in the official examples? An animated face like above would be a nice showcase.
> 
> Hey @Mugen87, Rainer from @readyplayerme here. We're happy to contribute the asset!
> 
> Leaving one here, let me know if there's a better place to do that. It has 63 blend shapes:
> 
> [readyplayerme-avatar.zip](https://github.com/mrdoob/three.js/files/6939492/readyplayerme-avatar.zip)
> 
> ![image](https://user-images.githubusercontent.com/14925757/128370215-494e2206-4f87-480c-af51-067fd32dc06d.png)
> 
> PS. any additional avatars could be exported via https://demo.readyplayer.me, they come with https://creativecommons.org/licenses/by-nc-sa/4.0/ license.

how you made this?  is here a live demo? thanks
