### ISSUE TITLE
isDirty/Culled/didRender flag

### ISSUE THREAD

**Issue by drcmda** [mrdoob/three.js#20432] opened 2020-09-29 11:42 UTC
The WebGLRenderer checks if an object intersects the cameras frustrum before it is allowed to render: https://github.com/mrdoob/three.js/blob/dev/src/renderers/WebGLRenderer.js#L1170-L1205

Could we have a simple flag on the object which tells us if was considered for rendering or not?

```jsx
if (!object.frustumCulled || _frustum.intersectsObject(object)) {
  // ...
  object.didRender = true
} else {
  object.didRender = false
}
```

This would allow us to quickly build virtualised primitives without the expense of running that check twice. For instance flexbox: https://github.com/pmndrs/react-three-flex We're running into problems with lots and lots of elements because calculating layout is expensive. But we could then just bail out on objects that aren't even shown, thereby virtualising it.

**Comment by Mugen87** [comment] 2020-09-29 11:48
Duplicate of #17271.

**Closed** 2020-09-30 09:28 UTC
Labels: Duplicate
