### ISSUE TITLE
FBXLoader: Colors are loaded as Gray instead of the actual color

### ISSUE THREAD

**Issue by MarcRibguth** [mrdoob/three.js#12649] opened 2017-11-14 15:31 UTC
Hey, 
the colors on the object i was working with are not loading. The colors were added by blender and the blades and body of this object, are red and orange. They are loaded as grey.

[Fan.zip](https://github.com/mrdoob/three.js/files/1471395/Fan.zip)

Thanks for all the work you guys put in to this project!

- [x] Dev
- [ ] r88
- [ ] ...

##### Browser

- [x] probably all of them
- [x] tested with Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by mrdoob** [comment] 2017-11-15 00:03
https://github.com/mrdoob/three.js/pull/12648

**Comment by mrdoob** [comment] 2017-11-15 00:04
https://github.com/mrdoob/three.js/pull/12648

**Comment by looeee** [comment] 2017-11-15 02:55
@mrdoob I don't think #12067 is related. The problem is with the `fan_with color.fbx` file, which has no textures but the meshes are colored somehow. 

I've done some testing but can't see where the colors are specified (it doesn't seem to be in either the geometry or materials which would be the normal places. So perhaps this is an issue with the binary parser. 

@MarcRibguth would you be able to export `fan_with color.fbx` in ASCII format? 
Also, can you include the textures used by the  `Fan_brocken_textures.fbx` file? I can't test it without them.

**Comment by MarcRibguth** [comment] 2017-11-15 09:43
Here is the ASCII format:
[Fan_ascii.zip](https://github.com/mrdoob/three.js/files/1474096/Fan_ascii.zip)

**Comment by looeee** [comment] 2017-11-15 11:42
@MarcRibguth thanks - that's in an old version of the format though - version 6100. Only version 7000 and up is supported by the FBXLoader. Are you using the latest version of the blender exporter?

**Comment by MarcRibguth** [comment] 2017-11-15 12:27
Sorry, I'm not really familiar with 3D stuff. A coworker of mine did the export for me and just now, i tried the export with Blender v2.79 and got the same fbx version(6100).
The object was just from a lookup from the internet, to see if the animations are working with the loader (i don't think they do).

**Comment by looeee** [comment] 2017-11-15 12:36
Hmm, looks like the blender ASCII exporter hasn't been updated in a few years. I guess they decided to focus on the binary exporter instead. 

BTW if you want animations to work with the loader, make sure to bake animations when exporting - I'm not familiar with the blender exporter but there should be some setting there that allows this.

**Comment by MarcRibguth** [comment] 2017-11-15 13:03
Thanks for the advice, i will test it.

**Comment by pikilipita** [comment] 2017-12-12 19:49
It seems blender does not save colors the same way as other 3D softwares, at least not like Cheetah 3D.
I made a simple test: a scene with colored cubes in blender. 

test A: exporting as fbx 7.4 from blender and loading in the threejs : colors are lost.

test B: exporting as fbx 7.4 from blender, importing this fbx into cheetah, then exporting the scene from cheetah as fbx and loading it in threejs: colors are correct.

So colors are saved in fbx files from blender.
in blender ascii 6.4 exporter, it seems is was saved maybe as 'DiffuseColor', maybe stil the same in binary 7.4 ...

**Comment by mrdoob** [comment] 2017-12-12 19:50
@pikilipita could you share the test files?

**Comment by pikilipita** [comment] 2017-12-12 19:54
[test fbx materials colors.zip](https://github.com/mrdoob/three.js/files/1553073/test.fbx.materials.colors.zip)
sure

**Comment by pikilipita** [comment] 2017-12-12 20:10
Off topic, but thanks @looeee for the animation bake advice, it made my day brighter :)

**Comment by looeee** [comment] 2017-12-13 04:51
@pikilipita that advice is actually out of date since #12758 was merged - unbaked animations should be supported now!

**Comment by looeee** [comment] 2018-03-07 10:11
Fixed in #13515

**Closed** 2018-03-07 21:27 UTC
Labels: Duplicate, Loaders
