### ISSUE TITLE
UniformsUtils clones texture parameters

### ISSUE THREAD

**Issue by TheManWhoWas** [mrdoob/three.js#7223] opened 2015-09-23 14:29 UTC
We're using a custom ShaderMaterial that we clone for each mesh so they can have unique uniforms.

But it turns out that internally UniformsUtils.clone() is called which clones the texture parameter. This means each one counts as unique and gets uploaded to the GPU separately. Not good!

So unless we're going about this the wrong way, it would seem better if texture parameters were copied by reference rather than cloned as hard to see anyone wanting to duplicate the textures like this.

**Comment by mrdoob** [comment] 2015-09-23 21:47
This will also be solved when `THREE.Image` gets implemented.

**Comment by TheManWhoWas** [comment] 2015-09-24 10:21
Just removing the "instanceof THREE.Texture" (line 45 of UniformsUtils) from the if statement fixes the problem too.

**Comment by jsantell** [comment] 2018-12-07 18:35
Dupe of https://github.com/mrdoob/three.js/issues/3283?

**Comment by Mugen87** [comment] 2020-02-26 16:38
Closing in favor of #5821.

**Closed by Mugen87** 2020-02-26 16:38 UTC
Labels: Feature Request
