### ISSUE TITLE
Can't load #standard_surface_brick_procedural.mtlx sample file

### ISSUE THREAD

**Issue by Me-Priyank** [mrdoob/three.js#28989] opened 2024-07-26 15:45 UTC
### Reproduction steps

Go to https://academysoftwarefoundation.github.io/MaterialX/
In the top left dropdown, select "standard_surface_brick_procedural.mtlx"
Play with the parameters on the right side
Download the files ([standard_surface_brick_procedural.zip](https://github.com/user-attachments/files/16391842/standard_surface_brick_procedural.zip))
Load with MaterialXLoader
Note the exception.

### Code

```js

    const mtlxLoader = new MaterialXLoader();
    const path = "https://raw.githubusercontent.com/AcademySoftwareFoundation/MaterialX/main/resources/Materials/Examples/StandardSurface/";
    const file = "standard_surface_brick_procedural.mtlx";
    mtlxLoader
          .setPath( path )
	  .loadAsync( file )
          .then( ({ materials}) => { 
          	console.log("Loaded materials", materials);
                 const firstMaterial = Object.values( materials )[0];
                 mesh.material = firstMaterial;

                 // should be able to adjust procedural parameters here
          });

```

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/g3atw6k5/)
* [jsfiddle-dev](https://jsfiddle.net/hjqw94c5/)

### Version

r167

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by Mugen87** [comment] 2024-07-26 15:56
Duplicate of #28988.

**Closed by Mugen87** 2024-07-26 15:56 UTC
