### ISSUE TITLE
uniformArray on wgslFn receives array<vec4<T>, L> instead of array<T, L>.

### ISSUE THREAD

**Issue by blessedbythestorm** [mrdoob/three.js#29720] opened 2024-10-22 00:33 UTC
### Description

Passing an array uniform to wgslFn results in it receiving array<vec4<T>> instead.

### Reproduction steps

1. Try out the provided shader.

### Code

```typescript
		let mat = new MeshBasicNodeMaterial({
			transparent: true,
			depthWrite: false,
			blending: AdditiveBlending
		});
		
		const shader_params = {
			uv: uv(),
			diffuse_texture: texture(diffuse_texture),
			diffuse_sampler: texture(diffuse_texture),
			error_cells: uniformArray(new Array(data.gridWidth * data.gridHeight).fill(-1), 'int'),
		}

		const fragment_shader = wgslFn(`
		    fn main_fragment(
		      uv: vec2<f32>,
		      diffuse_texture: texture_2d<f32>,
		      diffuse_sampler: sampler,
		      error_cells: array<i32, ${data.gridWidth * data.gridHeight}>
		    ) -> vec4<f32> {    
		        var color = textureSample(diffuse_texture, diffuse_sampler, uv);
		        
				let cellX = i32(floor(uv.x * f32(${data.gridWidth})));
			    let cellY = i32(floor(uv.y * f32(${data.gridHeight})));
			    let cellIndex = cellY * ${data.gridWidth} + cellX;
                
			    var isOk = false;
			    for (var i = 0; i < ${data.gridWidth * data.gridHeight}; i = i + 1) {
			        if (error_cells[i] == cellIndex) {
			            isOk = true;
			            break;
			        }
			    }

		        if (isOk) {
			        color = mix(color, vec4<f32>(0.0, 1.0, 0.0, 0.5), 0.2);
			    } else {
			        color = mix(color, vec4<f32>(1.0, 0.0, 0.0, 0.5), 0.2);
			    }
		        
		        return color;    
		    }
	    `);
	    
	    mat.colorNode = fragment_shader(shader_params);
```

### Screenshots

![image](https://github.com/user-attachments/assets/576b995c-bf96-49e3-98c1-21a871540785)

### Version

r169

### Device

Desktop

### OS

Windows

**Comment by Spiri0** [comment] 2024-10-22 12:57
Since vec4 is exactly right for me, I didn't stumble across it. I suspect the cause of your error message is that vec4 is hardcoded as format in src/nodes/accessors/UniformArrayNode.js.

**Comment by sunag** [comment] 2024-10-22 14:10
Maybe it can be resolved with a `buffer` instead of `uniformArray`.

**Comment by blessedbythestorm** [comment] 2024-10-22 14:20
Ah thanks for the suggestion and sorry if I've made a mistake myself. 

Wondering, what is the proper way currently to pass an array of i32 to wgslFn, a buffer then? 
I saw other examples that suggested using uniformArray for tsl shaders and I thought that would be the correct way?

**Comment by sunag** [comment] 2024-10-22 15:58
I fixed a type conversion here https://github.com/mrdoob/three.js/pull/29724

Try with `array<vec4<i32>, ${ count }>` , WebGPU/WGSL has stride align limitation, so don't be too intuitive without vectors or structures.

```js
const fragment_shader = wgslFn( `
	fn main_fragment(
		cells: array<vec4<i32>,3>
	) -> vec4<f32> {    

		let value = cells[ 0 ].x;

		return vec4f( f32( value ) );    

	}
` );

materialBox.colorNode = fragment_shader( {
	cells: uniformArray( [ 1, 2, 3 ], 'int' )
} );
```

**Comment by blessedbythestorm** [comment] 2024-10-22 16:22
Thank you, this solution works. So I guess the vec4 is due to alignment constraints then, good to know that.

**Closed** 2024-10-22 17:02 UTC
