### ISSUE TITLE
CSS3DRenderer Sprite not rendering properly on Safari

### ISSUE THREAD

**Issue by jhelf** [mrdoob/three.js#7802] opened 2015-12-16 12:49 UTC
You can see the issue If you look at the css renderer "sprite" exemple on safari  : http://threejs.org/examples/#css3d_sprites

It works on other browsers.

**Comment by mrdoob** [comment] 2015-12-16 18:17
Could you post a screenshot?

**Comment by WestLangley** [comment] 2015-12-16 20:40
@mrdoob For me, it renders a single sprite in the upper-left corner.

**Comment by leitzler** [comment] 2015-12-16 21:50
Upper left corner until dragged, then correct (iOS 9.2 Safari)

**Comment by mrdoob** [comment] 2015-12-17 02:02
I can replicate. Once the camera moves everything renders as it should.

**Comment by jhelf** [comment] 2015-12-17 14:56
Ye that's the issue I get, only one sprite showing on the upper left corner. This is causing some issues on a project I'm working on where I don't move the camera and therefore the sprites are not rendered properly. For now I reverted back to an older version of the renderer which fixed the problem for now.

Let me know if you find a solution for it. No sure why Safari would act differently than Chrome.

Thanks!
Jean

**Comment by speigg** [comment] 2016-01-28 05:31
The problem is caused by this commit https://github.com/mrdoob/three.js/commit/8ed08e983fcc78a50b8ac4ee917a23754cc6fd55

**Comment by Mugen87** [comment] 2016-02-01 10:02
@speigg You're right. Replacing the following line in `THREE.CSS3DRenderer` fixes the bug. At least on my iMac.
```javascript
var epsilon = function ( value ) {

    //return Math.abs( value ) < Number.EPSILON ? 0 : value;
    return Math.abs( value ) < 0.000001 ? 0 : value;

};
```

**Comment by speigg** [comment] 2016-02-01 14:13
When the value is very close to zero, Safari will output numbers in scientific notation, i.e. 1.6×10−10 becomes 1.6e-10. This notation is not parsed correctly by the css transform matrix3d function.

**Comment by speigg** [comment] 2016-02-01 14:18
I suppose this could also cause problems with large numbers. A proper solution would somehow ensure somehow that scientific notation is never used for numbers in the matrix3d function.

**Comment by Mugen87** [comment] 2016-02-01 16:17
>But in safari, the scientific notation is not parsed correctly by the css transform matrix3d function.

@speigg So you estimate this as a faulty behavior of the browser? If so, i think we should submit a bug at Apple (http://www.apple.com/feedback/safari.html). It's definitely bad, when browser implementations vary in this area.

**Comment by mrdoob** [comment] 2016-02-07 10:06
Sounds like a Safari bug indeed!

**Comment by Mugen87** [comment] 2016-02-14 20:46
I've reported a bug. Let's see what will happen....

**Comment by matthewspencer** [comment] 2016-04-13 23:39
Ran into this issue as well—it became much more pronounced after the Safari 9.1 update. The temporary workaround I implemented staggers adding the CSS3DSprites to the scene. It doesn’t fix, but it helps!

**Comment by speigg** [comment] 2016-04-14 15:20
The fix is to change the epsilon function in CSS3DRenderer as described above

**Comment by matthewspencer** [comment] 2016-04-14 16:14
I experienced issues even after changing `Number.EPSILON` to `0.000001`

**Comment by Mugen87** [comment] 2016-04-14 19:35
Unfortunately, i've got no response on my bug report so far (used [Apple Bug Reporter](https://bugreport.apple.com/logon)). The answer of Apple/Safari Team is still something i'm very interested in. Honestly, i prefer a bugfix for Safari rather than changing `CSS3DRenderer`. All browsers should identically process the css transform matrix3d function.

**Comment by litherum** [comment] 2016-05-11 04:51
Attaching a reduction test case of the WebKit bug.
[Reduction.html.zip](https://github.com/mrdoob/three.js/files/258586/Reduction.html.zip)

**Comment by litherum** [comment] 2016-05-11 04:55
I found this WebKit bug: https://bugs.webkit.org/show_bug.cgi?id=154506

**Comment by kenchikuka** [comment] 2016-09-03 19:34
@Mugen87 I agree with your point about parity but in the absence of a fix from Apple I have had to modify a project copy of the renderer as per #8839 using :

`var epsilon = function ( value ) {`
``
   return Math.abs( value ) < Number.EPSILON ? 0 : Number( value.toFixed(6) );
``
`};`

which enables compatibility for my project.
I have applied this fix to the CSS3DStereoRenderer also and would like to ask why this was renderer was removed from Three? 
Moving forward could there be an option to incorporate it in the CSS3DRenderer as an option ?

**Comment by Mugen87** [comment] 2016-09-04 09:30
> I have applied this fix to the CSS3DStereoRenderer also and would like to ask why this was removed from Three?

Sry, i don't know that. I'm just annoyed that this problem is still not fixed in webkit: [Bug 127720 - CSS 2.2: Support scientific notations for all numbers in CSS](https://bugs.webkit.org/show_bug.cgi?id=127720)

**Comment by mrdoob** [comment] 2016-11-16 00:58
> This is now fixed. However, it's just waiting on the new CSS parser to be enabled by default. This should happen in the coming days or week.

🎉

**Comment by Mugen87** [comment] 2016-12-09 17:22
I can confirm that the bug is fixed with the latest version of WebKit Nightly (r209601). The mentioned [CSS3D example](https://threejs.org/examples/css3d_sprites.html) works perfectly in Safari now :raised_hands:

**Closed** 2016-12-09 17:29 UTC
