### ISSUE TITLE
Documentation contains fake hyperlinks which are bad for usability (can't be opened in new tabs)

### ISSUE THREAD

**Issue by diamondavocado** [mrdoob/three.js#19798] opened 2020-07-05 20:11 UTC
three.js's documentation contains a bunch of fake hyperlinks; anchor tags which do not have an `href` attribute but instead rely on JavaScript `onclick` events to navigate.

These links can't be opened in new tabs by middle-clicking or by right-clicking. The links also don't show a URL preview in the status bar when the user hovers over them.

This is terrible for usability and should be universally discouraged across the web.

Example:

1. Open https://threejs.org/docs/index.html#api/en/animation/AnimationAction
2. Try to middle-click the blue *AnimationClips* text which appears to be a hyperlink.
3. Try to right-click the same text and open the link in a new tab or new window.
4. You can't.

The links should have a proper `href` attribute added to them.

**Comment by DefinitelyMaybe** [comment] 2020-07-05 20:33
was it just this one or were there some others that you've found as well?

**Comment by will-ca** [comment] 2020-07-06 06:07
@DefinitelyMaybe The vast majority of the links are fake I think. The only ones that seem to be real are what I assume to be hard-coded links with specific, explicit (usually external) URLs. Everything that's auto-generated and everything that points to an internal page or anchor— E.G. every class, function, module, and method, as well as most manually inserted links that that point to a class, function, module, or method— is fake.

As an aside, the reliance on the URL's anchor fragment to differentiate pages is also terrible for usability because it bypasses browsers' history and page navigation. Chrome thinks that `https://threejs.org/docs/#examples/en/loaders/GLTFLoader` is the same page as `https://threejs.org/docs/#examples/en/controls/OrbitControls`, for example— In fact, it thinks that every single page in the docs is the same page, because the significant part of the URL actually *is* (incorrectly) the same— and it will offer to take you to an existing tab (for a completely different definition) instead of opening a new page when you type the name of a definition from your browsing history into its address bar.

**Comment by Mugen87** [comment] 2020-07-06 08:39
Duplicate of #13900.

**Closed by Mugen87** 2020-07-06 08:39 UTC
