### ISSUE TITLE
OutputPass inpostprocessing. render error

### ISSUE THREAD

**Issue by zhaocaho** [mrdoob/three.js#28981] opened 2024-07-26 10:09 UTC
### Description

Added a MeshPhysicalMaterial cube, set transparent=true,opacity=0.3.

### Reproduction steps

1.render error

### Code

```js
<script type="module">
			import * as THREE from 'three';

			import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
			import { RGBELoader } from 'three/addons/loaders/RGBELoader.js';
			import { EffectComposer } from 'three/addons/postprocessing/EffectComposer.js';
			import { RenderPass } from 'three/addons/postprocessing/RenderPass.js';
			import { OutputPass } from 'three/addons/postprocessing/OutputPass.js';
			import { GUI } from 'three/addons/libs/lil-gui.module.min.js';

			const params = {
				add_RenderPass_OutputPass: true
			};


			let gui;
			let camera, scene, renderer;
			let composer;

			init();

			function init() {

				const container = document.createElement( 'div' );
				document.body.appendChild( container );

				camera = new THREE.PerspectiveCamera( 45, window.innerWidth / window.innerHeight, 0.25, 20 );
				camera.position.set( - 1.8, 0.6, 2.7 );

				scene = new THREE.Scene();

				new RGBELoader()
					.setPath( 'textures/equirectangular/' )
					.load( 'royal_esplanade_1k.hdr', function ( texture ) {

						texture.mapping = THREE.EquirectangularReflectionMapping;

						scene.background = texture;
			
		} );
				const ambientLight = new THREE.AmbientLight( 0xffffff, 1 );
				scene.add( ambientLight );
			
				const geometry = new THREE.BoxGeometry( 1, 1, 1 );
  				const material = new THREE.MeshPhysicalMaterial( { color: 0x00ff00, transparent: true, opacity: 0.3 } );
  				const cube = new THREE.Mesh( geometry, material );
				scene.add( cube );
			
				renderer = new THREE.WebGLRenderer();
				renderer.setPixelRatio( window.devicePixelRatio );
				renderer.setSize( window.innerWidth, window.innerHeight );
				renderer.setAnimationLoop( animate );

				container.appendChild( renderer.domElement );
			
				composer = new EffectComposer( renderer );
				composer.setPixelRatio( window.devicePixelRatio );
				composer.setSize( window.innerWidth, window.innerHeight );
				composer.addPass( new RenderPass( scene, camera ) );
				composer.addPass( new OutputPass() );


				const controls = new OrbitControls( camera, renderer.domElement );
				controls.minDistance = 2;
				controls.maxDistance = 10;
				controls.target.set( 0, 0, - 0.2 );
				controls.update();

				gui = new GUI();
				gui.width = 350;
				gui.add( params, 'add_RenderPass_OutputPass' );

				window.addEventListener( 'resize', onWindowResize );

			}

			function onWindowResize() {

				camera.aspect = window.innerWidth / window.innerHeight;
				camera.updateProjectionMatrix();

				renderer.setSize( window.innerWidth, window.innerHeight );
				composer.setSize( window.innerWidth, window.innerHeight );

			}

			//

			function animate() {

				if ( params.add_RenderPass_OutputPass ) {

					 composer.render();
			
				} else {

					renderer.render( scene, camera );
			
				}

			}

		</script>

```

### Screenshots

<img width="522" alt="44" src="https://github.com/user-attachments/assets/25ed4eef-0520-4705-b551-098117f4df81">
<img width="535" alt="33" src="https://github.com/user-attachments/assets/df906021-1cf2-4135-887e-0b00f6b52413">

### Version

r166

**Comment by Mugen87** [comment] 2024-07-26 10:17
Duplicate of #27184.

**Closed by Mugen87** 2024-07-26 10:17 UTC
