### ISSUE TITLE
Instanced mesh from gltf file dosen't transform correctly

### ISSUE THREAD

**Issue by Suprhimp** [mrdoob/three.js#24968] opened 2022-11-16 09:16 UTC
**Instanced mesh from gltf file dosen't transform correctly**

I thought that this bug is from three-gltf-transform, which is very useful to load instanced mesh. But when I look directly with console, **the matrix of the instanced mesh was correct.**

Let me show my files and symptom with screenshot.

This is my test file to check the EXT mesh loader.
As you can see the instanced monkey are look backward and positioned slightly left.
![image](https://user-images.githubusercontent.com/73486185/202138711-b5fa6927-610f-4a9d-abe0-3f5b036d4fd2.png)

but when I load with my own loader and three js editor, I think the parent geometry trasnform are not correct.
![image](https://user-images.githubusercontent.com/73486185/202138753-f9ed54bf-f2c0-4304-907f-96ae42de84d9.png)

I console logged the instansed mesh. But I think the matrix(position,scale,rotation) are correct but not adjusted in scene.
![image](https://user-images.githubusercontent.com/73486185/202138880-14f9d616-fbc9-46cf-b300-83941bc8e903.png)

Plus you can see the yello box helper goes correctly though instanced mesh is not.
![image](https://user-images.githubusercontent.com/73486185/202139302-b5e14c28-7005-4b56-8f40-b09b8ae9fc01.png)

**Comment by Mugen87** [comment] 2022-11-16 09:25
Do you mind sharing your glTF asset? BTW: What is `three-gltf-transform`? Is it a npm package?

**Comment by Mugen87** [comment] 2022-11-16 09:47
I've checked the model with `three.js`, [BabylonJS](https://sandbox.babylonjs.com/)  and Sketchfab. The latter one does not seem to support `EXT_mesh_gpu_instancing`. However `three.js` and `BabylonJS` render it identically. Meaning the monkeys are oriented in the same direction.

/ping @takahirox

**Comment by takahirox** [comment] 2022-11-16 18:18
Do you use [glTF-Blender-IO-EXT-mesh-gpu-instancing](https://github.com/takahirox/glTF-Blender-IO-EXT-mesh-gpu-instancing) to export glTF with `EXT_mesh_gpu_instancing`? If so I speculate this known issue may be the cause https://github.com/takahirox/glTF-Blender-IO-EXT-mesh-gpu-instancing/issues/6 Perhaps a problem is not in Three.js but in the addon.

**Comment by Suprhimp** [comment] 2022-11-16 23:10
Yep I use that blender addon.

I thought that this problem is about the addon or the three-gltf-extension
at first. But since when I check the transform in matrix by console and
gltf file has the correct transform coordinate , i thought it would be the
three js side bug.

If you want gltf file not glb I can upload it!

2022년 11월 17일 (목) 오전 3:18, Takahiro ***@***.***>님이 작성:

**Comment by WestLangley** [comment] 2022-11-17 01:44
`mesh.matrix` is approximately equivalent to a 180 degree rotation around the y-axis.

However, `mesh.matrix` and `mesh.instancedMatrix[ 0 ]` are identical.

So each instance is rotated twice by the same matrix.

three.js appears to be rendering the glTF file correctly.

**Comment by Suprhimp** [comment] 2022-11-17 02:20
Then for the correct position and rotation, the `mesh.matrix` and `mesh.instanceMatrix` have to be different right?

**Comment by takahirox** [comment] 2022-11-25 04:48
As I thought the problem was in the addon and it has been fixed. Closing.

**Closed by takahirox** 2022-11-25 04:48 UTC
Labels: Needs Investigation
