### ISSUE TITLE
BufferGeometry requires a 'position' attribute to render

### ISSUE THREAD

**Issue by imv-uw** [mrdoob/three.js#22243] opened 2021-08-02 12:30 UTC
With r111, WebGlRenderer begins checking for a position buffer attribute and uses its count in deciding whether to invoke the program. This introduced an arbitrary new requirement that BufferGeometry have a 'position' attribute. I suggest that the old behavior be followed, in which BufferGeometry.setDrawRange() is respected.

[WebGLRenderer.js](https://github.com/mrdoob/three.js/blob/r111/src/renderers/WebGLRenderer.js):

```
var position = geometry.attributes.position;
if ( index !== null && index.count === 0 ) return;
if ( position === undefined || position.count === 0 ) return;
```

**Comment by Mugen87** [comment] 2021-08-02 12:54
Duplicate of #19430.

**Closed by Mugen87** 2021-08-02 12:54 UTC
