### ISSUE TITLE
Impossible to read multiple render targets pixels ( fix )

### ISSUE THREAD

**Issue by Chrisyss** [mrdoob/three.js#23864] opened 2022-04-07 10:54 UTC
as stated in the Title.

I saw many people need it btw :)
This fixes it: 

Outside of core:
```

readMultipleRenderTargetPixels = function (renderTarget,tex, x, y, width, height, buffer, index) {
		

    let framebuffer = renderer.properties.get(renderTarget).__webglFramebuffer;
    gl = renderer.getContext();
  
    let currentRenderTarget = renderer.getRenderTarget();
    if (framebuffer) {
      renderer.state.bindFramebuffer(gl.FRAMEBUFFER, framebuffer);
      var attachement = [gl.COLOR_ATTACHMENT0,gl.COLOR_ATTACHMENT1,gl.COLOR_ATTACHMENT2,gl.COLOR_ATTACHMENT3];
      gl.readBuffer(attachement[index]);

      try {
        const texture =tex;
        const textureFormat = texture.format;
        const textureType = texture.type;

        if (x >= 0 && x <= renderTarget.width - width && y >= 0 && y <= renderTarget.height - height) {
          gl.readPixels(x, y, width, height, gl.RGBA, gl.FLOAT, buffer);
          // gl.readPixels(x, y, width, height, utils.convert(textureFormat), utils.convert(textureType), buffer);
        }
      } finally {
        // restore framebuffer of current render target if necessary
        const framebuffer = currentRenderTarget !== null ? renderer.properties.get(currentRenderTarget).__webglFramebuffer : null;
        renderer.state.bindFramebuffer(gl.FRAMEBUFFER, framebuffer);
      }
    }
  };
```
  
  Inside of Core:
  
 ```
 
  		this.readMultipleRenderTargetPixels = function (renderTarget,tex, x, y, width, height, buffer, index) {
		

			let framebuffer = properties.get(renderTarget).__webglFramebuffer;

		

			if (framebuffer) {
				state.bindFramebuffer(_gl.FRAMEBUFFER, framebuffer);
				var attachement = [_gl.COLOR_ATTACHMENT0,_gl.COLOR_ATTACHMENT1,_gl.COLOR_ATTACHMENT2,_gl.COLOR_ATTACHMENT3];
				_gl.readBuffer(attachement[index]);

				try {
					const texture =tex;
					const textureFormat = texture.format;
					const textureType = texture.type;

					if (x >= 0 && x <= renderTarget.width - width && y >= 0 && y <= renderTarget.height - height) {
						_gl.readPixels(x, y, width, height, _gl.RGBA, _gl.FLOAT, buffer);
						// _gl.readPixels(x, y, width, height, utils.convert(textureFormat), utils.convert(textureType), buffer);
					}
				} finally {
					// restore framebuffer of current render target if necessary
					const framebuffer = _currentRenderTarget !== null ? properties.get(_currentRenderTarget).__webglFramebuffer : null;
					state.bindFramebuffer(_gl.FRAMEBUFFER, framebuffer);
				}
			}
		};
```

**Comment by Mugen87** [comment] 2022-04-07 11:41
Marking this issue as a duplicate of #22403.

The current implementation of MRT will probably be refactored, see https://github.com/mrdoob/three.js/pull/23444#issuecomment-1034958524. Until it's decided what happens with `WebGLMultipleRenderTargets`, I suggest to wait with adding such a method to the core.

**Closed by Mugen87** 2022-04-07 11:41 UTC
