### ISSUE TITLE
THREE.BufferGeometryUtils.mergeBufferGeometries 

### ISSUE THREAD

**Issue by xjindf** [mrdoob/three.js#14324] opened 2018-06-19 07:31 UTC
I tried to merge a lot of cylinders, but the result was not expected. I didn't know where the problem came out. Maybe it was a bug, but when I lowered the number of creation to 600 times code, who could help me, thank you very much!
```js
var geos = [];
for (var i = 0; i < 1000; i++) {
    var geo = new THREE.CylinderBufferGeometry(1, 1, 20, 16);
    var pos = new THREE.Vector3();
    pos.x = Math.random() * 800 - 400;
    pos.z = Math.random() * 800 - 400;
    geo.translate(pos.x, pos.y, pos.z);
    geos.push(geo);
}
var bf_geo = THREE.BufferGeometryUtils.mergeBufferGeometries(geos);
var mergeMesh = new THREE.Mesh(bf_geo, new THREE.MeshLambertMaterial({ color: 0xff0000 }));
scene.add(mergeMesh);
```

**Comment by Mugen87** [comment] 2018-06-19 10:44
Um, there seems to a problem with the index of the geometry. If I lower the amount of geometries (e.g. 500), the result looks good. If I increase the amount to 700, lines appear between the single cylinders. 

@xjindf Is that what you mean with "unexpected result"?

The problem does not occur if the `CylinderBufferGeometry` is turned into a non-indexed geometry via `geo = geo.toNonIndexed();`.

Demo: https://jsfiddle.net/f2Lommf5/7371/

**Comment by takahirox** [comment] 2018-06-19 11:12
I haven't looked into the detail yet but my quick guess. Because of TypedArray? `mergeBufferAttributes`  reuses the existing type. If merged attribute needs bigger type, the data will be broken.

**Comment by xjindf** [comment] 2018-06-19 11:42
@Mugen87 Yes, as you have described, using geo.toNonIndexed() seems to solve it, but can there be a better way, as xjindf said, thanks

**Comment by takahirox** [comment] 2018-06-19 11:52
Just in case, "An easy fix" I've mentioned meant an easy fix in `BufferGeometryUtils`, not in user code.

**Comment by Mugen87** [comment] 2018-06-19 13:59
@takahirox Yes, that seems to be the root cause. Using `setIndex()` ensures that `Uint32BufferAttribute` is used if necessary.

**Comment by WestLangley** [comment] 2018-06-19 15:58
/ping @donmccurdy 

BTW, after [this commit](https://github.com/mrdoob/three.js/commit/eecc8f7c5c13c11fd07147faaaac868804400b3f), I would have expected to find `BufferGeometryUtils.js` in the `js/utils` directory.

**Comment by takahirox** [comment] 2018-06-19 16:03
I don't know the historical reasons, but yeah it seems that `BufferGeometryUtils.js` should be under `js/utils` like `GeometryUtils.js` and `SceneUtils.js` from its name.

**Comment by donmccurdy** [comment] 2018-06-19 16:09
+1 for moving to `js/utils`, the docs already claim it's there. Not sure what I think about changing the type of the index yet but open to reviewing a PR if it's a simple change.

**Comment by Mugen87** [comment] 2018-06-19 16:36
How about the following approach: https://jsfiddle.net/f2Lommf5/7385/
```js
if ( isIndexed ) {

	var indexOffset = 0;
	var mergedIndex = [];

	for ( var i = 0; i < geometries.length; ++ i ) {

		var index = geometries[ i ].index;

		if ( indexOffset > 0 ) {

			for ( var j = 0; j < index.count; ++ j ) {

				mergedIndex.push( index.getX( j ) + indexOffset );

			}

		}

		indexOffset += geometries[ i ].attributes.position.count;

	}

	if ( ! mergedIndex ) return null;

	mergedGeometry.setIndex( mergedIndex );

}
```

**Comment by takahirox** [comment] 2018-06-19 16:46
I think you can remove

    	if ( ! mergedIndex ) return null;

**Comment by takahirox** [comment] 2018-06-19 16:48
if ( isIndexed ) {

	var indexOffset = 0;
	var mergedIndex = [];

	for ( var i = 0; i < geometries.length; ++ i ) {

		var index = geometries[ i ].index;

		for ( var j = 0; j < index.count; ++ j ) {

			mergedIndex.push( index.getX( j ) + indexOffset );

		}

		indexOffset += geometries[ i ].attributes.position.count;

	}

	mergedGeometry.setIndex( mergedIndex );

}

**Comment by Mugen87** [comment] 2018-06-19 17:00
Yeah, looks good. I'll make a PR when your #14329 is merged.

**Closed** 2018-06-21 00:06 UTC
Labels: Bug

**Comment by ndhabrde11** [comment] 2019-04-26 11:21
I am experiencing the same issue with a model. Other part is confidential so I am only able to paste a small part of the model where the issue is, here is a screenshot:
![image](https://user-images.githubusercontent.com/24761808/56804364-1a9b6580-6843-11e9-9d23-9334471a8be5.png)

I have loaded the json file of the model, converted all its geometries to buffergeometries, merged vertices, created a list and then used BufferGeometryUtils to merge these geometries. 
Following is the index of the final geometry:
![image](https://user-images.githubusercontent.com/24761808/56804443-66e6a580-6843-11e9-92e9-84197c04830f.png)

**Comment by WestLangley** [comment] 2019-04-26 11:28
@ndhabrde11 Please see if you can produce a _simple_, live example that duplicates the issue.

**Comment by ndhabrde11** [comment] 2019-04-29 05:56
You can mark this as closed. The geoemtry is broken in the original model itself which is causing it to break when geometries are merged.
![image](https://user-images.githubusercontent.com/24761808/56878369-66cbed00-6a71-11e9-9a2a-7a2eba68ce48.png)
Without merge
![image](https://user-images.githubusercontent.com/24761808/56878416-a5fa3e00-6a71-11e9-8570-635cc39b2d18.png)
With merge

**Comment by VivekSri006** [comment] 2023-05-02 07:09
how can we apply different materials in mergeBufferGeometries ?

**Comment by Mugen87** [comment] 2023-05-02 07:46
Applying different materials to a merged geometry defeats the purpose of merging geometries in the first place. You want to reduce draw calls but by using multi materials you end up with multiple render items again.
