### ISSUE TITLE
Linewidth parameter for LineBasicMaterial is ignored

### ISSUE THREAD

**Issue by alex4200** [mrdoob/three.js#20228] opened 2020-08-30 15:16 UTC
##### Description of the problem

The parameter `linewidth` from the `LineBasicMaterial` [class](https://threejs.org/docs/index.html#api/en/materials/LineBasicMaterial) is ignored. The expected outcome is to set the width of a line with this parameter. 

Code: 

 ```
 container = document.createElement('div');
document.body.appendChild(container);
camera = new THREE.PerspectiveCamera(45, window.innerWidth / window.innerHeight, 1, 10000);
camera.position.set(0, 0, 150);
scene = new THREE.Scene();
scene.add(camera);
renderer = new THREE.WebGLRenderer({
	clearAlpha: 1
});
renderer.setSize(window.innerWidth, window.innerHeight);
renderer.setClearColor(0xcaffee, 1);
document.body.appendChild(renderer.domElement);
			
var material = new THREE.LineBasicMaterial( { color: 0xff0000, linewidth: 10000000 } );
var points = [];
points.push( new THREE.Vector3(-50, 0, 0 ) );
points.push( new THREE.Vector3( 50, 0, 0 ) );
var geometry = new THREE.BufferGeometry().setFromPoints( points );
var line = new THREE.Line( geometry, material );
scene.add( line );
renderer.render( scene, camera );
			
animate();
function animate() {
	requestAnimationFrame(animate);
	renderer.render(scene, camera);
}
```

##### Three.js version

- [x] r119
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [x] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [x] macOS 10.14.6
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment] 2020-08-30 15:58
Duplicate of #10357.

**Closed by Mugen87** 2020-08-30 15:58 UTC
