### ISSUE TITLE
Object is still referenced by renderItems in WebGLRenderList, after it is removed from scene.

### ISSUE THREAD

**Issue by clineyuan** [mrdoob/three.js#12621] opened 2017-11-10 08:40 UTC
After an object was removed from scene, it is still referenced by renderItems.  I clear renderItems as below. But the object may be referenced by opaque or transparent. Once I clear opaque and transparent, nothing is rendered(only background color)! I don't how to get it fixed. Could you please double check if the original code is correct and if not how to fix it?

	`function WebGLRenderList() {

		var renderItems = [];
		var renderItemsIndex = 0;

		var opaque = [];
		var transparent = [];

		function init() {

			renderItemsIndex = 0;
			opaque.length = 0;
			transparent.length = 0;

			# renderItems = [];
		}`

##### Three.js version
- r88

**Comment by Usnul** [comment] 2017-11-10 10:09
I do not understand what your problem is. You have not explain what you are doing, what happens and how it differs from your expectations.

The code you have provided does not help to clarify this situation for me.

Please consider editing your post.

**Comment by clineyuan** [comment] 2017-11-10 12:19
Usnul, in my project, threejs objects will be added to and removed from scene frequently. Once I remove them from scene, I suppose that they should be referenced by THREE. But when I use Chrome dev tool to take a snapshot, I found "renderItems" still kept some of them.

The above code only assigns zero to renderItemsIndex, but doesn't make renderItems empty. I think it causes the "memory leak".

**Comment by aardgoose** [comment] 2017-11-11 20:54
This is a duplicate of #12447 which is addressed by PR #12464 (not merged yet)

**Comment by clineyuan** [comment] 2017-11-12 03:34
Great!

**Closed** 2017-11-12 10:51 UTC
Labels: Duplicate
