### ISSUE TITLE
ObjectLoader.prototype.load whitespace incorrectly typed at this.resourcePath

### ISSUE THREAD

**Issue by ajvincent** [mrdoob/three.js#15216] opened 2018-11-06 14:58 UTC
##### Description of the problem

https://github.com/mrdoob/three.js/blob/dev/src/loaders/ObjectLoader.js#L78
this.resourcePath = this.resourcePath || path;

Between "||" and "path", there is a \xa0 character, which should be a space.  This caused a syntax error.  From Firefox devtools:

SyntaxError: unexpected token: identifier[Learn More] three.js:38497:45

This appeared using build/three.js, not build/three.min.js.

##### Three.js version

- [x] Dev
- [x] r98
- [ ] ...

##### Browser

- [ ] All of them
- [ ] Chrome
- [x] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [ ] macOS
- [x] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

n/a

**Comment by Mugen87** [comment] 2018-11-06 15:16
Should be fixed in `dev` with new builds. Sry, I have no idea how this happened 🤔 .

**Closed** 2018-11-06 15:15 UTC

**Comment by ajvincent** [comment] 2018-11-06 15:20
Thanks for the rapid response!  This was obviously very easy to miss. I didn't see it at first when looking at GitHub.  I would suggest a build verification step that looks for whitespace characters like this, or does a try (load(...))

**Comment by Mugen87** [comment] 2018-11-06 15:28
I have no error when using `ObjectLoader` in the unminified build with Firefox on macOS.

https://threejs.org/examples/#webgl_loader_json_claraio

Could this problem related to the OS? (I've seen you are using Linux)

**Comment by ajvincent** [comment] 2018-11-06 15:37
> Could this problem be related to the OS? (I've seen you are using Linux)

Maybe...  (Specifically, I am on Fedora Linux 28.) But it's running inside a web browser, so it shouldn't really be a factor.  I'd be very surprised if \xa0 was treated as a space on MacOS and as something else on Linux by the JavaScript engine.

**Comment by Mugen87** [comment] 2018-11-06 16:20
Strange. Like I said, I'm not able to reproduce the syntax error on macOS. FF on Android 9 looks also good (tested on a Pixel).

In any event, thanks for reporting this issue! 👍
