### ISSUE TITLE
Animation not working - DAE Load - https://blackthread.io/gltf-converter/

### ISSUE THREAD

**Issue by thebiggins** [mrdoob/three.js#18207] opened 2019-12-20 05:50 UTC
I have a DAE model that previews fine in macOS Catalina with animation.  Drag and dropping into GLTF converter (https://blackthread.io/gltf-converter/) shows the model but not the animation.  Animations from a test FBX do show.

MacOS 10.15.1 DAE Preview (it is animating)

<img width="212" alt="Screen Shot 2019-12-19 at 9 27 25 PM" src="https://user-images.githubusercontent.com/13670112/71232430-d3b52100-22a6-11ea-9b07-6abafce4ed2d.png">

The same DAE file also loads properly into Cheetah3D with working animation.

<img width="1165" alt="Screen Shot 2019-12-19 at 9 29 07 PM" src="https://user-images.githubusercontent.com/13670112/71232968-ea5c7780-22a8-11ea-8379-59e7d4b5adb5.png">

Model File Attached:

[Ezreal_Idle.dae.zip](https://github.com/mrdoob/three.js/files/3986899/Ezreal_Idle.dae.zip)

##### Three.js version

- [ ] Dev
- [ ] r111
- [x] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)
MacBook Pro 13" i5 1.4Ghz
Intel Iris Plus Graphics 645 1536 MB

**Comment by Mugen87** [comment] 2019-12-20 09:36
This issue is actually a duplicate of #13981. I assume it's not yet possible to directly export to glTF from Cheetah3D, right?

Can you please try the conversion with this CLI tool? 

https://github.com/KhronosGroup/COLLADA2GLTF/

**Comment by Mugen87** [comment] 2019-12-20 09:36
This issue is actually a duplicate of #13981. I assume it's not yet possible to directly export to glTF from Cheetah3D, right?

Can you please try the conversion with this CLI tool? 

https://github.com/KhronosGroup/COLLADA2GLTF/

**Comment by thebiggins** [comment] 2019-12-21 22:11
@Mugen87 I Converted the file using https://github.com/KhronosGroup/COLLADA2GLTF/

- The model now loads with what appears to be proper bone hierarchy but the mesh is a mess.
![Screen Shot 2019-12-21 at 2 02 29 PM](https://user-images.githubusercontent.com/13670112/71314306-95307b00-23fa-11ea-9e69-75a8f6853444.png)

**Exported File:**
[Ezreal_Idle.gltf.zip](https://github.com/mrdoob/three.js/files/3991858/Ezreal_Idle.gltf.zip)

Cheetah3D does support GLB/GLTF export now (not import though) but I am using the trial which can't export (I will post in their forum asking for them to convert for me).

**Comment by donmccurdy** [comment] 2019-12-22 00:31
The DAE/Collada model also looks pretty broken after importing into Blender:

![Screen Shot 2019-12-21 at 4 29 36 PM](https://user-images.githubusercontent.com/1848368/71315334-607aee80-240f-11ea-912c-e89e72091f0f.png)

**Comment by thebiggins** [comment] 2019-12-22 02:00
@donmccurdy Correct, If I run the DAE through the Autodesk converter and save as an FBX it will load into Blender (and Godot 3.2b4) but some of the rotations are off just a bit in the animation (not usable).

Blender and Godot are doing something wrong in their import/export - MacOS and Cheetah have it right.  I haven't tried Maya yet, I have that on my work machine - I will give that a shot tonight and see if I can export into something Godot can handle properly.  From what I hear, GLTF is the preferred format for Godot.  

At least I know Unity works - was just wanting to do a small project to test Godot.  I appreciate all the effort from everyone :)

**Comment by thebiggins** [comment] 2019-12-22 05:55
Frank Beckmann from the C3D forum converted the DAE for me - works fine in three.js and Godot, though the mesh still has some issues in Blender.  I am going to pick up Cheetah3D :)

**Converted Files:**
[Ezreal_Idle.gltf.zip](https://github.com/mrdoob/three.js/files/3992170/Ezreal_Idle.gltf.zip)
[Ezreal_Idle.glb.zip](https://github.com/mrdoob/three.js/files/3992171/Ezreal_Idle.glb.zip)

**Closed** 2019-12-22 10:14 UTC
Labels: Duplicate, Loaders
