### ISSUE TITLE
Setting "needsUpdate" to true on WebGLRenderTarget.texture fails

### ISSUE THREAD

**Issue by gkjohnson** [mrdoob/three.js#18852] opened 2020-03-10 02:23 UTC
I ran into this when trying to add a user toggle for switching between point and linear filtering like so:

```js
const renderTarget = new WebGLRenderTarget();

// ...render scene...

renderTarget.texture.minFilter = NearestFilter;
renderTarget.texture.needsUpdate = true;

// rendering fails because texture can't be updated
```

Here's a fiddle demonstrating the issue (needsUpdate is set in the render loop):

https://jsfiddle.net/qg7rmu4k/

I see that issue #9327 was closed previously for not having a use case attached to it. In this case it's because I'm setting needsUpdate in order to change any of the texture sampling fields.

**Comment by Mugen87** [comment] 2020-03-10 10:38
This issue is actually a duplicate of #14375.

**Closed** 2020-03-10 10:38 UTC
Labels: Duplicate

**Comment by gkjohnson** [comment] 2020-03-11 02:17
Thanks! I missed that -- I'll take the conversation over there.
