### ISSUE TITLE
Renderer context moved to iframe causing isWebGL2 to fail

### ISSUE THREAD

**Issue by antpb** [mrdoob/three.js#25638] opened 2023-03-09 04:47 UTC
### Description

I'm seeing a very similar issue to https://github.com/mrdoob/three.js/issues/24634 in iframe contexts and thought I'd raise it again for consideration.

I have a WordPress plugin that lets you build Three.js scenes in the wp post editor. There was a recent change to WordPress where the post editor is now wrapped in an iframe. This is causing behavior very similar to the issue linked above where the webgl context breaks and cant render anything with non-basic materials or textures. This change will likely not be reverted so I need to figure out a workaround to keep this plugin alive.

I've been documenting my progress debugging this in the WordPress issue: https://github.com/WordPress/gutenberg/issues/47983

Before iframe wrapper:
<img width="565" alt="Screenshot 2023-03-08 at 10 14 33 PM" src="https://user-images.githubusercontent.com/8985705/223918137-fe4467fc-a106-4619-8b87-d3b7c30cef79.png">

After iframe wrapper:
<img width="808" alt="Screenshot 2023-03-08 at 10 14 16 PM" src="https://user-images.githubusercontent.com/8985705/223918143-47373781-c7c4-4426-8dc1-7b902c8a06bf.png">

I've attempted to define webgl2 explicitly in my Canvas component (using r3f) but it doesnt seem to stick when the context is moved to inside an iframe. 

I've documented this issue since I've been trying to solve it within the WordPress repository but I fear there isn't a fix I can implement on that side of things.

My plugin code lives here for more context:
https://github.com/antpb/three-object-viewer

If you are familiar or have a WordPress handy you can reproduce this on a site by installing the Gutenberg plugin and the Three Object Viewer plugin together. The Gutenberg plugin is the development version of the WordPress editor so it has all the new and shiny things like this iframe change. 

### Reproduction steps

1. If you have a WordPress site log in and go to the plugin screen
2. click add new
3. search Gutenberg
4. Install and activate Gutenberg (this is the development build of the editor)
5. Go back go plugin screen this time searching for Three Object Viewer
6. Add a post and type `/3D Environment` and select the 3D environment block
7. See webgl errors

### Code

```js
// code goes here
```

### Live example

Don't have a live example since this only happens in the logged in editor view.

### Version

0.150.1

### Device

Desktop

### Browser

Chrome

### OS

MacOS

**Comment by donmccurdy** [comment] 2023-03-09 04:56
Could you share the full error log, and the full set of HTML attributes attached to the iframe? It will be much easier for us to investigate this if we can reproduce the issue in a web browser without having to set up a new WordPress project first.

**Comment by Mugen87** [comment] 2023-03-09 09:06
Duplicate of https://github.com/mrdoob/three.js/issues/24634.

**Closed by Mugen87** 2023-03-09 09:06 UTC
Labels: Duplicate
