### ISSUE TITLE
There is a bug about CSS2DRenderer

### ISSUE THREAD

**Issue by dds-du** [mrdoob/three.js#25611] opened 2023-03-03 09:17 UTC
### Description

When I dblclick a CSS2DRenderer mask,it's will choose something that can't see.
Then, my mouse become not-allowed when I drag it. 

### Solution

I resloved it by add style user-select:none to the CSS2DRenderer div.

### Alternatives

CSS2DRenderer, Bug

**Comment by Mugen87** [comment] 2023-03-03 09:20
Can this is be reproduced with one of the live examples? E.g.: https://threejs.org/examples/css2d_label?

If not, do you mind adding a fiddle that demonstrates the issue? https://jsfiddle.net/g3atw6k5/

**Comment by Mugen87** [comment] 2023-03-03 11:25
Closing. The issue can be reopened when the issue is properly filed. Meaning with live examples.

**Closed by Mugen87** 2023-03-03 11:25 UTC
