### ISSUE TITLE
camera.getWorldDirection() behavior altered in WebXR

### ISSUE THREAD

**Issue by paulmasson** [mrdoob/three.js#19891] opened 2020-07-21 00:37 UTC
In WebVR one could simply use `camera.getWorldDirection()` to find the direction in which the camera is pointed in VR. As of r113, in WebXR this same call returns information about the parent rig of the camera, rather than the camera, at least in Oculus browser on both Quest and Go.

The culprit is the line `this.updateMatrixWorld( true )` in the function, because without it the correct camera information is returned. I can't see any recent changes in `camera.updateMatrixWorld` that would cause the change. Is this just expected behavior in WebXR vs WebVR? If so then `camera.getWorldDirection` is not useful in this context.

**Comment by Mugen87** [comment] 2020-07-21 08:34
Duplicate of #18448.

**Closed by Mugen87** 2020-07-21 08:34 UTC

**Comment by Mugen87** [comment] 2020-07-21 08:36
Can you please verify if #19085 would solve the issue?
