### ISSUE TITLE
[docs] TorusKnotGeometry & TorusKnotBufferGeometry misleading code in the official docs

### ISSUE THREAD

**Issue by danieldanielecki** [mrdoob/three.js#19191] opened 2020-04-22 15:59 UTC
##### Description of the problem

The official docs for [TorusKnotGeometry](https://threejs.org/docs/#api/en/geometries/TorusKnotGeometry) and [TorusKnotBufferGeometry](https://threejs.org/docs/#api/en/geometries/TorusKnotBufferGeometry) has misleading code examples. To achieve that one as in the docs developers need to use `MeshLambertMaterial`, not `MeshBasicMaterial` as written in the docs. It gives completely different output than in the code examples which you can see in the CodeSandboxes below.

If you'll take a look into the color `0xffff00` in code examples, it cannot match, because it's yellow. Not like in the visualisation light blue...

It looks like these docs should be improved to give a real code, because based on these I couldn't reproduce the effect, at all. Possibly it would be `MeshLambertMaterial` with `AmbientLight`/`PointLight` (or any other lights - couldn't fully reproduce on my own). For other settings of this visualisation I've followed [creating a scene manual](https://threejs.org/docs/#manual/en/introduction/Creating-a-scene).

* [CodeSandbox using MeshLambertMaterial based on official code example](https://codesandbox.io/s/torusknotbuffergeometry-using-meshlambertmaterial-cqj6s)
* [CodeSandbox using MeshBasicMaterial based on official code example](https://codesandbox.io/s/torusknotbuffergeometry-using-meshbasicmaterial-9t6dg)

##### Three.js version

- [x] 110 (latest at CDN)

##### Browser

- [x] All of them

##### OS

- [x] Not applicable

##### Hardware Requirements (graphics card, VR Device, ...)

- [x] None

**Comment by Mugen87** [comment] 2020-04-22 16:14
All code examples of the geometries use `MeshBasicMaterial`. These listings are actually unrelated to the geometry browser (which is the WebGL content you see in the doc pages).

If this is confusing, I would rather remove all code examples since the geometry browser also uses `WireframeGeometry`, lights and so on. You would have to list a lot of code if it should 100% reproduce what you see in the rendered scene.

**Comment by danieldanielecki** [comment] 2020-04-23 04:56
I'd like to reproduce the example from `TorusKnotBufferGeometry`/`TorusKnotGeometry`, but with these 4 lines that's definitely not gonna to happen:

```
var geometry = new THREE.TorusKnotBufferGeometry( 10, 3, 100, 16 );
var material = new THREE.MeshBasicMaterial( { color: 0xffff00 } );
var torusKnot = new THREE.Mesh( geometry, material );
scene.add( torusKnot );
```

Where can I find full source code for it then? Don't you find it a bit confusing giving a code example which doesn't work as expected?

**Comment by Mugen87** [comment] 2020-04-23 08:35
> Where can I find full source code for it then? 

Right here: https://github.com/mrdoob/three.js/blob/dev/docs/scenes/geometry-browser.html

> Don't you find it a bit confusing giving a code example which doesn't work as expected?

Well, it depends a bit on what your expectations are. I never would have thought that the current layout of the page could be confusing for users. 

The code example just represents a minimal setup that shows how to create an instance of the respective geometry. The geometry browser is a totally different thing. TBH, I though this would be obvious...

**Comment by danieldanielecki** [comment] 2020-04-23 09:43
Many thanks @Mugen87 for the link, couldn't see anywhere in the docs that to have it working some extra methods are required. Will try to reproduce this knot with the given source code. 

Well, if you're not getting any docs improvements from developers like that one, then definitely close this issue.

**Comment by Mugen87** [comment] 2020-04-23 10:32
Okay, let's close this for now. If more users hit the same issue, we can still think of a different approach.

**Closed by Mugen87** 2020-04-23 10:32 UTC
Labels: Documentation

**Comment by danieldanielecki** [comment] 2020-04-27 10:23
@Mugen87 took some time to reproduce it, but finally [it is (CodeSandbox)](https://codesandbox.io/s/torusknotbuffergeometry-almost-complete-as-in-the-official-docs-9mqje)! It's not 100% as in the docs, even though the properties seems to be the same as in the [source code](https://github.com/mrdoob/three.js/blob/dev/docs/scenes/geometry-browser.html). If you have some time I'd be happy to see the modified CodeSandbox, shouldn't take you much time.

To be honest, it's not the most pleasant library to use I've touched. It's my second time (right after [an animation to my 404 page](https://codesandbox.io/s/threejs-ball-wireframe-xt4u6)) with Three.js and the docs in a form of CodeSandboxed/alternatives would've been way easier to read. Remember, that the first animation took me 1 week to realise what is what (using in Angular/TypeScript though). At least for me all these things like camera, lights, scene were not obvious. If you'd work on docs in the future, [Svelte](https://svelte.dev) has the best docs I've ever seen (especially the REPL part).

The linked [source code](https://github.com/mrdoob/three.js/blob/dev/docs/scenes/geometry-browser.html) is also basically, without any kind of documentation (e.g. `JSDoc`). With an alternatives sources [such as this](https://threejsfundamentals.org/threejs/lessons/threejs-primitives.html) was able to work on the `TorusKnotBufferGeometry`.

Nevertheless, thanks for the response and take this as a feedback.

PS. `MeshBasicMaterial` is not being used, [as you can see its MeshPhongMaterial.](https://github.com/mrdoob/three.js/blob/dev/docs/scenes/geometry-browser.html#L1498), which is different than [LineBasicMaterial](https://github.com/mrdoob/three.js/blob/dev/docs/scenes/geometry-browser.html#L1497).

**Comment by Mugen87** [comment] 2020-04-27 10:33
Here is the updated live example. The parameters of `TorusKnotBufferGeometry` were slightly off:

https://codesandbox.io/s/torusknotbuffergeometry-almost-complete-as-in-the-official-docs-4qgci?file=/index.html

> PS. MeshBasicMaterial is not being used, as you can see its MeshPhongMaterial., which is different than LineBasicMaterial.

I was referring to the minimal code example, not the geometry browser.

**Comment by danieldanielecki** [comment] 2020-04-27 11:51
@Mugen87 many thanks!

Didn't catch [this](https://github.com/mrdoob/three.js/blob/dev/docs/scenes/geometry-browser.html#L1134-L1141), just used parameters from the official docs.

**Comment by zlf2002171** [comment] 2020-05-18 14:21
unsubscribe


2020-05-18 

zlf2002171 



发件人：✅ Daniel Danielecki <notifications@github.com>
发送时间：2020-04-27 19:52
主题：Re: [mrdoob/three.js] [docs] TorusKnotGeometry & TorusKnotBufferGeometry misleading code in the official docs (#19191)
收件人："mrdoob/three.js"<three.js@noreply.github.com>
抄送："Subscribed"<subscribed@noreply.github.com>

@Mugen87 many thanks!
Didn't catch this, just used parameters from the official docs.
