### ISSUE TITLE
Question:Can support VAO?

### ISSUE THREAD

**Issue by cjsjy123** [mrdoob/three.js#19408] opened 2020-05-21 10:32 UTC
I saw the relevant PR, and verified some of the performance improvements, but it has not been merged into this. Can the official support VAO? Or when will it be ready to support VAO?

**Comment by Mugen87** [comment] 2020-05-21 11:33
Closing this as a duplicate of #8705. Please continue the discussion about VAO's there.

**Closed by Mugen87** 2020-05-21 11:33 UTC
