### ISSUE TITLE
Incorrect bounding box, collada model

### ISSUE THREAD

**Issue by stijndeschuymer** [mrdoob/three.js#13989] opened 2018-05-04 08:57 UTC
##### Description of the problem

In the latest version (r92) the stormtrooper collada model has an incorrect boundingBox.
I tried the BoxHelper:
```
const box = new THREE.BoxHelper(object, 0xff0000);
scene.add(box);
```
or a manual approach:
```
const boundingBox = new THREE.Box3().setFromObject(trooper);
const size = boundingBox.getSize();
const center = boundingBox.getCenter();
const geometry = new THREE.BoxGeometry(size.x, size.y, size.z);
const material = new THREE.MeshBasicMaterial({ wireframe: true, color: 0x0000ff });
const box2 = new THREE.Mesh(geometry, material);
box2.position.set(center.x, center.y, center.z);
scene.add(box2);
```
Both approaches result in the model not being in the boundingbox:
<img width="419" alt="screen shot 2018-05-04 at 10 31 38" src="https://user-images.githubusercontent.com/4083920/39619241-6cc3028a-4f87-11e8-9a29-edc91c513a82.png">

I already figured out that this started with r87,
r86 didn't have this issue:
<img width="511" alt="screen shot 2018-05-04 at 10 31 25" src="https://user-images.githubusercontent.com/4083920/39619325-b69244a2-4f87-11e8-822d-b5ab8fcb3444.png">

example code:
r86: https://github.com/mrdoob/three.js/compare/r86...stijndeschuymer:bounding-box-test
r87: https://github.com/mrdoob/three.js/compare/r87...stijndeschuymer:bounding-box-test-r87

I'm currently trying to figure out what causes this, but I'm quite new to three.js,
so I'd highly appreciate it if someone pointed me in the right direction!

##### Three.js version

- [x] r92
- [x] r87
- [ ] r86

**Comment by stijndeschuymer** [comment] 2018-05-04 09:14
apperently the example in r87 is ColladaLoader2.js

**Comment by Mugen87** [comment] 2018-05-04 09:26
From my point o view, it's not a bug. It works as designed.

> Is there a way to get around this?

Read https://github.com/mrdoob/three.js/issues/11991 for more information.

**Comment by Mugen87** [comment] 2018-05-04 09:30
This issue is essentially duplicate of #11991 since both are related to bounding volumes and animation.

**Comment by stijndeschuymer** [comment] 2018-05-04 11:52
Thanks! I checked #11991 but I still have issues trying to draw a boundingbox, I'll move this to [stackoverflow](https://stackoverflow.com/questions/50173778/three-js-draw-bounding-box-around-skinnedmesh) https://jsfiddle.net/66sor15y/4/

**Closed** 2018-05-04 12:26 UTC
Labels: Duplicate
