### ISSUE TITLE
GLTF Exporter: Multiple objects with same name animation issue

### ISSUE THREAD

**Issue by viperphase1** [mrdoob/three.js#18895] opened 2020-03-13 21:02 UTC
If two objects have the same name and the second object has animations the animations on the second object will instead be applied to the first on export.

**Comment by donmccurdy** [comment] 2020-03-13 21:21
Hmmm... KeyframeTrack objects typically have a [`.name` property](https://threejs.org/docs/#api/en/animation/KeyframeTrack.name) like `Cog.scale` where "Cog" is the name of the object it refers to. With only that to go on, I don't think that GLTFExporter can guess which object you want the animation to affect.

You might want to change your keyframe tracks to reference UUIDs, or ensure unique names on the objects?

**Comment by viperphase1** [comment] 2020-03-13 21:46
> You might want to change your keyframe tracks to reference UUIDs

Okay I'll try that. Thanks for the suggestion.

**Comment by viperphase1** [comment] 2020-03-13 22:41
Unfortunately changing the keyframe track's name to use the object's uuid doesn't fix the problem. It's as if the exporter uses the uuid to find the name of the object and sets the keyframe track's name to '[object_name].quaternion'.

**Comment by donmccurdy** [comment] 2020-03-17 05:29
@viperphase1 GLFTExporter uses the track name to look up the object it references:

https://github.com/mrdoob/three.js/blob/42c09065d951c526702b545fba016ce5e2a7f1e9/examples/js/exporters/GLTFExporter.js#L1567-L1568

If that lookup returns the right object, then the exported file should have animation targeting the right object. I'd suggest testing your model in https://sandbox.babylonjs.com/ just to be sure it's not dealing with unique name related issues.

If it works there, but not when you bring it back into three.js, then I guess you're dealing with the opposite end of the problem — GLTFLoader creates a _new_ clip using the name of the object that clip targets. When you pass that clip into your AnimationMixer, if two objects share that name under the root object given to the mixer, they could get mixed up again.

**Comment by donmccurdy** [comment] 2020-03-28 19:29
As far as I can tell this is a duplicate of https://github.com/mrdoob/three.js/issues/15087. GLTFExporter may be writing the correct thing, but GLTFLoader is unable to target animation at objects with duplicate names. A PR has been opened to fix that, or in the meantime you may need to avoid the issue by assigning unique names to objects.

**Closed by donmccurdy** 2020-03-28 19:29 UTC
