### ISSUE TITLE
Update broke fbx loader, doesn't load textures

### ISSUE THREAD

**Issue by Heaust-ops** [mrdoob/three.js#22285] opened 2021-08-06 15:32 UTC
FBXLoader doesn't load textures,
I tried swapping out the threejs lib in the node modules to an older one (a month old) and it works,
so some update happened which either broke it or changed the way it works?

Import:
`import { FBXLoader } from "three/examples/jsm/loaders/FBXLoader";`

Code:
```
  loadFBXModel(path, modelFile, pos = [0, 0, 0], size = 0.1) {
    const loader = new FBXLoader();
    loader.setPath(path);
    loader.load(modelFile, (fbx) => {
      fbx.scale.setScalar(size);
      fbx.traverse((c) => {
        c.castShadow = true;
      });
      fbx.position.copy(new THREE.Vector3(...pos));
      this._scene.add(fbx);
    });
  }
```
how it is with older version:
<img width="136" alt="image" src="https://user-images.githubusercontent.com/54670936/128532439-b4fb84f5-c87a-445b-8d34-d33086cbc46e.png">

how it is in the current version:
<img width="125" alt="image" src="https://user-images.githubusercontent.com/54670936/128532623-39c0a5d0-a785-4dec-a204-7f5f788dabe3.png">

**Comment by Mugen87** [comment] 2021-08-06 15:43
Do you mind sharing the FBX asset with all textures in this thread?

**Comment by Heaust-ops** [comment] 2021-08-06 16:03
> Do you mind sharing the FBX asset with all textures in this thread?

Sure,
https://drive.google.com/drive/folders/1iGboxEd-4Z8xodyxjSqoU1qV_CRM6rfY?usp=sharing
(I don't have separate textures, I downloaded it from mixamo, also idk how to upload files on github so here's a drive link)

**Comment by guerreroje** [comment] 2021-08-06 16:46
I also have the same problem with some FBX models that in previous versions worked correctly for me. It throws me these warnings:
THREE.Material: 'map' parameter is undefined.
THREE.Material: 'normalMap' parameter is undefined.
THREE.Material: 'specularMap' parameter is undefined.
THREE.FBXLoader: Vertex has more than 4 skinning weights assigned to vertex. Deleting additional weights.

**Comment by Mugen87** [comment] 2021-08-06 17:55
@camnewnham Do you mind having a look at this issue?

**Comment by worstpractice** [comment] 2021-08-06 22:33
I can confirm this issue.

[This repo](https://github.com/worstpractice/babbys-first-skyrim) should have everything you need, just make sure you have the pnpm package manager installed (npm i -g pnpm) and you should be good to go (pnpm i && pnpm start).

I primarily dev on Windows (10), so apologies if any platform-specific code snuck in. I always try to write portable code, even for personal toy projects like this one.

I recently bumped three-js, and now the sword guy looks just like on the "after" sceenshot posted by @Heaust-ops above.

**Comment by camnewnham** [comment] 2021-08-06 22:38
Thanks for the reports and providing the sample files.
This was caused by https://github.com/mrdoob/three.js/pull/22114 and is resolved by https://github.com/mrdoob/three.js/pull/22289

**Comment by worstpractice** [comment] 2021-08-06 22:58
> Thanks for the reports and providing the sample files.
> This was caused by #22114 and is resolved by #22289

I can further confirm that #22289 has indeed fixed the issue.

Thank you!

**Comment by Heaust-ops** [comment] 2021-08-07 10:16
That does solve the problem thank you so much!! :D
(not closing the issue rn cause it isn't merged yet)

**Closed** 2021-08-07 10:36 UTC
Labels: Loaders, Needs Investigation

**Comment by Mugen87** [comment] 2021-08-07 10:38
PR is now merged so the module version of `FBXLoader` is now fixed on `dev` 👍 .
