### ISSUE TITLE
VTK loader for "UNSTRUCTURED_GRID" dataset

### ISSUE THREAD

**Issue by DevArt002** [mrdoob/three.js#20258] opened 2020-09-02 22:44 UTC
Hi, Three.js team.

I am a fan of Three.js. I had done several successful Three.js projects.
So, first of all, I would love to say, "Thank you for your dedicated library".

##### Description of the problem
I know that now I am commenting duplicated issue related to VTK loader.
The issue was commented in Feb, 2018. But since I VTK loading is important certainly, I decided to comment again.

So, I have one VTK file generated from one external device. It has UNSTRUCTURED_GRID dataset which is not allowed yet by VTK loader. Of course, I tried to use alternative model extensions such as .fbx, .ply, etc.
But unfortunately, my partners says it's a pain for them to convert current VTK to different extensions.
Anyway, they provided me .ply. Its external shape looks good. But the internal shape is just empty one.

This is VTK internal view:
![vtk_capture](https://user-images.githubusercontent.com/52213952/92043050-ba2f0900-ed51-11ea-8e84-e4b2d3b12567.png)

And this is PLY internal view:
![ply_capture](https://user-images.githubusercontent.com/52213952/92043404-5c4ef100-ed52-11ea-96a8-c3053e42a8b0.PNG)

As you can see, their internal views are different.

At the moment, I'd like to ask 2 questions:
1. VTK loader will never work with the rest 4 vtk datasets including  "UNSTRUCTURED_GRID"?
2. If so, how can we generate alternative model extension having same geometry as VTK?

##### Three npm version
0.120.1 latest

I'd love to believe you know the solution.

Thank you!

**Comment by mrdoob** [comment] 2020-09-03 08:03
Could you share the vtk file so we can investigate?

**Comment by Mugen87** [comment] 2020-09-03 08:52
This issue is actually a duplicate of #13386.

**Comment by DevArt002** [comment] 2020-09-03 09:51
Hi, @Mugen87 

Yes, it's duplicated issue. But the last issue was commented about 2 years ago. So, wanted to ask if it's not supported yet.
And if so, wanted to ask how we can overcome the issue with alternative solution.

**Comment by Mugen87** [comment] 2020-09-03 10:02
It's okay to continue the discussion in existing threads. That makes it easier to follow the topic.

**Closed** 2020-09-03 10:16 UTC
Labels: Duplicate, Loaders

**Comment by DevArt002** [comment] 2020-09-03 10:24
hum, it's not helpful.
Could you mind to let me know how to overcome above issue?
As you can see, the PLY geometry is different from VTK one.

**Comment by Mugen87** [comment] 2020-09-03 10:38
> VTK loader will never work with the rest 4 vtk datasets including "UNSTRUCTURED_GRID"?

This depends if someone contributes the respective code in `VTKLoader`. If you look at the history of #13386, it is not a very requested feature.

> As you can see, the PLY geometry is different from VTK one.

Is this also try in other viewers. For example that happens if you import the PLY file to Blender? If it looks the same like `three.js`, the PLY export is probably wrong.

**Comment by DevArt002** [comment] 2020-09-03 10:43
Yes, PLY was not exported correctly.

**Comment by DevArt002** [comment] 2020-09-03 10:45
Well, it is a different question.
What is your feedback CSG.js? I am using it for mesh manipulation.

**Comment by Mugen87** [comment] 2020-09-03 11:17
Please continue the discussion at the [forum](https://discourse.threejs.org/). GitHub is intended for feature requests and bug reports only.
