### ISSUE TITLE
ObjectLoader joined Geometry MultiMaterial with textures

### ISSUE THREAD

**Issue by trumanus** [mrdoob/three.js#10000] opened 2016-11-03 17:04 UTC
##### Description of the problem 

I tried understand why threejs ObjectLoader does not import multi material on a single skynned and i found that only a material il loaded per geometry.

i don't want to unwrap models becouse a lot of work

how can ObjectLoader does  like JSONLoader ?

![textureproblem](https://cloud.githubusercontent.com/assets/3648370/19976455/0234cf7a-a1f0-11e6-9260-700f0c4cefc1.png)
 
i test also Jsonaloader instead but no model is shown..

please help i'm blocked..

##### Three.js version

- [ ] Dev
- [X] r82
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

##### Hardware Requirements (graphics card, VR Device, ...)

**Comment by inear** [comment] 2016-11-04 10:26
Why is this not a bug (or a featurerequest )? I have the same problem trying to export a skinned mesh with multimaterials, and the objectloader does not support it.

**Comment by mrdumb** [comment] 2016-11-04 11:23
It works just fine.
But you need to know how to create the skinned mesh.
Example: http://necromanthus.com/Test/html5/ptess.html

**Comment by inear** [comment] 2016-11-04 12:07
That example is loaded with the JSONLoader, not the ObjectLoader. The JSONLoader works with multiple materials, even though you need to wrap it manually (as you do) with a THREE.MultiMaterial (previously called MeshFaceMaterial) before parsing the json. But the ObjectLoader suppose to replace the JSONLoader in the future from what I understand, and work seems to be focused on that one. It's also a Blender issue, I don't know about the 3DSMax exporter in your case. In Blender, the face material indexes are added, but the material is only one, not an array. Multi materials work if you create all the materials manually, but that is not an optimal workflow when getting models from the artists.

**Comment by mrdumb** [comment] 2016-11-04 12:10
JSONLoader or ObjectLoader is the same thing (here).
Your problem is (probably) the Blender exporter.

**Comment by inear** [comment] 2016-11-04 13:25
JSONLoader and ObjectLoader parse the json differently. But probably you ment that the result was the same with your example, so...

Yes, it's probably a Blender export problem. But it's hard to know where in the pipeline things get wrong. If the latest exporter follow the interface of the latest importer. Or vice versa.

So I think that it's valid to look at it as a bug. And for me it seems like the exporter can only assign one material per mesh instead of an array. The array is stored in the scene-object in json file. But not referenced as an array by the mesh itself, just one guid to the first in the list. 

https://github.com/mrdoob/three.js/blob/dev/utils/exporters/blender/addons/io_three/exporter/object.py#L94

**Comment by makc** [comment] 2016-11-05 15:23
🏆 this is issue 10K ! 🍾🎉

**Comment by makc** [comment] 2016-11-05 15:25
@mrdumb great username )

**Comment by makc** [comment] 2016-11-05 15:26
> Why is this not a bug (or a featurerequest )?

it's leftovers from issue template

**Comment by trumanus** [comment] 2016-11-05 17:22
@mrdumb is not a problem of blender exporter, in json all materials are inside i think the problem is the skinend mesh call itself... when you create the skinned Object mesh just the last material is applied.  "return material[name]" search it , from exported json materials object .

@inear 
Is not a bug from my point of view is just a PR or CR... 

load just one optimized texture map is not so incorrect, if you work into a game engine.. But there are all the passages to unwrap and pack again in blender and... finally is a lot of work...
I tried to make same change to mesh multi materials.. but the problem is the right order of UVmap into materials...

some ideas?

**Comment by makc** [comment] 2016-11-05 17:46
you could create one indexed geometry (and mesh) per material and only index relevant faces there. I guess vertex buffers can be shared to save memory.

**Comment by makc** [comment] 2016-11-05 18:07
I seem to remember that geometry has some properties for draw range, so having multiple geometries with same vertex data and ranges according to materials should also work?

**Comment by Mugen87** [comment] 2018-11-29 13:52
Closing because...

- The Blender JSON export is gone since `R93`.
- `JSONLoader` will be removed with `R99`. 
- `ObjectLoader` should properly support objects with multiple materials since `R85`.
- `SkinnedMesh` does not support `Geometry` anymore with `R99`. 

The best thing for people who still use the Blender JSON exporter is to switch to `glTF`. The following guide provides all necessary information in order to start with `glTF`:

https://threejs.org/docs/index.html#manual/en/introduction/Loading-3D-models

**Closed by Mugen87** 2018-11-29 13:52 UTC
Labels: Loaders
