### ISSUE TITLE
allocateBones problem

### ISSUE THREAD

**Issue by light564** [mrdoob/three.js#17959] opened 2019-11-19 08:00 UTC
##### Description of the problem

I have 2 skinnedMesh, use the same material. And one has 13 bones, another has 19 bones, then the allocateBones function will return 13 or 19, but not max(13, 19). It has led to some problem in Android.

##### RK3399 Android7.0

**Comment by Mugen87** [comment] 2019-11-19 10:07
I'm afraid your problem is somewhat unclear. Please invest more effort in this issue and demonstrate the problem with a live example. Alternatively, sharing a git repository with a reproduction test is also a good idea.

> It has led to some problem in Android.

Please avoid using phrases like "not working" or "some problems". Always be concrete. What problems do you see on Android? Any error messages or warnings?

**Comment by light564** [comment] 2019-11-26 08:28
I have 2 object, for example A and B.
A.skeleton=[bone1], B.skeleton=[bone1, bone2]
A.material = material1, B.material = material1
then if capabilities.floatVertexTextures is false, the allocateBones will return 1, and the shader on material1 will  #define MAX_BONES 1

**Comment by Mugen87** [comment] 2019-11-26 09:54
> he allocateBones will return 1,

Please demonstrate this with a live example since I'm unable to reproduce. Because of the following line, the function should return 2 for the second skeleton:

https://github.com/mrdoob/three.js/blob/c23622828aa2415979a700c5df68a7828edcbd36/src/renderers/webgl/WebGLPrograms.js#L75

**Comment by light564** [comment] 2019-11-26 12:09
sorry for my English.....

but the allocateBones won't execute twice, because of the same material.
this is a live example
https://jsfiddle.net/0h7ykj3p/

**Comment by Mugen87** [comment] 2019-11-26 12:27
Okay, now I see what you mean. As a workaround, you have to apply a material per skinned mesh. Also try to avoid using the same bones in different skeletons.

**Comment by light564** [comment] 2019-11-26 12:43
I use FBX file from Maya, so it's hard to do that~

**Comment by Mugen87** [comment] 2019-11-26 12:48
What happens if you convert the FBX file to `glTF` via:

https://github.com/facebookincubator/FBX2glTF

**Comment by Mugen87** [comment] 2019-12-07 12:11
I assume this issue here is a `Won't fix` because of several reasons:

- only a small number of devices are affected (84% of all devices support floating point textures and 98% support at least four texture units in the vertex shader).
- it only happens when materials are shared between skinned meshes with different bone count
- implementing a fix in `setProgram()` is complicated since the renderer would need the ability to match one material to multiple shader programs (we only support the other way around)
- as an alternative fix, the renderer could use `nVertexMatrices` as `maxBones` value in `allocateBones()`. But as a result, the renderer might allocate too many resources depending on the use case.
- the issue does not happen with WebGL 2

**Closed** 2019-12-30 15:21 UTC
