### ISSUE TITLE
Phong and Standard materials are broken @ Adreno 308 Phones

### ISSUE THREAD

**Issue by FMS-Cat** [mrdoob/three.js#19351] opened 2020-05-13 10:29 UTC
##### Description of the problem

The examples for [phong](https://threejs.org/examples/?q=phong#webgl_materials_variations_phong) and [standard](https://threejs.org/examples/?q=standard#webgl_materials_variations_standard) materials are broken on Adreno 308 phones.
~~I'm gonna try other GPUs as well.~~ did it, results below

![Android%20One%20S2_20200513_192627](https://user-images.githubusercontent.com/7824814/81801624-a9af1480-954f-11ea-9592-29db9c763c21.jpg)

##### Three.js version

r116

##### Environments

- Adreno 308
  - Android One S2, Android 8.0.0, Chrome 81
  - it LGV36, Android 8.1.0, Chrome 81
  - Galaxy J4+ SM-J415N, Android 8.1.1, Chrome 81

- DID NOT repro @ Adreno 306
  - Galaxy J5(2016) SM-J510S, Android 6.0.1, Chrome 81

- DID NOT repro @ Adreno 430
  - Xperia Z5 SO-01H, Android 7.0, Chrome 81

**Comment by FMS-Cat** [comment] 2020-05-13 10:42
It seems that the reproducing range is extremely small, we might just want to ignore this......
I'm tweaking around shaders right now but I completely have no idea what is wrong with the issue

**Comment by mrdoob** [comment] 2020-05-13 15:14
Was this the issue that required `material.precision = 'mediump';`?

**Comment by FMS-Cat** [comment] 2020-05-14 07:43
Wow... you're right. `material.precision = 'mediump'` makes it work...

Honestly I'm not sure what should we do from here...

**Comment by Mugen87** [comment] 2020-05-14 10:37
see https://github.com/mrdoob/three.js/issues/14137#issuecomment-395820452

It means that the `highp` codepath on certain Adreno devices is buggy and the following WebGL conformance test should fail:

https://www.khronos.org/registry/webgl/sdk/tests/conformance/glsl/misc/struct-as-inout-parameter.html?webglVersion=1&quiet=0&quick=1

It's a Qualcomm driver bug which is unlikely to be fixed.

**Comment by Mugen87** [comment] 2020-05-14 10:38
Also related: #14570

**Comment by Mugen87** [comment] 2020-05-14 10:39
Marking this issue as a duplicate of #14137.

**Closed by Mugen87** 2020-05-14 10:39 UTC
Labels: Device Issue, Duplicate

**Comment by mrdoob** [comment] 2020-05-14 15:00
@FMS-Cat 

> Honestly I'm not sure what should we do from here...

@bhouston proposed that we should try to use `mediump` by default in the library and fix any shaders that require changes.

**Comment by FMS-Cat** [comment] 2020-05-18 08:38
I'm going to switch to mediump by the application side when the GPU is Adreno 308 for this time. Thanks for the info!

**Comment by zlf2002171** [comment] 2020-05-18 09:09
unsubscribe

2020-05-18 

zlf2002171 



发件人："Mr.doob" <notifications@github.com>
发送时间：2020-05-13 23:15
主题：Re: [mrdoob/three.js] Phong and Standard materials are broken @ Adreno 308 Phones (#19351)
收件人："mrdoob/three.js"<three.js@noreply.github.com>
抄送："Subscribed"<subscribed@noreply.github.com>

Was this the issue that required material.precision = 'mediump';?

**Comment by arpu** [comment] 2020-05-18 18:51
@FMS-Cat  can you share the code to change this on Application level?

**Comment by FMS-Cat** [comment] 2020-05-19 01:16
> @FMS-Cat  can you share the code to change this on Application level? 

Using `material.precision` for each materials as noted above worked for me.

**Comment by arpu** [comment] 2020-05-19 07:59
th! if i set https://threejs.org/docs/#api/en/renderers/WebGLRenderer.precision  does this set it for the material too? ( like for all materials i use like in glb models)

**Comment by Mugen87** [comment] 2020-05-19 09:06
@arpu Yes, this is the default for all materials. You can overwrite it by setting `precision` on material level.
