### ISSUE TITLE
Transparent objects cannot penetrate to cast shadows

### ISSUE THREAD

**Issue by 1187882990** [mrdoob/three.js#26933] opened 2023-10-10 06:23 UTC
### Description

Transparent objects cannot penetrate to cast shadows, such as transparent Windows, and light cannot pass through clear glass to create shadows in the room.

### Solution

Similar to the effect of lights in unity, lights can penetrate transparent objects to achieve a realistic shadow effect

### Alternatives

null

**Comment by gkjohnson** [comment] 2023-10-10 07:16
Duplicate of #10600

**Closed by gkjohnson** 2023-10-10 07:16 UTC
