### ISSUE TITLE
Code Snippets in Firefox have no spacing

### ISSUE THREAD

**Issue by PulseFiction** [mrdoob/three.js#29632] opened 2024-10-12 16:01 UTC
### Description

When accessing the documentation on the Firefox browser, the code snippets do not have any spacing.

### Reproduction steps

1. Open firefox
2. Go to three.js documentation
3. Go to any part with a code snippet

### Code

N/A

### Live example

see below

### Screenshots

How it should look like (from Chrome browser):
![image](https://github.com/user-attachments/assets/f94a67b1-afe8-4055-9745-013eb75ee6c5)

How it looks like on Firefox:
![image](https://github.com/user-attachments/assets/4c8b6bf6-03a7-47d5-ae9e-8aec367cbaed)

### Version

current

### Device

Desktop

### Browser

Firefox

### OS

Windows

**Comment by Mugen87** [comment] 2024-10-12 18:36
Duplicate of #29569.

**Closed by Mugen87** 2024-10-12 18:36 UTC
