### ISSUE TITLE
backgroundNode color renders in the shadow map 

### ISSUE THREAD

**Issue by Samsy** [mrdoob/three.js#30111] opened 2024-12-12 14:22 UTC
### Description

When using : 

`scene.backgroundNode = new THREE.Color(0xff0000)`

The background color renders in the shadow map 

but also : 

`scene.background = new THREE.Color(0xff0000)` does same effects

EDIT :  

For some reasons, the backgroundNode allows THREE.Color as input, realised it is not a problem using color( 0xff000 ) from TSL color 

<img width="667" alt="Screenshot 2024-12-12 at 15 19 45" src="https://github.com/user-attachments/assets/f4b66376-51e3-4b8e-8167-6be34dfde839" />

### Live example

This fiddle display the shadow map texture in the center plane 

[Live fiddle](https://jsfiddle.net/7v0skobf/5/)

### Version

r171

### Device

Desktop

### Browser

Chrome

### OS

MacOS

**Comment by Makio64** [comment] 2024-12-13 09:39
Hey guys, looking at this issue, I was wondering if it's normal we can assign a Color to a node ? 
Is it automatically convert to vec4() node ?

**Comment by Mugen87** [comment] 2024-12-19 16:15
> I was wondering if it's normal we can assign a Color to a node ?

No, this was a caused by an issue in the renderer. Should be fixed via https://github.com/mrdoob/three.js/pull/30169.

**Comment by Mugen87** [comment] 2024-12-19 17:05
@Samsy I'll try to file an additional PR that fixes the shadow map issue. We have encountered the same issue some time ago in context of post processing.

**Closed** 2024-12-19 22:58 UTC
Labels: Nodes
