### ISSUE TITLE
TextureLoader load method onProgress does not trigger

### ISSUE THREAD

**Issue by lgd8981289** [mrdoob/three.js#20682] opened 2020-11-13 12:46 UTC
**version**
THREE.JS V0.122.0

**Describe the bug**

TextureLoader load method onProgress does not trigger

***Code***

```js
let loader = new TextureLoader();
  loader.load(
    'https://res.lgdsunday.club/renting_panorama_4.jpg',
    // onLoad
    (texture) => {
      // ...
    },
    // onProgress
    (event) => {
      console.log('----------------------------');
    }
  );
```

**Expected behavior**

onProgress should be triggered

**Comment by Mugen87** [comment] 2020-11-13 16:41
This issue is a duplicate of #10439.

`TextureLoader` internally uses `ImageLoader`. This loader is based on the `Image` API which does not support progress events.

**Closed by Mugen87** 2020-11-13 16:41 UTC
