### ISSUE TITLE
.initRenderTarget missing in WebGPURenderer

### ISSUE THREAD

**Issue by Makio64** [mrdoob/three.js#29898] opened 2024-11-15 04:02 UTC
### Description

The initRenderTarget is missing in the WebGPURenderer
https://threejs.org/docs/#api/en/renderers/WebGLRenderer.initRenderTarget

### Solution

implement it

### Alternatives

Maybe there is another way in webgpu to init it before using it i'm not aware of it.

**Comment by Makio64** [comment] 2024-11-15 04:40
It appears `WebGPURenderer` also missing `initTexture`

**Comment by sunag** [comment] 2024-11-16 20:46
![image](https://github.com/user-attachments/assets/20b44d74-3717-4da2-b908-347bb437ad7f)

`WebGPURenderer` should initialize the texture if it uses `copyTextureToTexture` automatically.

**Comment by Makio64** [comment] 2024-11-18 10:25
> ![image](https://private-user-images.githubusercontent.com/502810/386876408-20b44d74-3717-4da2-b908-347bb437ad7f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5MjU2NTksIm5iZiI6MTczMTkyNTM1OSwicGF0aCI6Ii81MDI4MTAvMzg2ODc2NDA4LTIwYjQ0ZDc0LTM3MTctNGRhMi1iOTA4LTM0N2JiNDM3YWQ3Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExOFQxMDIyMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMDhkNWRjMDgwOWMzYzE3YjI4MWEwNjZhZjg3ZDliYTI3MWZiYjZiMTFjODNmZGNjNTRjZjc5MGZlM2UzNjllJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.6EmUwdzKyOcpNyTP1Lhd7xvfXw0I6uuoP063Y2ebuzw)
> 
> `WebGPURenderer` should initialize the texture if it uses `copyTextureToTexture` automatically.

I also want to call it before display it the first time to init the renderTexture in the memory before drawing on it and avoid extra uploadtime, same for `initTexture` to avoid upload when it matters.

**Comment by Mugen87** [comment] 2024-11-23 17:12
I'm not sure I understand the use case of `initRenderTarget()` in context of `WebGPURenderer`. In `WebGLRenderer` it was only added to fix the usage of uninitialized render target textures with `copyTextureToTexture()`, see #28282. As pointed out in https://github.com/mrdoob/three.js/issues/29898#issuecomment-2480805381, that step is not required in `WebGPURenderer`.

Unlike `initTexture()` there is no texture decode overhead to avoid with `initRenderTarget()`. Is the framebuffer creation and configuration a noticeable overhead?

**Comment by Makio64** [comment] 2024-11-25 04:15
@Mugen87 I got the habbit to initialized all textures before using them and I though I should do the same for RT.
This said in a current project, when im using a RT which wasn't used I can feel there is a short latency during the frame, which make sense as the rt init screensize texture right ? Maybe there is something i got it wrong about how the RT are working in webgpu.

**Comment by Makio64** [comment] 2024-11-25 10:09
Thanks @Mugen87 !
Just to be clear if I create a renderTarget of the size of my screen, it doesnt create a texture of the same size in the gpu which will require allocation space later on the first render on this target ?
 
Should i use `renderer.initTexture( rt.texture )` or is it totally pointless ?

I will try to make an example next weekend on it.

**Comment by Mugen87** [comment] 2024-11-25 10:45
> Just to be clear if I create a renderTarget of the size of my screen, it doesnt create a texture of the same size in the gpu which will require allocation space later on the first render on this target ?

No, it does create a texture. I'm interested in the overhead that you encounter in your use case which is caused by pure memory allocation.

> Should i use renderer.initTexture( rt.texture ) or is it totally pointless ?

No it should prepone the mentioned allocation.

**Comment by Mugen87** [comment] 2024-12-19 23:19
Closing. We can reopen the issue when a performance issue with framebuffer creation can be demonstrated.

**Closed by Mugen87** 2024-12-19 23:19 UTC
Labels: Enhancement
