### ISSUE TITLE
hi baby ObjectLoader  BUG has stopped me

### ISSUE THREAD

**Issue by Yong1235321** [mrdoob/three.js#26072] opened 2023-05-17 09:47 UTC
### Description

线框几何体好像没有定义 .fromJSON() 方法！在导入包含线框几何体的场景时出现错误！位于 ObjectLoader.parseGeometries()

The wireframe geometry does not seem to have a defined. fromJSON() method! An error occurred while importing a scene containing wireframe geometry! Located in Object Loader. parseGeometries()

### Reproduction steps

1.
2.
3.

### Code

```js
// code goes here
```

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/g3atw6k5/)
* [jsfiddle-dev](https://jsfiddle.net/hjqw94c5/)

### Screenshots

![WKQQ3H3O~4VTXSML4%`VTAB](https://github.com/mrdoob/three.js/assets/103259982/b3199bfa-4309-4558-9c1b-1cb59800dbb1)
![WC2EY%RVZU3(EY}%LK@64EG](https://github.com/mrdoob/three.js/assets/103259982/984a6572-eaa3-440d-b742-8f82297c388e)

### Version

151

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by Mugen87** [comment] 2023-05-17 09:48
Duplicate of #16340.

**Closed by Mugen87** 2023-05-17 09:48 UTC
