### ISSUE TITLE
Updating textures in VR causes weird objects to appear

### ISSUE THREAD

**Issue by siner77** [mrdoob/three.js#14468] opened 2018-07-13 12:13 UTC
##### Description of the problem

I'm working on a project like MS Paint in 3D using Three.js and WebVR.

I'm trying to draw on texture using HTML canvas and canvasTexture. I'm just using lines and arcs on a virtual canvas at the place of uvs given from raycast with plane intersection. Everything here works ok.

The problem:

When I use any "handheld" drawing tool (e.g. pencil), I need to update the texture every frame to show the drawing in realtime. Then, only in VR (on desktop everything is ok), on my plane mesh (and on some other meshes added to the scene, but only a few) **a weird alpha clipping mask appears which covers pixels of my painting/drawing** (when transparency is enabled it replace drawing pixels with fully transparent pixels) (see screenshots 3 ,4, 5 and 6). This weird mask moves with me and follows me when I'm moving my head in the VR headset, it is not stationary (see screenshot 2). The appearance of the mask seems to be a set of objects in front of the camera when I'm entering VR mode (see screenshot 0).

But, when I stop drawing/painting and stop updating the texture, everything is ok and the drawing/painting displays normally (see screenshot 1).

After some investigation I figured out that the problem is in only one line of code, which sets texture needsUpdate boolean to true.

I cannnot share whole code or application, but I'm attaching some pieces of it.

Screenshot 0

![ss0](https://user-images.githubusercontent.com/5720311/42690329-0dc0f8f6-86a4-11e8-8ba1-376c24146dc7.png)

The first render of scene after entering VR mode.

Screenshot 1 

![ss1](https://user-images.githubusercontent.com/5720311/42690349-28dee30a-86a4-11e8-9270-1c065c33df97.png)

Normal display of drawing canvas when there is no need to update texture. There is transparency on canvas because of (only for testing and having a possibility to show the problem better) disabling material transparency.

Screenshot 2

![ss2](https://user-images.githubusercontent.com/5720311/42690360-2fb916a0-86a4-11e8-8c53-13fb9573bc01.png)

Weird mask shows on loaded mesh and on background behind the window.

Screenshot 3

![ss3](https://user-images.githubusercontent.com/5720311/42690374-39df4d34-86a4-11e8-91ed-970b42aa13e5.png)

Mask shows on drawing palette mesh.

Screenshot 4, 5, 6

![ss4](https://user-images.githubusercontent.com/5720311/42690378-413a6afa-86a4-11e8-9310-c410fcb33da6.png)
![ss5](https://user-images.githubusercontent.com/5720311/42690381-440a1280-86a4-11e8-96b6-fe70dea8837b.png)
![ss6](https://user-images.githubusercontent.com/5720311/42690383-465de084-86a4-11e8-8287-2baf89e84229.png)

Shows the mask and how it follows head movement.

Pieces of class #1 which creates meshes and materials. 

```
        const canvasGeometry = new THREE.PlaneBufferGeometry(this.canvasDimensions.w, this.canvasDimensions.h);
        this.canvas = new THREE.Mesh(canvasGeometry,
            new THREE.MeshBasicMaterial({side: THREE.FrontSide, transparent: false}) //normally transparent value is true, but false shows how "mask" looks like
        );
        this.canvas.position.x = this.canvasDimensions.w / 2;
        this.canvas.name = 'drawing palette';
        this.add(this.canvas);

        this.canvasBackground = new THREE.Mesh(canvasGeometry,
            new THREE.MeshBasicMaterial({side: THREE.FrontSide})
        );
        this.canvasBackground.position.x = this.canvasDimensions.w / 2;
        this.canvasBackground.name = 'drawing palette background';
        this.add(this.canvasBackground);
```
		
Pieces of class #2 which handles drawing with HTML canvas part. 

 ```
        this._canvas = document.createElement('canvas');
        this._canvasContext = this._canvas.getContext('2d');
	///	
        this.canvasTexture = new THREE.Texture(this._canvas);
        this.canvasTexture.needsUpdate = true;
        this.paletteMesh.material.map = this.canvasTexture;
        this.paletteMesh.material.needsUpdate = true;
	///
		drawHand() {
			this._canvasContext.beginPath();
			if (!this.buttonDownThisFrame) {
				this._canvasContext.moveTo(this.previousFrameDrawPosition.x, this.previousFrameDrawPosition.y);
			}
			this._canvasContext.lineTo(this.thisFrameDrawPosition.x, this.thisFrameDrawPosition.y);
			this._canvasContext.stroke();
			this._canvasContext.arc(this.thisFrameDrawPosition.x, this.thisFrameDrawPosition.y, this.brush.getSize() / 2, 0, 2 * Math.PI);
			this._canvasContext.fill();
			this._canvasContext.closePath();

			this.canvasTexture.needsUpdate = true; // when this flag is set to true (when button is down) "mask" appears
		} 
```

##### Three.js version

- [ ] Dev
- [x] r94 (and previous)
- [ ] ... 

##### Browser

- [ ] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [x] Occulus browser

##### OS

- [ ] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS
- [x] Samsung Gear
- [x] Occulus GO

##### Hardware Requirements (graphics card, VR Device, ...)
- Samsung Gear
- Occulus GO

**Comment by Mugen87** [comment] 2018-07-15 08:15
As long as you can't demonstrate the bug in a small and complete live example/test case, it will be hard to investigate the issue.

**Comment by siner77** [comment] 2018-07-20 15:00
Apologies for the delay, I've been working on a live example for you.

Ok, I've been able to cut the drawing module and reproduce bug on a really small piece of code. At the beginning I couldn't break it, but finally I achieved that and now I can send you a live example with a link to the source files. 

But when I was preparing this example for you, I found out something else, which is, that this bug only occurs when I change the html canvas (which I'm using to draw) dimensions. 

The example has some meshes in front of the camera (to show how the "mask" works). On the left there is a plane on which you can draw without the bug. But on the right side there is another plane with a canvas where dimensions of the canvas are changed, and the problem is visible.

Working exmaple: 
http://vrlite.lucas-studios.com/draw_test/

Source in .zip:
http://vrlite.lucas-studios.com/draw_test/drawingExample.zip

**Comment by Mugen87** [comment] 2018-07-20 16:55
I'll have a look at it. Thanks for preparing the demo!

**Comment by Mugen87** [comment] 2018-07-20 18:03
I've debugged your app but I could not find the problem. A few things I noticed:

You have statements in your code which are not necessary or wrong. I don't understand why you set...
- `WebGLRenderer.sortObjects` to `false`,
- `WebGLRenderer.localClippingEnabled` to `true`,
- the `alpha` parameter of `WebGLRenderer` to `true`
- the `preserveDrawingBuffer` parameter of `WebGLRenderer` to `true`

Besides, I've tested with Google Daydream and the 3D effect looks wrong (like the left and right eye are not in sync). The official `three.js` examples don't have this visual problem https://threejs.org/examples/?q=webvr. BTW: Both planes are black and I'm not able to draw anything.

The problem is that your provided example is still too complex. You have to provide a more simple test case without any node modules and 3rd party libraries. Just use the classes of the`three.js` repo.

**Comment by siner77** [comment] 2018-07-23 07:03
I have used those renderer settings, because that is what I need in whole application (drawing is only one of modules, but I was able to reporduce this bug on smaller version where there is only a drawing part) and I wanted it to be as close to my app as possible.
I have not tested it on Daydream (probably you could not test it because daydream gamepad button maybe be not supported, I will check it/add it). As I marked in issue I have been using Occulus Go and Samsung Gear where OS/Browser are probably the same. 
I will try to modify exmaple (but still OG/Gear may be needed) and I will inform you. 
Still thanks for looking into it.

**Comment by siner77** [comment] 2018-07-23 11:02
Ok I tried to make it a little bit smaller. I have tested it on Daydream and bug does not appear. So as I expected, it is only on GearVR/OcculusGO. 
Working exmaple:
http://vrlite.lucas-studios.com/draw_test/
Source in .zip:
http://vrlite.lucas-studios.com/draw_test/draw_test.zip

**Comment by Mugen87** [comment] 2018-07-23 18:17
Sry, I don't have this device so I can't make a test.

**Comment by Mugen87** [comment] 2018-07-24 13:37
Closing for now. We can reopen if you can proof it's a bug in `three.js`.

**Closed by Mugen87** 2018-07-24 13:37 UTC
Labels: Device Issue

**Comment by mrdoob** [comment] 2018-07-24 20:08
FYI @DigiTec

**Comment by paullaffitte** [comment] 2019-11-28 06:53
I have a bug with Oculus Browser (6.2.11.181027543) on Oculus Go too. The sentence "Updating textures in VR causes weird objects to appear", exactly describe my problem. The issue doesn't seems to happens on Gear VR.

I was developing a GUI for a VR video player, using a canvas to draw it and then using it as a texture.

I made a [demo](https://jsfiddle.net/082u61qb/2/) available on jsfiddle with a checkbox to enable or disable the bug. The bug happening when the version of a video texture is updated by the function .update(). Then, during the frame where the texture is updated, the second object in my scene seems to generate some masks over the first object with the video texture. The demo is 88 lines long, including the html, so I think it will be pretty easy to debug.

Here are some screenshots for who doesn't want to try the demo :

- When the update method is called (I used a green background, that's why you can see green rectangles)
![Screenshot from 2019-11-28 13-47-13](https://user-images.githubusercontent.com/23403270/69783283-cba51c80-11e5-11ea-842f-84ae77a25cc6.png)

- When I replace the update method by another one doing nothing (the video texture is thus not updating and the video is freezed)
![Screenshot from 2019-11-28 13-47-26](https://user-images.githubusercontent.com/23403270/69783284-cba51c80-11e5-11ea-83c4-b39a4e46b009.png)

**Comment by mrdoob** [comment] 2019-11-29 02:54
> I also have a bug with Oculus Browser (6.2.11.181027543) on Oculus Go. The sentence "Updating textures in VR causes weird objects to appear", exactly describe my problem. The issue doesn't seems to happens on Gear VR.

You should probably report the bug to Oculus.
