### ISSUE TITLE
Marching Cubes - Weird Grid Stretching

### ISSUE THREAD

**Issue by jxm-math** [mrdoob/three.js#14060] opened 2018-05-14 14:41 UTC
##### Description of the problem

An applet using Marching Cubes library renders differently in different computers / browsers. The code for the applet is located in https://cdn.rawgit.com/TungstenHub/tngt-threejs/master/scripts/quadrics.html and a StackExchange question https://stackoverflow.com/questions/50304079/marching-cubes-for-quadrics-three-js/50322344 shows **two different behaviours on the same applet**, both having a GIF exposing the rendered result.

The answer of the SE question reports the right behavior of Marching Cubes, showing accurate parameter-dependent quadrics.

The question reports an anomaly in which the base grid gets strangely stretched and the surfaces linearly distorted. This effect has been observed many times after clearing all browsing cache, both in Chrome and Firefox Quantum. 

If more people open the applet above, perhaps some report the same strange behavior and the cause may be detected.

##### Three.js version

- [ ] Dev
- [x] r92
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [x] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [ ] macOS
- [x] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)
-

**Comment by WestLangley** [comment] 2018-05-14 17:17
Sorry, this is not a help site. Please do not cross-post help question here.

**Comment by jxm-math** [comment] 2018-05-14 19:08
@WestLangley The issue has come up from a SE question, but I have posted it here as a **potential bug: the same MarchingCubes snippet works differently in different devices**. In any case, I'm sorry for the inconvenience if the issue does not match the purpose of this channel.

**Comment by WestLangley** [comment] 2018-05-14 19:32
@jxm-math I understand. Unfortunately, plenty of users post here when there is a "potential bug". However, if you can _demonstrate_ a three.js bug, then that is a different matter. Thank you for understanding.

**Comment by Mugen87** [comment] 2018-05-14 21:05
I can actually confirm the problem. The following application behaves inconsistent in Chrome and Safari.

https://cdn.rawgit.com/TungstenHub/tngt-threejs/master/scripts/quadrics.html

The visual outcome is different when e.g the value of parameter `a11` is increased. In Chrome, the sphere becomes wide. The sphere in Safari gets tighter.

Safari (correct):
![image](https://user-images.githubusercontent.com/12612165/40023265-c9a51efc-57ca-11e8-9120-f8d8fdb4906f.png)

Chrome (wrong):
![image](https://user-images.githubusercontent.com/12612165/40023298-e2b51b90-57ca-11e8-93ef-ce373b06ac99.png)

@jxm-math This is the problem you've mentioned in stackoverflow, right?

**Comment by jxm-math** [comment] 2018-05-15 07:07
@Mugen87 Exactly! Thank you very much

**Comment by Mugen87** [comment] 2018-05-15 10:03
I've exported the fields data in Safari in the following file. Can you please verify if you have the same data in your browser? You can use this fiddle to export your data: https://jsfiddle.net/srq6qt2z/5/

Maybe there is a problem in the way, you generate these data in your application. 

[data_safari.txt](https://github.com/mrdoob/three.js/files/2004334/data_safari.txt)

**Comment by Mugen87** [comment] 2018-05-15 10:30
I'm afraid you've used an old fiddle. Can you make a test again with https://jsfiddle.net/srq6qt2z/7/

Parameter `a11` should have a value of 3.

**Comment by jxm-math** [comment] 2018-05-15 10:38
I think the previous test was done with the newest fiddle, but I'm not sure. Versions 1 and 2 seem the same

[data-chrome2.txt](https://github.com/mrdoob/three.js/files/2004443/data-chrome2.txt)

**Comment by Mugen87** [comment] 2018-05-15 10:42
Sry, I was the one with the wrong fiddle 😅. These are the data with the correct parametrization. 
[data_safari.txt](https://github.com/mrdoob/three.js/files/2004457/data_safari.txt)

It looks like the values are identical.

**Comment by Mugen87** [comment] 2018-05-15 11:02
I don't know why but your demo also works on Firefox. Seems to be a browser issue...

**Comment by Mugen87** [comment] 2018-05-15 11:15
If i turn of flat shading, it seems to work: https://jsfiddle.net/f2Lommf5/6249/

**Comment by Mugen87** [comment] 2018-09-05 14:30
I'm unable to reproduce the problem in Chrome 69. Closing.

**Closed by Mugen87** 2018-09-05 14:30 UTC
Labels: Browser Issue
