### ISSUE TITLE
iOS 17 safari on iPhone 15 pro: blank white canvas and "context lost" in console over and over

### ISSUE THREAD

**Issue by yspreen** [mrdoob/three.js#26829] opened 2023-09-24 06:08 UTC
### Description

I have a simple scene with some cannon js and three js. MeshBasicMaterial WebGLRenderer MeshPhongMaterial.

<img width="1031" alt="image" src="https://github.com/mrdoob/three.js/assets/12631527/d33ce4c0-a979-482c-9ea9-7837206ad8a0">

### Reproduction steps

iPhone 15 pro with safari?

### Code

if needed I can provide a basic example but I don't have one handy.

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/g3atw6k5/)
* [jsfiddle-dev](https://jsfiddle.net/hjqw94c5/)

### Version

0.156.1

**Comment by Mugen87** [comment] 2023-09-24 08:30
Did that already happen with iOS 16?

**Comment by yspreen** [comment] 2023-09-24 16:35
@Mugen87 I got a new phone and a new OS. I'm gonna go try some of the examples to see if those work. before on another phone on iOS 16 it was fine

**Comment by yspreen** [comment] 2023-09-24 16:36
this page is broken too https://next.junni.co.jp

**Comment by yspreen** [comment] 2023-09-24 16:39
okay I rebooted the phone, that fixed it. phew. probably just another iOS 17 issue, hopefully something that will be solved by apple

**Comment by Mugen87** [comment] 2023-09-24 18:22
Closing for now then. Thanks for reporting the issue. We'll keep an eye on the iOS 17 rollout.

**Closed by Mugen87** 2023-09-24 18:22 UTC
Labels: Device Issue

**Comment by pandamicro** [comment] 2023-09-25 04:33
> Did that already happen with iOS 16?

Might also happen with iOS 16.7, we have seen similar context lost issue

**Comment by hybridherbst** [comment] 2023-09-25 04:36
Just want to add that I’ve also seen repeated context losses over the weekend, on multiple websites and often involving “leave the page and come back”, where then the console was spammed with “context lost” every frame.

Unfortunately I haven’t found a clear repro yet…

**Comment by pandamicro** [comment] 2023-09-25 06:54
One way to increase reproduce rate is that you can lock the screen after you got some WebGL page opened, unlock after locking a while could immediately trigger context lost on some pages.

**Comment by Mugen87** [comment] 2023-09-25 08:42
> Unfortunately I haven’t found a clear repro yet… what worries me is that it happens both on Safari and Chrome.

Seems to be a WebKit related issue then. Could this be the right bug:

https://bugs.webkit.org/show_bug.cgi?id=261331

**Comment by ted-piotrowski** [comment] 2023-09-25 17:38
One workaround at this point is to use Add to Home Screen. The full screen web app appears to use a different code path that doesn't lose context.

**Comment by ajmas** [comment] 2023-11-11 02:46
> One workaround at this point is to use Add to Home Screen. The full screen web app appears to use a different code path that doesn't lose context.

This didn’t make a difference for me. 

I had opened a forum post on this issue: https://discourse.threejs.org/t/three-js-broken-on-ios-17-with-context-lost/58025

There I show it’s essentially right when we ads instanciating the render context. The output at the start of the logs:

```
[Error] WebGL: context lost.
	getContext
	getContext (chunk-HR4Q7LEE.js:17002)
	WebGLRenderer (chunk-HR4Q7LEE.js:17029)
	Module Code (mini-main.ts:2)
[Error] TypeError: null is not an object (evaluating 'gl.getShaderPrecisionFormat(gl.VERTEX_SHADER, gl.HIGH_FLOAT).precision')
	getMaxPrecision (chunk-HR4Q7LEE.js:9651)
	WebGLCapabilities (chunk-HR4Q7LEE.js:9665)
	initGLContext (chunk-HR4Q7LEE.js:17057)
	WebGLRenderer (chunk-HR4Q7LEE.js:17090)
	Module Code (mini-main.ts:2)
```

I am tempted to try out an older version and see if this is a regression from a specific version.

**Comment by ted-piotrowski** [comment] 2023-11-11 02:57
I have a non threejs project and it's the same problem. I find that restarting Safari fixes the issue but I don't know the cause.

**Comment by ajmas** [comment] 2023-11-11 20:10
I can confirm this is indeed a pure WebGL/Webkit issue, since the following code fails with a "context  lost" error:

```js
      function initWebGL () {
        const canvas = document.querySelector('#canvas');
        canvas.width = window.innerWidth;
        canvas.height = window.innerHeight;

        const glOptions = {
          // antialias: false,
          alpha: false,
          premultipliedAlpha: false
        };

       const gl = canvas.getContext('webgl2', glOptions)
          || canvas.getContext('webgl', glOptions)
          || canvas.getContext('experimental-webgl', glOptions);

      }

      initWebGL();
```

I'll open Webkit bug report and link it here.

**Comment by ajmas** [comment] 2023-11-11 20:31
Webkit ticket: https://bugs.webkit.org/show_bug.cgi?id=264684

**Comment by ajmas** [comment] 2023-11-11 20:41
Just noticed there was an OS update for iOS and iPadOS.

I confirm this is no longer an issue with iPadOS 17.1.1 or 17.1.1.

For anyone else running into this issue please check you have updated your device first (something I should have done).

**Comment by wcsdn** [comment] 2025-02-11 02:13
Is there a repair plan? We cannot require users to upgrade their devices, right

**Comment by yspreen** [comment] 2025-02-11 02:18
@wcsdn it's a webkit issue, there isn't really another solution. apple's software has been incredibly buggy these last two years
