### ISSUE TITLE
A DirectionalLight with shadow adds yellow tint on some devices (Pixel 3a)

### ISSUE THREAD

**Issue by viperphase1** [mrdoob/three.js#18410] opened 2020-01-17 04:05 UTC
As of threejs version 112 a directional light with castShadow set to true adds a yellow tint to objects on some devices including the Pixel 3a. Confirmed on the Pixel 3a using both Chrome 79 and Firefox 68.4.1.

Here's a demo of the issue (no cdn for 112 exists so you'll have to download it)
The cube should be a yellowish green. 
The yellow tint goes away if you do one of the following:
- use a previous version of threejs
- comment out 'mainLight.castShadow = true'
- skip enabling the shadowMap on the renderer.
```
<html>
<head>
<!--    <script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/110/three.min.js"></script>-->
    <script src="three.112.js"></script>
    <style>
        body {
            margin:0;
            padding:0;
        }
        #scene-container {
            width:100%;
            height:100%;
        }
    </style>
</head>
<body>
    <div id="scene-container"></div>
    <script>
        const container = document.querySelector( '#scene-container' );

        const scene = new THREE.Scene();

        scene.background = new THREE.Color( 'skyblue' );

        const mainLight  = new THREE.DirectionalLight(0xFFFFFF, Math.PI - 0.5);
        mainLight.castShadow = true;
        mainLight.position.set(0.15, 0.866, 0.35);
        scene.add( mainLight );

        const fov = 35;
        const aspect = container.clientWidth / container.clientHeight;
        const near = 0.1;
        const far = 100;

        const camera = new THREE.PerspectiveCamera( fov, aspect, near, far );
        camera.position.set( 0, 0, 10 );

        const geometry = new THREE.BoxBufferGeometry( 2, 2, 2 );

        const material = new THREE.MeshStandardMaterial();
        material.roughness = 1;
        material.metalness = 0;

        const mesh = new THREE.Mesh( geometry, material );
        scene.add( mesh );

        const renderer = new THREE.WebGLRenderer();
        renderer.shadowMap.enabled = true;
        renderer.shadowMap.type = THREE.PCFSoftShadowMap;
        renderer.setSize( container.clientWidth, container.clientHeight );
        renderer.setPixelRatio( window.devicePixelRatio );

        container.appendChild( renderer.domElement );

        renderer.render( scene, camera );
    </script>
</body>
</html>

```

**Comment by WestLangley** [comment] 2020-01-17 07:23
Duplicate of #18315.

**Closed** 2020-01-17 10:50 UTC
Labels: Duplicate

**Comment by WestLangley** [comment] 2020-01-17 16:03
@viperphase1 Thank you anyway. This issue should be resolved in the `dev` branch.
