### ISSUE TITLE
Documentation is not searchable

### ISSUE THREAD

**Issue by intrepidOlivia** [mrdoob/three.js#26264] opened 2023-06-14 18:55 UTC
### Description

The documentation does not appear to be indexed for searching; only the "main topics" are accessible through the search function (which is not useful since the same could be achieved with Ctrl-F).

### Reproduction steps

Repro steps:
1. Navigate to the documentation site https://threejs.org/docs/
2. Search for a method name that you know exists (such as `[getControllerGrip](https://threejs.org/docs/index.html#api/en/renderers/webxr/WebXRManager.getControllerGrip)`)

Expected result:
* A link appears to the searched method name

Actual result:
* Search results are blank.

### Code

```js
// code goes here
```

### Live example

https://threejs.org/docs/

### Screenshots

<img width="356" alt="Screenshot 2023-06-14 at 11 53 04 AM" src="https://github.com/mrdoob/three.js/assets/3474569/c37b03c6-c5c4-4bde-a6df-a6aa8b2cd1a7">

### Version

r153

### Device

Desktop

**Comment by Mugen87** [comment] 2023-06-14 21:39
Duplicate of #19342.

**Closed by Mugen87** 2023-06-14 21:39 UTC
