### ISSUE TITLE
FBXLoader animation bug

### ISSUE THREAD

**Issue by lilypen** [mrdoob/three.js#17787] opened 2019-10-22 06:29 UTC
##### Description of the problem
Three is a bug in FBXLoader with animation .When I run the example webgl_loader_fbx.html,only changing the Samba Dancing.fbx to man.fbx(already attched to this issue.), the animation is different from what opened in 3dmax. The right animation is that the man is walking normally.

[man.zip](https://github.com/mrdoob/three.js/files/3754016/man.zip)

##### Three.js version
 106dev

##### Browser
only tried on chrome and firefox
##### OS
windows

**Comment by looeee** [comment] 2019-10-22 06:48
Closing, as this look like it's a duplicate of #14903

@lilypen can you post your model to that thread instead please?

**Closed by looeee** 2019-10-22 06:48 UTC
