### ISSUE TITLE
Layers can directly set the layers of all child nodes

### ISSUE THREAD

**Issue by wangchao0724** [mrdoob/three.js#27623] opened 2024-01-26 08:52 UTC
### Description

When I want an object to be on a separate layer, I find that I must set the layers of all its subsets to truly take effect. Why can’t I set the current object directly, and then all its subsets can inherit this layer?

![image](https://github.com/mrdoob/three.js/assets/155077270/2b5ff351-6af0-4c9c-924b-47739aec3891)

In the figure, it can be seen that when the layer of the current object is not on the same layer as the camera, its child nodes will still be recursive, which forces me to set all its child nodes to be on another layer

### Solution

Layers can directly set the layers of all child nodes

### Alternatives

Layers can directly set the layers of all child nodes

**Comment by Mugen87** [comment] 2024-01-26 09:31
Duplicate of #18937.

**Closed by Mugen87** 2024-01-26 09:31 UTC
