### ISSUE TITLE
TransformControls: Weird rotation behavior at perpendicular view to the gizmo

### ISSUE THREAD

**Issue by Ben-Mack** [mrdoob/three.js#13806] opened 2018-04-09 02:01 UTC
Please take a look at 2 gif below compared rotation behavior of Three.js vs 3ds Max at perpendicular view to the gizmo:

Three.js weird behavior: ( [video](https://www.youtube.com/watch?v=dkw7IdblsMY) )
![3js](https://user-images.githubusercontent.com/6309393/38475721-21adc7ec-3bd4-11e8-9604-19ca0ed95ca3.gif)

3ds Max good behavior: ( [video](https://www.youtube.com/watch?v=NOlicuB6jNU) )
![max](https://user-images.githubusercontent.com/6309393/38475729-2c106eec-3bd4-11e8-8ecd-6b368b6b28cb.gif)

**Comment by calrk** [comment] 2018-04-10 01:11
Similar issue to this https://github.com/mrdoob/three.js/issues/9312, which comes up a lot. Not an easy problem to fix given how it is currently implemented.

The rotation lines creates a plane, and then raycasts from the mouse position onto that plane in to find the position of the plane and calculate a good rotation value. When you are looking at the lines at the sharp angle like this, the plane is aligned with the camera so the raycast fails to collide with it and gives the result you are seeing.

A complex solution that I tried was to make the plane it raycasts against always facing the camera, but there is a lot of complex math and use of quaternions that I couldn't spend the time trying to learn.

My simple solution was to disable the rotation axes when you are looking at them at a sharp angle like this. As the TransformControls.js are an external file and not core to the ThreeJS code, you can edit it yourself to suit your needs. [Here is my example](http://games.clarklavery.com/resource/TransformControls.js), specifically around lines 480-491 to show how I do this.

**Comment by whatisor** [comment] 2018-05-16 16:07
Well, Sketchfab already can solve it  inside Advanced rotation :(

**Comment by arodic** [comment] 2018-05-22 19:47
I am familiar with this problem since I made it and it has been brought up a few times already. Perhaps it's time to rewrite the damn thing :)

I can try to merge a fix for this particular problem from an improved version of TransformControls in a different project.

**Comment by arodic** [comment] 2018-05-25 13:46
Quick update: I'm making good progress with this issue and a few more improvements. It's about 50% done.

Question for @Ben-Mack...

It appears that for perpendicular axis manipulation, 3dsMax converts linear mouse motion to rotation. How does is deal with parallel axis (green handle in your gif)? I find radial manipulation more intuitive (tracing a full circle around manipulator should result in 360 degree rotation) but this doesent play well with linear manipulation... So how can we have both? Perhaps I can switch between the two modes based on a dot product between eye and axis... I'm curious how does Max do it?

**Comment by Ben-Mack** [comment] 2018-05-25 14:40
Thanks for working on this @arodic 

Here the video for the 3ds Max rotation: https://www.youtube.com/watch?v=6pTi0KV5vh8

**Comment by arodic** [comment] 2018-05-25 18:03
Oh I see @Ben-Mack... it looks like 3ds Max uses only linear gesture. While I find less intuitive and precise for rotating around axis facing the camera, it definitely solves the problem with perpendicular ones. I think it is important that the user is able to do a full 360 rotation with a single gesture ideally. So maybe some hybrid UX will do...

**Comment by whatisor** [comment] 2018-05-27 12:10
If I can help some things, please tell me. I really need this done.

**Comment by arodic** [comment] 2018-05-27 17:01
@whatisor you can help by testing the new implementation on my fork. Scale mode is currently broken since I'm re-implementing it to fix issues #10916, #9312, #5489 and #5379 as well.

Please report issues in this thread.

**Comment by arodic** [comment] 2018-05-27 17:13
@whatisor note that temporarily I split the controls in three files but I intend to make it one file once it is done. Also note setter functions are deprecated since I have internal setters instead.

**Comment by whatisor** [comment] 2018-05-29 11:04
@arodic 
Quick test result for "perpendicular view"
1. When we click, Object "suddenly" changes direction to match with current mouse position, then it works well

**Comment by whatisor** [comment] 2018-05-30 01:54
@arodic Confirmed it works. Thank you so much.

**Closed** 2018-07-31 05:01 UTC
Labels: Feature Request

**Comment by Mknight492** [comment] 2019-06-20 06:04
how would I get this working as an npm module?

**Comment by clibequilibrium** [comment] 2024-07-07 01:31
I think there was a regression on this issue, it's still reproducible , sorry for necroing. 

![ezgif-5-68a4fc9dfe](https://github.com/mrdoob/three.js/assets/105135724/5e8acb60-92ff-46b7-85d9-b13beebedaf0)
