### ISSUE TITLE
ObjLoader + MtlLoader not displayed correctly (multimaterial in one MTL ?)

### ISSUE THREAD

**Issue by Aikyos** [mrdoob/three.js#12597] opened 2017-11-07 08:24 UTC
Hi,
I link to you my obj and my MTL i want to import in my code like this : 
```javascript   
var mtlLoader = new THREE.MTLLoader();

mtlLoader.setPath('models/');

mtlLoader.load( 'citadine2.mtl', function( materials ) {

    materials.preload();

    var loader = new THREE.OBJLoader( manager );

    loader.setMaterials( materials );

    loader.setPath('models/');

    loader.load( 'citadine2.obj', function ( object ) {

        object.name="citadine2";

        scene.add( object );

    }, onProgress, onError );

});
```

But the best i can got it's that : 
![1](https://user-images.githubusercontent.com/6474357/32483418-4e37e118-c39c-11e7-9b87-b42161403db7.jpg)

And what i want its this : I got this with import my both files to http://3dviewer.net/.
![2](https://user-images.githubusercontent.com/6474357/32483422-5200d3d6-c39c-11e7-9020-68f425fdb2e7.jpg)

It seems Objloader can't have a mtl with multimaterials.

See my files : 

[models.zip](https://github.com/mrdoob/three.js/files/1449168/models.zip)

Can you tell me what i am doing wrong  please ?

Thank you & sorry for my bad english.

##### Three.js version

- [X] Dev
- [X] r87
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment] 2017-11-07 11:58
I can confirm that both `OBJLoader` and `OBJLoader2` display the model in a wrong way. Sketchfab can handle the `obj` and `mtl` files correctly.

![image](https://user-images.githubusercontent.com/12612165/32492576-1dd5449c-c3bb-11e7-9253-5dd526de5d41.png)

> It seems Objloader can't have a mtl with multimaterials.

No, this should actually be supported.

\cc @kaisalmen

**Comment by kaisalmen** [comment] 2017-11-07 21:59
`OBJLoader2` with ambient lighting at 0xFFFFFF looks like this:
![image](https://user-images.githubusercontent.com/21079138/32519998-d35ed4a6-c40e-11e7-86a9-3154712434c1.png)
It seems to be an issue with double side or transparent materials. Need to find out if `MTLLoader` already creates materials with wrong properties. Will investigate....

**Comment by Aikyos** [comment] 2017-11-08 08:42
Thank you guys.

**Comment by kaisalmen** [comment] 2017-11-09 21:59
@Aikyos @Mugen87 with enforced two sided materials and VertexNormalHelpers active for the complete mesh you can see that the surface orientation of the windshield is not correct:
![image](https://user-images.githubusercontent.com/21079138/32630986-f0ffb4f8-c59e-11e7-97d6-3166f05cb72b.png)

Only looking at mesh "VitreAV_Plane.043" without double side material enforced and VertexHelper in place you can see that the normal orientation is wrong:
![image](https://user-images.githubusercontent.com/21079138/32631433-87d26424-c5a0-11e7-9130-8ac9b8ebed2e.png)

Status:
Done:
- `OBJLoader2` processes everything correct. 
- http://3dviewer.net/ seems to enforce DoubleSide

Todo:
- Test `OBJLoader` considering what is now known

**Comment by kaisalmen** [comment] 2017-11-11 22:15
On the branch above I modified one obj and one obj2 example for demonstration purposes. The obj and mtl files are contained, but are not foreseen to be contained in a potential merge request.
I commented the maps in the mtl file, otherwise the materials look odd (potential `MTLLoader` improvement needed here?).
Example `OBJLoader + MTLLoader` makes all materials `THREE.DoubleSide` and it now uses TrackballControlls to ease navigation. Example `OBJLoader2 usage options` lets you switch the sie modes. 

`OBJLoader` seems to have a problem with some meshes/materials as the bottom of the car is missing
![image](https://user-images.githubusercontent.com/21079138/32693888-1556194c-c733-11e7-9704-6fd65983729a.png)

`OBJLoader2` seems to behave correctly.

**Comment by kaisalmen** [comment] 2017-11-19 22:08
I will continue to investigate. I just didn't have the time to work on it.

**Comment by Aikyos** [comment] 2017-11-20 13:34
No problem, you help is welcome. Don't worry about the time.

**Comment by mrdoob** [comment] 2018-02-07 02:36
@kaisalmen any luck?

**Comment by kaisalmen** [comment] 2018-02-07 06:07
I almost forgot about it, but this is next on my list. All other issues and enhancements are done or PRs are under review.

**Comment by kaisalmen** [comment] 2018-02-09 22:36
@mrdoob This is a nasty one and not easy to fix. `OBJLoader` assumes that `f` (and there are four sub-types), `l` and `p` don't intermix before new vertices/groups/objects are declared, but this is exactly happening, see lines 32864-32873 from citadine2.obj:
```console
f 8896/8775/7361 8094/8777/7363 8093/9207/7525 8092/9205/7182
f 8094/8777/7363 8091/8778/7364 8918/9206/7524 8093/9207/7525
l 9003 9010
l 9004 9008
l 9006 9011
l 9007 9009
l 9008 9002
l 9009 9005
o BrakeLight_Plane.015
v 0.059668 1.137745 1.244512
```
The spec does not forbid it, so it can occur and it does. I just made `OBJLoader2` resilient to it lately and that is what the open PR mostly about. I wasn't aware until now though that it is exactly the same issue here. A recent bugfix repaired line rendering in `ObjLoader`. It applies the complete Line material to all read faces and lines as it does not start a new mesh internally:
![image](https://user-images.githubusercontent.com/21079138/36052998-3a60c15c-0df0-11e8-9832-a4ea5b37b20e.png)

It is the same reason why the verify from #13156 looks like this (top is `OBJLoader2`, bottom is `OBJLoader`):
![image](https://user-images.githubusercontent.com/21079138/36053212-154667d6-0df1-11e8-8a25-cb8f8bef7aea.png)
The three missing cubes are described with different face-types.

The fix for `OBJLoader2` took a couple of hours and that code I know better. For `OBJLoader` it is likely more complicated as we need to rethink the way meshes are detected.

**Comment by mrdoob** [comment] 2018-02-10 00:04
Oh man, that sounds like a nightmare... Glad to hear that #13156 fixes this.
Thanks for doing all the investigation and for the verify file. Super helpful!

**Comment by kaisalmen** [comment] 2018-02-10 20:48
`OBJLoader2` stores which face type is active (all four `f` types, `l` and `p`) and creates a new mesh every time the face type changes in the OBJ file or in case `g` is declared. But, if for example the same `f` type is interrupted by `v` definitions used again only a new mesh is created when a new `g` is declared.

**Comment by mrdoob** [comment] 2018-02-27 05:06
As far as I understand `OBJLoader2` should be able to load this file correctly. Closing...

**Closed by mrdoob** 2018-02-27 05:06 UTC
