### ISSUE TITLE
Import GLB exception

### ISSUE THREAD

**Issue by alekcac** [mrdoob/three.js#25429] opened 2023-02-03 18:14 UTC
### Description

It looks like that the latest three.js version does not work with gltf/glb models that have mesh nodes inherited from nodes in the joints list.

### Reproduction steps

1. Link to the file to reproduce: https://drive.google.com/file/d/1F5IG-WUQda0ahrBQB3ToFTifQ5x4zmoG
2. Looks like the issue is in the recent versions of the three.js gltf loader (r149). [glTF-Validator](https://github.khronos.org/glTF-Validator/) indicates minor issues with the model, blender also was able to import it and render.
I did not non perform a detailed investigation of gltf loader sources, but I have tried to import the model with the previous versions of three.js and found out that r147 works

### Code

```js
// code goes here
```

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/g3atw6k5/)
* [jsfiddle-dev](https://jsfiddle.net/hjqw94c5/)

### Screenshots

<img width="904" alt="Screenshot 2023-02-03 at 22 07 01" src="https://user-images.githubusercontent.com/1832042/216675645-4d913f2f-6f01-411d-a8c3-561af3119d09.png">

### Version

r149

### Device

Desktop

### Browser

Chrome, Safari

### OS

Windows, MacOS

**Comment by donmccurdy** [comment] 2023-02-03 18:18
Hi, sorry for the trouble! This will be fixed on next release.

- https://github.com/mrdoob/three.js/issues/25332
- https://github.com/mrdoob/three.js/pull/25377

**Closed by donmccurdy** 2023-02-03 18:18 UTC

**Comment by takahirox** [comment] 2023-02-03 19:11
I'm happy if you test on the dev branch to check if the problem is actually resolved with your assets, just in case.
