### ISSUE TITLE
BasisTextureLoader & ShaderPass issue

### ISSUE THREAD

**Issue by Horsetopus** [mrdoob/three.js#18719] opened 2020-02-24 13:13 UTC
##### Description of the problem

When using BasisTextureLoaded with a ShaderPass, the texture will only be used properly if the uniform value is set after the instantiation of the ShaderPass.

> let shaderPass = new ShaderPass( {
> 
>     vertexShader:   vertexShader,
>     fragmentShader:  fragmentShader,
>     uniforms: {
>       'tDiffuse': { value: null },
>       'tTexture': { value: texture }
>     }
> } );
> 
> //Will only work if you add this line.
> shaderPass.uniforms[ "tTexture" ].value = texture;

Without this line, the texture2D( tTexture, vUv) will be return vec4( 0., 0., 0., 0. )

I couldn't create a fiddle.
I don't know it it's due to webworkers or to webassembly, or some path issues, but it was a mess.
So I created a github repository.
https://github.com/Horsetopus/threejs-basistexturelaoder-shaderpass-issue

##### Three.js version

- [ ] Dev
- [x] r113
- [ ] ...

##### Browser

- [x] Chrome
- [x] Firefox
- [x] Edge
- Internet Explorer ? just won't work.

##### OS

- [ ] All of them
- [x] Windows
- [?] macOS
- [?] Linux
- [?] Android
- [?] iOS

**Comment by Mugen87** [comment] 2020-02-24 13:27
Duplicate of https://github.com/mrdoob/three.js/issues/6841.

`ShaderPass` internally clones uniforms via `UniformsUtils.clone()`. Hence, it's necessary to set uniforms after the instance of `ShaderPass` was created.

**Closed by Mugen87** 2020-02-24 13:27 UTC

**Comment by Horsetopus** [comment] 2020-02-24 16:31
I see...
I lost quite some time on this one, I can't be the only one.
May I suggest a warning message at runtime if it can be detected? In the constructor of ShaderPass for example?
Or maybe somewhere in the documentation, here:
https://threejs.org/docs/#manual/en/introduction/How-to-use-post-processing
Or in a new page for shaderpass?

**Comment by Mugen87** [comment] 2020-02-24 16:33
It's not necessarily a thing of `ShaderPass`. I vote to add a note to the `UniformsUtils` page which is quite empty yet.

https://threejs.org/docs/#api/en/renderers/shaders/UniformsUtils
