### ISSUE TITLE
Uniform modelViewProjection

### ISSUE THREAD

**Issue by jjxtra** [mrdoob/three.js#17023] opened 2019-07-12 22:40 UTC
##### Description of the problem
Feature request: Add `modelViewProjection` matrix to all shaders as a global uniform. Right now every vertex shader I see using three js has to do a `projectionMatrix * modelViewMatrix` in order to get the object to clip position.

The multiplication should be able to be done on the CPU in something like a onPreRender callback and sent down to the shader as a `mat4 modelViewProjection` uniform. This saves a matrix multiply in the vertex shader. The clip position can then be computed via `modelViewProjection * objPosition`.

##### Three.js version
- [x] r106

##### Browser
- [x] All of them

##### OS
- [x] All of them

**Comment by WestLangley** [comment] 2019-07-12 23:35
Duplicate of #5974.

But probably a better answer is the built-in shaders pass the intermediate value as varying:

```glsl
vViewPosition = - mvPosition.xyz;
```

**Closed** 2019-07-13 13:12 UTC
Labels: Duplicate

**Comment by jjxtra** [comment] 2019-07-13 15:26
For anyone curious how to do this:

```
	mesh.onBeforeRender = function (renderer, scene, camera, geometry, material, group)
	{
		// provide modelViewProjection to line shader, this eliminates one matrix multiply
		material.uniforms.modelViewProjection.value.multiplyMatrices(camera.projectionMatrix, camera.matrixWorldInverse); 
		material.uniforms.modelViewProjection.value.multiply(mesh.matrixWorld);
	};
```

Regarding concerns of max uniforms, I would expect uniforms to be compiled out if unused in the shader, so it's ok to define lots of them as long as they aren't referenced. Could be wrong I suppose...
