### ISSUE TITLE
the polygonOffset do not work if the render logarithmicDepthBuffer is on

### ISSUE THREAD

**Issue by woolpeeker** [mrdoob/three.js#19551] opened 2020-06-04 02:49 UTC
##### Bug report
I find that the polygonOffset do not work if turn logarithmicDepthBuffer on.

I have a model which contains several totally overlapped mesh surface. And I try to use `logarithmicDepthBuffer = true ` to solve it, but no lucky. And I try to use polygonOffset, but it only works when `logarithmicDepthBuffer = false`. 

Is it a bug or just the feature of webglrender?
##### Three.js version
r117
##### Browser
Firefox
##### OS
Server: Ubuntu 18.04.4 LTS
Client: Windows 10

**Comment by Mugen87** [comment] 2020-06-04 08:20
Duplicate of #18807.

**Closed by Mugen87** 2020-06-04 08:20 UTC
