### ISSUE TITLE
10x shader compilation time regression from r132 to r133 (Windows)

### ISSUE THREAD

**Issue by toji** [mrdoob/three.js#22758] opened 2021-10-29 18:45 UTC
**Describe the bug**

This appears to be the core issue behind https://github.com/google/model-viewer/issues/2915

It seems that something about a recent materials change has caused shader compilation on my PC to take ~10x(!) longer than it used to. If I were to guess at why I'd say that it's probably the DirectX shader compiler hitting a pathological case that wasn't there before and trying to do an insane loop unroll or something of that nature.

**To Reproduce**

1. git checkout r132
2. Open examples/webgl_animation_keyframes.html
3. Observe load time
4. git checkout r133
5. Refresh examples/webgl_animation_keyframes.html
6. Observe (much longer) load time

With r132 I get the following recording from the performance tab in Chrome dev tools (though it's worth noting the same regression is also observable when using Firefox):

<img width="884" alt="Screenshot 2021-10-29 113147" src="https://user-images.githubusercontent.com/805273/139484874-de26dba4-16ab-4794-bd41-9c9b328d0201.png">

You can see that the largest block of work on the main thread takes ~500ms. It bottoms out at a bunch of getProgramInfoLog calls and a couple of texImage2D calls that all take about 20-50ms.

With r133 the recording looks significantly different. There are multiple calls to getProgramInfoLog that take ~150ms each and one particularly long one that takes 3+ seconds! In total, the block of work that represents to model's upload to the GPU takes nearly 5 seconds to complete, a 10x increase between versions (and consistent with what <model-viewer> was seeing.)

<img width="884" alt="Screenshot 2021-10-29 113654" src="https://user-images.githubusercontent.com/805273/139485848-3c228c54-2038-4cc2-bf63-b5834814e413.png">

**Platform:**

 - Device: Desktop, Intel Core i7-10700K, Nvidia GTX 1660 Super
 - OS: Windows 11
 - Browser: Chrome Canary 97.0.4685.2, Firefox Nightly 95.0a1
 - Three.js version: r133

**Comment by elalish** [comment] 2021-10-29 18:50
Indeed, I'm doing  a roll-back of model-viewer v1.9 right now because of this regression. Thanks @toji for the detailed repro!

**Comment by Mugen87** [comment] 2021-10-29 18:56
It seems this is a duplicate of #22631.

**Comment by Mugen87** [comment] 2021-10-29 18:57
Would be great if you could bump: https://bugs.chromium.org/p/chromium/issues/detail?id=1256340

**Comment by elalish** [comment] 2021-10-29 18:57
I don't believe that's true, as r134 has the same behavior as r133 here. Unless that issue  hasn't been completely fixed yet?

**Comment by toji** [comment] 2021-10-29 18:59
Is it? While the end result seems similar that one seemed to focus on stalls when uploading textures, while this issue is pretty clearly showing that stalls are coming from program compilation.

**Comment by Mugen87** [comment] 2021-10-29 19:01
> I don't believe that's true, as r134 has the same behavior as r133 here. Unless that issue hasn't been completely fixed yet?

No, it isn't. The issue has been closed because it needs to be fixed on the browser side.

The only option to fix this in `three` would be to revert the `SRGB8_ALPHA8` and accept wrong colors due to wrong texture filtering again (on all platforms).

> While the end result seems similar that one seemed to focus on stalls when uploading textures, while this issue is pretty clearly showing that stalls are coming from program compilation.

If the regression disappears by using `WebGL1Renderer`, `SRGB8_ALPHA8` is the problem.

**Comment by toji** [comment] 2021-10-29 19:04
Ah, I see that this IS a very direct duplicate of #22700, and in that thread they do point out that removing `sRGBEncoding` resolves the issue.

I'm not sure why that would be showing up in `getProgramInfoLog()` either. Does setting `sRGBEncoding` cause any shader changes?

**Comment by Mugen87** [comment] 2021-10-29 19:08
> Does setting sRGBEncoding cause any shader changes?

When loading an asset via `GLTFLoader` then no. The encoding is defined _before_ the first shader compilation happens so there should not be an overhead in that regard.

**Comment by elalish** [comment] 2021-10-29 19:12
Yeah, and we remove the `getProgramInfoLog()` calls by setting `checkShaderErrors = false`, in which case it just seem to be the next gl call that gets hammered. Really wish Chrome's profiler somehow made it clearer where time was actually being spent.

**Comment by toji** [comment] 2021-10-29 19:19
Confirmed this against webgl_animation_keyframes.html. If I go into r133's code and change WebGLTextures.js:169 from

```js
if ( glType === _gl.UNSIGNED_BYTE ) internalFormat = ( encoding === sRGBEncoding ) ? _gl.SRGB8_ALPHA8 : _gl.RGBA8;
```

to simply 

```js
if ( glType === _gl.UNSIGNED_BYTE ) internalFormat = _gl.RGBA8;
```

Then load times are instantly better (though the scene is predictably washed out.)  Which... is straight up baffling to me, honestly. 😵

**Comment by Mugen87** [comment] 2021-10-29 20:42
Disabling `SRGB8_ALPHA8` in the engine should look like so: #22759

Changing `WebGLTextures` is one part of the solution. We also have to ensure that the engine does not inject the inline GLSL decode and `PMREMGenerator` does not use `SRGB8_ALPHA8` as well.

**Comment by toji** [comment] 2021-10-29 21:41
Hold on, think I've found something: Do you have any sense of how difficult it would be to make use of texStorage2D in this scenario? (WebGL2 only) I have an early indication that may be a workaround for the performance hit here. (And should be a best practice all around.)

**Comment by toji** [comment] 2021-10-29 22:02
Left a comment on #22631 with more of my findings.

**Comment by Mugen87** [comment] 2021-10-30 08:36
> Do you have any sense of how difficult it would be to make use of texStorage2D in this scenario? 

Related issue: #21874

One reason I did not focus on the issue yet is https://github.com/mrdoob/three.js/issues/21874#issuecomment-859398117 and the fact that is requires a bit of refactoring in `WebGLTextures`.

When I remember correctly you must now in advance the number of mips for a texture whereas with `texImage2D()` you don't have to. If we want to use `texStorage2D()` I guess we need the result of the following computation before making the WebGL call. 
```js
Math.log2( Math.max( width, height, depth ) )
```

**Comment by Mugen87** [comment] 2021-10-30 08:38
TBH, I always fear refactorings in `WebGLTextures` a bit because of the many code paths and the respective complexity. 

For a quick fix of this issue I would rather merge #22759 and plan more time for the introduction of `texStorage2D()`.

**Comment by hybridherbst** [comment] 2021-11-05 14:53
The file in https://github.com/mrdoob/three.js/issues/22785 (closed as duplicate of this issue) exhibits slowdowns way beyond the 10x mark (going from "loads immediately" to "loads never and makes the entire browser unresponsive").

**Comment by mrdoob** [comment] 2021-11-05 19:40
Probably best to wait a few weeks on https://bugs.chromium.org/p/chromium/issues/detail?id=1256340 but sounds like the best solution for this would be to disable `SRGB8_ALPHA8` (#22759) and try again in a few months.

**Comment by Mugen87** [comment] 2021-11-05 19:47
That sounds like the best solution to me, too!

**Comment by Mugen87** [comment] 2021-11-10 08:56
Since #22759 has been merged, the performance regression should disappear with `r134`.

**Closed by Mugen87** 2021-11-10 08:56 UTC
Labels: Browser Issue, Regression
