### ISSUE TITLE
VAO Test  ~5000ms from 1500ms with latest THREE r126 regression to r117.1

### ISSUE THREAD

**Issue by arpu** [mrdoob/three.js#21503] opened 2021-03-23 15:32 UTC
**Describe the bug**

VAO Test  ~5000ms from 1500ms with latest THREE r126 regression to r117.1

Test from https://github.com/mrdoob/three.js/pull/16287
**To Reproduce**

https://jsfiddle.net/s4vwgm2x/ (`r126.1`)
https://jsfiddle.net/s4vwgm2x/1/ (`r117.1`)

**Expected behavior**

<1500ms withVAO 

**Screenshots**
![Bildschirmfoto von 2021-03-23 15-49-42](https://user-images.githubusercontent.com/14173/112172190-c8148080-8bf4-11eb-9751-fd34bccf1cbc.png)
![Bildschirmfoto von 2021-03-23 16-31-49](https://user-images.githubusercontent.com/14173/112172785-4bce6d00-8bf5-11eb-9510-363e1ace73fb.png)

**Platform:**

 - Device: [Desktop]
 - OS: [ Linux]
 - Browser: [Chrome]
 - Three.js version: [r126.1]

**Comment by Mugen87** [comment] 2021-03-23 15:56
`r126.1`: 

![image](https://user-images.githubusercontent.com/12612165/112176699-9dc4c200-8bf8-11eb-8feb-d3acf8bd53cf.png)


`r117.1`:

![image](https://user-images.githubusercontent.com/12612165/112176552-7a017c00-8bf8-11eb-8c0a-d976b07a0066.png)

I'm unable to reproduce on my system. iMac (10.15.7), Chrome 89.0.4389.90, AMD Radeon R9 M295X 4 GB.

**Comment by Mugen87** [comment] 2021-03-23 15:59
@arpu Please make more tests on other systems before you report a performance regression.

**Comment by Mugen87** [comment] 2021-03-23 16:13
On my Pixel 4a, `r126.1` has a way better performance than `r117.1` ( 2200ms vs 3100ms).

**Comment by mrdoob** [comment] 2021-03-23 16:36
On MacBook Air M1 `r126.1` gives ~1330 and `r117.1` gives ~1460.

**Comment by mrdoob** [comment] 2021-03-23 16:39
> Device: [Desktop]
OS: [ Linux]

I'm surprised that a Linux user gives so little information about their system.
Linux distro and GPU driver/version should be a must.

**Comment by arpu** [comment] 2021-03-23 16:51
thx for testing. 
looks more a problem with linux/wayland and amd GPU 
same result on Firefox/chrome stable and chrome dev 

AMD® Radeon (tm) rx 460 graphics
Google Chrome | 89.0.4389.90 (Offizieller Build) (64-Bit)

cannot provide more test on different systems ( only have this one)

**Comment by Mugen87** [comment] 2021-03-23 16:57
Closing for now then. Seems to be a problem on your system.

**Closed by Mugen87** 2021-03-23 16:57 UTC

**Comment by arpu** [comment] 2021-03-23 17:26
sorry to inform you this Regression, is on a more widely used System too.
r117.1
![r117 1](https://user-images.githubusercontent.com/14173/112190279-221d4200-8c05-11eb-8928-d3b5d857f7fe.PNG)
r126.1
![r126 1](https://user-images.githubusercontent.com/14173/112190303-28132300-8c05-11eb-8e17-46bac68ff320.PNG)

```

Initialization time | 305
-- | --
In-process GPU | false
Passthrough Command Decoder | true
Sandboxed | true
GPU0 | VENDOR= 0x1002, DEVICE=0x67ef, SUBSYS=0x16451642, REV=197, LUID={0,39049} *ACTIVE*
GPU1 | VENDOR= 0x1414, DEVICE=0x008c, LUID={0,42057}
Optimus | false
AMD switchable | false
Desktop compositing | Aero Glass
Direct composition | true
Supports overlays | false
YUY2 overlay support | NONE
NV12 overlay support | NONE
BGRA8 overlay support | NONE
RGB10A2 overlay support | NONE
Diagonal Monitor Size of \\.\DISPLAY1 | 23.7"
Driver D3D12 feature level | D3D 12.0
Driver Vulkan API version | Vulkan API 1.2.0
Driver vendor | ANGLE
Driver version | 27.20.14501.18003
GPU CUDA compute capability major version | 0
Pixel shader version | 5.0
Vertex shader version | 5.0
Max. MSAA samples | 8
Machine model name |  
Machine model version |  
GL_VENDOR | Google Inc.
GL_RENDERER | ANGLE (Radeon(TM) RX 460 Graphics Direct3D11 vs_5_0 ps_5_0)
GL_VERSION | OpenGL ES 2.0.0 (ANGLE 2.1.14675 git hash: f25a0b5b404b)

````

**Comment by mrdoob** [comment] 2021-03-23 17:30
Sorry. We can't revert that change at this point.
It's just unfortunate that some "old" GPU/drivers struggle with VAOs.

**Comment by arpu** [comment] 2021-03-23 17:43
copy!  will try this on more AMD based and newer gpus if i find some users with this

**Comment by arpu** [comment] 2021-03-23 17:43
looks more a amd driver bug for now or chrome angel

**Comment by Mugen87** [comment] 2021-03-23 17:45
Consider to report this performance issue at: https://bugs.chromium.org/p/chromium/issues/list

**Comment by arpu** [comment] 2021-03-23 17:50
ok get some more reports from windows user  with 
Nvidia RTX 3060TI
r126.1:
![r126 1 nvidia](https://user-images.githubusercontent.com/14173/112193867-9a393700-8c08-11eb-8404-4d32d1460024.png)
![r117 1](https://user-images.githubusercontent.com/14173/112193933-a91fe980-8c08-11eb-97ac-975447ac1cb7.png)

so its not amd specification

**Comment by arpu** [comment] 2021-03-23 17:52
@mrdoob  should i change the Titel again?

**Comment by mrdoob** [comment] 2021-03-23 17:57
Let's wait for more reports.

**Comment by danielesteban** [comment] 2021-03-23 18:10
Hello there!
I just tried this on my Windows 10 - Nvidia RTX 2070S with the 461.72 GRD driver on chrome 89.

r126.1:
![126](https://user-images.githubusercontent.com/806111/112196046-e84f3a00-8c0a-11eb-9dd9-c5bb92fdb132.jpg)

r117.1:
![117](https://user-images.githubusercontent.com/806111/112196295-2cdad580-8c0b-11eb-9ad4-98060e42cc8d.png)

**Comment by mrdoob** [comment] 2021-03-23 18:25
@arpu Could you do another test with r118? Would be helpful to figure out exactly what version caused this.

**Comment by Mugen87** [comment] 2021-03-23 18:27
When using `r118`, please also test with `WebGL1Renderer`? Just to make sure the regression is unrelated to WebGL 2.

**Comment by arpu** [comment] 2021-03-23 18:46
Readeon 460 on Linux chrome 89 
r118.1 with webGL1Renderer 
![Bildschirmfoto von 2021-03-23 19-43-05](https://user-images.githubusercontent.com/14173/112200964-12efc180-8c10-11eb-9d0e-368f38af9e72.png)
https://jsfiddle.net/txpLmn8b/1/

r118.1 with webGLRenderer 
![Bildschirmfoto von 2021-03-23 19-45-56](https://user-images.githubusercontent.com/14173/112201314-6a8e2d00-8c10-11eb-91ff-f9ad853dd601.png)
https://jsfiddle.net/txpLmn8b/

**Comment by Mugen87** [comment] 2021-03-23 18:49
Okay, there is a difference but the real gap seems to be related to VAO.

I think it's best to report this performance issue to the Chromium team. I suspect the performance depends on which native 3D API is targeted by WebGL. And maybe on the drivers.

**Comment by arpu** [comment] 2021-03-23 19:51
i am not sure i can provide a Webgl only Test Case for the Chrome Team,  maybe @toji or @takahirox  can help on this?

**Comment by Mugen87** [comment] 2021-03-23 19:54
This is not necessarily required. `three.js` test cases are often sufficient for investigation such issues.

**Comment by arpu** [comment] 2021-03-24 12:30
can i disable VAO in THREE on chrome?  ( will try making the bug Report to the Chrome Team today)

**Comment by Mugen87** [comment] 2021-03-24 12:56
No, VAO is not configurable. I suggest you use `three.js` from revision `r117` like in your first fiddle.

**Comment by arpu** [comment] 2021-03-24 14:08
using r117.1 is not an option for me because i need Alpha to Coverage  from coming r127 

bugreport done https://bugs.chromium.org/p/chromium/issues/detail?id=1192082

**Comment by Mugen87** [comment] 2021-03-24 14:26
To clarify: I only suggest to use `r117` in the fiddle, not in your app^^.

Anyway, before considering making VAO optional or configurable, it's best to find out first why certain platforms struggle with many VAO calls. Maybe there is the possibility to improve something in the browser implementations or ANGLE in order to fix this.

In general, using VAOs is a recommended and widely used way for performance improvements. Babylon.js also uses them.

**Comment by arpu** [comment] 2021-06-26 09:26
@Mugen87 @mrdoob  some updates from google at https://bugs.chromium.org/p/chromium/issues/detail?id=1192082#c16
( three should disable VAO )

**Comment by mrdoob** [comment] 2021-06-26 09:42
@kenrussell

We should remove VAO support? #16287 
Do you recommend that we stop the effort of adding UBO support too? #21558

**Comment by takahirox** [comment] 2021-06-26 16:49
In https://bugs.chromium.org/p/chromium/issues/detail?id=1192082#c16

>Submitter, for now, the best workaround would be to change Three.js back to stop using VAOs.
>
> We'll start profiling ANGLE in the GPU process next week to understand where the hot spots are. about:gpu from this machine follows.

My understanding is Chrome(Chromium) will try to optimize WebGL VAO performance, isn't it? I think whether we should remove it or not very depends on whether they do and its ETA. And we still can get benefit of VAO on other platforms (Safari, Firefox, etc) so disabling it (for now) only on Chrome can be one of the options.

**Comment by mrdoob** [comment] 2021-06-28 08:27
Ah... I thought this was an ANGLE issue which affects all browsers, no?

**Comment by takahirox** [comment] 2021-06-28 09:14
Oh... I think I have misread. Yeah Firefox seems to have the same performance problem https://bugs.chromium.org/p/chromium/issues/detail?id=1192082#c15

**Comment by kenrussell** [comment] 2021-06-28 21:19
If it's not too difficult to leave the VAO and non-VAO code paths in place, that would be great - we will absolutely try to optimize the VAO path better in ANGLE in https://crbug.com/1192082 .

Would appreciate it if you'd continue pursuing using UBOs. The implementation of this functionality in ANGLE on top of D3D11 has already received quite a lot of attention in https://bugs.chromium.org/p/angleproject/issues/detail?id=3682 , and I think it should be a performance benefit on all platforms. But if you can try it and let the browser implementers know about any performance pitfalls you have, with test cases, that would be greatly appreciated.

**Comment by Mugen87** [comment] 2021-06-29 07:45
How about adding a new parameter for `WebGLRenderer` that enables VAO instead of always trying to use it when available? In this way, we can easily restore the current behavior when the VAO path gets optimized but we still allow users to use VAO if it introduces a performance benefit to their app.

**Comment by mrdoob** [comment] 2021-06-29 15:20
@Mugen87 

> How about adding a new parameter for `WebGLRenderer` that enables VAO instead of always trying to use it when available?

That sounds good to me 👍

**Comment by mrdoob** [comment] 2021-07-02 11:57
So it seems like this has been fixed in Chrome after all? https://bugs.chromium.org/p/chromium/issues/detail?id=1192082#c21

@arpu can you try Chrome Canary (93.0.4562.0+)?

**Comment by arpu** [comment] 2021-07-02 12:29
sorry can only test this on Linux now need to wait for the dev channel update

**Comment by kenrussell** [comment] 2021-07-02 18:47
Yes, hopefully this performance problem has been addressed on all platforms. The problem was solely in Chrome, not ANGLE, so I apologize for incorrectly guessing where it was. Please follow up on https://crbug.com/1192082 to confirm whether this is fully addressed. Thanks.
