### ISSUE TITLE
OutlinePass not rendering visible/hidden edges correctly on skinnedMesh

### ISSUE THREAD

**Issue by Centipede5** [mrdoob/three.js#21790] opened 2021-05-05 18:57 UTC
**Description**

When an OutlinePass postprocessing effect is added to a skinned mesh the visible/hidden edge colors are not displayed correctly. They seem to be displaying as if the skinnedmesh was static

**To Reproduce**

1. Create SkinnedMesh 
2. Create Mesh to obscure SkinnedMesh
3. Create an OutlinePass for the SkinnedMesh with 2 different colors for visible/hidden edges 

***Code***

See live example

***Live example***
[jsfiddle](https://jsfiddle.net/Centipede5dev/q9kwpf4L/3)

**Expected behavior**

The visible/hidden edge colors will display correctly according to the current animation of the SkinnedMesh

**Screenshots**

![image](https://user-images.githubusercontent.com/29002999/117194515-2ca92a80-adb2-11eb-93a7-67c1519930fc.png)

**Platform:**

 - Device: Desktop
 - OS: Windows
 - Browser: Chrome
 - Three.js version: r128

**Comment by Mugen87** [comment] 2021-05-05 20:57
The asset is not a skinned mesh. It uses morph targets.

Even without the animation I can see that the visible edge color bleeds through the cube: https://jsfiddle.net/kg7enzp8/

So I think this issue is unrelated to animations.

**Comment by Mugen87** [comment] 2021-05-05 21:02
It seems that the issue is less visible when lowering the edge thickness: https://jsfiddle.net/shkmu9ta/

**Comment by Centipede5** [comment] 2021-05-06 01:09
> Even without the animation you can see that the visible edge color bleeds through the cube: https://jsfiddle.net/kg7enzp8/1/

True. but its just bleed over, not incorrectly outlining sections of it like in my example. it looks like with outline is drawn as if the model wasn't animated, then morphed onto the animated model without changing how the visible/hidden edges are calculated

**Comment by Mugen87** [comment] 2021-05-06 08:34
> it looks like with outline is drawn as if the model wasn't animated,

TBH, I don't think this is true. To me, it seems to be an issue how the pass blends the colors together. If the artifact in https://jsfiddle.net/kg7enzp8/1/ is fixed, it's probably also okay for the animated fiddle.

**Comment by Mugen87** [comment] 2021-05-06 14:03
Um, it seems the `edgeStrength` property can't take arbitrary values. At some point the result looks clearly wrong.

https://jsfiddle.net/zw21apbc/1/

In this example, only the visible edges should be outlined. But a high value of `edgeStrength` also makes the hidden edges bleed trough.

**Comment by codrakai** [comment] 2021-05-15 05:44
Inclined to agree with both of you on this one: the mask isn't respecting the morph targets, and the blur _after_ the mask means some of the `visibleEdgeColor` bleeds into a zone where it should be the `hiddenEdgeColor` if it's anything at all. Regarding a high value for `edgeStrength`, I couldn't tell—is that hidden edge supposed to be visible in that case? If not, when does the `hiddenEdgeColor` show? I'm afraid I'm not familiar with the full range of expected behaviors for this pass.

Scoping it just to the first issue: playing with positions of things to generate a clear bad application of the mask, I got:

<img width="242" alt="Screen Shot 2021-05-14 at 10 23 43 PM" src="https://user-images.githubusercontent.com/59149612/118349040-0ea29f00-b503-11eb-942c-cc92bdc8fa4b.png">

I think this can be fixed on this line of the vertex shader in the `getPrepareMaskMaterial` method:
https://github.com/mrdoob/three.js/blob/67df2ed21a1353f60e545bb07c18edabf872a25b/examples/jsm/postprocessing/OutlinePass.js#L456

Changing the `position` to `transformed` so that we have the model coords as affected by the morph targets yielded the following result:

<img width="242" alt="Screen Shot 2021-05-14 at 10 32 41 PM" src="https://user-images.githubusercontent.com/59149612/118349229-4f4ee800-b504-11eb-8b09-3a09856c12d5.png">

This is clearly much better, though you can see some of the bleeding that @Mugen87 mentions in the lower right corner of the image.

For an animated version of this, I've got a bit of a hacked together fiddle at https://jsfiddle.net/yd6wo18z/9/ that demonstrates the fix.

_If_ this seems like a valid fix for that aspect and it's something that belongs in the codebase, I can open a PR, or one of y'all can do it instead of waiting around for me—happy to do whatever works best for everyone.

**Comment by Mugen87** [comment] 2021-05-15 07:49
> Changing the position to transformed so that we have the model coords as affected by the morph targets yielded the following result:

That is indeed a bug, good catch! It would be great if you can open a PR with your suggested change 👍

**Closed** 2021-05-17 14:09 UTC
Labels: Bug
