### ISSUE TITLE
Unit scale factor

### ISSUE THREAD

**Issue by notghettolenny** [mrdoob/three.js#24123] opened 2022-05-25 07:38 UTC
did not see UnitScaleFactor participating in the calculation in the FBXLoader code.

Expected behavior

Whether three.js can add a parameter like Unity's fbx model import can control whether to enable the model unit scaling factor.

Platform:

Device: [Desktop]
OS: [Windows]
Browser: [Chrome]
Three.js version: [ r120]

**Comment by Mugen87** [comment] 2022-05-25 07:41
Duplicate of #20402.

**Closed by Mugen87** 2022-05-25 07:41 UTC
