### ISSUE TITLE
MeshBasicMaterial "flips" under shadow influence

### ISSUE THREAD

**Issue by killroy42** [mrdoob/three.js#8760] opened 2016-04-28 12:07 UTC
##### Description of the problem 

MeshBasicMaterial with side = THREE.BackSide seems to "flip" after one frame if there is a shadow casting light.

Reproduction: http://codepen.io/killroy/pen/yORMNO
Scene has:
- cube with MeshBasicMaterial({side: THREE.BackSide})
- SpotLight with castShadow = true
- WebGLRenderer with shadowMap.enabled = true

if any of these components are changed, it renders correctly. Otherwise, it will flash for one frame, then disapear (as if rendered with face: THREE.FrontSide)

Adding a WireframeHelper also causes it to render correctly.

These conditions should not interact! shadows should not affect BasicMaterial! side should not flip due to shadow settings, etc.

##### Three.js version

- [ ] Dev
- [x] r76
- [x] r72
- [x] r58

##### Browser

- [] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [] All of them
- [x] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by killroy42** [comment] 2016-04-28 12:13
Seems this was introduced between r74 and r75.

**Comment by mrdoob** [comment] 2016-04-29 02:18
Hmm, I only see yellow...

![screen shot 2016-04-28 at 19 17 40](https://cloud.githubusercontent.com/assets/97088/14906908/f6eb2e02-0d75-11e6-9b21-dabb0dbdc1d8.png)

**Comment by killroy42** [comment] 2016-04-29 07:48
Yes, on r74. on r76, you will not see it. On r76, if you comment out any of the lines marked with "// This causes it", it re-appears. This shows there is some sort of interaction between shadow maps and MeshBasicMaterial in r76, that's not present in r74, which probably should not be there, since that material is not affected by shadows. I'm afraid I don't understand the underlying systems well enough to find the problem myself :(

**Comment by tschw** [comment] 2016-04-29 10:33
@mrdoob
I noticed the `shadowMapCull*Faces` stuff and apparently troublesome direct tweaking of the GL state while adding `ShadowMap.allowDoubleSided` recently. I guess I'll merge the functionality and remove the defunct code.

Anything noteworthy about the history? Used by (just if you know, will `grep` otherwise)?

@killroy42 
> Adding a WireframeHelper also causes it to render correctly.
> 
> These conditions should not interact! shadows should not affect BasicMaterial! side should not flip due to shadow settings, etc.

No, this is definitely quirky!

I guess the symptom may be gone on `dev` already. However, the cause is still there - just sleeping. Apparently`ShadowMap` and `WebGLRenderer` don't quite agree on who's in charge of the GL state and it can cause weird effects (I guess there's nothing special about `WireframeHelper` - just that it causes a state change).

**Comment by killroy42** [comment] 2016-04-29 11:08
I've cleaned up the reproduction so you can compare the different causes and revisions with dat.GUI:
http://codepen.io/killroy/pen/yORMNO

(Perhaps also a neat way to inject different THREE revisions for regression testing in general...)

**Comment by tschw** [comment] 2016-04-29 15:33
Neat test bed!

Current `dev` seems still broken https://raw.githubusercontent.com/mrdoob/three.js/dev/build/three.js

**Comment by tschw** [comment] 2016-04-29 15:36
Feature branch looks fine https://raw.githubusercontent.com/tschw/three.js/Shadowing/build/three.js

**Comment by killroy42** [comment] 2016-04-29 15:54
Added those to the testbed via rawgit.com: http://codepen.io/killroy/pen/yORMNO
What's the route for the feature branch to land? I'm building for the future, so I don't mind running those in my prototyping environment...

**Comment by mrdoob** [comment] 2016-04-29 15:58
Just merged it. You should be able to check `dev` now.

**Comment by killroy42** [comment] 2016-04-29 16:09
You're the best! BTW, what's the best way to find if a feature already exists before making my own version? It seems that a lot of major THREE features are currently scattered between the code base, the examples folder and various third-party repositories... we need a THREE module registry... Specifically I want to make a simple wrapper for turning a shader/material into a texture (animated).

**Comment by mrdoob** [comment] 2016-04-29 16:13
Closing this. Feel free to continue discussing though!

**Closed by mrdoob** 2016-04-29 16:13 UTC

**Comment by killroy42** [comment] 2016-04-29 16:19
Confirmed. Had to do some cache wrestling with rawgit.com but http://codepen.io/killroy/pen/yORMNO shows r77dev is A-OK!
