### ISSUE TITLE
IFC importer for threejs

### ISSUE THREAD

**Issue by kdilayer** [mrdoob/three.js#9764] opened 2016-09-24 12:01 UTC
I have written an ifc 2x3 importer for threejs. It is very experimental but most of the objects will render.

Is this something that can be included in the distribution ? My hope is that someone would develop it further and eventually also add support for ifc4

Example of imported ifc:
![ifc-imported](https://cloud.githubusercontent.com/assets/22413236/18808330/99a80a64-8267-11e6-847d-10750cecc8d9.png)

**Comment by kdilayer** [comment] 2016-09-24 12:17
forgot to mention that it depends on ThreeCSG

**Comment by mrdoob** [comment] 2016-09-24 15:33
Never heard of this format. Where is it usually used?

**Comment by kdilayer** [comment] 2016-09-24 19:10
As far as I konw, It's used mainly in the construction business, building modeling. Supported by Autocad, Revit, Tekla and Solibri to mention a few.

**Comment by mrdoob** [comment] 2016-09-24 20:24
I see I see!
What does it need ThreeCSG for?

**Comment by kdilayer** [comment] 2016-09-24 20:56
For example; a Wall object (extruded shape in threejs) might have an opening. And the easiest solution I found was to use ThreeCSG. Also used in other cases like IfcBooleanResult.

Link to the IfcOpeningElement spec:
http://www.buildingsmart-tech.org/ifc/IFC2x3/TC1/html/ifcproductextension/lexical/ifcopeningelement.htm

**Comment by johnney88** [comment] 2016-09-25 04:41
you can reference at 
http://www.ifcquery.com

**Comment by fraguada** [comment] 2016-09-25 08:38
@mrdoob , IFC stands for Industry Foundation Classes and is meant to be a standard exchange format for Building Information Model/Management (BIM) projects.  Software packages typically related to this are [Revit](http://www.autodesk.com/products/revit-family/overview), [ArchiCAD](http://www.graphisoft.com/archicad/), [VisualARQ](http://visualarq.com), and quite few others.  While I am generalizing, BIM software provides standard object types such as walls, slabs, roofs, stairs, windows, etc all driven by a family/style definition where the operator defines the parameters for the object.  Therefore if I have a wall with a layer of CMU, Plasterboard, and Tile, I can define the thicknesses of all of the layers.  I something changes, I change the family/style definition, and everything automagically updates!  Reality is not so magical!  It is a contentious format, as each software vendor is free to play around with the definition of what a wall may constitute in import/export http://buildingsmart.org/compliance/certified-software/.  
It is a great format to support, and I thank @kdilayer for setting it up.  @johnney88 is that viewer using threejs?

**Comment by johnney88** [comment] 2016-09-25 09:19
Yes, The Viewer use Threejs.
 The saved  file 'ifcquery.min.js' is writed by Three.js, but it is encoded.

**Comment by rhairston** [comment] 2016-09-26 20:20
I can confirm that ifc is used in ConSci. I actually used an ifc converter app to convert my companies files into .objs with .mtl files and they read really well. So taking out the middle man would be really helpful since our customers tend to upload ifc files anyway

**Comment by RicoLiu** [comment] 2016-10-14 05:33
@rhairston An ifc converter app?It can convert ifc file into obj file so that Threejs can load it well.
Am I right?

**Comment by mrdoob** [comment] 2016-10-14 21:47
Thanks everyone for chiming in!

@kdilayer a PR would be great. Please, include ThreeCSG too 😊

**Comment by cmeeren** [comment] 2016-11-24 13:44
Any progress here? We're currently converting IFC to DAE for use with three.js, but would love it if three.js supported IFC directly.

**Comment by remitache** [comment] 2016-12-02 04:55
Hi kdilayer,

I am very interested into having a look and taking it further.

**Comment by Servuc** [comment] 2016-12-14 08:31
Hi everybody,

I've seen that too https://www.npmjs.com/package/ifc-convert
With that you can convert IFC to DAE, OBJ, STP and IGS.

**Comment by AlexanderChen1989** [comment] 2017-05-22 02:05
@kdilayer Any progress ?

**Comment by dslwz2008** [comment] 2017-07-05 01:41
@kdilayer Any progress here? It will save a lot of things if three.js could support IFC format directly.

**Comment by RicoLiu** [comment] 2017-07-05 01:44
@dslwz2008 [https://github.com/mrdoob/three.js/issues/9860](https://github.com/mrdoob/three.js/issues/9860)

**Comment by jean-noelp** [comment] 2017-11-14 16:03
Nobody has any news ?

**Comment by kdilayer** [comment] 2017-11-15 17:21
I tweaked the editor to supprt ifc files.
A few screenshots attached. I have worked on this for quite some time now... currently I have not seen any IFC 2x3 files that it cant render... largest file that I've tried is 180 MB... 
Awesome.
![screen shot 2017-11-15 at 19 19 31](https://user-images.githubusercontent.com/22413236/32850113-f3c992fe-ca39-11e7-9d81-c2d0a3a020d7.png)
![screen shot 2017-11-15 at 19 19 20](https://user-images.githubusercontent.com/22413236/32850114-f3e42164-ca39-11e7-830d-5cef33ab71a9.png)
![screen shot 2017-11-15 at 19 19 08](https://user-images.githubusercontent.com/22413236/32850115-f427a18c-ca39-11e7-93d6-73ecf8ee31d2.png)
![screen shot 2017-11-15 at 19 18 45](https://user-images.githubusercontent.com/22413236/32850117-f44625b2-ca39-11e7-93b4-232bb4133005.png)

**Comment by simplynail** [comment] 2017-11-16 01:18
Hey, awesome work!
Can this be accessed directly from master branch or the tweaked code for IFC support sits somewhere else?

**Comment by jean-noelp** [comment] 2017-11-16 09:01
Yer ! Awsome ! How can we have access to this loader code, please ? :o

**Comment by Mugen87** [comment] 2017-11-16 09:58
I vote for a PR 😊 !

**Comment by swisx** [comment] 2017-11-23 09:48
We would love this feature as well, for now, I'm converting IFC files to obj with https://github.com/IfcOpenShell/IfcOpenShell, but some more complicated geometries are still not parsed, so sometimes is the object, not 100% complete.

**Comment by CraigMcCarthy11** [comment] 2017-12-13 17:08
Hi, I was wondering if you were able to get some of the complex things such as doors and transparencies with windows loading in your viewer and loader. It looks awesome so far! I'm curious if you planned on putting out any version of this in the near future.

Good luck!, Thanks for updating.

**Comment by Foosballfan** [comment] 2018-01-23 11:35
Hi @kdilayer, could we please have access to your application?

I'm interested to see the file size difference between .ifc and three.js formats.

Thanks!

**Comment by jean-noelp** [comment] 2018-01-23 13:07
@Foosballfan I think an IFC is not an interesting format for the size, since it's very verbose. It's just an exchange format for architecture software like AutoDesk.
It's a standard or BIM. (ask to google this term which is famous in this kind of profession)

**Comment by Foosballfan** [comment] 2018-01-23 14:32
@jean-noelp  Thanks for the reply.

I have an ifc file for a building which is 34MB and am trying to display this data on the web with the smallest possible download size.

With Unity WebGL I can get it down to about 11MB but would like to see whether it is possible with more pure WebGL using Three.js. Hopefully I can achieve an even smaller download size.

Do you have any experience with a similar situation?

**Comment by donmccurdy** [comment] 2018-01-23 15:06
@Foosballfan to minimize file size, the steps I would try are:

1. convert to OBJ
2. run through [obj-simplify](https://github.com/jonnenauha/obj-simplify)
3. compress the OBJ with [Draco](https://github.com/google/draco)
4. load with THREE.DRACOLoader

If the file can't be converted to OBJ or another format, then there's probably not a lot you can do beyond simplifying the model or using gzip... "pure WebGL using three.js" is a way of rendering the file, but you must still use some format or other to get the file loaded first.

**Comment by Foosballfan** [comment] 2018-01-23 15:26
@donmccurdy That looks great, thanks!

I'll give it a go and see how it turns out.

I originally gave up on obj as the one I made is 220MB from the 34MB file.

**Comment by Mugen87** [comment] 2018-02-12 12:29
Closing the issue since @kdilayer is obviously not willing to share his implementation. I've added `IFCLoader` as a task to the loader wish list in #5524.  

As long as there is no `IFCLoader`, try to convert `IFC` files to other formats like `OBJ`. Looks like the following tool can perform this conversion: http://ifcopenshell.org/ifcobj.html

Also see https://github.com/IfcOpenShell/IfcOpenShell

**Closed by Mugen87** 2018-02-12 12:29 UTC

**Comment by dlabz** [comment] 2018-03-23 23:41
@Foosballfan : IFC is the most efficient way to compress geometry. Problem is, the procedural approach required to render it is not really compatible with triangles. A 34MB IFC can easily extract to a 4GB of triangle streams. IFC describes an elbow pipe with just 4 vertices, but it will take hundreds of triangles to render it. One look at the OP's renderings, and I can tell there is no spoon. Sure, he can do straight lines and one axis toroidal shapes. But, IFC specification includes definitions of a surfaces swept by two bezier splines. So, it's 8 3D vertices defining a practically infinite set of triangles. Architects love that tool, but even rendering a 2D representation of it on a computer is problematic, since the formula doesn't allow the` f(x) = y` approach. 
Here, have a look at official IFC specificatoin: http://www.buildingsmart-tech.org/ifc/IFC4/final/html/schema/ifcgeometryresource/lexical/ifcbsplinesurface.htm

**Comment by Aarbel** [comment] 2018-04-22 11:47
@kdilayer are you still active on github ? would you like to share to implementation ? Thanks !

**Comment by Foosballfan** [comment] 2018-04-24 14:44
The approach I settled for was to use BimServer for streaming the binary IFC data and then constructing it in ThreeJS. The download size over the web socket is satisfactory and I have full control over the model in Three.

You can take a look at the way BimViewer works as a starting point.

**Comment by Joao-b4** [comment] 2019-09-25 17:18
any answers?

**Comment by mrdoob** [comment] 2019-09-28 16:09
@Joao-b4 What about?

**Comment by Joao-b4** [comment] 2019-09-29 17:17
about a possible IFC loader

**Comment by mrdoob** [comment] 2019-09-30 01:37
Ah, I guess it's up to @kdilayer...

**Comment by Joao-b4** [comment] 2019-09-30 04:31
I believe that @kdilayer will have nothing, since it has been 3 years since the publication and no response, nor activity on his profile.
I don't understand how the creation of a loader works, and I have a little knowledge in the library, I work with it a little while ago, I would have some links to create a loader, I can get enough disposition and knowledge in the future.

**Comment by Mugen87** [comment] 2019-09-30 10:01
I have outlined [here](https://github.com/mrdoob/three.js/issues/5524#issuecomment-388775266) a basic scaffold of `THREE.IFCLoader`. The most difficult part when writing a loader is to actually understand the respective 3D format. Only then you can parse the format and transform the geometry and/or material data into `three.js` entities (e.g. `THREE.BufferGeometry`). I recommend to study a more or less simple loader like `THREE.PLYLoader` in order to understand this process. And of course the IFC standard (https://www.iso.org/standard/51622.html)

**Comment by Joao-b4** [comment] 2019-09-30 14:01
thanks, an ifc loader would be really useful, and i need one right now, i'm using what they mentioned above, to convert to OBJ, but i don't think it's the best way

**Comment by Foosballfan** [comment] 2019-09-30 14:15
This was a few years ago so my memory is rusty but I believe our solution was to use bim server to deliver the geometries from the server and then use Three on the front end to handle the rendering.

It took a bit of messing around but eventually worked.

**Comment by xawill** [comment] 2019-10-31 10:35
[IfcConvert](https://github.com/klokoy/ifc-convert) is an IfcConverter for Node.js. It converts from .ifc to .dae, .obj, .stp and .igs. I didn't try it yet, but if it works as described, I guess we would not need any .ifc loader in Three.js anymore, right ?
.ifc contains much more information than just the 3D model, but as far as Three.js is concerned, only the 3D model should be imported.
For an exported, this would be different, as one could want to export his own BIM library in an .ifc file, alongside the actual exported 3D model.
Does it make sense ?

**Comment by Mugen87** [comment] 2019-10-31 10:50
It still could be interesting to directly load `IFC` into the browser without the need for a separate conversion tool. However, the mentioned tool is just a wrapper around [IfcOpenShell](http://ifcopenshell.org/ifcconvert.html). So it does not do something really new...

**Comment by jean-noelp** [comment] 2019-10-31 10:51
I think the import workflow through IfcConverter could be good!

On the contrary, the ifc export does not make any sense for me, because you loose every relevant ifc data (architectural components, BIM stakeholders...) in a lambda Three.js viewer, unless to build an IfcEditor with Three.js.

**Comment by xawill** [comment] 2019-10-31 11:03
@Mugen87 Well, the main added value is the Node package, as to my knowledge IfcOpenShell is online a CLI tool.

@jean-noelp You are right. I didn't mean an export of the "master .ifc file", but rather a "library .ifc file" BIM stakeholders could import in their own "master .ifc file". For instance you are a garage door manufacturer, use Three.js to plan the installation for your clients (architects, for instance) and export the BIM library containing your BIM objects (typically the garage door). You see what I mean ? But anyway, there would be no way to have this exporter built in Three.js as each particular use-case is way too much specific (I guess).

**Comment by yuzhongxin19860213** [comment] 2019-12-13 02:29
I find a TOOL, IFC can be resolved   ,
It's not free ，
But parsing IFC structure is free and open source
http://www.apstex.com/

**Comment by DanielRamosAcosta** [comment] 2020-05-28 14:08
Greetings, theare aren't any news from @kdilayer right? he never released the source code?

**Comment by yuzhongxin19860213** [comment] 2020-05-28 14:10
?&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Daniel Ramos"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月28日(星期四) 晚上10:08
收件人:&nbsp;"mrdoob/three.js"<three.js@noreply.github.com&gt;;
抄送:&nbsp;"漏网de鱼"<270354052@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [mrdoob/three.js] IFC importer for threejs (#9764)





 
Greetings, theare aren't any news from @kdilayer right? he never released the source code?

**Comment by Aarbel** [comment] 2020-08-30 18:00
any news about this ?

**Comment by agviegas** [comment] 2020-10-30 11:27
Hey! A few days ago I started to implement an IFC parser in JS with the idea of applying it to Three.js. This is a personal project that I do in my spare time, so I have no clear idea how long it will take. However, I saw this thread today and thought you may find it of interest. You can find it [here](https://github.com/agviegas/IFC.js).

**Comment by Aarbel** [comment] 2020-10-30 14:53
@agviegas looking forward for what you do with it ! a PR could be really welcome

**Comment by mrdoob** [comment] 2020-10-31 09:56
Indeed! @agviegas we may get more people helping on it if you do a PR with it 😍

**Comment by kdilayer** [comment] 2020-10-31 11:16
Unfortunaltey I was unable to release my work on the ifcimporter, but I can help @agviegas

**Comment by agviegas** [comment] 2020-10-31 15:53
@mrdoob That sounds great. I am still working on the core functionalities of the parser; it can already load all spatial structure elements and I will start building the geometry soon. I suppose that the code also needs to be adapted to [this](https://github.com/mrdoob/three.js/issues/5524#issuecomment-388775266) before doing the PR. Is there any references to check to prepare the code for the PR? We can do this whenever you want. Any help regarding this will be welcomed.

On the other hand, the IFC format is very easy to implement, although it can be a little intimidating because of the harshness of the official documentation. I consider that I know the IFC format relatively well, so if anyone is interested in participating, we can surely get this ready sooner. 🙂 

![Captura](https://user-images.githubusercontent.com/56475338/97783645-7b72cf00-1b99-11eb-8b8a-8c0476095d6b.JPG)

**Comment by mrdoob** [comment] 2020-10-31 16:48
> I suppose that the code also needs to be adapted to [this](https://github.com/mrdoob/three.js/issues/5524#issuecomment-388775266) before doing the PR. 

Yes, it should use the same interface the other loaders use. Maybe the [MD2Loader](https://github.com/mrdoob/three.js/blob/dev/examples/jsm/loaders/MD2Loader.js) is the simpler reference right now.

Don't worry about having everything perfect for the PR. You can submit what you have as a draft and we can help making sure the code fits the rest.

**Comment by agviegas** [comment] 2020-11-24 00:39
After several stumbles and struggles with the format there are already some results. I have implemented the first version of the parser, as well as some of the geometric entities (including extrusions and b-reps). Much remains to be done yet, but I am happy with the results so far. The image below shows a small IFC generated by Revit running smoothly in Chrome. Each geometric instance has the parsed IFC information associated (in fact, in the scene below each instance has a material depending on its cathegory / ifcclass), so creating filters using properties values (Psets and Qsets) should not be hard to archieve from this point. Any ideas or suggestions are welcomed. 🙂

![20201124_screenshot](https://user-images.githubusercontent.com/56475338/100030313-8533cf00-2df3-11eb-881a-a493b554a4d6.jpg)

**Comment by mrdoob** [comment] 2020-11-24 09:41
@agviegas Excellent!

**Comment by haroldiedema** [comment] 2020-11-25 14:32
@agviegas Very well done!

As for ideas for property management. How are you storing these now? Just as `userData` on the meshes or geometry I suppose?

Most of our customers use software like HiCad or ArchiCAD for their modeling and they store A TON of information that is very important for the constructionworkers (thermal density, wind resistance, measurements, weights, etc. etc.).

I'm also very curious about the parsing/loading speed. The models I've tested my implementation with take about 5 seconds to parse, but to generate the geometry, the process takes nearly 2 minutes to convert to a DAE model. (I'm converting it server-side due to the lack of time and experience on my end :sweat_smile:, which is why I'm so excited for this loader to work 'natively')

**Comment by agviegas** [comment] 2020-11-25 17:44
@haroldiedema  I haven't implemented the property sets yet, but the current data structure consists of a JS object where the keys are the express IDs and the values are the parsed objects loaded in memory. Each property that was an express ID is replaced by a reference to the object with that ID. In the current implementation, each instance of _IfcProduct_ with one or more geometric representations has an additional property called _Geometry_ , which is an array of references to the geometries of the scene. For example, each _IfcWallStandardCase_ has a property _Geometry_ with a reference to the _Path_ (a `Line`) a to the _Body_ (a `Mesh`). 

Probably each geometric instance of Three.js will have a property containing the express ID, so finding back the ifc entity loaded in memory (and the related information) will be easy (f. e. when clicking on the meshes in the scene). 

As for the user defined properties, there will be one or more _IfcRelDefinesByProperties_ (or another indirect relationship object) to bind everything toguether. Perhaps each instance of IfcProduct can have an attribute _hasPropertySets_ which would contain an array of the related parsed property sets (I have seen this pattern in other IFC libraries, and this is what I am doing with other indirect relationships such as _IfcRelAggregates_). I am not worried about the amount of properties as they will be structured according to the IFC, but let's see how it goes when I get there. 😅

I am making everything client-side, and currently the parsing takes less than a second and the geometric generation of the last scene shown around 4 seconds. I am aware that with bigger files this time will increase; however, I hope to be able to optimise the system when I have covered more IFC entities and can load IFCs from real projects. 🙂 I will be extending the _CONTRIBUTING_ document, in case anyone wants to dig into any of this.

**Comment by haroldiedema** [comment] 2020-11-26 08:44
@agviegas that sounds awesome!

I've tried cloning the main branch of your repo to test some of our customers models, but unfortunately every single one of them produces an error in the console about _ExpressId is undefined (not all models are 100% coherent when it comes to referencing records that actually exists). I think some CAD software don't clean up references nicely to removed properties.

I could share some of these models with you, but we'll have to do that privately. You can reach me at harold@iedema.me if you're interested in some more test cases of models exported with ArchiCAD or HiCAD.

**Comment by andrewisen** [comment] 2020-11-27 16:20
> @haroldiedema I haven't implemented the property sets yet, but the current data structure consists of a JS object where the keys are the express IDs and the values are the parsed objects loaded in memory. Each property that was an express ID is replaced by a reference to the object with that ID. In the current implementation, each instance of _IfcProduct_ with one or more geometric representations has an additional property called _Geometry_ , which is an array of references to the geometries of the scene. For example, each _IfcWallStandardCase_ has a property _Geometry_ with a reference to the _Path_ (a `Line`) a to the _Body_ (a `Mesh`).
> 
> Probably each geometric instance of Three.js will have a property containing the express ID, so finding back the ifc entity loaded in memory (and the related information) will be easy (f. e. when clicking on the meshes in the scene).
> 
> As for the user defined properties, there will be one or more _IfcRelDefinesByProperties_ (or another indirect relationship object) to bind everything toguether. Perhaps each instance of IfcProduct can have an attribute _hasPropertySets_ which would contain an array of the related parsed property sets (I have seen this pattern in other IFC libraries, and this is what I am doing with other indirect relationships such as _IfcRelAggregates_). I am not worried about the amount of properties as they will be structured according to the IFC, but let's see how it goes when I get there. 😅
> 
> I am making everything client-side, and currently the parsing takes less than a second and the geometric generation of the last scene shown around 4 seconds. I am aware that with bigger files this time will increase; however, I hope to be able to optimise the system when I have covered more IFC entities and can load IFCs from real projects. 🙂 I will be extending the _CONTRIBUTING_ document, in case anyone wants to dig into any of this.

Parsing `User Defined IFC Property Sets` is super-easy. I have a [repo](https://github.com/andrewisen/bim-whale) that does that. My parser is not as sophisticated as yours.

However, I have noticed that some properties tend to break parsers. I haven't used [chevrotain](https://github.com/SAP/chevrotain), so I'm not sure how your code would hold up. I have written more about these problems [here](https://github.com/andrewisen/bim-whale/issues/4). Hope it can be of some use to you.

Anyways, very good job so far! 👍

**Comment by agviegas** [comment] 2020-11-30 18:57
Update: I have deployed the app in [Github pages](https://agviegas.github.io/IFC.js/) for easier user testing throughout the development. This includes responsive navigation for mobile and tablet support. Also, [here](https://agviegas.github.io/ifcjs-example-01/) you can find an alternative deploy that loads an IFC model on startup; the logic for clearing the scene and adding multiple IFCs is not implemented yet, but at least you can see how the navigation looks. The parsing is made by the client, so the loading times depend on the device used. My laptop makes it in around 5 seconds, while my Moto G5 Plus needs around 50 seconds for this scene. There are still classes to be implemented before loading a full project, but feel free to send me any IFCs to add them to the testing files.

**Comment by agviegas** [comment] 2021-01-06 00:34
In case you are interested, this Saturday [OSArch](https://osarch.org/) has invited me to present the project in their monthly meeting. [Feel free to join](https://wiki.osarch.org/index.php?title=Monthly_Meetup), say hi, see the last advances and drop your questions / ideas. 🙂

**Comment by mrdoob** [comment] 2021-01-06 09:59
@agviegas Nice!

Are you still planning on doing a pull request with what you have so other people can fill the gaps?

**Comment by agviegas** [comment] 2021-01-06 11:31
@mrdoob Yes, I was planning on doing the pull request once all the basic IFC2x3 entities are implemented (we are close to this point). Nevertheless, everything is ready to make the PR. Do you think it is better to make the PR now? 

Also, I have noticed that the examples folders (both js and jsm) contain only the bundled files. I assume that the original code will remain in its original repository, and the PR will only add the bundles. Is that right? I ask this because I am not sure wether future collaborations will be PRs to the original repository or somewhere else.

**Comment by Mugen87** [comment] 2021-01-06 12:10
Since the original repository is quite big, it's probably better to just mirror the build files into the `three.js` repository. 

TBH, my opinion from https://github.com/mrdoob/three.js/pull/20836#issuecomment-739481896 still stands.

**Comment by mrdoob** [comment] 2021-01-06 16:18
I agree. I think we can have `webgl_loader_ifc` using the builds for exposure and if people want to contribute they can do so in the original repo.

**Comment by Aarbel** [comment] 2021-01-11 00:11
@agviegas did you included all recent WebGl files optimization in your loader ? (for example the ones that Draco use for Gltf)

Goal: Ifc files can be heavy to load, having modern 3d display optimizations would be perfect !

**Comment by agviegas** [comment] 2021-01-11 08:18
@Aarbel I didn't know about these optimization features, so I haven't implemented them so far. However, once we complete all the basic geometric entities of IFC2x3 and merge the PR, it would be a great functionality to implement!

**Comment by mrdoob** [comment] 2021-03-30 12:14
`IFCLoader` just landed! 🍾 #20598

**Comment by shohara** [comment] 2021-07-02 02:11
Are there any working projects to include layer in IFC? 
It seems the loaded model includes "layers", but it includes only "mask=1", when I loaded the default rac_advanced_sample_project.ifc.

**Comment by agviegas** [comment] 2021-07-02 05:53
Hey, what do you mean by "layers"? You can already filter, select and extract subsets of geometry by IFC class (e. g. isolate all IfcDoors). Is this what you mean?

**Comment by fraguada** [comment] 2021-07-02 10:34
The threejs object schema includes layers: https://threejs.org/docs/index.html?q=layers#api/en/core/Layers
@shohara is that what you are referring to?

**Comment by shohara** [comment] 2021-07-02 17:29
@agviegas @fraguada Thanks for your comments. The "layers" I mentioned is the layers in CAD. We can define layers (kind of view sets) in Revit or ARCHICAD: https://helpcenter.graphisoft.com/user-guide/88369/. I suppose the layers in such CADs will be converted IFC objects (e.g. IfcPresentationLayerAssignment).

I think it is similar to object group in threejs: https://threejs.org/docs/index.html?q=group#api/en/objects/Group. Therefore, I imagined IFC's layer might be converted to object groups by IFCLoader, but I could not find such properties in the loaded model. The layer in threejs as mentioned by @fraguada is also similar, but it seems we can only define layers up to 32. 

@agviegas
> You can already filter, select and extract subsets of geometry by IFC class (e. g. isolate all IfcDoors). Is this what you mean?
It seems similar too, but I don't familiar with filtering the IFC model. Therefore I don't know whether I can filter the objects which are selected in CAD as a layer. Would you mind telling me more about how we can filter, select and extract subsets of geometry by IFC class? 

Thanks,

**Comment by agviegas** [comment] 2021-07-02 17:34
Maybe we can continue the conversation in our discord channel so we can figure out how to help you or include your suggestion in the list of issues: https://discord.gg/jBRSMgHC 😄 otherwise, feel free to directly ask in the github repositories!
