### ISSUE TITLE
Editor: Support the animations for Storage. 

### ISSUE THREAD

**Issue by linbingquan** [mrdoob/three.js#20465] opened 2020-10-06 16:16 UTC
I found the animations doesn't save in Storage.

**Comment by Mugen87** [comment] 2020-10-06 17:44
I guess storing animations only makes sense if instances of `SkinnedMesh` can be serialized/deserialized, see #6040.

Marking this issue as a duplicate of #16234.

**Closed by Mugen87** 2020-10-06 17:44 UTC
Labels: Editor
