### ISSUE TITLE
Resizing Renderer (on orientation change) corrupts window.innerWidth/Height

### ISSUE THREAD

**Issue by PeterKey** [mrdoob/three.js#12988] opened 2017-12-29 00:05 UTC
##### Description of the problem

I may have discovered a very strange bug:

If you adjust the three.js (full-screen) canvas size by calling `renderer.setSize(window.innerWidth, window.innerHeight)` on resize, switching from landscape to portrait mode messes up window.innerWidth/Height.

Yup, it actually seems to change what window.innerWidth/Height returns.

I have set up a small test case inside this [repository](https://github.com/PeterKey/sizeBug-threejs).

1. Open test.html
2. Fire up Devtools
3. Toggle Device Toolbar
4. Select a phone
5. Switch from landscape to portrait mode and observe console output

This bug also occurs on my android phone with Chrome. It messes up a project real bad I am currently working on and I was able to get rid of the bug by excluding the line `renderer.setSize(window.innerWidth, window.innerHeight)`.

**I can add additional information and do further testing if this is not intended behaviour and I didn't make a mistake.**

##### Three.js version

- [ ] Dev
- [x] r89
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome [v. 63.0.3239.108 (Desktop), v. 63.0.3239.108 (Android)]
- [ ] Firefox
- [ ] Internet Explorer

##### OS

(As far as I was able to test it)

- [ ] All of them
- [ ] Windows
- [x] macOS
- [ ] Linux
- [x] Android
- [ ] iOS

**Comment by drreparo** [comment] 2017-12-29 02:08
It just because physicsResolution, devicePixelRatio.

Example iphone6, css resolution is 375 x 667, physics resolution is 750 x 1334, and devicePixelRatio is 2.
resolution is multiplied by physics resolution and devicePixelRatio . 1500 x 2668.

You can edit devtools device option, custom resolution and custom devicePixelRatio.
and check [https://mydevice.io/devices/](https://mydevice.io/devices/) your devices value.

**Comment by Mugen87** [comment] 2017-12-29 09:41
I've transferred your code to this fiddle: https://jsfiddle.net/bja0cpge/5/

As far as i can see, i get valid results in the console even if i change the orientation of the emulated device. 

> switching from landscape to portrait mode messes up window.innerWidth/Height.

What do you mean with "messes up"? What values do you get? And what values do you expected?

**Comment by PeterKey** [comment] 2017-12-29 10:33
Thank you for taking your time investigating this!

This is the console output on my sample project.

```
width: 412 height: 732      # portrait mode
width: 732 height: 412      # landscape mode
width: 732 height: 1301     # portrait mode
width: 732 height: 412      # landscape mode
```

The first time I switch from landscape to portrait mode the values aren't correct anymore. It should be 412x732 instead of 732x1301.

Your fiddle seems to work fine for me as well. I actually wasn't able to replicate this in a fiddle, that's why I created the repository.

**Comment by Mugen87** [comment] 2017-12-29 13:23
In any event, i don't think this is a `three.js` issue. It is not a bug in the library if you get wrong values `window.innerWidth` and `window.innerHeight`. I suggest you should post a help request at stackoverlfow.

**Comment by mrdoob** [comment] 2017-12-30 17:55
> Your fiddle seems to work fine for me as well. I actually wasn't able to replicate this in a fiddle, that's why I created the repository.

That means that the error is in your code and not in the library or browser.

**Closed by mrdoob** 2017-12-30 17:55 UTC

**Comment by glegenty** [comment] 2018-01-05 16:06
I have the same issue also only on chrome.

**Comment by PeterKey** [comment] 2018-01-05 17:37
I am happy that I'm not the only one. [This is the related Stackoverflow post.](https://stackoverflow.com/questions/48033845/window-innerwidth-height-gets-corrupted-by-resizing-three-js-renderer-on-orienta/48116336#48116336) Until we can't confirm that this is a three.js issue we should continue the discussion there. _Please upvote on SO for traction_  😌

**Comment by ItsTehStory** [comment] 2018-07-20 13:05
I just answered on your Stackoverflow @PeterKey! I don't use three.js and I ran into the problem so not a three.js problem ;)

**Comment by philipp7pc** [comment] 2020-12-21 23:09
I would like to pick this up, in the hope somebody has isolated how iOS devices hand over the viewport pixel sizes to - in this case three - .js
Did anybody find a different workaround than coloring the main's background the same color of the render's background. It's kind of immanent even on the three.js samples if you open them on an iPhone.

**Comment by mrdoob** [comment] 2020-12-22 00:04
@philipp7pc Can you share a screen recording that shows the issue you're trying to describe?

**Comment by philipp7pc** [comment] 2021-01-05 00:55
@mrdoob sorry for answering so late. Using different accounts for research and work. ;] 
I'm struggling to screen grab the issue (also, it's not happening on my old iPhone6). But it might be visible if you try on http://inertiaplayer.de (start in portrait and then rotate device to landscape). 

Meanwhile I found out that webkit deals differently with the canvas sizes. Changing sizes from pixels to vh and vw and so on doesn't change things. ... Sorry, I'll find a way to document this a little better soon.

... but also: Thanks for the great work on three.js. Great tool!
