### ISSUE TITLE
Using native WebGLTexture as a RawShaderMaterial uniform

### ISSUE THREAD

**Issue by Siroko** [mrdoob/three.js#5230] opened 2014-08-23 22:17 UTC
Do you have any clue for passing a native WebGLTexture to one Shader in a Three material?

We are sharing the Three gl context to do a series of calculations and stuff on the GPU, but the main purpose is to render the final data with three, so I need to put my output texture (WebGLTexture) as a Sampler2D uniform in a THREE.RawShaderMaterial. I don't know if this is possible using the available API of the engine.

Thanks in advance and keep up the great work!

**Comment by valentin-pinkau** [comment] 2017-01-18 11:26
Is there any progress on this issue? 
Would it be hard to overload the THREE.Texture constructor to use a WebGLTexture as an argument?

**Comment by schteppe** [comment] 2017-05-25 13:44
This seems to work in r85:

```js
var texture = new THREE.Texture();
var properties = renderer.properties.get( texture );
properties.__webglTexture = myWebGLNativeTexture;
properties.__webglInit = true;
```

**Comment by Mugen87** [comment] 2021-01-18 10:36
Duplicate of #17766.

**Closed by Mugen87** 2021-01-18 10:36 UTC
Labels: Suggestion
