### ISSUE TITLE
Why doesn't my texture look crisper when I zoom it?

### ISSUE THREAD

**Issue by MeRahulAhire** [mrdoob/three.js#25167] opened 2022-12-21 13:50 UTC
### Description

Hi @mrdoob, I'm using a `8192x4096`px  image as a texture on glb sphere. When I zoom the camera I don't see the details as what we excpect while normally zooming high res image. Rather, even on normal view distance the texture appear to be less crisp and slightly blurry as compared to original image. it seems like the threejs or R3F is sampling the pixel values in improper way especially at Egypt, US and other. I tried adding even more high res image but it created the same result.

**Here's the Demo** - https://b375b1d9.experientia-in.pages.dev/nasa-black-marble
**This is the actual image which I'm using as texture** - https://static.experientia.in/nasaBlackMarble/2016_nasaBlackMarble_8K_bin.webp

There's nothing so special about the code, but incase you want to review it, [here you go](https://github.com/experientia-in/experientia.in/blob/react/src/nasa-black-marble/comp/earth.jsx).
[index.jsx](https://github.com/experientia-in/experientia.in/blob/react/src/nasa-black-marble/index.jsx)

From last month, I'm trying to debug this issue, I thought maybe its [OpenLayers](https://openlayers.org)'s fault as I'm projecting map on a sphere via canvasTexture and the answer is no because I can see OpenLayers's Canvas rendering clear image but I'm not understanding what's happening when I use it over R3F. 

Can you please help me with this. I tried almost everything but nothing seems to work.

### Reproduction steps

Mentioned above

### Code

mentioned above

### Live example

mentioned above

### Version

0.9.0

### Device

Desktop, Mobile

### Browser

Chrome, Firefox

### OS

Windows

**Comment by donmccurdy** [comment] 2022-12-21 13:58
If there's nothing special about the code, could you create a reproduction of the issue using _just_ the static texture on a THREE.SphereGeometry? The demo above has far more code than I can help you debug, including OpenLayers and React Three Fiber, which makes it very hard for us (or you!) to narrow down the cause. 

Without a simple way to reproduce the issue I think we have to consider this a "help request" and close it, since we support those only in our other discussion locations:

- [questions](https://stackoverflow.com/questions/tagged/three.js)
- [discord](https://discord.gg/56GBJwAnUS)
- [forum](https://discourse.threejs.org/)

**Closed by donmccurdy** 2022-12-21 13:58 UTC

**Comment by MeRahulAhire** [comment] 2022-12-22 09:04
@mrdoob Oh sorry, I forgot  to include my code sandbox demo. Here you go - https://codesandbox.io/s/ol-r3f-99e1gs

Can you please tell me what's happening here?
