### ISSUE TITLE
webgl_loader_gltf memory problem

### ISSUE THREAD

**Issue by harry-liu** [mrdoob/three.js#13037] opened 2018-01-04 09:04 UTC
##### Description of the problem

in this tutorial, after switch models for many times the memory is grow quickly, is there any way to fix it?

https://threejs.org/examples/webgl_loader_gltf.html

##### Three.js version

- [ ] Dev
- [x] r89
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by looeee** [comment] 2018-01-04 09:19
Confirmed  on Windows 10, Chrome Version 64.0.3282.71 (Official Build) beta (64-bit).

RAM usage is steady about 120mb, but every time I switch models GPU memory use jumps ~200mb. 
Pretty soon it gets maxed out and then I get a black screen with the dreaded "Rats! Webgl hit a snag" message.

**Comment by takahirox** [comment] 2018-01-04 09:27
The issue confirmed.

That example creates a scene and a renderer when switching model.
I speculate old resources aren't disposed correctly.

I'll look into later...

**Comment by donmccurdy** [comment] 2018-01-04 16:33
I wonder if we should simplify the glTF examples... right now they’re more unit tests than anything else, and not a very helpful reference for developers... opened https://github.com/mrdoob/three.js/issues/13041

**Comment by mrdoob** [comment] 2018-01-05 00:36
Closing this in favour of #13041

**Closed by mrdoob** 2018-01-05 00:36 UTC
Labels: Bug

**Comment by takahirox** [comment] 2018-01-05 14:59
I confirmed that main source of the issue is old resources aren't released.
Probably it wouldn't be better to switch model in an example, releasing all unnecessary resources with `.dispose()` is a bit complicated for users.
So, I think #13041 is one of the best ways for us.

(But I'm still wondered why old `WebGLRenderer` instance isn't automatically released... who holds the reference?)

BTW I found one minor feedback about resource management, I'll make PR later.
