### ISSUE TITLE
PMREMGenerator EnvMaps only work with one renderer

### ISSUE THREAD

**Issue by njarraud** [mrdoob/three.js#19114] opened 2020-04-12 04:10 UTC
##### Description of the problem

I don't know if it is expected or if I miss something, but it looks like the envmap textures generated by PMREGenerator and the renderer specified at that time cannot be re-used with another renderer.

In this example, the envmap is generated using **renderer**.
If the scene is rendered with **renderer2**, it doesn't work.
* [jsfiddle](https://jsfiddle.net/uhzg3Lyv/2/)

Replace `var pmremGenerator = new THREE.PMREMGenerator( renderer );`
by `var pmremGenerator = new THREE.PMREMGenerator( renderer2 );`
on line 49 to check the difference.

##### Three.js version

- [x] Dev
- [x] r115

##### Browser

- [x] All of them

##### OS

- [x] All of them

**Comment by sciecode** [comment] 2020-04-12 04:45
You can't share resources (texture in this case) between two `WebGLRenderingContexts`.

Refer to https://stackoverflow.com/a/9123699/2620080

**Comment by njarraud** [comment] 2020-04-12 06:24
All right. Independently from the memory usage, everything else is working fine though. That is the only issue.

**Comment by Mugen87** [comment] 2020-04-12 08:49
Duplicate of #18976.

**Closed by Mugen87** 2020-04-12 08:49 UTC

**Comment by sciecode** [comment] 2020-04-12 09:02
By the way, this is not a duplicate of #18976.

This is about sharing a texture between WebGL contexts, which is impossible due to WebGL limitations. The other issue was about using the same instance of `PMREMGenerator` for multiple contexts, which was fixed with your PR.

Issue should still be closed, because there's nothing we can do about it. But I just wanted to be clear about it.

**Comment by sciecode** [comment] 2020-04-12 09:05
By the way, this is not a duplicate of #18976.

This is about sharing a texture between WebGL contexts, which is impossible due to WebGL limitations. The other issue was about using the same instance of `PMREMGenerator` for multiple contexts, which was fixed with your PR.

Issue should still be closed, because there's nothing we can do about it. But I just wanted to be clear about it.

**Comment by njarraud** [comment] 2020-04-12 09:08
@sciecode No problem to close it. I also think that this is not a duplicate of #18976.

**Comment by Mugen87** [comment] 2020-04-12 09:19
@sciecode I see this a bit different since the issue I linked was focused about the valid combinations of `PMREMGenerator` and `WebGLRenderer`. Hence, I think this discussion belongs to it..
