### ISSUE TITLE
WebGPURenderer: `MeshNormalMaterial` should not be tone mapped 

### ISSUE THREAD

**Issue by WestLangley** [mrdoob/three.js#28831] opened 2024-07-07 23:00 UTC
### Description

__WebGLRenderer__:

`MeshNormalMaterial` inherits the `.toneMapped` property as `true`, but the material omits the tone mapping shader chunks, so the material is never tone mapped.

This is the correct behavior. We never want the material to be tone mapped.

__WebGPURenderer__:

`MeshNormalMaterial` responds to tone mapping. It should not. This needs to be fixed.

Note: There are other problems with `MeshNormalMaterial` that cause the material to be washed out when rendered with `WebGPURenderer`. That will be addressed in a separate PR after this issue is resolved.

### Reproduction steps

1.
2.
3.

### Code

```js
// code goes here
```

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/g3atw6k5/)
* [jsfiddle-dev](https://jsfiddle.net/hjqw94c5/)

### Version

r167dev

**Comment by sunag** [comment] 2024-07-08 04:28
This is not a bug, `.material.toneMapped=false` and `material.colorSpaced=false` are not supported by `WebGPURenderer`. https://github.com/mrdoob/three.js/pull/27880 https://github.com/mrdoob/three.js/pull/28779#discussion_r1661264665 https://github.com/mrdoob/three.js/pull/27238#issuecomment-1983881679

**Comment by Mugen87** [comment] 2024-07-08 08:44
Maybe it's important to highlight once more that `WebGPURenderer` does not support inline tone mapping and color space conversion. Hence, it is not possible to control which materials should be tone mapped or not. I think this is a good change since it solves #23019 and makes the tone mapping and color space step more consistent.

So `WebGPURenderer` always handles tone mapping and color space conversion as a separate render pass.

**Comment by Mugen87** [comment] 2024-07-08 08:45
The main purpose for `MeshNormalMaterial` is to save normals in a render target for further processing. That fact that it can be used as a material for rendering is a nice side effect but not its main purpose. So retaining the visual look of `MeshNormalMaterial` is not negligible, imo.

**Comment by WestLangley** [comment] 2024-07-08 15:50
WebGLRenderer on the left; WebGPURenderer on the right. No tone mapping applied.

<img width="762" alt="Screenshot 2024-07-08 at 11 39 38 AM" src="https://github.com/mrdoob/three.js/assets/1000017/0de3070a-6245-4998-9fbb-1e30896bdf23">

IMHO, I do not think this is acceptable. By convention, the packed normal is interpreted as a color in sRGB color space.

**Comment by WestLangley** [comment] 2024-07-08 16:05
>Maybe it's important to highlight once more that WebGPURenderer does not support inline tone mapping and color space conversion. Hence, it is not possible to control which materials should be tone mapped or not.

Hmm... I am inclined to think that is too restrictive. If all materials are tone mapped, I think we have to have a way to disable it.

Think of overlay text or a heads-up display. That would not normally be tone mapped.

Nor should something like `AxesHelper` -- and `MeshLineMaterial`. Also `MeshBasicMaterial` in certain cases.

Tone mapping can cause significant hue shifts. So can exposure control.

**Comment by sunag** [comment] 2024-07-08 16:19
> Think of overlay text or a heads-up display. That would not normally be tone mapped.

HUD is normally used in another `render-pass`, so it won't be affected.

**Comment by WestLangley** [comment] 2024-07-08 16:29
What about the other issues I mentioned?

**Comment by Mugen87** [comment] 2024-07-08 16:34
The `toneMapped` property was coupled to inline tone mapping. There is no way to support this property when tone mapping is applied as a pass.

@WestLangley I don't think we can achieve what you are asking for without changing some fundamentals in the renderer. I do not vote for doing this since tone mapping and color space conversion is now more correctly implemented than in `WebGLRenderer`.

**Comment by Mugen87** [comment] 2024-07-08 16:37
There was always a difference when tone mapping was applied inline and when used in FX workflows via `OutputPass`. This difference is now finally resolved in `WebGPURenderer`.

**Comment by sunag** [comment] 2024-07-08 16:55
Since `AxesHelper` overlaps all other objects, this could be solved with a `render-pass` as well.

![image](https://github.com/mrdoob/three.js/assets/502810/10afbe3f-9d32-49ff-a04e-172eba8ddb1b)

I believe that other cases could be solved with MRT properties applied to the material and PostProcessing, such as:

```js
material.mrtNode = mrt( { overlay: directionToColor( normalWorld ) } );
```

This is being developed initially here https://github.com/mrdoob/three.js/pull/28833

if we look at the projects from the three.js home page, I think 99% will make better use of the new system, `normals` for visual purposes is more related to our example.

**Comment by WestLangley** [comment] 2024-07-08 17:35
`WebGPURenderer` removes the ability for users to set `material.toneMapped` to `false`, a feature which has been used by `WebGLRenderer` internally -- particularly for objects that do not respond to lights.

Another example use case would be text labels.

**Closed** 2024-07-09 09:19 UTC

**Comment by bhouston** [comment] 2024-07-09 17:34
Normal, depth and velocity materials (and similar utility materials) are intended to be rendered into linear space only - never sRGB and also never tone mapped.  This is because they need to be encoded consistently so that they can be decoded consistently.  Thus toneMapping should never be supported on them.

**Comment by mrdoob** [comment] 2024-07-11 19:30
Should we add more logic in the renderers to automatically render objects that shouldn't be tone mapped in a different pass?

That way we won't need to deprecate `material.toneMapped`... 🤔

**Comment by donmccurdy** [comment] 2025-02-28 03:31
> Should we add more logic in the renderers to automatically render objects that shouldn't be tone mapped in a different pass?

I think that could be a good option.

I'm also wondering if we may need to bring back the option of rendering directly to the drawing buffer (with tone mapping and color space transforms in the fragment shader), simply for performance reasons. If so that would be another option here.

**Comment by WestLangley** [comment] 2025-02-28 03:52
>I'm also wondering if we may want to bring back the option of rendering directly to the drawing buffer (with tone mapping and color space transforms in the fragment shader).

Yes. I support that. I think that should be the default -- just as it is in `WebGLRenderer`. Granted, blending is not performed in linear color space in that case, but I think 99% of users do not care about those artifacts. Users who do care, can use post-processing. This would also allow `material.toneMapped` to be supported again, allowing for greater flexibility.

**Comment by bhouston** [comment] 2025-02-28 13:22
It is 2x faster or better than using post-processing in my original tests - in part because it can use RGBA8 buffers rather than multiple FP buffers: https://github.com/mrdoob/three.js/pull/8250

**Comment by sunag** [comment] 2025-03-06 03:16
Just wanted to clarify some pros and cons and why `material.toneMapped` is deprecated in WebGPURenderer.

Pros
- Pipeline optimized for refractions, we can have access to what has already been rendered in linear-color-space, so for materials with transmission or refractions we do not need to render opaque materials twice, this has proven to be much more performant for PBR.
- Transparent materials respect tone mapping and color conversion since they not are applied in overlay with opaque materials as it was inline.
- It is important that the changes are more aligned with future generations of hardware than with hardware that is limited to RGBA8 buffers. In this scenario, PostProcessing is something used in any project, like `bloom` for example and there will certainly not be the load mentioned above.

Cons
- `material.toneMapped` will not be available per material. 

Alternative
- Implement a `renderer.outputNode` where we could control the output similar to what we did in `PostProcessing.outputNode`. https://github.com/mrdoob/three.js/pull/30387#issuecomment-2629246834

Just wanted to make a note of this. `MeshNormalMaterial`, `MeshDepthMaterial`, `MeshDistanceMaterial` are meant to be used in calculations in PostProcessing or during the beauty pass, if the user is mixing them with the beauty pass with others meshes for aesthetic purposes, they are certainly creating a project for fun and not serious math. That's why our recommendation is to use MRT or `RenderTarget` for this purpose.

**Comment by WestLangley** [comment] 2025-03-06 04:33
Thank you, @sunag, for your comments.

I use `MeshNormalMaterial` for debugging normals. Rendering the correct colors is important in this case.

Regarding tone mapping, only lit materials need to be tone mapped -- not the entire scene. You wouldn't typically tone map a solid scene background color,  scene clear-color, a heads-up display, `LineBasicMaterial`, or `MeshBasicMaterial` (unless it was reflecting an HDR environment). This is why `material.toneMapped` is important.

**Comment by donmccurdy** [comment] 2025-03-10 04:01
For me the overriding concern is that color management and tone mapping must be cheap for mobile and WebXR devices with WebGPURenderer. When an application's performance budget can afford lighting, tone mapping should be near-zero extra cost. If that's not possible with post-processing (I don't have hardware to test this; do we feel #30387 has solved it?) then I think we really need to find a solution for the performance, and materials used for debugging like MeshNormalMaterial can be considered downstream of that problem.

That said... I don't feel that per-material opt-out for tone mapping is the only solution here at all, we don't have to take the same approach as WebGLRenderer if that's a concern. 

Something like `renderer.outputNode` would be interesting. An API to move some _objects_ (as opposed to materials) to a different render pass, and to disable tone mapping on that pass, could work. That would be helpful for rendering UI in addition to these debugging materials.

**Comment by WestLangley** [comment] 2025-03-26 04:08
How about if we inline tone mapping in `WebGPURenderer` -- like we do for `WebGLRenderer` -- and apply the color space transform in `OutputPass`?

This allows `material.toneMapped` to be supported. Also, tone mapping does not change the linear color space, so blending is still correctly implemented with linear colors.

This way, we are able to tone map only the materials that respond to light -- not the entire scene.

**Comment by sunag** [comment] 2025-03-26 05:41
> Regarding tone mapping, only lit materials need to be tone mapped -- not the entire scene. You wouldn't typically tone map a solid scene background color, scene clear-color, a heads-up display, LineBasicMaterial, or MeshBasicMaterial (unless it was reflecting an HDR environment). This is why material.toneMapped is important. 

I don't think all users are looking for this in the same way https://github.com/mrdoob/three.js/pull/26208#issuecomment-1720376041, https://github.com/mrdoob/three.js/pull/26857#issuecomment-1737401251. I created an example showing how to use fog and background without tone-mapping in a scene with tone-mapping using TSL https://threejs.org/examples/?#webgpu_custom_fog_background. It is recommended that HUDs be made in another render-pass, even to enable advanced effects such as blurring or blending like overlay. Inline tone-mapping does not solve what I mentioned above https://github.com/mrdoob/three.js/issues/28831#issuecomment-2702686424 and TSL already supports blending background and fog without tone-mapping, the only strong reason I see is about skipping post-processing, which seems to me to be far from the reality of the current graphics generation but if we are going to add it as an alternative like `renderer.outputNode` then we can add this support for `material.toneMapped`.
