### ISSUE TITLE
GLTFLoader: Doesn't work in Web Worker

### ISSUE THREAD

**Issue by rduboveckij** [mrdoob/three.js#18765] opened 2020-02-27 22:27 UTC
##### Description of the problem

I have been using GLTFLoader with DracoLoader to load my GLTF model and it simply doesn't without hacks. 

There are errors that I have dealt with:

- Refused to execute script from 'blob:http://localhost/70c5a9eb-f362-41b3-a00a-fdbdfd5159c8' because its MIME type ('') is not executable.
Fix is next: `this.workerSourceURL = URL.createObjectURL( new Blob( [ body ], { type: 'text/javascript' } ) );`

 - ReferenceError: document is not defined
    at ImageLoader.load (http://localhost/ed0f7af9865be3c65a71.worker.js:42943:15)
    at TextureLoader.load (http://localhost/ed0f7af9865be3c65a71.worker.js:43068:10)
    at http://localhost/ed0f7af9865be3c65a71.worker.js:59389:12
    at new Promise (<anonymous>)
Fix is next: `this.textureLoader = typeof WorkerGlobalScope !== 'undefined' && self instanceof WorkerGlobalScope ? new ImageBitmapLoader( this.options.manager ) : new TextureLoader( this.options.manager );`

- Uncaught (in promise) Error: context.requestAnimationFrame is not a function
    at Wheel.worker.ts:69
    at _onError (GLTFLoader.js:118)
Fix is next: `animation.setContext( window || self );`

Partially related to https://github.com/mrdoob/three.js/issues/15556

##### Three.js version

- [ ] Dev
- [x] r113
- [ ] ...

##### Browser

- [] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [x] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)
Any device that supports https://caniuse.com/#feat=offscreencanvas
I am testing on my Pixel 4XL

**Comment by takahirox** [comment] 2020-02-27 22:42
In addition to them, I think the following line in `.loadTexture()` can cause an error because of no `window` in workers.

```
var URL = window.URL || window.webkitURL;
```

**Comment by rduboveckij** [comment] 2020-02-27 23:45
> In addition to them, I think the following line in `.loadTexture()` can cause an error because of no `window` in workers.
> 
> ```
> var URL = window.URL || window.webkitURL;
> ```

I have

**Comment by ECorreia45** [comment] 2020-08-27 05:32
Any solution to this yet?

**Comment by stickyfingies** [comment] 2022-08-24 17:40
Can we merge these changes?  The change set is small and unlikely to cause conflicts.  And, it would tremendously help me out in a project I'm currently working on.  I think there is an active demand for running GLTFLoader on a separate DOM-less thread.

**Comment by mrdoob** [comment] 2022-08-24 18:58
@donmccurdy @takahirox what do you guys think we should do here?

**Comment by donmccurdy** [comment] 2022-08-24 19:28
Supporting GLTFLoader in environments like Web Workers, Node.js, and perhaps Deno are all in the same category for me — I would like GLTFLoader to work in those environments, but I'm not using it with them myself, and without environment-specific test coverage it is very easy for regressions to happen in those environments. So I think we have to call that "best effort" support at this point.

Still, I'm happpy to approve small PRs that fix references to resources not available in Web Workers, e.g. `window → self`. 

***

Aside — I would just flag that GLTFLoader does no heavy lifting on the main thread, it uses internal Web Workers (via DRACOLoader and KTX2Loader) for heavy tasks. If you are trying to optimize your main thread by doing model loading on a Worker, that makes a lot of sense for OBJLoader but probably won't help much for GLTFLoader. Unless you are also rendering in the Web Worker, with OffscreenCanvas, in which case that is the right choice.

**Comment by stickyfingies** [comment] 2022-08-24 19:47
> Unless you are also rendering in the Web Worker, with OffscreenCanvas, in which case using GLTFLoader in the same Worker makes sense.

Specifically, serializing scene data (images, geometries, materials) from the `main thread` --> `render thread` is possible but impractically slow.  Getting images across the CPU border means:

1) load GLTF model on the main thread
2) for all textures, render them to an html canvas
3) extract canvas data with `getImageData()`
4) transfer the image data via `postMessage()` to the render thread
5) finally, reconstruct the images using a `DataTexture` in the render thread.

Somewhere during this process, `readPixels()` is called to extract the texture data.  On integrated GPU systems (MSI P15, Intel Core i7), moving this memory around isn't a big problem.  On dedicated devices, however (MSI P15, Nvidia GTX 1650) the `readPixels` operation takes orders of magnitude longer (I presume this is because texture data must pass through PCI).

In this context, being able to load `.gltf` models directly from a worker thread is incredibly invaluable, as there is no longer any need for this crazy image (de)serialization bullshit :laughing:

@donmccurdy @takahirox @mrdoob I'll ping you in small PRs that fix references to resources not available in Web Workers, e.g. window → self.

**Comment by jespertheend** [comment] 2023-09-28 19:18
We've successfully been using GLTFLoader and DRACOLoader inside a web worker on https://narrow.one/ for a few years now.
If I remember correctly, the main thing I had to do to make this work was to make use of the [Module Workers Polyfill](https://gist.github.com/developit/220246bc99044af74a6680ce13284f59#module-workers-polyfill-) to support Safari, which doesn't allow you to create nested workers.
It seemed to be supported in Chrome out of the box. Although I did run into the "MIME type ('') is not executable" error just now, not sure why I haven't run into that earlier.

To also make GLTFLoader and DRACOLoader work inside Deno I had to apply the following fixes:
- Rewrite all "three" imports to the absolute path of threejs, import maps are not supported in workers
- Change `new Worker( this.workerSourceURL );` to `new Worker( this.workerSourceURL, {type: "module"} );` inside DRACOLoader, classic workers are not supported in Deno.
- Add the `type: "text/javascript"` to `URL.createObjectURL`, which was already mentioned above
- #26863

**Comment by donmccurdy** [comment] 2024-11-05 15:14
Small PRs fixing issues with using GLTFLoader in Web Workers, Node.js, or Deno are welcome. Some adaptations to other runtime environments (like replacing all imports) are out of scope for three.js and would need to be handled at the application level, or by forking the loader, as @jespertheend describes. I'm happy to review PRs, but unless someone has bandwidth to work on support for these environments (I do not) I'd prefer to close the issue.

**Closed by donmccurdy** 2024-11-05 15:14 UTC
Labels: Enhancement
