### ISSUE TITLE
SpotLight.target stopped working starting from r69.

### ISSUE THREAD

**Issue by RunninglVlan** [mrdoob/three.js#6522] opened 2015-05-07 22:23 UTC
Prior to r69 SpotLight.target was being added to the scene when SpotLight or its parent was added to it, not anymore.

Because of that changing SpotLight.target has no effect on the direction of the light anymore. Right now as a workaround SpotLight.target should be added to the scene manually, then light's direction will change when SpotLight.target.position will be updated.

**Comment by WestLangley** [comment] 2015-05-07 23:41
Duplicate of https://github.com/mrdoob/three.js/issues/5555.

**Closed** 2015-05-08 00:14 UTC
Labels: Duplicate
