### ISSUE TITLE
X, Y and Z axes as default values in three.js core

### ISSUE THREAD

**Issue by Wilt** [mrdoob/three.js#8459] opened 2016-03-24 10:04 UTC
##### Description of the feature request/enhancement

I notice that I often have to use xAxis, yAxis and zAxis in my three.js application.
Because of this I repeatingly end up creating new `Vector3` objects whenever I need these axes, which seems a bit unnecessary. Would it be possible to make default axes part of the core?
Something like:

```
THREE.Default.XAxis = new THREE.Vector3( 1, 0, 0 );
THREE.Default.YAxis = new THREE.Vector3( 0, 1, 0 );
THREE.Default.ZAxis = new THREE.Vector3( 0, 0, 1 );
```

Or alternatively: 

```
THREE.Axes.X = new THREE.Vector3( 1, 0, 0 );
THREE.Axes.Y = new THREE.Vector3( 0, 1, 0 );
THREE.Axes.Z = new THREE.Vector3( 0, 0, 1 );
```

Similarly there is the `THREE.Object3D.DefaultUp = new THREE.Vector3( 0, 1, 0 );`
this could then maybe be replaced with:

```
THREE.Default.Up = THREE.Default.YAxis
```

I can make a pull request, but I just need some guidance on where to put them.

They could immediately be used in the three js code. For example in the `THREE.Object3D` methods `rotateX`, `rotateY` and `rotateZ`:

```
rotateX: function () {
    var v1 = THREE.Default.XAxis;
    return function ( angle ) {
        return this.rotateOnAxis( v1, angle );
    };
}(),

rotateY: function () {
    var v1 = THREE.Default.YAxis;
    return function ( angle ) {
        return this.rotateOnAxis( v1, angle );
    };
}(),

rotateZ: function () {
    var v1 = THREE.Default.ZAxis;
    return function ( angle ) {
        return this.rotateOnAxis( v1, angle );
    };
}(),
```

And probably on more places.

**Comment by bhouston** [comment] 2016-03-24 12:51
I've done this pattern before.  I usually put these on the Vector3 class or what ever class type the consts are:

```
THREE.Vector3.Zero = new THREE.Vector3( 0, 0, 0 );
THREE.Vector3.XAxis = new THREE.Vector3( 1, 0, 0 );
...
THREE.Vector4.WAxis = new THREE.Vector4( 0, 0, 0, 1 );
...
THREE.Box3.Empty = new THREE.Box3();
...
THREE.Sphere.Unit = new THREE.Sphere( 1, new THREE.Vector3.Zero.clone() );
```

But with JavaScript this is all fairly dangerous to do because these values are not truly const, so I am not sure this is a great idea.

**Comment by tschw** [comment] 2016-03-24 20:31
Useful suggestion IMO, I frequently end up defining those constant somewhere in user code :+1:

@bhouston 
> I've done this pattern before. I usually put these on the Vector3 class or what ever class type the consts are

Yes, better place.

> But with JavaScript this is all fairly dangerous to do because these values are not truly const, so I am not sure this is a great idea.

Could [`Object.freeze`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/freeze) them. In this case, a failed attempt to modify the objects throws in strict mode. Would still yield confusing behavior when embedded by reference in relaxed mode. 

Something like this might work to detect misuse from inside the library

```javascript
THREE.Box = ( function() {
    'use strict'; // to report misuse of frozen objects

    var Box = function Box( ... ) { 
        // ...
    };

    Box.prototype = {
        // ...
    };

    Box.Empty = Object.freeze( new Box() );
    return Object.freeze( Box );
} )();
```

or going for strict mode globally altogether. It might save us from a bunch of bugs, after all.

**Comment by Wilt** [comment] 2016-03-29 07:56
@bhouston  You say fairly dangerous, but it is of course the responsibility of the developer to use the constants correctly. But @tschw his suggestion could nicely solve it all together.

**Comment by tschw** [comment] 2016-03-29 12:29
It was just a thought. Above example is sketchy and won't work. It would work for `Vector`s but not for `Box`. In this case we'd have to run a `deepFreeze` function (as in the MDN article cited above) or also
```javascript
Object.freeze( Box.Empty.min ); 
Object.freeze( Box.Empty.max );
```
.

**Comment by mrdoob** [comment] 2016-03-29 16:03
> or going for strict mode globally altogether. It might save us from a bunch of bugs, after all.

We do use `'use script'` already... https://github.com/mrdoob/three.js/blob/master/build/three.min.js#L2

`Object.freeze()` would be good to use at some point thought. I often have typo bugs like `renderer.atuoClear = true`.

**Comment by tschw** [comment] 2016-03-29 16:34
> Last time I checked Object.freeze() produced less performant code though.

Oh interesting, you checked on it already! I guess that was about freezing the constructors / prototypes?

At least V8 is supposed to use it for optimization (don't remember where I read it - but it was an official source). Theoretically, knowing stuff to be immutability can allow aggressive optimization, so I would have expected the opposite.

If still the case with current browsers, we should be careful. I guess just freezing the constants, which would catch the most vicious case (object gets passed and then changed somewhere), might still be possible with an acceptable / below measurable penalty. You can then mischievously 
```javascript
Box.Empty = nonemptyBox;
```
but hey, *who does that?!* It's not exactly a frequent error :-).

**Comment by bhouston** [comment] 2016-03-29 16:40
@tschw the error that i see that is common is that someone will pass in the Axis vector into a function that manipulates it and then you no longer have a constant.  Something like this seems very easy to do:

```
var rotatedXAxis = Vector3.XAxis.applyMatrix4( rotationMatrix );

var myObjectTranslation = Vector3.XAxis.subtract( new Vector3( 10, -1, 0 ) );
```

But I am still okay adding constants like this.

**Comment by bhouston** [comment] 2016-03-29 16:42
BTW the best way to check for speed differences is jspref.com: Freeze seems to run pretty fsat these days in Chrome - although once it as very slow: https://jsperf.com/freeze-vs-seal-vs-normal/3

**Comment by bhouston** [comment] 2016-03-29 16:55
@tschw, one of the most common coding errors in Clara.io by far has been the unintential manipulation of member variables of classes.  Someone meant to read a member variable of a class but ended up manipulating that variable and passed it back to another function, and now things appear to work for a little bit but really everything is massively screwed up.  The issue is that copying variables is costly but not copying makes it very easy to make these types of errors.  Too bad there wasn't a const keyword in JavaScript. :)

**Comment by tschw** [comment] 2016-03-29 18:39
@bhouston 
> the error that i see that is common is that someone will pass in the Axis vector into a function that manipulates it
> [...] one of the most common coding errors in Clara.io by far has been the unintential manipulation of member variables of classes. Someone meant to read a member variable of a class but ended up manipulating that variable and passed it back to another function, and now things appear to work for a little bit but really everything is massively screwed up.

@tschw
> [...] the most vicious case (object gets passed and then changed somewhere) [...]

Yes, I think we agree that freezing the constant objects would be quite useful. Someone accidentally assigning a new object to the constructor's property (= redefining the static member) seems a lot less likely and easier to track than indirect change of the object passed somewhere by reference, thus I don't think there's that important to freeze the constructors.

I find it highly desirable to have code like this
> `var myObjectTranslation = Vector3.XAxis.subtract( new Vector3( 10, -1, 0 ) );`

throw up. In particular because it doesn't read wrong at all and becomes even less obvious when a parameter other than `this` is used for passing the object.

@bhouston 
> BTW the best way to check for speed differences is jspref.com

I'm using it when I can (see [here](https://github.com/mrdoob/three.js/blob/master/src/math/Interpolant.js#L55-L59)). It used to be offline for a long time and has many bugs. The penalty for `freeze` looks very much acceptable again in Firefox 42. I measure 0.62% - and it's an excess test. Jsperf hangs trying to publish the result, so I'm posting it here. Also, the captcha is currently bugged, so I can't modify the test to check on strict mode :(.

Another thing to be keep in mind is, that jsperf is only concerned about overall throughput - not necessarily about producing a steady frame rate - so you gotta watch out when it comes to garbage being produced. But there shouldn't be any in this particular case and we all know that, of course :).

> Too bad there wasn't a const keyword in JavaScript. :)

There is one now (in ES 2015), but it won't help: It only assures the name is not rebound to another object - we'd still have to freeze the object to ensure it doesn't get changed. Like a pointer to non-const inside a const object makes the pointer const but does not require a const pointee. There is no concept of a "value" like we have in C/C++, which would allow for a reasonably practical definition of recursive immutability.

**Comment by Wilt** [comment] 2016-05-16 13:34
@MrDoob If I create a pull request for such a feature, would you consider merging it?

**Comment by mrdoob** [comment] 2016-05-16 15:29
I would be nice first identify all the other places...

> And probably on more places.

**Comment by Wilt** [comment] 2016-05-17 09:08
@MrDoob here they come:

1) `THREE.Object3D`
`THREE.Object3D.rotateX`:
https://github.com/mrdoob/three.js/blob/master/src/core/Object3D.js#L155
`THREE.Object3D.rotateY`:
https://github.com/mrdoob/three.js/blob/master/src/core/Object3D.js#L167
`THREE.Object3D.rotateZ`:
https://github.com/mrdoob/three.js/blob/master/src/core/Object3D.js#L179

`THREE.Object3D.translateX`:
https://github.com/mrdoob/three.js/blob/master/src/core/Object3D.js#L210
`THREE.Object3D.translateY`:
https://github.com/mrdoob/three.js/blob/master/src/core/Object3D.js#L222
`THREE.Object3D.translateZ`:
https://github.com/mrdoob/three.js/blob/master/src/core/Object3D.js#L234

2) `THREE.MouseControls`:
https://github.com/mrdoob/three.js/blob/master/examples/js/controls/MouseControls.js#L16
https://github.com/mrdoob/three.js/blob/master/examples/js/controls/MouseControls.js#L17

3) `THREE.TransformControls`:
`constructor`:
https://github.com/mrdoob/three.js/blob/master/examples/js/controls/TransformControls.js#L456
https://github.com/mrdoob/three.js/blob/master/examples/js/controls/TransformControls.js#L457
https://github.com/mrdoob/three.js/blob/master/examples/js/controls/TransformControls.js#L458
`this.update`:
https://github.com/mrdoob/three.js/blob/master/examples/js/controls/TransformControls.js#L668
https://github.com/mrdoob/three.js/blob/master/examples/js/controls/TransformControls.js#L669
https://github.com/mrdoob/three.js/blob/master/examples/js/controls/TransformControls.js#L670

4) `THREE.DecalGeometry`:
`computeDecal`
https://github.com/mrdoob/three.js/blob/master/examples/js/geometries/DecalGeometry.js#L211
https://github.com/mrdoob/three.js/blob/master/examples/js/geometries/DecalGeometry.js#L217
https://github.com/mrdoob/three.js/blob/master/examples/js/geometries/DecalGeometry.js#L223

5) `THREE.CubeCamera`:
`constructor`
https://github.com/mrdoob/three.js/blob/master/src/cameras/CubeCamera.js#L18
https://github.com/mrdoob/three.js/blob/master/src/cameras/CubeCamera.js#L28
https://github.com/mrdoob/three.js/blob/master/src/cameras/CubeCamera.js#L38

For now those are the ones I found. 

----------------------

If there would also be negative vectors for xAxis, yAxis and zAxis we could also replace some more, for example in 

1) `THREE.DecalGeometry`:
`computeDecal`
https://github.com/mrdoob/three.js/blob/master/examples/js/geometries/DecalGeometry.js#L212
https://github.com/mrdoob/three.js/blob/master/examples/js/geometries/DecalGeometry.js#L218
https://github.com/mrdoob/three.js/blob/master/examples/js/geometries/DecalGeometry.js#L224

2) `THREE.CubeCamera`:
`constructor`
https://github.com/mrdoob/three.js/blob/master/src/cameras/CubeCamera.js#L23
https://github.com/mrdoob/three.js/blob/master/src/cameras/CubeCamera.js#L33
https://github.com/mrdoob/three.js/blob/master/src/cameras/CubeCamera.js#L43

------------------------------

On top of that the axis could be used to set values. For example in `CubeCamera` is now written:

    cameraPX.up.set( 0, - 1, 0 );   =>  cameraPX.up.copy( Vector3.NegXAxis );
    cameraPX.up.set( 0, - 1, 0 );   =>  cameraPX.up.copy( Vector3.NegXAxis );
    cameraPY.up.set( 0, 0, 1 );    =>  cameraPX.up.copy( Vector3.ZAxis );
    cameraNY.up.set( 0, 0, - 1 );    =>  cameraPX.up.copy( Vector3.NegZAxis );
    cameraPZ.up.set( 0, - 1, 0 );    =>  cameraPX.up.copy( Vector3.NegYAxis );
    cameraNZ.up.set( 0, - 1, 0 );    =>  cameraPX.up.copy( Vector3.NegYAxis );

But I don't think such changes will make things more efficient...

**Comment by WestLangley** [comment] 2016-05-17 09:51
Note that sometimes `new THREE.Vector3( 1, 0, 0 )` is used once in a constructor and then garbage-collected; other times, it is in a closure, so only one instance is created by the method anyway.

Also, `new THREE.Vector3( 1, 0, 0 )` is sometimes used as a _direction_, and other times as a 3D _point_. Be careful what you name it.

**Comment by Wilt** [comment] 2016-05-17 14:39
@WestLangley I get your point, but since there is no `THREE.Vertex3` any more it became hard to distinguish them and the interface became the same for both.

I agree that those `Axis` objects should only be used in case they represent a direction vector not when they represent a point. I believe in all the above examples they represent axes. Please correct me if (and where) you think I am wrong.

**Comment by WestLangley** [comment] 2016-05-17 17:41
@Wilt Where `lookAt( point )` is used. We do not have a `lookIn( direction )` method, likely because it is not really needed.

https://github.com/mrdoob/three.js/blob/master/src/cameras/CubeCamera.js#L23

**Comment by Wilt** [comment] 2016-05-18 09:34
@WestLangley  Good point. Thanks for the comment.

**Comment by killroy42** [comment] 2016-09-29 10:23
Would Object.defineProperty(THREE.Vector3, 'Up', {
  value: new THREE.Vector3(0, -1, 0), configurable: false, enumerable: true, writable: false
}); solve the modification issue?

Personally, the potential for user code interference doesn't bother me, since everything else isn't safe either. THREE.Vector3 can be modified as well as THREE to break everything. We cannot really prevent that.

**Comment by bhouston** [comment] 2016-09-29 12:46
I believe it wouldn't because you could modify the values of X, Y and Z of the Vector3, without modifying the pointer to that Vector3 itself.

**Comment by killroy42** [comment] 2016-09-29 12:50
TBH, we probably want an immutable/functional set of math ops eventually.

**Comment by WestLangley** [comment] 2019-10-19 19:05
I think this proposal was sufficiently debated. Closing.

**Closed by WestLangley** 2019-10-19 19:05 UTC
Labels: Suggestion
