### ISSUE TITLE
ThreeJs ThreeMF loader is blocking the UI while upzipping the 3MF file.

### ISSUE THREAD

**Issue by frederik14** [mrdoob/three.js#20206] opened 2020-08-28 09:36 UTC
##### Description of the problem

ThreeJs ThreeMF loader is blocking the UI while upzipping the 3MF file.

```javascript
try {
	zip = new JSZip( data ); // eslint-disable-line no-undef
} catch ( e ) {
	if ( e instanceof ReferenceError ) {
		console.error( 'THREE.3MFLoader: jszip missing and file is compressed.' );
		return null;
	}
}
```

According the the [JSZip documenation](https://stuk.github.io/jszip/documentation/howto/read_zip.html) I assume it would be better to unzip the container asynchronously not to block the UI.

##### Three.js version

- [x ] Dev
- [ ] r120
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment] 2020-08-28 09:49
Even when doing this task asynchronously, it's still done in the main thread and thus blocking the UI.

**Comment by frederik14** [comment] 2020-08-28 10:33
Depends on how JSZip is written, but I assume it releases the main thread after every chunck making the UI responsive. Explained [here](https://www.youtube.com/watch?v=vn3tm0quoqE).

**Comment by Mugen87** [comment] 2020-08-28 10:48
Can you please prove your assumption with a concrete live example?

Notice that the upgrade of  JSZip was tried several times. It was not possible to finish it because it's necessary to retain the sync usage of `Loader.parse()`. More information: https://github.com/mrdoob/three.js/pull/19097#issuecomment-617740966

**Comment by frederik14** [comment] 2020-08-28 13:07
Thanks for the reference! Tentone clearly had the same idea as me. But indeed I don't think we will be able to keep the sync behavior of the loader.parse() external API. To fix it I would suggest to extend the external API with a parseAsync() function. The original parse function of the threeMf loader will still need to use a sync unzip function. I don't know if JSZip 3 still has this behavior? I will get started creating a live example proving the performance benefit.

**Comment by Mugen87** [comment] 2020-08-28 13:11
> The original parse function of the threeMf loader will still need to use a sync unzip function. I don't know if JSZip 3 still has this behavior?

When I remember correctly, it was removed. Hence it suggested to look for a different library which provides a sync method.

**Comment by frederik14** [comment] 2020-08-28 15:39
I came to the conclusion that loading the zip file indead blocks the thread for a couple of milliseconds [jsfiddle](https://jsfiddle.net/y9d6wrs2/91/). But opening the 3mf file takes very little time compared to the total 3mf loading time. If the loader would be async it could do all the small actions in the js event queue. This would update the UI in between every small parsing action. ([js event queue explained](https://www.youtube.com/watch?v=8aGhZQkoFbQ))

**Comment by donmccurdy** [comment] 2020-08-28 17:58
Might be a good candidate for https://github.com/mrdoob/three.js/pull/19650? We could keep JSZip but move it to a worker.

**Comment by Mugen87** [comment] 2020-11-12 14:48
After a closer performance analysis of `3MFLoader.parse(), the actual overhead does indeed not come from the unzip operation. `DOMParser.parseFromString( )` as well as the processing of the XML document takes way more time than anything else. In `webgl_loader_3mf_materials`, unzipping takes 2.6 ms whereas the rest of `parse()` takes 1.85 seconds.

So similar to `ColladaLoader`, the actual overhead is produced by parsing and processing XML. Hence, marking this issue as a duplicate of #11746.

**Closed by Mugen87** 2020-11-12 14:48 UTC
Labels: Loaders
