### ISSUE TITLE
Key animations don't stop at last frame

### ISSUE THREAD

**Issue by AAAIII** [mrdoob/three.js#8446] opened 2016-03-22 23:26 UTC
##### Description of the problem 

Since the new animation system I can't make my key animations stop at their last frame. Most of the Three.js examples have animations with a infinite loop and so the bug is not visible. My animations are made to run once, but they get resetted to the first frame after the one loop. Even when I use *.time = 1;* command, they still reset to the first frame.   

##### Three.js version

- [x] r75
- [x] r74
- [x] r73

##### Browser

- [x] All of them

##### OS

- [x] All of them

**Comment by tschw** [comment] 2016-03-23 23:48
Can't reproduce a bug in `r74`. 

`LoopOnce` appears to work just fine in http://threejs.org/examples/#webgl_animation_skinning_morph .
You might want to set `.clamp = true` if you want the state of the last frame to be held.

**Comment by AAAIII** [comment] 2016-03-24 21:52
I tryed _.clamp = true;_, _.clampWhenFinished =  true;_ and stil the animation gets reset to the first frame. I even tryed with _THREE.LoopOnceClamp_. I'll make a fiddle with my animation to show the bug.

**Comment by AAAIII** [comment] 2016-04-04 21:42
I found bugged animations in some Three.js examples. You can see these on http://threejs.org/examples/#webgl_loader_json_blender, http://threejs.org/examples/#webgl_loader_collada, http://threejs.org/examples/#webgl_loader_collada_skinning, http://threejs.org/examples/#webgl_loader_fbx and http://threejs.org/examples/#webgl_loader_json_blender. In all these examples you can see bugged animations that jump from the last frame to the first frame.

**Comment by tschw** [comment] 2016-04-06 12:01
> I tryed .clamp = true;, .clampWhenFinished = true; and stil the animation gets reset to the first frame. I even tryed with THREE.LoopOnceClamp. 

`.clampWhenFinished = true` should be enough.

The animation stops correctly at the last frame. The loader duplicates the first frame as the last in the morph target case, however.

    https://github.com/mrdoob/three.js/blob/master/src/animation/AnimationClip.js#L143-L150

I'm not sure how to best solve it, so that no case breaks. 

/ping @bhouston

**Comment by bhouston** [comment] 2016-04-06 13:41
A) We could clamp to the frame just before the last if it isn't looking?  I think that would work.  But then clamp would have  different end point than looping and that may be problematic.

B) We could also take a flag into the CreateFromMorphTargetSequence() function that controls as to whether the clip should be ```makeLoopable``` (e.g. duplicated last frame as first)?  I think this second solution is probably best.

I guess there was probably special case code to handle these two situations before?  I suspect there was and it was something like possible solution A above.  I unfortunately do not have time today to look into this.

**Comment by tschw** [comment] 2016-04-15 01:03
@AAAIII 
> I found bugged animations in some Three.js examples.

I read into these as well. Turns out those are a very different story:

In http://threejs.org/examples/#webgl_loader_json_blender

The big guy in the middle (the one that has a jumpy animation) still uses pre `r73` animation. The many little guys use the current animation system and don't jump. I guess that might have been a compatibility test. 

http://threejs.org/examples/#webgl_loader_collada
http://threejs.org/examples/#webgl_loader_collada_skinning

both still use pre `r73` animation.

http://threejs.org/examples/#webgl_loader_fbx

uses the current animation system, and I don't see anything obviously wrong - except for the animation might be a little quirky. 

> In all these examples you can see the bugged animations that jump from the last frame to the first frame.

Looks like the opposite case and the code I just made optional is missing pre `r73`.

**Comment by AAAIII** [comment] 2016-04-16 22:05
> http://threejs.org/examples/#webgl_loader_fbx 
> uses the current animation system, and I don't see anything obviously wrong - except for the animation might be a little quirky. 

I watched that animation in slow motion (low fps) and could see that some frames are getting skipped. That animation doesn't look smooth but glitched. That animation does look smooth in Maya .

**Comment by tschw** [comment] 2016-04-16 22:11
If your animation stops at the last frame setting `noLoop` to `true`, you should really open a new ticket and close this one.

**Comment by AAAIII** [comment] 2016-04-20 17:00
I tryed to set `noLoop` to true in `r76` and everything works fine only when I use `THREE.LoopOnceClamp`. Without `THREE.LoopOnceClamp` it doesn't work. Thanks for the fix.

**Comment by tschw** [comment] 2016-04-20 17:21
`THREE.LoopOnceClamp` does not exist (it only existed as a leftover edit). Set `.clampWhenFinished` to true.

**Comment by AAAIII** [comment] 2016-04-20 17:42
Okay, I got it working with `THREE.LoopOnce`, `.clampWhenFinished` and `noLoop` set to `true`. Thanks for all the help.

**Closed** 2016-04-20 17:46 UTC

**Comment by tschw** [comment] 2016-04-20 19:38
Thanks for reporting and for your patience!
