### ISSUE TITLE
UniformsUtils.clone(...) doesn't perform a deep-copy on Array properties

### ISSUE THREAD

**Issue by epmik** [mrdoob/three.js#30219] opened 2024-12-27 10:13 UTC
### Description

According to the documentation UniformsUtils.clone(...) clones an object performing a deep-copy. However that is not the case when the object contains an Array. To clone/copy an Array, The slice() function is used () and the slice() function return a shallow copy. That can create some problems when you use an array in your uniform object and alter it's values.

[UniformsUtils documentation](https://threejs.org/docs/#api/en/renderers/shaders/UniformsUtils)
[UniformsUtils source](https://github.com/mrdoob/three.js/blob/master/src/renderers/shaders/UniformsUtils.js)
[Array.slice() documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/slice)

### Reproduction steps

1. Create a shader where one of the uniform properties is an array
2. Create 2 meshes with 2 different ShaderMaterials based on the first shader
3. Alter the uniform array property for one of the materials and the other material is altered as well

### Code

```js
const GradientShader = {

	uniforms:
	{
		'u_gradient': {
			value: [
			
				{ time:  0.0, color: new THREE.Vector4(1, 1, 1, 1) },
				{ time:  1.0, color: new THREE.Vector4(0, 0, 0, 1) },			
                        ]
		},
	},

	vertexShader: `...`,
	fragmentShader: ` ...`
};

const material1 = new THREE.ShaderMaterial( 
	{ 
		uniforms: THREE.UniformsUtils.clone(GradientShader.uniforms), 
		vertexShader: GradientShader.vertexShader, 
		fragmentShader: GradientShader.fragmentShader 
	});

const material2 = new THREE.ShaderMaterial( 
	{ 
		uniforms: THREE.UniformsUtils.clone(GradientShader.uniforms), 
		vertexShader: GradientShader.vertexShader, 
		fragmentShader: GradientShader.fragmentShader 
	});
      
// altering the array for material2 also alters the values for material1 and the source GradientShader object
material2.uniforms.u_gradient.value[1].color = new THREE.Vector4(1, 0, 0, 1);

```

### Live example

https://jsfiddle.net/dzvrqns5/1/
One of the spheres should have a gradient running from white to black, the other one from white to red. Both spheres are however red.

### Version

r171

### Device

Desktop

### Browser

Chrome, Edge

### OS

Windows

**Comment by Mugen87** [comment] 2024-12-27 10:22
Duplicate of #16080.

**Closed by Mugen87** 2024-12-27 10:22 UTC
