### ISSUE TITLE
GPGPU examples do not work on iOS Safari or Chrome

### ISSUE THREAD

**Issue by seieibob** [mrdoob/three.js#9628] opened 2016-09-05 22:20 UTC
##### Description of the problem 

```
[Warning] WebGL: INVALID_FRAMEBUFFER_OPERATION: clear: framebuffer not complete (three.js, line 19838)
[Warning] WebGL: INVALID_FRAMEBUFFER_OPERATION: drawElements: framebuffer not complete (three.js, line 16994)
```

This is happening in the GPGPU examples and in my own project (see [joncole.me/reaction-diffusion](http://www.joncole.me/reaction-diffusion)), which uses the latest build, indicating that whatever problem this is spans multiple versions of Three. It seems to me that the problem is related to the use of floating-point textures, but my knowledge ends there. 

The problem is that the things the shaders do in these examples (i.e. forming the waves in the water example) don't seem to take, and it will repeatedly spit out the two errors above.

I could reproduce this on an iPad (9.3.3), iPhone 6 (9.0.2), and iPhone 6s (9.3.4), using both Chrome and Safari. I do not know if this affects Android, but it seems likely.

##### Three.js version

- [x] Dev
- [x] r80
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [x] IOS

##### Hardware Requirements (graphics card, VR Device, ...)
Any device with iOS 8.0+, most likely

**Comment by satori99** [comment] 2016-09-05 23:18
The example you posted works fine for me on Firefox/Windows.

It shows THREE.WebGLRenderer 81dev in the console and has no errors at all.

**Comment by seieibob** [comment] 2016-09-05 23:20
The issue is with iOS Safari and Chrome.

**Comment by satori99** [comment] 2016-09-05 23:22
oops, I meant to say Chrome/Windows.... No error still.

**Comment by seieibob** [comment] 2016-09-05 23:23
Ah, I should clarify. You need to be using an iOS device, and access the page on Chrome or Safari.

**Comment by seieibob** [comment] 2016-09-05 23:32
I believe it's an issue with the OES_texture_float extension. iOS seems to report this even if it can't use it, it appears. See [Here on SO](http://stackoverflow.com/questions/20847546/how-can-i-convey-high-precision-uv-coordinates-between-render-passes-in-webgl/20850964#20850964) for more details.

**Comment by seieibob** [comment] 2016-09-06 01:35
This may be an issue deeper than Three.js is responsible for. The issue turns out to be with WEBGL_color_buffer_float. Some devices are able to write to floating point render textures despite not supporting the WEBGL_color_buffer_float extension, including iOS devices (as of 9.3.4) and my Macbook Pro (not sure if others behave the same way, but it seems to be driver level).

My solution is to check for this extension only on mobile, in order to prevent breaking it on any desktop browsers that have the capability but don't explicitly support it. 

Should this be considered closed?

**Comment by mrdoob** [comment] 2016-09-06 19:55
Hmm, on my iPad, http://threejs.org/examples/#webgl_gpu_particle_system kind of works. It breaks after some seconds. I wonder if this has something to do with `mediump`/`highp`?

**Comment by seieibob** [comment] 2016-09-07 01:06
I think that one works (if briefly) because it isn't using floating point render textures. In contrast, the GPGPU examples use GPUComputationRenderer, which reads from and renders to float textures. 

Most platforms properly report that they can read from float render textures using OES_texture_float. If you want to know whether you can render to a float texture, you look for WEBGL_color_buffer_float; however, to my knowledge there are very few platforms that support WEBGL_color_buffer_float, even if the hardware can do it. This behavior is what caused my confusion.

[From what I'm reading](https://www.khronos.org/registry/webgl/extensions/WEBGL_color_buffer_float/), WEBGL_color_buffer_float probably isn't going to gain wider support. Instead, WebGL 2.0 is going to replace it with an extension called EXT_color_buffer_float that should (should) do the same thing but have wider support from browsers.

The core problem isn't Three's fault, but perhaps something could be done to throw an error on unsupported platforms? The technique I'm aware of for checking for float texture render support is to set up a simple scene and try to render it into a texture, which would kind of look like the following:

```
//Set up a scene, renderer, and camera beforehand
var renderTarget = new THREE.WebGLRenderTarget(16, 16, {
            format: THREE.RGBAFormat,
            type: THREE.FloatType
});
renderer.render(scene, camera, renderTarget);
var gl = renderer.context;
var status = gl.checkFramebufferStatus(gl.FRAMEBUFFER);
if (status !== gl.FRAMEBUFFER_COMPLETE) {
    return false;
}
return true;
```

**Comment by yomboprime** [comment] 2016-09-07 01:44
Hi, (I'm the author of the GPGPU stuff)

@naso  [already spotted the issue](https://github.com/yomboprime/GPGPU-threejs-demos/issues/5) and made it work on iOS by using HalfFloat precision.

So it would be easy to add your test to GPUComputationRenderer and then a variable to set the texture type to HalfFloat if the test fails.

I will look into it.

**Comment by yomboprime** [comment] 2016-09-07 02:53
I did the changes. Please let me know if this one works in iOS:

http://yomboprime.github.io/GPGPU-threejs-demos/webgl_gpgpu_water.html

If all goes well, it should work and display this message in the console: `FloatType not supported for render targets, switching to HalfFloatType.`

**Comment by seieibob** [comment] 2016-09-07 14:13
I haven't done any in-depth testing, but it works on my iPhone and iPad. I wonder if the other demos will work the same with half-precision. Mine behaves differently, but I guess that's just something I have to work around.

Thank you for your work. Feel free to close this whenever you're satisfied!

**Comment by yomboprime** [comment] 2016-09-07 17:33
Yes, the other demos in that repo will work (not the erosion one though). Just go to:
http://yomboprime.github.io/GPGPU-threejs-demos/

I will make a PR with the changes. I can not close this issue, I'm only a contributor ;-)

**Closed** 2016-09-08 05:24 UTC

**Comment by yomboprime** [comment] 2016-09-08 06:26
BTW, this should be tested more thoroughly by someone with a iOS device.
I don't know how it looks with the HalfFloat type, but 16 bits seems too little to me.

**Comment by mrdoob** [comment] 2016-09-08 06:52
I'll try tomorrow.

**Comment by mrdoob** [comment] 2016-09-08 18:47
Works fine! 👌

**Comment by yomboprime** [comment] 2016-09-08 21:23
Nice!

**Comment by colejd** [comment] 2021-02-09 00:42
To recall, the trick was to force half precision for iOS devices because they didn't report their ability to perform float render-to-texture even though they could. This trick appears to no longer work on newer versions of Three. For browsers that don't declare `WEBGL_color_buffer_float` or `EXT_color_buffer_float`, `checkFramebufferStatus()` will now fail. I'm not really sure what the fix is, though. Any ideas @yomboprime?

**Comment by colejd** [comment] 2021-02-09 00:51
A good test would be to take one of the GPGPU demos that uses the half-precision hack, and try it against a newer version of Three and seeing if anything breaks. Not sure which one to try though.

**Comment by yomboprime** [comment] 2021-02-09 01:30
Sorry I can't help with the testing, no iOS here.

**Comment by Mugen87** [comment] 2021-02-09 09:57
@colejd Are you testing with iOS 14?

**Comment by colejd** [comment] 2021-02-09 15:06
Yes @Mugen87

**Comment by Mugen87** [comment] 2021-02-09 16:14
Then please notice that this is related to iOS 14 and not to newer `three.js` versions, see #20415.

**Comment by colejd** [comment] 2021-02-09 16:32
Unfortunately I don't think that's it @Mugen87.  If I understand correctly, in your linked issue, the problem is that iOS is incorrectly reporting that it has capabilities it actually does not have. In my case, iOS is not reporting capabilities it actually has (in this case, half-precision render-to-float-texture). Previously, I could get around this issue by using half-precision and just trusting that it would work on iOS, but now the same trick results in an incomplete framebuffer when I try to render.

I'm trying to isolate it to a specific cause to avoid wasting your time. For now, what I know is that my old build works on my device and my new build does not, and the only difference I can identify that would make a difference is my upgrade of Three from `0.87.1` to `0.125.2`. I'll try to post some minimal examples soon.

**Comment by Mugen87** [comment] 2021-02-09 16:41
> I'll try to post some minimal examples soon.

That would be great! I just wanted to highlight that iOS 14 triggered the change in #20415. It could be necessary to update other code for the same reason.
