### ISSUE TITLE
Continuous Integration for three.js, Documenting requirements

### ISSUE THREAD

**Issue by levilime** [mrdoob/three.js#13580] opened 2018-03-13 11:06 UTC
##### Continuous Integration for three.js, Documenting requirements

Hey @mrdoob @fernandojsg , I hope I am on topic with the following question.   I was wondering about the work being done on Continuous integration of the system for running tests. I would be thankful to get insight with answers to these following questions:
- There is already [a static analysis tool](https://lgtm.com/projects/g/mrdoob/three.js/) which gives a good overview on some of the quality elements of the system. But I notice that the build does not fail although it throws some stylistic errors. Is there a motivation for this? How is the tool being used exactly to maintain the quality of the system?
- How would a continuous integration that runs the tests be configured to work well for maintaining three.js . I've noticed there are a lot of test `TODO` 's and fail, should the CI fail because of them? How do you see these failing tests be resolved or should they stay like that indefinitely? Would code coverage and branching depth be worthwhile metrics for giving insight in the health of the system in your opinion? I have already seen approaches for unit testing and recent mocking approaches in three.js. With it also be interesting to do integration tests with the browser?

I am exploring this because I would like to do some work on this front if it is appropriate. Alternatively I would like to write some documentation about these tests and their actual use in three.js. Thanks and would love to get a response. Keep up the good work 🥇 

I first wanted to post this [here](https://github.com/mrdoob/three.js/issues/13533) but I think a new issue is more appropriate.

**Comment by Mugen87** [comment] 2018-03-13 12:15
> I've noticed there are a lot of test TODO 's and fail, should the CI fail because of them? 

The fails should be gone on `dev` branch. I've removed them with recent PRs.

**Comment by Mugen87** [comment] 2018-03-13 13:43
When i think about it: I think it would be better to just have a single issue about CI. That's easier to manage and the discussion happens at a single place.

**Comment by levilime** [comment] 2018-03-13 21:43
Hey @Mugen87 thanks for your response. On your first remark. I saw these fixes, passing the tests when the environment does not have certain dependencies in for example https://github.com/mrdoob/three.js/issues/13556, good work!  I notice on the current dev build 88a2bf98881df8b8a362beb9e1b81d4ae1ffe27 there are still 3 failing tests 
- `not ok 1074 Source > Maths > Euler > set/get properties`
- `not ok 1075 Source > Maths > Euler > clone/copy`
- `not ok 1077 Source > Maths > Euler > fromArray`

Is this intentional or is this something that should be fixed?

**Comment by levilime** [comment] 2018-03-13 21:45
On the second point on the single issue for CI. That sounds good could I help in any way to arrange this?

**Comment by Mugen87** [comment] 2018-03-14 10:16
> I help in any way to arrange this?

I guess we should close this issue and focus on #13533 instead

**Comment by Mugen87** [comment] 2018-03-14 10:35
> Is this intentional or is this something that should be fixed?

Can't reproduce with `npm run build` on `dev`(0c6c0050982cf3697005bb7ca419b4dbd6a9279a)

![image](https://user-images.githubusercontent.com/12612165/37397324-9bdfc898-277b-11e8-8f6f-a1c5990fc76f.png)

**Closed** 2018-03-14 14:54 UTC

**Comment by levilime** [comment] 2018-03-15 22:26
Hey @Mugen87 I made a separate issue about the failing tests, I wonder what to do so they work for everyone: https://github.com/mrdoob/three.js/issues/13606.

Thanks!
