### ISSUE TITLE
Fog doesn't work on Chrome in Nexus devices if antialias = true

### ISSUE THREAD

**Issue by StarPlugins** [mrdoob/three.js#7769] opened 2015-12-10 07:35 UTC
On Nexus devices running Chrome, setting antialias = true in renderer causes fog to not appear.

Tested on Three.js r72 and r73.

Other Android and iOS devices are fine.

Seems related to this:
http://stackoverflow.com/questions/27368813/three-js-fog-on-chrome-mobile-not-working

Suggested workaround is not good as it saps performance:
antialias = false
renderer.setPixelRatio((window.devicePixelRatio || 1) * 2);

**Comment by mrdoob** [comment] 2015-12-10 23:28
What Nexus devices have you tried? Also, can you create a jsfiddle?

**Comment by StarPlugins** [comment] 2015-12-11 08:16
Actually, this is more pervasive than I initially thought - it happens on more than Nexus.

There is a fiddle here: https://jsfiddle.net/3s7ha8hq/3/

The green area should start fading to white from very near the camera plane.

The fog effect gets pushed way back when antialias = true. This happens on the following devices I tested on.

- Nexus 7 (2013) (Marshmallow, Adreno 320 GPU)
- Sony Xperia M2 (Lollipop, Adreno 305 GPU)
- Motorola Moto E 4G 2nd Generation (Lollipop, Adreno 306 GPU)

This device works fine: Huawei Honor 4X (KitKat, ARM Mali-450MP4 GPU).

**Comment by WestLangley** [comment] 2015-12-11 16:51
Is fog affected if you set DPR properly in your fiddles?

	renderer.setPixelRatio( window.devicePixelRatio );
	renderer.setSize( window.innerWidth, window.innerHeight );

**Comment by StarPlugins** [comment] 2015-12-11 17:46
`renderer.setPixelRatio( window.devicePixelRatio );` doesn't make any difference.

**Comment by mrdoob** [comment] 2015-12-11 20:08
I can reproduce this on a Nexus 5.

antialias = false

![screenshot_20151211-145912](https://cloud.githubusercontent.com/assets/97088/11754267/13e6bb8c-a018-11e5-8a09-65a8a209850c.png)

antialias = true

![screenshot_20151211-145957](https://cloud.githubusercontent.com/assets/97088/11754270/1804feea-a018-11e5-975e-17c71f2f97bc.png)

here's the relevant glsl code:

```glsl
float depth = gl_FragCoord.z / gl_FragCoord.w;
float fogFactor = smoothstep( fogNear, fogFar, depth );
```

I suspect `gl_FragCoord.w` is wrong in these devices when `antialias` is `true`.

/ping @kenrussell

**Comment by WestLangley** [comment] 2015-12-12 00:37
Could it be a depth buffer precision problem? Increase the camera near plane to 1; tighten up the far plane.
```javascript
var camera = new THREE.PerspectiveCamera( 75, window.innerWidth / window.innerHeight, 1, 10 );
```

**Comment by StarPlugins** [comment] 2015-12-12 05:14
Changing the near and far planes makes no difference - the fog still appears much further back.

**Comment by MasterJames** [comment] 2015-12-12 08:41
Maybe you/we need to scale the depth factor depending on which buggy client, (which needs to have a bug report submitted there if possible), is rendering. 
It seems maybe this isn't a threejs error? Is there a simple way to prove where the bug lies?  At least for now maybe device patching is recommended.

**Comment by StarPlugins** [comment] 2015-12-12 23:47
@MasterJames It appears that it's the far fog distance that gets moved further back in the 'bug'

I suppose you could move the far fog distance forward - I tried it in the Fiddle and it seemed to look ok.

However, I'm not sure how you'd detect the device - it seems to be anything using Adreno GPUs from my tests.

A better solution than device detection might be 'bug' detection:

- Render a small scene with a single full-green (0x00FF00) object that fogs
- Read the pixel value from some point in the canvas that should be fogged
- If that pixel is 0x00FF00 , then you know the fog is buggy and should be moved forwards when creating the real scene

**Comment by MasterJames** [comment] 2015-12-13 01:54
That's a good idea. Unless you can detect.
I was hopeful it was a pixel aspect ratio or something the devices list would reveal.

http://stackoverflow.com/questions/13196753/detecting-the-gpu-with-a-browser-and-javascript

**Comment by StarPlugins** [comment] 2015-12-16 06:17
I created this snippet which detects if the fog bug exists. It basically creates a small render area and draws a green plane to a white-fogged scene. If the pixels read back as green, it knows the fog bug exists on the device: https://jsfiddle.net/d6m63k37/

By turning antialiasing on and off, you can confirm the check works.

It only reads a single pixel, but by tilting the plane along its x-axis, a gradient check could be performed for a more elaborate check.

Provisionally, I've found that dividing the fog distances by 4 on bugged devices will roughly match the intended fog distances.

As it is, I don't think this is a ThreeJS issue and is related specifically Adreno GPUs. There's loads of devices that use those, so handy to know how to workaround.
```
var scene = new THREE.Scene();
// Set to max fog at camera plane.
scene.fog = new THREE.Fog(0xffffff, 1, 2);

var camera = new THREE.PerspectiveCamera(75, 1, 0.1, 1000);

var renderer = new THREE.WebGLRenderer({
  antialias: true
});
renderer.setSize(32, 32);
//  document.body.appendChild(renderer.domElement);

var geometry = new THREE.PlaneGeometry(1, 1);
// Set to a mid-green.
var material = new THREE.MeshBasicMaterial({
  color: 0x008800
});
var plane = new THREE.Mesh(geometry, material);
plane.position.z = -2;
scene.add(plane);

renderer.render(scene, camera);

// Read pixel from frame buffer.
var gl = renderer.getContext();
var pixelValues = new Uint8Array(4);
gl.readPixels(0, 0, 1, 1, gl.RGBA, gl.UNSIGNED_BYTE, pixelValues);
// If value is original, unfogged color, then we know fog bug exists.
if (pixelValues[1] === 0x88) alert("Fog bad :-(");
else alert("Fog good :-)");
```

**Comment by kenrussell** [comment] 2015-12-28 20:28
Thanks for reporting this. A WebGL conformance test has been added for this in https://github.com/KhronosGroup/WebGL/pull/1400 and a bug has been filed against Qualcomm with internal bug ID 26333630. Hopefully it will be fixed in an upcoming Android release; until then, please try to work around the bug. Thanks.

**Comment by mrdoob** [comment] 2015-12-29 00:08
@kenrussell thanks!

**Closed by mrdoob** 2015-12-29 00:08 UTC

**Comment by mrdoob** [comment] 2017-01-16 19:36
![screenshot_20170116-203404](https://cloud.githubusercontent.com/assets/97088/21996615/6d8b8618-dc2b-11e6-98e9-99f8239742d4.png)

**Comment by pathei** [comment] 2017-03-07 12:05
Hi, works well for the Fog module but in the FogExp2 it is also an issue. Currently workaround for me was to multiply the fogs density value by four after detecting Androids "Qualcomm" in the gl-context (gl.vendor).

**Comment by mrdoob** [comment] 2017-03-16 17:50
@pathei do you mind updating the jsfiddle in this thread showing the issue? Also share screenshots if possible.

**Comment by pathei** [comment] 2017-03-22 10:59
@mrdoob sure, I hope it helps.
On a current project I created a fog:
```
function createFog(color, near){
  scene.fog = new THREE.FogExp2( color, near );
}
```
Expected end result in mobile devices is:
<img width="240" alt="three_fog_a" src="https://cloud.githubusercontent.com/assets/9036203/24192444/47f76966-0eef-11e7-9347-339609da9463.png">



On Android mobile devices with a Qualcomm chipset e.g.:

- Samsung Galaxy SM-T550 Galaxy Tab A (2015)
- Sony Xperia Z1 (2013)

I got following effect.
<img width="240" alt="threejs_fog_b" src="https://cloud.githubusercontent.com/assets/9036203/24192472/6c4c2612-0eef-11e7-8079-c5b8aa610f6b.png">

Haven´t had more devices with Qualcomm to test on.

After playing with the near attribute in the FogExp2 it seems like the fog get´s applied on that mentioned devices "farer away".
So for my use case it worked to:

- get webgl context
- get debugInfo.UNMASKED_VENDOR_WEBGL
- read out qualcomm chipset
- return an integer which get´s used as factor for multiplying with fog near value
 (this factor get´s applied to a global variable wrapper = DM)
```
detectWebGLSupport: function() {
  var canvas = document.createElement("canvas"),
  gl     = canvas.getContext("webgl") || canvas.getContext("experimental-webgl");
              
  if (gl && gl instanceof WebGLRenderingContext) {
    DM.webGLActive           = true;
    DM.antialisIsSupported = gl.getContextAttributes().antialias;
    detectFogBug(gl); 
    return true;
   }
   else {
     DM.webGLActive = false;
     return false;
   }
}

/**
 * Detecting Qualcom GPU/Driver at Android devices to prevent WebGL/Three.jsR84 fogExp2 distance bug.
 * A value of 4 seems to work fine here. FF (Current Firefox 52.0.1) doesn´t support WEBGL_debug_renderer_info.
 */
function detectFogBug(gl){
  if(gl.getExtension('WEBGL_debug_renderer_info') !== null){
    var debugInfo = gl.getExtension('WEBGL_debug_renderer_info');
    var vendor      = gl.getParameter(debugInfo.UNMASKED_VENDOR_WEBGL);
    DM.fogBugFactor = (vendor == "Qualcomm" ) ? 4 : 1;
   }
   else {
     DM.fogBugFactor = 1;
   }
  }
 }


/**
 * Multiplying fog density with the calculated factor from deviceFeatures.js
 * to prevent android/three.js fog bug.
 */
function createFog(color, near){
  scene.fog = new THREE.FogExp2( color, near*DM.fogBugFactor );
 }
```

Updated fiddle:
https://jsfiddle.net/pathei/zncwkqq2/2/

If someone got´s an alternative for this pls shoot out.
cheers

**Comment by WestLangley** [comment] 2017-03-22 14:42
@pathei Cleaned up fiddle: https://jsfiddle.net/zncwkqq2/3/

**Comment by WestLangley** [comment] 2017-03-22 14:49
@pathei said
>After playing with the near attribute in the FogExp2

`FogExp2` does not have a `near` attribute; it has a `density`.

**Comment by mrdoob** [comment] 2017-04-04 21:54
Hmm... this is the relevant glsl code:

```glsl
#define LOG2 1.442695
#define whiteCompliment(a) ( 1.0 - saturate( a ) )
```

```glsl
fogDepth = -mvPosition.z;
```

```glsl
float fogFactor = whiteCompliment( exp2( - fogDensity * fogDensity * fogDepth * fogDepth * LOG2 ) );
```

**Comment by mrdoob** [comment] 2017-04-04 22:05
https://jsfiddle.net/3x61hb9c/
https://jsfiddle.net/3x61hb9c/1/

**Comment by mrdoob** [comment] 2017-04-04 22:14
Seems like I'm unable to reproduce...
