### ISSUE TITLE
Editor: Camera selector drop-down is unclickable on mobile

### ISSUE THREAD

**Issue by GamerWael** [mrdoob/three.js#20245] opened 2020-09-02 08:38 UTC
The camera selector drop-down remains unclickable on mobile even after the addition of multiple cameras in the scene.

##### Three.js version

- [ ] Dev
- [ ] r120
- [ ] ...
- [x] Editor

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [x] Android
- [ ] iOS

**Comment by Mugen87** [comment] 2020-09-02 08:47
I can confirm this on prod. However, the `dev` seems to be already fixed. Can you please give it a try?

https://raw.githack.com/mrdoob/three.js/dev/editor/index.html

**Comment by GamerWael** [comment] 2020-09-02 08:49
Yep, it's working perfectly in the dev version.

**Comment by Mugen87** [comment] 2020-09-02 08:55
Closing then. This will be fixed in prod with the next release at the end of the month.

**Closed by Mugen87** 2020-09-02 08:55 UTC
Labels: Bug, Editor

**Comment by mrdoob** [comment] 2020-09-02 10:46
Seems like this was the issue: https://github.com/mrdoob/three.js/commit/44c63360c59056b1f8e9caf8570ce00083d5fcd7

In the past iPads needed this, but with with the move to Pointer Events maybe it's no longer needed.

Hopefully it should work in a few minutes.
