### ISSUE TITLE
THREE.Sprite don't intersect when size attenuation false

### ISSUE THREAD

**Issue by T4lus** [mrdoob/three.js#15010] opened 2018-10-04 15:34 UTC
##### Description of the problem
Hi everyone,

I just found that sprite don't get hit when size attenuation is false

* [plunker](https://next.plnkr.co/plunk/11YcD9hjVI69rfO72fUm) (latest release branch)

##### Three.js version

- [ ] Dev
- [x] r97
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by WestLangley** [comment] 2018-10-04 17:13
Thanks, but this is a duplicate of #14934.

**Closed by WestLangley** 2018-10-04 17:13 UTC
