### ISSUE TITLE
[r102] Resized textures are flipped upside-down

### ISSUE THREAD

**Issue by drcmda** [mrdoob/three.js#15896] opened 2019-03-03 16:07 UTC
##### Description of the problem

Sprites are flipped. This happened after somewhere between 101 (which works) and 102. In the sandbox below you can exchange the three version, going back to the last major has them positioned correctly.

https://codesandbox.io/s/1z92z6xwz4

##### Three.js version

- [x] r102

##### Browser

- [x] Chrome

##### OS

- [x] macOS

**Comment by drcmda** [comment] 2019-03-03 19:51
I noticed it seems to have to do something with texture resizing, doing this:

    canvas.width = canvas.height = 1024

makes it project correct again. But when it has to resize, it flips.

**Comment by MasterJames** [comment] 2019-03-04 09:28
I noticed trying version 102 from 99 that the texture looked flipped. I think though after attempts to flip it it didn't change that there was an error in reading in the texture coordinates from the OBJ via OBJLoader.
I was originally confused by fact that I could not find an OBJLoader.js anywhere in src so I had actually just Grabbed ObjectLoader [which is the native json format].

I had used the examples OBJLoader from r102 but I've also attempted 102 with a recovered version.

It seems only r99 (that I have or tried but probably it's okay in r100?! Alas I'm statistically doubting it's okay in r101).

Maybe there's is some documentation on a "new way" I've not been able to fully realize? please advise.

Is it missing from the build somehow?

**Comment by peteshea** [comment] 2019-03-04 12:07
I'm seeing a similar (same) issue in the latest version of the three.js/editor. If you create a plane object  and then upload and map a texture to it, the UVs will be flipped and inverted.

**Comment by mmakrzem** [comment] 2019-03-04 14:27
In the release notes for 102 (https://github.com/mrdoob/three.js/releases) under the WebGLRenderer section it says Make .setViewport(), .setScissor() relative to lower-left corner. https://github.com/mrdoob/three.js/pull/13593  Perhaps that has something to do with the flip?

**Comment by Mugen87** [comment] 2019-03-04 16:04
Okay, I can reproduce the bug with this fiddle: https://jsfiddle.net/nrjL28px/4/

I can also confirm that the problem was introduced with this PR: #15805

**Comment by merwaaan** [comment] 2019-03-04 18:08
@Mugen87 Didn't realize that ImageBitmap was flipped. I'll propose a fix.

**Comment by mrdoob** [comment] 2019-03-11 19:30
This should now be fixed in the `dev` branch.
Sorry about the regression!

**Closed by mrdoob** 2019-03-11 19:30 UTC
Labels: Regression
