### ISSUE TITLE
Distortion of PointsMaterial in combination with OrthographicCamera in high aspect ratio Viewports

### ISSUE THREAD

**Issue by smoes** [mrdoob/three.js#19021] opened 2020-04-03 05:24 UTC
##### Distortion of PointsMaterial in combination with OrthographicCamera in high aspect ratio Viewports

When using OrthographicCamera in Combination with Points and PointsMaterial, there is a distortion of the points. In the provided example a point will not be rendered quadratic, but as a rectangle. The issue only appears on some browser/os-combinations.

* [jsfiddle](https://codepen.io/smoesorino/pen/qBdwPVx) (example)
* [image](https://aws1.discourse-cdn.com/standard17/uploads/threejs/original/2X/0/04cedf9c429e48c77ff61c27607d9cc767012f77.png) (image, chrome on ubuntu)

##### Three.js version

- [x] r110
- [x] r101

I haven't tested additional versions

##### Browser

This is a little tricky, since we talk about browser/os combinations. We observed it for:

Chrome (80.0.3987.149)/Ubuntu 18.04
Safari (13.0.5)/MacOs 10.13.6

Firefox is having entirely different issues, resulting in no display at all on several OS.

**Comment by Mugen87** [comment] 2020-04-03 09:19
I've updated the fiddle with a more "usual" setup: https://jsfiddle.net/36pzsdaj/1/

This produces the same result with Chrome, Firefox and Safari on macOS.

If you still encounter differences in browser, please report them directly to the respective vendors.

**Comment by smoes** [comment] 2020-04-03 09:31
Does not encounter in your example, since the aspect ratio is too low (maybe it encounters, but the effect is too little). When I increase the width tremendously in both, the aspect ratio calculation and the renderer `setSize` function, it encounters (tested with Linux Chrome, as above)

**Comment by Mugen87** [comment] 2020-04-03 09:42
> When I increase the width tremendously in both

What does "tremendously " mean? Can you update the fiddle with your values?

A very large view frustum can introduce a series of problems e.g. depth precision issues which are only limited to mitigate. In most cases, scaling the scene down and thus minimizing the frustum is often the best approach.

**Comment by smoes** [comment] 2020-04-03 09:50
https://jsfiddle.net/8ejyk0cr/

Scroll to the right to see the dot. 

All off my colleagues encounter the error on Safari on MacOS, it's not only Chrome on Ubuntu. I can collect the version information of their installations if needed.

**Comment by Mugen87** [comment] 2020-04-03 10:00
Sorry, but I don't see any issues on my iMac with macOS 10.15.4 and latest Safari.

Please try to reproduce the issue with [Babylon.js](https://playground.babylonjs.com/) and if possible with pure WebGL. 

You have not demonstrated a `three.js` bug so far and hence it was not right to open an issue in the first place. GitHub is for bugs and feature requests only.

**Comment by mrdoob** [comment] 2020-04-04 00:20
> * [jsfiddle](https://codepen.io/smoesorino/pen/qBdwPVx) (example)

I can reproduce in MacOS 10.15.3.

In Chrome 80.0.3987.149 I get this:

<img width="224" alt="Screen Shot 2020-04-04 at 9 14 41 AM" src="https://user-images.githubusercontent.com/97088/78413995-fc460880-7654-11ea-8d7c-dbbbaf27c9e1.png">

In Safari 13.0.5 I get this:

<img width="224" alt="Screen Shot 2020-04-04 at 9 14 50 AM" src="https://user-images.githubusercontent.com/97088/78414081-63fc5380-7655-11ea-9547-19d03ee0dc5e.png">

**Comment by WestLangley** [comment] 2020-04-04 02:40
@smoes This is not specific to `PointsMaterial`, nor is it governed by the camera aspect ratio.

You are exceeding the Max Render Buffer Size for your browser/device.

Firefox is kind enough to warn that something is amiss.

    Error: WebGL warning: clear: Requested size 8193x400 was too large, but resize to 4096x200 succeeded.

See https://webglreport.com.

Alternatively,

```js
var gl = renderer.getContext();

console.log( gl.getParameter( gl.MAX_RENDERBUFFER_SIZE ) ); // 8192 or 16384
```

>Firefox is having entirely different issues, resulting in no display at all on several OS.

The point is being rendered, just in the wrong place because the indexing into the buffer is messed up.

**Comment by Mugen87** [comment] 2020-04-04 08:27
Related #5194.

**Comment by mrdoob** [comment] 2020-04-04 09:25
> Firefox is kind enough to warn that something is amiss.

Hmm, maybe we could be kind too... 🤔

**Comment by Mugen87** [comment] 2020-04-04 09:35
Do you mean https://github.com/mrdoob/three.js/issues/5194#issuecomment-68481074?

**Comment by mrdoob** [comment] 2020-04-04 10:50
Yes.. Glad to see I'm consistent..  😁

**Comment by Mugen87** [comment] 2020-04-13 10:07
Closing in favor of #5194.

**Closed by Mugen87** 2020-04-13 10:07 UTC
Labels: Duplicate
