### ISSUE TITLE
Wrong order of loading events

### ISSUE THREAD

**Issue by flerokoo** [mrdoob/three.js#12601] opened 2017-11-07 18:14 UTC
I am loading a scene with textures via ObjectLoader.

Live test: http://shodiev.ru/other/three_events/
Zip with testcase: https://yadi.sk/d/sGqOqpbm3PVSM9

As you can see in console, events are firing in unexpected order: function that i pass to LoadingManager is called before ObjectLoader is complete.

It looks like LoadingManager completes when only _scene.json_ is loaded although there's still images to load.

Is it supposed to be like that?

##### Three.js version

- [ ] Dev
- [x] r88
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Itee** [comment] 2017-11-07 21:28
Something seem to be wrong in ObjectLoader.

In ctor the manager is correctly set:

```javascript
function ObjectLoader( manager ) {

	this.manager = ( manager !== undefined ) ? manager : DefaultLoadingManager;
	this.texturePath = '';

}
```

and this manager is transmit to FileLoader in load method at line 78:

```javascript
	load: function ( url, onLoad, onProgress, onError ) {

		if ( this.texturePath === '' ) {

			this.texturePath = url.substring( 0, url.lastIndexOf( '/' ) + 1 );

		}

		var scope = this;

		var loader = new FileLoader( scope.manager );
		loader.load( url, function ( text ) {
			... 
			scope.parse( json, onLoad ); // NOTE THE PARSE METHOD HERE
		}

	},
```

but not under parse methods:

- parseGeometries line 161-162:

```javascript
var geometryLoader = new JSONLoader();
var bufferGeometryLoader = new BufferGeometryLoader();
```

- parseMaterials line 377:

```javascript
var loader = new MaterialLoader();
```

- parseImages line 452 - 454 ( redefine a new LoadingManager )

```javascript
var manager = new LoadingManager( onLoad );

var loader = new ImageLoader( manager );
```

Finally your onLoad methods attach to ObjectLoader is call under parse methods:

```javascript
var images = this.parseImages( json.images, function () {

	if ( onLoad !== undefined ) onLoad( object );

} );
```

So... The callback you attach to ObjectLoader is called after ( async ) the onLoad callback transmit to the initial LoadingManager that efectively return before the end of parse methods.

I don't know if this is wanted by design but it's unclear.

@Mugen87 do you know something about this missing manager in parse methods ?

**Comment by flerokoo** [comment] 2017-11-08 20:28
That's exactly what i was thinking.
And i sure want to know if it is supposed to work like that? In that case how should i know when scene is fully loaded (including textures)?

**Comment by Mugen87** [comment] 2017-11-09 11:09
Basically the manager instance of a loader should be passed to all internal loaders used for texture, material or other file loading stuff. If this is not the case, we should investigate the respective code sections.

**Comment by Itee** [comment] 2017-11-09 12:50
Ok i will take a look deeper

**Comment by Mugen87** [comment] 2018-08-16 13:50
Closing in favor of #13177. The  source of this issue is that `ObjectLoader` uses an internal instance of `LoadingManager`

**Closed by Mugen87** 2018-08-16 13:50 UTC
Labels: Duplicate, Loaders
