### ISSUE TITLE
Incorrect movement with pointerlock examples

### ISSUE THREAD

**Issue by YatrikPatel** [mrdoob/three.js#17216] opened 2019-08-08 21:47 UTC
I have a found a bug with the [controls/pointerlock](https://threejs.org/examples/#misc_controls_pointerlock) example. When looking straight down, the camera doesn't move at all (the player should be moving at a consistent speed along the x,z plane regardless of camera orientation). 

I have tried using `` 

```
var cameraDirection = controls.getDirection(new THREE.Vector3()).clone();
var angle = Math.atan2(cameraDirection.x, cameraDirection.z);

// and then update camera position (if forward key pressed with) with:
controls.getObject().position.z += (Math.cos(angle))
controls.getObject().position.x += (Math.sin(angle))
```

However, this results in the camera moving in another direction  (the `angle` variable snaps to the closest multiple of pi/2 radians) when the camera is facing straight down or straight up. 

What's the solution to this problem?

**Comment by Mugen87** [comment] 2019-08-09 09:31
Um, it works fine with the version from `R103`:

https://rawcdn.githack.com/mrdoob/three.js/r103/examples/misc_controls_pointerlock.html

Seems the bug was introduced with: https://github.com/mrdoob/three.js/pull/16171

/ping @WestLangley

**Comment by WestLangley** [comment] 2019-08-09 19:46
>Seems the bug was introduced with: #16171

I would not call this a "bug". I would call it an example.

>the player should be moving at a consistent speed along the x,z plane regardless of camera orientation

 If someone wants to change the example to have different behavior that is fine with me.

**Comment by Mugen87** [comment] 2019-08-10 09:37
> I would not call this a "bug". I would call it an example.

The problem is that the current behavior is just wrong for a FPS controls. This bug was introduced with #16171. The PR would have never been merged if this issue was detected during the review.

**Comment by YatrikPatel** [comment] 2019-08-10 19:50
I agree with @Mugen87. This example must be updated. Despite extensive searching, I have found no online example that fixes this behavior and uses a recent version of three.js and PointerLockControls.

**Closed** 2019-08-25 10:00 UTC
Labels: Bug, Examples
