### ISSUE TITLE
Terrible performance when using a reflector with sRGB encoding

### ISSUE THREAD

**Issue by SBRK** [mrdoob/three.js#19248] opened 2020-04-28 17:34 UTC
It seems to be something like this issue: 
https://github.com/mrdoob/three.js/issues/18893

In my case, the renderer `outputEncoding` is `GammaEncoding` and  I'm using an `EffectComposer` with a `GammaCorrectionShader` pass at the end.

If I use a reflector with the default `LinearEncoding` then it runs fine, but the reflection colors are screwed, they appear too dark. If I use `sRGBEncoding` as the reflector encoding, then the reflection colors are correct but it's running slow as hell, probably recompiling the shaders all the time. 

Is there a way I can get correct colors without recompiling the shaders all the time?

**Comment by Mugen87** [comment] 2020-04-28 17:42
Duplicate of #18893.

If you assign `GammaEncoding` to `outputEncoding`, the you have to use `GammaEncoding` for the reflector, too.

**Closed by Mugen87** 2020-04-28 17:42 UTC
Labels: Duplicate

**Comment by SBRK** [comment] 2020-04-28 19:44
@Mugen87 I had the same issue with `GammaEncoding`

**Comment by Mugen87** [comment] 2020-04-28 20:11
Can you please demonstrate this with a fiddle?

**Comment by SBRK** [comment] 2020-04-29 08:23
I will try, but I have a complex rendering pipeline. In the meantime, I'm back on my code and did retry `GammaEncoding` as encoding for both Reflector and outputEncoding, with EffectComposer disabled. It doesn't recompile but the colors are off :
![image](https://user-images.githubusercontent.com/119354/80575172-67d88700-8a03-11ea-8ce4-69984b27943a.png)

**Comment by Mugen87** [comment] 2020-04-29 08:27
> In my case, the renderer outputEncoding is GammaEncoding and I'm using an EffectComposer with a GammaCorrectionShader pass at the end.

It is does not make sense to render the beauty pass with gamma correction and then apply `GammaCorrectionShader` at the end of your pass chain. It seems you are doing this right now.

**Comment by SBRK** [comment] 2020-04-29 08:36
> > In my case, the renderer outputEncoding is GammaEncoding and I'm using an EffectComposer with a GammaCorrectionShader pass at the end.
> 
> It is does not make sense to render the beauty pass with gamma correction and then apply `GammaCorrectionShader` at the end of your pass chain. It seems you are doing this and apply gamma twice right now.

Maybe, but I'm having the wrong color problem even without the postprocessing enabled

**Comment by Mugen87** [comment] 2020-04-29 08:43
I suggest you use the [forum](https://discourse.threejs.org/) to clarify this issue.

**Comment by SBRK** [comment] 2020-04-29 08:53
Ok, I found my mistake, I was using black as color, thinking it was added to the reflection color (I first tried with white and it was all white). If I use `0.5, 0.5, 0.5` it's fine
