### ISSUE TITLE
Bug WebGPURenderer set scene.environment break NodeMaterial

### ISSUE THREAD

**Issue by Makio64** [mrdoob/three.js#28857] opened 2024-07-12 13:12 UTC
### Description

I have a scene with a mix of StandardMeshNodeMaterial and custom NodeMaterial. I get an error message only when i set the scene.environment, If I use MeshBasicNodeMaterial instead of NodeMaterial it works.

```js
// error when using NodeMaterial
Uncaught TypeError: properties.nodes is not iterable
    at Proxy.analyze (chunk-OPBR7TQE.js?v=ac4c42a7:4013:35)
    at Proxy.build (chunk-OPBR7TQE.js?v=ac4c42a7:411:12)
```

### Reproduction steps

Create a scene with an hdr set to scene.environment, add a mesh with a NodeMaterial into the scene.

### Code

```js
import { BackSide, Color, IcosahedronGeometry, Mesh } from 'three'
import { NodeMaterial, uniform, uv, mul, add, vec4, mix, sub, clamp } from 'three/examples/jsm/nodes/Nodes.js'
import { MeshBasicNodeMaterial } from 'three/addons/nodes/Nodes'

//...
		const topColor = uniform(new Color(0x020f56))
		const bottomColor = uniform(new Color(0x41b883))
		const opacity = uniform(0)
		const UV = add(mul(sub(uv().y, .5), 4), 0)
		const skyColor = mix(bottomColor, topColor, clamp(UV, 0., 1.))

		const material = new NodeMaterial() // BUG : if NodeMaterial no problem except if scene.environment!=null, work with MeshBasicNodeMaterial.
		material.colorNode = vec4(skyColor, opacity)
		material.side = BackSide
		material.depthWrite = false
		material.depthTest = true
		material.transparent = true
```

### Live example

Is there a fiddle. with hdr used on latest ?

### Version

r166.1

**Comment by Mugen87** [comment] 2024-07-12 20:49
> Is there a fiddle. with hdr used on latest ?

Try it with: https://jsfiddle.net/y41zsgq7/1/

**Comment by Mugen87** [comment] 2024-07-20 09:30
> Create a scene with an hdr set to scene.environment, add a mesh with a NodeMaterial into the scene.

I've done that in the following fiddle but I'm unable to reproduce. Do you mind updating the code so the error pops up?

https://jsfiddle.net/gpq1nmez/2/.

**Comment by Mugen87** [comment] 2024-07-23 09:04
Closing for now. Feel free to reopen the issue when a live example for reproduction can be provided.

**Closed by Mugen87** 2024-07-23 09:04 UTC
Labels: Bug, WebGPU
