### ISSUE TITLE
GLTFExporter: incorrect export for non-indexed geometry with groups

### ISSUE THREAD

**Issue by querielo** [mrdoob/three.js#24310] opened 2022-07-04 15:58 UTC
[Here](https://github.com/mrdoob/three.js/blob/dev/examples/jsm/exporters/GLTFExporter.js#L1700) we can see that non-indexed geometry with groups are ignored. That causes incorrect generation of accessors for non-indexed geometry with groups.

**Platform:**

 - Platform: everywhere
 - Three.js version: [r142]

**Comment by Mugen87** [comment] 2022-07-04 16:02
Duplicate of #21538.

**Closed by Mugen87** 2022-07-04 16:02 UTC
