### ISSUE TITLE
Some model bounding boxes and the size mismatch problem of the model itself

### ISSUE THREAD

**Issue by calmheaded** [mrdoob/three.js#27407] opened 2023-12-20 05:42 UTC
### Description

Is the blue bounding ball and red bounding box of this bird model located at two different positions from the model? The length, width, and height of the output bounding box are 0.000911805538293729, 0.0009637973789130264, 0.0003165724071125201, which are too small. Resulting in the model and bounding box not being together. If I use boundingBox. union (new THREE. Box3(). setFromObject (mesh)); Merging all meshes together to obtain the bounding box as the final bounding box will affect some of the originally normal model displays. This problem is due to the problem with the bounding box of the computational model itself

### Reproduction steps

![image](https://github.com/mrdoob/three.js/assets/22089884/35886c2a-5f9f-4a8e-8847-9235f1e3df20)
![image](https://github.com/mrdoob/three.js/assets/22089884/6defdb63-32fd-49c0-baba-79377b9a73fe)

I have also tried to delete the floor of a model and recalculate the bounding box, but found that it does not overlap with the model. Therefore, when some models are adapted, only the bounding box can know its center and radius for adaptation. There seems to be no other way to compare and judge whether the bounding boxes of the model are consistent, staggered, overlapping, or inconsistent in size, and there is no way to determine

### Code

[```js
// code goes here
```](https://codepen.io/xkx2024/pen/PoLYmLK?editors=1010)


### Live example

[* [jsfiddle-latest-release](https://jsfiddle.net/g3atw6k5/)
* [jsfiddle-dev](https://jsfiddle.net/hjqw94c5/)
](https://codepen.io/xkx2024/pen/PoLYmLK?editors=1010)

### Screenshots

![image](https://github.com/mrdoob/three.js/assets/22089884/8cdba41b-acef-4a47-84d4-d151a122f1f5)


### Version

0.145.0

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by calmheaded** [comment] 2023-12-20 05:54
![image](https://github.com/mrdoob/three.js/assets/22089884/2c619517-2c0f-4f57-86e8-17d0ddf02fcf)
Regarding the issue with that bird, if I traverse the mesh boundingBox. union (new THREE. Box3(). setFromObject (mesh)); Taking the union of all mesh bounding boxes can solve this problem. The green bounding box and the white bounding box are correct, but many other models display incorrectly

**Comment by calmheaded** [comment] 2023-12-20 05:58
![image](https://github.com/mrdoob/three.js/assets/22089884/86e4f603-c7cf-4067-ac78-4b08bc8b94ff)
If we use the method of merging meshes to obtain a bounding box, various display problems may occur in the model that was originally normally adapted due to overlapping and overlapping situations


![Image](https://github.com/mrdoob/three.js/assets/22089884/7d7e2d2a-74b2-44ee-918d-5d25e51d4001)
![Image](https://github.com/mrdoob/three.js/assets/22089884/edd071e4-ed31-4601-bfcd-896ee25d9d29)

**Comment by Mugen87** [comment] 2023-12-20 09:36
At least in your first codepen you compute the bounding box with outdated world matrices. Use `model.updateMatrixWorld();` before creating the bounding box.

Duplicate of #21404.

**Closed by Mugen87** 2023-12-20 09:36 UTC

**Comment by Mugen87** [comment] 2023-12-20 09:40
As said before `Box3.setFromObject()` and `Box3.expandByObject()` should make sure they operate on up-to-date world matrices like `Object3D.getWorldPosition()` or `Object3D.getWorldDirection()`. Developers frequently have issues both `Box3` methods and then reports issues here. That is a clear sign the current behavior is error-prone.
