### ISSUE TITLE
DeviceOrientationControls is not in correct position in some latest Android phones

### ISSUE THREAD

**Issue by kezmanh** [mrdoob/three.js#22613] opened 2021-09-30 15:06 UTC
**Describe the bug**

Song Xperia 1 ii
Samsung s21+

Tried the above devices, need to set controls.alphaOffset= 80 in order to locate it to the center area of the camera.

However, there are no problems in iPhone and some of the older Android devices.

**Platform:**

 - Device: [Mobile]
 - OS: [Android, iOS]
 - Browser: [Chrome]
 - Three.js version: [r133]

**Comment by Mugen87** [comment] 2021-10-01 07:40
Duplicate of #15828.

**Closed by Mugen87** 2021-10-01 07:40 UTC

**Comment by mrdoob** [comment] 2021-10-01 07:51
@Mugen87 I'm thinking we could remove DeviceOrientationControls 🤔

**Comment by Mugen87** [comment] 2021-10-01 08:01
Yes, it seems now that WebXR has matured the class lost its primary purpose.

**Comment by niklasp** [comment] 2021-12-01 11:09
@mrdoob are there alternatives? How to let users navigate on mobile?
