### ISSUE TITLE
GLTFLoader: Support KHR_materials_transmission physically-based transparency

### ISSUE THREAD

**Issue by Doerge** [mrdoob/three.js#21000] opened 2021-01-04 17:29 UTC
**Describe the bug**

The extension `KHR_materials_transmission` does not semi transparent materials from a `.glb`.

**To Reproduce**

1. Get the reference glb from here https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/TransmissionTest
2. Load it with threejs gltf loader.
3. The parts of the geometry that are supposed to be semi-transparent are instead 100% opaque. Only 100% transparency is respected. See screenshots below.

***Live example***

https://jsfiddle.net/jt6ywhs5/12/

**Expected behavior**

Semi-transparency and transmission works.

**Screenshots**

Reference:
<img width="423" alt="Screenshot 2021-01-04 at 17 52 32" src="https://user-images.githubusercontent.com/3216279/103559289-31b6a580-4eb6-11eb-8ee1-0e45a4e3522b.png">
Threejs:
<img width="420" alt="Screenshot 2021-01-04 at 18 22 10" src="https://user-images.githubusercontent.com/3216279/103561476-db4b6600-4eb9-11eb-8dc5-69ca8a5bfe0d.png">

**Platform:**

 - Device: Desktop
 - OS: MacOS
 - Browser: Chrome 87.0.4280.88 (Official Build) (x86_64)
 - Three.js version: latest stable from https://threejs.org/build/three.module.js

**Comment by donmccurdy** [comment] 2021-01-04 17:37
three.js only implements a small part of the `KHR_materials_transmission` extension today, which is why we haven't listed the extension in the docs yet. There are more transmission features left to implement. See https://github.com/mrdoob/three.js/issues/16977 for a bit more about this. Also note that using an environment map is critical for physically-based reflections.

**Comment by Doerge** [comment] 2021-01-04 17:51
Ah I see. I was a bit too fast then. I landed on the source code through Google, and thought it was already there. Sorry!
Yeah, I didn't bother with an env map, since it was clear the semi transparency wasn't working. Was hoping it was just a setting but alas! Feel free to close this issue if it's already tracked elsewhere.

**Comment by donmccurdy** [comment] 2021-01-04 17:54
Let's keep this open — https://github.com/mrdoob/three.js/issues/16977 is a pretty broad issue so I think it's good to have something specifically tracking `KHR_materials_transmission`.

**Comment by yaroslavnikiforov** [comment] 2021-03-09 14:43
Is it possible to implement this in three.js using MeshPhysicalMaterial without extension? (like Rough Transmission yellow ball on the reference image)

**Comment by donmccurdy** [comment] 2021-03-09 17:35
No, some changes to MeshPhysicalMaterial would need to be made to support these features.

**Comment by yaroslavnikiforov** [comment] 2021-03-09 22:29
Hi, what is the status of implementing this, is it work in progress? Will it be included in the next release? Thanks.

**Comment by donmccurdy** [comment] 2021-03-09 22:41
Sorry, this is not being worked on right now. If anyone is interested in working on it please let us know. :)

**Comment by patricpalmefjord** [comment] 2021-03-10 08:48
Thank you for the update, I was hoping this enhancement would roll out during March. It would be really useful to have.

**Comment by rawwerks** [comment] 2021-03-15 01:58
i would be happy to subsidize the work if someone has the skills and bandwidth to get KHR_materials_transmission fully implemented in three.js . please reach out if you are interested and available in the coming weeks.

**Comment by Mandoliiin** [comment] 2021-04-19 13:05
Hi, I'm in real need of this enhancement. Any update when on we can expect this bug to be fixed? Otherwise, is there some workaround I can use to achieve similar effect in the meanwhile? I cannot find anything. Thanks! :slightly_smiling_face:

**Comment by rawwerks** [comment] 2021-04-25 15:30
if you can think of anyone who can get this done as a contractor, please send them here: https://www.upwork.com/job/Seeking-talented-javascript-developer-enhance-three_~0153b7a387f184d444/

**Comment by whatisor** [comment] 2021-04-29 01:53
The first issue of current transmission implementation is not yet auto-enable Transparent which makes Alpha meaningful.

`#ifdef TRANSMISSION
		diffuseColor.a *= mix( saturate( 1. - totalTransmission + linearToRelativeLuminance( reflectedLight.directSpecular + reflectedLight.indirectSpecular ) ), 1.0, metalness);
	#endif`
	
However, currently, other issues I found are:
+ roughness does not work as expected.
+ Alpha map does not work with Metallic
![Screenshot (89)](https://user-images.githubusercontent.com/6780177/116493068-1f7ad000-a8c8-11eb-979d-798afd29ed4a.png)

**Comment by whatisor** [comment] 2021-05-04 16:07
We decided to follow GLTF Viewer Sample to implement this. There is some point which needs to be considered:
+ Opaque object is considered as an environment/background of others with transmission. Should it be a forced rule in threejs core or just a flexible option of application where the application can choose background/foreground object? 
@mrdoob 

![KHR_Transmission_v0 1](https://user-images.githubusercontent.com/6780177/117032394-a64a0580-ad2b-11eb-9980-ca9e3e535dbe.png)

[Source](https://github.com/3dgraphicsplus/three.js/tree/KHR_materials_transmission)

**Comment by whatisor** [comment] 2021-05-04 16:14
Improvement points:
+ Refraction with thickness
+ Dynamic background ( adobe is crazy cool with this stuff for supporting by lazy rendering)
![adobe_transmission](https://user-images.githubusercontent.com/6780177/117035313-5de01700-ad2e-11eb-8dc5-36f7840c6472.png)
[Adobe](https://assets.adobe.com/id/urn:aaid:sc:US:77f9bb87-1444-4cbe-b602-cb4cfbdca7a9?view=dimension)

**Comment by mrdoob** [comment] 2021-05-04 19:59
@whatisor I think for now we should just render the opaque meshes into a renderTarget: https://github.com/mrdoob/three.js/issues/16977#issuecomment-749793318

**Comment by whatisor** [comment] 2021-05-05 11:30
Yes, agreed. @mrdoob 
However, I am also considering how it can become a PR with these modifications and next improvements...

**Comment by whatisor** [comment] 2021-05-08 17:41
![fixed-roughness-lod](https://user-images.githubusercontent.com/6780177/117548374-e4626480-b05e-11eb-9482-381ba41a059d.png)

Fixed roughness by texturelod. I guess it is more accurate if the map is POT. ( right now just using default rendering resolution for opaque map resolution)

**Comment by mrdoob** [comment] 2021-05-10 12:39
@whatisor looking good!

**Comment by whatisor** [comment] 2021-05-13 07:16
![image](https://user-images.githubusercontent.com/6780177/118091751-64892100-b3f5-11eb-929a-2b7d924d6674.png)
The latest version,  I just fix the refraction issue for thickness support.
Thickness refraction is cool thing I got from gltf viewer. However, I do not see this parameter from GLTF data.

**Comment by whatisor** [comment] 2021-05-13 10:58
I have a big question: How to evaluate if Transmission rendering is correct?

**Comment by mrdoob** [comment] 2021-05-13 11:03
@elalish maintains this fidelity testing page: https://github.com/google/model-viewer/pull/2374 

We'll be able to compare with babylon.js implementation once the new example gets added.

**Comment by mrdoob** [comment] 2021-05-13 11:04
@elalish maintains this fidelity testing page: https://modelviewer.dev/fidelity/

We'll be able to compare with babylon.js implementation once the new example gets added.

**Comment by yaroslavnikiforov** [comment] 2021-05-13 16:14
Hi, is there some source code available to test? Thanks.

**Comment by donmccurdy** [comment] 2021-05-13 16:27
> However, I do not see [thickness refraction] parameter from GLTF data...

If only the `KHR_materials_transmission` extension is given, the material should be treated as "thin-walled", with no refraction. When the extension is also combined with [KHR_materials_volume](https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Khronos/KHR_materials_volume), refraction effects are possible with the `thicknessFactor` and `thicknessTexture` properties. Certainly I'd be excited to see both supported in THREE.MeshPhysicalMaterial. :)

**Comment by rawwerks** [comment] 2021-05-13 16:32
There's a great sneak peek and explanation of the volume refraction here: https://youtu.be/JMiXv2PgGBY?t=2552

**Comment by whatisor** [comment] 2021-05-15 02:23
> Hi, is there some source code available to test? Thanks.
Forked is here : https://github.com/3dgraphicsplus/three.js/tree/KHR_materials_transmission

**Comment by takahirox** [comment] 2021-05-18 05:47
> Certainly I'd be excited to see both supported in THREE.MeshPhysicalMaterial. :)

I'm thinking of adding the following properties corresponding to `KHR_materials_volume` parameters
- `thickness`
- `thicknessMap`
- `attenuationDistance`
- `attenuationColor`

Note: `MeshPhysicalMaterial` already has `transmission` and `transmissionMap` corresponding to `KHR_materials_transmission` parameters and `ior` corresponding to `KHR_materials_ior` parameter.

**Comment by takahirox** [comment] 2021-05-24 09:45
Made a PR #21884

**Comment by yaroslavnikiforov** [comment] 2021-05-26 12:28
Hi guys! Will it work out of the box like with Babylon, or it will need some additional setup like in the example? With PMREM env map, that toggleOpaque function and calling render twice in an animation loop. Doesn't look like it would be possible to use it, because of 9-10 fps like in the example.

<img width="572" alt="Screenshot 2021-05-26 at 15 25 50" src="https://user-images.githubusercontent.com/42115630/119659528-e71ed100-be36-11eb-8e47-343c68a5965d.png">

**Comment by donmccurdy** [comment] 2021-05-26 18:51
@yaroslavkhudchenko you can find the three.js example here, the setup is pretty normal:

https://github.com/mrdoob/three.js/blob/dev/examples/webgl_loader_gltf_transmission.html

Physically-based transmission will be more expensive than alpha blending. But your exact framerate will depend on many things. For example, I would expect that using transmission on a smaller area of the viewport will be cheaper than using it on a larger area of the viewport. The best thing to do here would be to test and report issues when this is available.

**Comment by donmccurdy** [comment] 2021-05-27 18:59
Fixed in https://github.com/mrdoob/three.js/pull/21884, many thanks @takahirox, @whatisor, @rawwerks and anyone else contributing here. 👏

**Closed by donmccurdy** 2021-05-27 18:59 UTC
Labels: Enhancement

**Comment by takahirox** [comment] 2021-06-16 05:03
So, the transmission support quality got better with the several PRs.

I'm thinking of adding `KHR_materials_volume` and `KHR_materials_ior` extensions support to `GLTFLoader` next.

I would like to know your opinion about the new example.

**1. Model**

I'm thinking of using TransmissionRoughnessTest model from glTF-Sample-Models repo because it has transmission, volume, and ior extensions

https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/TransmissionRoughnessTest

Let me know if you know better models.

**2. Update the existing example or new Example**

I think we have three options.

a.  Replacing the model of `webgl_loader_gltf_transmission` example.

b. Add the new model to `webgl_loader_gltf_transmission` and allow users to switch models like `webgl_loader_gltf_extensions`

c. Adding a new example `webgl_loader_gltf_volume`

I don't have strong opinion. Any preferences?

**Comment by donmccurdy** [comment] 2021-06-16 05:38
A few more samples:

- https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/AttenuationTest
- https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/DragonAttenuation

/cc @emackey I don't suppose there is a version of https://sketchfab.com/3d-models/real-time-refraction-demo-mosquito-in-amber-37233d6ed84844fea1ebe88069ea58d1 with these extensions added?

No preference on whether, or where, to add a new example.

**Comment by takahirox** [comment] 2021-06-16 05:43
> * https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/AttenuationTest
> * https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/DragonAttenuation

I knew those two models but unfortunately they don't use `KHR_materials_ior` extension although the dragon model looks nicer than TransmissionRoughnessTest.

**Comment by donmccurdy** [comment] 2021-06-16 05:49
I'll gladly add IOR to as many models as you want, if you're working on implementing it. 😍

**Comment by mrdoob** [comment] 2021-06-16 11:07
@takahirox 

> b. Add the new model to `webgl_loader_gltf_transmission` and allow users to switch models like `webgl_loader_gltf_extensions`

That sounds like the best option to me 👍

**Comment by WestLangley** [comment] 2021-06-16 11:57
As I said elsewhere, the `webgl_loader_gltf_transmission` example is not useful to us because the parameter settings are not accessible. There is no way to determine if the code is working properly because we don't know what we are looking at.

That example _is_ useful for comparing three.js to other renderers.

I would remove it from the examples. We have another transmission example with a GUI.

**Comment by mrdoob** [comment] 2021-06-16 12:07
I think it is useful so people can see that we correctly render gltfs that use transmission though.

**Comment by WestLangley** [comment] 2021-06-16 12:25
>I think it is useful so people can see that we correctly render gltfs that use transmission though.

Do you plan to add all the examples? https://github.com/cx20/gltf-test#extension-test-models

**Comment by emackey** [comment] 2021-06-16 13:23
> I knew those two models but unfortunately they don't use `KHR_materials_ior` extension

This is one of those wrinkles in the glTF spec that I wasn't able to avoid.  The IOR extension merely sets the IOR, which defaults to 1.5 if you don't use the IOR extension.  The actual switch for enabling or disabling the refractions themselves is controlled by the `thicknessFactor` in `KHR_materials_volume` being zero or nonzero (thin-walled or thick-volume material).  It may not be intuitive at first glance, but it makes sense when you take the time to deeply understand the glTF materials system design.

> /cc @emackey I don't suppose there is a version of [the Sketchfab mosquito with the new glTF extensions]

Yes, I had built that a while ago as a Khronos-internal test.  But the source model is CC-BY and I've been meaning to post in on the sample repo with some nice documentation and credits.  Someday soon I hope, unless someone else beats me to it.  Bonus points if the proper IOR for amber is looked up and added to the model.

**Comment by takahirox** [comment] 2021-06-16 16:20
I agree with @mrdoob 

> I think it is useful so people can see that we correctly render gltfs that use transmission though.

We have one example or model per one glTF extension which `GLTFLoader` support.

**Comment by donmccurdy** [comment] 2021-06-16 17:30
In my mind the three purposes of examples are, from most to least important:

1. Help users learn three.js
2. Showcase three.js features
3. Visual regression tests

The current transmission model mostly does (3), i.e. it's a model designed to test a feature and compare across engines. I don't necessarily think we need one model per glTF extension; ideally we'd cover each extension in unit tests instead. If we have a more visually interesting model for the transmission use case (with or without volume and ior) i think it'd be fine to replace the current one too.

**Comment by takahirox** [comment] 2021-06-16 17:41
> i think it'd be fine to replace the current one too.

I was thinking the similar thing. We have `webgl_materials_physical_transmission` example which has the parameter GUI then we can replace the testing model in `webgl_loader_gltf_transmission` with a more looking nicer one (maybe that Dragon one because it's well known by 3D CG folks) for showcase of glTF + transmission showcase purpose.

**Comment by WestLangley** [comment] 2021-06-16 18:06
`webgl_loader_gltf_transmission` has the `transparent` property of each sphere to set to `false`. Are you aware of that? Is that what the loader should be doing?

Even setting `transparent` to `true`, only front-faces show the hot-spot. (This may be a known limitation, but @mrdoob just added support for properly rendering backfaces of double-sided meshes.) There should be two hot-spots.
<img width="123" alt="Screen Shot 2021-06-16 at 1 53 43 PM" src="https://user-images.githubusercontent.com/1000017/122269153-e4018880-ceaa-11eb-8e14-65e9c56f8866.png">

There is a tone mapping problem, somewhere...
<img width="113" alt="Screen Shot 2021-06-16 at 1 51 42 PM" src="https://user-images.githubusercontent.com/1000017/122269137-e06e0180-ceaa-11eb-991e-6d51fd134415.png">

**Comment by donmccurdy** [comment] 2021-06-16 18:45
> webgl_loader_gltf_transmission has the transparent property of each sphere to set to false. Are you aware of that? Is that what the loader should be doing?

In glTF, a model may specify "transmission+alphaMode=BLEND" or "transmission+alphaMode=OPAQUE". The latter is [recommended](https://github.com/KhronosGroup/glTF/blob/master/extensions/2.0/Khronos/KHR_materials_transmission/README.md#blend-mode) but not required. The loader is interpreting `alphaMode=OPAQUE` as `transparent=false`. It is not a perfect analog, since `.transparent` controls three things: blend mode, sort order, and two-pass double-sided rendering.

I think you are asking if associated behaviors — other than the blend mode — should apply to transmissive materials, too?

**Comment by WestLangley** [comment] 2021-06-16 19:07
@donmccurdy Thank you for your reply.

I was trying to determine why, when looking at the transmissive sphere, I do not see two hot-spots. To try to determine why, I had to debug the loaded glTF model, because the model parameter settings are obfuscated, and there is no other way to tell what I am looking at.

That is all I was focusing on, but I think your higher-level questions are important.

**Comment by coderextreme** [comment] 2021-07-02 04:24
> Hi, I'm in real need of this enhancement. Any update when on we can expect this bug to be fixed? Otherwise, is there some workaround I can use to achieve similar effect in the meanwhile? I cannot find anything. Thanks! slightly_smiling_face

Something like this? https://playcanv.as/p/wQgQBgkE/

**Comment by donmccurdy** [comment] 2021-07-10 04:58
@takahirox this might be a helpful sample and discussion, as well: https://github.com/KhronosGroup/glTF-Sample-Models/pull/319

**Comment by takahirox** [comment] 2021-07-11 02:14
@donmccurdy 

Thanks! I will make an example with it.
