### ISSUE TITLE
Outline pass can't handle transparent background

### ISSUE THREAD

**Issue by kevinkleine** [mrdoob/three.js#12678] opened 2017-11-16 18:11 UTC
##### Description of the problem 

After commit b3cf1c73c279d7d9788d4a9735d17dcb7893b50c the outlinePass renders transparent backgrounds in black.

##### Three.js version

- [x] Dev
- [x] r88

##### Browser

- [x] Chrome latest
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows 10
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment] 2017-11-16 18:52
This commit was reverted, see #12281

Maybe a subsequent commit introduced the problem. Does it work with `R87`?

**Comment by yuluyi** [comment] 2017-12-21 12:12
Same problem in r89

**Comment by DIeHarke** [comment] 2018-02-07 13:35
I can also confirm that this issue still exists in r89.

**Comment by Mugen87** [comment] 2018-02-07 13:41
@DIeHarke Can you provide a live demo for debugging? 😇 

Or maybe you can tell how to change the example [webgl_postprocessing_outline.html](https://threejs.org/examples/webgl_postprocessing_outline.html) in order to reproduce the issue.

**Comment by DIeHarke** [comment] 2018-02-07 15:28
@Mugen87 I create a pastebin with an updated example. You can find it here:

[https://pastebin.com/u7reMDFg](url)

Things I changed:
- Created a css color gradient background (line: 9)
- Activated alpha mode of WebGlRenderer (including setting of clearColor, gammaInput and gammaOutput) (line: 150 - 155)
- (Re-)Enabled resetting to empty array, when no object intersection was found (line: 357)

Now when you hover over the scene and you are not intersecting any objects you can see the gradient background. Otherwise if an intersection was found the outline gets drawn and the background changes to black.

**Comment by Mugen87** [comment] 2018-02-07 16:54
Okay, i've created a fiddle so we can easily test the issue: https://jsfiddle.net/9a3c8o5a/3/

**Comment by WestLangley** [comment] 2018-02-07 17:06
Are you sure this is a bug? Try the original version of `OutlinePass` and see if transparent background was ever supported. If not, this is a feature request.

**Comment by Mugen87** [comment] 2018-02-07 17:37
You are right. I've tested with an [older version](https://github.com/mrdoob/three.js/blob/eafc8ad66ded672dcc9fc6457f43ece04d7aff7c/examples/js/postprocessing/OutlinePass.js) and there is the same behavior:

https://jsfiddle.net/9a3c8o5a/4/

**Comment by DIeHarke** [comment] 2018-02-07 18:02
Hmm okay I just thought it was possible before, because the title of the issue gave me that impression.

**Comment by DIeHarke** [comment] 2018-02-09 10:23
I think I came up with a nice approach  for alpha support. The basic idea is to create the "blurring" and "glowing" of the outline not by darken the rgb color part. Instead the alpha part of the color is getting reduced.

Main changes in the code:
- The edge detection shader got changed. Instead of outputting colors for the visible and hidden color it is setting either the r or g value of the color to 1.
   - edge is visible: fragment color (1.0, 0.0, 0.0)
   - edge is hidden: fragment color (0.0, 0.0, 0.0)
- The final overlay shader got changed. Uniforms for the visible and hidden color are now getting passed to the shader as well. The r and g values of the previous finalColor computed in fragmentShader are now being used as weighting factor to cumulate the visible and hidden color to create the final normalized rgb color value. The alpha value defines the sum of both weighting factors.

Here is a fiddle with a very rough implementation:

https://jsfiddle.net/q916xq1s/

**Comment by DIeHarke** [comment] 2018-02-09 19:27
Here is also a fiddle with a version, where the pulsing feature is also realised with the alpha approach:
- https://jsfiddle.net/k9sg683h/

**Comment by Mugen87** [comment] 2018-02-10 10:06
I've encountered a little bug: The usage of the pattern texture does not work anymore.

**Comment by DIeHarke** [comment] 2018-02-10 10:22
Okay fixed in this version:
- https://jsfiddle.net/ntkfoyc7/

**Comment by Ben-Mack** [comment] 2018-03-18 09:13
@DIeHarke Working great, thank you!

Can you create a pull request to merge this feature?

**Comment by alwxkxk** [comment] 2018-11-20 10:08
@DIeHarke thank you !

**Comment by silvainSayduck** [comment] 2019-01-08 14:44
Thanks for the awesome work @DIeHarke!

On a side note, I think `blending: THREE.AdditiveBlending` should also be replaced by `blending: THREE.NormalBlending` in the `getOverlayMaterial` function, as it enables using `OutlinePass` with light opaque backgrounds.

(Unfortunately, the `FXAAShader` yields very poor results with a transparent background, and is still the best way to get anti-aliasing while using `EffectComposer` imho.)

**Comment by Mugen87** [comment] 2019-09-11 09:39
Fixed via #17462

Working fiddle: https://jsfiddle.net/dmfe9p3a/1/

**Closed** 2019-09-11 09:38 UTC
Labels: Feature Request
