### ISSUE TITLE
StereoEffect is not working like it was in r65 - Mobile Stereo VR effect with DeviceOrientation

### ISSUE THREAD

**Issue by RudyAramayo** [mrdoob/three.js#8865] opened 2016-05-12 06:32 UTC
##### Description of the problem

StereoEffect is not working for Google Chrome Canary

on iOS safari and chrome stereoeffect is working
on OSX safari is working but on google chrome canary (Version 52.0.2728.0 canary (64-bit)
) stereo effect is not wokring

it happened since I upgraded from the r65 build to the r76 build. I upgraded three.min.js as well as StereoEffect.js which uses the new StereoCamera object.

Can you please advise if you can reproduce the following error:
On all browsers including mobile, you can see the stereo output jsut fine.
On Chrome Canary, the following web link will show only half the rendering...

http://orbitusbiomedical.github.io/BioPen/tornado3.html?stereo=true

What should I do for the stereo support? is this a browser bug that needs to be filed with Google Chrome? the right camera renders for 1 frame and then instantly becomes a blank screen.

Thanks! Love the framework and working with it is a pleasure!
...
##### Three.js version
- [ ] Dev
- [x] r76
- [x] r65
##### Browser
- [ ] All of them
- [x] Chrome
- [x] Safari
- [ ] Firefox
- [ ] Internet Explorer
##### OS
- [ ] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [x] IOS
- [x] OSX
##### Hardware Requirements (graphics card, VR Device, ...)

Google cardboard, galaxy gear vr, oculus rift

**Comment by RudyAramayo** [comment] 2016-05-12 06:36
http://threejs.org/examples/#webgl_effects_stereo

This example shows a similar effect... if you see the right camera is very different in brightness than the left eye... seems to be only with Google Chrome Canary, Google Crome seems to be rendering properly

**Comment by makc** [comment] 2016-05-12 21:12
I can confirm.
![screen shot 2016-05-12 at 23 11 10](https://cloud.githubusercontent.com/assets/242577/15230635/f939dcae-1896-11e6-92dd-0159d0d371bb.png)

Also, the line between left and right is shaking at some angles?

**Comment by mrdoob** [comment] 2016-05-12 22:21
I can reproduce too.

http://threejs.org/examples/#webgl_effects_anaglyph also looks much more bright.

**Comment by mrdoob** [comment] 2016-05-12 22:22
@makc That error is unrelated. It has already been fixed in the `dev` branch.

**Comment by Mugen87** [comment] 2018-02-17 13:54
Unable to reproduce with Chrome  64.0.3282.140. Closing for now.

**Closed by Mugen87** 2018-02-17 13:54 UTC
Labels: Browser Issue
