### ISSUE TITLE
USDZ Loader doesn't load certain USDZ files

### ISSUE THREAD

**Issue by kitaedesigns** [mrdoob/three.js#26864] opened 2023-09-28 21:10 UTC
### Description

The USDZ loader seems to only load USDZs with a certain hierarchy. USDZs with a flat hierarchy do not load in the 3D scene at all. As you can see in the screenshot below, USDZ with a 'Materials' and 'Geom' like the default saeukkang.usdz model will load just fine, other USDZs that do not have this hierarchy like the flower_tulip.usdz will not load and appear in the scene at all. 

### Reproduction steps

1. Compare loading the USDZ that's in the USDZ Loader example https://threejs.org/examples/models/usdz/saeukkang.usdz and one from Apple's USDZ page https://developer.apple.com/augmented-reality/quick-look/models/tulip/flower_tulip.usdz

2. The Apple USDZ will not load in the scene and be viewable (flower_tulip.usdz)

3. If you open up the USDZs in Reality Composer Pro (Mac Only) you can see the hierarchy structure is different between the two models. This may be the heart of the issue.

### Code

usdzLoader.load("https://threejs.org/examples/models/usdz/saeukkang.usdz", async function ( object ) {
        scene.add(object)
    })

### Live example

https://threejs.org/examples/?q=usdz#webgl_loader_usdz

### Screenshots

![image](https://github.com/mrdoob/three.js/assets/23407511/f7982a3a-b28f-4a89-95ae-1996e9d4b82a)

### Version

r157

### Device

Desktop, Mobile

### Browser

Chrome, Safari

### OS

Windows, MacOS

**Comment by mrdoob** [comment] 2023-09-29 03:26
It's unrelated to hierarchy.

The `flower_tulip.usdz` file has a `usdc` (crate) inside which we don't support yet.
We only support `usda` files for now.

**Comment by mrdoob** [comment] 2023-09-29 03:26
Duplicate of #26171

**Closed by mrdoob** 2023-09-29 03:26 UTC
