### ISSUE TITLE
Glitches in the LensFlare demo

### ISSUE THREAD

**Issue by trusktr** [mrdoob/three.js#13170] opened 2018-01-24 21:05 UTC
##### Description of the problem

In the [LensFlare demo](https://threejs.org/examples/webgl_lensflares.html), I see glitches that look like this

![screenshot 2018-01-24 at 10 55 28 am](https://user-images.githubusercontent.com/297678/35356756-31c69374-0106-11e8-8f76-9411f36cbf1e.png)

##### Three.js version

- [ ] Dev
- [x] r89 (at time of writing)
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome (in Chrome OS, Samsung Chromebook Pro)
- [ ] Firefox (Android version in Chrome OS, unable to reproduce here)
- [ ] Internet Explorer (didn't test)

##### OS

- [ ] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS
- [x] Chrome OS

Maybe this is just a Chrome OS issue?

**Comment by trusktr** [comment] 2018-01-24 21:08
Unable to reproduce in Chrome for macOS. Maybe it's a Chrome OS issue.

**Comment by Mugen87** [comment] 2018-01-24 22:43
I unable to reproduce on Chrome (64.0.3282.119) for macOS 10.13.2. Is it the only example where you see such artifacts? Can you please make a test with the `dev` branch, too?

**Comment by Mugen87** [comment] 2018-01-28 21:09
Closing for now. I suggest to open an issue at https://bugs.chromium.org/p/chromium/issues/list

**Comment by mrdoob** [comment] 2018-01-31 16:03
Actually, I can reproduce on a PixelBook.

The new version in `dev` doesn't show the artifacts though:
http://rawgit.com/mrdoob/three.js/dev/examples/webgl_lensflares.html

However, it's also slower. I'll have to investigate...

**Comment by mrdoob** [comment] 2018-02-09 03:40
#13280 solved the performance issues for me.

**Comment by Mugen87** [comment] 2018-02-09 19:22
The performance is still the same on my iMac. I've noticed that it's highly resolution dependent. If I reduce the size of my window, performance gets much better

**Comment by mrdoob** [comment] 2018-02-09 20:39
Actually... Yeah, I still have performance issues on the MacBook Pro...

**Comment by mrdoob** [comment] 2018-02-13 03:43
@Mugen87 After trying everything... Seems like, for whatever reason, adding `alpha: true` back to the `WebGLRenderer` fixes the performance issue... 1937e58e8eedff74f2a8c2d3274a56c098cddc38

Do you see the same on your iMac?

**Comment by mrdoob** [comment] 2018-02-13 03:47
Note that... This doesn't seem related to the `Lensflare` code. As I can see the same behaviour by commenting out the `light.add( lensflare );` line.

**Comment by Mugen87** [comment] 2018-02-13 13:18
> Do you see the same on your iMac?

Yes 😊 . The performance is now nearly identical to the previous lensflare implementation. I wonder why `alpha: true` makes the difference...

**Comment by mrdoob** [comment] 2018-02-13 13:59
Yeah... I'll try to reproduce the issue and report the bug. Closing this 🙌

**Comment by mrdoob** [comment] 2018-02-14 02:07
Chrome bug for the `alpha: true` regression: https://bugs.chromium.org/p/chromium/issues/detail?id=812071

**Comment by mrdoob** [comment] 2018-02-22 18:59
Okay, fix landed and should be solved in Chrome 65.

**Comment by mrdoob** [comment] 2018-03-07 22:07
Okay, Chrome 65 fixed the `alpha: true` issue. Things are fast once agaIn on MacBook Pros.

I'll report the glitches on Chromebooks next.

**Closed** 2018-12-05 14:35 UTC
Labels: Browser Issue

**Comment by mrdoob** [comment] 2018-12-11 05:21
I was going to say that we shouldn't close because it had not been resolved yet, but I tried on the Pixelbook and I can't reproduce anymore 🎉

**Comment by Mugen87** [comment] 2018-12-11 09:40
Understood! 😇
