### ISSUE TITLE
In version 131, fbx files are loaded without textures.

### ISSUE THREAD

**Issue by avatar-studio** [mrdoob/three.js#22320] opened 2021-08-12 20:02 UTC
**Describe the bug**

In version 131, fbx files are loaded without textures.

**To Reproduce**

1. extract attached file
2. run index.html

reproduce file is below

***Code***

    let character = await new Promise((res,rej)=>{
        new FBXLoader().load('ArcherRi01.FBX', newChar=>res(newChar));
    });

***Live example***

nothing

**Expected behavior**

loaded without texture

**Screenshots**

![qqqq11212](https://user-images.githubusercontent.com/88191844/129261856-90dced3a-4de0-4170-a704-db57ea679e13.png)

**Platform:**

 - Device: [Desktop, Mobile]
 - OS: [Windows, MacOS, Linux, Android, iOS]
 - Browser: [Chrome, Firefox, Safari, Edge]
 - Three.js version: [dev, r131]

**Comment by Mugen87** [comment] 2021-08-12 20:38
Duplicate of #22285.

**Closed by Mugen87** 2021-08-12 20:38 UTC
