### ISSUE TITLE
UnrealBloompass effect has a bug in iOS 15

### ISSUE THREAD

**Issue by uoon-dev** [mrdoob/three.js#24022] opened 2022-05-07 15:26 UTC
**Describe the bug**
When applying the UnrealBloomPass effect to any canvas image from three/examples/jsm/postprocessing/UnrealBloomPass,
it causes an afterimage effect. 

**To Reproduce**

1. Go to threejs example uses UnrealBloomPass (iOS 15)
2. Move the mesh to any direction

***Live example***
* https://threejs.org/examples/webgl_postprocessing_unreal_bloom.html

**Expected behavior**
There should be no afterimage on the canvas where the UnrealBloomPass effect was applied.

**Screenshots**
<img src="https://user-images.githubusercontent.com/38661266/167260360-4e521c41-d65c-44b5-8e89-f63ccb5ade19.jpg" width="430" />

**Platform:**

 - Device: Mobile
 - OS: iOS 15
 - Browser: Chrome, Safari
 - Three.js version: 0.140.0

**Comment by Alex-Orsholits** [comment] 2022-05-08 15:50
Hi, I have also witnessed other postprocessing effects with a similar issue, such as SAOPass (but not SSAOPass!). 
I am also using iOS15 (iPad OS).

Sadly, the developer console does not output any sort of error:

![IMG_0758](https://user-images.githubusercontent.com/56907127/167304021-b7acb7e5-fbdd-4ed6-9719-a7735622fcc8.jpg)

**In my case, turning off antialiasing somehow fixed the issue, though I am not exactly sure why...**

(For reference, here is a video of the issue in the case of SAOPass)
https://www.youtube.com/shorts/7OAlpVqS5wA

**Comment by LeviPesin** [comment] 2022-05-08 16:19
This is a duplicate of https://github.com/mrdoob/three.js/issues/23730 and https://github.com/mrdoob/three.js/issues/23733.

**Closed** 2022-05-08 17:45 UTC
Labels: Duplicate, Device Issue
