### ISSUE TITLE
WebGLBindingStates setupVertexAttributes BUG

### ISSUE THREAD

**Issue by xjindf** [mrdoob/three.js#20196] opened 2020-08-27 02:17 UTC
When I use the scene with both InstancedMesh and normal Mesh, and set the scene.overrideMaterial =Depthmaterial; then object.instanceMatrix Is the undefined value, because normal Mesh does not have this property. In the setupVertexAttributes method of WebGLBindingStates, const attribute= attributes.get(object.instanceMatrix) On line 386, an exception is thrown. It is suggested to modify the get method of WebGLAttributes and add judgment:

```
function get(attribute) {
     if (attribute === undefined) {
         return undefined;
     }
    if ( attribute.isInterleavedBufferAttribute ) { attribute = attribute.data ;}
    return buffers.get ( attribute );
}
```

**Comment by takahirox** [comment] 2020-08-27 02:28
Hi, thanks for the report!

Would you mind if making an example which can reproduce the error at [jsfiddle](https://jsfiddle.net/c5m1kazu/)? It helps us investigate the problem.

**Comment by xjindf** [comment] 2020-08-27 02:38
https://jsfiddle.net/yzogx8v5/4/

**Comment by xjindf** [comment] 2020-08-27 02:40
Before joining the instancematrix, my program is working well, so a judgment should be added here

**Comment by Mugen87** [comment] 2020-08-27 07:18
Duplicate of #17701.

**Comment by Mugen87** [comment] 2020-08-27 07:18
There is also a PR for fixing this issue: #20135

**Closed by Mugen87** 2020-08-27 07:18 UTC

**Comment by Mugen87** [comment] 2020-08-30 11:40
Another user in the forum has run into this bug: https://discourse.threejs.org/t/mixed-use-of-mesh-and-instancedmesh-r120-version-reports-an-error/18281/2
