### ISSUE TITLE
FBXLoader: fails to load file

### ISSUE THREAD

**Issue by NicekDev** [mrdoob/three.js#13786] opened 2018-04-06 12:53 UTC
##### Description of the problem

Hello,

the FBXLoader is not loading the file (folder scene1 in attached ZIP)
the fbx file verion is binary and higher than 7.0

in 3dMax it works - looks like this:
![2018-04-06_13-58-31](https://user-images.githubusercontent.com/38126874/38421147-75f59f58-39a6-11e8-9444-73b04f53bbdd.jpg)

After loading it with FBXLoader I get this error:

```
THREE.FBXLoader: FBX binary version: 7400
TypeError: GetData[infoObject.mappingType][infoObject.referenceType] is not a function
    at getData (FBXLoader.js:1402)
    at FBXLoader.js:949
    at Array.forEach (<anonymous>)
    at FBXLoader.js:947
    at Array.forEach (<anonymous>)
    at genGeometry (FBXLoader.js:829)
    at parseMeshGeometry (FBXLoader.js:743)
    at parseGeometry (FBXLoader.js:680)
    at parseGeometries (FBXLoader.js:662)
    at THREE.FBXLoader.parse (FBXLoader.js:107)
```

it seems like it is trying to load function GetData['ByVertice']['IndexToDirect'] that is not there (I don't know if it should)

After saving it with 3dMax and loading to THREEJS it works and looking good (folder scene1_max in attached ZIP):

![2018-04-06_14-07-57](https://user-images.githubusercontent.com/38126874/38421258-d320b2ee-39a6-11e8-8c40-4e74942717a1.jpg)

I'm not sure why it is not working with original file. I would like to keep it in original as it is generated by software that I use and I want to pass it automatically to THREEJS without manual opening and saving in external programs like 3dMax. 

I was trying to change some things in FBXLoader library (not knowing exactly what I'm doing - by switching off things that were causing problems) just to open original file somehow but what I only achieved is this view (no textures or correct mapping and visible triangles on objects):

![2018-04-06_14-01-51](https://user-images.githubusercontent.com/38126874/38421483-9935c7b2-39a7-11e8-8019-b6a20babf8b3.jpg)

FILES 
(folder "scene1" contains original file that doesn't work, "scene1_max" contains file saved in max that works):
[scene.zip](https://github.com/mrdoob/three.js/files/1883878/scene.zip)

PS: I'm new here so I hope I'm writing about this issue in correct place (if not let me know where should I put it)

##### Three.js version

- [x] Dev
- [ ] r91

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by looeee** [comment] 2018-04-07 03:00
> it seems like it is trying to load function GetData['ByVertice']['IndexToDirect'] 

I tried adding in this function, but it doesn't resolve the issue. Perhaps we should add support for this, but your model is the first I've seen that uses this mapping type for UVs. 

There are other problems with the UVs too - they are not defined in the range [0, 1], and all the indices are ranges `1, 2, .... , n` so it seems like they are being added unnecessarily. 

![untitled-1](https://user-images.githubusercontent.com/5307958/38450569-61b784b2-3a4a-11e8-9461-024b849ae3ca.png)

What program are you exporting from? It might have some errors in exporting UVs.

**Comment by NicekDev** [comment] 2018-04-07 18:37
Hi @looeee,

thank you for quick response on this issue. 

Would this be possible to add support for this in the way that it skips those UV issues or somehow fixes them? 3dMax reads the file correctly so probably would be possible to read it also in THREEJS. The program is Intericad and I unfortunately have no influence on how it exports the file...

Do you have any advice what could I do to make it work like in 3dMax but directly in THREEJS?

**Comment by looeee** [comment] 2018-04-08 06:29
@NicekDev the problem is I'm not sure what UVs greater than 1 are supposed to mean. It could be a shorthand for texture tiling, or it could be a mistake, in which case we'll have to figure out what the actual values should be. 

There's also a third possibility that the parser is reading the values wrong for some reason, I think this is unlikely though. 

I've made a new PR here #13798 which simplifies this part of the loader, although it doesn't yet make your model load correctly.

**Comment by NicekDev** [comment] 2018-04-10 08:40
hi @looeee 

I see the code is simplified, and now my case go through it.
It now breaks at:

```
TypeError: Cannot read property 'a' of undefined
    at genGeometry (FBXLoader.js:750)
    at parseMeshGeometry (FBXLoader.js:743)
    at parseGeometry (FBXLoader.js:680)
    at parseGeometries (FBXLoader.js:662)
    at THREE.FBXLoader.parse (FBXLoader.js:107)
    at Object.onLoad (FBXLoader.js:53)
    at XMLHttpRequest.<anonymous> (three.js:30796)
```

I was looking for this out of 0-1 range UVs mapping issue for FBX files.
I found some topics on other forums about it:

https://forums.autodesk.com/t5/fbx-forum/fbx-uv-usable-range/td-p/5287187

https://forums.autodesk.com/t5/fbx-forum/getpolygonvertexuv-returns-uv-s-outside-of-0-0-1-0-range/td-p/5141796

https://www.gamedev.net/forums/topic/661164-fbx-uv-usable-range/

so as you said:

>  I'm not sure what UVs greater than 1 are supposed to mean. It could be a shorthand for texture tiling

many people say here as well, it is for texture tiling.

You think it could be possible to add support on this as texture tiling for FBXLoader?
Would this solve problem with my file or there are also other issues?

**Comment by looeee** [comment] 2018-04-12 04:47
OK, I see the problem, but it's kind of odd. There are empty geometry nodes that consist of just a name and type but with no vertex info. 
I've added a check for these and your model loads correctly here #13834

Can you verify whether the model looks correct with this fix, or whether we need to do more work on the UVs?

**Comment by NicekDev** [comment] 2018-04-12 08:46
Beautiful! Works like a charm :)

The model loads correctly and I checked also on other generated files - bigger and more complex and everything is working.

Only issue that I found left is that there are some textures that use .tga image files so those textures are not loaded (object appears all white) but it's a detail as those textures are used not so often and also I can change them to other format.

Thank you @looeee. I owe you a beer ;)

**Comment by looeee** [comment] 2018-04-12 09:30
Great 😄 

I had previously created a PR to support TGA and DDS files, it kind of got lost in the complications of getting DDS to work and nobody seemed to have much need of it so I closed it:  #13227

It doesn't work for DDS files, but it was working for TGA files. 
You'll need to include [TGALoader](https://github.com/mrdoob/three.js/blob/dev/examples/js/loaders/TGALoader.js) as well.

**Comment by NicekDev** [comment] 2018-04-12 11:27
I included TGALoader but I get this from FBXLoader anyway:

```
FBXLoader.js:256 FBXLoader: Image type "tga" is not supported.
parseImage @ FBXLoader.js:256
parseImages @ FBXLoader.js:192
parse @ FBXLoader.js:103
```

I added 'image/tga' case to 'parseImage' function in FBXLoader (was not there) so the code goes through it and message is not appearing but still the objects are white without texture.

```
		switch ( extension ) {

			case 'bmp':

				type = 'image/bmp';
				break;

			case 'jpg':
			case 'jpeg':

				type = 'image/jpeg';
				break;

			case 'png':

				type = 'image/png';
				break;

			case 'tif':

				type = 'image/tiff';
				break;
				
			case 'tga':

				type = 'image/tga';
				break;
				
			default:

				console.warn( 'FBXLoader: Image type "' + extension + '" is not supported.' );
				return;

		}
```

am I missing something else?

**Comment by NicekDev** [comment] 2018-04-12 12:32
Great, works. Thanks a lot! :)

only thing I had to change is to get file type in a different way as this way I think is not working in current varsion:

`if ( fileName.indexOf( 'image/tga' ) !== - 1 )`

PS: Why not to add this TGA loading option to official FBXLoader? If the problem was with DDS files maybe just cut them off but leave TGA?

**Comment by looeee** [comment] 2018-04-12 12:44
No reason except for limited time and the fact that I didn't have any models with TGA textures to test it with. 

If you want to make a PR to add support that would be great 😄

**Closed** 2018-04-12 16:05 UTC

**Comment by NicekDev** [comment] 2018-04-12 19:14
@looeee I did a PR here:
#13841

There is only this "if" line that I know is not so nice... If you could just check it and propose change maybe :)
