### ISSUE TITLE
OrbitControls does not work correctly when the camera has a parent.

### ISSUE THREAD

**Issue by sanonz** [mrdoob/three.js#18817] opened 2020-03-05 10:27 UTC
##### Description of the problem

1. The camera has a parent.
2. The parent sets the position.

* [OrbitControls-example](https://stackblitz.com/edit/three-example) (latest release branch)

##### Three.js version

- [ ] Dev
- [x] r114
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment] 2020-03-05 10:34
Duplicate of #15267.

**Closed by Mugen87** 2020-03-05 10:34 UTC
