### ISSUE TITLE
Microsoft Edge compat

### ISSUE THREAD

**Issue by csuwildcat** [mrdoob/three.js#6915] opened 2015-07-27 23:37 UTC
Hey there Threesians,

I am working on assessing, cataloging, and triaging library compat with Microsoft Edge. Do you know the version compat range for Three in Edge? Are all versions fully operable in Edge? Also, do you have any bugs that block features or compat I can help with or escalate?
- Daniel

**Comment by mrdoob** [comment] 2015-07-28 00:19
No idea... I don't have a Microsoft Edge myself... 😔

**Comment by Cy-Bo-Rg** [comment] 2015-07-28 00:44
I was able to run three.js on android browser version 2.3.7.
it should run on everything... :P
If it won't , blame your browser(or your chipset)! X)

Also, why are you using many accounts,all related to yourself, to spread
the same message among many libraries ?
https://github.com/meteor/meteor/issues/4791
That's a lot of effort by your part! :P

**Comment by csuwildcat** [comment] 2015-07-28 01:40
@Cy-Bo-Rg though Edge is a (very) strictly standards compliant browser, I am doing personal outreach to library authors to check compat and see if there are any issues I can help with or escalate. Thankfully most libraries Just Work™, but given our fragile, coder humanity, we have seen a few bugs here and there (most of which are actually from Edge following the specs closer than others - I know, that's pretty mind blowing to hear from an MS browser).

I felt personally reaching out to each library would be maximally helpful to the community, as it gives lib authors a direct line in triaging and assessing what we hope will be a delightful change from IE :)

(Note: I just joined MS after running the Developer Ecosystem at Mozilla for 5 years, so I understand and sympathize with any frustration you have over IE and the past)

**Comment by mrdoob** [comment] 2015-07-28 02:02
I would *really* appreciate if Microsoft Edge adopted the open formats OGG and WebM. Because of Apple and Microsoft we are forced to have two versions of every video and audio we host on the web.

**Comment by dubejf** [comment] 2015-07-28 03:33
I haven't tried Edge yet. As far as I know, things mostly work in IE11, and have been working for the past few versions. My experience is limited though (e.g. no experience with post-processing effects).

Here are a few issues specific to IE I am aware of - nothing critical.

#6349 Function.name. (Solved by Polyfill) - I assume that one will be in Edge.
#5813 Problem with a simple shader loop. (Solved with library workaround) - Reproduced in IE11.
#6560 SVG to texture error. (Open) - Reproduced in IE11.
#4098/#6692 2D Canvas preserve-3d not supported. (Open) - That seems to be fixed in Edge.

**Comment by titansoftime** [comment] 2015-08-01 05:48
Just got Edge on my laptop. Experience is better than IE11 so far. WebGL (at least Three.js) performance is still less than chrome. I noticed one strange visual effect in Edge. I have a "winter" zone with a mirror reflection (based on ocean demo). On rotation the reflected objects kind of "streak" until I stop and the renderer can catch up.

You can see for yourself at titansoftime.com.

**Comment by bhouston** [comment] 2015-08-03 17:23
There are some important distinctions in terms of supported extensions, the most important I find is the CubeMap LOD extension: https://www.khronos.org/registry/webgl/extensions/EXT_shader_texture_lod/

The other issue is that transparent PNGs (32bit RGBA) are loaded by IE in such a way that their color depth is greatly reduced.

https://clara.io/view/42c32462-a1d7-4fb3-ad8e-1aefe39924ed/webgl

What it looks like in Edge (yikes!):

![image](https://cloud.githubusercontent.com/assets/588541/9043317/996b60d8-39e2-11e5-9edf-e8962921321a.png)

What it looks like in Chrome:

![image](https://cloud.githubusercontent.com/assets/588541/9043324/a38e8ec8-39e2-11e5-8696-7c7b686c7475.png)

What it looks like in Firefox:

![image](https://cloud.githubusercontent.com/assets/588541/9043344/c1a335a8-39e2-11e5-8dc7-083c944e0e50.png)

**Comment by csuwildcat** [comment] 2015-08-04 18:56
@bhouston I will get this into the hands of the Edge dev team.

**Comment by positlabs** [comment] 2015-10-05 18:48
@mrdoob, there are free VMs for testing Edge. 
https://dev.modern.ie/tools/vms/mac/

**Comment by mrdoob** [comment] 2015-10-05 19:08
IE11 and Window10 is 5GB... 😶

**Comment by positlabs** [comment] 2015-10-05 19:45
Another options is remoteIE, but it's kind of slow for webgl stuff. 

https://remote.modern.ie/

**Closed** 2016-12-17 23:00 UTC
