### ISSUE TITLE
WebGPU example "Fat line" broken when dash enabled

### ISSUE THREAD

**Issue by Makio64** [mrdoob/three.js#28977] opened 2024-07-26 06:16 UTC
### Description

On r167 the webgpu fatline example crash when i enabled "dashed" using   

<img width="242" alt="Screenshot 2024-07-26 at 14 14 15" src="https://github.com/user-attachments/assets/f0992408-fca0-424e-8ebf-9f3a79dac0c8">

<img width="808" alt="Screenshot 2024-07-26 at 14 09 07" src="https://github.com/user-attachments/assets/22235243-aacc-4836-8ee4-0ec753deaf97">

### Reproduction steps

1. go to https://threejs.org/examples/?q=webgpu#webgpu_lines_fat
2. enabled dashed

### Version

r167

### Device

Tested on m3 pro max.
Desktop

### Browser

Chrome

### OS

MacOS

**Comment by Mugen87** [comment] 2024-07-26 08:46
Duplicate of #28884-

**Closed by Mugen87** 2024-07-26 08:46 UTC
