### ISSUE TITLE
controls 

### ISSUE THREAD

**Issue by skdctlt** [mrdoob/three.js#21564] opened 2021-04-02 09:20 UTC
When I use ArrayCamera(), TrackballControls() doesn't work!

**Comment by Mugen87** [comment] 2021-04-02 09:36
Duplicate of #15107.

**Closed by Mugen87** 2021-04-02 09:36 UTC

**Comment by skdctlt** [comment] 2021-04-02 12:10
thank you! But I use the method you provided, it still doesn't work.
Here's my code, I don't know what went wrong.
		function animate() {
				controls.update();
				changeCameraRotation();
				render();
				requestAnimationFrame( animate );
			}


			function render(){
				renderer.render( scene, camera );
			}


			function changeCameraRotation(){
				subcamera_upper.rotation.copy(camera.rotation);
				subcamera_upper.updateProjectionMatrix();


				subcamera_lower.rotation.copy(camera.rotation);
				subcamera_lower.updateProjectionMatrix();


				subcamera_l.rotation.copy(camera.rotation);
				subcamera_l.updateProjectionMatrix();


				subcamera_p.rotation.copy(camera.rotation);
				subcamera_p.updateProjectionMatrix();


				subcamera_r.rotation.copy(camera.rotation);
				subcamera_r.updateProjectionMatrix();
			}

**Comment by skdctlt** [comment] 2021-04-08 06:34
> thank you! But I use the method you provided, it still doesn't work.
> Here's my code, I don't know what went wrong.
> 
> ```js
> 		function animate() {
> 				controls.update();
> 				changeCameraRotation();
> 				render();
> 				requestAnimationFrame( animate );
> 			}
> 
> 
> 			function render(){
> 				renderer.render( scene, camera );
> 			}
> 
> 
> 			function changeCameraRotation(){
> 				subcamera_upper.rotation.copy(camera.rotation);
> 				subcamera_upper.updateProjectionMatrix();
> 
> 
> 				subcamera_lower.rotation.copy(camera.rotation);
> 				subcamera_lower.updateProjectionMatrix();
> 
> 
> 				subcamera_l.rotation.copy(camera.rotation);
> 				subcamera_l.updateProjectionMatrix();
> 
> 
> 				subcamera_p.rotation.copy(camera.rotation);
> 				subcamera_p.updateProjectionMatrix();
> 
> 
> 				subcamera_r.rotation.copy(camera.rotation);
> 				subcamera_r.updateProjectionMatrix();
> 			}
> ```


> thank you! But I use the method you provided, it still doesn't work.
> Here's my code, I don't know what went wrong.
> 
> ```js
> 		function animate() {
> 				controls.update();
> 				changeCameraRotation();
> 				render();
> 				requestAnimationFrame( animate );
> 			}
> 
> 
> 			function render(){
> 				renderer.render( scene, camera );
> 			}
> 
> 
> 			function changeCameraRotation(){
> 				subcamera_upper.rotation.copy(camera.rotation);
> 				subcamera_upper.updateProjectionMatrix();
> 
> 
> 				subcamera_lower.rotation.copy(camera.rotation);
> 				subcamera_lower.updateProjectionMatrix();
> 
> 
> 				subcamera_l.rotation.copy(camera.rotation);
> 				subcamera_l.updateProjectionMatrix();
> 
> 
> 				subcamera_p.rotation.copy(camera.rotation);
> 				subcamera_p.updateProjectionMatrix();
> 
> 
> 				subcamera_r.rotation.copy(camera.rotation);
> 				subcamera_r.updateProjectionMatrix();
> 			}
> ```

[demo.zip](https://github.com/mrdoob/three.js/files/6276544/demo.zip)
This is my demo, but it still doesn't work, it doesn't rotate the camera.
