### ISSUE TITLE
A way to manage multiple instances

### ISSUE THREAD

**Issue by BrianCraig** [mrdoob/three.js#9160] opened 2016-06-17 04:21 UTC
I was trying to instance a geometry, but i find it too hard to manipulate. The scenario is this. I have a geometry & shader of some over-used thing in my game. But having to manage a lot of instances separately is really difficult when every attribute of every instance is somewhere on an array, and it's even more difficult when you want to destroy some instances and create new ones still drawing the ones you need. I came to the conclusion that is better to add some abstraction layer to this cases, in which i'm interested of program it.

I made some idea of the API that i think would be good, to make more developer-friendly instances, that manages by itself all the memory exchange to the GPU. [Here](https://gist.github.com/BrianCraig/9583e688206089f96bbdb5d6735cf0cf)

:)

**Comment by Mugen87** [comment] 2019-07-15 12:01
Duplicate of #5171

**Closed by Mugen87** 2019-07-15 12:01 UTC
Labels: Duplicate
