### ISSUE TITLE
Non flat-shaded materials sometimes fail to render on Chrome on Linux?

### ISSUE THREAD

**Issue by krzys-h** [mrdoob/three.js#27107] opened 2023-11-03 09:45 UTC
### Description

I've ran into a really weird bug which affects only some THREE.js content on Chrome on Linux. I can't quite figure out at what level the issue lies, but since the same model file runs fine in all non-THREE.js based viewers I figured I would start here, but I wouldn't be suprised if it turns out there is some underlying driver level issue. So far I only tested on `Intel(R) HD Graphics 4600`, but I will try to test same OS different GPU configuration soon.

I have a GLTF model file with a simple skinned mesh, which causes really weird glithes upon rendering - but only in this one browser/OS combination. After some investigation, I narrowed it down to possibly being an issue with rendering specific materials, as it doesn't happen when I enable `flatShading: true`. I'm not convinced this is the underlying issue though, as the same issue manifests itself in other places - so far I only saw it with THREE.js content though.

So far, I managed to reproduce the issue in:
1. My own code, using my own GLTF file (see the fiddle in the "Live example" section)
2. https://gltf.pmnd.rs/ - shows both the issue demonstrated here, as well as some similar artifacting on other objects, even when no skinned mesh is present
3. https://adjam93.github.io/threejs-model-viewer/ - shows the same thing, both when uploading my GLTF files, as well as the default objects (which are OBJ)

### Reproduction steps

Just run the attached fiddle on a platform where it breaks. Nothing else is necessary.

### Code

(the exact code does not seem relevant to the issue - see the attached fiddle which is basically the simplest usage of `GLTFLoader` possible)

### Live example

https://jsfiddle.net/9pwh5s70/22/

### Screenshots

* Repro demo using Chrome on Linux (not working)

  ![image](https://github.com/mrdoob/three.js/assets/1517255/c794de19-b661-4044-81f5-b9ab73f80fe3)
* Repro demo using Firefox on Linux on the same machine (working)
  
  ![image](https://github.com/mrdoob/three.js/assets/1517255/048d4677-a3b3-4fab-b6f0-8d4237bc2cfd)
* Repro demo using Chrome on Linux on the same machine, but I changed `flatShading` to `true` (working)

  ![image](https://github.com/mrdoob/three.js/assets/1517255/9a96cdbe-db02-4f86-9f06-75e71c42aa6c)
* Repro demo using Chrome on a different machine running Windows (working)

  ![image](https://github.com/mrdoob/three.js/assets/1517255/ca11fd1b-f91b-41a8-bc53-397c53f35886)
* Minor artifacting on a non-skinned mesh in https://gltf.pmnd.rs/ - does not happen on Windows, does not happen in Firefox on Linux

  https://github.com/mrdoob/three.js/assets/1517255/efc55d09-ba51-443b-a54d-6d505bd20d43
* Artifacting on https://adjam93.github.io/threejs-model-viewer/ using the default OBJ model - does not happen on Windows, does not happen in Firefox on Linux, does not happen when you switch materials to anything else

  ![image](https://github.com/mrdoob/three.js/assets/1517255/e492f5ad-f5e0-4527-9be3-c236d7e4960d)

### Version

r158 in the repro demo, but the same ssue happens in various versions scattered around the internet

### Device

Desktop

### Browser

Chrome

### OS

Linux

**Comment by Mugen87** [comment] 2023-11-03 10:42
I can't reproduce on macOS so can you make a test with `MeshBasicMaterial`? It would be interesting to know if the same issue happens with unlit materials.

**Comment by krzys-h** [comment] 2023-11-03 11:48
`MeshBasicMaterial` works fine:

![image](https://github.com/mrdoob/three.js/assets/1517255/3d0d80ec-f1e6-426f-ac37-f98067ad204b)

Here is the GPU report: [about-gpu-2023-11-03T11-45-41-051Z.txt](https://github.com/mrdoob/three.js/files/13249732/about-gpu-2023-11-03T11-45-41-051Z.txt)

**Comment by Mugen87** [comment] 2023-11-03 11:56
Do you mind trying to update the version of your Mesa driver to the latest version? Even if it works in Firefox, Chrome could still have problems with the GPU driver.

**Comment by krzys-h** [comment] 2023-11-03 12:06
I updated mesa from `23.0.4-0ubuntu1~22.04.1` to `24.0~git2311030600.5550c1~oibaf~j (git-5550c1d 2023-11-03 jammy-oibaf-ppa)` using [ppa:oibaf/graphics-drivers](https://launchpad.net/~oibaf/+archive/ubuntu/graphics-drivers) - nothing changed, the issue still happens.

Here is an updated GPU report: [about-gpu-2023-11-03T12-04-50-441Z.txt](https://github.com/mrdoob/three.js/files/13249922/about-gpu-2023-11-03T12-04-50-441Z.txt)

**Comment by krzys-h** [comment] 2023-11-03 13:06
I just tried a Ubuntu 22.04.1 live USB on the same machine, and to my suprise the issue doesn't happen there, even though the versions of Chrome and Mesa (before upgrade) are exactly the same? It seems that for whatever reason, my system chooses to run with Vulkan, while the Live USB chose OpenGL:

```diff
-*   Video Decode: Software only. Hardware acceleration disabled
+*   Video Decode: Hardware accelerated
 *   Video Encode: Software only. Hardware acceleration disabled
-*   Vulkan: Enabled
+*   Vulkan: Disabled

...

-GL implementation parts         : (gl=egl-angle,angle=vulkan)
-Display type                    : ANGLE_VULKAN
+GL implementation parts         : (gl=egl-angle,angle=opengl)
+Display type                    : ANGLE_OPENGL
 GL_VENDOR                       : Google Inc. (Intel)
-GL_RENDERER                     : ANGLE (Intel, Vulkan 1.2.238 (Intel(R) HD Graphics 4600 (HSW GT2) (0x00000416)), Intel open-source Mesa driver-23.0.4)
+GL_RENDERER                     : ANGLE (Intel, Mesa Intel(R) HD Graphics 4600 (HSW GT2), OpenGL 4.6 (Core Profile) Mesa 23.0.4-0ubuntu1~22.04.1)
```

Here is a full GPU report from the Live USB: 
[about-gpu-2023-11-03T12-56-39-516Z.txt](https://github.com/mrdoob/three.js/files/13250459/about-gpu-2023-11-03T12-56-39-516Z.txt)

**Comment by krzys-h** [comment] 2023-11-03 13:09
When I force disabled Vulkan via `chrome://flags`, the issue disappeared - I guess it's a browser bug then?

**Comment by Mugen87** [comment] 2023-11-03 18:37
Yes. Would you be willing to report your findings here?

**Comment by krzys-h** [comment] 2023-11-04 08:21
Reported at https://bugs.chromium.org/p/chromium/issues/detail?id=1499575

I could not figure out a way to set the component, so I assume I don't have the permissions to do that and they will triage it accordingly.

**Comment by Mugen87** [comment] 2023-11-04 10:25
My hope is the Chromium devs could maybe give us a hint at what point in the shaders the error might occur.

**Comment by mrdoob** [comment] 2023-11-08 08:56
We should probably close this.

**Closed by mrdoob** 2023-11-08 08:56 UTC
Labels: Browser Issue
