### ISSUE TITLE
UniformsUtils.clone() is deprecated — but nothing replaces it?

### ISSUE THREAD

**Issue by mattdesl** [mrdoob/three.js#10191] opened 2016-11-21 22:01 UTC
It looks like recent versions of ThreeJS have deprecated UniformsUtils.clone() with a warning message. However, `Object.assign` (which has replaced it in the examples) is not a real replacement. The reason is that `Object.assign` doesn't do a deep clone or clone ThreeJS specific objects, like `THREE.Color` or `THREE.Vector3`.

Typical usage:

```js
const baseShaderMaterial = new THREE.ShaderMaterial({ ... });

const redShaderMaterial = baseShaderMaterial.clone();

// we can now mutate the uniforms without affecting the base material!
redShaderMaterial.uniforms.color.value.setStyle('red');
```

Any particular reason why this function is deprecated? I've found it quite useful. 

Cheers!

**Comment by mrdoob** [comment] 2016-11-22 16:27
You can read the reasoning in #8016.

**Comment by mrdoob** [comment] 2016-11-22 16:28
The good news is that we have added a `clone()` to `Uniform`. Which also means, we'll have to transition to `new THREE.Uniform( 1.0 )` instead of `{ value: 1.0 }`...

**Comment by WestLangley** [comment] 2016-11-25 06:28
Is this the reason for the bizarre behavior in [this fiddle](http://jsfiddle.net/o65wcyvr/) (r.83dev)?

The cube on the right should be nearly-opaque blue, but takes on the material of one of the other cubes based on the rendering order (which is governed by the camera position).

**Comment by aardgoose** [comment] 2016-11-25 16:59
looks like it is.

replacing the settings for the blue cube with

uniforms.diffuse = new THREE.Uniform( new THREE.Color( 0x0000ff ) );
uniforms.opacity = new THREE.Uniform( 0.9 );

works as expected

**Comment by WestLangley** [comment] 2016-11-25 19:33
But in the fiddle, the same bizarre behavior occurs if no uniforms are redefined.

```javascript
var uniforms = Object.assign( {}, shader.uniforms );
// uniforms.diffuse = new THREE.Uniform( new THREE.Color( 0x0000ff ) );
// uniforms.opacity = new THREE.Uniform( 0.9 );
```

**Comment by WestLangley** [comment] 2016-12-11 01:58
I agree with @mattdesl that this is a problem.

**Comment by Mugen87** [comment] 2016-12-13 20:21
I slightly adjusted the camera of the [fiddle](http://jsfiddle.net/o65wcyvr/2/) so the first render produces the correct result. As soon as you move the camera the `ShaderMaterial` is rendered wrong. 

After some debugging i've found a problem that is maybe caused of the manner,`UniformsLib` is used in the library. In `three.js` the uniforms of a shader program are created via `UniformsLib` like this. 

```javascript
uniforms: Object.assign( {},
   THREE.UniformsLib.common,
   THREE.UniformsLib.aomap,
   THREE.UniformsLib.lightmap,
   ...
```
This approach means that the properties in `uniforms` (`diffuse`, `opacity`etc.) are shared over all materials because they are objects (e.g. `opacity: { value: 1.0 }`). The bizarre behavior in the example occurs since the execution of `WebGLRenderer .setProgram()` affects uniform values in other materials. In our case `WebGLRenderer .refreshUniformsCommon()` (which is triggered by `MeshLambertMaterial`) overwrites the `common` uniforms properties in the custom `ShaderMaterial`.

I'm not sure about this, but the way the library creates uniform objects does not look very robust to me. The example shows which strange errors can be caused by the implementation. I think we need to find a solution, so the uniform values of a material are more independent to each other.

**Comment by WestLangley** [comment] 2016-12-13 20:29
> I think we need to find a solution, so the uniform values of a material are more independent to each other.

We had a solution: `THREE.UniformsUtils.clone()`.

**Comment by Mugen87** [comment] 2016-12-13 20:32
Correct 😉 . `THREE.UniformsUtils.clone()` actually provides the mechanism for resolving the mentioned object references. This logic is now missing in some way...

**Comment by mrdoob** [comment] 2016-12-14 07:21
Yeah, I felt this was going to create problems... That's why I didn't released last month.

Un-deprecating!

**Comment by mrdoob** [comment] 2016-12-14 09:31
Done!

@aardgoose @takahirox sorry for the trouble guys! 😞

**Closed by mrdoob** 2016-12-14 09:31 UTC

**Comment by aardgoose** [comment] 2016-12-15 10:23
I was expecting you to reverse this, given the breakages it was causing. Got me to learn more parts of the code, so not at all wasted.

**Comment by takahirox** [comment] 2016-12-19 01:18
FYI,

I think the reason why this didn't cause any problems among non-`ShaderMaterial`s is
their uniforms are dynamically updated right before their rendering by
copying the data from material parameters to shared uniforms.

Even with `ShaderMaterial` we can do that by using `onBeforeRender()` without
`THREE.UniformsUtils.clone()`. Actually `OutlineEffect` does this and haven't
faced any problems (so far).
