### ISSUE TITLE
Error "Cannot read property 'y' of undefined" in the file ShapePath.js

### ISSUE THREAD

**Issue by blizzard-mindfloat** [mrdoob/three.js#20296] opened 2020-09-08 20:16 UTC
If in the file [Font.js](https://github.com/mrdoob/three.js/blob/dev/src/extras/core/Font.js) in the function `createPath` value `glyph.o` ends with text `"m {number} {number} z "` (e.g. `"m 167 878 z "`) then in the file [ShapePath.js](https://github.com/mrdoob/three.js/blob/dev/src/extras/core/ShapePath.js) in the function `isPointInsidePolygon` occurs this error:
![image](https://user-images.githubusercontent.com/38355819/92515962-c06f2a80-f214-11ea-9067-bd7d604968fa.png)
![image](https://user-images.githubusercontent.com/38355819/92516377-6e7ad480-f215-11ea-99e3-0749538ff5b7.png)

This happens, for example, when I use character "Ö" of font [Calibri](https://github.com/mrdoob/three.js/files/5190808/Calibri.zip).

In the file [ShapePath.js](https://github.com/mrdoob/three.js/blob/dev/src/extras/core/ShapePath.js) in the function `toShapes` this code:
```
} else {

	newShapeHoles[ mainIdx ].push( { h: tmpPath, p: tmpPoints[ 0 ] } );
```
should be changed to this code:
```
} else if ( tmpPoints.length ) {

	newShapeHoles[ mainIdx ].push( { h: tmpPath, p: tmpPoints[ 0 ] } );
```

**Comment by mrdoob** [comment] 2020-09-09 06:23
Can you create a jsfiddle?

**Comment by blizzard-mindfloat** [comment] 2020-09-16 09:45
https://jsfiddle.net/blizzard_mindfloat/6smn8heb/

**Comment by Mugen87** [comment] 2020-09-16 10:10
I've checked out your fiddle but I don't think the suggested change is appropriate. We should clarify instead why `THREE.Font` creates an empty sub path. 

Does a definition of `"m {number} {number} z "` actually makes sense? Could this be a problem in the font generator?

**Comment by blizzard-mindfloat** [comment] 2020-09-16 11:37
The JSON file used in jsfiddle was generated using generator http://gero3.github.io/facetype.js/ and using TTF file downloaded from https://www.fontmirror.com/calibri.

I have replaced all texts `"m {number} {number} z "` with text `"z"` and now there is no error and the character "Ö" seems to be fine: https://jsfiddle.net/blizzard_mindfloat/6smn8heb/2

**Comment by Mugen87** [comment] 2020-09-16 12:06
@gero3 Do you mind having a look at this. It would be good to know why `"m {number} {number} z" exists in the JSON (and what's its purpose).

**Comment by Mugen87** [comment] 2020-09-21 18:10
Closing for now. The issue can be reopened if it's proven that `facetype.js` works as intended.

**Closed by Mugen87** 2020-09-21 18:10 UTC
