### ISSUE TITLE
TransformControls example doesn't disable OrbitControls when interacting

### ISSUE THREAD

**Issue by gsimone** [mrdoob/three.js#20202] opened 2020-08-27 14:43 UTC
It used to, the code is still here, so it's probably something that changed in either OrbitControls or TransformControls

https://threejs.org/examples/#misc_controls_transform

**Comment by Mugen87** [comment] 2020-08-27 15:18
Duplicate of #20193.

**Closed by Mugen87** 2020-08-27 15:18 UTC
