### ISSUE TITLE
Cannot update texture properties of WebGLRenderTarget without an image

### ISSUE THREAD

**Issue by AlexVestin** [mrdoob/three.js#19244] opened 2020-04-27 21:25 UTC
##### Description of the problem
I'm trying to update the wrapping and filtering of the texture in a WebGLRenderTarget object,
however when updating the properties and setting `needsUpdate` of the texture to true, it throws the error:
```
THREE.WebGLState: TypeError: Failed to execute 'texImage2D' on 'WebGLRenderingContext': No function was found that matched the signature provided
```

I made a fiddle to test it here: https://jsfiddle.net/7bdLa8of/10/

I looked around the code and found that since image is not undefined [here](https://github.com/mrdoob/three.js/blob/952b8a3e31ec08a1b08b62e9947755a7be74701c/src/renderers/webgl/WebGLTextures.js#L330) (it's ` { width, height }`) it gets treated as an HTMLElement [here](https://github.com/mrdoob/three.js/blob/952b8a3e31ec08a1b08b62e9947755a7be74701c/src/renderers/webgl/WebGLTextures.js#L813) and fails.

I tried simply guarding it with a isRenderTarget and skipping the previous line and also [this](https://github.com/mrdoob/three.js/blob/952b8a3e31ec08a1b08b62e9947755a7be74701c/src/renderers/webgl/WebGLTextures.js#L639), however that left me with a black texture.

##### Three.js version

- [ ] Dev
- [x] r115

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment] 2020-04-28 11:03
Duplicate of #14375.

**Closed by Mugen87** 2020-04-28 11:03 UTC
