### ISSUE TITLE
Morph targets vertices array in Blender exporter wrong

### ISSUE THREAD

**Issue by inear** [mrdoob/three.js#7724] opened 2015-12-03 08:56 UTC
In the Blender Export 4.4 there is an issue with the vertices of morph targets. They are parsed as triplets of arrays: `[[x,y,z],[x,y,z],...]` but should be one singel array `[x,y,z,x,y,z]`. 

I'm not good enough with python to make the change, but I think it's `extend([vertex.co.x, vertex.co.y, vertex.co.z])` that should be `extend((vertex.co.x, vertex.co.y, vertex.co.z))` on line 409 in mesh.py.

I't worked for me when changing in the exported json object directly.

**Comment by inear** [comment] 2015-12-03 09:46
No, it was the `morph.append([co.x, co.y, co.z])` in `def blend_shapes(` that should be `extend` instead. But let me know if I'm using "blend shapes" and "morph targets" in a wrong way. I don't understand the difference since both output morph-targets.

**Comment by DelvarWorld** [comment] 2016-04-23 03:28
Just hit this too, all of the examples use a flat array of verts. @mrdoob this isn't an enhancement, it's currently impossible to export morph targets from blender. Ping @phfatmonkey 

Did this ever work? How did any of the example files like http://threejs.org/examples/models/animated/horse.js with a flat list of verts get built? the blend file for that example isn't in this repo.

**Comment by DelvarWorld** [comment] 2016-04-23 04:32
I made a small script to flatten the vertex array of your output json file. It modifies the file in place. use at your own risk! https://gist.github.com/DelvarWorld/15340499495afea654e45d9ace113d28

**Comment by mrdoob** [comment] 2016-04-23 08:37
> Did this ever work? How did any of the example files like http://threejs.org/examples/models/animated/horse.js with a flat list of verts get built? the blend file for that example isn't in this repo.

That file was not done with Blender. It was done in Maya, exported as a series of OBJs and combined using the converter: https://github.com/mrdoob/three.js/blob/master/utils/converters/obj/convert_obj_three.py

**Comment by donmccurdy** [comment] 2018-03-03 00:24
Closing as duplicate of https://github.com/mrdoob/three.js/issues/8710, which has more recent updates.

**Closed by donmccurdy** 2018-03-03 00:24 UTC
Labels: Blender Exporter, Duplicate, Feature Request
