### ISSUE TITLE
Messed up colors when using OutputPass

### ISSUE THREAD

**Issue by atul-livspace** [mrdoob/three.js#27405] opened 2023-12-20 04:38 UTC
### Description

When using output pass, the colors are not obeying the Color values set to the objects and the scene background.
Here's the rendered image for before and after implementing output pass. 

**Before:**
<img width="400" alt="Screenshot 2023-12-20 at 9 59 41 AM" src="https://github.com/mrdoob/three.js/assets/56149701/79cfbc91-1b9e-401d-b4b4-cc0612806a06">

**After:**
<img width="400" alt="Screenshot 2023-12-20 at 9 59 23 AM" src="https://github.com/mrdoob/three.js/assets/56149701/caed7fc0-0401-473b-981e-1998eae7ba09">

Notice how the color of the background and object changes from what it was originally set.

### Reproduction steps

1. create a scene setup
2. add `EffectComposer`
3. add passes: `RenderPass` and `OutputPass`
4. compare the output by disabling and enabling the `OutputPass`

### Code

```js
composer = new EffectComposer( renderer );
const renderPass = new RenderPass( scene, camera );
composer.addPass( renderPass );

scene.background = new THREE.Color(1,1,1); // pure white 
const outputPass = new OutputPass();

// try commenting below block of code and see the color different.
composer.addPass( outputPass );
```

### Live example

https://jsfiddle.net/zLne9hc5/

### Version

r159

### Device

Desktop

### Browser

Chrome

### OS

MacOS

**Comment by Mugen87** [comment] 2023-12-20 09:17
Duplicate of #27184.

**Closed by Mugen87** 2023-12-20 09:17 UTC

**Comment by atul-livspace** [comment] 2023-12-20 17:31
> Duplicate of #27184/#23019.

Upon investigating further within the context of other issues, I removed transparency from the object; however, the coloring issue persists. I extensively reviewed the list of similarly reported issues but couldn't determine an appropriate solution.

Fortunately, it seems that `THREE.AgXToneMapping` (released a few hours ago) is functioning properly. I'm eagerly anticipating its release 🥇.
