### ISSUE TITLE
ArrowHelper exception

### ISSUE THREAD

**Issue by IMACS-Iain** [mrdoob/three.js#6305] opened 2015-03-29 17:14 UTC
Two divs, each containing ArrowHelper object, throws
    Uncaught TypeError: Cannot read property 'length' of undefined
at line 21532 of three.js.

http://jsfiddle.net/d0ozrv24/

three.js, revision 71. 
Tested in Firefox 36.0.4, and Chrome 41.0.2272.101 m, Windows 7, Intel(R) HD graphics 2000.

**Comment by valette** [comment] 2015-05-20 11:08
Hi,

I also just have been bitten by this bug, due to #189 . This is caused by these objects created once and for all:
https://github.com/mrdoob/three.js/blob/master/src/extras/helpers/ArrowHelper.js#L19-23

unfortunately, one cannot share geometries across renderers. A simple fix is to put these lines in the returned function instead of outside of it (after line 25).

**Comment by dubejf** [comment] 2015-07-24 14:31
Fixed by #6723 on the dev branch. http://jsfiddle.net/d0ozrv24/2/

**Closed by dubejf** 2015-07-24 14:31 UTC
Labels: Bug
