### ISSUE TITLE
SVGLoader: SVGs are sometimes rendered incorrectly.

### ISSUE THREAD

**Issue by eulertour** [mrdoob/three.js#19184] opened 2020-04-22 02:52 UTC
##### Description of the problem

Similarly to #19102. The following SVG renders correctly in Chrome, Firefox, Android, but incorrectly on the latest three.js commit.

[8.txt](https://github.com/mrdoob/three.js/files/4513542/8.txt)

Repro: https://jsfiddle.net/9Lth4x8w/

##### Three.js version

- [x] Dev

##### Browser

- [x] All of them

##### OS

- [x] Linux
- [x] Android

**Comment by Mugen87** [comment] 2020-12-10 10:19
This is actually a duplicate of #16950. The shape is rendered correctly if the contour is defined first and then the holes or vice verse.

Contour first: https://jsfiddle.net/ch1syL4j/1/
Holes first: https://jsfiddle.net/ch1syL4j/2/

However, the original SVG mixes the contour and hole definitions like described here: https://github.com/mrdoob/three.js/issues/16950#issuecomment-510948591

**Closed by Mugen87** 2020-12-10 10:19 UTC
Labels: Loaders
