### ISSUE TITLE
Animations mixing bones that aren't part of their keyframes; can't play two distinct animations at same time

### ISSUE THREAD

**Issue by timetocode** [mrdoob/three.js#21512] opened 2021-03-25 06:48 UTC
**Describe the bug**

Mixer cannot play two animations at the same time without mixing weights, even for bones/vertices that are not part of the animation. In my situation, I cannot play an attack animation or wave animation or any upper-body-only animation while the legs are moving without some amount of mixing occurring.

**To Reproduce**

Steps to reproduce the behavior (using Blender, and gltf export):
1. Using a model in blender, add an animation that moves *only the legs*. Call the animation "Run"
2. Add another animation that moves *only the arms*. Call the animation "Attack"
3. Import the object using gltf
4. Play the "Run" and "Attack" animations at the same time (see code and gif)

What you'll see is that the "Run" animation is distorted during the "Attack" animation and vice-versa, even though the attack animation does not have any bones or vertices in common with the run animation.  They're essentially being mixed with the a transform of zero for duration of the other animation.

I do not know if this the intended behavior, though if it is the intended behavior then the presumable solution is to use multiple mixers which produces some flickering effects at the end of non-looping animations (I can report this separately, if this is in fact the intended solution and just a separate bug).

If this is not a bug, then some improvements to the documentation and examples may be helpful. I volunteer to help with this if needed.

***Code***

```js
// import a gltf with animations then...
const attack = mixer.clipAction(AnimationClip.findByName(animations, 'Attack'))
const run = mixer.clipAction(AnimationClip.findByName(animations, 'Run'))

attack.play() // animation clip using only arms
run.play() // animation clip using only legs
```

***Live example***

I have no included a live example, though if someone tells me that this is *not* intended behavior I can attempt to construct one.

**Expected behavior**

The expected behavior would be that the "attack" animation moves only the arms, and the "run" animation moves only the legs, and that these two animations can be played/started/stopped/reset without affecting each other.

**Screenshots**
This gif shows a run animation being played with the legs swinging in a large stride. After a second I trigger the attack animation to begin playing, and then the legs only swing half as far (this is the mixing). The actual attack animation is also quite distorted. The second gif shows how the animation should look.
![2021-03-24_23-15-40](https://user-images.githubusercontent.com/2829725/112427619-20cc4200-8cf7-11eb-883e-a01d9433e394.gif)

The second gif shows something closer to the expected behavior which is that the arm and leg animations are not being mixed together. This was accomplished with multiple mixer instances (and has another bug where the run flickers when the attack animation finishes, though this not shown here).
![2021-03-24_21-26-02](https://user-images.githubusercontent.com/2829725/112427765-5e30cf80-8cf7-11eb-9985-5a671bbb14c1.gif)

**Platform:**

 - Device: Desktop
 - OS: Windows
 - Browser: Chrome
 - Three.js version: 0.125.2

**Comment by Mugen87** [comment] 2021-03-25 08:44
> If this is not a bug, then some improvements to the documentation and examples may be helpful. I volunteer to help with this if needed.

Feel free to improve documentation in order to clarify that it is not possible to weight individual bones.

**Comment by timetocode** [comment] 2021-03-25 09:13
Hi @Mugen87 thanks for the reply!

To produce that second gif (the expected result) I created two mixers, one for upper body and one for lower body. I then played the two animations on the separate mixers. If both of the animations are set to loop it appears to work fine. 

If one of the animations is set to LoopOnce (my attack animation is), then sometimes there is a flicker of the incorrect frame that appears right as the animation ends. It appears that as the attack animation finishes, sometimes the run animation resets to its first frame -- but not always. Altogether it seems to be *very close* to being a way of weighting two distinct sets of bones and achieving this, but I don't yet know the internals of it so maybe it is more complicated. Do you think that might be close to being a viable solution? If so I can attempt to figure it out and make a PR and an example for the demos.

**Comment by Mugen87** [comment] 2021-03-25 09:19
> Do you think that might be close to being a viable solution?

TBH, I don't think this is the intended usage of the API^^. And I do not vote to add an example for something like that. Seems you are pushing the animation system to its limits.

Since the animation system is already quite complex, I do not vote to add even more features to it unless many user request them.

**Comment by RemusMar** [comment] 2021-03-25 10:53
> The expected behavior would be that the "attack" animation moves only the arms, and the "run" animation moves only the legs

In fact the expected behaviour is to blend both animations (mixed weights).
And that's the current behaviour.

> I do not vote to add even more features to it unless many user request them.

+1

**Comment by Mugen87** [comment] 2021-03-25 12:16
Closing. There is no need to enhance the documentation as long as no other users struggle with this topic. This issue itself should be documentation enough for now.

**Closed by Mugen87** 2021-03-25 12:16 UTC

**Comment by donmccurdy** [comment] 2021-03-25 15:52
The new [additive blending](https://threejs.org/examples/?q=additi#webgl_animation_skinning_additive_blending) mode would allow this, I think.

**Comment by RemusMar** [comment] 2021-03-25 16:23
> The new additive blending mode would allow this, I think.

Probably.
But the best approach (used in many game engines) is to divide the mesh into several parts and to animate each part.
Otherwise you need to waste a bunch of resources preventing the skin modifier (the weights controller) accessing unwanted vertices.

**Comment by Mugen87** [comment] 2021-03-25 16:29
The soldier asset from [webgl_animation_skinning_blending](https://threejs.org/examples/webgl_animation_skinning_blending) is a good example for this. The body and the visor are actually two separate skinned meshes.

**Comment by timetocode** [comment] 2021-03-25 16:32
Additive blending might work for some of these types of animations if there were some changes, esp if there were zero weights in one of the two animations it makes sense that the other could be 'added' to it. I've tried this with my animation above (which does have zero overlap between the two animations) for some reason playing the run animation poses the upper body in the last frame of the attack animation. This occurs even though the attack animation has yet to be played. And then playing the attack animation (on additive) adds it in... effectively twice in total due to the pose.

I'm new to animating, so I went to investigate whether playing 2 animations at the same time (without just mixing) was an actual common thing in game engines. As far as I could tell this is sometimes accomplished by having an animation affect only a set of bones or vertices. What the feature is called varies by engine, but is sometimes called an animation mask or animation layer. In unreal and unity I see examples of grouping vertices or bones into a category like "UpperBody" and then playing an aim-down-sights animation (or any other upper body stuff) set to affect UpperBody. This works at the same time that the walk or run animations takes place. I'm not sure what those engines actually do at that point.. whether they are applying some sort of tree of filters/layers to the weights, or whether they just internally bake some new animations like "aim-down-sights-while-running"

**Comment by RemusMar** [comment] 2021-03-25 16:45
> having an animation affect only a set of bones or vertices.

That's the waste of resources I was talking about.
Just think about a high-poly (>50K) skinned mesh.

**Comment by timetocode** [comment] 2021-03-25 17:11
I'll try cutting them in half at the waist and making separate upper body and lower body animations. Thanks for the suggestion.

As for resources, my mesh is 812 triangles in blender.

I don't know the performance choke point for skinned mesh animation, nor the technique, but wouldn't having an animation affecting just a few bones use less resources than having it affect all of the bones? Maybe that's just not how things work, I don't know much webgl.

**Comment by Mugen87** [comment] 2021-03-25 17:35
@timetocode  Please use the [forum](https://discourse.threejs.org/) for further help requests and discussions about animations.

**Comment by donmccurdy** [comment] 2021-03-25 18:43
>  Just think about a high-poly (>50K) skinned mesh.

One other clarification... I'm pretty sure that additive blending does not impose any additional per-vertex cost. It may impose an additional per-bone cost, although that depends on how the animation is authored and could be minimal.  Additive blending is a newer feature in the library, and to be fair I'm not sure we know the best workflows for authoring and performance in these cases yet. Would be happy to discuss further in the forums, as Mugen87 suggests.
