### ISSUE TITLE
computeBoundingBox/computeBoundingSphere failed on "position" attribute with itemSize 2

### ISSUE THREAD

**Issue by ooatom** [mrdoob/three.js#25748] opened 2023-03-31 17:03 UTC
### Description

Currently, `computeBoundingSphere` and `computeBoundingBox` assumes the itemSize of position attribute is 3. With 2  the codes below would return z with NaN, then throw the error.

(_I am creating many points in a vertical plane with itemSize 2 to reduce the memory usage._)

    // Box3.js
    this.expandByPoint( _vector.fromBufferAttribute( attribute, i ) );

    // Vector3.js
	fromBufferAttribute( attribute, index ) {

		this.x = attribute.getX( index );
		this.y = attribute.getY( index );
		this.z = attribute.getZ( index );

		return this;
	}

Maybe we could simply return 0 if not exist?

    // BufferAttribute.js

	getZ( index ) {

		let z = this.array[ index * this.itemSize + 2 ];

		if ( this.normalized ) z = denormalize( z, this.array );

		return z || 0;

	}

### Reproduction steps

> the fastest approach 

1. find examples/webgl_custom_attributes_points.html
2. search `const positions = new Float32Array( amount * 3 );`, replace 3 to 2
3. search `geometry.setAttribute( 'position', new THREE.BufferAttribute( positions, 3 ) );`, replace 3 to 2

### Code

```js
// see above
```

### Live example

none

### Version

0.150.0

**Comment by Mugen87** [comment] 2023-03-31 17:06
Duplicate of #6288.

**Closed by Mugen87** 2023-03-31 17:06 UTC
