### ISSUE TITLE
TransformControls: able to translate object on invisible/hidden axes

### ISSUE THREAD

**Issue by ausrussell** [mrdoob/three.js#19170] opened 2020-04-19 18:26 UTC
Hi, love this code but think I see an issue which can be seen on the live example (https://threejs.org/examples/misc_controls_transform.html)  where the user is able to toggle off an axis (X,Y or Z) but is still able to translate the object along that axis even while the handles are not visible... you just have to carefully click and drag where you think the invisible handles are.
I believe the issue may have arisen with how the three.js raycaster catches the handles meshes that are not visible. 
I seem to have fixed it for my case by throwing in a conditional checking for visibility of the children in the this.pointerHover handler

```js
var intersect = ray.intersectObjects(_gizmo.picker[this.mode].children, true)[0] || false;
if (intersect) {
			if (!intersect.object.visible) {//my added condition
				const intersectedChildren = ray.intersectObjects(_gizmo.picker[this.mode].children, true);
				this.axis = null;
				for (let i = 0; i < intersectedChildren.length; i++) {
					if (intersectedChildren[i].object.visible) {
						this.axis = intersect.object.name;
						continue;
					}
				}
			} else {
				this.axis = intersect.object.name;
			}
```

Just thought I'd let you know.

**Comment by arodic** [comment] 2020-04-19 21:16
This is a duplicate of re-opened issue #11340
PR with a fix has been approved: #19152
thanks for reporting @ausrussell!

**Closed** 2020-04-20 06:50 UTC
Labels: Duplicate
