### ISSUE TITLE
editor error while importing facecap.glb (webgl_morphtargets_face example)

### ISSUE THREAD

**Issue by fgerges** [mrdoob/three.js#25230] opened 2023-01-04 12:28 UTC
### Description

when importing the facecap.glb file (used in webgl_morphtargets_face example) in the editor, the import is not done and you can see the following error on the browser console:

GLTFLoader.js:1215 Uncaught (in promise) Error: THREE.GLTFLoader: setKTX2Loader must be called before loading KTX2 textures
    at GLTFTextureBasisUExtension.loadTexture (GLTFLoader.js:1215:11)
    at GLTFLoader.js:2585:37
    at GLTFParser._invokeOne (GLTFLoader.js:2494:19)
    at GLTFParser.getDependency (GLTFLoader.js:2583:24)
    at GLTFParser.assignTexture (GLTFLoader.js:3020:15)
    at GLTFParser.loadMaterial (GLTFLoader.js:3216:26)
    at GLTFLoader.js:2577:38
    at GLTFParser._invokeOne (GLTFLoader.js:2494:19)
    at GLTFParser.getDependency (GLTFLoader.js:2575:24)
    at GLTFParser.loadMesh (GLTFLoader.js:3438:12)
loadTexture @ GLTFLoader.js:1215
(anonyme) @ GLTFLoader.js:2585
_invokeOne @ GLTFLoader.js:2494
[...]

### Reproduction steps

1. download facecap.glb from three.js/examples/models/gltf/
2. go to https://threejs.org/editor/
3. click import
4. select facecap.glb downloaded before
5. open the browser debug console

### Code

na

### Live example

na

### Version

r148

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by Mugen87** [comment] 2023-01-04 12:32
Duplicate of #22035.

**Closed by Mugen87** 2023-01-04 12:32 UTC

**Comment by RockyKev** [comment] 2023-02-05 20:49
It is the same problem as #22035, but the core issue IMO is that developers re-creating this [example in the docs](https://threejs.org/examples/#webgl_morphtargets_face)  are now stuck with not knowing how to view  facecap.glb. 

Maybe the solution would be to improve that example with a model developers CAN use in the https://threejs.org/editor/?

**Comment by Mugen87** [comment] 2023-02-05 22:41
@RockyKev Actually it's more important to keep the morph target asset compressed so the example loads as fast as possible. Even if that means it can't be view in the editor right now.
