### ISSUE TITLE
OrthographicCamera doesn't render correctly under Intel graphic cards

### ISSUE THREAD

**Issue by mjiangcn** [mrdoob/three.js#17800] opened 2019-10-23 07:34 UTC
##### Description of the problem

We have a scene for showing lot of points. We use a PerspectiveCamera and OrthographicCamera to watch that scene. PerspectiveCamera looks good, but many integrated graphics cards dont render view from OrthographicCamera correctly.

Describe the bug or feature request in detail.
Screenshot with problem:
![image](https://user-images.githubusercontent.com/48277261/67353709-cf5dd780-f585-11e9-8ad3-a17c86cd5db6.png)

Screenshot without problem:
![image](https://user-images.githubusercontent.com/48277261/67353964-78a4cd80-f586-11e9-9209-516653e53a31.png)

##### Three.js version

- [ ] Dev
- [x] r109
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)
Quick way to reproduce is switching Macbook to integrated card via running ```sudo pmset -a GPUSwitch 0``` and restart the browser(if external display is connected, you also need to disconnect as well)

**Comment by Mugen87** [comment] 2019-10-23 09:33
Can you please also make a test with the current `dev` builds of `three.js`? You can find them here: https://github.com/mrdoob/three.js/tree/dev/build

> sudo pmset -a GPUSwitch 0

Does this trigger a permanent change? How can you reset this config?

**Comment by mjiangcn** [comment] 2019-10-23 10:14
Yes, @Mugen87  so to switch back, you can  execute ```sudo pmset -a GPUSwitch 2```(FYI: https://www.3u.com/tutorial/articles/1866/how-to-switch-graphics-card-on-macbook-with-one-step)

**Comment by Mugen87** [comment] 2019-10-23 12:45
Does it also happen with this official example:

https://threejs.org/examples/webgl_points_sprites

**Comment by Mugen87** [comment] 2019-10-23 12:53
Can you reproduce the problem with this example: https://jsfiddle.net/pbjzmn4k/

**Comment by sciecode** [comment] 2019-10-28 14:23
I've tried many instances of `Points` and I wasn't able to reproduce this under any circumstance.

@mjiangcn do you think you could provide an example like Mugen requested?
If possible, also share the screenshots with integrated and independent graphics card for comparison.

**Comment by Mugen87** [comment] 2019-11-01 09:59
Closing for now. This seems to be an Intel driver issue. Consider to report the issue here instead:

https://software.intel.com/en-us/forums/graphics-driver-bug-reporting

@mjiangcn We often have the problem that devs report driver bugs here at the `three.js` repo. You should actually only do this if the bug is `three.js` exclusive. For example: If you can render points with plain WebGL or an other WebGL engine without problems but `three.js` gives you visual glitches, it's okay to report the issue here. If you see the glitch with all engines, it's probably a device, driver or browser issue. 

It should be clear that we can't fix such issues and it is more target-aimed to report this directly to browser or GPU vendors.

**Closed by Mugen87** 2019-11-01 09:59 UTC
Labels: Device Issue

**Comment by bb7bb** [comment] 2019-11-02 12:02
@mjiangcn you can try to set material `new PointsMaterial({ size: 1 })`.maybe it can help you
