### ISSUE TITLE
renderOrder problems, "glDrawArrays: attempt to access out of range vertices"

### ISSUE THREAD

**Issue by drcmda** [mrdoob/three.js#6603] opened 2015-05-26 08:06 UTC
I seem to have trouble getting renderOrder to work. It crashes WebGL. I simply give give meshes a higher value and lines a lower, like this:

mesh.renderOrder = 2;
line.renderOrder = 1;

And that's enough to choke WebGL. I set the attribute directly on the actual meshes, not the parent objects. I use BufferGeometry for both.

As for the application - meshes, lines, etc. come through the wire from an attached CAD system. I have no control over and shouldn't change the array order or the incoming objects. THREE always allowed me though to steer the render order still with renderDepth. How can i get the same thing done with renderOrder, why is it crashing?

renderDepth in r69, lines show through the meshes
![r69](https://cloud.githubusercontent.com/assets/2223602/7807601/372be23e-038d-11e5-8b4c-3b69d37a405c.jpg)

r71, renderDepth obsolete, lines shines through in any random order in which they came through
![r71](https://cloud.githubusercontent.com/assets/2223602/7807612/436345b0-038d-11e5-8d57-94c7f0f972c6.jpg)

r71, renderOrder crashes the application
![r71ro](https://cloud.githubusercontent.com/assets/2223602/7807775/99780278-038e-11e5-929d-dc99de78b086.jpg)

**Comment by WestLangley** [comment] 2015-05-26 14:31
Can you provide a test case so we can reproduce your results? Please see "How to report a bug" in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md).

**Comment by mathdoodle** [comment] 2015-06-08 01:57
I believe I know the cause of this and a possible fix, but I'm going to defer to "authority" since I don't yet know the root cause and I'm still finding my way around three.js. Here's what I found: When I upgraded an application from revision ~59 to 71 I got what I think is the same error. I discovered that the application was using THREE.Line and found that setLineBuffers() was being called. Consequently, __webglUVBuffers is undefined and WebGL complains when trying to bindBuffer. The 'fix' for me was simple, test for both geometryGroup.__webglUVBuffer && object.geometry.faceVertexUvs[ 0 ] in the renderBuffer method. I'm not experienced enough with three.js to know why the faceVertexUVs[ 0 ] test is insufficient. I home this means something to those "In the know". If you would like clarification, please don't hesitate to contact me.
david.geo.holmes@gmail.com

**Comment by drcmda** [comment] 2015-06-12 10:06
David, i also use ShaderMaterial. But my Project is huge and so i couldn't easily reduce it, not knowing where to look. I then tried to debug it myself but it goes too deeply into THREE and webgl internals that i would have to understand first. All i did to cause it was update to r71 and set renderOrder=2 on a BufferGeom mesh (and 1 on a BufferGeom line), these two things were enough. And so i hoped anyone here would perhaps already know the issue.


I have since reworked my Shaders to adapt them to r71 entirely (fog implementation changed among some other things) and the error is gone. I also had some custom material cloning that i adapted. I can't really tell what in the end made it work. :-(

**Comment by mathdoodle** [comment] 2015-06-12 16:24
It could still be the same bug. The fact that you modified your shaders and caused it to go away is significant to me. Three.js decides what buffers to to use during rendering based upon the 'standard' shader attributes that it successfully manages to cache. But some of these attributes may be unused by the shader program and the ShaderMaterial class prepends a bunch of attributes to your shader code which may not all be used. The trouble then happens when such attributes exist but corresponding buffers are not created and bound. The difference between what buffers are prepared by setLineBuffers() and setMeshBuffers() gets towards the root cause. The problem is that ShaderMaterial is not configured according to whether it is being consumed by a Mesh or a Line. One work-around might be to take control by using RawShaderMaterial, but you still have to conform to Three.js protocols if you are using the Mesh and Line objects.

I'm glad that the issue no longer affects you, but I believe the library still has a problem.

**Comment by jonnenauha** [comment] 2015-06-14 11:18
@mrdoob It seems `Object3D.renderDepth` was renamed to `Object3D.renderOrder` at some version. Reg. documentation in #6417 could we please write this down somewhere. I had no idea this had happened and our code uses renderDepth so this would have come as a silent bug, luckily I have not upgraded yet (due to poor docs/migration guides)

**Comment by Mugen87** [comment] 2018-03-07 11:32
Closing for now. We can reopen if the bug still exists with the latest version of `three.js`.

**Closed by Mugen87** 2018-03-07 11:32 UTC
Labels: Bug
