### ISSUE TITLE
Line Width in LineBasicMaterial

### ISSUE THREAD

**Issue by joselevelsup** [mrdoob/three.js#14627] opened 2018-08-03 03:14 UTC
##### Description of the problem
So I have tried to adjust the `linewidth` in the `LineBasicMaterial` but it only renders out as 1 pixel instead of 5 (which is where I am trying to adjust). I have tried to preview this in Chrome, Firefox, and Safari but to no success. Any idea on why this isn't working. I read the docs and followed the way its used. 

##### Three.js version

- [ ] Dev
- [x] r95
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [x] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment] 2018-08-03 08:11
Duplicate of #10357

Please have a look at the following example which renders lines based on a triangles (so called Ribbon or MeshLine).

https://threejs.org/examples/#webgl_lines_fat

**Closed by Mugen87** 2018-08-03 08:11 UTC

**Comment by joselevelsup** [comment] 2018-08-03 12:38
Wait why was this closed? I tried the example and even went into the example's source code to try and replicate it but got no where. The linewidth still doesn't change. Also I get an error stating `LineMaterial` or `LineGeometry` is not a constructor. So this is still an issue.

**Comment by Mugen87** [comment] 2018-08-03 13:10
`LineGeometry` is part of the examples not of the core.

**Comment by Mugen87** [comment] 2018-08-03 13:12
BTW: You can change the line width in the example over the gui.

![image](https://user-images.githubusercontent.com/12612165/43644588-9d474340-972f-11e8-8903-2ece50461427.png)

**Comment by joselevelsup** [comment] 2018-08-03 13:23
The only difference is that I am using Aframe/Threejs with React. Do you have a lead on how to import those files to use it?

**Comment by joselevelsup** [comment] 2018-08-03 13:24
I've seen the example and was trying so hard to replicate it in my project just to get thick lines.

**Comment by mrdoob** [comment] 2018-08-03 13:50
@joselevelsup keep trying! 💪

**Comment by Mugen87** [comment] 2018-08-03 14:05
@joselevelsup The forum is the right place for help requests:

https://discourse.threejs.org/

**Comment by lshe7842** [comment] 2018-12-09 04:41
Hey @joselevelsup , in case this is still a problem for you. What I did was to copy n paste the LineGeometry file out and then in the new file add `var THREE = window.THREE || require('three');` on the top and then change all THREE.* namespaces. Then in your reactjs codes you can just do normal require from the new file.
