### ISSUE TITLE
ThreeJS editor does not load or open on iPhone 13, 13 Mini, 13 Pro

### ISSUE THREAD

**Issue by trofimenk0** [mrdoob/three.js#27545] opened 2024-01-11 11:53 UTC
### Description

ThreeJS editor does not load or open on iPhone 13, 13 Mini, 13 Pro

### Reproduction steps

1. Try to open https://threejs.org/editor/ on the IPhone 13, 13 Mini, 13 Pro

### Code

```js
// code goes here
```

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/g3atw6k5/)
* [jsfiddle-dev](https://jsfiddle.net/hjqw94c5/)

### Screenshots

![image](https://github.com/mrdoob/three.js/assets/42813266/695aecc9-3615-4c10-8c5a-3841171cd9f4)

### Version

r160

### Device

Mobile

### Browser

Chrome, Firefox, Safari, Edge

### OS

iOS

**Comment by Mugen87** [comment] 2024-01-11 12:06
What version of iOS are you using?

**Comment by trofimenk0** [comment] 2024-01-11 13:17
IOS v16
It can be seen on the left sidebar in the screenshot

**Comment by trofimenk0** [comment] 2024-01-11 13:17
> What version of iOS are you using?

IOS v16
It can be seen on the left sidebar in the screenshot

**Comment by trofimenk0** [comment] 2024-01-11 13:23
> What version of iOS are you using?

To be precise, IOS version 16.3

**Comment by Mugen87** [comment] 2024-01-11 14:36
This is a duplicate of #27387.

**Closed by Mugen87** 2024-01-11 14:36 UTC
