### ISSUE TITLE
Can't do middle click in the docs in order to open link in new tab

### ISSUE THREAD

**Issue by felixniemeyer** [mrdoob/three.js#25125] opened 2022-12-12 15:56 UTC
**Describe the bug**
Middle clicking links in the threejs docs has no effect. 
Right clicking links does not bring up the usual browser link menu. 

**Platform**
Mozilla Firefox 107.0.1 on 6.0.11-1-MANJARO 

**To Reproduce**
1. Go to https://threejs.org/docs/#api/en/materials/ShaderMaterial
2. Try to open the link to `WebGLProgram` and `RawShaderMaterial` for further reading 
3. You will most likely want to middle click these links to open them in background tabs
4. But nothing happens if you middle click these links

**Expected behavior**
I expect links to be opened in a new tab when clicking them with the middle mouse button just like on 99% of the web.

**Comment by Mugen87** [comment] 2022-12-12 16:10
Duplicate of #13900.

**Closed by Mugen87** 2022-12-12 16:10 UTC
