### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'value')

### ISSUE THREAD

**Issue by monkyver** [mrdoob/three.js#26402] opened 2023-07-10 08:54 UTC
### Description

Using some models, throws an error

three.module.js:26556 Uncaught TypeError: Cannot read properties of undefined (reading 'value')
    at refreshTransformUniform (three.module.js:26556:1)
    at refreshUniformsCommon (three.module.js:26744:1)
    at Object.refreshMaterialUniforms (three.module.js:26599:1)
    at setProgram (three.module.js:29271:1)
    at WebGLRenderer.renderBufferDirect (three.module.js:28156:1)
    at renderObject (three.module.js:28823:1)
    at renderObjects (three.module.js:28792:1)
    at renderScene (three.module.js:28680:1)
    at WebGLRenderer.render (three.module.js:28498:1)
    at render$1 (index-22ee0173.esm.js:1519:1)

### Reproduction steps

1. use this model in a scene in glb format (https://sketchfab.com/3d-models/dirty-plank-504babddf86c4c2c85bc2ee3c7f53002)

works with r150 and below instead

### Version

r151

### Device

Desktop

### Browser

Chrome, Firefox, Safari, Edge

### OS

Windows, MacOS

**Comment by Mugen87** [comment] 2023-07-10 09:04
I've downloaded the asset as a glb and imported it into the [three.js editor](https://threejs.org/editor/). The asset relies on the `KHR_materials_pbrSpecularGlossiness` glTF extension which is not supported in `three.js` since `r147` anymore. Hence, it is not rendered as expected.

However, I was not able to reproduce the runtime error. This could be related to your app specific code.

Try to convert the glTF asset to metallic/roughness with the following guide:

https://www.donmccurdy.com/2022/11/28/converting-gltf-pbr-materials-from-specgloss-to-metalrough/

**Comment by Mugen87** [comment] 2023-07-12 08:39
Closing. Please use the [forum](https://discourse.threejs.org/) if you need more help investigating your issue. If it turns out to be a bug in `three.js`, we can reopen this thread.

**Closed by Mugen87** 2023-07-12 08:39 UTC
