### ISSUE TITLE
Multisampled EffectComposer with more than two Passes produce artefacts

### ISSUE THREAD

**Issue by RealTecWare** [mrdoob/three.js#23675] opened 2022-03-08 09:08 UTC
**Describe the bug**

There is a problem with the EffectComposer in combination with a multisampled rendertargets.
This combination produce artefacts when two or more passes like RenderPass or TexturePass are enabled.

**To Reproduce**

1. Use a Revision after following commit: b2ea47ac7a575032af050b43afb8f57478efc8b6 
2. Open examples/webgl_postprocessing_backgrounds.html
3. Modify the code

***Code***

```js
//Modify following Line:
composer = new EffectComposer( renderer );

//Change it to:
const renderTarget = new THREE.WebGLMultisampleRenderTarget( width, height );
//Or for newer threejs version
//const renderTarget = new THREE.WebGLRenderTarget( width, height, { samples: 1 } );
composer = new EffectComposer( renderer, renderTarget );
```

***Live example***

* [jsfiddle-v135-release](https://jsfiddle.net/th3s0urc3/dn4chvrf/)
* [jsfiddle-dev](https://jsfiddle.net/th3s0urc3/nrbjqp96/)

**Expected behavior**

In v134 everything works as expected:
* [jsfiddle-v134-release](https://jsfiddle.net/th3s0urc3/t5mjb367/)

**Screenshots**

v135 with WebGLMultisampleRenderTarget - Chrome:
![Screenshot 2022-03-08 091558](https://user-images.githubusercontent.com/11577704/157195079-6bf8d4da-f53e-4281-b182-731517034416.png)

dev with WebGLRenderTarget and samples set to 1 - Chrome:
![Screenshot 2022-03-08 091730](https://user-images.githubusercontent.com/11577704/157195545-093269b0-6bee-4410-8f44-8ad9a9d4fc25.png)

v135 with WebGLMultisampleRenderTarget - iOS Safari:
![photo_2022-03-08_09-31-33](https://user-images.githubusercontent.com/11577704/157202642-1283142e-7fbc-40f3-829f-993484698326.jpg)

**Platform:**

 - Device: [Desktop, Mobile]
 - OS: [Windows, Android, iOS]
 - Browser: [Chrome, Safari, Edge]
 - Three.js version: [dev, r135, b2ea47ac7a575032af050b43afb8f57478efc8b6 ]

**Comment by Mugen87** [comment] 2022-03-08 09:11
Duplicate of #22967.

**Closed by Mugen87** 2022-03-08 09:11 UTC
