### ISSUE TITLE
Is it possible to add a setColorAt method for BatchedMesh?

### ISSUE THREAD

**Issue by CahierX** [mrdoob/three.js#27449] opened 2023-12-27 03:27 UTC
### Description

Now the setColorAt method on InstanceMesh is very useful, can it also be added to BatchedMesh?

### Solution

Add setColorAt  to set instanceColor look like InstancedMesh

### Alternatives

null

**Comment by Mugen87** [comment] 2023-12-27 09:39
Instancing and batching work different meaning you don't have instanced attributes when rendering a batched mesh. Having instanced attributes made it easy to implement instanced colors for `InstancedMesh`.

It's important to highlight that `setColorAt()` was added so different colors per instance was possible. When using `BatchedMesh`, you can already have different colored geometries via vertex colors.

Meaning if you use `addGeometry()` with geometries that hold vertex colors, you can author different colors per geometry by simply altering vertex color values.

**Comment by mrdoob** [comment] 2023-12-28 04:44
@gkjohnson Have your ever needed this?

**Comment by gkjohnson** [comment] 2023-12-28 07:40
As Mugen mentioned - users can already do this by creating geometry with a color channel which is effectively how InstancedMesh worked. In order to do this in a more memory-efficient way you'd need to pack the per-geometry colors into a texture and sample them in the shader. I've provided a demo of this idea in https://github.com/mrdoob/three.js/issues/27170#issuecomment-1823855592.

In short, though, I think this can be closed as a duplicate of #27203 which is really just about being able to have more granular, high performance control over the material of individual geometries.

**Closed** 2023-12-28 08:55 UTC
Labels: Duplicate
