### ISSUE TITLE
VideoTexture updating at 60-90fps

### ISSUE THREAD

**Issue by mrdoob** [mrdoob/three.js#13379] opened 2018-02-20 23:14 UTC
As reported in https://github.com/mrdoob/three.js/pull/12763#issuecomment-364320372, we're currently updating the video texture at 60 (or 90 in VR) fps.

Ideally we'll only update the texture on the GPU in sync with the video framerate (usually 25-30). Unfortunately the web platform does not provide any API for figuring out the framerate of a video so something like `videoTexture.frameRate = 25` is needed.

It seemed easy enough so I tried to implement this (#13304) but I hit some browser bugs and I had to revert (#13305).

It'll be good to investigate this a bit more and report bugs to browsers if needed.

**Comment by RemusMar** [comment] 2018-02-21 13:17
Ricardo, you can try my 3 years old approach:
```javascript
setInterval( function () { updateVideoTex(); }, 40 );
// ...
function  updateVideoTex() {
	if ( video.readyState === video.HAVE_ENOUGH_DATA ) {
		videoTexture.needsUpdate = true;
	}
}
```
It works just fine for me.
cheers

**Comment by Mugen87** [comment] 2018-02-21 13:43
@RemusMar see https://github.com/mrdoob/three.js/pull/12763#issuecomment-365092556

**Comment by RemusMar** [comment] 2018-02-21 13:48
> RemusMar see #12763 (comment)

Ohhh ... and he still gets 60-90FPS ???

**Comment by Mugen87** [comment] 2018-02-21 13:57
I guess it works but it's more like a workaround.

**Comment by RemusMar** [comment] 2018-02-21 14:01
> I guess it works but it's more like a workaround.

I think in this case an independent clock is the best solution.
It's also very easy to set the desired update interval.

**Comment by mrdoob** [comment] 2018-02-21 16:05
@RemusMar Also see https://github.com/mrdoob/three.js/pull/13305#issuecomment-367153579

**Comment by RemusMar** [comment] 2018-02-21 16:40
> RemusMar Also see #13305 (comment) 

"1, 2, 4, 3, 5" indicates a terrible mess with the movie decoder and frames buffer (on the browser side).
Honestly, Google Chrome was a collection of bugs from the very beginning (I did never recommend it).
In any case, in my opinion **setInterval** seems to be the most "friendly" solution.

**Comment by mrdoob** [comment] 2018-02-21 16:44
Yeah, I also think `setInterval()` is the right approach. I just created this issue to remind myself that I need to investigate this and find a robust solution.

**Comment by makc** [comment] 2018-02-21 20:33
why not just
```javascript
Object.defineProperty(videoTexture, "needsUpdate", {
    value: true,
    writable: false
});
```
then you won't need setInterval =)

**Comment by makc** [comment] 2018-02-21 20:35
ah wait, it's the opposite of what you want. you want to skip the frames

**Comment by mrdoob** [comment] 2018-03-02 03:32
Alright... Can you guys try the example in your browsers and see if you see it jumping back frames from time to time?

https://rawgit.com/mrdoob/three.js/dev/examples/webvr_video.html

**Comment by RemusMar** [comment] 2018-03-02 06:31
> Can you guys try the example in your browsers and see if you see it jumping back frames from time to time?
> https://rawgit.com/mrdoob/three.js/dev/examples/webvr_video.html 

Everything seems to be ok.
:+1: 
But on some devices 2 x 1024 x 1024 x 24 / second might be problematic.
I would limit the source video to 512x512 pixels

**Comment by Mardonis** [comment] 2018-03-02 13:16
I saw some flickering of jumping back some.
Google Chrome Version 64.0.3282.186 (Official Build) (32-bit)

**Comment by Mugen87** [comment] 2018-03-02 14:35
Same here with Chrome (64.0.3282.186) in macOS.

![2018-03-02 15 33 49](https://user-images.githubusercontent.com/12612165/36903830-226c8bea-1e2f-11e8-82bd-5136040f92ed.gif)

**Comment by RemusMar** [comment] 2018-03-02 15:37
@Mugen87 @Mardonis 
Do you have issue with Firefox?

**Comment by Mugen87** [comment] 2018-03-02 15:42
No, the video looks fine with FF (58.0.2) 😊

**Comment by dustinkerstein** [comment] 2018-03-02 17:28
This example doesn't actually play in OSX Safari (neither does the regular video panorama example). It throws an "Unhandled Promise Rejection: [Object DOMError] - This has nothing to do with this latest change, but it would be good to test in Safari as I think this new code is going to cause rapid black frame flickering (it doesn't leave the previous frame like on Firefox). 

Also, I don't actually think this setTimeout solution is going to work as intended. Syncing with the video frames when we don't have a proper frame decode callback means at best we can only hope to be in sync, but it's likely going to drift and either drop / duplicate frames. I've been dealing with this problem for a while with PanoMoments.com - I think the only safe solution is to do a texture update on every single render loop even though it has a high performance cost, especially at 90hz. But I'd love to be proven wrong :)

**Comment by Mugen87** [comment] 2018-03-02 18:00
> This example doesn't actually play in OSX Safari 

I guess it's because Safari does not support WebM.

**Comment by RemusMar** [comment] 2018-03-02 18:01
> Also, I don't actually think this setTimeout solution is going to work as intended.
> Syncing with the video frames when we don't have a proper frame decode callback means at best we can only hope to be in sync, but it's likely going to drift and either drop / duplicate frames.

It's working just fine (at least on Firefox ESR, Firefox Quantum and older Chrome versions).
It doesn't have any artefact and it's always in sync (because setInterval is never accurate, the browser calls the trigger when everything is ready, including the last decoded frames).
I've tested this method with a 90 minutes movie and I didn't notice any glitch.
You can even include extra delays:
http://necromanthus.com/Test/html5/testA_disco.html 
```javascript
			if (viddel == 0 ) {
				if ( video.readyState === video.HAVE_ENOUGH_DATA ) {
					TVimgCon.drawImage( video, 8, 8 );
					if ( TVtex ) {
						TVtex.needsUpdate = true;
					}
				}
				viddel = 1;
			} else {
				viddel -= 1;
			}
```
I didn't notice any issue on Android mobile phones (Firefox and Chrome both).

**Comment by dustinkerstein** [comment] 2018-03-02 18:06
@RemusMar Interesting. What video framerates did you try? I'm curious how it handles 25fps and other rates that don't divide into 60fps nicely.

**Comment by RemusMar** [comment] 2018-03-02 18:12
> What video framerates did you try? I'm curious how it handles 25fps and other rates that don't divide into 60fps nicely.

I've encoded all the videos by myself: 
256x144 pixels
24 or 25 FPS
VP8

setInterval is set to 40ms (around 25 FPS).
Not a single glitch with both 24 and 25 FPS movies.

**Comment by mrdoob** [comment] 2018-03-02 21:54
@Mardonis Is that with MacOS? Windows? Linux? ...

**Comment by Mardonis** [comment] 2018-03-02 22:06
Windows 7

**Comment by dustinkerstein** [comment] 2018-03-02 22:43
Try this link on Safari (based on the above demo just with an mp4 at 29.97fps) - https://files.panomoments.com/js/videoTexture.html - It will flash black every other frame (**_don't view if you're epileptic_**). On Windows Chrome I think I am seeing frame dropping/duplicating frames which causes a very noticeable judder. 

Here's this same example but with texture.needsUpdate = true on every render loop - https://files.panomoments.com/js/videoTextureRenderUpdates.html - Notice there is no judder.

**Comment by mrdoob** [comment] 2018-03-02 22:55
If the mp4 is at 29.97fps, you should change the `setInterval()` acoordingly:

```js
setInterval( function () {

    if ( video.readyState >= video.HAVE_CURRENT_DATA ) {

        texture.needsUpdate = true;

    }

}, 1000 / 29.97 );
```

**Comment by dustinkerstein** [comment] 2018-03-02 22:59
Sorry about that. Fixed in the link. It still drops frames though :)

**Comment by mrdoob** [comment] 2018-03-02 23:01
@jonobr1 have you seen this flickering in Safari before?

**Comment by jonobr1** [comment] 2018-03-02 23:44
Yes @mrdoob this is a new issue with Safari 11.01 I think is the version? 11.1 ( in beta ) doesn't have this issue.

**Comment by jonobr1** [comment] 2018-03-02 23:46
I think this is the bug you're referring to: https://bugs.webkit.org/show_bug.cgi?id=171054

**Comment by RemusMar** [comment] 2018-03-03 08:02
> Try this link on Safari (based on the above demo just with an mp4 at 29.97fps) - 
> https://files.panomoments.com/js/videoTexture.html 

That movie (1920 x 960) runs terrible (very choppy) even on Firefox Windows.
As I said before, 2 x 1024 x 1024 x 24 / second might be problematic on many devices.
If I resample that 1920x960 movie to 1024x512 I get smooth movement (at least on Firefox Windows).

**Comment by dustinkerstein** [comment] 2018-03-03 08:24
I imagine that has more to do with your computer's capabilities. 4k 30fps is very doable in WebGL based players but it does depend on the hardware.

**Comment by RemusMar** [comment] 2018-03-03 09:15
> 4k 30fps is very doable in WebGL based players but it does depend on the hardware.

WebGL at UHD is something, videotexture at UHD is something completelly different.
Anyway, 4K at 30fps runs choppy even on top hardware and it doesn't run at all on iOS and mobile devices.

**Comment by mrdoob** [comment] 2018-03-03 17:28
In VR, 1024x512 is not enough.

**Comment by mrdoob** [comment] 2018-03-08 04:40
Reported bug to Chrome:
https://bugs.chromium.org/p/chromium/issues/detail?id=819914

**Comment by RemusMar** [comment] 2018-03-08 07:00
> In VR, a 1024x512 360° video is not enough

I know that, but it shows where the real problem is.
Depending on hardware, movie resolution and encoding type, it runs choppy in any browser and any OS.
As I said before, WebGL at UHD is something, videotexture at UHD is something completelly different.

**Comment by mrdoob** [comment] 2018-03-08 07:11
Yeah, I know, but we're going to make it work.

**Comment by makc** [comment] 2018-03-08 11:31
why not just have a timestamp on VideoTexture object, e.g. texture.lastUpdated = Date.now(), then you won't need these timeouts

**Comment by makc** [comment] 2018-03-08 11:37
and in the renderer you would just do something like
```
if(texture.needsUpdate || (Date.now() - texture.lastUpdated > 1000 / texture.frameRate)) {
 ...
 texture.lastUpdated = Deate.now();
}
```

**Comment by makc** [comment] 2018-03-08 11:45
funny thing, https://github.com/mrdoob/three.js/pull/13304/files mentioned above was doing basically the same thing, except
> if ( prevTime + ( 1 / this.frameRate ) < time ) {

why 1? the value returned by performance.now is not in seconds

**Comment by RemusMar** [comment] 2018-03-08 12:23
> if (texture.needsUpdate || (Date.now() - texture.lastUpdated > 1000 / texture.frameRate)) {

This method is not good because it's not accurate at all.
You check for Date.now() every 16.66ms and you can use integers only to add delay.
1 = 16.66ms = 60Hz
2 = 33.33ms = 30Hz
3 = 50ms = 20Hz
etc
You cannoe evan get a decent 40ms (20Hz) interval.
That's why the only solution here is **setInterval**
cheers

**Comment by mrdoob** [comment] 2018-03-08 15:21
Guys... The code implemented is correct already, we just bumped into a Chrome bug and they are looking into it.

**Comment by RemusMar** [comment] 2018-03-08 15:27
> Guys... The code implemented is correct already,

https://github.com/mrdoob/three.js/blob/dev/src/textures/VideoTexture.js 
The current update interval is 60 times per second (without setInterval)

**Comment by RemusMar** [comment] 2018-03-08 15:47
In any case, to update a 2048x1024 videoTexture 60 times per second is a waste of resources for nothing.

**Comment by mrdoob** [comment] 2018-03-08 16:05
@makc 

> why 1? the value returned by performance.now is not in seconds

https://github.com/mrdoob/three.js/commit/5e04f7639a852e9a63d460a82cdd4dfda2459ad1#diff-f9692e8d9d94a2c66a74e82488183c60

@RemusMar 

This is the code we're trying to use:

https://github.com/mrdoob/three.js/blob/dev/examples/webvr_video.html#L69-L83

Once it works in all browsers we'll implement in `VideoTexture` directly.

**Comment by RemusMar** [comment] 2018-03-08 16:13
> This is the code we're trying to use:
> Once it works in all browsers we'll implement in VideoTexture directly.

I use it for 3 years, it worked just fine in older Chrome versions, so it will work in all the (non buggy) browsers.
A faster and elegant solution you can find above (see that piece of script with **viddel -= 1;**)
You don't even need setInterval for that.
Just multiply with 2 the default 16.66ms interval.
You will update the textures at 30Hz.
It will cover all the existing movies (30, 25, 24 FPS), it's a very simple solution and always in sync.
It will come with a significant performances boost on any device.

**Comment by netpro2k** [comment] 2018-03-10 01:14
>  The current update interval is 60 times per second (without setInterval)
> In any case, to update a 2048x1024 videoTexture 60 times per second is a waste of resources for nothing.
The current code runs at whatever refresh rate `requestAnimationFrame` is running at. On many VR devices this is 90 FPS, this is where I started seeing noticeable issues.

> A faster and elegant solution you can find above (see that piece of script with viddel -= 1;)
> You don't even need setInterval for that.
Since the frequency this block is invoked at depends on context, you can't just drop every other frame. Ideally we want to actually get the FPS from the source and render only when a new video frame is actually available, but barring that manually setting the FPS cap seems to be our best workaround.

**Comment by RemusMar** [comment] 2018-03-10 08:14
> The current code runs at whatever refresh rate requestAnimationFrame is running at.

Obviously.
And that's 60Hz in most of the cases.

> Since the frequency this block is invoked at depends on context, you can't just drop every other frame.

You can and I do that (with excellent results) for many years ago.
A movie recorded at 24, 25 or 30Hz and played back at 60Hz will have (at least) 2 sequential frames with the same content.
With that simple method all you do is to use a single one of them to update the texture.
The performances boost is HUGE!
The same significant boost for those VR devices (from 90Hz to 45Hz).

Again, as I said from the very beginning, **setInterval** and **videoTexture.frameRate** would be the best soltuion here.

**Comment by mrdoob** [comment] 2018-03-10 16:03
@netpro2k does https://rawgit.com/mrdoob/three.js/dev/examples/webvr_video.html work well for you?

**Comment by mrdoob** [comment] 2018-03-10 18:49
@dustinkerstein You're correct. With the `setInterval()`/`setTimeout()` approach we'll be losing frames from time to time but we're already losing frames because the devices aren't able to upload to the GPU at 60Hz/90Hz so performance degrades and frames are lost.

You can still do this though:

```js
var texture = new THREE.Texture( video );
texture.format = THREE.RGBFormat;
texture.generateMipmaps = false;

function render() {

    requestAnimationFrame( render );

    texture.needsUpdate = true;
    renderer.render( scene, camera );

}
```

This is just a temporal solution. Videos tend to get decoded in the GPU and they're working on a WebGL extension that will allow us to use it directly without having to download it and upload it again.

https://www.khronos.org/registry/webgl/extensions/proposals/WEBGL_video_texture/

**Comment by dustinkerstein** [comment] 2018-03-10 19:09
Yeah, I'll be sticking with the manual needsUpdate method for my application. 

With the proposed WEBGL_video_texture spec, since we still won't know exactly when the new frame is ready (from the GPU / software decoder), we'll need to call needsUpdate every frame (at 60/90hz) but since WebGL now has shared access to the texture, we won't incur the additional texture download/upload cost, correct?

**Comment by mrdoob** [comment] 2018-03-10 19:19
> Or does the need for needsUpdate just totally go away?

That's my understanding. I think it automatically shows the last decoded frame.

**Closed** 2020-12-17 20:37 UTC
Labels: Enhancement

**Comment by MadebyAe** [comment] 2022-09-08 01:36
@mrdoob Did you revert this amazing feature (`videoTexture.frameRate = 25`)?

**Comment by mrdoob** [comment] 2022-09-09 23:58
Yes, we now use [`requestVideoFrameCallback()`](https://web.dev/requestvideoframecallback-rvfc/).
