### ISSUE TITLE
The coordinate system problem of blender to three.js

### ISSUE THREAD

**Issue by iceleaf97** [mrdoob/three.js#10111] opened 2016-11-13 16:11 UTC
(*** This section is for bug reports and feature requests only. This is NOT a help site. Do not ask help questions here. If you need help, please use stackoverflow. ***)

##### Description of the problem 
In this three.js scene, I put my camera at (0, 0, 80) and put a directionalLight at ( 50, 50, 50 ). Then, I create a white sphere geometry (the left sphere) and load a json model from blender (the right sphere). However, the scene showed on the screen looks weird. The directional light project on the wrong surface of the json model. It seems the problem of the coordinate system. 
[two sphere](https://www.dropbox.com/s/uunddfmy3h46brn/blender.png?dl=0)

The version I use is that Blender v2.78 and three.js r80

##### Three.js version

- [ ] Dev
- [ ] r82
- [x] r80

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by TristanVALCKE** [comment] 2016-11-13 20:18
And what about three.js r82 ? Same problem ?

**Comment by MichaelHazani** [comment] 2016-11-13 21:02
Commenting here to say I've noticed similar behavior in specifically circumstances - namely upon importing a sphere from Blender and trying to illuminate it. Both DirectionalLight and PointLight yielded surprisingly counterintuitive and seemingly wrong results. I ended up working around the anomaly (code [here](https://github.com/MichaelHazani/moonwatch/blob/master/src/lib/app.js), live [here](moonwatch.herokuapp.com)) but the issue is definitely there. 

Hope someone has an illuminating thought about it.

**Comment by TristanVALCKE** [comment] 2016-11-13 23:00
I got an 404 error for second (live) link. 
What is the sphere type ? Ico or UV ? Seems to be an UVSphere, right ?

And what about the blender export, as json object, right ? And did you try with an .obj export if you got the same behavior (this could be a work around waiting fix).

For me the first thing that came up, is flipped normal (means inside the sphère, so try to flit normal before exporting your json) and give me a feedback.

**Comment by iceleaf97** [comment] 2016-11-14 05:04
Here are some test results:
blender version: v2.78a
exporter: io_three
sphere type: UVsphere
model filetype: .json

【io_three  version 76】
I got a correct result
[version 76](https://dl.dropboxusercontent.com/u/22576846/io_three_r76.png)

【io_three   all versions after 77】
I got the wrong result
[version 77](https://dl.dropboxusercontent.com/u/22576846/io_three_r77.png)

**Comment by zydecode** [comment] 2016-11-15 13:33
not sure if this is the same issue, but I solved similar to this by changing a line in one of the blender -> threejs exporter files: in exporter/api/mesh.py change line 619 from:
vector = (vector[0], vector[2], -vector[1])
to 
vector = (vector[0], vector[1], vector[2])

**Comment by mrdoob** [comment] 2016-11-17 03:57
@zydecode would you like to do a Pull Request with the fix?

**Comment by zydecode** [comment] 2016-11-17 04:00
I'm happy to, as it immediately solved the issues we were having, and 
we've had no more issues since implementing this fix.

I just hope that the vectors were not as they were to solve another issue..

Cheers,

Sean

**Comment by iceleaf97** [comment] 2016-11-17 05:39
@zydecode It does work! Thank you.

**Comment by mvangeest** [comment] 2017-02-10 15:38
@iceleaf97 A pull request for this change was created (#10155) and has since been merged; if that fixes the problem, perhaps this issue can be closed?

**Closed** 2017-02-10 16:43 UTC
