### ISSUE TITLE
Setting a non-one value to renderer.xr.setFramebufferScaleFactor() to lead to pose error

### ISSUE THREAD

**Issue by edankwan** [mrdoob/three.js#19140] opened 2020-04-15 12:47 UTC
Setting a non-one value to renderer.xr.setFramebufferScaleFactor() to lead to pose error.

For example, adding `renderer.xr.setFramebufferScaleFactor(0.5);` after the line of `renderer.xr.enabled = true;` in [webxr_ar_cones](https://threejs.org/examples/webxr_ar_cones), when the user tap the center of the screen, the cone will be created at the right bottom corner.

##### Three.js version

- [ ] Dev
- [x] r115
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [x] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)
Pixel 2, Chrome v84 Canary

**Comment by Mugen87** [comment] 2020-04-15 17:40
Framebuffer scaling was added back with #18606 (/cc @Firepal).

**Comment by Mugen87** [comment] 2020-04-17 10:14
I can reproduce the issue on a Pixel (1) with Chrome Dev 83.

When debugging the code, `three.js` only places a mesh at the position defined by the `select` event. However, I can't see an obvious issue in the library here. It seems the event data are wrong in the first place.

I've also tested `webxr_vr_ballshooter` and `webxr_vr_dragging` on a Oculus Quest and Oculus Browser by setting `framebufferScaleFactor` to `0.5`. The interaction and rendering works as expected.

Do you mind filing an issue at https://bugs.chromium.org/p/chromium/issues/list instead? The component should be `Blink>WebXR>AR`.

**Comment by Firepal** [comment] 2020-04-17 11:46
Could reproduce on Galaxy S8, Chrome 80.
Forgot to check if the `setFramebufferScaleFactor` function worked in AR...

But so did Chrome developers, I guess?
The "select volume" is sized to the render, and not to the entire screen as you would assume.

**Comment by Mugen87** [comment] 2020-04-17 11:57
> Could reproduce on Galaxy S8, Chrome 80.

Wait, you checked this issue in context of VR, right? And you can reproduce the issue? I thought it does only happen in AR.

**Comment by Mugen87** [comment] 2020-04-17 11:59
> The "select volume" is sized to the render, and not to the entire screen as you would assume.

May I ask what you mean by that?

**Comment by Firepal** [comment] 2020-04-17 13:10
@Mugen87  
When you `setFramebufferScaleFactor` to, for example, `0.5`, you expect just the framebuffer to be scaled to 0.5x, but the area of the screen you can interact with is scaled to 0.5x too.

With `renderer.xr.setFramebufferScaleFactor(0.5)`, the area highlighted in red in this image is the predicted size of the framebuffer (and interaction area) compared to my phone screen.

![image](https://user-images.githubusercontent.com/29317321/79571654-d80a1300-80bb-11ea-8a29-3e1f888f534a.png)

And it's correct, pressing the middle of the screen makes cones appear in the corner of the screen instead of the middle of the screen, because the interaction area is half the size of the screen (like the framebuffer before it's automatically scaled back up).

This changes with different `setFramebufferScaleFactor` values accordingly.
`0.05` makes the interaction area a tiny spot in the top-left of the screen.

**Comment by Mugen87** [comment] 2020-04-17 13:13
Thanks for the clarification. I bet this explanation is valuable for the Chromium team as well^^.

**Comment by Firepal** [comment] 2020-04-17 13:23
@Mugen87 You're welcome! Also, I initially contributed the function to `three.js` for VR, and I had no idea the AR part of WebXR used this function too, welp!

**Comment by Mugen87** [comment] 2020-04-19 09:43
@edankwan I've filed an issue at the Chromium bugtracker today right here:

https://bugs.chromium.org/p/chromium/issues/detail?id=1072225

**Comment by Mugen87** [comment] 2020-04-21 08:44
The bug was fixed now 🎉. The commit should land in production with Chrome 84.

https://storage.googleapis.com/chromium-find-releases-static/56b.html#56bfe671577daa82c7288505e4d814ef4f9cede0

**Closed by Mugen87** 2020-04-21 08:44 UTC
Labels: Browser Issue
