### ISSUE TITLE
RepeatWrapping don't work for normalMaps

### ISSUE THREAD

**Issue by ghost** [mrdoob/three.js#9244] opened 2016-06-28 15:36 UTC
If i like to use a tileable normalmap i can't use RepeatWrapping - nothing happens with the settings and no errors are showing up.
```js
var textureLoader = new THREE.TextureLoader();
var textureNormal = textureLoader.load( "./textures/carpet_normal.png" );
textureNormal.wrapS = textureNormal.wrapT = THREE.RepeatWrapping;
textureNormal.repeat.set( 8, 8 );
```
=> no effect!
##### Three.js version
- [ ] Dev
- [ ] r78
- [ ] ...
##### Browser
- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
##### OS
- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment] 2016-06-28 21:15
Can you create a jsfiddle/test case that show the issue?

**Comment by projekthelden** [comment] 2016-06-29 07:07
Not really because of the code structure - but it is the same issue within the three.js Inspector in Chrome. The repeat settings are there, but nothing happens on the normal map.

![bildschirmfoto 2016-06-29 um 09 02 13](https://cloud.githubusercontent.com/assets/19413261/16443364/a77cbcd0-3dd8-11e6-9e5c-19b44819e4d6.png)

**Comment by mrdoob** [comment] 2016-06-29 19:03
It's because, at the moment, we can only handle one repeat/offset per material. And `map` is being prioritised there.

**Comment by Mugen87** [comment] 2020-02-19 16:34
Duplicate of #9457.

**Closed by Mugen87** 2020-02-19 16:34 UTC
Labels: Feature Request
