### ISSUE TITLE
CSS3DRenderer IOS : CSS3DRender partially render

### ISSUE THREAD

**Issue by c4ntin** [mrdoob/three.js#27378] opened 2023-12-14 14:43 UTC
### Description

Hello,
On my scene, I added multiple CSS3DObject it works well on windows, android and macbook but on Iphone et Ipad. They are troncated (see fiddle).

My video sample is 320x176px  (same comportment with other html elm). 
If you resize it and keep the ratio to 1.8x1meter. The video is truncated! (line 94)
If you resize it and keep the ratio to 0.9x0.5meter. The video is display correctly! (line 95)

### Reproduction steps

1. Open the link fiddle on iphone or ipad and observe the bug.
2. Change the line 94 to 95 => no bug

### Code

```js
// Simple three.js example

import * as THREE from 'three';
import {
  OrbitControls
} from 'three/addons/controls/OrbitControls.js';
import {
  CSS3DRenderer,
  CSS3DObject
} from 'three/addons/renderers/CSS3DRenderer.js';
let mesh, renderer, scene, camera, controls, rendererCss;

init();
animate();

function init() {
  // scene
  scene = new THREE.Scene();

  // camera
  camera = new THREE.PerspectiveCamera(40, window.innerWidth / window.innerHeight, 0.1, 10000);
  camera.position.set(1, 0, 1);

  // renderer
  const renderContainer = document.querySelector('#Renders');

  renderer = new THREE.WebGLRenderer({
    antialias: true,
    alpha: true
  });
  renderer.outputColorSpace = THREE.LinearSRGBColorSpace;
  renderer.toneMapping = THREE.LinearToneMapping;
  renderer.toneMappingExposure = 1;
  renderer.setSize(window.innerWidth, window.innerHeight);
  renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));
  renderer.setClearColor(0x000000, 0);
  renderer.domElement.style.zIndex = "1";
  renderer.domElement.style.position = "fixed";
  renderer.domElement.style.top = "0";
  renderer.domElement.style.left = "0";

  renderContainer.style.position = "fixed";
  renderContainer.style.top = "0";
  renderContainer.style.left = "0";
  renderContainer.style.zIndex = "3";

  rendererCss = new CSS3DRenderer();
  renderContainer.appendChild(rendererCss.domElement);
  rendererCss.setSize(window.innerWidth, window.innerHeight);
  rendererCss.render(scene, camera);

  rendererCss.domElement.appendChild(renderer.domElement);
  window.addEventListener('resize', () => onWindowResize());



  // controls
  controls = new OrbitControls(camera, renderer.domElement);
  scene.add(new THREE.AmbientLight(0x222222));

  // axes
  //scene.add( new THREE.AxesHelper( 20 ) );

  var videoObj = CreateAssetVideoObj3d();
  scene.add(videoObj);
}

function onWindowResize() {
  // Update camera
  this.camera.aspect = window.innerWidth / window.innerHeight;
  this.camera.updateProjectionMatrix();

  // Update renderer
  this.renderer.setSize(window.innerWidth, window.innerHeight);
  this.renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));
  this.rendererCss.setSize(window.innerWidth, window.innerHeight);
}


function animate() {

  requestAnimationFrame(animate);

  //controls.update();

  renderer.render(scene, camera);
  rendererCss.render(scene, camera);
}

function CreateAssetVideoObj3d() {
  const ratioMeterPx = 1000;

  const resize = Resize(1000, 550, 2 * ratioMeterPx, 1 * ratioMeterPx);//bug iphone
  //const resize = Resize(1000, 550, 1 * ratioMeterPx, 0.5 * ratioMeterPx);//no bug  why??????
  console.log("resize", resize);
  const objContainer = new THREE.Object3D();

  const videoElm = CreateVideoElm(resize.w, resize.h);
  //console.log("dfdsf",resize.w, resize.h)
  const divElm = document.createElement("div");
  divElm.appendChild(videoElm)

  var cssObj = new CSS3DObject(divElm);
  cssObj.position.set(0, 0, 0);
  cssObj.scale.set(1 / ratioMeterPx, 1 / ratioMeterPx, 1 / ratioMeterPx);

  var material = new THREE.MeshBasicMaterial({
    opacity: 0,
    color: new THREE.Color(0x000000),
    blending: THREE.NoBlending
  });
  var geometry = new THREE.BoxGeometry(resize.w, resize.h, 0);
  var supportObj3d = new THREE.Mesh(geometry, material);
  supportObj3d.position.set(0, 0, 0);
  var holder = new THREE.Group();
  holder.add(cssObj);
  holder.add(supportObj3d);
  objContainer.add(holder);
  holder.rotateY(-Math.PI / 2);

  objContainer.position.set(0, 0, 0);
  return objContainer;
}

function CreateVideoElm(width, height) {
  const video = document.createElement("video");
  const videoSrc = document.createElement("source");
  videoSrc.setAttribute("type", "video/mp4");
  video.append(videoSrc);
  videoSrc.src = "https://img.colleconline.com/videosart/b37f9521fd6f4ad5b4d7c50d46e3da0c/be4eae566fd546b0804d81ecd9d9cade/mov_bbb-231213130129.mp4";
  video.poster = "https://img.colleconline.com/artefactimg/b37f9521fd6f4ad5b4d7c50d46e3da0c/89f8c3cac8864a2a852651d865bab825.jpg"
  video.width = width;
  video.height = height;
  video.setAttribute("webkit-playsinline", "webkit-playsinline");
  video.setAttribute("playsinline", "");
  video.setAttribute("loop", "");
  //video.setAttribute("controls", "");
  //video.setAttribute("autoplay", "");
  video.setAttribute("crossorigin", "anonymous");
  video.load();

  return video;
}

function Resize(w, h, maxw, maxh) {
  var ratio = Math.min(maxw / w, maxh / h);
  console.log("resize", maxw / w, maxh / h, ratio);
  return {
    w: w * ratio,
    h: h * ratio
  };
}

```

### Live example

* [css3drender](https://jsfiddle.net/7fx26g0q/)

### Screenshots

![Screenshot 2023-12-14 100259](https://github.com/mrdoob/three.js/assets/7249833/ab0811ee-d289-49fa-a0d3-b2c136a09346)
![Screenshot 2023-12-14 100455](https://github.com/mrdoob/three.js/assets/7249833/9e61f7c5-b0dd-435b-a2e4-2a4f596f9872)

### Version

0.156.0

### Device

Mobile

### Browser

Chrome, Safari

### OS

iOS

**Comment by Mugen87** [comment] 2023-12-14 15:14
I can confirm the issue on an iPad with iPadOS 17.1.2. Maybe related to #26950.

**Comment by Mugen87** [comment] 2023-12-14 15:15
Since the behavior depends on the size, this is actually a duplicate of #26950.

**Closed by Mugen87** 2023-12-14 15:15 UTC
Labels: Browser Issue, Addons
