### ISSUE TITLE
Adding Rotation to Cubemap and PMREM Generator Examples

### ISSUE THREAD

**Issue by kitaedesigns** [mrdoob/three.js#26652] opened 2023-08-26 23:08 UTC
### Description

Rotating the cubemap is something that is pretty standard in any 3D app that uses Image Based Lighting, currently, there does not seem to be a way to do it in three.js without writing a custom shader or adapting RoomEnvironment.js. Adding this rotation to update the scene background to match as well would be very helpful.

### Solution

Adding this ability to the example would be greatly beneficial to everyone as finding the correct rotation for lighting/reflections.  

### Alternatives

I've tried creating a sphere with flipped normals and mapping the image to it and rotating that but that solution only changes the image background and then creates a mismatch between the lighting/reflections rotation and then the visual background's rotation. I've also rotated the cubemap in Photoshop and reuploaded it but that is quite cumbersome and not everyone has the ability to do that. Referencing this R3F demo may be helpful https://codesandbox.io/s/rotate-environments-ygmu6m?file=/src/App.js

**Comment by Mugen87** [comment] 2023-08-27 08:13
Duplicate of #16328.

**Closed by Mugen87** 2023-08-27 08:13 UTC
