### ISSUE TITLE
load VTKdata created by Paraview failed (no data shown)

### ISSUE THREAD

**Issue by Lenvia** [mrdoob/three.js#20582] opened 2020-10-29 16:22 UTC
Hello,

I am trying to load vtk files in three.js using the VTKLoader.  I just modified the file "webgl_loader_vtk.html" and replace the original file "bunny.vtk" with my own vtkdata.

The vtk file is produced by paraview. 
But the loader fails and there is no data shown in browser (no error shown). I trid to use "console.log(geometry)" and found no data in it.

You can click this [link](https://drive.google.com/file/d/1y-bFwxvkBoLbRl7064uhRhN3r-TkN9pS/view?usp=sharing) to get the vtk file.

Any suggestion?
Thank you!

**Comment by Mugen87** [comment] 2020-10-29 16:40
Possibly a duplicate of #16527.

**Comment by Lenvia** [comment] 2020-10-29 16:53
> Possibly a duplicate of #16527.

Unfortunately, I have checked that issue before. My Dataset type is POLYDATA, which meet the requirement.

I have compare my vtkdata with "bunny.vtk", and I found some words in my file which I am not familiar, such as "METADATA", "INFORMATION".
I don't know what they mean, even though I tried to look up the VTKDataFormat.

Do you have other suggestions?
Thank you!

**Comment by Lenvia** [comment] 2020-10-30 05:20
hi, 
I checked the source code of VTKLoader.js and found that it did not parse the attributes such as "LINES" and "VECTORS", but only parsed the attributes such as "POINTS" and "POLYGONS".

However, my vtk file contains such as

LINES 2 294
142 8 9 10… (the first line)
150 159 160… (the second line)

as well as

VECTORS Normals double
1 0 0 1 0 0 1 0 0
…

And other data.
It may not recognize these, so it did not read the data.

**Closed** 2020-10-30 05:57 UTC
Labels: Loaders
