### ISSUE TITLE
toJSON(meta) deletes metadata field without checking existence

### ISSUE THREAD

**Issue by jtkbong** [mrdoob/three.js#24863] opened 2022-10-28 00:59 UTC
Hi,

I am using the getObjectByName method to get mesh data for my scene. My meshes don't have the metadata field, so when I invoke this function, the delete line fails:
```
function extractFromCache( cache ) {

			const values = [];
			for ( const key in cache ) {

				const data = cache[ key ];
				-> delete data.metadata;
				
				values.push( data );

			}

			return values;

		}
```

Any advice on what I can do?

Thanks,
Jeremy

**Comment by Mugen87** [comment] 2022-10-28 07:49
Do you mind demonstrating the issue with a live example? https://jsfiddle.net/7u84j6kp/

I'm afraid the issue is not clear so far.

**Comment by jtkbong** [comment] 2022-10-28 19:07
of course, I will try my best.

I have added the window function call that calls to get the object in here:

https://jsfiddle.net/ep5z7L2r/

We use AMI.VolumeLoader to load meshes in our 3D scene, then these are added to the scene via `scene.add`.

We have a debug test hook that is called through selenium's execute_script. When that is called, an error is returned as a result of data.metadata not existing when extractFromCache tries to delete it.

Please let me know if you need more info.

**Comment by Mugen87** [comment] 2022-10-31 09:19
Closing until the error is reproducible.

**Closed by Mugen87** 2022-10-31 09:19 UTC
