### ISSUE TITLE
Suggestion: Make mipmapping more user-friendly

### ISSUE THREAD

**Issue by EliasHasle** [mrdoob/three.js#17314] opened 2019-08-22 09:57 UTC
##### Description of the problem
Background: #7063

When a user sets the minFilter to one that uses mipmaps and does not supply manually created mipmaps, are there any cases where this user does not want mipmaps generated on the first render? The current behavior is that the texture rendering fails.

I do not have the full overview, but I notice this related method in WebGLTextures.js: https://github.com/mrdoob/three.js/blob/027f70773db6d0f298391b7069012bd8d3d3bf40/src/renderers/webgl/WebGLTextures.js#L103

I have a proposal, that I don't know yet whether is both possible and beneficial:
1. Remove the `generateMipmaps` option.
2. If not existing already, add an internal flag that tells whether any mipmaps are in place (either generated or loaded) for the texture.
3. If the flag is false and mipmaps are needed for the filtering, then always generate mipmaps before using the texture.
4. Add an option to `Texture` for automatically updating mipmaps on dynamical textures.

I may have overlooked/misunderstood something regarding the importance of `generateMipmaps`.

**Comment by gkjohnson** [comment] 2019-08-23 03:46
I haven't used it myself but the `texture2d` shader function can take a third `bias` argument that changes which mipmap level is used when sampling the texture. I haven't tested the behavior but if it still changes the mipmap level even when `minFilter` is set to `NearestFilter` then that would be a case when you might want to generate mipmaps without setting `minFilter` to a a setting that uses mipmaps.

If the goal is to prevent mistakes / confusion then would it make sense to update the docs to be a bit more clear or do something like log a warning when `generateMipmaps` is `false` but `minFilter` uses them?

**Comment by EliasHasle** [comment] 2019-08-27 19:47
> I haven't used it myself but the texture2d shader function can take a third bias argument that changes which mipmap level is used when sampling the texture.

I haven't tested it either, but the [WebGL 1.0 reference card](https://www.khronos.org/files/webgl/webgl-reference-card-1_0.pdf) tells me that both `bias` and `lod` are `float` parameters, triggering interpolation (or selection, in the case of MIPMAP_NEAREST?) between mipmap levels. I suppose that would be only when the minification filter is one of the minification modes that "cares" about multiple levels, that is one of the mipmapping types.

However, [WebGL 2](https://www.khronos.org/files/webgl20-reference-guide.pdf) includes `textureSize` and `texelFetch` functions that take an `int lod` parameter that forces selection of a specific Mipmap level, possibly regardless of `TEXTURE_MIN_FILTER`.

So it looks like one cannot simply remove `generateMipmaps`. But improving the docs and default behavior should still be possible. Small undetected mistakes with hard-to-grasp parameters like these are the kind of bug that bugs people for hours.

**Comment by Usnul** [comment] 2019-08-28 03:20
I don't understand the motivation for it. Generation of mipmaps is fairly quick, and you would want to use mipmaps in most cases. Being able to control whether mips are generated or not is useful, to me at least. There are plenty of cases when mipmaps are not useful too. Generating mipmaps in a lazy way could be a good idea, but I feel that Virtual Texture tech is a better avenue to pursue if the goal is to save CPU cycles and RAM on mip generation.

Could you provide some usecases for what you're suggesting, I'm a just not seeing it without more info :)

**Comment by EliasHasle** [comment] 2019-08-28 05:46
@Usnul It is not about particular use cases or particular solutions. I am concerned with two things:
1. Avoiding hard-to-fix errors.
2. Keeping power/flexibility for advanced users.

It looks to me like point 1 may be served best by eliminating manual setting of `generateMipmaps`, but that it will be at the cost of point 2. The question then is whether it would still be possible to automate some cases, or at least spit out warnings when settings are invalid at render time.

**Comment by Usnul** [comment] 2019-08-28 06:15
@EliasHasle 
thanks, I think I understand it better now. What kind of "hard-to-fix error" do you mean?

**Comment by EliasHasle** [comment] 2019-08-28 06:21
Forgetting to set `generateMipmaps=true` on a DataTexture when setting `texture.minFilter=THREE.LinearMipmapLinearFilter` will cause the texture to disappear with no warning. I believe the requirement is mentioned in current docs.

**Comment by Usnul** [comment] 2019-08-28 08:06
I see the issue now. I think it's a very valid concern, probably input validation somewhere inside the renderer is the way to go.  I'm starting to think more and more that three.js would benefit from a development build separate to a production build, to enable some additional validation and error reporting.

**Comment by Mugen87** [comment] 2021-03-09 13:36
Automatic configurations are always tempting but the problem is that inferring something from properties or parameters can quickly lead to unexpected behavior or can completely break use cases. A good example for this is #18861. The engine tries to be smart by avoiding generating mipmaps in certain scenarios but this apparently blocks users in doing other things.

It is not acceptable to remove `Texture.generateMipmaps` since it is required to notify the engine whether to generate mipmaps or not. Besides, there are use cases where app level code or engine components like texture loaders provide mipmaps so automatic generation is not necessary. But you still want to use trilinear filtering.

Besides, all texture and render targets classes provide now proper `minFilter` and `magFilter` default values. If users decide to change them, one can expect that they know what they are doing and also understand the consequences of certain settings. Since the documentation are not intended as a replacement for basic computer graphics education, I do not vote to add more explanations to it. I think it's best to close this issue and focus on #18861 instead.

**Closed** 2021-03-26 10:29 UTC
Labels: Suggestion
