### ISSUE TITLE
Bitmap image resize over max size doesnt honor imageOrientation flipY

### ISSUE THREAD

**Issue by Samsy** [mrdoob/three.js#25327] opened 2023-01-24 10:00 UTC
### Description

Trying to load a bitmap oversize, get resized, but flipped in a canvas ! 

I wonder if there is a way to check if the bitmap was created with an imageOrientation

https://github.com/mrdoob/three.js/blob/dev/src/renderers/webgl/WebGLTextures.js#L67

### Reproduction steps

1. load a bitmap image oversize as a texture

### Code

```js
// code goes here
```

### Live example

.

### Version

last

**Comment by Mugen87** [comment] 2023-01-24 10:18
> I wonder if there is a way to check if the bitmap was created with an imageOrientation

Not at the moment. `imageOrientation` is an options parameter of `createImageBitmap()` and the resulting instance of `ImageBitmap` does not report its respective options. If we want to evaluate it we need to store it right before this line:

https://github.com/mrdoob/three.js/blob/4a6cf23c5f69ecde00e79171be7235deb39dff79/src/loaders/ImageBitmapLoader.js#L80

However, I'm not sure this approach works if two image bitmaps are loaded with different options in a sequence. Meaning:
```
loader.setOptions( options1 );
loader.load( ... ):
loader.setOptions( options2 );
loader.load( ... );
```
Depending on which image is loaded first, the wrong options might be stored in the image bitmap. So this would only be safe if `options` is a parameter of `load()`. But then the loader wouldn't have the common `Loader.load()` signature anymore.

**Comment by Mugen87** [comment] 2023-01-24 10:19
I think we can consider this issue as a duplicate of #16144.

Yes, this issue is not about POT but the real problem is the resize that happens in `WebGLTextures`.

**Closed by Mugen87** 2023-01-24 10:19 UTC
