### ISSUE TITLE
Visual bug in Mozilla Firefix 50.1.0

### ISSUE THREAD

**Issue by Thund3rb1rd** [mrdoob/three.js#10647] opened 2017-01-25 10:48 UTC
##### Description of the problem 

We are building a panorama 360 image using Three.js library. Unfortunately, we can't overcome the bug that happens only in Mozilla Firefox  50.1.0. As you see on the screenshots, only a single side image is shown and the others are solid black. Can you please help us?

##### Three.js version

- [x ] Dev
- [ ] r82
- [ ] ...

##### Browser

- [] All of them
- [ ] Chrome
- [x ] Firefox
- [ ] Internet Explorer

##### OS

- [] All of them
![three js _ examples - mozilla firefox 2017-01-25 12 29 51](https://cloud.githubusercontent.com/assets/14910770/22287654/4eb9a31e-e2fc-11e6-9d8a-e8b56a52d7a6.png)
![three js _ examples - mozilla firefox 2017-01-25 12 30 21](https://cloud.githubusercontent.com/assets/14910770/22287661/5869e482-e2fc-11e6-9b3f-4c7113bbc55e.png)
![three js _ examples - mozilla firefox 2017-01-25 12 31 39](https://cloud.githubusercontent.com/assets/14910770/22287667/5b597dce-e2fc-11e6-8e99-32261589b0f7.png)

- [x] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by looeee** [comment] 2017-01-25 10:57
It's working fine for me, same FF version and Windows 10.

**Comment by mrdoob** [comment] 2017-01-25 15:45
I can reproduce on Firefox 50.1.0 / Fedora 25.

![screenshot from 2017-01-25 15-43-58](https://cloud.githubusercontent.com/assets/97088/22297451/337f7844-e315-11e6-8654-415dd13fa9ce.png)

I think we should give another go to [CSS3DRenderer](https://github.com/mrdoob/three.js/blob/dev/examples/js/renderers/CSS3DRenderer.js). I have the feeling it could use the API better...

**Comment by kearwood** [comment] 2017-01-25 23:58
Tracking investigation in Bugzilla:

https://bugzilla.mozilla.org/show_bug.cgi?id=1333948

We suspect that this may have been fixed in FF53..

Can anyone that reproduced it confirm that it's working in Firefox nightly?

Thanks!

**Comment by Thund3rb1rd** [comment] 2017-01-26 08:56
nope, still able to reproduce the bug in Mozilla Firefix 50.1.0

![d0 91 d0 b5 d0 b7 d1 8b d0 bc d1 8f d0 bd d0 bd d1 8b d0 b9 - paint 2017-01-26 10 47 59](https://cloud.githubusercontent.com/assets/14910770/22325291/062a683a-e3b6-11e6-9987-19441595dbe6.png)

**Comment by RemusMar** [comment] 2017-01-26 17:46
> we can't overcome the bug that happens only in Mozilla Firefox 50.1.0

I cannot replicate your issue on Windows XP, 7 and 8.1

![css3d_panorama](https://cloud.githubusercontent.com/assets/11772787/22343256/1546bc98-e400-11e6-8691-e049c368ca35.jpg)

**Comment by Mugen87** [comment] 2017-01-29 23:06
Can't reproduce with FF Nightly 54.0a1 (2017-01-29) (64-bit) on Mac OS 10.11.6.

**Closed** 2017-04-04 11:03 UTC
