### ISSUE TITLE
Editor adds undo recovery option for non indexDB

### ISSUE THREAD

**Issue by WREQI** [mrdoob/three.js#28019] opened 2024-03-28 03:44 UTC
### Description

The editor loads a slightly larger model, and after each editing, the indexDB cache becomes very sluggish. It is possible to add a undo and restore function that does not use IndexDB. I guess using IndexDB is to ensure that the browser can still function normally after closing, but in many cases, it automatically restores without closing the browser. Using the editor is mainly to check and view the correctness of the test model and to build a simple scene. An option can be provided to disable the caching mode of indexDB.
As shown in the figure below, simply dragging once results in a delay of 258.73ms. During this time period, it is easy to make a second drag and get stuck
![image](https://github.com/mrdoob/three.js/assets/35467304/393518ca-5f64-4da7-a1dc-fac702f1bee5)

### Solution

Add the option to disable indexDB

### Alternatives

Alternatives
Describe alternatives you've considered.

**Comment by Mugen87** [comment] 2024-03-28 09:34
I think you can avoid the issue by just disabling `autosave` at the top right of the app window.

In this way, the scene isn't saved on each edit anymore but you can still use undo commands if necessary.

Would that be an acceptable solution for you?

**Comment by Mugen87** [comment] 2024-03-28 09:35
This issue is somewhat a duplicate of #15853.

**Comment by WREQI** [comment] 2024-03-29 01:56
> 我认为您可以通过在应用程序窗口的右上角禁用来避免此问题。`autosave`
> 
> 这样，场景不再在每次编辑时保存，但如有必要，您仍然可以使用撤消命令。
> 
> 这对您来说是一个可以接受的解决方案吗？

Okay, I didn't see it

**Closed** 2024-03-29 01:56 UTC
Labels: Editor
