### ISSUE TITLE
directional light halo flickers in mobile devices (possibly Adreno gpus)

### ISSUE THREAD

**Issue by VanderSP** [mrdoob/three.js#26687] opened 2023-09-03 14:58 UTC
### Description

directional light halo flickers in (xiaomi redmi note 7, the one i tested) mobile device, for example, t3d.js lib doesn't have the halo neither the problem, also threejs illuminates just one side of cube, and t3d all faces...

### Reproduction steps

1. create directional light
2. create a plane or box, spheres doesn't have this problem
3. rotate a bit with orbit controls you will see horrible flickers, not that´s related to orbit controls, but interestingly some combinations of positioning and rotation of mesh and light

### Code

```js
// code goes here
```

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/g3atw6k5/)
* [jsfiddle-dev](https://jsfiddle.net/hjqw94c5/)

### Version

testes from r110 to r156

### Device

Mobile

### Browser

Chrome

### OS

Android

**Comment by Mugen87** [comment] 2023-09-04 07:58
It is not possible to investigate the issue with the information you have provided so far. 

- Share a live example that demonstrates the issue.
- Share a screenshot or video since the mentioned flickering does not happen on all devices.
- Share more information about your mobile devices (OS and browser version, chipset). It's best to type `chrome://gpu/` in your Chrome address bar and share the report.

We can reopen the issue when these information are provided.

**Comment by Mugen87** [comment] 2023-09-05 17:02
Interesting! I can actually reproduce the issue on a Pixel 4a with latest Chrome.

**Comment by Mugen87** [comment] 2023-09-05 17:03
Live example with `r156`: https://jsfiddle.net/4xz1oj3e/1/show

**Comment by VanderSP** [comment] 2023-09-05 17:06
I tried to upload a video, but i failed miserably, tried from android, tried from windows, converted to gif, nothing works
putting a video in github is depressive

**Comment by VanderSP** [comment] 2023-09-05 18:02
in Mali-G77 MC9 is working fine...

Adreno related maybe?

**Comment by Mugen87** [comment] 2023-09-06 07:45
Yes, maybe. It is not the first time we have issues with this type of GPU.

**Comment by Mugen87** [comment] 2023-09-06 07:46
For testing: https://jsfiddle.net/m0cn9peq/show

**Comment by Mugen87** [comment] 2023-09-06 07:49
https://jsfiddle.net/yw7s1mvn/show

**Comment by Mugen87** [comment] 2023-09-06 07:54
It also happens with phong materials using high `shininess` values. 

https://jsfiddle.net/yw7s1mvn/show

So the issue is not related to the PBR implementation.

**Comment by Mugen87** [comment] 2023-09-06 07:55
Test link: https://jsfiddle.net/g5tzkmsf/show

**Comment by Mugen87** [comment] 2023-09-06 08:04
https://jsfiddle.net/c6kqs4d7/1/show

**Comment by Mugen87** [comment] 2023-09-06 08:47
https://jsfiddle.net/ysc8pb5u/show

**Comment by Mugen87** [comment] 2023-09-06 08:49
https://jsfiddle.net/8wnhced7/show

**Comment by Mugen87** [comment] 2023-09-06 08:51
https://jsfiddle.net/8wnhced7/1/show

**Comment by Mugen87** [comment] 2023-09-06 08:53
https://jsfiddle.net/8wnhced7/2/show

**Comment by Mugen87** [comment] 2023-09-06 09:13
I could imagine the issue is related to what @gkjohnson mentions here: https://github.com/mrdoob/three.js/pull/24435#issuecomment-1203336806

> Just a small word of caution here - on some Android Adreno devices floats in structs are limited to 16 bits of precision instead of 32 while non struct uniforms are afforded 32 bits of precision... which is a massive pain. It might not be a huge issue for values that are kept between [ -1.0, 1.0 ], but it's something to keep in mind as you go.

**Comment by VanderSP** [comment] 2023-09-06 20:29
@Mugen87 Exactly... confirmed here your jsfiddle´s!

**Comment by Mugen87** [comment] 2023-09-07 08:06
It seems the only way to solve the issue in `three.js` is to avoid any usage of structs in GLSL. This requires a huge refactoring and the resulting code will be much less readable and more verbose. Especially function signatures will look horrible after this change.

Outside of `three.js` the issue can be fixed if Qualcomm fixes their drivers (which would be in some sense the best solution). Although this won't help devices which do no receive system updates anymore. I believe Chrome could fix the issue if the browser switches to a Vulkan backend (see https://github.com/KhronosGroup/WebGL/issues/3351#issuecomment-1286267604). I've tried to force Vulkan via `chrome://flags/` but it seems Chrome still uses OpenGL ES on Android.

**Comment by VanderSP** [comment] 2023-09-07 13:43
t3d.js doesn't have this issue, seems like it doesn't uses a halo?

**Comment by gkjohnson** [comment] 2023-09-08 07:44
> It seems the only way to solve the issue in three.js is to avoid any usage of structs in GLSL. This requires a huge refactoring and the resulting code will be much less readable and more verbose. Especially function signatures will look horrible after this change.

Agreed. I would pick maintainability myself, though there are a lot of older Adreno devices out there. Adreno devices have long [had some of the worst mobile drivers](https://twitter.com/garrettkjohnson/status/1670750185243430912?s=20) but according to [this comment](https://github.com/KhronosGroup/WebGL/issues/3351#issuecomment-1286518632) the Adreno 660 (2020 release) no longer has this precision issue so hopefully through the years this will become less of a problem.

**Comment by Mugen87** [comment] 2023-09-08 08:42
Then let's mark this issue as a `Won't fix` on our side.

**Comment by VanderSP** [comment] 2023-09-08 11:15
660 is new and has the bug in asus zen fone 8

**Comment by gkjohnson** [comment] 2023-09-09 07:46
> 660 is not that old and has the bug in asus zen fone 8

I'm sorry, you're right. I misread the comment at the link above. It seems like the Adreno 660 still has the precision bug that will cause this issue so it looks like there isn't necessarily an end for this. But as mentioned previously the code ergonomics would suffer dramatically from addressing this issue in the general case and make the code a lot harder to maintain.

It's possible that we only need to pull one or two fields out of structs to address this but still ideally Qualcomm would fix their terribly buggy drivers - or at least it would be nice for browsers to unpack structures on compilation to avoid these precision issues.

If you help identify which fields need to be removed from the struct to retain precision it might help the project make these decision about what can be done.

**Comment by Mugen87** [comment] 2023-09-09 08:34
I suspect the culprit is the struct `GeometricContext` because it holds view position, normals and viewing direction vectors. Loosing precision for these units could be origin for the flickering. I haven't tested it yet since removing just this single struct has quite an impact on the GLSL code base.

**Comment by Mugen87** [comment] 2023-09-11 08:39
https://jsfiddle.net/3gbq29ys/show

**Comment by VanderSP** [comment] 2023-09-11 12:18
Fixed

**Comment by Mugen87** [comment] 2023-09-12 09:24
I've cleaned up the code a bit and this is how the changes to the core would look like when `GeometricContext` is going to be removed:

https://github.com/Mugen87/three.js/commit/6be97acd85812be657eb5b8ebb4d70a656b32c01

Granted, the code isn't so nicely structured as before but it isn't that bad after all. However, this change will break quite some example code since certain modules implement custom shader code or modifications based on `GeometricContext`. E.g. `CSMShader`, `MeshGouraudMaterial`, `MMDToonShader`, `SubsurfaceScatteringShader`. I suspect that app-level code will also be affected by this change. 

Um, it's really hard to evaluate the trade-off of this change. On the one hand, better support for Android devices, on the other hand less readable GLSL code and migration tasks.

@mrdoob What do you think we should do here?

**Comment by Mugen87** [comment] 2023-09-15 08:57
After thinking about this issue a few times I vote to update the shaders in order to avoid the glitches with Adreno GPUs. Since even modern chips are affected and the total number of affected devices is quite high, the changes to the shader code base are appropriate to me.

**Comment by VanderSP** [comment] 2023-09-15 18:14
Thank you, you are greatly contributing to the community 💪

COOL INFORMATIVE ->
https://www.techcenturion.com/mobile-gpu-rankings

**Closed** 2023-09-20 13:55 UTC
Labels: Device Issue
