### ISSUE TITLE
STL rendering issues on Chrome

### ISSUE THREAD

**Issue by ShtiviGrin** [mrdoob/three.js#23946] opened 2022-04-26 09:02 UTC
**Describe the bug**

I am working on a project in which I need to add an ability to view stl files uploaded by users.
I followed some tutorials and examples, and in all of them I encountered an issue with rendering the stls. They look like that:
<img width="1392" alt="image" src="https://user-images.githubusercontent.com/69106412/165261983-4871dcd6-626e-4009-b8f8-0556201eb337.png">

This happens on Chrome.
On Safari it works normally.

Here is a link to the STL that you see in the screenshot:
https://storage.googleapis.com/ucloud-v3/ccab50f18fb14c91ccca300a.stl

I have tried it on other files, got the same resuilt.

**To Reproduce**
Just run the code below.

***Code***

```js
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />

    <title>Stl Viewer</title>
    <script>
      function STLViewer(model, elementID) {
        var elem = document.getElementById(elementID)

        var camera = new THREE.PerspectiveCamera(70, elem.clientWidth / elem.clientHeight, 1, 1000)
        var renderer = new THREE.WebGLRenderer({ antialias: true, alpha: true })
        renderer.setSize(elem.clientWidth, elem.clientHeight)
        elem.appendChild(renderer.domElement)

        window.addEventListener(
          'resize',
          function () {
            renderer.setSize(elem.clientWidth, elem.clientHeight)
            camera.aspect = elem.clientWidth / elem.clientHeight
            camera.updateProjectionMatrix()
          },
          false
        )

        var controls = new THREE.OrbitControls(camera, renderer.domElement)
        controls.enableDamping = true
        controls.rotateSpeed = 0.3
        controls.dampingFactor = 0.1
        controls.enableZoom = true
        controls.autoRotate = false
        controls.autoRotateSpeed = 0.75

        var scene = new THREE.Scene()
        scene.add(new THREE.HemisphereLight(0xffffff, 1.5))

        new THREE.STLLoader().load(model, function (geometry) {
          const material = new THREE.MeshPhongMaterial({ color: 0xaaaaaa, specular: 0x111111, shininess: 200 })
          const mesh = new THREE.Mesh(geometry, material)
          scene.add(mesh)

          var middle = new THREE.Vector3()
          geometry.computeBoundingBox()
          geometry.boundingBox.getCenter(middle)
          mesh.geometry.applyMatrix(new THREE.Matrix4().makeTranslation(-middle.x, -middle.y, -middle.z))
          mesh.castShadow = false
          mesh.receiveShadow = false

          var largestDimension = Math.max(
            geometry.boundingBox.max.x,
            geometry.boundingBox.max.y,
            geometry.boundingBox.max.z
          )
          camera.position.z = largestDimension * 1.5

          var animate = function () {
            requestAnimationFrame(animate)
            controls.update()
            renderer.render(scene, camera)
          }

          animate()
        })
      }

      window.onload = function () {
        STLViewer('https://storage.googleapis.com/ucloud-v3/ccab50f18fb14c91ccca300a.stl', 'model')
      }
    </script>
  </head>

  <body>
    <noscript>You need to enable JavaScript to run this app.</noscript>

    <script src="./lib/three.min.js"></script>
    <script src="./lib/STLLoader.js"></script>
    <script src="./lib/OrbitControls.js"></script>

    <div id="model" style="width: 1500px; height: 1000px"></div>
  </body>
</html>

```

I downloaded three.min.js, STLLoader.js and OrbitControls directly from the three.js repo:

https://github.com/mrdoob/three.js/blob/dev/build/three.min.js
https://github.com/mrdoob/three.js/blob/dev/examples/js/loaders/STLLoader.js
https://github.com/mrdoob/three.js/blob/dev/examples/js/controls/OrbitControls.js

I tried also taking from master, same result.

**Expected behavior**

STL should simply render normally.
<img width="1284" alt="image" src="https://user-images.githubusercontent.com/69106412/165263782-26f89191-eadf-4942-970f-be7ac5e89587.png">

**Platform:**

 - Device: Desktop
 - OS: MacOS
 - Browser: Chrome version 100.0.4896.127 (today's latest), Safari (15.3)
 - Three.js version: [dev, r???]

**Comment by Mugen87** [comment] 2022-04-26 09:20
I have drag'n'dropped the asset into the [three.js editor](https://threejs.org/editor/) (prod and dev) and it renders as expected:

<img width="1340" alt="image" src="https://user-images.githubusercontent.com/12612165/165266939-eb313e5d-8085-40a4-a4b3-60fd5f0fbb2a.png">

Tested with Chrome 100.0.4896.127.

Do the asset look good on your device if import the asset in the editor?

**Comment by ShtiviGrin** [comment] 2022-04-26 11:01
> I have drag'n'dropped the asset into the [three.js editor](https://threejs.org/editor/) (prod and dev) and it renders as expected:
> 
> <img alt="image" width="1340" src="https://user-images.githubusercontent.com/12612165/165266939-eb313e5d-8085-40a4-a4b3-60fd5f0fbb2a.png">
> 
> Tested with Chrome 100.0.4896.127.
> 
> Does the asset look good on your device if import it into the editor?

Thanks for your quick reply!

this is what I get on the editor:
![image](https://user-images.githubusercontent.com/69106412/165285986-e048f8ea-bd0a-4e46-b3ca-f697b41c96e8.png)

**Comment by Mugen87** [comment] 2022-04-26 11:04
You are on macOS, right? Can you please update to the latest version?

This looks like a driver/device issue to me.

**Comment by ShtiviGrin** [comment] 2022-04-26 11:06
@Mugen87 sure, I'll do that. the only thing is that on Safari it works perfectly fine.

**Comment by Mugen87** [comment] 2022-04-26 14:22
Do you see similar issues with the official three.js examples? https://threejs.org/examples/

**Comment by ShtiviGrin** [comment] 2022-04-26 14:25
@Mugen87 nope, they are working for me

**Comment by Mugen87** [comment] 2022-04-26 15:13
Strange. Sorry, I have not idea was going wrong on your system.

I've tested the asset on a Windows notebook with latest Chrome and the `three.js editor` but with the same result. The STL is rendered as expected.

**Comment by ShtiviGrin** [comment] 2022-04-27 06:23
@Mugen87 Hi again,
I don't see any console errors. 
On Firefox it also works fine.

**Comment by Mugen87** [comment] 2022-04-28 08:38
You might want to test if Chrome Canary can properly render the asset on your system.

Can you also drag'n'drop the STL asset [here](https://sandbox.babylonjs.com/)? How is it rendered?

**Comment by ShtiviGrin** [comment] 2022-04-28 08:45
@Mugen87 

With Chrome Canary I get the same buggy result.
But on that link you sent me it's working.

**Comment by ShtiviGrin** [comment] 2022-04-28 08:46
@Mugen87 

With Chrome Canary I get the same buggy result.
But on that link you sent me it's working.

**Comment by Mugen87** [comment] 2022-04-28 08:50
Just for testing: Can you please replace the following line:
```js
const material = new THREE.MeshPhongMaterial({ color: 0xaaaaaa, specular: 0x111111, shininess: 200 })
```
with an unlit material. Something like:
```js
const material = new THREE.MeshBasicMaterial({ color: 0xaaaaaa })
```
Any improvements?

**Comment by ShtiviGrin** [comment] 2022-04-28 09:45
![image](https://user-images.githubusercontent.com/69106412/165725573-bd6af512-d254-401a-8e35-621560af3ad4.png)
well that's better... but it doesn't have all the details

**Comment by Mugen87** [comment] 2022-04-28 09:49
How does it look like with `MeshLambertMaterial`?

**Comment by ShtiviGrin** [comment] 2022-04-28 09:59
You are a genius my friend. Thank you so much!

**Comment by Mugen87** [comment] 2022-04-28 10:10
How does the rendering now look like?

**Comment by ShtiviGrin** [comment] 2022-04-28 11:04
Perfect

![image](https://user-images.githubusercontent.com/69106412/165738633-5fb7b912-81d9-4bfa-9263-5884e0fdc302.png)

**Comment by Mugen87** [comment] 2022-04-28 11:12
I wonder why it does not work with phong and PBR materials on your system🤔 .

**Comment by ShtiviGrin** [comment] 2022-04-28 11:34
No idea to be honest

**Comment by ShtiviGrin** [comment] 2022-04-28 12:35
@Mugen87 Ok I don't know what's happening, but now it's messed up once again. I didn't change anything in the code, so it's very weird.

**Comment by Mugen87** [comment] 2022-04-28 15:23
Sorry, I have no idea what's going on.

**Comment by Mugen87** [comment] 2022-04-28 15:23
Closing. This seems to be a device related issue.

**Closed by Mugen87** 2022-04-28 15:23 UTC
Labels: Browser Issue

**Comment by tilli** [comment] 2022-05-19 19:44
Bumped into similar today after upgrading from r112 to r140. r118 had switched to use WebGL2Renderer by default and that seemed to cause problems with MacOS + Chrome, although Safari worked fine. Chrome started working after I changed my code to use WebGL1Renderer.

**Comment by mrdoob** [comment] 2022-05-20 06:51
@tilli Sounds like a Chrome bug, no?

**Comment by tilli** [comment] 2022-05-20 07:22
Yep, seems so

**Comment by Mugen87** [comment] 2022-07-31 21:01
In the meanwhile, there is a Chromium bug tracking this issue:

https://bugs.chromium.org/p/chromium/issues/detail?id=1321452

**Comment by stewartoallen** [comment] 2022-07-31 21:32
thanks for linking the issues. please up-vote the chromium bug. around Mac OS 11.6.4 something changed that broke rendering in Chromium on Intel Macs. doesn't affect other browsers, architectures, or OS.

**Comment by LeviPesin** [comment] 2022-08-01 09:02
Is it a duplicate of https://bugs.chromium.org/p/chromium/issues/detail?id=1301748?

**Comment by Mugen87** [comment] 2022-08-01 09:16
Looks like the same problem.
