### ISSUE TITLE
GLTF loader, skinned meshes, cloning

### ISSUE THREAD

**Issue by Usnul** [mrdoob/three.js#14439] opened 2018-07-10 12:39 UTC
if you load a gltf model with some skinned animation and then try to clone that mesh - you will find yourself in a bit of a pickle!

Skinned geometry loaded with GLTF has no "bones" property, which is expected by "SkinnedMesh", see:
https://github.com/mrdoob/three.js/blob/17264b950a70d7c9db097c03797b6be77adf94b3/src/objects/SkinnedMesh.js#L38-L47

so you'll end up with a skinned mesh, alright, but your character will have no spine! ..or any other bones for that matter. From my experience - the mesh will not render at all as a result.

**Comment by Mugen87** [comment] 2018-07-10 13:19
That's a duplicate of #11573 and #11574

**Closed** 2018-07-10 13:20 UTC
Labels: Duplicate
