### ISSUE TITLE
Clipping plane artifacts in Mac Chrome browser

### ISSUE THREAD

**Issue by Omxjep3433** [mrdoob/three.js#25764] opened 2023-04-03 13:32 UTC
### Description

There are artifacts when using clipping planes in the Mac Chrome browser. I do not see this issue in Safari. I presume this issue always occurs, but it is easiest to see when some parts of the object are transparent. In my JSFiddle example, I am using a very simple alpha map so that the left and right edges of the plane have 0 opacity. In the Mac Chrome browser, you will see very thin lines where the clipping planes exist. If the artifacts aren't visible initially in the JSFiddle example, try resizing the JSFiddle viewport until the artifacts become visible.

Three JS version: 0.151.2
Chrome version: Version 111.0.5563.146 (Official Build) (arm64) 
Computer: Macbook Air M1 (2020)

### Reproduction steps

1. Create a mesh with a plane geometry
2. Assign an alpha map such that the edges of the object have 0 opacity. The same effect can be seen when using a fragment shader where the alpha channel is 0 near the edges of the object. My use case is using clipping planes with MSDF text, but I am using a plane mesh in my example for simplicity.
3. Create clipping planes in the material near the edges of the mesh

### Code

```js
const planeGeometry = new THREE.PlaneGeometry(1, 1);
const material = new THREE.MeshBasicMaterial({
  color: 0x000000,
  transparent: true
});

const plane = new THREE.Mesh(planeGeometry, material);

material.clippingPlanes = [
  new THREE.Plane(new THREE.Vector3(-1, 0, 0), 0.5),
  new THREE.Plane(new THREE.Vector3(1, 0, 0), 0.5),
  new THREE.Plane(new THREE.Vector3(0, -1, 0), 0.5),
  new THREE.Plane(new THREE.Vector3(0, 1, 0), 0.5),
];

// The alpha map below is very simple. It has white edges with a black center so the edges of the mesh have 0 opacity.
new THREE.TextureLoader().load("https://iili.io/HOxtH9s.png", texture => {
  material.alphaMap = texture;
  material.needsUpdate = true;
});
```

### Live example

https://jsfiddle.net/y9s3vgj8/1/

### Screenshots

![image](https://user-images.githubusercontent.com/129760192/229524890-03664a64-3f12-4d29-bb62-51950b58a3ca.png)

### Version

r0.151.2

### Device

Desktop

### Browser

Chrome

### OS

MacOS

**Comment by Mugen87** [comment] 2023-04-03 13:46
It seems this is a duplicate of #21571.

**Comment by SeanPeplinski** [comment] 2023-04-03 17:40
I wanted to share some findings with my particular issue. It seems that this issue has something to do with the interaction between texture sampling and discard statements, which are found in THREE's clipping planes snippet. It seems that textures are sampled incorrectly after a fragment is discarded, which causes these hairline artifacts.

I am able to solve my issue above with the following change to shader compilation:
```
// Moving the clipping planes snippet to be after the snippet where the alpha map is sampled.
material.onBeforeCompile = shader => {
  shader.fragmentShader = shader.fragmentShader.replace(
    "#include <clipping_planes_fragment>",
    ""
  );

  shader.fragmentShader = shader.fragmentShader.replace(
    "#include <alphamap_fragment>",
    `
      #include <alphamap_fragment>
      #include <clipping_planes_fragment>
    `
  );
};
```

Note that this modification is bad for performance since the shader will be executing code for fragments that are going to be discarded. If used in production, you would want to set a 'define' and execute conditionally for Mac Chrome browsers.

This solution would need to be modified a bit for other use cases not using an alpha map. For example, I had clipping plane artifacts when clipping MSDF text. I was able to solve the issue by sampling the font texture before the clipping planes snippet.

**Comment by Omxjep3433** [comment] 2023-04-03 17:41
I wanted to share some findings with my particular issue. It seems that this issue has something to do with the interaction between texture sampling and discard statements, which are found in THREE's clipping planes snippet. It seems that textures are sampled incorrectly after a fragment is discarded, which causes these hairline artifacts.

I am able to solve my issue above with the following change to shader compilation:
```
// Moving the clipping planes snippet to be after the snippet where the alpha map is sampled.
material.onBeforeCompile = shader => {
  shader.fragmentShader = shader.fragmentShader.replace(
    "#include <clipping_planes_fragment>",
    ""
  );
  shader.fragmentShader = shader.fragmentShader.replace(
    "#include <alphamap_fragment>",
    `
      #include <alphamap_fragment>
      #include <clipping_planes_fragment>
    `
  );
};
```

Note that this modification is bad for performance since the shader will be executing code for fragments that are going to be 
discarded. If used in production, you would want to set a 'define' and execute conditionally for Mac Chrome browsers.

This solution would need to be modified a bit for other use cases not using an alpha map. For example, I had clipping plane artifacts when clipping MSDF text. I was able to solve the issue by sampling the font texture before the clipping planes snippet.

**Comment by Mugen87** [comment] 2023-04-03 17:47
I can't reproduce the issue on my mac mini. Can you please test if the issue also goes away if you set the `minFilter` and `magFilter` texture properties to the value `THREE.NearestFilter`?

**Comment by Omxjep3433** [comment] 2023-04-03 17:55
Interesting, that indeed also fixes the issue.

**Comment by Mugen87** [comment] 2023-04-03 17:58
I guess the glitches are caused by inaccuracies during the texture filtering process. Since this is a WebGL internal issue, we are not going to change something in the engine.

**Closed by Mugen87** 2023-04-03 17:58 UTC
