### ISSUE TITLE
MorphTargets support on Lines

### ISSUE THREAD

**Issue by araid** [mrdoob/three.js#4209] opened 2013-12-13 21:46 UTC
Since the Line constructor takes the same Geometry as Mesh, it feels a bit of a waste that morph targets are not supported, and morphTargetInfluences not available. It would be very useful to move and morph lines without losing the original vertex positions.

Is this feature on the roadmap? Otherwise I'd like to ask for the recommended approach to achieve this. Thanks!

**Comment by looeee** [comment] 2016-12-16 12:45
Duplicate of #2875

**Closed** 2017-04-07 19:40 UTC
Labels: Enhancement
