### ISSUE TITLE
Typescript first compile fails, "Cannot find name 'OffscreenCanvas'"

### ISSUE THREAD

**Issue by Alexithemia** [mrdoob/three.js#17698] opened 2019-10-09 13:37 UTC
ERROR in node_modules/three/src/renderers/WebGLRenderer.d.ts(34,31): error TS2304: Cannot find name 'OffscreenCanvas'.

Three version 0.109.0

Written in Typescript, module declared in typings.d.ts.

import * as THREE from 'three';

using MeshPhongMaterial, SphereGeometry, TorusGeometry, Geometry, and Mesh.

Fails first compile, recompiling still shows error but works as expected.

**Comment by Mugen87** [comment] 2019-10-09 14:33
@yiyix Any ideas about this issue?

**Comment by Mugen87** [comment] 2019-10-10 09:51
Well, adding [@types/offscreencanvas](https://www.npmjs.com/package/@types/offscreencanvas) to the project seems to solve the issue.

see https://discourse.threejs.org/t/webglrenderer-d-ts-error-after-update-to-r109/10106

**Comment by yiyix** [comment] 2019-10-10 10:48
Sorry about it. OffscreenCanvas is added to TypeScript last year. I am glad
the issue is solved now.

**Comment by jnuricumbo** [comment] 2019-10-10 10:50
I get the same error with r109, adding @types/offscreencanvas solve the issue, but now the question is, everyone using typescript should install that package only because of that type?

**Comment by Mugen87** [comment] 2019-10-10 11:05
> OffscreenCanvas is added to TypeScript last year. I am glad the issue is solved now.

Um, are you sure about that? It seems many devs having issues since `OffscreenCanvas` is used in `WebGLRenderer.d.ts`...

**Comment by NicolasRannou** [comment] 2019-10-10 11:43
@Alexithemia which version of TS are you using?

**Comment by Mugen87** [comment] 2019-10-12 11:28
It seems this problems occurs even with latest TS `npm` package `3.6.4`.

https://discourse.threejs.org/t/webglrenderer-d-ts-error-after-update-to-r109/10106/6?u=mugen87

**Comment by Mugen87** [comment] 2019-10-13 10:12
This issue is somewhat complicated since we can't make everyone happy. If we revert #17571, devs won't be able to pass `OffscreenCanvas` to `WebGLRenderer` anymore. However, it's then necessary to install `@types/offscreencanvas` or `typescript@next` until the actual TS package natively supports `OffscreenCanvas`. Not sure we want to force all TS users to do so.

Right now, I tend to revert the PR since more devs are complaining than benefiting from this change. 

@mrdoob Are you okay with that?

**Comment by mrdoob** [comment] 2019-10-14 13:06
I think it would be better to install `@types/offscreencanvas`.

**Comment by Mugen87** [comment] 2019-10-14 14:43
Okay. After all it should be only a temporary issue. And applying the additional dependency is easy done. Closing for now.

**Closed by Mugen87** 2019-10-14 14:43 UTC

**Comment by Xakaloz** [comment] 2019-10-17 12:30
Hello,
Installing the `@types/offscreencanvas` package doesn't solve the error for me.
I am using Typescript 3.6.2 and  three 0.109.0.
Any solution without touching at the node packages files ?
Thank you.

**Comment by Xakaloz** [comment] 2019-10-17 12:44
> Hello,
> Installing the `@types/offscreencanvas` package doesn't solve the error for me.
> I am using Typescript 3.6.3 and Three 0.109.0.
> Any solution without touching at the node packages files ?
> Thank you.

Erratum: my VSCode was using Typescript 3.6.3 BUT the typescript version in my package.json is 3.4.3.
It's a Ionic 4 projet with Angular 8 and I cannot update typescript to 3.6.3...

**Comment by Xakaloz** [comment] 2019-10-17 13:59
Fixed the issue upgrading Angular 8.1.2 to 8.2.11, supporting Typescript 3.5.3.

**Comment by George35mk** [comment] 2019-11-12 13:35
In my case, I am building a library that uses the Three.js and I get the same warning and I solved with these steps.



### tsconfi.lib/json

```json
{
  "extends": "../../tsconfig.json",
  "compilerOptions": {
    "outDir": "../../out-tsc/lib",
    "target": "es2015",
    "declaration": true,
    "inlineSources": true,
    "types": ["webgl2", "offscreencanvas"],  <--------- here
    "lib": [
      "dom",
      "es2018"
    ]
  },
  "angularCompilerOptions": {
    "annotateForClosureCompiler": true,
    "skipTemplateCodegen": true,
    "strictMetadataEmit": true,
    "fullTemplateTypeCheck": true,
    "strictInjectionParameters": true,
    "enableResourceInlining": true
  },
  "exclude": [
    "src/test.ts",
    "**/*.spec.ts"
  ]
}
```

The `webgl2` inside the types solves this warning.

```console
ERROR: node_modules/three/src/renderers/webgl/WebGLUtils.d.ts(3,43): error TS2304: Cannot find name 'WebGL2RenderingContext'.
```


And the  `offscreencanvas` inside the types solve this warning.

```console
ERROR: node_modules/three/src/renderers/WebGLRenderer.d.ts(35,31): error TS2304: Cannot find name 'OffscreenCanvas'.
```

**Comment by PickleProgramming** [comment] 2020-01-16 04:56
I got this issue as well, however when I installed `@types/offscreencanvas` my `tsc` command started spitting this out:
```
node_modules/@types/offscreencanvas/index.d.ts(16,53): error TS2304: Cannot find name 'CanvasState'.
node_modules/@types/offscreencanvas/index.d.ts(16,66): error TS2304: Cannot find name 'CanvasTransform'.
node_modules/@types/offscreencanvas/index.d.ts(16,83): error TS2304: Cannot find name 'CanvasCompositing'.
node_modules/@types/offscreencanvas/index.d.ts(17,5): error TS2304: Cannot find name 'CanvasImageSmoothing'.
node_modules/@types/offscreencanvas/index.d.ts(17,27): error TS2304: Cannot find name 'CanvasFillStrokeStyles'.
node_modules/@types/offscreencanvas/index.d.ts(17,51): error TS2304: Cannot find name 'CanvasShadowStyles'.
node_modules/@types/offscreencanvas/index.d.ts(17,71): error TS2304: Cannot find name 'CanvasFilters'.
node_modules/@types/offscreencanvas/index.d.ts(17,86): error TS2304: Cannot find name 'CanvasRect'.
node_modules/@types/offscreencanvas/index.d.ts(17,98): error TS2304: Cannot find name 'CanvasDrawPath'.
node_modules/@types/offscreencanvas/index.d.ts(18,5): error TS2304: Cannot find name 'CanvasText'.
node_modules/@types/offscreencanvas/index.d.ts(18,34): error TS2304: Cannot find name 'CanvasImageData'.
node_modules/@types/offscreencanvas/index.d.ts(18,51): error TS2304: Cannot find name 'CanvasPathDrawingStyles'.
node_modules/@types/offscreencanvas/index.d.ts(18,76): error TS2304: Cannot find name 'CanvasTextDrawingStyles'.
node_modules/@types/offscreencanvas/index.d.ts(18,101): error TS2304: Cannot find name 'CanvasPath'.
node_modules/@types/offscreencanvas/index.d.ts(34,53): error TS2304: Cannot find name 'CanvasRenderingContext2DSettings'.
node_modules/@types/offscreencanvas/index.d.ts(36,90): error TS2304: Cannot find name 'ImageBitmapRenderingContext'.
node_modules/@types/offscreencanvas/index.d.ts(49,22): error TS2304: Cannot find name 'CanvasImageSource'.
node_modules/@types/offscreencanvas/index.d.ts(51,22): error TS2304: Cannot find name 'CanvasImageSource'.
node_modules/@types/offscreencanvas/index.d.ts(53,22): error TS2304: Cannot find name 'CanvasImageSource'.
node_modules/@types/offscreencanvas/index.d.ts(58,43): error TS2304: Cannot find name 'ImageBitmapSource'.
node_modules/@types/offscreencanvas/index.d.ts(59,43): error TS2304: Cannot find name 'ImageBitmapSource'.
node_modules/@types/offscreencanvas/index.d.ts(64,48): error TS2304: Cannot find name 'Transferable'.
node_modules/@types/offscreencanvas/index.d.ts(68,48): error TS2304: Cannot find name 'Transferable'.
node_modules/@types/offscreencanvas/index.d.ts(72,48): error TS2304: Cannot find name 'Transferable'.
node_modules/@types/offscreencanvas/index.d.ts(76,26): error TS2304: Cannot find name 'WindowOrWorkerGlobalScope'.
node_modules/@types/offscreencanvas/index.d.ts(76,53): error TS2304: Cannot find name 'WindowEventHandlers'.
node_modules/@types/offscreencanvas/index.d.ts(77,70): error TS2304: Cannot find name 'Transferable'.
node_modules/@types/offscreencanvas/index.d.ts(80,83): error TS2304: Cannot find name 'Transferable'.
node_modules/three/src/renderers/webvr/WebVRManager.d.ts(13,15): error TS2304: Cannot find name 'VRDisplay'.
node_modules/three/src/renderers/webvr/WebVRManager.d.ts(14,21): error TS2304: Cannot find name 'VRDisplay'.
```
Here is my `package.json`
```
{
  "name": "pickle.codes",
  "version": "1.0.0",
  "description": "this is my web server :)",
  "private": true,
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [
    "pickle",
    "tesseract",
    "web server"
  ],
  "author": "Matthew Pickle",
  "license": "MIT",
  "dependencies": {},
  "devDependencies": {
    "@babel/core": "^7.8.3",
    "@babel/preset-env": "^7.8.3",
    "@types/gsap": "^1.20.2",
    "@types/offscreencanvas": "^2019.6.1",
    "@types/three": "^0.103.2",
    "babelify": "^10.0.0",
    "bootstrap": "^4.4.1",
    "browserify": "^16.5.0",
    "fancy-log": "^1.3.3",
    "gsap": "^3.0.5",
    "gulp": "^4.0.2",
    "gulp-autoprefixer": "^7.0.1",
    "gulp-babel": "^8.0.0-beta.2",
    "gulp-cssnano": "^2.1.3",
    "gulp-rename": "^2.0.0",
    "gulp-sass": "^4.0.2",
    "gulp-sourcemaps": "^2.6.5",
    "gulp-tap": "^2.0.0",
    "gulp-typescript": "^6.0.0-alpha.1",
    "gulp-uglify-es": "^2.0.0",
    "jquery": "^3.4.1",
    "three": "^0.110.0",
    "tsify": "^4.0.1",
    "typescript": "^3.7.4",
    "vinyl-buffer": "^1.0.1",
    "vinyl-source-stream": "^2.0.0"
  }
}

```

and my `tsconfig.json`:
```
{
	"compilerOptions": {
		"module": "commonjs",
		"target": "es2015",
		"declaration": true,
		"noImplicitAny": true,
		"removeComments": true,
		"preserveConstEnums": true,
		"types": [
			"webgl2",
			"offscreencanvas"
		],
		"lib": [
			"DOM",
			"ES2015",
			"ES2016",
			"ES2018",
			"ES2015.Iterable",
			"esnext"
		],
		"outDir": "dist/js/projects"
	},
	"file": [
		"src/js/projects/tesseract/main.js"
	]
}
```
