### ISSUE TITLE
Model transmission appears to break since v0.145 (w/ react-three-fiber)

### ISSUE THREAD

**Issue by Monstarrrr** [mrdoob/three.js#24799] opened 2022-10-14 15:28 UTC
Model transmission breaks since v0.145, the model's material containing transmission becomes black/dark and doesn't reflect light.

1. Go to [![Edit ThreeJS_Transmission-breaks-v0.145_MRE](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/threejs-transmission-breaks-v0-145-mre-z556yu?fontsize=14&hidenavigation=1&theme=dark)
2. Change ``three``'s version between ``v0.145`` and ``v0.144``
3. Observe the model

The model should look the same as in ``v0.144`` and reflect lights properly.

Working transmission (``v0.144``):  
![Working transmission](https://user-images.githubusercontent.com/31903668/195883546-b5e58c45-e6e3-4dee-8219-1ace5b30e2df.png)

Broken transmission (``v0.145``):  
![Broken transmission](https://user-images.githubusercontent.com/31903668/195883294-d0b8ba9b-d6c6-4f9c-adda-9c2023b17dd6.png)

**Platform:**

 - Device: [Desktop, Mobile]
 - OS: Windows
 - Browser: [Chrome, Firefox]
 - Three.js version: 0.145

**Comment by Mugen87** [comment] 2022-10-14 15:43
Do you mind posting this at the `react-three-fiber` first? If it turns out to be an issue in the engine, we can reopen the issue.

It would be then good to reproduce the glitch without `react-three-fiber`.  E.g. my modifying https://threejs.org/examples/webgl_loader_gltf_transmission and provide it as a codesandbox.

**Comment by CodyJasonBennett** [comment] 2022-10-14 15:43
Can you continue in https://github.com/pmndrs/three-stdlib? Nothing to do with R3F BTW. If you were to create a minimal example, you'd find that using GLTFLoader from three to work without issue.

**Comment by CodyJasonBennett** [comment] 2022-10-14 15:50
FWIW, this was fixed in three itself in https://github.com/mrdoob/three.js/pull/24622, I'll mirror this in three-stdlib.

**Closed** 2022-10-14 15:50 UTC
