### ISSUE TITLE
Cannot clone THREE.Line which geometry is type of THREE.Geometry

### ISSUE THREAD

**Issue by cnstoba** [mrdoob/three.js#15426] opened 2018-12-13 10:45 UTC
Right now you cannot clone a THREE.Line when it's geometry attribute is a type of THREE.Geometry.

This is because the clone method calls the constructor without parameters so that the new line's geometry attribute will be constructed as a THREE.BufferGeometry by default. Then the copy method tries to copy a THREE.Geometry object into a THREE.BufferGeometry, which doesn't work.

So shouldn't the clone method look like the one in THREE.Mesh ? meaning:

`clone: function () {

     return new this.constructor(this.geometry, this.material).copy( this );

}`

[This](https://jsfiddle.net/8no92gha/) fiddle shows the error:
    

I don't know but maybe this kind of problem could exist at other places too.

##### Three.js version

- [x] Dev
- [ ] r99
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment] 2018-12-13 11:38
I think this is a duplicate of #15239 and #15064

**Closed** 2018-12-19 12:37 UTC
Labels: Duplicate

**Comment by tooleks** [comment] 2019-03-26 16:04
@Mugen87 

What is the solution? Fiddle from `master` branch still doesn't work: https://jsfiddle.net/dc5fb0x9/.

```
TypeError: index is undefined
```

**Comment by Mugen87** [comment] 2019-03-26 16:31
This is already fixed in `dev`, see https://jsfiddle.net/62s8gxqp/

Will be available with the next release `R103`.

**Comment by tooleks** [comment] 2019-03-26 16:35
Great! Thanks.

Here is a workaround until next release.

```
/**
 * @returns {Line}
 */
function cloneLine() {
  return new this.constructor(this.geometry, this.material).copy(this);
}

const line = new THREE.Line(lineGeometry, lineMaterial);
line.clone = cloneLine;

line.clone();
```
