### ISSUE TITLE
Cannot read properties of undefined (reading 'traverse')

### ISSUE THREAD

**Issue by rubeniskov** [mrdoob/three.js#26727] opened 2023-09-10 21:49 UTC
### Description

There is a bug when doing traverse if using "removeFromParent" or any mutation operation inside the callback function produces an error "Cannot read properties of undefined (reading 'traverse')" because the children array is decreasing the number of items and loop is taking a length variable instead of the actual length property.

```tsx
collider.traverse((node) => {
  if (/^ceil/.test(node.userData.name)) {
    node.removeFromParent();
  }
});
```

Alternatively it can be done like this but less efficient

```tsx
const nodes: Object3D<Event>[] = [];

collider.traverse((node) => {
    if (/^ceil/.test(node.name)) {
      nodes.push(node);
    }
});

nodes.forEach((node) => {
    node.removeFromParent();
});

```

### Reproduction steps

1. Do a traverse
2.  perform a "node.removeFromParent();"
3. Then gets the error

### Code

```js
collider.traverse((node) => {
  if (/^ceil/.test(node.userData.name)) {
    node.removeFromParent();
  }
});
```

### Live example

https://codesandbox.io/s/awesome-rosalind-5hjwx4?file=/src/Stage.tsx

### Screenshots

https://github.com/mrdoob/three.js/assets/6261914/5833fbe8-691c-48fa-aafb-4645b0f1db8f

### Version

r0.155

### Device

Desktop

### Browser

Chrome

### OS

MacOS

**Comment by alone-as-a-god** [comment] 2023-09-11 07:20
The documentation states that it is strongly discouraged to modify the scene graph in the .traverse function.
Since I've had similar issues in the past the way I worked around this was by creating an Object3D Array and then using the traverse function to push objects into that array.
After this just traverse the array and update your objects there.

Not 100% sure if that's the best option but it's the easiest workaround I could think of.

**Comment by gkjohnson** [comment] 2023-09-11 09:46
This could be addressed by making a copy of the child array before iterating over it but it's unnecessary and even then I don't know what the proper expected behavior would be. If you remove a child it would still be traversed over (but only sometimes depending on where in the hierarchy it was removed) etc. I think any change here would make the function behavior confusing in the case of a modified heirarchy.

The docs already discourage modifying the object hierarchy in all traversal functions which is the right thing do to, in my opinion.

> Note: Modifying the scene graph inside the callback is discouraged.

The performance impact of pushing to an array should be negligible and If users need a different behavior they can implement their own functionality.

**Comment by rubeniskov** [comment] 2023-09-12 00:43
I understand the implications of changing the behavior of this traverse function, considering its crucial role both in the library itself and in third-party libraries.

In my case, I was working with models that had a large number of nodes, where the grouping of certain elements, such as ceilings, had a large number of nested elements. Therefore, continuing to iterate over them was not necessary.

As you all mention, an external utility can be created for this case since it involves trivial logic.

**Closed** 2023-09-12 06:33 UTC
