### ISSUE TITLE
Raycaster does seem to work on the basis of the first key frame of animation all the time.

### ISSUE THREAD

**Issue by hotohoto** [mrdoob/three.js#6548] opened 2015-05-12 07:47 UTC

**Comment by WestLangley** [comment] 2015-05-12 10:03
Can you provide a test case, along with the information requested in "How to report a bug" in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md)?

**Comment by RemusMar** [comment] 2015-05-12 10:03
Yes, that's true (and annoying).
But the current approach speeds up the things a lot.
The bones matrices are computed by the CPU, but the new vertex positions are computed by GPU.
So the CPU has access to the first pose only.
That's why RayCasting does not work for skinned meshes.

**Comment by RemusMar** [comment] 2015-05-12 10:08
> Can you provide a test case

http://necromanthus.com/Test/html5/testA.html 
Check out the "walking girl" (the legs area).
The animation is ignored by the RayCaster.
Only the initial pose gets into count.

**Comment by RemusMar** [comment] 2015-05-12 10:12
The initial pose for a skinned mesh is the equivalent of:
mesh.material.skinning = false;

**Comment by WestLangley** [comment] 2015-05-12 10:47
Oh, I see. I misread the title of the post. 

Thank you @RemusMar for the clarification.

Yes, you will have to update the positions on the CPU side as-needed when raycasting.

Perhaps a `SkinnedMesh.prototype.raycast()` method would be appropriate.

**Comment by hotohoto** [comment] 2015-05-14 05:25
Thanks for your advises and I'll check them out.
I agree that I'll have to read the "How to report a bug" page in guidelines, too.
:-D

**Comment by Mugen87** [comment] 2018-08-16 18:08
Duplicate of #6440

**Closed by Mugen87** 2018-08-16 18:08 UTC
