### ISSUE TITLE
Path/Shape subdivision issue

### ISSUE THREAD

**Issue by cgabard** [mrdoob/three.js#7916] opened 2016-01-05 16:53 UTC
Hello, I have an issue with path/shape subdivision of curved path. I use r73 and the issue is not linked to a specific browser version or graphic card, pure JS issue.

I try to draw an half circle with Shape and absarc. Here is a minimal example with few curveSegments: http://jsfiddle.net/kvpbmw5d/

Everything happens as the last segment is missing. Here is an updated example where the last point of the arc is draw : http://jsfiddle.net/cxx6nrLt/

Logically the subdivision should create point to this arc end. The current behavior is very strange. 

Maybe I can do a patch if needed.

**Comment by WestLangley** [comment] 2016-01-05 17:48
Correct. It appears that `shape.createPointsGeometry( n );` and `shape.createSpacedPointsGeometry( n );` do not sample from the entire arc -- or omit the last segment.

>Maybe I can do a patch if needed.

Please do. : - )

In your fiddle, use `LineBasicMaterial` for lines.

/ping @zz85

**Comment by cgabard** [comment] 2016-01-06 14:39
``createSpacedPointsGeometry`` does the right job, it is only ``createPointsGeometry`` that have a strange behavior. 

In fact, I made a mistake. It is not the last segment that is not draw but the first one. The current ``Shape.getPoints`` function made the assumption that the first point is already made by a previous drawing element.

Then my example can be easily corrected to have the correct shape. I think the assumption is strange and error prone but I do not know how canvas work with this kind of shape.

**Comment by WestLangley** [comment] 2016-01-06 16:32
>The current Shape.getPoints function made the assumption that the first point is already made by a previous drawing element.

That is not exactly it. Your sequence of draws were not connected. You could have drawn your arc starting from the opposite end: http://jsfiddle.net/kvpbmw5d/1/

Or, as you said, set a different start point: http://jsfiddle.net/kvpbmw5d/2/

Related: http://stackoverflow.com/questions/28008608/why-cant-i-draw-a-complete-circle-with-arc-in-three-js

**Comment by WestLangley** [comment] 2019-10-18 01:02
@Mugen87 Does this appear to be resolved to you?

**Comment by Mugen87** [comment] 2019-10-18 09:57
The sampling logic of `getPoints()` and `getSpacedPoints()` is still different because how `CurvePath.getPoints()` is implemented: see http://jsfiddle.net/x7ge1cdf/

`CurvePath.getPoints()` ensures a minimal resolution for certain curves so the given `divisions` might be overwritten with a higher value. So the result of the subdivision still might vary, however it's the intended result and not an unexpected behavior.

Hence, I would close the issue for now. If more devs are going to complain, we can revisit the issue at any time.

**Comment by WestLangley** [comment] 2019-10-18 15:55
@Mugen87 Referring specifically to the apparent issue here, there are currently no "missing segments". Right?

**Comment by Mugen87** [comment] 2019-10-18 17:02
Correct. As far as I can see, the amount of segment corresponds to the expected value. In my fiddle ten for `getPoints()` and five (the value of `n_subs`)  for `getSpacedPoints()`.

**Comment by WestLangley** [comment] 2019-10-18 17:17
>Everything happens as the last segment is missing.
>In fact, I made a mistake. It is not the last segment that is not draw but the first one. The current Shape.getPoints function made the assumption that the first point is already made by a previous drawing element.

@Mugen87 I think we are not on the same page... I interpret "missing segments" to mean the arc is not complete.

**Comment by Mugen87** [comment] 2019-10-20 10:18
> I interpret "missing segments" to mean the arc is not complete.

Okay, I see. When inspecting the fiddles of the OP, I can't reproduce the reported issue anymore. The shape is closed due to the `shape.lineTo(0, 0);` call. If I remove this line, I get the expected half circle.

It seems that with older versions of `three.js` a bit of the half circle was missing. So it appears the issue is resolved.

**Closed by Mugen87** 2019-10-20 10:18 UTC
