### ISSUE TITLE
Editor Scene Export, Image URLs Missing

### ISSUE THREAD

**Issue by fraguada** [mrdoob/three.js#6004] opened 2015-01-30 08:16 UTC
I think this is by design, but it would be nice that the Scene exported from the Editor would also include map URLs in the JSON.  Since the editor spits out the JSON, it would make sense why the URLs are not included (the maps are not downloaded).  I am using the editor to help 'reverse-engineer' the 4.3 scene format (get examples of different scenes, how different objects show up in the JSON, etc) and I noticed if I give a map to an object's material, this does not show up in the material in the generated JSON.

**Comment by mrdoob** [comment] 2015-02-05 01:45
Yeah, this hasn't been implemented yet...

**Comment by Mugen87** [comment] 2018-09-10 18:07
This issue is actually a duplicate of #4365

**Closed by Mugen87** 2018-09-10 18:07 UTC
Labels: Feature Request
