### ISSUE TITLE
ShapePath cut holes in wrong shape plane

### ISSUE THREAD

**Issue by PavelTkachuk** [mrdoob/three.js#20854] opened 2020-12-08 10:44 UTC
**Describe the bug**

ShapePath makes holes in wrong shape plane if shapes added in specific order.

**To Reproduce**

Create ShapePath as described below

***Code***

```js
const shape = new THREE.ShapePath();

    shape.moveTo(0, 0);
    shape.lineTo(0, 9);
    shape.lineTo(8, 9);
    shape.lineTo(8, 0);
    shape.currentPath.closePath();

    shape.moveTo(1, 1);
    shape.lineTo(7, 1);
    shape.lineTo(7, 5);
    shape.lineTo(1, 5);
    shape.currentPath.closePath();

    shape.moveTo(3, 2);
    shape.lineTo(3, 4);
    shape.lineTo(5, 4);
    shape.lineTo(5, 2);
    shape.currentPath.closePath();

    shape.moveTo(4, 3);
    shape.lineTo(5, 3);
    shape.lineTo(5, 4);
    shape.lineTo(4, 4);
    shape.currentPath.closePath();

    shape.moveTo(1, 6);
    shape.lineTo(7, 6);
    shape.lineTo(7, 8);
    shape.lineTo(1, 8);
    shape.currentPath.closePath();


    const shapes = shape.toShapes();
    const geometry = new THREE.ExtrudeBufferGeometry(shapes, {
      depth: 1,
      bevelEnabled: false,
    });
    const material = new THREE.MeshPhongMaterial({ color: 0xb0b0b0});
    const mesh = new THREE.Mesh(geometry, material);
   
    scene.add( mesh );
```

***Live example***

* [jsfiddle-latest-release](https://jsfiddle.net/4rfsqp75/)

**Expected behavior**

Hole should be in correct shape plane

**Screenshots**

Shape adding order:
![1](https://user-images.githubusercontent.com/13413484/101473792-f5456780-3952-11eb-898a-91ac20984217.png)
Expected result:
![2](https://user-images.githubusercontent.com/13413484/101473795-f5ddfe00-3952-11eb-8fa5-024329efc5e8.png)
Actual result:
![3](https://user-images.githubusercontent.com/13413484/101473797-f6769480-3952-11eb-856a-abe568fe9180.png)

**Platform:**

 - Device: [Desktop]
 - OS: [Windows]
 - Browser: [Chrome]
 - Three.js version: [latest release]

**Comment by PavelTkachuk** [comment] 2020-12-08 12:40
Issue seems to be in "ambiguous" flag:
https://github.com/mrdoob/three.js/blob/dev/src/extras/core/ShapePath.js#L242
This flag applied to all holes, but probably should be set to each hole individually. This part should be changed too:
https://github.com/mrdoob/three.js/blob/dev/src/extras/core/ShapePath.js#L264

**Comment by mrdoob** [comment] 2020-12-08 16:18
Would you like to do a PR with the change?

**Comment by PavelTkachuk** [comment] 2020-12-08 16:58
yep, I'll do it soon

**Comment by Mugen87** [comment] 2020-12-10 10:49
This is also a duplicate of #16950.

**Closed by Mugen87** 2020-12-10 10:49 UTC
