### ISSUE TITLE
new THREE.DataTexture() width 'format = THREE.LuminanceFormat'  'type = THREE.UnsignedByteType'   but not working,

### ISSUE THREAD

**Issue by Ghfjj** [mrdoob/three.js#24081] opened 2022-05-18 08:16 UTC
**Describe the bug**
Use DataTexture to render 8-bit grayscale images using "Format = three.luminanceFormat, type = three.unsignedByteType",get an error message on the browser

***Code***

```js
var geometry = new THREE.PlaneGeometry(256, 256)
  var width = 256 
  var height = 256
  var size = width * height
  var data = new Uint8Array(size)
  for(let i = 0; i < size; i ++) {
    data[i] = i % 256
  }

var texture = new THREE.DataTexture(data, width, height);
  texture.internalFormat = 'LUMINANCE'
  texture.format = THREE.LuminanceFormat
  texture.type = THREE.UnsignedByteType
texture.needsUpdate = true

var material = new THREE.MeshPhongMaterial({
    map: texture, // 设置纹理贴图
  })


get error:
[.WebGL-00002992014D4600] GL_INVALID_ENUM: Invalid format.
[.WebGL-00002992014D4600] GL_INVALID_OPERATION: Level of detail outside of range.
```

**Expected behavior**

show a gray texture

**Screenshots**

**Platform:**

 - Device: [Desktop]
 - OS: [Windows]
 - Browser: [Chrome
 - Three.js version: [dev, r140]

**Comment by Mugen87** [comment] 2022-05-18 08:20
Duplicate of #23824.

**Closed by Mugen87** 2022-05-18 08:20 UTC

**Comment by Ghfjj** [comment] 2022-05-18 08:29
> Duplicate of #23824.

Thanks！
