### ISSUE TITLE
Clicking on the Ammo sample in the r120 does not launch the iron ball

### ISSUE THREAD

**Issue by cx20** [mrdoob/three.js#20191] opened 2020-08-26 13:58 UTC
##### Description of the problem

In the previous Ammo sample, clicking with the mouse launch an iron ball.
However, in the `r120` [sample](https://github.com/mrdoob/three.js/blob/r120/examples/physics_ammo_break.html), the iron ball does not appear when the mouse is clicked.
I tried the combination of the r120 sample and the previous version of [OrbitControls.js](https://github.com/mrdoob/three.js/blob/r119/examples/jsm/controls/OrbitControls.js) and the iron ball does appear, so I think this control is probably related.

[r120 Ammo Convex object breaking example result:](https://rawcdn.githack.com/mrdoob/three.js/r120/examples/physics_ammo_break.html)
![image](https://user-images.githubusercontent.com/1833979/91311880-8ce0d900-e7ee-11ea-960e-7196969af507.png)

[r119 Ammo Convex object breaking example result:](https://rawcdn.githack.com/mrdoob/three.js/r119/examples/physics_ammo_break.html)
![image](https://user-images.githubusercontent.com/1833979/91311849-84889e00-e7ee-11ea-9347-0c748318c1bb.png)

##### Three.js version

- [x] r120

##### Browser

- [x] Chrome
- [x] Firefox

##### OS

- [x] Windows

##### Hardware Requirements (graphics card, VR Device, ...)

MacBook Air (BootCamp) Intel(R) UHD Graphics 617 Direct3D11 vs_5_0 ps_5_0

**Comment by Mugen87** [comment] 2020-08-26 14:40
I see similar problems in the spline editor example where I can't interact with `TransformControls` anymore.

https://threejs.org/examples/webgl_geometry_spline_editor

Maybe related to the introduction of Pointer Events in `OrbitControls`.

**Comment by Mugen87** [comment] 2020-08-26 15:02
When using `OrbitControls` (r120) and you make a mouse click, a `pointerdown` event listener processes the event and calls `event.preventDefault()`. However, this call prevents the respective mouse event from being sent. Hence, any event listeners listening to `mouse` event handlers are now broken with `OrbitControls`.

Since `EditorControls` does not call `event.preventDefault()`, the controls still works with `TransformControls`. 

I guess this side effect was missed when Pointer Events were introduced. It seems we can only fix this in two ways:

- Revert the Pointer Events change.
- Remove the calls from `event.preventDefault()`.

**Comment by Mugen87** [comment] 2020-08-26 15:10
Even when removing `event.preventDefault()` from `pointerdown` and `pointermove` event listeners in `OrbitControls`, `webgl_geometry_spline_editor` is still broken 🤔 .

**Comment by Mugen87** [comment] 2020-08-26 15:25
More simple repro case:

r119: https://jsfiddle.net/jog5nqyh/
r120: https://jsfiddle.net/jog5nqyh/1/

**Comment by Mugen87** [comment] 2020-08-26 15:29
@mrdoob I suggest we revert the Pointer Events change and make `r120.1`. It seems this change has the potential to break a lot of user code.

**Comment by Mugen87** [comment] 2020-08-26 20:12
PR: #20194

**Comment by marcofugaro** [comment] 2020-08-27 10:20
> Remove the calls from `event.preventDefault()` in `OrbitControls` and `TrackballControls` from pointer event listeners (although I'm not sure about the consequences of doing this).

The `preventDefault()` on mousedown event was introduced in #15620, I don't fully understand why it was added, but probably you guys do.

I've update the broken jsfiddle of the issue with the mousedown's `preventDefault()` commented out. I can't reproduce the original issue, can you?

https://jsfiddle.net/marcofugaro/2ftxhosr/1/

**Comment by Mugen87** [comment] 2020-08-27 10:33
If when commenting out the calls of `preventDefault()`, `webgl_geometry_spline_editor` is still broken.

If we were aware that calling `preventDefault()` on a pointer event breaks the respective mouse events, I doubt the controls PRs were merged.

**Comment by Mugen87** [comment] 2020-08-27 10:35
> The preventDefault() on mousedown event was introduced in #15620, I don't fully understand why it was added, but probably you guys do.

BTW: The call of `preventDefault()` in `mousemove` was implemented earlier. And is problematic, too.

**Comment by Mugen87** [comment] 2020-08-27 10:39
As a roadmap, I suggest to revert, figure out if it's possible to remove the usage of `preventDefault()` and only then introduce Pointer Events.

**Comment by mrdoob** [comment] 2020-08-29 20:02
Fixed: https://github.com/mrdoob/three.js/commit/9f2226e76da8b80acb791866fb42f3608871271c

In fact, the iron balls never worked on mobile. Now they do.

**Closed by mrdoob** 2020-08-29 20:02 UTC
Labels: Regression

**Comment by cx20** [comment] 2020-08-30 16:16
Thanks! I have confirmed that the sample works with the updated `r120`.

[r120 Ammo Convex object breaking example](https://rawcdn.githack.com/mrdoob/three.js/r120/examples/physics_ammo_break.html).
