### ISSUE TITLE
Raycaster is not easily extendable. Can I fix?

### ISSUE THREAD

**Issue by lewibs-Powern** [mrdoob/three.js#26993] opened 2023-10-16 18:09 UTC
### Description

The raycaster right now internally uses a function that it does not export. This means that it is very difficult to extend and update the raycaster to work with external libraries such as potree. If I make a pr that makes the raycaster a little easier to maintain and also easier to extend would someone be able to take a look at that.

### Solution

I will just be removing the functions and making them work within the classes.

### Alternatives

None

**Comment by Mugen87** [comment] 2023-10-16 18:15
> This means that it is very difficult to extend and update the raycaster to work with external libraries such as potree.

Can you please describe in more detail how you would update `Raycaster` to make it "work" with external libraries? 

What exactly does not work with the unmodified version?

**Comment by lewibs-Powern** [comment] 2023-10-16 18:20
Sure I primarily was hoping to make my own version of intersectObject but what im seeing is that internally both intersectObjects and intersectObject both use the same function. Which means any updated method would need to have a full update on the raycaster.

What I would do is make a private _intersectObject that replaces the intersectObject function. This way if people need to update how the intersecting works, they are able to just change that one method.

**Comment by lewibs-Powern** [comment] 2023-10-16 18:20
If i know it will be at least looked at ill go ahead and write it and open a pr since its an easy update

**Comment by luckywangming** [comment] 2023-10-17 01:29
good

**Comment by Mugen87** [comment] 2023-10-17 09:53
> What I would do is make a private _intersectObject that replaces the intersectObject function.

Pseudo private methods are not real private so they do not fulfill the actual purpose of making something not public accessible. 

Let's consider for a moment we would add `_intersectObject()` and at some point switch to a real private method via the ECMA 2022 syntax `#intersectObject()`. Would it still be possible to overwrite such a private method definition in sub classes?

**Comment by gkjohnson** [comment] 2023-10-17 23:54
> /cc @gkjohnson three-mesh-bvh does something similar, by patching [mesh.raycast](https://github.com/gkjohnson/three-mesh-bvh#use)?

Yes that's the case - the Mesh.raycast (or any Object3D.raycast) function can be overwritten via prototype override, class extension, or per-object assignment to add custom raycasting functionality. The 3DTilesRenderer also implements [custom raycasting](https://github.com/NASA-AMMOS/3DTilesRendererJS/blob/60e0b9947835916b63af8622aebeff381d803717/src/three/TilesGroup.js#L17-L23) for hierarchical traversal this way, as well.

> it is very difficult to extend and update the raycaster to work with external libraries such as potree

The description of the problem is too vague to say whether - a proper description of what can't be done should be provided. But without more information I'd say this can already be handled in other ways.

**Comment by mrdoob** [comment] 2023-10-18 04:57
Closing for now.

**Closed by mrdoob** 2023-10-18 04:57 UTC
