### ISSUE TITLE
Documentation UX problem: middle mouse button (open link in new tab) not working in inner page links

### ISSUE THREAD

**Issue by ferrybig** [mrdoob/three.js#13951] opened 2018-04-28 19:58 UTC
This is a problem with the documentation of threejs, not threejs itself, I got redirected by the [IRC chat](https://webchat.freenode.net/?channels=three.js) by a red colored user "bai" to place this bug here.

# Steps:

1. go to https://threejs.org/docs/index.html#api/lights/DirectionalLight
2. Press middle mouse button on any link on the page, for example `DirectionalLightShadow`

# Expection:

Since it has the pointer cursor, I expect the browser to open the page on a new tab

# Reality:

The browser executes the scroll using middle mouse button interaction

# Why is this a problem

This is a problem because when new developers come to the documentation, and seeing an first impression from breaking the UX flow most people are used with, is a bad sign and encourages new people to go away.

**Comment by Mugen87** [comment] 2018-04-28 20:05
That's essentially  a duplicate of #13900, right?

**Closed** 2018-04-28 20:07 UTC
Labels: Documentation

**Comment by ferrybig** [comment] 2018-04-28 20:09
@Mugen87 The only difference is that I'm reporting it as a bug instead of a suggestion, as it deviates from the expected behaviour from the users point of view

**Comment by Mugen87** [comment] 2018-04-28 20:14
That's a good point! I'll link your comment in the leading issue.
