### ISSUE TITLE
WebXRManager getCamera()

### ISSUE THREAD

**Issue by MrDChristop** [mrdoob/three.js#21869] opened 2021-05-21 10:04 UTC
Hi
First I would like to point out that the documentation for WebXRManager has missing functions that are there in the source but not mentioned in the documentation. Not sure how you want to tackle this as in the source there is no comments about what these extra functions do. The webxr section could benefit of some more docu.
 
I was in the need of getting the fov of the AR camera when in immersive-ar mode in WebXR and stumbled upon WebXRManager.getCamera(). Some tutorial say that this is the AR/VR camera that is used. 
On my phone it reports a fov of 50 always (once you enter AR mode). Which is not right. So what is this function supposed to do?

I ended up calculating the fov like so once a XRFrame was available.
Do you propose a different solution? You could add a function to WebXRManager that has the below code.
I dont know what the getCamera function does in VR mode, maybe it works but in AR mode i dont think it works as expected.
 
         ```
   let ref= this.renderer.xr.getReferenceSpace();
            let pose= frame.getViewerPose(ref);
            if (pose) {
            let fovi = pose.views[0].projectionMatrix[5];
            const fov = Math.atan2(1, fovi) * 2 * 180 / Math.PI;
            console.log(fov);
            }
```

Thanks
Dimi

**Comment by Mugen87** [comment] 2021-05-23 13:14
Duplicate of #13173.

I think the problem is that `getCamera()` was originally intended as an internal method. It returns an instance of `ArrayCamera` which a special type of camera and more like a container for sub cameras. Its `fov` property is never set since the renderer does not require it. That explains the value of  50 which is the default `fov` of `PerspectiveCamera` (the upper class of `ArrayCamera`).

I wonder if it isn't better when `WebXRManaer.getCamera()` computes the `fov` value of the XR camera in order to avoid this confusion.

> First I would like to point out that the documentation for WebXRManager has missing functions that are there in the source but not mentioned in the documentation. 

Only public methods were documented so far. If `getCamera()` is considered to be public, it should be added to the documentation. Since multiple example actually use the method, it's probably time for doing this. Same for `getHand()`, `getReferenceSpace()` and `getSession()`.

**Comment by MrDChristop** [comment] 2021-05-23 15:36
Well getCamera() makes you think it will return the actual AR/VR camera that is used when switching to immersive mode.
I find out that your camera is not used for actual rendering in that mode, so somehow a new camera is created.

**Comment by Mugen87** [comment] 2021-05-25 07:32
Since the missing mehtods are now documented, this issue can be closed.

According to https://github.com/mrdoob/three.js/issues/13173#issuecomment-525540079, the `fov` has to be manually computed based on the given matrices from the WebXR API. For performance reasons, `three.js` does not do this every frame. It would also be a pure read-only property since the `fov` in context of XR can be changed compared to normal rendering.

**Closed by Mugen87** 2021-05-25 07:32 UTC
Labels: Documentation, Question

**Comment by MrDChristop** [comment] 2021-05-25 08:13
Thanks
I would also add to the getCamera() documentation that it just returns a container and note what attributes are correctly applied.  For example that Its fov property is never set since the renderer does not require it. That explains the value of 50 which is the default fov of PerspectiveCamera (the upper class of ArrayCamera) (your words).

You dont have to compute the fov every frame, Just provide as you said a function based on the above comment that can be called by the programmer if needed once inside the update loop. I would definitely add two convenience functions to WebXR Manager for resolution and fov.
