### ISSUE TITLE
Ray.IntersectSphere returns a hit for NaN values

### ISSUE THREAD

**Issue by wmurphyrd** [mrdoob/three.js#14191] opened 2018-06-01 15:56 UTC
##### Description of the problem

If the sphere in Ray.IntersectSphere has any null or NaN values, the function will return a modified `target` with its values set to NaN rather than returning null as expected for a non-intersection. When used in raycasting the result is that an object with invalid values is permanently added to the top of the list of current intersections. 

The culprit is:

https://github.com/mrdoob/three.js/blob/dev/src/math/Ray.js#L266

As it is using a truthy condition to inditcate a miss. Reversing the comparison to:

`if ( !(d2 <= radius2) ) return null;`

Would instead return null if either value is invalid. 

##### Three.js version

- [X] Dev
- [X] r93

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by WestLangley** [comment] 2018-06-01 16:05
>If the sphere in Ray.IntersectSphere has any null or NaN values

If that is happening, you have a problem in your app. Why does your sphere have invalid data?

**Comment by haroldiedema** [comment] 2018-06-04 16:03
What a nice little coincidence! I happened to stumble across this exact same issue last night :joy: 

Sorry to dissapoint, but @WestLangley is most likely right on this one. In my case, one of my objects that was in my `intersectObjects` array didn't have a valid position. One of the values was `NaN`, causing the raycaster to give some unexpected behavior.

**Comment by wmurphyrd** [comment] 2018-06-06 13:12
@WestLangley I'm extending the raycaster to support instanced geometry, and invalid data is one of my test cases.

Is this the intended behavior, then? I come from a data engineering background where the convention is to always expect unknown values and that any operation on an unknown value yields another unknown (anything else, [as best described by David Winsemius](http://r.789695.n4.nabble.com/Fortune-candidate-Re-Why-can-t-R-understand-if-num-NA-tt4666250.html#none), would be to violate the 2nd law of thermodynamics), so it looked to me like a simple mistake. Forgive me if conventions differ in this realm.

**Comment by WestLangley** [comment] 2018-06-06 18:07
three.js expects valid data -- not null, NaN, or missing; it is up to your application layer to ensure that.

If three.js accommodated invalid data in this method, it would have to do so in every method.

>I'm extending the raycaster to support instanced geometry

Instanced geometry is very flexible, and it may be difficult to support instanced-raycasting in general, but a three.js example in which that is done would be awesome, if you are interested. :-)

**Comment by makc** [comment] 2018-06-09 21:11
> any operation on an unknown value yields another unknown

unknown in a sense that you don't know what to expect ) like, you did not really know if your test was going to return hit or no hit. you guessed it would be no hit, and you guessed wrong.

**Comment by Mugen87** [comment] 2018-06-13 08:47
> three.js expects valid data -- not null, NaN, or missing; it is up to your application layer to ensure that.

Correct. Closing the issue since it's an app related issue.

**Closed by Mugen87** 2018-06-13 08:47 UTC
