### ISSUE TITLE
localToWorld uses matrix from the previous frame

### ISSUE THREAD

**Issue by hopeless-programmer-online** [mrdoob/three.js#20220] opened 2020-08-29 19:35 UTC
##### Description of the problem

It seems that `Object3D.prototype.localToWorld` (and all other matrix-related stuff) works with the matrix that is not up to dated.
This can be easily checked by the following code:

```typescript
const object = new three.Mesh(
    new three.BoxGeometry(1, 1, 1),
    new three.MeshBasicMaterial,
);

// expected : 0, 0, 0
// actual   : 0, 0, 0
console.log(object.localToWorld(new three.Vector3(0 ,0, 0)));

object.position.set(1, 2, 3);

// expected : 1, 2, 3
// actual   : 0, 0, 0
console.log(object.localToWorld(new three.Vector3(0 ,0, 0)));

object.updateWorldMatrix(true, false);

// expected : 1, 2, 3
// actual   : 1, 2, 3
console.log(object.localToWorld(new three.Vector3(0 ,0, 0)));
```

The only way to fix this is to use `updateWorldMatrix` (or render the scene) to force matrix update.
In my case this causes a camera to lag behind the object which it is tracking. That was definitely not what I was expect to see, so I think this should be fixed.

**Comment by donmccurdy** [comment] 2020-08-29 20:00
Hi! These matrices are updated automatically only once per frame, during the render process. See https://threejs.org/docs/#manual/en/introduction/How-to-update-things. If you need more frequent updates on particular objects you do need to call updateWorldMatrix yourself. This avoids performance problems as positions of many objects may be updated in between renders.

If you're having trouble making this pattern work well in your application, we should be able to help at https://discourse.threejs.org/.

**Comment by WestLangley** [comment] 2020-08-29 20:15
I think three.js methods should return the correct answer.

**Comment by hopeless-programmer-online** [comment] 2020-08-29 22:24
@donmccurdy I think you misunderstood me.
I think there is absolutely no reason to call `localToWorld` or any other matrix-related stuff to get the **outdated** matrix.
If someone calls `localToWorld` it means that he **really** needs this matrix. And I can't even imagine the use-case when someone calls `localToWorld` to get the matrix from the previous frame.
So, if there are no use-cases for calling `localToWorld` without `updateWorldMatrix` - maybe it would be good to `updateWorldMatrix` call inside the `localToWorld`?
Nevertheless, if there is at least one use-case to do so - please let me know.
Thanks.

**Comment by donmccurdy** [comment] 2020-08-29 22:45
Users expect these methods to be both correct and efficient. In this case those two goals are at odds. If you are writing an application where performance is at a premium, users (often!) turn off even the matrix updates that would normally happen when rendering, so the matrix never updates at all except when they tell it to. It's not that the user wants to use an outdated matrix, but that they are carefully managing when the matrix gets updated.

Imagine that you are going to update your scene graph once (say, when a physics simulation runs) and then do a bunch of calculations after that, calling these methods on many nodes. You don't want to traverse up or down the tree every time you call a method on any node. You want to do it once, for the entire tree, and then have the objects' methods run more efficiently.

Admittedly this catches users by surprise sometimes too, but I can't think of a reason users would expect `localToWorld` to return the "correct" answer that doesn't equally apply to accessing `.matrixWorld` directly. Maybe a better argument would be consistency with `getWorldPosition` and similar methods. In past projects I've avoided those methods because I knew `localToWorld` was more efficient, and #20221 would decrease that efficiency.

I'm not necessarily opposed to #20221, but we should be very careful about changes like this. I wish there were an option like `matrixAutoUpdate` to disable this behavior when users need finer control over performance. I'll reopen the issue and let others weigh in here, thanks for the comments.

**Comment by hopeless-programmer-online** [comment] 2020-08-29 23:13
I fully understand that there is a performance reason to not recompute matrix on every call to `localToWorld`.
But there might be at least two options to mitigate the impact on performance or eliminate it at all:
1. Update the matrix only if object or its parent (recursively) has changes in position/rotation/hierarchy/etc. This will replace the entire recomputation with traversing the flags and caching the results. Also, traversing can be eliminated if the parent node will notify all of its children about changes.
2. Use separate methods for the rendering engine and public apis. In this case user will always get the correct result for extra cost and the engine will also compute each matrix only once, without any additional checks and caching. And in case if user definitely know that caching is not needed in particular case he can always call "uncached" api.

**Comment by Mugen87** [comment] 2020-08-30 09:13
The real issue is that `three.js` world matrix computation is slow because there is no caching or avoidance of redundant computations. This was discussed in the past and evaluated with multiple PRs (which got never merged).

Methods like `localToWorld()` and `worldToLocal ()` should ensure to work with the latest world matrix. Not doing this just to improve performance is wrong. 

As a reminder: The first step of making the world matrix computations more efficient is to make `Object3D.matrix` private.

**Comment by WestLangley** [comment] 2020-08-30 09:44
>Methods like localToWorld() and worldToLocal () should ensure to work with the latest world matrix. Not doing this just to improve performance is wrong.

Yes. Trading accuracy for performance is acceptable; trading correctness for performance is not.

>The first step of making the world matrix computations more efficient is to make Object3D.matrix private.

I have discussed this before, and explained that users need to have the ability to update the object matrix directly -- as they have been able to do since the inception of three.js. The object matrix can be made private as long as this capability remains.

**Comment by Mugen87** [comment] 2020-08-30 10:05
Before every body repeats his arguments about that topic, here is one related discussion: #18344

**Comment by donmccurdy** [comment] 2020-08-31 05:39
> world matrix computation is slow because there is no caching or avoidance of redundant computations... The first step of making the world matrix computations more efficient is to make Object3D.matrix private.

@Mugen87 I'm not aware of any proposals for caching that would allow an Object3D deeply nested in the scene graph to detect changes to the transforms of its ancestors... are there ideas on that? It sounds very difficult to me.

> ...trading correctness for performance is not.

@WestLangley I understand your point, but if these methods are used according to their documentation, the results will be correct. Admittedly, that isn't always intuitive, but I don't think this is so straightforward as a correct vs. incorrect matter. Why do we have `.matrixWorldNeedsUpdate` if we're going to ignore it and recalculate the world matrix every time a getter is called? The question is whether the (real) confusion sometimes caused by needing to manually update matrices outweighs the (also real) benefits of having that control. 

***

Here are two ideas:

**(a)** Methods like `localToWorld`, `worldToLocal`, `getWorldPosition`, etc. should only update the world matrix if `.matrixAutoUpdate` is true. It's true by default, so new users will get correct results without needing to manually update the matrix. Users who want more control can disable it.

**(b)** Methods like `localToWorld`, `worldToLocal`, `getWorldPosition` could take an optional `worldMatrix` parameter. When given, that parameter would be used as-is. When not given, the methods could recalculate the world matrix and use that. For users who are managing their matrix updates, just passing in the object's own `.worldMatrix` property would be easy enough:

```js
object.localToWorld( position, object.worldMatrix );
```

**Comment by Mugen87** [comment] 2020-08-31 09:17
> @Mugen87 I'm not aware of any proposals for caching that would allow an Object3D deeply nested in the scene graph to detect changes to the transforms of its ancestors... are there ideas on that? It sounds very difficult to me.

AFAIK, it was not explicitly discussed when transformation caching and the usage of dirty flags was evaluated.

**Comment by WestLangley** [comment] 2020-08-31 15:36
@donmccurdy This is a difficult issue, and I think your concerns are valid ones. The perfect solution has alluded us, so far...

>Methods like localToWorld, worldToLocal, getWorldPosition, etc. should only update the world matrix if .matrixAutoUpdate is true.

`.matrixAutoUpdate` applies to the object matrix, not the world matrix. It exists so users can set it to `false` and update the object matrix directly. It also exists so users can set it to `false` for known-static objects.

**Comment by donmccurdy** [comment] 2020-08-31 16:52
The docs define it more broadly —

> When this is set, it calculates the matrix of position, (rotation or quaternion) and scale every frame _and also recalculates the matrixWorld property._

Whether we want to double down on that, I don't know. But I think the cases where users would set it to false are likely also cases where they wouldn't want getters recalculating the world matrix.

**Comment by WestLangley** [comment] 2020-08-31 17:25
>and also recalculates the matrixWorld property.

I think the docs are misleading. The world matrix is always recalculated if a parent transform is changed -- regardless of the value of `.matrixAutoUpdate`.

>But I think the cases where users would set it to false are likely also cases where they wouldn't want getters recalculating the world matrix.

I do not think that is true. The world matrix must be updated if an ancestor transform is changed.

**Comment by donmccurdy** [comment] 2020-09-02 01:52
> I think the docs are misleading. The world matrix is always recalculated if a parent transform is changed -- regardless of the value of .matrixAutoUpdate.

Hm, you're right. I'm not sure what the docs are trying to say here – I certainly read that incorrectly. WebGLRenderer does check `scene.autoUpdate`, and will skip updating any world matrices if it is false. 

https://github.com/mrdoob/three.js/blob/696d7836d1fc56c4702a475e6991c4adef7357f4/src/renderers/WebGLRenderer.js#L992

I guess that rules out **(a)** from my earlier suggestions; I don't think we want an API that requires access to the parent scene when calling these methods.

> The world matrix must be updated if an ancestor transform is changed.

Updating the world matrix is necessary at some point after an ancestor transform is changed, but I'm trying to avoid the outcome where it's updated defensively every time it is used. Or at least to provide an option for users who want to avoid that performance cost.

**Comment by WestLangley** [comment] 2020-09-02 03:00
We could wait until a user complains about performance. In which case, we can advise the user to inline the relevant code chunks and avoid a traversal up the tree.

But, if you insist,
```js
object.localToWorld( target, updateWorldMatrix = true ) { // or default to false

    if ( updateWorldMatrix === true ) this.updateWorldMatrix( true, false );
    ...
}
```
We would have to do that everywhere.

**Comment by Mugen87** [comment] 2020-09-02 16:28
> We could wait until a user complains about performance.

Well, there are already enough complains that the world matrix computation in `three.js` is a hot spot during performance analysis in certain scenarios. We should be aware that #20221 won't improve this situation.  

That said, I still favor correctness in this case since.

**Comment by WestLangley** [comment] 2020-09-02 18:42
>Well, there are already enough complains that the world matrix computation in three.js is a hot spot during performance analysis in certain scenarios

Three complaints out of how many millions of users?

Furthermore, the renderer was calling `object.updateMatrixWorld()`, which unnecessarily traverses _down_ the tree. I would not consider prior complaints relevant to current three.js versions.

Let's see if there are complaints with the new versions. If there are, we can address it.

>That said, I still favor correctness in this case.

Yes. I agree with that. :-)

**Comment by Mugen87** [comment] 2020-09-02 18:50
> Three complaints out of how many millions of users?

You should not do the mistake to underestimate the current performance limitations of the engine's world matrix computations. Other engines like BabylonJS handle this topic way better. Even if there are no new complains, the way `three.js` updates its world matrices needs to be revisited.

**Comment by WestLangley** [comment] 2020-09-02 19:14
>the way three.js updates its world matrices needs to be revisited.

Oh, I have no objections if you want to do that. But please first _demonstrate_ there is a measurable performance penalty -- relative to the cost of rendering. And then propose a solution that fixes it.

**Comment by Mugen87** [comment] 2020-09-02 19:21
Yes, that sounds good. We need a test case for validation anyway!

**Comment by WestLangley** [comment] 2020-09-02 19:29
@gero3 put a lot of effort into this years ago. I also implemented a lazy-update method to try to improve the performance of quaternion/rotation updating. Nothing I tried improved performance. @gero3 filed multiple PRs, none of which were merged (I think).

But if you want to have a go at it, that would be great, IMO.

**Comment by Mugen87** [comment] 2020-09-16 16:20
Another user stumbled across this issue :/

https://discourse.threejs.org/t/get-threejs-coordinates-of-mesh-intersection-directly-below-mouse-click/18756/4?u=mugen87

**Comment by Mugen87** [comment] 2023-03-07 10:06
Fixed via #25097.

**Closed by Mugen87** 2023-03-07 10:06 UTC
Labels: Suggestion

**Comment by donhatch** [comment] 2023-07-08 12:14
> Another user stumbled across this issue :/
> 
> https://discourse.threejs.org/t/get-threejs-coordinates-of-mesh-intersection-directly-below-mouse-click/18756/4?u=mugen87

Hold on, did you give them the right advice on that?  You suggested calling `mesh.updateMatrixWorld()`.  But that can't just be called out of the blue, since that will use mesh.parent.matrixWorld, which isn't necessarily up-to-date.  In general, my understanding is that .updateMatrixWorld() makes sense only in situations when you know the parent's is already up-to-date; for instance when it's part of an overall top-down traversal beginning at the top with scene.updateMatrixWorld(), as is done at the beginning of WebGLRenderer.render().

Did you mean to say `mesh.updateWorldMatrix(/*updateParents=*/true, /*updateChildren=*/false)` instead?

**Comment by Mugen87** [comment] 2023-07-08 12:47
`localToWorld()` internally uses `updateWorldMatrix( true, false );` now so users don't have to worry about this issue anymore. So the forum topic is outdated. However, it makes sense to update the answer at the forum to use `updateWorldMatrix()` instead.

**Comment by donhatch** [comment] 2023-07-08 13:09
> `localToWorld()` internally uses `updateWorldMatrix( true, false );` now

Oh!  I missed that memo, thanks :-)

Incidentally I think maybe TransformControls() makes the same mistake of calling `this.object.updateMatrixWorld()` when there's no guarantee that `this.object.parent.matrixWorld` is up to date... should that be updateWorldMatrix() too?     If so, maybe the whole codebase should be audited for that mistake? 

(That'll be nuts, though... that call to `updateMatrixWorld()` is actually in `TransformControls.updateMatrixWorld()`, so changing it to call `updateWorldMatrix()` would introduce a bottom-up traversal in the middle of the top-down traversal, which could have a performance penalty if this.object is deep in the scene, since there seems to be no principled dirty/clean markings to prevent redundant computations.   Sorry I don't have a clean solution for anything here, just pointing out more problems.  This whole matrix system seems... problematic.)

**Comment by donhatch** [comment] 2023-07-08 13:25
> > Well, there are already enough complains that the world matrix computation in three.js is a hot spot during performance analysis in certain scenarios
>
> Three complaints out of how many millions of users?

Make it four.  I looked into why my rendering is so slow the other day, and found out it's spending almost all its time in updateMatrixWorld() -- which was particularly unexpected since (1) no matrices were changing at all, and (2) almost all of that was spent traversing parts of the tree that [weren't even visible at the particular time](https://github.com/mrdoob/three.js/issues/14360) (in my app, visibility of various expensive subtrees gets turned on and off as the user checks/unchecks checkboxes).   Worse, there doesn't seem to be a good generally usable fix on my end (I'm concluding, after reading the many related bug reports, and aborted PRs, and source code). This doesn't reflect well on the product, and this kind of dismissal of this serious problem on the basis of number of complaints is disappointing to hear.  It seems likely to me that the small number of people you're hearing from who are feeling this pain and speaking about it are exactly those power users who are crafting sophisticated scenes and apps who care about this and would benefit greatly from a good usable robust efficient general matrix management system, which three.js doesn't have, at this point, it seems.

I concur with Mugen87's reply:
> You should not do the mistake to underestimate the current performance limitations of the engine's world matrix computations. Other engines like BabylonJS handle this topic way better. Even if there are no new complains, the way `three.js` updates its world matrices needs to be revisited.

I wasn't familiar with BabylonJS before this, but this review makes me inclined to look into it.
