### ISSUE TITLE
Bad performance on the latest Chrome beta 60.0.3112.40

### ISSUE THREAD

**Issue by looeee** [mrdoob/three.js#11610] opened 2017-06-25 04:28 UTC
##### Description of the problem 

Very bad WebGL performance on the latest Chrome beta 60.0.3112.40 on Windows 10

With a very simple example I'm getting around 40fps on Chrome http://jsfiddle.net/akmcv7Lh/154/
More complex example run at <10 fps https://threejs.org/examples/#webgl_animation_cloth

Both run at a smooth 60fps on Firefox and Edge. Tested with and without stats overlay in case that was the issue, and I've also tested just calling RequestAnimationFrame, which seems to be working fine on its own so it's most likely a WebGL issue. 

I've submitted a Chrome bug report [here](https://bugs.chromium.org/p/chromium/issues/detail?id=736622#).

##### Three.js version

- [ x ] Dev
- [ x ] r86

##### Browser

- [ x ] Chrome beta 60.0.3112.40

##### OS

- [ x ] Windows 10

##### Hardware Requirements (graphics card, VR Device, ...)

Geforce GTX 970m

**Comment by Misiek304** [comment] 2017-06-25 22:10
That's because of this:
![image](https://user-images.githubusercontent.com/15746026/27520137-e09f37e8-5a03-11e7-9029-5e820d532a45.png)

They broke something real bad in this build

**Comment by mrdoob** [comment] 2017-06-27 01:02
FYI @kenrussell

**Comment by kenrussell** [comment] 2017-06-27 17:43
Sorry about the regression in performance. This bug happened because there was a merge conflict when merging a bug fix from top-of-tree to Chrome Beta. It will be fixed in the next Chrome Beta build.

As a workaround, you could try Chrome Dev or Canary. Of course, if you see issues with these newer branches, please file bugs right away and please feel free to email me the bug IDs directly: kbr at chromium dot org.

Separately, we'll work on improving our testing processes for Chrome's branches like Beta. Currently the majority of the testing is done on top-of-tree, so regressions caused by merges can unfortunately slip through.

**Comment by Misiek304** [comment] 2017-06-28 14:24
Honestly... Things like that shouldn't happen. This is a major issue with beta release. I would expect to see something like this in dev but not beta, channel that's design to polish the release not fix major problems.

But since it happened then I would expect the "fix" sooner then "next Chrome Beta build". It's already more then then 7 days without a resolution. I hope that the new testing procedures you are planning to implement will minimalizm the risk of such a big issue.

**Closed** 2017-07-31 15:02 UTC
Labels: Browser Issue
