### ISSUE TITLE
[Example] Broken TSL editor example

### ISSUE THREAD

**Issue by s-rigaud** [mrdoob/three.js#29191] opened 2024-08-20 23:25 UTC
### Description

The TSL editor is broken, it seems to be a simple WebGPURenderer import but I'm not 100% sure how it should be fixed.

### Reproduction steps

https://threejs.org/examples/?q=webgpu#webgpu_tsl_editor

### Code

https://threejs.org/examples/?q=webgpu#webgpu_tsl_editor

### Live example

https://threejs.org/examples/?q=webgpu#webgpu_tsl_editor

### Version

r167

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by Mugen87** [comment] 2024-08-21 08:41
Duplicate of #29164.

**Closed by Mugen87** 2024-08-21 08:41 UTC
