### ISSUE TITLE
LatheGeometry produces mesh with open ends when using phiStart and phiLength

### ISSUE THREAD

**Issue by hean01** [mrdoob/three.js#10765] opened 2017-02-08 23:44 UTC
##### Description of the problem 

When using LatheGeometry with `phiStart` and `phiLength` the resulting mesh have open ends, expected to get closed ends or at least have an option to close.

```
  var r = 5;
  var shape = new THREE.Shape();
  shape.moveTo(r, 0);
  shape.lineTo(r + 1, 0);
  shape.lineTo(r + 1, 1);
  shape.lineTo(r, 1);
  shape.lineTo(r, 0);

  var g = new THREE.LatheGeometry(shape.getPoints(), 32, 0, 5.0);
```

##### Three.js version

- [ ] Dev
- [X] r84
- [ ] ...

##### Browser

- [ ] All of them
- [X] Chrome
- [X] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [X] Linux
- [ ] Android
- [ ] IOS

**Comment by Mugen87** [comment] 2017-02-09 18:10
Here's an example: https://jsfiddle.net/c26wef25/5/

Closing the ends is not supported by `LatheGeometry`. `CylinderGeometry` also can't close the geometry, if you partly draw it. Not sure if this is a too specific requirement....

**Comment by WestLangley** [comment] 2017-02-09 19:29
@Mugen87 I have never seen `LatheGeometry`used in that manner. The normals do not really make sense for that shape.

**Comment by Mugen87** [comment] 2017-02-09 19:47
You're right. We normally use points arrays like in this example...

https://jsfiddle.net/c26wef25/11/

**Comment by WestLangley** [comment] 2017-02-09 19:52
The docs say:

>Possible uses include donuts, pipes, vases etc. The lathe rotate[s] around the Y axis.

I do not think it was intended to support "donuts".

**Comment by Mugen87** [comment] 2017-02-09 19:57
Let's adjust the docs...

**Closed** 2017-02-09 22:31 UTC
