### ISSUE TITLE
Weird jitter of objects with Mali GPU

### ISSUE THREAD

**Issue by Evertvdw** [mrdoob/three.js#15282] opened 2018-11-20 07:10 UTC
##### Description of the problem

Hello,

I have a strange problem which has been bugging me for quite a while now, the issue is best explained by a short video:

![Video](https://i.imgflip.com/2n01ga.gif)

As you can see the objects in the scene have a jitter when you move the camera around but also a similar thing happens every now and then when the camera is not moving. It's been driving me crazy for a while now. This video has been taken on a Tinkerboard with TinkerOS, but the same issue is also there on a Tinkerboard with FlintOS. 

On a regular laptop there is no issue and everything is moving smoothly. I'm not sure if this is a bug or if it is expected behaviour seeing the differences in hardware, so I was hoping somebody could shed some light on this.

Here is a WebGL report from the Tinkerboard: 
<a href="https://ibb.co/chtyS0"><img src="https://preview.ibb.co/nNKu0L/image.png" alt="image" border="0"></a>

Here a WebGL report from my laptop:
<a href="https://ibb.co/kafgVL"><img src="https://preview.ibb.co/c78qPf/Untitled.png" alt="Untitled" border="0"></a>

Obviously there are differences but I have no idea if any of these difference would explain this behaviour. 

Can anyone clarify?

Thanks!

##### Three.js version

- [ ] Dev
- [x] r98
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome (Chromium v62)
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment] 2018-11-20 11:35
Do you have the same issue with other WebGL demos? If so, it seems to be a driver related issue. In this case, there is nothing we can do here. It might be better to report the bug to the GPU vendor.

**Comment by Mugen87** [comment] 2018-11-20 17:04
Crossposting:

https://stackoverflow.com/questions/53395835/weird-jitter-of-objects-in-three-js-using-mali-gpu

**Comment by mrdoob** [comment] 2018-11-20 20:09
What's the size of your scene and what did you set at `near` and `far` to your camera?

**Comment by Evertvdw** [comment] 2018-11-21 06:51
> Crossposting:
> 
> https://stackoverflow.com/questions/53395835/weird-jitter-of-objects-in-three-js-using-mali-gpu

I tried a question on stackoverflow as well indeed.

For near I use 200 and far 4000, that was one of the first things I tried to limit the gap between these values and keep the near as high as possible. 

That white floor you see in the video has a z-dimension of 0 in my model, when I gave this plane some height this effect went away. But the question still is why that is a problem on this GPU and not on others.

**Comment by Mugen87** [comment] 2018-11-21 19:55
> But the question still is why that is a problem on this GPU and not on others.

Like I said before, you should report this problem to the GPU vendor. I don't think this space here is able to answer this question.

**Comment by mrdoob** [comment] 2018-11-21 20:13
Can you share a screenshot of your scene in wireframe?

**Comment by Evertvdw** [comment] 2018-11-26 09:13
> Can you share a screenshot of your scene in wireframe?

How would I do that? 

And I can't find a place where I can ask this question to the GPU vendor. My thought is that it somehow has to do with a buffer size or  one of the max values in the Webglreport that causes this behaviour. Does Three.js use these in any way or is it up to the browser to take care of this?

**Comment by Evertvdw** [comment] 2018-11-28 10:16
> You render all materials with `.wireframe` set to `true`.

Ok, here is a screenshot:
![image](https://user-images.githubusercontent.com/5757159/49144847-ab0a6400-f2fe-11e8-9a3e-7e246a4cdca5.png)

> Why do you think it's not a GPU driver issue?

I also had this issue with a Rpi3, with a broadcom gpu. So that why I think that something else is going on. Floating point precision also is something that I thought of but I already have my renderer initiated with precision to highp, is there anything else I could do about that? 

And thanks for the link! I'll try that as well. Thanks for the support so far!

**Comment by Mugen87** [comment] 2018-11-28 12:01
> but I already have my renderer initiated with precision to highp

The problem is that does not mean you actually get `highp`. On many older devices, you still get `mediump`.

**Comment by Evertvdw** [comment] 2018-11-28 13:32
> The problem is that does not mean you actually get `highp`. On many older devices, you just get `mediump`.

Can I then somehow account for this when constructing my model so that precision is not an issue?

**Comment by Mugen87** [comment] 2018-11-28 13:52
What is the scale of you model? I mean the min/max range of your vertices?

**Comment by Evertvdw** [comment] 2018-11-28 14:44
> What is the scale of you model? I mean the min/max range of your vertices?

Here is the gltf file I exported from blender and use as input. Its readable in a text-editor, does that give information about the min/max range of vertices? 

[factorylayout.zip](https://github.com/mrdoob/three.js/files/2625049/factorylayout.zip)

**Comment by Mugen87** [comment] 2018-11-28 14:54
Unfortunately no. I also need the `bin` file. The Blender file would be even better.

**Comment by Evertvdw** [comment] 2018-11-28 15:03
I also have that of course: 

[blenderfile.zip](https://github.com/mrdoob/three.js/files/2625133/blenderfile.zip)

**Comment by Mugen87** [comment] 2018-11-28 16:44
Um, some of your vertices have a `y` value of `0` and `0.050000`. Can you try to set all `y` values to `0` and then make a test?

**Comment by Evertvdw** [comment] 2018-11-29 06:00
> Um, some of your vertices have a `y` value of `0` and some of `0.05`. Is there a special reason for this? Can you try to set all `y` values to `0` and then make a test?

Probably no, but where do you see that? I'm not a pro with blender, this is my first shot at it :)

**Comment by Mugen87** [comment] 2018-11-29 10:10
I've exported the project as an `OBJ`. Not for asset delivery (of course not!), just to inspect the geometry data.

**Comment by Mugen87** [comment] 2018-12-04 10:53
Closing. This is clearly not a `three.js` issue. Please use the [forum](https://discourse.threejs.org/) or stackoverflow for more help or feedback.

**Closed by Mugen87** 2018-12-04 10:53 UTC
Labels: Device Issue

**Comment by mrdoob** [comment] 2020-02-14 19:36
So I actually bought a Tinkerboard because of this issue back in 2018 but I didn't have time to test it until now.

TinkerOS-Debian seems to be pretty unsupported and updating Chromium to the latest version makes Chromium crash at startup. Seems like ASUS is not doing a good job with support and software.

Raspberry Pi 4 + Raspbian seems like a much better option.
