### ISSUE TITLE
ObjectLoader doesn't load a scene object's background texture or environment

### ISSUE THREAD

**Issue by meliharvey** [mrdoob/three.js#18715] opened 2020-02-24 02:07 UTC
##### Description of the problem

Currently, ObjectLoader doesn't load the specified background texture or environment of a scene's JSON object. 

I've outlined a solution below that would import a CubeTexture or Texture for the scene background, and a CubeTexture for environment (since that's the only type of texture environment supports). This involved passing textures into `parseObject()` and then added them to the scene object.

I could make a PR if looks good, but I'm also not sure if this conflicts with some of the plans outlined in existing issue #17420. Either way this seems like a desirable feature of ObjectLoader.

```javascript
parseObject: function ( data, geometries, materials, textures ) {

	var object;

	...

	function getTexture( name ) {

		if ( textures[ name ] === undefined ) {

			console.warn( 'THREE.ObjectLoader: Undefined texture', name );

		}

		return textures[ name ];

	}

	switch ( data.type ) {

		case 'Scene':

			object = new Scene();

			if ( data.background !== undefined ) {

				if ( Number.isInteger( data.background ) ) {

					object.background = new Color( data.background );

				} else {

					object.background = getTexture( data.background );

				}

			}

			if ( data.environment !== undefined ) {

				var texture = getTexture ( data.environment );

				if ( texture instanceof CubeTexture ) {

					object.environment  = texture;

				}

			}

			if ( data.fog !== undefined ) {

				if ( data.fog.type === 'Fog' ) {

					object.fog = new Fog( data.fog.color, data.fog.near, data.fog.far );

				} else if ( data.fog.type === 'FogExp2' ) {

					object.fog = new FogExp2( data.fog.color, data.fog.density );

				}

			}

			break;
	...
```

##### Three.js version

- [x] Dev
- [x] r113

##### Browser

- [x] All of them

##### OS

- [x] All of them

**Comment by Mugen87** [comment] 2020-02-24 10:09
Thanks for reporting this! Yes, this is a knows issue especially because of the editor, see #16154. However, it's also necessary to `Scene.toJSON()` as outlined in #18479 since the method is currently not able to serialize a texture for `background` and `environment`.

I'll marking your issue as a duplicate of #16154. Please proceed the discussion in the existing thread.

**Closed by Mugen87** 2020-02-24 10:09 UTC

**Comment by Mugen87** [comment] 2020-02-24 11:04
> I could make a PR if looks good, but I'm also not sure if this conflicts with some of the plans outlined in existing issue #17420.

I think implementing this independently of #17420 is okay. It would be great if you can make a PR based on your ideas and #18479 👍.

If you are not familiar with the editor's code yet, then just focus on the changes within the core. I can provide the missing bits for the editor if necessary.
