### ISSUE TITLE
Camera is attached backwards on parent object

### ISSUE THREAD

**Issue by cbabc** [mrdoob/three.js#13753] opened 2018-04-03 08:07 UTC
##### Description of the problem

When a camera is attached to an object, it looks at the opposite direction than the parent's lookAt direction.  Therefore, the parent cannot be used to make the camera follow with lookAt function, unless the camera is first rotated locally 180 degrees on Y axis, like bellow. So, it is a fundamental bug that needs correction.

```
var camRig = new THREE.Object3D();
var camPersp = new THREE.PerspectiveCamera( 50, w/h, 1, 2000 );

camRig.add(camPersp);

// *** workaround ***
camPersp.rotateOnAxis(new THREE.Vector3(0,1,0), deg2rad(180));

scene.add(camRig);

camRig.position.set(x, y, z);
camRig.lookAt(target);
```

##### Three.js version
- [ ] r91  - apparently, all versions so far

**Comment by Mugen87** [comment] 2018-04-03 08:14
https://stackoverflow.com/questions/49611798/three-js-camera-does-not-follow-parents-lookat

**Comment by looeee** [comment] 2018-04-03 08:53
See #737

I don't think the other conversation reached any concrete conclusion on this though.

**Comment by cbabc** [comment] 2018-04-03 14:04
We have this behavior:

No matter what orientation has the parent object on the Y axis before the attachment (eg, 0deg, 45deg, 125deg, etc), the camera **always** needs to be rotated 180 degrees, either before, or after it is attached, in order to resolve the lookAt issue.

Hope this helps.

**Comment by WestLangley** [comment] 2018-04-04 02:45
This is not a bug.

`Object3D.lookat( vector )` orients an object so the object's _positive_-z axis points in the direction of `vector `.

Cameras are the exception.

`Camera.lookat( vector )` orients the camera so the camera's _negative_-z axis points in the direction of `vector `. 

This is because three.js cameras look down their local negative-z axis.

**Comment by Mugen87** [comment] 2018-04-04 08:09
Since this was discussed before, I vote to close the issue. The standards of `three.js` are defined in @WestLangley's post. I don't think it makes sense to change them now.

**Comment by cbabc** [comment] 2018-04-04 10:52
@WestLangley 

> "This is not a bug"
Behavior opposite than what is expected, is usually a bug.

> "This is because three.js cameras look down their local negative-z "
What that has to do with attaching them backwards to the object's front?
Isn't the purpose of attaching a camera to follow the object and eventually the object's lookAt?

And what is the benefit of keeping it as it is, vs the benefit of resolving this?

**Comment by looeee** [comment] 2018-04-04 13:36
@cbabc can you do some research and see how other libraries and apps handle this? 

If three.js is non-standard then IMO we should look into providing a fix or workaround.

**Comment by Mugen87** [comment] 2018-06-21 21:20
https://stackoverflow.com/questions/33407209/why-does-the-camera-face-the-negative-end-of-the-z-axis-by-default?rq=1

I vote to close the issue.

**Closed** 2018-09-04 09:44 UTC
