### ISSUE TITLE
Round / circular points via Three.PointsMaterial with WebGL

### ISSUE THREAD

**Issue by Bandit** [mrdoob/three.js#11157] opened 2017-04-10 09:20 UTC
Been learning a bit about `Points`. I have a series of points that make up a shape and rotate slowly. Each point is one of 6 colours.

I want to make them circular rather than square, but all of the examples I've seen to do that don't use `Points` at all. Should I change to a `Sprite` (as per this example: https://github.com/mrdoob/three.js/blob/master/examples/canvas_lines_sphere.html#L65-L90) and re-factor my code in order to get circular points, or is there another way?

Using r84

**Comment by jostschmithals** [comment] 2017-04-10 09:51
Possibly a duplicate of https://github.com/mrdoob/three.js/issues/11016 (especially http://jsfiddle.net/myy7x4zd/10/)?

**Comment by Bandit** [comment] 2017-04-10 10:31
Thanks for the reply. So in summary the only way is via an image colorized via a custom shader?

Feels pretty overengineered but I guess it's a limitation of WebGL or something

**Comment by Mugen87** [comment] 2017-04-10 12:59
You don't have to write a custom shader. Check out how `PointsMaterial` is created in this example.

https://threejs.org/examples/?q=points#webgl_points_billboards

**Closed** 2017-04-10 13:29 UTC
Labels: Help (please use Stackoverflow)

**Comment by Odin04ka** [comment] 2018-02-12 01:22
Uncaught TypeError: THREE.PointsMaterial is not a constructor ..... from this example https://threejs.org/examples/#webgl_points_billboards
