### ISSUE TITLE
Multiple version of the same program compiled with different directives

### ISSUE THREAD

**Issue by fernandojsg** [mrdoob/three.js#16356] opened 2019-04-29 19:47 UTC
When working on the Multiview PR https://github.com/mrdoob/three.js/pull/16316 I'm facing a problem with the shader generation: If you are going to use multiview you need to add an specific directive on the shader: `layout(num_views = 2) in;`. This will require a FBO with a TextureArray2D attached with two views.

Typically if we require a multiview session is because we are going to use an `ArrayCamera` with multiple views (as a CAD software) or we want to render both eyes in VR so we will get a huge improvement. But if we render just 1 view it will add a penalty because we will sill be using a two-dimensional FBO.

Ideally we could have a "simple" way to compile the same program for different "app's presets" so we could switch between the programs as the presets change. 
For example we could compile the with or without multiview and use these shaders depending if we are in VR presenting or just painting in 2D to the canvas.

Is there any ideas or any similar work already done in this area?

**Comment by mrdoob** [comment] 2019-05-01 04:23
Not that I know of.

**Comment by Mugen87** [comment] 2020-07-18 13:56
Let's consider this issue as a duplicate of #15047. Having such a system should also solve this request since it's then possible to use [customProgramCacheKey()](https://threejs.org/docs/index.html#api/en/materials/Material.customProgramCacheKey) in order to conditionally switch between different shader programs without recompiles.

**Closed by Mugen87** 2020-07-18 13:56 UTC
