### ISSUE TITLE
Points: Vertex colors not serialized/deserialized correctly when using Geometry

### ISSUE THREAD

**Issue by wpk-** [mrdoob/three.js#7149] opened 2015-09-11 10:50 UTC
The `Geometry` for a `PointCloud` object has no `faces` (it is an empty array). However, `JSONLoader.prototype.parse` only parses color referenced through the faces. The bit that loops over the vertices ignores color: https://github.com/mrdoob/three.js/blob/master/src/loaders/JSONLoader.js#L182

The consequence of the bug is that `PointCloud` objects in a JSON file cannot define vertex colors. The following link shows that the JSON defines vertex colors, but the point cloud is rendered black.
http://jsfiddle.net/J7zp4/166/
The next link shows the point cloud rendered with the defined colors. The only difference is line 29 and 30 have been uncommented.
http://jsfiddle.net/J7zp4/167/

So I think that the JSONLoader should check for vertex colors around line 182 (linked above).

**Comment by fraguada** [comment] 2015-09-11 13:23
You should do this via BufferGeometry with a Position and a Color Array.

**Comment by wpk-** [comment] 2015-09-14 16:14
That looks like a reasonable workaround. Thanks. Nevertheless, it doesn't really fix the issue that the `ObjectLoader` ignores vertex color in a `Geometry` that has no faces defined. Are there any implications of using `BufferGeometry` instead of the regular `Geometry`?

**Comment by fraguada** [comment] 2015-09-14 16:35
I think [this](http://threejs.org/docs/#Reference/Core/BufferGeometry) is pretty clear on what the pros / cons could be.  There are probably more reasons to use one over the other, and some clues are scattered around [here](https://github.com/mrdoob/three.js/issues/5186) and [there](http://stackoverflow.com/questions/23607780/three-js-buffergeometry-vs-geometry-for-particles).

**Comment by wpk-** [comment] 2015-09-14 17:07
For me your `BufferGeometry` is a reasonable workaround. As you point out, however, there are situations where `BufferGeometry` is actually not preferred, meaning the `ObjectLoader` issue is still open.

**Comment by fraguada** [comment] 2015-09-14 17:25
I just looked around in the examples and it seems in some cases, mostly when points are to be animated, they get generated in code and pushed into a `Geometry`, there are also several situations where `BufferGeometry` stands out.  The question is, is this an issue, or is this by design?  If it is by design, perhaps there should be a more stringent effect, such as an error or a warning.  If it is an issue, what could be the way to ameliorate it?  @mrdoob or @WestLangley might be able to settle if this is by design or otherwise.  For my purposes, importing as `BufferGeometry` has worked fine.

**Comment by mrdoob** [comment] 2015-09-24 23:59
I think you should use `BufferGeometry` whenever you can. The only con is that it's harder to modify if you have to.

**Comment by bhowes-tt** [comment] 2016-04-22 17:58
:+1: for adding vertex colors support to the JSONLoader.  This would also allow lines with vertex colors to be loaded - at the moment that doesn't seem to be possible, either.

**Comment by Mugen87** [comment] 2018-08-17 11:14
It's also important to highlight that `Object3D.toJSON()` has problems with serializing point cloud data based on `Geometry`. So this issue should track the whole serialization/deserialization process.

A workaround is the usage of `BufferGeometry`.

**Comment by Mugen87** [comment] 2018-11-29 12:34
I guess we can close this issue since `JSONLoader` has been removed from core. It's not recommended to serialize/deserialize `Geometry` anymore. 

Using `BufferGeometry` is not a workaround anymore but the intended solution.

**Closed by Mugen87** 2018-11-29 12:34 UTC
Labels: Bug, Loaders
