### ISSUE TITLE
Json Blender Exporter Phong shading issue

### ISSUE THREAD

**Issue by elipeters** [mrdoob/three.js#9612] opened 2016-09-01 23:30 UTC
I was getting a problem where the only lighting affecting the json model, with its default phong shading, was ambient.

I believe the issue was the bump scale array as changing this to a value to not an array ie 1.0 fixed the issue for me...
`"mapBumpScale":[10.0,10.0]`

Is this a new feature for bump map materials that we are be able to adjust x and y offset?...and for what version is this compatible with?

Json Exporter vers 1.5.0
r77 (npm version)
Blender 2.77
OSX Mac El Capitan 10.11.6

**Comment by WestLangley** [comment] 2016-09-02 02:04
Duplicate of #9106.

**Closed** 2016-09-06 18:12 UTC
Labels: Duplicate
