### ISSUE TITLE
Object with materials that have morphTargets = true will scale down when another object's morphTargetInfluence is modified

### ISSUE THREAD

**Issue by onthez** [mrdoob/three.js#9626] opened 2016-09-05 18:03 UTC
##### Description of the problem

When a scene contains at least one object with morphTargets and another object that does not have morphTargets, but has a material with morphTargets = true;
changing the morphTargetInfluence of the first object will cause the second object to scale down.
Expected behavior would be for morph to influence no change on an object that has no morph targets even if it's materials have them flagged true

This link demonstrates two issues; one described above and a second issue that has already been submitted (#9625)
http://webdev5.onthez.com/morph_scale_bug.html

Use the dat.gui sliders to adjust the morphs of the object on the left.  You'll see the object on the right reduce in scale (though the scale values remain at (1,1,1)
##### Three.js version
- [x] Dev
- [X] r80
- [ ] ...
##### Browser
- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
##### OS
- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS
##### Hardware Requirements (graphics card, VR Device, ...)

no special hardware required

**Comment by mrdoob** [comment] 2016-09-07 05:29
I think #9640 should have fixed this. Do you mind testing?
https://rawgit.com/mrdoob/three.js/dev/build/three.min.js

**Comment by jds580s** [comment] 2016-09-07 05:39
Thanks, I'm glad to test it.
It looks like the dev build doesn't resolve the issue.
Reading issue #9640 it sounds like there may be some relation they may be related.

This link utalizes the latest dev
http://webdev5.onthez.com/morph_scale_bug-dev.html

**Comment by takahirox** [comment] 2016-09-07 05:55
I think the root issue is the same as #9640.

But in this example non-mophs mesh doesn't have `morphTargetInfluences`
and then `morphInfluences` won't be touched in `WebGLRenderer.renderBufferDirect()`
and the cached valued of it could still keep.

Don't you set `morphTargets = false` for the object which doesn't have `morphTargetInfluences`?

**Comment by jds580s** [comment] 2016-09-07 06:02
Typically I would set morphTargets = false to avoid it in a scene similar to this one linked.
That is a stripped down test of just the basics to recreate the problem.

In the project I am working on the second object does have it's own set of morphs which require morphTargets = true.  There are also other objects which don't need to morph, but share materials with objects that do which causes them to exhibit the same problem.

**Comment by takahirox** [comment] 2016-09-25 04:02
How about letting an object have empty `morphTargetInfluences []`?
I think this'll work now because of #9640.

@mrdoob 
I'm still not sure if we should care the case that 
an object doesn't have `morphTargetInfluences` and its material's `morphTargets` is true.
What do you think?

**Comment by looeee** [comment] 2019-01-26 06:20
I just ran into this bug. Very confusing for a few minutes! 

I can confirm that setting  `mesh.morphTargetInfluences = []` on the mesh without morph targets works.

**Comment by donmccurdy** [comment] 2019-02-01 19:34
Another recent example: https://github.com/mrdoob/three.js/issues/15672 😓

**Comment by Mugen87** [comment] 2021-03-03 14:35
Should be fixed via #18072.

**Closed by Mugen87** 2021-03-03 14:35 UTC
Labels: Bug
