### ISSUE TITLE
Shadows do not render on OS X Chrome

### ISSUE THREAD

**Issue by benlambt** [mrdoob/three.js#5232] opened 2014-08-25 17:57 UTC
See this Stackoverflow post for details:
http://stackoverflow.com/questions/24744246/casting-shadow-on-meshphongmaterial-or-meshlambertmaterial-in-three-js

I get the the same result (no shadow when a texture is applied) on Chrome 36.0.1985.143 / OS X 10.9.4

It works on Firefox 31.0 /  OS X 10.9.4

**Comment by justinross** [comment] 2015-01-09 01:00
So... I think I'm running into this issue, but I can't get shadows on texture in any browser (Chrome, Firefox, or Safari, at least) on my mac. Even on http://mrdoob.github.com/three.js/examples/webgl_morphtargets_md2_control.html

System info: 
![image](https://cloud.githubusercontent.com/assets/1120106/5673890/fa8100c8-9756-11e4-8e40-af27fb8ad69b.png)

GFX Card info: 
![image](https://cloud.githubusercontent.com/assets/1120106/5673900/0a99bf0e-9757-11e4-95a5-c9edd2a42089.png)

Firefox 24 ESR (tried on latest, too. ESR is just what I have open right now):
![image](https://cloud.githubusercontent.com/assets/1120106/5673925/3270ad8a-9757-11e4-96d2-fd8b57798c8d.png)

My work in Chrome: 

With textures (gray ground plane has no texture): 
![image](https://cloud.githubusercontent.com/assets/1120106/5673953/a8f83e1e-9757-11e4-8768-1a661d216d05.png)

No texture: 
![image](https://cloud.githubusercontent.com/assets/1120106/5673963/c8d9329c-9757-11e4-8784-9adcce3ff336.png)


So... Yeah. That's all. Though, maybe my iMac is just dumb, since it's not working in any of my browsers. *shrug*

**Comment by justinross** [comment] 2015-01-09 13:57
Yup! As soon as I add an image, the shadows disappear.


Though, I'm starting to wonder if there are even supposed to be shadows on the morphtarget example. I tried it on a windows machine (chrome), and still no shadows.

**Comment by WestLangley** [comment] 2015-01-09 15:16
http://mrdoob.github.com/three.js/examples/webgl_morphtargets_md2_control.html uses cascading shadows, and the demo broke some time ago. So far, we have not been able to track down the issue.

**Comment by justinross** [comment] 2015-01-09 17:42
So probably not a good example of my issue, since I'm not using cascading shadows to the best of my knowledge. I'll try to put together a fiddle to verify the problem.

Side note: Shadows on textures *do* work on mobile Safari, iOS8 (though, the framerate is kind of terribad. Probably something to do with rendering at 1920x1080 * 2 or whatever the 6 Plus renders stuff at): 

![image](https://cloud.githubusercontent.com/assets/1120106/5684298/d379e91c-97e3-11e4-83e3-07b8a085bada.png)

**Comment by justinross** [comment] 2015-01-10 01:07
Yeah, nevermind. I must have been doing something hinky. It's working in other browsers now. Still not Chrome, though. Not sure what changed.

**Comment by Neko36** [comment] 2015-01-26 13:02
Hi experts,

i have also the problem, that shadows are not getting rendered, but only on materials, where a texture is applied. The bug appears in Chrome(40.0.2214.91 (64-bit)) and Firefox(35), but only with OS X (10.10.1). On Windows 7 and Ubuntu 14.04, everything works fine.

Three.js R 70

**Comment by erixxon** [comment] 2015-02-15 20:10
Imac 5k radeon, shadows don't appear at all on textures (but without), testing on chrome, firefox and safari :-/

**Comment by neurofuzzy** [comment] 2015-03-09 01:18
Same here. Shadows work if there is no texture map on the material. As soon as I add a texture, shadows stop working. (all browsers)

Intel core i5
OS X 10.9.5
AMD Radeon HD 6770M 512 MB

**Comment by arturkot** [comment] 2015-05-01 11:53
Hi everyone,

I've got the same problem and I'm on MBP 2011 with AMD Radeon HD 6490M 256 MB __plus__ integrated GPU (the OS chooses which one to use per needs). Shadows don't display in any of the browsers until there's no texture assigned to the material. Smells like problems with ATI...

**Closed** 2015-09-03 04:34 UTC
Labels: Bug

**Comment by codeka** [comment] 2015-10-12 13:34
Should this be closed, it's still apparently happening for me:

http://jsfiddle.net/4Txgp/456/

Change the MeshLambertMaterial from using a texture to just a color and shadows work again.

**Comment by mrdoob** [comment] 2015-10-12 14:32
We have been unable to reproduce 😕

**Comment by WestLangley** [comment] 2015-10-12 15:18
From the previous comments, it appears to be AMD Radeon HD-specific.

**Comment by codeka** [comment] 2015-10-13 01:51
Yeah, I'm on a Mid-2015 Mac Book Pro with AMD Radeon R9 M370X 2048 MB, so it definitely could be specific to that.

One thing that's interesting, in my game I have a ShaderMaterial which uses all the various "shadowmap" THREE.ShaderChunk's to get proper shadows, but using the built-in MeshLambertMaterial or MeshPhongMaterial I don't get shadows:

![Shadows](http://i.imgur.com/3cgaXAg.png)

See the shadows on the terrain, which uses my custom ShaderMaterial, but not on the house? The code in the above has a bunch of extra junk so it's probably not worth sharing, but I'll have a play around with that jsfiddle and see if I can see anything else.

**Comment by codeka** [comment] 2015-10-13 10:45
So I had a play around with the jsfiddle at http://jsfiddle.net/4Txgp/459/ and if I use a basic ShaderMaterial I've defined, then it works:

![Working](http://i.imgur.com/B7tvqAR.png)

but if I use a MeshPhongMaterial/MeshLambertMaterial instead, I get no shadows:

![Not working](http://i.imgur.com/dUckfXA.png)

It's weird because my ShaderMaterial is using the same ShaderChunks as the lambert/phong shaders. There must be something else there that's conflicting.

**Comment by codeka** [comment] 2015-10-13 10:54
Looking at https://code.google.com/p/chromium/issues/detail?id=225578, I wonder if the issue is more to do with the complexity of the shader. The MeshPhongMaterial/MeshLambertMaterial shaders are pretty big, perhaps the driver is unable to properly unroll the loops in those, but because my shader is smaller it's able to unroll them?

**Comment by Mugen87** [comment] 2015-10-13 11:47
@codeka: I have noticed the same behavior with your jsfiddle on my iMac.

I'm afraid this problem requires a precise debugging of the MeshPhongMaterial/MeshLambertMaterial. There must be a part of the final shader program, that produces the mentioned visual error.

**Comment by WestLangley** [comment] 2015-10-13 16:14
The following change to the Phong shader solves the problem on my AMD Radeon.

```javascript
fragmentShader: [

	"#define PHONG",

	"uniform vec3 diffuse;",
	"uniform vec3 emissive;",
	"uniform vec3 specular;",
	"uniform float shininess;",
	"uniform float opacity;",

	THREE.ShaderChunk[ "common" ],
	THREE.ShaderChunk[ "color_pars_fragment" ],
	THREE.ShaderChunk[ "uv_pars_fragment" ],
	THREE.ShaderChunk[ "uv2_pars_fragment" ],
	THREE.ShaderChunk[ "map_pars_fragment" ],
	THREE.ShaderChunk[ "alphamap_pars_fragment" ],
	THREE.ShaderChunk[ "aomap_pars_fragment" ],
	THREE.ShaderChunk[ "lightmap_pars_fragment" ],
	THREE.ShaderChunk[ "emissivemap_pars_fragment" ],
	THREE.ShaderChunk[ "envmap_pars_fragment" ],
	THREE.ShaderChunk[ "fog_pars_fragment" ],
	THREE.ShaderChunk[ "lights_phong_pars_fragment" ],
	THREE.ShaderChunk[ "shadowmap_pars_fragment" ],
	THREE.ShaderChunk[ "bumpmap_pars_fragment" ],
	THREE.ShaderChunk[ "normalmap_pars_fragment" ],
	THREE.ShaderChunk[ "specularmap_pars_fragment" ],
	THREE.ShaderChunk[ "logdepthbuf_pars_fragment" ],

	"void main() {",

	"	vec3 outgoingLight = vec3( 0.0 );",
	"	vec4 diffuseColor = vec4( diffuse, opacity );",
	"	vec3 totalAmbientLight = ambientLightColor;",
	"	vec3 totalEmissiveLight = emissive;",
	"	vec3 shadowMask = vec3( 1.0 );",

		THREE.ShaderChunk[ "logdepthbuf_fragment" ],
	//	THREE.ShaderChunk[ "map_fragment" ],
		THREE.ShaderChunk[ "color_fragment" ],
		THREE.ShaderChunk[ "alphamap_fragment" ],
		THREE.ShaderChunk[ "alphatest_fragment" ],
		THREE.ShaderChunk[ "specularmap_fragment" ],
		THREE.ShaderChunk[ "normal_phong_fragment" ],
		THREE.ShaderChunk[ "lightmap_fragment" ],
		THREE.ShaderChunk[ "hemilight_fragment" ],
		THREE.ShaderChunk[ "aomap_fragment" ],
		THREE.ShaderChunk[ "emissivemap_fragment" ],

		THREE.ShaderChunk[ "lights_phong_fragment" ],
		THREE.ShaderChunk[ "shadowmap_fragment" ],

		"totalDiffuseLight *= shadowMask;",
		"totalSpecularLight *= shadowMask;",

		THREE.ShaderChunk[ "map_fragment" ], // moved - workaround for ATI bug

		"#ifdef METAL",

		"	outgoingLight += diffuseColor.rgb * ( totalDiffuseLight + totalAmbientLight ) * specular + totalSpecularLight + totalEmissiveLight;",

		"#else",

		"	outgoingLight += diffuseColor.rgb * ( totalDiffuseLight + totalAmbientLight ) + totalSpecularLight + totalEmissiveLight;",

		"#endif",

		THREE.ShaderChunk[ "envmap_fragment" ],

		THREE.ShaderChunk[ "linear_to_gamma_fragment" ],

		THREE.ShaderChunk[ "fog_fragment" ],

	"	gl_FragColor = vec4( outgoingLight, diffuseColor.a );",

	"}"

].join( "\n" )
```

The problem can be demonstrated in the fiddle, too.

works: http://jsfiddle.net/4Txgp/459/

          THREE.ShaderChunk[ "shadowmap_fragment" ],
          "  vec4 color = texture2D(texture, vUv);",

broken: http://jsfiddle.net/4Txgp/460/

          "  vec4 color = texture2D(texture, vUv);",
          THREE.ShaderChunk[ "shadowmap_fragment" ],

**Comment by Mugen87** [comment] 2015-10-13 16:30
Works for me too!

**Comment by mrdoob** [comment] 2015-10-13 16:59
@WestLangley what made you try that change?

**Comment by WestLangley** [comment] 2015-10-13 17:18
> @WestLangley what made you try that change?

That is a long story, but I recalled that I discovered the issue 2 1/2 years ago when I was hacking up a projective texturing example. Projective texturing uses similar code as shadow mapping. What was happening at the time was the wrong texture was being projected.

It appears that simply accessing the texture prior to the shadow map chunk

    vec4 texelColor = texture2D( map, vUv ); 

breaks the shadow -- even if texelColor is not used.

**Comment by codeka** [comment] 2015-10-14 12:05
That's incredible! It works for me, too. I've updated the Chrome bug with these details, hopefully with such a simple repro, we'll see some traction.

@mrdoob I fixed this in head for myself with codeka/three.js@148ce98b9e4c9456533ea24bef03ab438f3f58a0, but I'm probably missing some interactions with the other materials, so I won't make a PR for that...

**Comment by WestLangley** [comment] 2015-10-15 03:54
@codeka More info. There is no need to re-order the shader code. Use `MeshPhongMaterial` as is.

First, set

    	renderer.shadowMap.type = THREE.BasicShadowMap;

Use one `DirectionalLight` with shadow.

The offending line is in `shadowmap_fragment.glsl`.

	vec4 rgbaDepth = texture2D( shadowMap[ i ], shadowCoord.xy );

it is indexing into the diffuse map, instead of the shadow map.

Hardwiring it like so,

	vec4 rgbaDepth = texture2D( shadowMap[ 0 ], shadowCoord.xy ); // i is 0, anyway

the shadow renders correctly, with a diffuse map.

```glsl
#else // no percentage-closer filtering:

			shadowCoord.z += shadowBias[ i ];

			vec4 rgbaDepth = texture2D( shadowMap[ i ], shadowCoord.xy ); // offending line
			float fDepth = unpackDepth( rgbaDepth );

			if ( fDepth < shadowCoord.z )
				shadow = shadowDarkness[ i ];

#endif
```

**Comment by simonihmig** [comment] 2016-01-05 18:55
I can confirm this on my iMac, using Chrome, FF and Safari!
Can this issue be reopened then?

![image](https://cloud.githubusercontent.com/assets/1325249/12124495/179f649a-b3e6-11e5-982a-89fc5ca5f2ad.png)
