### ISSUE TITLE
WebGLRenderTarget doesn't work in WebXR

### ISSUE THREAD

**Issue by marcofugaro** [mrdoob/three.js#18746] opened 2020-02-26 10:41 UTC
Hey! I am loving the new WebXR integration! Recently I've been trying to achieve [soft shadows like this](https://codepen.io/marco_fugaro/full/gOpgWqO) in an AR scene. However the WebGLRenderTarget is not showing anything in the AR scene.

I've tried putting together the [AR hit-test](https://threejs.org/examples/?q=webx#webxr_ar_hittest) example and the [barebones rendertarget demo](https://codepen.io/marco_fugaro/pen/RwPpPzm?editors=1000) and this is the resullt.

<img src="https://user-images.githubusercontent.com/7217420/75336447-7384c180-588b-11ea-9336-6ab293c23a24.png" width="200" />

[Here is the code from this example](https://codepen.io/marco_fugaro/pen/mdJWyJW?editors=1000), you can try it live either by accessing the debug view on codepen or here on githack https://raw.githack.com/marcofugaro/shadows-issue/master/webxr_ar_hittest_rendertarget.html

##### Expected behavior
The rendertarget should output a black circle

<img src="https://user-images.githubusercontent.com/7217420/75336483-87302800-588b-11ea-8ba7-fe4188c98557.png" width="250" />

##### Three.js version

- [x] Dev
- [ ] r113
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [x] Android
- [ ] iOS

**Comment by Mugen87** [comment] 2020-02-26 11:28
Related #15614 and #15393.

**Comment by marcofugaro** [comment] 2020-02-26 13:25
Thank you @Mugen87 I've tried the proposed solutions and none of them worked. I've even tried to update the WebXRManager with the changes from this PR #15840.

I don't understand what is causing this. I just know it is something to do with `setFramebuffer()`, but I don't know how to fix it.

**Comment by Mugen87** [comment] 2020-02-26 14:03
`Reflector` in works in VR which internally works with a render target. You can check this out in [webxr_vr_sandbox](https://threejs.org/examples/webxr_vr_sandbox). The idea is to disable `xr`, perform the rendering and then enable xr again. Something like:
```js
var currentRenderTarget = renderer.getRenderTarget();
var currentXrEnabled = renderer.xr.enabled;
var currentShadowAutoUpdate = renderer.shadowMap.autoUpdate;

renderer.xr.enabled = false;
renderer.shadowMap.autoUpdate = false;

renderer.setRenderTarget( renderTarget );
renderer.clear();
renderer.render( scene, camera );

renderer.xr.enabled = currentXrEnabled;
renderer.shadowMap.autoUpdate = currentShadowAutoUpdate;
renderer.setRenderTarget( currentRenderTarget );
```

**Comment by marcofugaro** [comment] 2020-02-26 14:45
It now works perfectly, thank you!!

<img src="https://user-images.githubusercontent.com/7217420/75355364-aab89a00-58ae-11ea-9ae3-fa8ffdbcd0c2.png" width="200" />

I didn't know about that trick. Is it something that will be fixed, or is it gonna be documented in the future?

In any case, should I leave this issue open as a reminder?

**Comment by Mugen87** [comment] 2020-02-26 15:15
#15614 is still open so I think closing this one is okay.

> Is it something that will be fixed, or is it gonna be documented in the future?

It's not really a bug since the engine works as designed. However, things might be refactored in the future to make RTT in context of XR easier. TBH, I'm not sure about that. Such XR related API topics were deferred in the past until WebXR was stable. Since this is now the case, it might be worth to revisit this issue.

**Closed** 2020-02-26 15:51 UTC

**Comment by mrdoob** [comment] 2020-02-26 19:17
> Hey! I am loving the new WebXR integration! Recently I've been trying to achieve [soft shadows like this](https://codepen.io/marco_fugaro/full/gOpgWqO) in an AR scene. However the WebGLRenderTarget is not showing anything in the AR scene.

Those shadows look familiar... 🤓I should try to make an official example out of it.

**Comment by marcofugaro** [comment] 2020-02-26 22:36
@mrdoob yeah they're awesome! Nice idea you got there 🙂 

I just updated the MeshDepthMaterial so it renders from black to transparent, this lets me use these shadows in AR as shadowplanes! 🙌
https://designguidelines.withgoogle.com/ar-design/content/realism.html#realism-shadow-planes

Also I am doing two blur passes, the second gets rid of the artifacts that appear when you increase the blur amount! Maybe you can also put that in the example 🕺

**Comment by mrdoob** [comment] 2020-02-26 22:41
Nice! Actually, would you like to add a example with what you have so far?

**Comment by marcofugaro** [comment] 2020-02-26 23:08
Sure! Would love to. 

Should it be an "ar shadowplanes" or just "soft planar shadows"?

**Comment by mrdoob** [comment] 2020-02-26 23:14
Your example on codepen should be good enough. Maybe `webgl_shadow_contact`?

**Comment by marcofugaro** [comment] 2020-02-26 23:25
Sure!

Currently I am doing this for the black to transparent depth material, however it feels like a hack. Do you have a better approach?


```js
// like MeshDepthMaterial, but goes from black to transparent
const depthMaterial = new THREE.ShaderMaterial({
  uniforms: {
    darkness: { value: state.darkness },
  },
  vertexShader: THREE.ShaderChunk['depth_vert'],
  fragmentShader: `
    #define DEPTH_PACKING 3200
    uniform float darkness;
    ${THREE.ShaderChunk['depth_frag'].replace(
      'gl_FragColor = vec4( vec3( 1.0 - gl_FragCoord.z ), opacity );',
      'gl_FragColor = vec4(vec3(0.0), (1.0 - gl_FragCoord.z) * darkness);'
    )}
  `,
})
```

**Comment by mrdoob** [comment] 2020-02-26 23:37
That seems good enough for now.
