### ISSUE TITLE
[idea] only traverse sub trees that need updates.

### ISSUE THREAD

**Issue by trusktr** [mrdoob/three.js#15444] opened 2018-12-17 06:20 UTC
##### idea

I'm not sure how much performance gain this would have, but it is possible that we can traverse only the subtrees that need updates by keeping track of which objects have been updated.

basic impl:

- any time a property is changed (f.e. position or rotation), push the object onto an array of nodes that need update. (either make the properties setters to trigger this automatically, or require users to call `object.needsUpdate()`, the latter of which is a breaking change)
- in the `renderer.render` call, instead of traversing the scene tree, iterate on this array of nodes that need update.
- for each object in array of nodes that need update
  - perform `object.updateMatrix()`
  - if the new matrix result differs from before
    - add the object into a `Set` of subtree roots only if the object does not have an ancestor that is already a subtree root (simplest way is to traverse upward to the root and check if each object is in the `Set` of subtree roots)
- after finished iterating the array of nodes that need update, iterate the `Set` of subtree roots.
- for each root in `Set` of subtree roots
  - perform `root.updateMatrixWorld()`
- finally, render the WebGL like before.

**Comment by Mugen87** [comment] 2018-12-17 13:50
Also related to #14138. The PR is about optimizing the performance of updating world matrices.

**Comment by mrdoob** [comment] 2018-12-18 00:00
> I'm not sure how much performance gain this would have

Maybe you can implement it on your end and report performance numbers?

**Comment by mrdoob** [comment] 2018-12-18 16:42
@Mugen87 Agreed. I would cosider this another duplicate of #14138.

**Closed** 2018-12-18 16:42 UTC
Labels: Duplicate
