### ISSUE TITLE
Expose the objects holding constants 

### ISSUE THREAD

**Issue by Sairony** [mrdoob/three.js#17909] opened 2019-11-11 14:46 UTC
It's useful for editors & data files to be able to enumerate constants. So instead of having `"wrapS" : 1000` you can write `"wrapS" : "RepeatWrapping"`, or if you want to construct a drop down for all the different texture filter modes etc. What seems to be the best approach at the moment is to copy & paste `TEXTURE_FILTER`, I think it would be better if they were just exported as is instead. Not only is it a whole lot cleaner than copy & paste, but it also guarantees that they're in sync if new ones ever gets added or if it's changed.

**Comment by Mugen87** [comment] 2019-11-11 16:46
I'm not sure I understand. How should this exposition of constant values look like from your point of view?

**Comment by donmccurdy** [comment] 2019-11-11 16:53
Constants are exported as shown here: https://threejs.org/docs/#api/en/constants/Textures. I'm not sure I understand what you're suggesting as the alternative, sorry.

**Comment by makc** [comment] 2019-11-11 19:54
@Mugen87 @donmccurdy maybe what @Sairony means is, when you type `texture.wrapS` in the console, you get a number instead of readable string.

@Sairony you can do this, though:
![Screen Shot 2019-11-11 at 20 53 20 ](https://user-images.githubusercontent.com/242577/68616458-5affbf80-04c5-11ea-8755-2edd07e4dbe8.png)

**Comment by Mugen87** [comment] 2019-11-12 10:34
Okay, I see. But I doubt we are going to change this. For example comparisons between strings tend to be slower than between numbers. With some user level code, it should be easy to get the intended mapping.

**Comment by Sairony** [comment] 2019-11-12 10:57
What I mean is that if lets say I want to be able to convert load a json entry such as `"wrapS": "RepeatWrapping"` into a proper `wrapS` to be set on a texture I need to map the string value to its numeric value first. To do this now I need to copy & paste all the different constants & create the mapping from string to value. But if they were already exposed I could do something like this:
```
let stringToConstant = Object.assign( {}, TEXTURE_MAPPING, TEXTURE_WRAPPING, TEXTURE_FILTER );
if( stringToConstant.hasOwnProperty( valueFromJSON ) ) 
    return stringToConstant[ valueFromJSON ];
```

Or if in an editor I want to for example have a drop down to select texture filtering:

```
Object.keys( TEXTURE_FILTER ).forEach( x => dropDown.addEntry( x ) );
```

There's a lot of uses for being able to enumerate the different options for these. They're basically enums, it's kind of like the age old problem of converting enum entries to string & working with their mappings to their values in a lot of other languages.

**Comment by Mugen87** [comment] 2019-11-13 19:19
TBH, I don't understand. The constant values are already exposed. What's missing?

**Comment by donmccurdy** [comment] 2019-11-13 19:45
I guess @Sairony is asking for all constants to be scoped under a particular namespace for their purpose. For example:

```
THREE.Mapping.UV
THREE.Mapping.CUBE_REFLECTION
THREE.Mapping.EQUIRECTANGULAR_REFLECTION
...
THREE.Wrapping.REPEAT
THREE.Wrapping.CLAMP_TO_EDGE
THREE.Wrapping.MIRRORED_REPEAT
```

From that perspective, the user can enumerate the choices in a dropdown with `Object.keys(THREE.Wrapping)` rather than having to maintain a matching list.

All else being equal I agree the scoped constants might be nice, but this seems like a major a hassle to change now, so I'm not sure we can justify moving all the constants.

**Comment by Mugen87** [comment] 2019-11-13 19:59
Thanks for this clarification! Indeed, I don't think we make such a change. However, could the OP derive the desired information from the TS declaration file in some way? It seems, the structure for this is already there. 

https://github.com/mrdoob/three.js/blob/4ab3edd67a233a5856998580dbe1a1d9f098101e/src/constants.d.ts#L120-L129

**Comment by looeee** [comment] 2019-11-14 00:33
> I guess @Sairony is asking for all constants to be scoped under a particular namespace for their purpose. 

Related: #12579, #12972

**Comment by Mugen87** [comment] 2019-11-14 10:41
In fact, this issue is a duplicate of #12579. Closing then.

**Closed by Mugen87** 2019-11-14 10:41 UTC
