### ISSUE TITLE
glb exporter about animation

### ISSUE THREAD

**Issue by Frankling** [mrdoob/three.js#29938] opened 2024-11-21 01:10 UTC
### Description

when I import the same glb with animations twice to threejs editor, then I export it as new glb file, but this glb 's animation doesn't work on the second object

### Reproduction steps

1.
2.
3.

### Code

```js
// code goes here
```

### Live example

* [jsfiddle-latest-release WebGLRenderer](https://jsfiddle.net/3mrkqyea/)
* [jsfiddle-dev WebGLRenderer](https://jsfiddle.net/gcqx26jv/)
* [jsfiddle-latest-release WebGPURenderer](https://jsfiddle.net/8L2jkmx7/)
* [jsfiddle-dev WebGPURenderer](https://jsfiddle.net/L3n1w4yh/)

### Version

170

**Comment by mrdoob** [comment] 2024-11-21 05:32
Please share the glb file.

**Comment by Frankling** [comment] 2024-11-21 07:05
[xbot.zip](https://github.com/user-attachments/files/17841197/xbot.zip)
@mrdoob

**Comment by Mugen87** [comment] 2024-11-21 09:44
This should be a duplicate of #25179.

**Closed** 2024-11-21 10:01 UTC
Labels: Duplicate
