### ISSUE TITLE
v85 crashes browser on older devices

### ISSUE THREAD

**Issue by dylnmc** [mrdoob/three.js#11448] opened 2017-06-05 17:10 UTC
##### Description of the problem 

using `camera.lookAt` and projection from camera frequently crashes older devices in release 85. I noticed this bug on an older iPad (version 8.1.3).

Here is jsfiddle that crashes safari: https://jsfiddle.net/qy7anq9w/ ((click or touch) and drag in the white are to initially load the scene -- sorry; I don't know why the scene doesn't load initially).

On crashing the first three times, the browser says "A problem has occurred with this webpage so it was reloaded." Upon the third crash, it does not reload the page, but rather, it just says something like "there was an error in this webpage.

I noticed that in version 85, you updated the `camera.lookAt` to be more robust, but I wasn't sure if it was **that** --**OR**-- **the projection from camera** in the `getScreenPosition` at the end of the jsfiddle.

Finally, I wanted to note that using threejs version 84 (and version 78 -- which had a weird line issue with THREE.CircleGeometr[ies]) worked. So, it must be something with ram consumption in v85.

##### Three.js version

85

##### Browser

safari

##### OS

iOs (older -- tested on v. 8.1.3)

---

edit: sorry about the fiddle. It behaves oddly on touch devices even though I call `preventDefault`. Also, *again* ... I do not know why the scene doesn't load initially, but if you just click+drag inside the scene (the scene fills the body), it will properly load the scene. *insert shrug* ==> I would debug, but I am at work, and although I received permission to submit this bug, I do not wish to spend any more time debugging, as I have things to do. I hope you all understand; thanks.

---

edit 2: I forgot to mention this earlier, but I could only reproduce the bug when the iPad was not plugged into the computer and dev mode (with console) was enabled ... pretty weird. Therefore, I couldn't figure out exactly what the cause of the bug was.

**Comment by dylnmc** [comment] 2017-06-05 17:18
this fiddle https://jsfiddle.net/s5s15Lj9/ , for example, does not crash safari -- all I did was swap out v85 for v84.

**Comment by mrdoob** [comment] 2017-06-06 00:17
Is there any way you could reduce that jsfiddle? There is too much going on right now.

**Comment by dylnmc** [comment] 2017-06-06 00:57
When I get some spare time, yes. (It might be later tonight or tomorrow evening.) Sorry -- I didn't mean to make you whittle it down; I know how many open issues you have. I can also check tomorrow to see if it is the projection from camera or camera.lookAt (or only both of them together) that is causing the problem, so that I can narrow it down a bit.

**Comment by Mugen87** [comment] 2017-09-07 09:49
@dylnmc Any news on this.

**Comment by dylnmc** [comment] 2017-09-08 11:07
I have no way of testing this now. A couple months ago, things were quite hectic (although this is just an excuse and I certainly could have found time), and the internship was ending. I actually am starting to work at the same place and will see what I can do.

Unfortunately, my "lunch breaks" this time around will be filled with classes, but I am sure that I can find some time to narrow down the cause—perhaps later next week.

Since it does not seem like anyone has referenced it, maybe it is outdated or not reproducible. 

Sorry for the delay, and if deemed still an open issue, I'll look into it next week,
dylnmc

**Comment by Mugen87** [comment] 2017-09-18 15:41
Closing. We can reopen this if the issue is still existing.

**Closed by Mugen87** 2017-09-18 15:41 UTC
Labels: Regression
