### ISSUE TITLE
Problem with shadows in chrome 105

### ISSUE THREAD

**Issue by anbello** [mrdoob/three.js#24587] opened 2022-09-02 15:32 UTC
**Describe the bug**

On chrome 105 shadows are no more visualized.

**To Reproduce**

Go to https://threejs.org/examples/?q=shadow#webgl_shadowmap_viewer
trying this with firefox is ok, with chrome 104 ok with chrome 105 no shadows

**Screenshots**

Firefox
![firefox](https://user-images.githubusercontent.com/4920098/188183376-656c44c9-37ad-4dfa-95aa-1d893f005a4a.png)

chrome 105
![chrome-105](https://user-images.githubusercontent.com/4920098/188183417-675a863d-e97a-44c9-8f78-3218c5623798.png)

**Platform:**

 - Device: [Desktop]
 - OS: [Linux]
 - Browser: [Chrome]
 - Three.js version: [r144]

**Comment by Mugen87** [comment] 2022-09-02 17:47
> with chrome 104 ok with chrome 105 no shadows

I'm afraid I can't reproduce the issue on Windows. Both browser versions work as expected.

**Comment by anbello** [comment] 2022-09-02 21:28
> > with chrome 104 ok with chrome 105 no shadows
> 
> I'm afraid I can't reproduce the issue on Windows. Both browser versions work as expected.

Can you try on Linux please?

**Comment by Mugen87** [comment] 2022-09-03 07:16
Sorry, I don't have a Linux OS at hand. On macOS, the examples looks as expected as well. Tested with Chrome 105.0.5195.102.

**Comment by anbello** [comment] 2022-09-03 10:36
> Sorry, I don't have a Linux OS at hand. On macOS, the examples looks as expected as well. Tested with Chrome 105.0.5195.102.
> 
> Can you please test if using Chrome Canary fixes the issue for you?

Canary doesn't exist for Linux, anyway I tested chrome beta that is ver. 106 and it's OK, no shadows problem.

**Comment by Mugen87** [comment] 2022-09-03 10:38
Okay, closing then.

**Closed by Mugen87** 2022-09-03 10:38 UTC
Labels: Browser Issue
