### ISSUE TITLE
FBX Object .clone() method not working properly

### ISSUE THREAD

**Issue by Bravos123** [mrdoob/three.js#14647] opened 2018-08-05 09:42 UTC
##### Three.js version

- [ ] Dev
- [x] r95
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

*I previously posted this problem on Stackoverflow but got no responses. However I decided to post it here as well as it's only a problem with FBX models and not OBJ models, which makes it look like some kind of bug.*

I am loading FBX models for my project. I Want to create multiple objects of the same FBX model but loading each separately is very inefficient so I would like to save one loaded model and clone it. This concept is working with the .OBJ format.

Everything works as expected but then I use "model.clone();" nothing really happens.
The model is no longer visible but I get no errors. If you compare the cloned model with the original they look exactly the same so I don't know why it's not showing up.

The part of the code where you can compare the two is:
"var sendModel = model;//Works
//var sendModel = model.clone();//Doesn't works"
Starting at line 30.

Here is some simplified working source code:

    <!DOCTYPE html>
    <html>
    <head>
    </head>
    <body>
	<script src="https://vitalkia.com/jsLibraries/zlib.min.js"></script>
	<script src="https://threejs.org/build/three.js"></script>
	<script src="https://threejs.org/examples/js/loaders/FBXLoader.js"> 
    </script>
	<script>
		var aspectRatio = 240 / 135;
		var scene;
		var renderer;
		var loaderFBX;
		var camera = new THREE.PerspectiveCamera(45, aspectRatio, 1, 10000);

		

		//Actual code
		//Setus up scene and renderer
		sceneSetup();
		
		//Load fbx and render
		//IGNORE ERROR ABOUT NOT FINDING THE RIGHT TEXTURE. It still works
		loaderFBX.load("https://threejs.org/examples/models/fbx/Samba Dancing.fbx", function(model){
			//Sending the object "model" works
			//But using model.clone() does not. It doesn't give any errors or anything, it's just not visible
			//If you compare the cloned model with the original they look exactly the same.
		
			var sendModel = model;//Works
			//var sendModel = model.clone();//Doesn't works
			console.log("Original: ");
			console.log(model);
			console.log("Cloned: ");
			console.log(model.clone());
		
			calcDistance(sendModel);
		
			scene.add(sendModel);
			renderer.render(scene, camera);
		});

		function calcDistance(model){
			var bbox = new THREE.Box3().setFromObject(model);

			var camDistance = bbox.max.z;
			if(bbox.max.x > camDistance){
				camDistance = bbox.max.x;
			}
			if(bbox.max.y*aspectRatio > camDistance){
				camDistance = bbox.max.y*aspectRatio;
			}
						    
			camera.position.z = camDistance;
			model.position.x -= bbox.getCenter().x;
			model.position.y -= bbox.getCenter().y;
		}

		function sceneSetup(){
			loaderFBX = new THREE.FBXLoader();
			scene = new THREE.Scene();
			renderer = new THREE.WebGLRenderer({antialias: true, alpha: true});
			renderer.setSize(240, 135);
			document.body.appendChild(renderer.domElement);
			var light1 = new THREE.PointLight(0xffffff, 1, 100000000);
			light1.position.set(0, 0, 15);
			scene.add(light1);
			var newLightPoint = new THREE.HemisphereLight(0x8be2ff, 0xfff9cf, 0.55);
			scene.add(newLightPoint);
			camera.position.set(0, 0, 100);
			scene.add(camera);
		}
	</script>
</body>
</html>

**Comment by looeee** [comment] 2018-08-05 11:02
The cloned objects are not actually the same. 

Two differences I've noticed are that the animation clips are not copied over to the cloned object, and the cloned skinned mesh's `skeleton.bones` arrays are empty.

**Comment by Bravos123** [comment] 2018-08-05 13:11
Where is skeleton.bones stored? I can't see it anywhere inside the object, or is it generated?

**Comment by looeee** [comment] 2018-08-05 13:44
This is a duplicate of #5878, and there is a proposed fix in #14494. I'm going to close this, please read through the discussion there to understand why this is occurring. 

You'll find the skeleton in `object.children[ 1 ].skeleton` and `object.children[ 2 ].skeleton`.

Regarding the animations, you'll have to copy them over manually. There is no "official" place to put animations, so they can't be cloned. With the FBXLoader, we're currently just dumping them all in the top level returned object, but there is no specific reason to do that.

**Comment by looeee** [comment] 2018-08-05 13:45
See also ##11574

**Closed by looeee** 2018-08-05 13:44 UTC

**Comment by donmccurdy** [comment] 2018-08-05 14:35
> Regarding the animations, you'll have to copy them over manually. There is no "official" place to put animations, so they can't be cloned

They also do not need to be cloned for reuse (when the skeleton is right) - just make a new mixer with the new model as its root and apply the same clips.
