### ISSUE TITLE
[FR]customDepthMaterial support for `onBeforeRender`

### ISSUE THREAD

**Issue by farfromrefug** [mrdoob/three.js#22937] opened 2021-12-02 14:19 UTC
**Is your feature request related to a problem? Please describe.**

Possibility to use a shared material for `customDepthMaterial` while changing uniforms on a per object basis
**Describe the solution you'd like**

add support for `onBeforeRender` to `WebGLShadowMap`

You would expect `onBeforeRender` to work just like it does for normal object rendering.

**Comment by Mugen87** [comment] 2021-12-02 14:25
Seems to be a duplicate of #14921.

**Comment by farfromrefug** [comment] 2021-12-02 14:29
@Mugen87 indeed seems like it is. What s the state on that PR for `onBeforeShadow`?  Locally i tested with `onBeforeRender` in `WebGLShadowMap` and it works great. Will it be accepted if i make a PR or is there a show stopper?

**Comment by Mugen87** [comment] 2021-12-02 14:37
There is already a PR. #17932

It wasn't merged because there was no consensus in #14921. Against this backdrop, I'm afraid it does not make sense to file a new PR.

**Closed by Mugen87** 2021-12-02 14:37 UTC

**Comment by farfromrefug** [comment] 2021-12-02 19:46
@Mugen87 i can understand for you to close this. But i am worried you closing this means this FR will simply be ignored as the old issue seems to not be going anywhere.
Moreover as `WebGLShadowMap` is not written as an es6 class there is no way to override `renderObject` to add custom behavior until this gets sorted.
Would you accept a PR to move `WebGLShadowMap` to es6 ?

**Comment by Mugen87** [comment] 2021-12-04 10:20
> But i am worried you closing this means this FR will simply be ignored as the old issue seems to not be going anywhere.

Just because the discussion in #14921 is stalled does not mean the feature request is not accepted. It's in general better to post at existing open issues than creating a new one.

**Comment by farfromrefug** [comment] 2021-12-04 11:12
Agree. Sorry i did not find the other issue first. Will reply there to mention i need it too
