### ISSUE TITLE
LinesSegments with World Units have Visible Artifacts from Various Angles (Fat Lines Example)

### ISSUE THREAD

**Issue by dyarosla** [mrdoob/three.js#26916] opened 2023-10-07 23:39 UTC
### Description

Artifacts can be see with World Unit lines, visible in webgl_lines_fat example. Attached image with circled problematic regions.

### Reproduction steps

1. Go to https://threejs.org/examples/?q=line#webgl_lines_fat
2. Toggle world units to on.
3. Examine the scene from various angles with LineWidths > 1.

### Code

Relates to LineMaterial.js

### Live example

https://threejs.org/examples/?q=line#webgl_lines_fat

### Screenshots

<img width="1398" alt="Screenshot 2023-10-07 at 5 29 31 PM" src="https://github.com/mrdoob/three.js/assets/1227028/a919f11e-66e8-43af-a34d-77601054773e">

### Version

r157

### Device

Desktop

### Browser

Chrome

### OS

MacOS

**Comment by gkjohnson** [comment] 2023-10-09 05:07
Are you able to reproduce and show the issue with just a single line segment?

The original thread on the perspective attenuated lines (#16912) contains more information on how exactly the feature works - the vertices effectively form a bounding box around the capsule and then a ray / line segment distance check is used in the fragment shader. It's possible that there's an issue in forming the bounding box vertices or something along those lines if you'd like somewhere to start and take a deeper look.

**Comment by dyarosla** [comment] 2023-10-09 05:13
I’m unsure if this occurs on a single line segment.

Also is there any reason why this isn’t using rectangular prisms per line segment instead of three quads (as I take it this is where things landed based on that thread)? A rectangular prism will always entirely contain a capsule and I’ve had success in using them for rendering thick lines with a similar approach elsewhere.

**Comment by gkjohnson** [comment] 2023-10-09 05:26
> I’m unsure if this occurs on a single line segment.

Have you tried to reproduce it? I'm not sure where else this kind of artifact could be coming from if not reproduceable with a single segment - it looks like sharper corners near the termination of the lines.

> Also is there any reason why this isn’t using rectangular prisms per line segment instead of three quads

The PR added a flag to the existing Line2 implementation which only supported screenspace thickness and therefore just used three connected quads originally. In theory those three quads (well only really two of them) could be used to fully define the projection of a rectangular prism that was facing the camera which seemed like a simple solution and didn't require changing geometry to toggle. I still think this is a fine solution as long as the math is being handled correctly.

**Comment by dyarosla** [comment] 2023-10-09 06:40
Ok, I was able to reproduce the issues in a single line segment. They are harder to see but there are various angles under which you can see the segment breaking down. I used one line segment from 0,0,0 to 10,10,10. I looked at it from glazing angles. You can see some hard edges on both the closest end cap and the furthest endcap.

<img width="252" alt="Screenshot 2023-10-09 at 12 33 10 AM" src="https://github.com/mrdoob/three.js/assets/1227028/b99d83cf-6666-442c-a76f-3bcfa904abba">
<img width="252" alt="Screenshot 2023-10-09 at 12 33 26 AM" src="https://github.com/mrdoob/three.js/assets/1227028/5add7d45-34f3-4c04-b3c1-48c6b66bca11">

**Comment by dyarosla** [comment] 2023-10-09 06:44
With two line segments other issues are prevalent.
See the blue cap have a hard edge here:
![image](https://github.com/mrdoob/three.js/assets/1227028/86a418e9-7db4-4ef3-95a4-dc108b731f78)

**Comment by gkjohnson** [comment] 2023-10-09 07:14
> In sum I think there are two problems. One is the single line segment issue which is likely a limitation of how using quads instead of a rectangular prism behaves (or some quad calculation is wrong for the endcaps)
>
> The second, with the jaggy edges, is likely due to the wrong zbuffer writing not using the raycast depth.

Agreed. I mentioned the limitation of depth writing [here](https://github.com/mrdoob/three.js/pull/16912#issuecomment-511647423) in the original PR. If there's a simple function that gives the surface intersection of a capsule then `gl_FragDepth` could be be written to which would fix this issue as well as intersections with other geometry. And since `discard` is already used in the shader I don't think this would have a meaningful impact on performance as long as the intersection function was fast.

The quad issue would need to be handled separately. I won't be able to look into this at the moment but if you'd like to try addressing either of them I'm happy to take a look at PRs and help get the fixes merged.

**Closed** 2023-12-11 09:44 UTC
Labels: Addons
