### ISSUE TITLE
Line2 negative scale

### ISSUE THREAD

**Issue by arthur7921** [mrdoob/three.js#21772] opened 2021-05-03 07:43 UTC
when i set a object(which instanced Line2).scale.x < 0, Line2 disappeared? is it normal?

***Live example***

* [jsfiddle-latest-release](https://codesandbox.io/s/lucid-browser-36v9e)

**Comment by arthur7921** [comment] 2021-05-03 08:04
just change public/client.js lione 100: -1 to 1, you will see Lines

**Comment by Mugen87** [comment] 2021-05-03 11:03
What is your use case for using a negative scale for lines?

**Comment by WestLangley** [comment] 2021-05-03 13:47
Duplicate of #19629.

**Closed by WestLangley** 2021-05-03 13:47 UTC

**Comment by WestLangley** [comment] 2021-05-03 13:49
>What is your use case for using a negative scale for lines?

Oh, it would be nice to know the answer to that question. :-)

**Comment by arthur7921** [comment] 2021-05-04 02:33
> > What is your use case for using a negative scale for lines?
> 
> Oh, it would be nice to know the answer to that question. :-)

draw a box line containes a object，and then mabey mirror the object

**Comment by arthur7921** [comment] 2021-05-04 03:14
> Duplicate of #19629.

Thx,  sovle my problem!
