### ISSUE TITLE
GLTFExporter unable to process compressed texture

### ISSUE THREAD

**Issue by stefandouw** [mrdoob/three.js#24321] opened 2022-07-06 15:28 UTC
**Describe the bug**

When trying to export a scene that contains a material that uses a compressed texture format an error will occur and the export will fail. Format number is 36492 which I believe is COMPRESSED_RGBA_BPTC_UNORM_EXT: https://www.khronos.org/registry/webgl/extensions/EXT_texture_compression_bptc/ 

**To Reproduce**

1. Convert a .jpg image with the tools provided by khronos: toktx --t2 --genmipmap --bcmp --2d texture.ktx2 texture.jpg
2. Use the image as a texture with the KTX2Loader
3. Attempt to export a scene that has the object with the KTX2 texture using the GLTFExporter
4. Error message appears in the browser console

**Screenshots**

![image](https://user-images.githubusercontent.com/9696122/177587129-691d9fa9-762b-4c13-93be-4b6f12c56d5d.png)

**Platform:**

 - Device: Desktop
 - OS: Windows 10
 - Browser: Chrome
 - Three.js version: 135

**Comment by donmccurdy** [comment] 2022-07-06 19:06
Related: 

- https://github.com/mrdoob/three.js/issues/22035
- https://github.com/mrdoob/three.js/issues/13911

As the error message suggests, GLTFExporter cannot export compressed textures. If we were to fix this, I believe the steps would be:

1. Add a helper function somewhere (`examples/jsm/utils/`?) that converts a CompressedTexture to an uncompressed Texture instance, using WebGLRenderer.
2. Either invoke that helper automatically in GLTFExporter, or require users to do so manually

Note that the process is lossy — GLTFExporter cannot reproduce the original compressed KTX2 file in any case, and I don't see a practical way around that. So I'm undecided about whether we should go this direction.

**Comment by Mugen87** [comment] 2022-07-07 08:02
Looking at the OP's workflow, it might be better to not create the compressed texture first and then using it for export. In general, the compression should be applied during the export or after it with a tool like `gltfpack`.

Nevertheless, I understand there are situations where compressed assets are loaded and users want to include it in other workflows (not just for rendering). A new helper would be a good start although the docs should highlight the mentioned consequences.

**Comment by stefandouw** [comment] 2022-07-07 08:48
Exporting a scene is only a small part of our application, users typically place various objects in an interactive scene and we provide the option to render the scene in high quality on a server. Therefore we would like to optimize the interactive experience by decreasing the memory footprint. Unfortunately we can't implement compressed textures right now until there is a solution for GLTFExporter.

**Comment by Mugen87** [comment] 2023-11-15 14:33
Closing since with the merge of #23321 the original runtime error should be fixed.

**Closed by Mugen87** 2023-11-15 14:33 UTC
Labels: Suggestion
