### ISSUE TITLE
[idea] Switch to semver versioning.

### ISSUE THREAD

**Issue by trusktr** [mrdoob/three.js#7067] opened 2015-08-28 19:18 UTC
What you have now is basically the equivalent of

```
0.1.0
0.2.0
0.3.0
0.4.0
0.5.0
0.6.0
...
0.71.0
```

in semver, but you're not taking advantage of the Major and Patch numbers to convey extra information about changes to the library. Check out semver for a basic explanation: http://semver.org/

**Comment by mrdoob** [comment] 2015-08-29 01:00
Duplicate of #3102

**Closed by mrdoob** 2015-08-29 01:00 UTC
Labels: Suggestion
