### ISSUE TITLE
Material cache non-unique hash - onBeforeCompile.toString

### ISSUE THREAD

**Issue by f1cognite** [mrdoob/three.js#15948] opened 2019-03-11 15:44 UTC
##### Description of the problem

Two different materials is being recognised as the same material here: https://github.com/mrdoob/three.js/blob/c94018cb475e1c357671138e78741b1a162e0bf9/src/renderers/webgl/WebGLPrograms.js#L218

```js
let someString = 'a';
const materialA = new THREE.MeshBasicMaterial();
materialA.onBeforeCompile = function() {
  // do something with someString
}

someString = 'b';
const materialB = new THREE.MeshBasicMaterial();
materialB.onBeforeCompile = function() {
  // do something with someString
}
```

The hash of those materials will be the same when using [`onBeforeCompile.toString()`](https://github.com/mrdoob/three.js/blob/c94018cb475e1c357671138e78741b1a162e0bf9/src/renderers/webgl/WebGLPrograms.js#L250) but they do different things because of different variable values.

So the compiled version of `materialA` is equal to the compiled version of `materialB` when they are not equal.

##### Three.js version

- [ ] Dev
- [x] r96
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by pailhead** [comment] 2019-03-16 19:05
This is not a bug this is a feature.

**Comment by Mugen87** [comment] 2019-03-17 10:26
This issue can be considered as a "Won't fix" (see https://github.com/mrdoob/three.js/issues/14245#issuecomment-397957636).

@f1cognite Please use one of the existing workarounds to avoid the issue.

**Closed by Mugen87** 2019-03-17 10:26 UTC
