### ISSUE TITLE
RENDER WARNING in two examples on Windows Chrome

### ISSUE THREAD

**Issue by takahirox** [mrdoob/three.js#14623] opened 2018-08-02 19:18 UTC
##### Description of the problem

I see RENDER WARNING in the two examples on my Windows + Chrome.

    [.Offscreen-For-WebGL-000002652FEC91C0]RENDER WARNING: Render count or primcount is 0.

https://threejs.org/examples/webgl_octree.html
https://threejs.org/examples/webgl_materials_cubemap_dynamic.html

But I don't see on FireFox nightly. It could be (Windows) Chrome specific issue?

##### Three.js version

- [x] Dev
- [x] r95
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by haroldiedema** [comment] 2018-08-02 19:44
Possible duplicate of #8395 ?

It occurred in PlayCanvas as well back in 2016: https://github.com/playcanvas/fonts/issues/5

**Comment by Mugen87** [comment] 2018-08-03 08:16
I also see the warnings with Chrome on macOS (10.13.6).

**Comment by Mugen87** [comment] 2018-08-03 08:50
`webgl_octree` should be okay now.

https://rawgit.com/mrdoob/three.js/dev/examples/webgl_octree.html

**Closed** 2018-08-03 09:16 UTC
