### ISSUE TITLE
VideoTexture uses the WebM source to display an exception

### ISSUE THREAD

**Issue by liaohengfan** [mrdoob/three.js#15361] opened 2018-12-03 14:10 UTC
##### Description of the problem
The actual situation is to use WebM as the source of Videotexture in three.js. The texture rendered has all the historical content of the video, not just the current frame of the video. But the content displayed on the Chrome VideoElements is normal.This error appears in the Chrome browser version 70.0.3538.110,  and there is no problem in the chrome 69 version, this situation makes me very trouble, thank you.

##### Three.js version

- [ ] Dev
- [ ] r99
- [ ] ...

##### Browser

- [ ] Chrome

##### OS
- [ ] Windows

**Comment by Mugen87** [comment] 2018-12-03 14:13
I don't understand why you have created a new issue. If it's a problem in the browser, this section is the wrong place for your post.

**Comment by Mugen87** [comment] 2018-12-03 14:37
Playing a WebM video with a `video` tag is something different than using a WebM video as a texture. Can you try to reproduce the problem without `three.js` but with plain WebGL? A small test case that demonstrates the issue would be a huge help for the Chromium team.

**Comment by Mugen87** [comment] 2018-12-04 10:51
BTW: The following example uses a WebM video and I'm not able to see a problem with Chrome 70.0.3538.110. 

https://threejs.org/examples/webgl_video_panorama_equirectangular.html

**Comment by liaohengfan** [comment] 2018-12-04 14:50
My project is to incorporate a dynamic character explanation in a panorama, so I need a transparent channel webm, VideoTexture format RGBA, I will provide screenshots displayed in different versions tomorrow, thank you for your attention.  :-)

**Comment by liaohengfan** [comment] 2018-12-05 01:54
This displays in chrome 70.0.3538.110:
![image](https://user-images.githubusercontent.com/11660002/49483584-be717e00-f86e-11e8-8b8a-6074c4893a21.png)

This displays in chrome 69:
![image](https://user-images.githubusercontent.com/11660002/49484888-a3edd380-f873-11e8-906a-0ee5cda5861d.png)

**Comment by Mugen87** [comment] 2018-12-05 11:30
Ca you share a link to your app?

**Comment by liaohengfan** [comment] 2018-12-05 14:10
Sorry, this project material can't be shared. I think you just lack a transparent WebM. I'll try to make one for you tomorrow.

**Comment by liaohengfan** [comment] 2018-12-06 03:01
This is the latest test result:
![image](https://user-images.githubusercontent.com/11660002/49558414-f13a7580-f945-11e8-8e45-3b678801c12e.png)
`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
    <script src="//threejs.org/build/three.js"></script>
</head>
<body>
<video src="./test.webm" id="webm_element" autoplay="autoplay" loop></video>
<script>
    function Demo(){
        this.init();
    }
    Demo.prototype.camera=null;
    Demo.prototype.renderer=null;
    Demo.prototype.scene=null;
    Demo.prototype.mesh=null;
    Demo.prototype.init=function(){
        this.camera = new THREE.PerspectiveCamera( 70, window.innerWidth / window.innerHeight, 1, 1000 );
        this.camera.position.z = 120;
        this.scene = new THREE.Scene();

        var videoElement=document.getElementById('webm_element');

        var texture = new THREE.VideoTexture(videoElement);
        texture.format=THREE.RGBAFormat;
        var geometry = new THREE.PlaneGeometry( 200, 200, 1 ,1);
        var material = new THREE.MeshBasicMaterial( { map: texture,transparent:true } );
        var mesh = new THREE.Mesh( geometry, material );
        this.scene.add( mesh );
        this.renderer = new THREE.WebGLRenderer( { antialias: true } );
        this.renderer.setClearColor(0x999999,1);
        this.renderer.setPixelRatio( window.devicePixelRatio );
        this.renderer.setSize( 500, 500 );
        document.body.appendChild( this.renderer.domElement );
        this.enterframe=()=>{
            requestAnimationFrame(this.enterframe);
            this.renderer.render(this.scene, this.camera);
        };
        this.enterframe();
    };
    window.onload=function(){
        new Demo();
    }

</script>
</body>
</html>`
WebM alpha file  zip :
[webm.zip](https://github.com/mrdoob/three.js/files/2651538/webm.zip)

**Comment by liaohengfan** [comment] 2018-12-06 03:04
![image](https://user-images.githubusercontent.com/11660002/49558591-8f2e4000-f946-11e8-8ac0-0c25a0346e45.png)

`function Demo(){
        this.init();
    }
    Demo.prototype.camera=null;
    Demo.prototype.renderer=null;
    Demo.prototype.scene=null;
    Demo.prototype.mesh=null;
    Demo.prototype.init=function(){
        this.camera = new THREE.PerspectiveCamera( 70, window.innerWidth / window.innerHeight, 1, 1000 );
        this.camera.position.z = 120;
        this.scene = new THREE.Scene();

        var videoElement=document.getElementById('webm_element');

        var texture = new THREE.VideoTexture(videoElement);
        texture.format=THREE.RGBAFormat;
        var geometry = new THREE.PlaneGeometry( 200, 200, 1 ,1);
        var material = new THREE.MeshBasicMaterial( { map: texture,transparent:true } );
        var mesh = new THREE.Mesh( geometry, material );
        this.scene.add( mesh );
        this.renderer = new THREE.WebGLRenderer( { antialias: true } );
        this.renderer.setClearColor(0x999999,1);
        this.renderer.setPixelRatio( window.devicePixelRatio );
        this.renderer.setSize( 500, 500 );
        document.body.appendChild( this.renderer.domElement );
        this.enterframe=()=>{
            requestAnimationFrame(this.enterframe);
            this.renderer.render(this.scene, this.camera);
        };
        this.enterframe();
    };
    window.onload=function(){
        new Demo();
    }`

WebM file:
[webm.zip](https://github.com/mrdoob/three.js/files/2651542/webm.zip)

**Comment by liaohengfan** [comment] 2018-12-06 03:07
This is the latest test result:
![image](https://user-images.githubusercontent.com/11660002/49558691-ed5b2300-f946-11e8-900e-05a27a500965.png)

coding files:
[WebMAlphaVideoTexture.zip](https://github.com/mrdoob/three.js/files/2651549/WebMAlphaVideoTexture.zip)

**Comment by Mugen87** [comment] 2018-12-06 14:55
[WebM_Test.zip](https://github.com/mrdoob/three.js/files/2653491/WebM_Test.zip)

I have refactored your demo a bit and added a "play" button. I'm actually not able to reproduce the error with Chrome 71.0.3578.80.

**Comment by liaohengfan** [comment] 2018-12-07 07:16
Your computer is Windows? My environment is Win10, 71.0.3578.80. Version is not solved.
![image](https://user-images.githubusercontent.com/11660002/49633045-e4478000-fa32-11e8-8bd4-715257be7734.png)

**Comment by mrdoob** [comment] 2018-12-07 09:12
The problem is with a transparent video, right?

**Comment by liaohengfan** [comment] 2018-12-07 10:08
Yes, a transparent WebM video file. Thank you.

**Comment by Mugen87** [comment] 2018-12-07 10:46
> Your computer is Windows?

No, I'm on macOS 10.14.1. Unfortunately, I'm not able to test with Windows.

I strongly recommend you use the isolated test case and file a bug right here: 

https://bugs.chromium.org/p/chromium/issues/list

In any event, this issue can't be fixed by `three.js`.

**Closed by Mugen87** 2018-12-07 10:46 UTC
Labels: Browser Issue

**Comment by liaohengfan** [comment] 2018-12-07 11:09
I've already feedback to chrome. Thank you.

**Comment by kainino0x** [comment] 2018-12-07 19:07
For reference, the Chrome bug is https://crbug.com/912842.
