### ISSUE TITLE
`CanvasTexture` broken since deb5a9e

### ISSUE THREAD

**Issue by Wyn-Price** [mrdoob/three.js#22864] opened 2021-11-20 01:31 UTC
**Describe the bug**

Commit deb5a9e7dcb88e7580f53bca6d174796055f3afa has broken `CanvasTexture`. When calling `needsUpdate = true`, the texture then spits out a bunch of errors:
```
[.WebGL-0000084C000AD400] GL_INVALID_OPERATION: Level of detail outside of range.
[.WebGL-0000084C000AD400] GL_INVALID_OPERATION: Texture format does not support mipmap generation.
[.WebGL-0000084C000AD400] GL_INVALID_OPERATION: The destination level of the destination texture must be defined.
```
This does not happen when using `Texture`

From what I can tell, this is caused [here](https://github.com/mrdoob/three.js/commit/deb5a9e7dcb88e7580f53bca6d174796055f3afa#diff-6bdac4da85be606f09e2ab24b41c761b23ced0d9acaa720e2f2200d938a714e9R739-R753). 
When testing, `CanvasTexture` had `useTexStorage` as true, and `allocateMemory` as false.
When testing, `Texture` had `useTexStorage` as true, and `allocateMemory` as true.

**To Reproduce**
Setup a texture using CanvasTexture, then call `texture.needsUpdate = true`

***Code***
Breaks:
```js
var texture = new THREE.CanvasTexture(canvas)
texture.needsUpdate = true
```
Does not break:
```js
var texture = new THREE.Texture(canvas)
texture.needsUpdate = true
```

***Live example***
**Look at lines 14 and 15**
Before deb5a9e7dcb88e7580f53bca6d174796055f3afa: https://jsfiddle.net/zkacqwt7/
After deb5a9e7dcb88e7580f53bca6d174796055f3afa: https://jsfiddle.net/Lw8fh1sk/

**Expected behavior**

I expect `CanvasTexture` to work, and not throw GL errors.

**Platform:**

 - Device: Desktop
 - OS: Windows
 - Browser: Chrome
 - Three.js version: dev

**Comment by Mugen87** [comment] 2021-11-20 09:07
When using `CanvasTexture`, an explicit call of `texture.needsUpdate = true;` is not required. The version updates automatically happens in the ctor: https://jsfiddle.net/60meupg4/

The code breaks right now since the renderer tests for texture version one. Your code skips this version. Let me make the code in the renderer more robust.

**Comment by Mugen87** [comment] 2021-11-20 09:08
Fixed via 3c2e417f704576613d8033bb1292a6b9d2e3cd9e.

**Comment by Mugen87** [comment] 2021-11-20 09:09
Thanks for filing this issue!

**Closed by Mugen87** 2021-11-20 09:08 UTC

**Comment by Mugen87** [comment] 2021-11-20 09:26
BTW: Here is the fiddle with the updated build file: https://jsfiddle.net/tb4hp5gm/

**Comment by Methuselah96** [comment] 2022-02-24 15:48
@Mugen87 I'm having a seemingly related issue with the same commit (trying to upgrade from r134 to r135).

![image](https://user-images.githubusercontent.com/693755/155557497-6bb7b5b4-aa25-41ac-a97c-5b064ec6aad0.png)

The code on my end that's causing the issue is a custom glyph implementation that uses `RawShaderMaterial` that I'm unfamiliar with. Do you have any pointers of things to look out for that could be causing the issue? I just wanted to ask before digging into the code on my end some more.
