### ISSUE TITLE
All document method links are broken, possibly for three years

### ISSUE THREAD

**Issue by AndrewRayCode** [mrdoob/three.js#7736] opened 2015-12-05 00:01 UTC
All doc links reference `window.parent.goTo` which has possibly never worked(?)

First commit referencing `window.parent.goTo` by @mrdoob on July 24th, 2012 `git show -p 9a1bd006143e7d949d4b21804d28ccf80db701c1 -- docs/page.js`

```
commit 9a1bd006143e7d949d4b21804d28ccf80db701c1
Author: Mr.doob <info@mrdoob.com>
Date:   Tue Jul 24 18:01:05 2012 +0200

    Refactored documentation system. No more XMLHttpRequest.
    Now you can browse the docs from the local system too.
```

Altered by @alteredq on Aug 8th 2012 `git show -p a650f50aa9ccb66e00d29d2efcbf31d6f13540fa`

```
commit a650f50aa9ccb66e00d29d2efcbf31d6f13540fa
Author: alteredq <postfilter@gmail.com>
Date:   Wed Aug 8 17:49:40 2012 +0200

    Fixed bug in docs regular expression.

    This was creating mess when URL contained "html" also elsewhere than just at the end.
```

Up next is @caseygrun `git log -p -- docs/page.js --author=Casey Grun` who made a bunch of commits to the docs file. This is a likely culprit because of multiple commits to address the same thing.

```
commit 5ddb3b7427f293eae8dedd496b1318ea42ea41b7
Author: Casey Grun <casey.grun@gmail.com>
Date:   Wed Oct 15 00:14:18 2014 -0400

    AlImprove member cross-linking functions in docs

...etc
```

Whodunit? :D

I don't know what the problem is because on the docs pages, `window.parent.goTo` is defined.

I actually don't know if the doc method linking _ever_ worked? I'm also not sure why we don't just use `<a href="#anchor">` which is the standard way to link to anchors on a page.

**Comment by mrdoob** [comment] 2015-12-06 14:32
Seems to work here...?

http://threejs.org/docs/#Reference/Cameras/Camera when I click in `matrixWorldInverse`, the page jumps to http://threejs.org/docs/#Reference/Math/Matrix4.

**Comment by DelvarWorld** [comment] 2015-12-06 18:43
@mrdoob click on the method link `.lookAt` on http://threejs.org/docs/#Reference/Cameras/Camera

**Comment by caseygrun** [comment] 2015-12-06 23:10
Working as intended. The links go to the page documenting the return type of the function. `.getWorldDistance` returns a `Vector3` (and so it goes to `Vector3`), `.clone` returns a `Camera`, and `.lookAt` returns nothing. You can see the return type in the tooltip.

As for why anchors aren't used, it's because the hashes take you to pages for the individual classes (e.g. 
<http://threejs.org/docs/#Reference/Cameras/Camera>)

**Comment by DelvarWorld** [comment] 2015-12-06 23:18
Hmm ok. Then this behavior is confusing. The expected behavior of clicking on a method name is to link to it. The use case being linking to specific parts of the docs to share with people, which is especially helpful for showing newcomers where documentation is. Linking to the return type of functions from clicking on the function name itself is counter to any other IDE or documentation example, and I don't think we should be inventing a UI pattern for no reason.

Traditionally return types are annotated in some way, like `[ Vector3 ] .getWorldDirection ([ Vector3  ] vector)`. 

The current behavior has not only confused me but every other developer I speak to about it in #three.js. Saying it's working "as intended" may be true, but that intended behavior is not desired for approachable documentation.

**Comment by caseygrun** [comment] 2015-12-06 23:37
Sorry, I didn't mean to be curt—I agree the current behavior is confusing. It's something that I thought about changing when I was working on the docs, but never got around to. 

At this point it wouldn't be hard to fix: you could change [this section](https://github.com/mrdoob/three.js/blob/master/docs/page.js#L30-L31) of `page.js`, which parses the raw HTML docs for tags that look like this: `[method:BufferGeometry rotateX]` and converts them into links. If you're interested in changing that, I'm sure a PR would be welcomed! 

I'll also mention that you can currently get a link to a particular member by clicking on the `#` sign to the right of the member name: 
<img width="491" alt="screen shot 2015-12-06 at 6 36 12 pm" src="https://cloud.githubusercontent.com/assets/566660/11616408/45044f5a-9c48-11e5-85c3-7882ed34a27b.png">

**Comment by DelvarWorld** [comment] 2015-12-06 23:58
I might have come off more aggressive than I meant, it's mostly surprise. If I have some free time over the holidays I will look into making a change like this. Also, I have no idea how I missed the anchor link on the right. Others have too. Maybe a quick fix would just be float that to the left?

**Comment by looeee** [comment] 2016-12-15 16:05
This is a duplicate of #9411

**Closed** 2017-04-06 18:40 UTC
