### ISSUE TITLE
Shared InterleavedBuffer and update of buffers

### ISSUE THREAD

**Issue by langovoi** [mrdoob/three.js#9318] opened 2016-07-11 14:51 UTC
##### Description of the problem

I have much Mesh with BufferGeometry.
It has one InterleavedBuffer for all attributes and one program.
Buffer updated more times when rendering, because check in WebGLRenderer is wrong. (https://github.com/mrdoob/three.js/blob/master/src/renderers/WebGLRenderer.js#L674)
This is bad for performance.

Maybe use info of attributes geometry instead `geometry.id`?
##### Three.js version
- [x] Dev
- [x] r78
- [x] ...
##### Browser
- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
##### OS
- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by sc0rp1d** [comment] 2016-08-15 16:45
ping @mrdoob

**Comment by mrdoob** [comment] 2016-08-15 18:16
Sorry, I do not understand the suggestion. Do you mind elaborating a bit more?

**Comment by sc0rp1d** [comment] 2016-08-15 19:17
I have much objects with BufferGeometry.
I created one InterleavedBuffer with all attributes and one BufferAttribute with indices.

But when it's render, I get update of buffer to WebGL for every object, but it is similar. So I get bad performance.

I thing is's because this compare is wrong.
https://github.com/mrdoob/three.js/blob/master/src/renderers/WebGLRenderer.js#L675

**Comment by Mugen87** [comment] 2020-02-18 20:05
It does not matter if an instance of `InterleavedBuffer` is used in context of a single or many geometries. `WebGLAttributes` ensures to update the buffer only a single time if the data have changed.

https://github.com/mrdoob/three.js/blob/d665e52a4a48a69fcbc86a961da830b769609193/src/renderers/webgl/WebGLAttributes.js#L127-L145

Closing until a performance problem can reproduced with a live example.

**Closed by Mugen87** 2020-02-18 20:05 UTC
