### ISSUE TITLE
MMDPhysics: Ammo.btDefaultCollisionConfiguration is not a function

### ISSUE THREAD

**Issue by kttkjl** [mrdoob/three.js#16046] opened 2019-03-24 01:58 UTC
Following the example for MMDAnimatonHelper

Load order is 
```
    <script src="./Dependencies/ammo.js"></script>
    <script src="https://threejs.org/build/three.min.js"></script>
    <script src="./Dependencies/mmdparser.min.js"></script>
    <script src="./Dependencies/inflate.min.js"></script>
    <script src="./Dependencies/TGALoader.js"></script>
    <script src="./Dependencies/OutlineEffect.js"></script>
    <script src="./Dependencies/MMDLoader.js"></script>
    <script src="./Dependencies/MMDPhysics.js"></script>
    <script src="./Dependencies/CCDIKSolver.js"></script>
    <script src="./Dependencies/MMDAnimationHelper.js"></script>
```

Error gets thrown when calling the Helper to add physics to a mesh with the helper function
```
let remilia;
let remAHelper = new THREE.MMDAnimationHelper();
MMDLoader.loadWithAnimation(
  "/ThreeJSTest/Remilia/remi_phys.pmx",
  "/ThreeJSTest/MMDAnim/walk/Female_run.vmd",
  function(o) {
    remilia = o.mesh;
    remilia.position.y = 1;
    remAHelper.add(o.mesh, {
      animation: o.animation,
      physics: true
    });
    scene.add(remilia);
  },
  undefined,
  function(err) {
    console.log(err);
  }
);
```
The code above is loaded after all the dependencies ... it fails with `Uncaught TypeError: Ammo.btDefaultCollisionConfiguration is not a constructor` on [this line](https://github.com/mrdoob/three.js/blob/de34d4e6951878b3654e3b23c09756b8d73e0108/examples/js/animation/MMDPhysics.js#L250)

**Comment by yomboprime** [comment] 2019-03-29 14:23
Are you using ammo.js from the three.js repository? More recent versions of Ammo need asynchronous initialization, so it could be the cause of the error.

**Comment by yomboprime** [comment] 2019-03-29 18:51
I have reproduced the same error using the latest version of Ammo, so this must be the cause.

Coincidentally I had planned to make a PR to update the Ammo version in Three.

**Comment by yomboprime** [comment] 2019-03-29 19:02
Related https://github.com/mrdoob/three.js/pull/16100

**Comment by kttkjl** [comment] 2019-03-29 20:36
> Are you using ammo.js from the three.js repository? More recent versions of Ammo need asynchronous initialization, so it could be the cause of the error.
> 
> (Edit: The error occurs at the first attempt to use Ammo)

I'm just grabbing the most up-to-date ammo.js from ammo.js's github

**Comment by yomboprime** [comment] 2019-03-29 20:40
> > Are you using ammo.js from the three.js repository? More recent versions of Ammo need asynchronous initialization, so it could be the cause of the error.
> > (Edit: The error occurs at the first attempt to use Ammo)
> 
> I'm just grabbing the most up-to-date ammo.js from ammo.js's github

That's the problem. Please see this PR for how to initialize correctly the latest Ammo version:
https://github.com/mrdoob/three.js/pull/16100

**Comment by yomboprime** [comment] 2019-03-31 11:33
Closing since it is resolved.

**Closed by yomboprime** 2019-03-31 11:33 UTC
