### ISSUE TITLE
threejs qt webengine 'shading' issue

### ISSUE THREAD

**Issue by hasancana** [mrdoob/three.js#10719] opened 2017-02-04 01:48 UTC
##### Description of the problem 
I have an issue with Three.JS on Qt WebEngine (based on Chromium) on my computer, no difference can be seen between vertices, the object does not have any 'shading'. The following example works fine on Google Chrome, Firefox but not on Qt WebEngine. Noting that the same thing works just fine on another computer but not mine.

Example tested:
https://threejs.org/docs/api/materials/MeshLambertMaterial.html

Screenshots:
http://i65.tinypic.com/2j2gjy8.png   
http://i67.tinypic.com/dh4dj9.png

##### Three.js version

latest build

##### Browser

Qt 5.7 WebEngine (based on Chromium)

##### OS

Windows 10

##### Hardware Requirements (graphics card, VR Device, ...)

Intel HD Graphics 4400

**Comment by RemusMar** [comment] 2017-02-04 11:54
> The following example works fine on Google Chrome, Firefox but not on Qt WebEngine.

So the issue has nothing to do with three.js

**Comment by vepebe** [comment] 2017-02-04 11:58
I assume it has because only from r74 up to the latest version, I have this issue. I can get 'shading' for example with r73, but the problem is that many other features are missing in these old versions. So r73 and below it works fine.

**Comment by mrdoob** [comment] 2017-02-04 19:44
Are you having this issue with all the materials or only `MeshLambertMaterial`?

**Comment by vepebe** [comment] 2017-02-11 13:42
Yes, I also tried MeshPhongMaterial but same results
http://i68.tinypic.com/qrz0op.png

Thanks.

**Comment by mrdoob** [comment] 2017-02-11 18:13
That tinypic link doesn't work. You can attach images to here directly.

**Comment by vepebe** [comment] 2017-02-11 18:15
sorry about that

here it is
<img width="1008" alt="screen shot 2017-02-11 at 4 38 36 pm" src="https://cloud.githubusercontent.com/assets/3217137/22856257/1863dcca-f09f-11e6-9dc7-5d04e2d217c7.png">

**Comment by mrdoob** [comment] 2017-02-11 18:16
Latest Intel drivers and all that?

**Comment by vepebe** [comment] 2017-02-11 18:58
No, I currently have Intel Graphics Driver 10.18.15.4271 , latest version on Intel website seems to be 15.40.28.4501. I can try install the latest drivers but I am afraid that something is missing/changed from version r74 and later, as with <=r73 I can get shading (of course not with this example).

**Comment by vepebe** [comment] 2017-02-11 22:23
I updated to latest version of Intel drivers, same problem.

**Comment by mrdoob** [comment] 2017-02-13 20:22
Have you reported this to Qt WebEngine?

**Comment by Mugen87** [comment] 2018-01-22 20:58
Closing, since this is a Qt WebEngine related issue.

**Closed by Mugen87** 2018-01-22 20:58 UTC
