### ISSUE TITLE
Power of 2 images upside down when using bitmap loader

### ISSUE THREAD

**Issue by dllz** [mrdoob/three.js#17353] opened 2019-08-26 13:11 UTC
When using the Image Bitmap Loader to load in images for sprites the images render upside down. It should be noted that if the image downloaded is not the correct power of 2 and the resizer is fired the images appear the right way up but if they images are the correct power of 2 and the resizer is not called they appear upside down;

```javascript
let material = new THREE.SpriteMaterial();
let sprite = new THREE.Sprite( material );
sprite.scale.set(5, 5, 5);
sprite.position.copy(props.position);
sprite.userData = props.userData;
scene.add(sprite);
new THREE.ImageBitmapLoader().load( props.imageUrl,  (imageBitmap) => {
	let texture = new THREE.CanvasTexture( imageBitmap );
	material = new THREE.SpriteMaterial( { map: texture } );
	sprite.material = material;
	sprite.scale.set(5, 5, 5);
       }, undefined, function (err) {
	     console.error("Error loading image", err)
} );
```

##### Three.js version

- [x ] r107

##### Browser

- [] All of them
- [x ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [] All of them
- [ ] Windows
- [ x] macOS
- [ x] Linux
- [ ] Android
- [ ] iOS
Havent tested on the others

**Comment by Mugen87** [comment] 2019-08-26 15:37
Duplicate of #16144

**Closed by Mugen87** 2019-08-26 15:37 UTC
