### ISSUE TITLE
Shadows do not appear sometimes when setting spotlight.distance to 0

### ISSUE THREAD

**Issue by sandersdevelopments** [mrdoob/three.js#27523] opened 2024-01-07 13:17 UTC
### Description

Hello!

I think I've found a quite special bug in the (current?) threejs version. It appeared in my code with the r151 but also in the https://threejs.org/editor/ : 

When I place a Spotlight to shine towards an object and setting the spotlight distance to something lower than the object it leads to not having shadows for the object, of course. But if I now change the distance of the spotlight to 0 (infinity) the shadow of the object does not reappear again. 
BUT if I have the spotlight distance to something GREATER than the object (so that the object throws a shadow) and THEN set the distance to 0, it works like expected - the shadow of the object appears / is still there. 

So, it looks like the distance itself is updated - but maybe the shadowmaps or smth dont?

Can someone verifiy this is an issue? Thanks in advance!

### Reproduction steps

1. Spawn a object at any position
2. Spawn a Spotlight and set the distance so that the object does not throw shadows(bc the distance is **lower**)
3. Change the distance to 0 (infinity) ===> no shadows appear

1. Spawn a object at any position
2. Spawn a Spotlight and set the distance so that the object does throw shadows (bc the distance is **higher**)
3. Change the distance to 0 (infinity) ===> shadows appear

### Code

```js
// code goes here
```

### Live example

* [official threejs editor](https://threejs.org/editor/)

### Screenshots

![image](https://github.com/mrdoob/three.js/assets/69421749/3bc4712e-c999-45b3-b3fa-03d61031d46a)

### Version

>r151

### Browser

Chrome

### OS

Windows 11

**Comment by Mugen87** [comment] 2024-01-07 14:18
I think this issue is a duplicate of #27290. Can you please have a look at #27290?

**Comment by sandersdevelopments** [comment] 2024-01-07 14:23
> I think this issue is a duplicate of #27290. Can you please have a look at #27290?

Yeah, I believe you are right. Sorry, I must have overseen that. I'll try the workarounds from there, thanks!

**Closed** 2024-01-07 14:32 UTC
Labels: Duplicate
