### ISSUE TITLE
Gltf file can't load when three's version>=134

### ISSUE THREAD

**Issue by neciszhang** [mrdoob/three.js#23094] opened 2021-12-27 06:44 UTC
**Describe the bug**
When I load .glb file in creat-react-app , i just use three.js@136, but i can't see it in my iphone.It's catch error "response.body.getReader".
When i use three@133, I load it successfully. I search the document, I think it's changed FileLoader with Fetch Api  in three@134.

***Code***

```js
// code goes here
let gltfLoader=new GLTFLoader()
gltfLoader.load(
          "xxx.glb",
          (gltf) => {
            scene.add(gltf.scene);
          },
          undefined,
          (error) => {
            console.info(error);
    
            // reject(error);
          }
        );
```

**Platform:**

 - Device: Mobile
 - OS:IOS
 - Browser: Chrome
 - Three.js version: [dev, r134]

**Comment by Mugen87** [comment] 2021-12-27 09:35
Duplicate of #23015.

**Closed by Mugen87** 2021-12-27 09:35 UTC
