### ISSUE TITLE
Blender export bumpScale format

### ISSUE THREAD

**Issue by JurgenHannaert** [mrdoob/three.js#9106] opened 2016-06-09 13:36 UTC
When exporting a model from Blender to the threejs json format the materials bumpScale properties are arrays, while threejs expects regular values.

Actual export:
`"bumpScale":[0.1,0.1]`]

Expected by threejs:
`"bumpScale": 0.1`
##### Three.js version
- [ ] r77

**Comment by carlosanunes** [comment] 2016-06-15 15:32
Confirmed.

**Comment by dherben** [comment] 2016-07-21 11:32
This happens because in api/material.py the bump_scale method simply delegates to normal_scale. That latter method was changed in commit  c9ce1e5 to return an array instead of a single float. This is correct for normal_scale, but not bump_scale.

@mrdoob, I'm fixing this in my local fork and I'd like to take this issue as an opportunity for my first pull request, if you're willing to guide me through the process.

**Comment by carlosanunes** [comment] 2016-07-26 18:42
It is quite straightforward. Just read these instructions:

https://help.github.com/articles/using-pull-requests/

And then when making the commit reference the issue number.

**Comment by elipeters** [comment] 2016-09-02 16:31
I'm using an npm r79 but I don't see a reported fix in releases for r80 for the normal scale not being set (apologies if I am incorrect) fixed by... 

`material.materials[0].normalScale = new THREE.Vector2(1,1);`

If you have a dark model with weird bright highlights then this should fix the issue. 

The json file creates `"mapNormalFactor":[1,1],`  which I think isn't committed to normalScale.

**Closed** 2017-01-10 23:48 UTC
Labels: Bug
