### ISSUE TITLE
geometry.computeVertexNormals() not working for extruded geometry

### ISSUE THREAD

**Issue by henryJack** [mrdoob/three.js#9862] opened 2016-10-14 11:30 UTC
##### Description of the problem

geometry.computeVertexNormals() not working for extruded geometry created using absarc.

Best explained with pictures and fiddle. 

![image](https://cloud.githubusercontent.com/assets/22593502/19385909/5ce26550-9209-11e6-952d-d63850b5ebe3.png)

![image](https://cloud.githubusercontent.com/assets/22593502/19385933/7dcc1e5a-9209-11e6-974b-c88b2fdf8a86.png)

https://jsfiddle.net/k2r4cqnh/2/

I have also tried `geometry.computeFaceNormals` and `shading: SmoothShading` but no dice! 

You get the same problem with the shape with/without a hole.
##### Three.js version
- [ ] r81
##### Browser
- [x] All of them
##### OS
- [ ] Windows

**Comment by Mugen87** [comment] 2016-10-14 12:26
Why are you re-computing the normals? `ExtrudeGeometry` provides automatically valid normals like all other geometry entities of three.js. If i delete `geometry.computeVertexNormals()` in your fiddle i get this:

![image](https://cloud.githubusercontent.com/assets/12612165/19387336/e7f871ec-9219-11e6-9255-7de73d6188b3.png)

**Comment by henryJack** [comment] 2016-10-14 12:32
There are still a lot of visible scares in that geometry. By computing the vertex normals you should be able to get the geometry as smooth as the native cylinder and torus geometries without having to use exessive numbers of segments

![image](https://cloud.githubusercontent.com/assets/22593502/19387527/a311ea92-9212-11e6-98c0-7efe33ee9749.png)

**Comment by Mugen87** [comment] 2016-10-14 12:43
I see what you mean. This could be a reasoned limitation of `ExtrudeGeometry`. After checking the source code `ExtrudeGeometry` seems to calculate normals via `computeFaceNormals`, which explains the visual result.

**Comment by Mugen87** [comment] 2016-10-14 12:49
Maybe we can try to solve this problem if we create an `ExtrudeBufferGeometry` in the future.

**Comment by henryJack** [comment] 2016-10-14 12:50
This seems weird as you can get super smooth geometry from things like 3D text that represents a ring. 

![image](https://cloud.githubusercontent.com/assets/22593502/19387933/14827000-9215-11e6-8756-93c6063c3caf.png)

https://threejs.org/examples/webgl_geometry_text.html#0067FF301#O

**Comment by Mugen87** [comment] 2016-10-14 12:53
Normals seem to be post-processed in this example, see

https://github.com/mrdoob/three.js/blob/master/examples/webgl_geometry_text.html#L384

**Comment by henryJack** [comment] 2016-10-14 13:28
Isn't that what I'm doing in the fiddle above?

**Comment by Mugen87** [comment] 2016-10-14 13:33
Only partial. Look at the section after `textGeo.computeVertexNormals();` (Line 389-426)

**Comment by Mugen87** [comment] 2016-10-14 13:38
Oh wait! This code isn't actually executed in the example. Um, then i don't know the reason for this behavior. Maybe it's the high resolution of the geometry?

**Comment by zz85** [comment] 2016-10-17 00:14
@henryJack if you're add after `geometry.computeVertexNormals();`

```js
for ( var i = 0; i < geometry.faces.length; i ++ ) {
	var face = geometry.faces[ i ];
	if (face.materialIndex == 1 ) {
		for ( var j = 0; j < face.vertexNormals.length; j ++ ) {
			face.vertexNormals[ j ].z = 0;
			face.vertexNormals[ j ].normalize();
		}
	}
}
```
 you will see that the ring is smooth. I can't remember how to make the sides flat though...

![image](https://cloud.githubusercontent.com/assets/314997/19422119/ad73cf1a-9441-11e6-85d3-674423d9dc6e.png)

**Comment by henryJack** [comment] 2016-10-17 08:28
There is still a seam/scar at (x,y)=(Radius,0) on the inside and outside...

![image](https://cloud.githubusercontent.com/assets/22593502/19430376/e92afde4-944b-11e6-93d7-30a2ef16eede.png)

**Comment by henryJack** [comment] 2016-10-17 08:35
Although that is probably to do with the way `path.absarc` closes the shape before extrusion because you get all kinds of strange behaviour around that point. For example by including a bevel (`var extrudeSettings = { amount: 3, bevelEnabled: true, curveSegments: 40 }`) you get this...

![image](https://cloud.githubusercontent.com/assets/22593502/19430660/fe96e8e0-944c-11e6-8130-d83baac9edba.png)

**Comment by highfieldjames** [comment] 2016-10-17 09:06
Hi @zz85 and @henryJack 

You can make the sides flat with a `THREE.MultiMaterial`.

`var material = new THREE.MultiMaterial( [
	new THREE.MeshPhongMaterial( { color: 0xffffff, shading: THREE.FlatShading } ), // front
	new THREE.MeshPhongMaterial( { color: 0xffffff, shading: THREE.SmoothShading } ) // side
] );`

`var extrudeSettings = {
  amount: 3,
  bevelEnabled: false,
  curveSegments: 40,
  material: 0,
  extrudeMaterial: 1
};`

See https://jsfiddle.net/k2r4cqnh/5/

![image](https://cloud.githubusercontent.com/assets/6731221/19431677/5447e7ae-9451-11e6-969c-f8e5b408112c.png)

**Comment by henryJack** [comment] 2016-10-17 09:33
Thanks for the help @highfieldjames . Nearly there now!

The following fiddle represents the simplest working example and our progress. https://jsfiddle.net/k2r4cqnh/7/

 However, we are still getting the scar where the `path.absarc` starts and ends before the extrusion...

![image](https://cloud.githubusercontent.com/assets/22593502/19432576/12043b64-9455-11e6-8d84-3c248780af2b.png)

 Which also causes other unflattering issues if you set `bevelEnabled: True`

![image](https://cloud.githubusercontent.com/assets/22593502/19432534/db4a84e8-9454-11e6-937a-067d022c1c0d.png)

**Comment by highfieldjames** [comment] 2016-10-17 10:51
I had a look at why Font works. There is no issue there because it only uses `quadraticCurveTo` and `bezierCurveTo`. If we try to create a (non-exact) circle with bezier curves, the issue is resolved.

See [https://jsfiddle.net/k2r4cqnh/9/](url).

Is this issue with arc already known? Perhaps a duplicate of #5817?

**Comment by henryJack** [comment] 2016-10-17 11:20
Perfect, thanks @highfieldjames and @zz85 for your help finding a workaround for now! 

To summarise the remaining issues then:

1) @zz85's code to smooth the sides could somehow be added automatically when calling 'geometry.computeVertexNormals()'.

2) Hopefully the start/end scaring issue with `path.absarc` can be resolved as it let's you define arbitrary start and end angles in one line - `.absarc ( x, y, radius, startAngle, endAngle, clockwise )`. 

3) Manually having to add `FlatShading` to keep the ends of an extruded shape from messing up when you want the sides smooth seems inelegant to me as you need to set different materials for different faces.

Again, thanks for all your help so far!

**Comment by WestLangley** [comment] 2016-10-17 16:09
@henryJack `geometry.computeVertexNormals()` is designed to be applied to any arbitrary geometry. We can't modify the method to accommodate your specific geometry.

Also, be aware that not all users are extruding a circle. If you were extruding the letter D, you would not want smooth normals everywhere.

three.js is a rendering engine, not a modeling tool. I think the best solution is for you to develop your model using modeling software, and import it into three.js.

**Comment by Mugen87** [comment] 2016-10-17 16:26
> geometry.computeVertexNormals() is designed to be applied to any arbitrary geometry. We can't modify the method to accommodate your specific geometry.

I can only agree with this! But maybe there is a way to create an `ExtrudeBufferGeomtry` that is a little bit more flexible than the current implementation. At least, we should keep this issue in mind when developing the `BufferGeometry` port.

**Comment by henryJack** [comment] 2016-10-18 09:15
@WestLangley - I agree that we shouldn't modify `geometry.computeVertexNormals()` directly but there should be a THREE method to achieve smoothing the faces of an extruded shape without artefacts. I am now using a `smoothExtrudedGeometry()` function based on the discussion in this thread. A nice example of this is the elimination of some bezier scaring on some 3D extruded helical gears. See before and after below...

before `smoothExtrudedGeometry()`
![image](https://cloud.githubusercontent.com/assets/22593502/19470624/1945ac46-9518-11e6-94a0-a0a6acc1cabc.png)

after `smoothExtrudedGeometry()`
![image](https://cloud.githubusercontent.com/assets/22593502/19470642/32fbf29e-9518-11e6-8b92-61f14bf1cbb4.png)

> three.js is a rendering engine, not a modeling tool. I think the best solution is for you to develop your model using modeling software, and import it into three.js.

I think the above image of gears shows that THREE.js can be a fantastic direct modelling tool. Given the many parameters used to describe certain geometries (such as gear teeth) it would not be practical to develop templates of such models if you want to dynamically change their attributes based on some user input. Or have I misunderstood something about THREE.js?

**Comment by WestLangley** [comment] 2016-10-18 13:36
>it would not be practical to develop templates of such models if you want to dynamically change their attributes based on some user input

@henryJack Good point.

>Like i said before, there is maybe a way to create an ExtrudeBufferGeometry that is a little bit more flexible than the current implementation.

@Mugen87 Yes. At a minimum, since `material.shading = THREE.FlatShading` can be used to render faceted edges, we can create an `ExtrudeBufferGeometry` and make sure to share vertices on the edge and bevel. That is, think of the entire edge and bevel as a warped `CylinderBufferGeometry`. That way, `computeVertexNormals()` can be applied to the edge, and the edge can appear smooth everywhere. The front and back faces (and normals) would have to be handled separately in the constructor.

I agree this would be a nice enhancement. It is not completely flexible, but it satisfies complaints by users of edges not being smooth.

**Comment by zz85** [comment] 2016-10-19 01:56
> start/end scaring issue with path.absarc

This is because the starting and ending vertices aren't the same.

This goes away if you add `geometry.mergeVertices();` before `geometry.computeVertexNormals();`

![image](https://cloud.githubusercontent.com/assets/314997/19502874/3e759dbc-95e2-11e6-9a40-352405d3811a.png)

**Comment by WestLangley** [comment] 2019-10-19 17:48
Closing due to age. If there is an issue is a recent three.js revision, please file a new issue.

**Closed by WestLangley** 2019-10-19 17:48 UTC
