### ISSUE TITLE
WebGL1Renderer now faster than WebGLRenderer after browser update

### ISSUE THREAD

**Issue by rgddev** [mrdoob/three.js#23821] opened 2022-03-31 11:38 UTC
Hi!

I was using Three.js this month for testing and everything was fine.

After I update Brave, today, all my code was running really slow, from 59 fps to 14-15 fps
The issue happened in both of the video cards in the notebook:
  - Intel HD Graphics 630 1536 MB
  - Radeon Pro 560 4 GB

Tried a lot of tests:
  - Updated r138 to r139: still slow
  - Put just 4 objects in scene: still slow
  - Changed WebGLRenderer to WebGL1Renderer: got speed back!

The renderer init code before:
`const renderer = new THREE.WebGLRenderer({
    antialias: true,
    powerPreference: "high-performance"
});
`

This is what the renderer init code looks now:
`const renderer = new THREE.WebGL1Renderer({
    antialias: true,
    powerPreference: "high-performance"
});`

Maybe it's a Chromium 99 vs 100 issue?
Can try to test in real Chrome browser and supply a full source code with different models if needed

**To Reproduce**

**Brave macOS version with the WebGLRenderer slow and WebGL1Renderer fast:**
Version 1.37.109 **Chromium: 100.0.4896.60** (Official Build) (x86_64)
Download link: https://github.com/brave/brave-browser/releases/tag/v1.37.109

**Brave macOS version with both WebGLRenderer and WebGL1Renderer fast:**
Version 1.36.117 **Chromium: 99.0.4844.74** (Official Build) (x86_64)
Download link: https://github.com/brave/brave-browser/releases/tag/v1.36.117

**Platform:**

 - Device: Desktop
 - OS: macOS (12.3 (21E230))
 - Browser: Chromium based
 - Three.js version: r138 and r139

**Comment by LeviPesin** [comment] 2022-03-31 11:41
Can you make a fiddle with these 4 objects?

**Comment by Mugen87** [comment] 2022-03-31 13:37
Please test with other browsers too. Meaning Chrome, Firefox and Safari.

At first sight, this looks like a WebGL 2 performance issue in Brave.

**Comment by rgddev** [comment] 2022-03-31 13:55
> Please test with other browsers too. Meaning Chrome, Firefox and Safari. As mentioned above, please share a test application for reproduction.
> 
> At first sight, this looks like a WebGL 2 performance regression in Brave.

Just installed and tested the example in Google Chrome
Version 100.0.4896.60 (Official Build) (x86_64)

It's happening as well.

Safari and Firefox, both latest versions in macOS, not happening

Probably a Chromium 100 engine issue

**Comment by rgddev** [comment] 2022-03-31 14:42
Just uploaded the example here with GIF files from Brave and Google Chrome
https://github.com/rgddev/threejs-chromium100-bug


> Please test with other browsers too. Meaning Chrome, Firefox and Safari. As mentioned above, please share a test application for reproduction.
> 
> At first sight, this looks like a WebGL 2 performance regression in Brave.

**Comment by LeviPesin** [comment] 2022-03-31 14:50
Can you please make a JS fiddle out of it?

**Comment by Mugen87** [comment] 2022-04-01 08:20
Closing. This issue can't be fixed in `three.js`.

I suggest you report the issue at https://bugs.chromium.org/p/chromium/issues/list or continue the discussion at https://github.com/brave/brave-browser/issues/22030.

**Closed by Mugen87** 2022-04-01 08:20 UTC
Labels: Browser Issue

**Comment by mrdoob** [comment] 2022-04-02 00:57
@kenrussell

Seems like Chrome 100 introduced a regression on MacOS/Radeon with WebGL 2 (but not WebGL 1).
Is this a known issue?

**Comment by LeviPesin** [comment] 2022-04-06 18:23
This appears to be some other Chromium 100 bug, not https://github.com/brave/brave-browser/issues/22030.
