### ISSUE TITLE
Feature Request: Native Support of Separate Repeat Values for Different Types of Maps

### ISSUE THREAD

**Issue by EtagiBI** [mrdoob/three.js#15066] opened 2018-10-16 08:40 UTC
Hello,

It would be really convenient to have native support of separate repeat values for different types of maps (e.g. diffuse and bump). It is possible to use this setting through API, but it's a way more complex approach.  StackOverflow discussion:
https://stackoverflow.com/questions/14371385/can-a-three-js-material-have-separate-repeat-values-for-a-bump-map-and-a-texture

**Comment by Mugen87** [comment] 2018-10-16 13:19
Duplicate of #9457

**Closed by Mugen87** 2018-10-16 13:19 UTC
