### ISSUE TITLE
Rendering a scene including points with an override material causes inconsistent behavior

### ISSUE THREAD

**Issue by Oletus** [mrdoob/three.js#28522] opened 2024-05-29 10:19 UTC
### Description

`MeshNormalMaterial` and `MeshDepthMaterial` shaders do not define `gl_PointSize`. When rendering a scene including points with `MeshNormalMaterial` or `MeshDepthMaterial` set as the override material, the points get a random size on Chrome on Mac with an M-series processor, resulting in severe artifacts.

### Solution

We could disable rendering points when using an override material that doesn't support points.

### Alternatives

We could set gl_PointSize in all shaders, but this could add overhead depending on how well the shader translation handles it. On D3D, gl_PointSize needs to be emulated by rendering quads, so setting gl_PointSize complicates translating the shader to the underlying system rendering API.

### Additional context

This issue might be resolved in the WebGL spec at some point. See related discussion here: https://github.com/KhronosGroup/WebGL/pull/3370

**Comment by Mugen87** [comment] 2024-05-30 08:35
> We could disable rendering points when using an override material that doesn't support points.

That sounds reasonable to me.

**Comment by Mugen87** [comment] 2024-06-01 09:04
Duplicate of #26732.

**Closed by Mugen87** 2024-06-01 09:04 UTC
Labels: Suggestion
