### ISSUE TITLE
Getting `navigator` undefined when using headless-gl

### ISSUE THREAD

**Issue by HirdayGupta** [mrdoob/three.js#24774] opened 2022-10-10 21:29 UTC
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `three@0.145.0` for the project I'm working on.

For context: I'm running `three` on a nodejs server using `headless-gl` as my renderer context. In doing so, I was getting an error that said `navigator` was undefined. I patched it locally as follows to get it to work, but just wanted to raise this issue in case its helpful to others / project maintainers.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/three/build/three.cjs b/node_modules/three/build/three.cjs
index ccf5e09..a3009c7 100644
--- a/node_modules/three/build/three.cjs
+++ b/node_modules/three/build/three.cjs
@@ -16515,7 +16515,7 @@ function WebGLTextures(_gl, extensions, state, properties, capabilities, utils,
 	const maxTextureSize = capabilities.maxTextureSize;
 	const maxSamples = capabilities.maxSamples;
 	const multisampledRTTExt = extensions.has('WEBGL_multisampled_render_to_texture') ? extensions.get('WEBGL_multisampled_render_to_texture') : null;
-	const supportsInvalidateFramebuffer = /OculusBrowser/g.test(navigator.userAgent);
+	const supportsInvalidateFramebuffer = true
 
 	const _videoTextures = new WeakMap();
 
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by donmccurdy** [comment] 2022-10-11 02:40
Hi @HirdayGupta! Support for using three.js in Node.js is on a best-effort basis, we aren't really set up to fix compatibility issues and maintain them with headless-gl. Pull requests for workarounds like this are welcome, though. For example:

```javascript
const userAgent = typeof navigator === 'undefined' ? '' : navigator.userAgent;
// ...
```

Patching the navigator object into the Node.js global context is also a possible workaround.

**Comment by Mugen87** [comment] 2022-10-11 07:55
This will be fixe with the next release, see #24717.

**Comment by Mugen87** [comment] 2022-10-11 07:55
Duplicate of #24716.

**Closed by Mugen87** 2022-10-11 07:55 UTC
