### ISSUE TITLE
GLTFLoader onProgress not working in chrome

### ISSUE THREAD

**Issue by hrahimi270** [mrdoob/three.js#16710] opened 2019-06-06 13:31 UTC
##### Description of the problem
`onProgress` method has a problem in chrome.
The `total` object is empty.
But I tested it in firefox and its working well.
My code example:
`console.log((xhr.loaded/xhr.total) * 100);`

##### Three.js version

- [x] 0.105.2

##### Browser

- [x] Chrome
- [ ] Firefox

##### OS

- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment] 2019-06-07 08:28
> The total object is empty.

I'm not able to reproduce this with Chrome on macOS. The `onProgress` callback looks like so:

```js
function onProgress( xhr ) {

    if ( xhr.lengthComputable ) {

        var percentComplete = xhr.loaded / xhr.total * 100;
        console.log( 'model ' + Math.round( percentComplete, 2 ) + '% downloaded' );

    }

}
```

**Comment by Mugen87** [comment] 2019-06-08 09:14
Closing. When `xhr.total` is broken on your system, consider to file an issue [here](https://bugs.chromium.org/p/v8/issues/list).

**Closed by Mugen87** 2019-06-08 09:14 UTC
