### ISSUE TITLE
Repository size

### ISSUE THREAD

**Issue by NicolasRannou** [mrdoob/three.js#17999] opened 2019-11-25 10:56 UTC
##### Description of the problem
`Three.js` Github repository is more than **700mb** big. It sounds like this issue already came up and may be related to the Github history but I think that is getting **REALLY** big and that'd be great if there are some Git pros out there knowing how to deal with that!

Note `git shallow-clone` could be a work around it.

##### Repoduce:
```
gitroot git clone https://github.com/mrdoob/three.js
Cloning into 'three.js'...
remote: Enumerating objects: 45, done.
remote: Counting objects: 100% (45/45), done.
remote: Compressing objects: 100% (42/42), done.
remote: Total 221599 (delta 23), reused 9 (delta 3), pack-reused 221554
Receiving objects: 100% (221599/221599), 727.72 MiB | 10.24 MiB/s, done.
```

More information
```
➜  three.js git:(dev) du -sh *
4.0K	LICENSE
4.0K	README.md
2.8M	build
3.4M	docs
1.9M	editor
362M	examples
268K	files
 32K	icon.png
 92K	package-lock.json
4.0K	package.json
3.2M	src
1.8M	test
 72K	utils
➜  three.js git:(dev) du -sh .*
4.0K	.editorconfig
743M	.git
4.0K	.gitattributes
8.0K	.github
4.0K	.gitignore
4.0K	.npmignore
4.0K	.travis.yml
```
##### Three.js version

- [X] Dev

**Comment by Mugen87** [comment] 2019-11-25 12:08
Sorry, but this is a duplicate of #16091

**Closed by Mugen87** 2019-11-25 12:08 UTC

**Comment by NicolasRannou** [comment] 2019-11-25 12:24
:+1:

**Comment by mrdoob** [comment] 2019-11-25 14:27
> Note `git shallow-clone` could be a work around it.

Good to know!
