### ISSUE TITLE
Blender Exporter 'KeyError'

### ISSUE THREAD

**Issue by daarong** [mrdoob/three.js#10928] opened 2017-03-03 22:51 UTC
I migrated to the latest Blender exporter, had error on my project file which previously worked.  I started a new blender file and found the same error persists.

To reproduce:

1) create a new blender file
2) create cube
3) apply blender material
4) apply blender texture (point at any image)
5) Export to JSON
6) Check box titled "Textures"
7) Error when saving:

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.76\scripts\addons\io_three
\__init__.py", line 812, in execute
    exporter.export_scene(filepath, settings)
  File "C:\Program Files\Blender Foundation\Blender\2.76\scripts\addons\io_three
\exporter\__init__.py", line 20, in inner
    func(filepath, options, *args, **kwargs)
  File "C:\Program Files\Blender Foundation\Blender\2.76\scripts\addons\io_three
\exporter\__init__.py", line 51, in export_scene
    scene_.parse()
  File "C:\Program Files\Blender Foundation\Blender\2.76\scripts\addons\io_three
\exporter\scene.py", line 102, in parse
    self._parse_textures()
  File "C:\Program Files\Blender Foundation\Blender\2.76\scripts\addons\io_three
\exporter\scene.py", line 243, in _parse_textures
    tex_inst = texture.Texture(texture_name, self)
  File "C:\Program Files\Blender Foundation\Blender\2.76\scripts\addons\io_three
\exporter\texture.py", line 24, in __init__
    self[constants.WRAP] = (num[wrap[0]], num[wrap[1]])
KeyError: 'repeat'

(note that by changing the texture "Image Mapping" to something other than 'repeat' simply alters the key error to whatever you selected)

* Blender version 2.74, 2.76, 2.78 (others not tested)
* Exporter says it is version "1.5" but I know previous versions were also still called "1.5".  I used the Master version from 2017-03-03 (today).

##### OS
- [x] All of them

**Comment by Mugen87** [comment] 2017-03-15 12:06
I've followed the steps described in your post but i am unable to reproduce the error with Blender 2.74.

Can you please share your blend file as an attachment? I'll check it on my computer...

**Comment by yomotsu** [comment] 2017-03-15 12:40
Screen capture of export setting is also helpful. Recently, default `type` setting has been changed to "Buffer Geometry". You may set normal "Geometry" when you publish it.

**Comment by daarong** [comment] 2017-03-15 13:45
Mugen87, I uninstalled my Blender and deleted all remaining traces in AppData/Roaming and Program Files, then I installed your Blender version of 2.74, then added in the latest version of the exporter. The same issue is popping up.  Did you grab the latest of the exporter?

The .blend should not be useful but I attached it anyway (any new scene built as described should reproduce it)
[untitled.zip](https://github.com/mrdoob/three.js/files/844652/untitled.zip)

yomotsu, the settings screenshot is here
![settings](https://cloud.githubusercontent.com/assets/4960537/23951158/5915de92-095b-11e7-8f3f-679666202c41.png)

I found that all export settings combinations I tried would produce the issue, so long as a material and texture were used in the scene, and the checkbox for "Textures" is ticked in the exporter.  Other combinations such as with or without ticking "Materials", "Export textures", or the use of Geometry versus BufferGeometry do not have an effect.

Thanks for looking at it guys

**Comment by jostschmithals** [comment] 2017-03-15 14:20
@daarong I tried your zip with the exact settings from your screenshot (blender 2.78), but get no errors either.
Did you try the exporter from the dev branch, too?

**Comment by Mugen87** [comment] 2017-03-15 14:32
Still unable to reproduce. Looks like this issue is a duplicate, see #10629

Maybe @phfatmonkey can help solving this issue.

**Comment by daarong** [comment] 2017-03-15 15:16
jostschmithals and Mugen87, it is a duplicate of #10629 - this has been fixed and I see that the dev branch exporter is working.

In the future I will remember to check the dev branch before posting... thanks guys.

**Comment by Mugen87** [comment] 2017-03-15 15:32
Do you mind closing the issue? Thanks!

**Closed** 2017-03-15 15:45 UTC
