### ISSUE TITLE
InstancedMesh instancing breaks if the supplied material has been already been used.

### ISSUE THREAD

**Issue by manthrax** [mrdoob/three.js#19576] opened 2020-06-06 12:59 UTC
##### Description of the problem
InstancedMesh instancing breaks if the supplied material has been already been used.

If a .clone() of the material is passed into the InstancedMesh, it works.

Repro showing the issue...   remove the .clone() operation to see instancing break.

https://jsfiddle.net/4u1aox7j/

##### Three.js version

- [x] Dev
- [x] r117
- [x] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment] 2020-06-06 13:10
Duplicate of #17701.

**Closed by Mugen87** 2020-06-06 13:10 UTC
