### ISSUE TITLE
Problem in THREE.JS editor

### ISSUE THREAD

**Issue by Imp-Tech** [mrdoob/three.js#4889] opened 2014-06-06 02:58 UTC
Hi!
I found the problem in three.js editor. For example when I deselect all objects in viewport and check or uncheck options 'snap' or 'local' checkbox then orbit and pan camera not working while not selected any object

**Comment by dubejf** [comment] 2015-07-01 04:33
I am not able to reproduce the issue with the current version of the editor (r71). Closing.

**Closed by dubejf** 2015-07-01 04:33 UTC
Labels: Bug
