### ISSUE TITLE
PointLight distance not working on macOS

### ISSUE THREAD

**Issue by revyTH** [mrdoob/three.js#16259] opened 2019-04-15 18:11 UTC
##### Description of the problem

PointLight distance seems to have no effect on macOS platform (10.14.4).

Plunker: [https://plnkr.co/edit/54Nqelu1Spgfl3rYKDGQ](https://plnkr.co/edit/54Nqelu1Spgfl3rYKDGQ)

Result on macOS 10.14.4:

<img width="690" alt="pointlight_test_macos" src="https://user-images.githubusercontent.com/26633801/56155107-6b48ce00-5fba-11e9-8363-e2329c448bc3.png">

Result on Windows 10:

![pointlight_test_windows](https://user-images.githubusercontent.com/26633801/56155149-80bdf800-5fba-11e9-84e8-57fb42df8c6e.png)

##### Three.js version

- [x] r103

##### Browser

- [x] All of them

##### OS

- [x] macOS 10.14.4

##### Hardware Requirements (graphics card, VR Device, ...)

**Comment by WestLangley** [comment] 2019-04-15 18:58
FYI: Plunker appears to work correctly for me on macOS 10.13.6, Safari and Chrome.

**Comment by revyTH** [comment] 2019-04-15 19:33
> FYI: Plunker appears to work correctly for me on macOS 10.13.6, Safari and Chrome.

Thanks, updated with os version

**Comment by mrdoob** [comment] 2019-04-16 08:24
Can't reproduce on macOS 10.14.3 (Intel Iris Graphics 550), Safari and Chrome.

What GPU do you have?

**Comment by Mugen87** [comment] 2019-04-16 12:16
> Can't reproduce on macOS 10.14.3 (Intel Iris Graphics 550), Safari and Chrome.

Same for me on macOS 10.14.4 (AMD Radeon R9 M295X). Tested on Chrome, FF and Safari.

**Comment by revyTH** [comment] 2019-04-16 12:20
> Can't reproduce on macOS 10.14.3 (Intel Iris Graphics 550), Safari and Chrome.
> 
> What GPU do you have?

NVIDIA GeForce GT 750M

I got the same wrong result on safari, chrome and firefox.

**Comment by Mugen87** [comment] 2019-04-16 17:48
Can you please try to update your graphics driver?

**Comment by Mugen87** [comment] 2019-04-16 17:48
Maybe a problem of the graphics driver...

**Comment by revyTH** [comment] 2019-04-16 18:09
I really don't know what to think...could really be the driver?


[point_test.mp4.zip](https://github.com/mrdoob/three.js/files/3086280/point_test.mp4.zip)

**Comment by mrdoob** [comment] 2019-04-17 10:32
Definitely seems to be the driver 😕

**Comment by Mugen87** [comment] 2019-04-17 11:43
Can you please run the [WebGL Conformance Tests](https://www.khronos.org/registry/webgl/sdk/tests/webgl-conformance-tests.html) on your system and share the failed tests? That could provide a hint about what's going wrong.

**Comment by revyTH** [comment] 2019-04-17 18:07
> Can you please run the [WebGL Conformance Tests](https://www.khronos.org/registry/webgl/sdk/tests/webgl-conformance-tests.html) on your system and share the failed tests? That could provide a hint about what's going wrong.

Done, this is the result of the test

[webgl-conformance-1.0.4 (beta).txt](https://github.com/mrdoob/three.js/files/3090930/webgl-conformance-1.0.4.beta.txt)

**Comment by Mugen87** [comment] 2019-04-18 09:11
I've tested your failures on my iMac and the following tests have passed successfully:

- conformance/glsl/bugs/init-array-with-loop.html
- conformance/glsl/bugs/vector-scalar-arithmetic-inside-loop.html
- conformance/glsl/bugs/vector-scalar-arithmetic-inside-loop-complex.html
- conformance/renderbuffers/framebuffer-object-attachment.html
- conformance/textures/misc/tex-input-validation.html

Especially the first three test cases could explain the visual error. These are known GLSL bugs usually fixed in newer driver versions.

**Comment by mrdoob** [comment] 2019-04-18 09:44
He's already running 10.14.4, so I guess there isn't much that can be done...

**Comment by mrdoob** [comment] 2019-04-18 09:44
FYI @kenrussell

**Closed by mrdoob** 2019-04-18 09:44 UTC
Labels: Device Issue

**Comment by kenrussell** [comment] 2019-04-19 18:50
The Mac OpenGL driver for the NVIDIA GeForce GT 750M is not in great shape. For example, there are many WebGL 2.0 conformance failures which the browser vendors will not be able to resolve because the issues are too deep in the driver and can't be worked around at the user level.

If you can boil this down into a smaller test and demonstrate exactly what GLSL operations are failing we might be able to raise the issues with Apple, but it's unlikely.

**Comment by revyTH** [comment] 2019-04-21 17:45
> The Mac OpenGL driver for the NVIDIA GeForce GT 750M is not in great shape. For example, there are many WebGL 2.0 conformance failures which the browser vendors will not be able to resolve because the issues are too deep in the driver and can't be worked around at the user level.
> 
> If you can boil this down into a smaller test and demonstrate exactly what GLSL operations are failing we might be able to raise the issues with Apple, but it's unlikely.

Hi, I've run the same test on High Sierra 10.13 and Sierra 10.12 and got always the same wrong result.  I've even tried the latest web driver from Nvidia for GT 750M to see if there was any difference, but same result. Switching to the integrated video card (Iris) works correctly, so it is the discrete driver for sure.
How should I test GLSL operations? Apologies, always used webgl at high level with three.js

**Comment by luisfonsivevo** [comment] 2020-05-29 22:18
Is there any workaround for this?

**Comment by aderaaij** [comment] 2021-01-30 14:47
> Is there any workaround for this?

@luisfonsivevo you can switch to the integrated graphics card with a tool like this: https://github.com/codykrieger/gfxCardStatus. Unfortunately you can't use an external monitor when you switch to your integrated gfx card
