### ISSUE TITLE
Setting request headers for loaders

### ISSUE THREAD

**Issue by jeanpul** [mrdoob/three.js#10609] opened 2017-01-19 10:06 UTC
Hi, this is my first post so first I want to thank mrdoob and all the contributors for this fantastic library.

##### Description of the problem 

I need to send specific headers with my TextureLoader request (XMLHttpRequest.setRequestHeader()) but I do not see any way to do that (I'm currently using r80). 

##### Three.js version

- [ ] r80
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment] 2017-01-19 13:18
Uhm... Interesting...

**Comment by takahirox** [comment] 2017-01-19 16:19
Will we add `setRequestHeader()` method to `FileLoader` and other loaders?
I'm gonna try to make PR if this sounds good.

**Comment by takahirox** [comment] 2017-01-19 22:11
Ah, I just realized now that
he wants `setRequestHeader()` for `TextureLoader`, not `FileLoader`.

The problem is that `ImageLoader` used by `TextureLoader` no longer uses
neither `FileLoader` nor `XMLHttpRequest` inside.
I mean there's no way to set header for image(texture) now...

One of the solutions is adding `setRequestHeader()` to `FileLoader` and
`ImageLoader` uses `FileLoader` (only if header is set),
but it'd complicate the design...

**Comment by mrdoob** [comment] 2017-01-23 00:39
> Will we add `setRequestHeader()` method to `FileLoader` and other loaders?

I guess that'll be some progress...

**Comment by takahirox** [comment] 2017-01-23 04:50
Maybe adding `setRequestHeader()` to `FileLoader` and
handling texture loading with header request in user code is the easiest way so far,
like this

    var texture = new Texture();
    var image = document.createElementNS( 'http://www.w3.org/1999/xhtml', 'img' );
    var loader = new FileLoader();
    loader.setResponseType( 'blob' );
    loader.setRequestHeader( { header: value } );
    loader.load( url, function ( blob ) {

        image.src = URL.createObjectURL( blob );
        texture.image = image;
        texture.needsUpdate = true;

    }, onProgress, onError );

(I haven't tried yet tho)

**Comment by jeanpul** [comment] 2017-01-23 10:15
@takahirox, thanks for your solution but I do not want to avoid the use of TextureLoader.

I'm actually using r80 and I have overloaded
XHRLoader.prototype.load in order to use setRequestHeader. I've put the headers parameters 
in the withCredentials property (I know that's not a long term solution)  such as :
  
`let loader = new TextureLoader();`
`loader.setWithCredentials({ withCredentials: true,`
`headers: [ { header: 'Auth', value: '****' } ]});`

Maybe the solution is to add a new method setHeaders like the existing setCrossOrigins ? 
We can add a headers property into the low level Loader class. 
Maybe If you want, I can do this myself and do a pull request, however I'm completly familiar with the last release.

**Comment by mrdoob** [comment] 2017-01-23 10:15
Yep! 👍

**Comment by takahirox** [comment] 2017-01-23 17:26
As I wrote, `ImageLoader` called by `TextureLoader` no longer uses `FileLoader` because of #10439.
That means there's no way to set headers for texture even if we add `setRequestHeader()` method to loaders.
(Please see the latest revision, not r80)

I'd suggest that we add `setRequestHeader()` to `FileLoader` (I'm gonna make PR soon) and
you override `ImageLoader.load()` by yourself on your environment so far
if you wanna keep using existing `TextureLoader`.
(Refer to e7f7d330b975b1e7d3b760a3b943976406bfa814)

**Comment by dbkaplun** [comment] 2018-04-20 19:35
Part of the problem here is that loaders do two things: they parse data as well as perform requests. Ideally loaders would only parse data.

**Comment by donmccurdy** [comment] 2018-04-20 21:16
#10708 was merged, is there more to do here? Several loaders have a `.parse()` method that can be used if the developer wants to perform requests some other way.

**Comment by Mugen87** [comment] 2018-04-21 09:13
Indeed, this one can be closed.

**Closed by Mugen87** 2018-04-21 09:13 UTC
Labels: Feature Request

**Comment by dbkaplun** [comment] 2018-04-26 17:26
Thanks, `parse` is exactly what I was looking for!

**Comment by Mugen87** [comment] 2022-03-15 15:44
Yes. Each loader class has a `setRequestHeader()` method and and `ColladaLoader` configures its internal file loader with the defined request headers.

**Comment by awarycha** [comment] 2022-03-16 12:33
Yeah I know that ColladaLoader has setRequestHeader() method and I use it for setting "Authorization" header. It works correct for model itself but if model includes texture as another file then ColladaLoader is fetching this file automatically but without setting "Authorization" header and then I get error for this another file. 
 In my project I use Threejs v.0.126.0 but to today i tested with the latest version 0.138.3 but still doesnt work or I can't do it.

**Comment by Mugen87** [comment] 2022-03-16 14:38
Unfortunately, `TextureLoader` as well as `ImageLoader` can utilize request headers because they do not depend on `FileLoader`.

Could you switch to glTF instead and load glb assets? That should solve the issue because all resources are packed into a single archive file.

**Comment by awarycha** [comment] 2022-03-17 07:35
Our application supports vorious types of files, gltf as well but it is up to the customer which file to use.

**Comment by donmccurdy** [comment] 2022-03-17 14:30
We can't set HTTP Request Headers on `<img>` tags ... I wonder how this worked in v0.126?

You might be able to work around the issue by registering a custom texture loader that uses `fetch` instead: https://threejs.org/docs/?q=loader#api/en/loaders/managers/LoadingManager.addHandler

**Comment by LeviPesin** [comment] 2022-03-17 14:48
> I wonder how this worked in v0.126?

The loader was loading the image via fetch, then making it blob, and then setting image src to it.
