### ISSUE TITLE
Device Orientation Issue?

### ISSUE THREAD

**Issue by farhanRIT** [mrdoob/three.js#15828] opened 2019-02-22 21:50 UTC
Hi, I tested this example https://threejs.org/examples/misc_controls_deviceorientation.html

And it seems that the start direction is not consistent between different orientation.

For example, in portrait mode, it will start by facing the wall (with door on left) BUT
if I turn upside down portrait mode, it will start by facing the window, the opposite of the wall with door on the left.

While on landscape mode, it will start by facing the huge window with the table on the right, while the other way of the landscape mode, it will start by facing the opposite side, facing the 3 little windows.

Shouldn't it always start by facing the same object / area of the room?
Is this a known bug?
If not, how can we start the app by facing the same object / area of the room no matter which orientation your device is currently/initially at?
Otherwise user A experience may be different than user B experience when they run the app with their devices at a different orientation.

Thanks.

**Comment by Mugen87** [comment] 2019-02-25 14:07
I'm unable to reproduce with a Pixel 1 and Chrome. In both portrait and landscape mode the camera faces towards the three-part window. Besides, the initial orientation depends on the tilt of the smartphone.

**Comment by looeee** [comment] 2019-02-28 10:39
Here's my results (Moto G6). 

Portrait, 0 degrees

![screenshot_20190228-182434](https://user-images.githubusercontent.com/5307958/53560602-bc763d00-3b87-11e9-8a85-9b2d5424866c.png)

Landscape, 90 degrees:

![screenshot_20190228-182545](https://user-images.githubusercontent.com/5307958/53560674-e596cd80-3b87-11e9-91c3-1fde02e61cfe.png)


Landscape, 270 degree:

![screenshot_20190228-182521](https://user-images.githubusercontent.com/5307958/53560667-e29bdd00-3b87-11e9-9b84-67595a8fbb4d.png)

**Comment by looeee** [comment] 2019-02-28 10:40
Here's a pen to help other people match up results to their screen orientation:

[What's My Screen Orientation?](https://codepen.io/looeee/full/gEaRZb)

**Comment by WestLangley** [comment] 2019-02-28 14:35
FWIW, from https://developer.apple.com/documentation/webkitjs/deviceorientationevent

>The angles of rotation—the alpha, beta, and gamma properties—do not represent the real world orientation. They are defined as an offset from an arbitrary direction—typically, the direction in which the device was held when the orientation was first obtained.

**Comment by farhanRIT** [comment] 2019-02-28 17:01
Yes, those screen shots are exactly what I see. Isn't that a bug or incorrect? I mean, if you start the app / initialize the app while holding the phone in portrait angle or landscape or upside down portrait or landscape, should the world always start facing the same direction? I mean if you are making a game, you expect it always to start facing the same direction or object?

For now I manage to fix it by rotating the scene initially based on the current orientation so it will always start facing same object/ direction. Not sure if this is the only way for fixing this bug if this is a bug.

**Comment by Mugen87** [comment] 2019-02-28 17:48
Um weird. I wonder why my smartphone behaves differently...

**Comment by Mugen87** [comment] 2020-03-11 13:20
Closing. This is a device specific issue and not related to the implementation of `DeviceOrientationControls`.

**Closed by Mugen87** 2020-03-11 13:20 UTC
Labels: Device Issue
