### ISSUE TITLE
ObjectLoader fails to parse geometry for EdgesGeometry

### ISSUE THREAD

**Issue by jgmedialtd** [mrdoob/three.js#26458] opened 2023-07-18 17:36 UTC
### Description

When attempting to parse scene.toJSON() using ObjectLoader, EdgesGeometry included in the geometry object throws an error

### Reproduction steps

When attempting to parse scene.toJSON() using ObjectLoader as follows:

const loader = new THREE.ObjectLoader();
loader.parse(scene)

At line 286 of https://github.com/mrdoob/three.js/blob/master/src/loaders/ObjectLoader.js

The following error is produced:

Geometries[data.type].fromJSON is not a function

When attempting to parse EdgesGeometry

Example EdgesGeometry included in the code block

### Code

{
    "uuid": "e731474d-0db4-4785-8ca1-662ef17d6f52",
    "type": "EdgesGeometry",
    "geometry": {
        "metadata": {
            "version": 4.6,
            "type": "BufferGeometry",
            "generator": "BufferGeometry.toJSON"
        },
        "uuid": "af74f822-ff1e-4321-a8a4-da77313180ce",
        "type": "BoxGeometry",
        "width": 1,
        "height": 1,
        "depth": 1,
        "widthSegments": 1,
        "heightSegments": 1,
        "depthSegments": 1
    },
    "thresholdAngle": 1
}

### Live example

N/A

### Version

r154

### Device

Desktop

### Browser

Chrome

### OS

MacOS

**Comment by Mugen87** [comment] 2023-07-18 18:01
Duplicate of #16340.

**Closed by Mugen87** 2023-07-18 18:01 UTC
