### ISSUE TITLE
bounding box for skinned mesh

### ISSUE THREAD

**Issue by mshamaseen** [mrdoob/three.js#20434] opened 2020-09-30 01:26 UTC
**Describe the bug**

I am not sure if this a gltf bug or a three js bug but when exporting a skinned mesh with an armature with a specific scale the bounding box will not work correctly, for example, I have an object with an armature of scale 0.018 for all axes and a mesh child with a scale of 1; what happens when I import it to threejs/editor is the bounding box take the scale of the armature, as the image below:
![image](https://user-images.githubusercontent.com/38951661/94632192-a7690f00-02d2-11eb-9328-e69233e4e8ec.png)

and, via coding, when I try to get the object size by:

`let measurementBox = new THREE.Box3().setFromObject( this.threeJsObject );
        measurementBox.getSize(this.objectSize);`

the result is the armature mesh child size (after scaling) multiplied by the armature scale again!
This means if the x dimension of a mesh after being scaled by an armature is 100 with a scale of 0.5 in the armature (actual size of the mesh is 200 then), the bounding box x size will be 50 and not 100, it will scale too after the mesh!

**To Reproduce**
here is the file that I am using, the armature scale is 0.018 and the bounding box is 0.018 of the actual size of the mesh rather than being 100% of the actual size of the mesh.

https://drive.google.com/file/d/14Iq0pUmHt1uE3F0brMIVfFL5taV2MEZs/view?usp=sharing

1. just import it in threejs/editor and check the bounding box!

**Expected behavior**

the bounding box surrounds all the mesh and not being multiplied with the armature scale, it should be like the image below:
![image](https://user-images.githubusercontent.com/38951661/94633127-0f205980-02d5-11eb-82d6-d908310f841a.png)

**Platform:**

 - Device: Desktop
 - OS:  Linux, ubuntu
 - Browser: All
 - Three.js version: r120

**Comment by gkjohnson** [comment] 2020-09-30 01:45
This a known issus with SkinnedMesh bounding boxes -- there are some related discussions in #18334, #18245, #14499

**Comment by Mugen87** [comment] 2020-09-30 09:31
Marking this as a duplicate of #14499.

**Closed by Mugen87** 2020-09-30 09:31 UTC
