### ISSUE TITLE
clampToMaxSize function in WebGLTextures may need type check

### ISSUE THREAD

**Issue by WJsjtu** [mrdoob/three.js#13454] opened 2018-02-28 06:17 UTC
##### Description of the problem

In `uploadTexture` function for `WebGLTextures`
https://github.com/mrdoob/three.js/blob/23be4d6b8484e2912c3ac760720d1ccc6af2f693/src/renderers/webgl/WebGLTextures.js#L429-L435
`clampToMaxSize` is called for any texture on texture.image.
I've figure out the texture type could only be one of `CanvasTexture` , `VideoTexture` and `DataTexture` for `uploadTexture`.
So the logic problem comes here,  `clampToMaxSize` function given an `DataTexture.image` ( an object with `width`, `height`, `data` properties ) will cause error on `drawImage` if the size is larger than `capabilities.maxTextureSize`.
https://github.com/mrdoob/three.js/blob/23be4d6b8484e2912c3ac760720d1ccc6af2f693/src/renderers/webgl/WebGLTextures.js#L18-L33

The example for [SkinnedMesh](https://threejs.org/docs/index.html#api/objects/SkinnedMesh) in doc will go to `clampToMaxSize` with `DataTexture.image`  as  image argument but its size is not larger than `capabilities.maxTextureSize` which makes it not trigger the error.
Maybe it is not practical to set extreme large number of bones, but I think logically this should be fixed.

`makePowerOfTwo` function do this well.

##### Three.js version

- [x] Dev
- [x] r90

Any thoughts?

**Comment by Mugen87** [comment] 2018-02-28 10:34
You mean this error, right?

https://jsfiddle.net/f2Lommf5/2175/

**Comment by WJsjtu** [comment] 2018-02-28 10:46
Yes, you are right!

**Comment by Mugen87** [comment] 2018-02-28 11:09
I guess this would fix the issue. We only use `canvas` for specific image types. 
```js
function clampToMaxSize( image, maxSize ) {

	if ( image.width > maxSize || image.height > maxSize ) {

		var scale = maxSize / Math.max( image.width, image.height );

		if ( image instanceof HTMLImageElement || image instanceof HTMLCanvasElement || image instanceof ImageBitmap ) {

			// Warning: Scaling through the canvas will only work with images that use
			// premultiplied alpha.

			var canvas = document.createElementNS( 'http://www.w3.org/1999/xhtml', 'canvas' );
			canvas.width = Math.max( Math.floor( image.width * scale ), 1 );
			canvas.height = Math.max( Math.floor( image.height * scale ), 1 );

			var context = canvas.getContext( '2d' );
			context.drawImage( image, 0, 0, image.width, image.height, 0, 0, canvas.width, canvas.height );

			console.warn( 'THREE.WebGLRenderer: image is too big (' + image.width + 'x' + image.height + '). Resized to ' + canvas.width + 'x' + canvas.height, image );

			return canvas;

		} else {

			var width = Math.max( Math.floor( image.width * scale ), 1 );
			var height = Math.max( Math.floor( image.height * scale ), 1 );

			console.warn( 'THREE.WebGLRenderer: image is too big (' + image.width + 'x' + image.height + '). Resized to ' + width + 'x' + height, image );

			image.width = width;
			image.height = height;

		}

	}

	return image;

}
```

**Comment by WJsjtu** [comment] 2018-02-28 12:11
Does `makePowerOfTwo` need to care about `DataTexture` if `textureNeedsPowerOfTwo(image) === true` ( Is this possible ? ) and `isPowerOfTwo(image) === false`?
https://github.com/mrdoob/three.js/blob/23be4d6b8484e2912c3ac760720d1ccc6af2f693/src/renderers/webgl/WebGLTextures.js#L48-L68

**Comment by Mugen87** [comment] 2018-02-28 13:50
Maybe. @WestLangley @mrdoob What do you think about this?

**Comment by mrdoob** [comment] 2018-03-01 01:50
So the problem is that `clampToMaxSize()` and `makePowerOfTwo()` breaks when passing a `DataTexture.image`?

**Comment by WJsjtu** [comment] 2018-03-01 02:32
`clampToMaxSize()` breaks and `makePowerOfTwo()` does nothing to `DataTexture.image`.

**Comment by WestLangley** [comment] 2018-03-01 07:07
POT is only required for mipmapping. DataTextures are typically neither mipmapped nor resized -- right?. So I do not understand what the issue is...

**Comment by WJsjtu** [comment] 2018-03-01 07:33
@WestLangley Well , thank you for pointing out that the DataTextures do not need power-of-two process. So you can take care of the first three comments of this issue and ignore others.

The issue is about `clampToMaxSize` function which is called on any texture's image including DataTextures.image without the type check of the image.
When a DataTextures.image with size larger than `capabilities.maxTextureSize` is passed to `clampToMaxSize`. `clampToMaxSize` will call Canvas.drawImage on an JS object ( DataTextures.image ). And this lets the console reporting the error: 

Uncaught TypeError: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The provided value is not of type '(CSSImageValue or HTMLImageElement or SVGImageElement or HTMLVideoElement or HTMLCanvasElement or ImageBitmap or OffscreenCanvas)'

**Comment by WestLangley** [comment] 2018-03-01 07:42
I do not think DataTextures should ever be resized.

**Comment by WJsjtu** [comment] 2018-03-01 07:52
@WestLangley Even the DataTextures are larger than `capabilities.maxTextureSize`?
This will cause warning in console.

WebGL: INVALID_VALUE: texImage2D: width or height out of range

**Comment by WestLangley** [comment] 2018-03-01 08:35
Resizing a DataTexture would destroy the data. If the DataTexture is too big, then that is a user error.

**Comment by Mugen87** [comment] 2018-03-01 14:55
It's not just a warning, `clampToMaxSize()` throws a runtime error: https://jsfiddle.net/f2Lommf5/2175/

My suggestion was to add at least a more robust version of `clampToMaxSize()` that avoids the runtime error and reports a warning instead ('image is too big...').

**Comment by Mugen87** [comment] 2018-03-13 11:02
Closing. If more users complain, we can still make `clampToMaxSize()` more robust. For now let's keep the code as it is.

**Comment by mrdoob** [comment] 2018-03-14 05:26
> My suggestion was to add at least a more robust version of `clampToMaxSize()` that avoids the runtime error and reports a warning instead (_image is too big..._).

That sounds good to me 👍

**Comment by Mugen87** [comment] 2018-03-14 10:23
Okay, i'll make a PR then 😊

**Closed** 2018-03-15 20:47 UTC
Labels: Suggestion
