### ISSUE TITLE
Add easing function to clip action.

### ISSUE THREAD

**Issue by pontiffpublishing** [mrdoob/three.js#9506] opened 2016-08-13 20:51 UTC
##### Feature Request

I like sticking with Three.js' built in animation system so everything works off the same clock.   Most of the stuff you find on the internet suggests using a third party tweening api, but that must be out of date because AnimationClip.js really takes care of business for just about anything you want.  However,  I don't see any way to pass an easing function to guide the interpolation process.  It looks like the mixer autonomously makes the decision later and everything comes out linear.

Any chance you could let us pass an easing function on creation of a clip?

Best Regards
##### Three.js version
- [ ] Dev
- [ ] r79
- [X ] r78
##### Browser
- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
##### OS
- [] All of them
- [X ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by tschw** [comment] 2016-08-17 21:47
Sorry for the late response. I've been on vacation w/o internet access.

There is a file for creating common tween-alike keyframe sequences somewhere in the examples folder. Ben wrote those with the original version and I ported it as the interface changed in r74. However, that being said, I don't think that library code is currently under test.

Also, you may want to use smooth interpolation and get away with a handful of keyframes for pretty much all possible tweens. So I'd say it's "sufficiently simple" to achieve requested functionality with Threejs as-is.

@pontiffpublishing 
> everything works off the same clock

Not necessarily, since you can time-scale tracks individually.

> pass an easing function to guide the interpolation process

The `Interpolant` base class is extensible. So if you want to interpolate differently than linear or cubic (using an hermitian construction from finite differences), you can roll your own.

**Comment by pontiffpublishing** [comment] 2016-08-18 15:46
Thanks for the tip about the Interpolant class.  I'll have a look at that.

I did see that tweening app in the examples folder.  That is what got
me looking in the right direction for rolling my own tweened animation
clips.  I guess the point I was trying to make there was that the
utility of your animation API appears to have advanced considerably
past the documentation and examples I find for it both on your website
and around the internet.

Regards.

P.S.  I don't use your API hoping it to be "sufficiently simple to
achieve requested functionality."  I use it hoping that it is
somewhere near state-of-the-art when it comes to webgl animation.  Is
someone doing this better?

**Comment by tschw** [comment] 2016-08-18 16:53
> I don't use your API hoping it to be "sufficiently simple to achieve requested functionality." I use it hoping that it is somewhere near state-of-the-art when it comes to webgl animation. Is someone doing this better?

Popularity doesn't solve problems - functionality does. I personally care more about whether a software component helps me get the job done than whether it qualifies as "trendy tech" by some dubious measure :).

Professional animation in 3D computer graphics is keyframe-based. I guess you too would be better off with cubic interpolation than with sinoids - keeping the derivative steady and nonzero looks way better than a patchwork of sinoids as you would get from chained tweens.

**Comment by pontiffpublishing** [comment] 2016-08-18 18:17
I should have put a winky-face on that comment, because I was teasing just
a little.  I've tried the rest, but time and again you guys have the go-to
package when I need to get the job done.  My thanks.

Roger that on the chained tweens.

**Comment by fatbird** [comment] 2017-06-01 18:37
I've actually just implemented a cubic-bezier interpolant for three, presumably for the same reason the op is requesting it: nicely eased motion between two points.  Within that limited use case of only two keyframes, and for numeric values, it works like a charm just like the CSS version: pass in the middle control points and the interpolation yields the Y value of the curve at time X.  Now I have lovely eased camera motion between presets, and it's much more convenient to take a cubic bezier curve than set up sufficient tweening keyframes for smooth interpolation.

That said, it's not obvious that this belongs with the more general Interpolants in three.  But now that I have it, it's very convenient, and there's a lot of practical use cases for this sort of thing.  I'm happy to try to work up a pull request that's up to three's standards, but maybe first I'd like a read on whether it would fit in.

**Comment by tschw** [comment] 2017-06-09 19:36
Nice, but this reads much like [CubicInterpolant](https://github.com/mrdoob/three.js/blob/dev/src/math/interpolants/CubicInterpolant.js) which is already there. It supports any number of keyframes and gives you a smooth curve in time through them (it also starts and stops with zero derivative and loops smoothly). You can play with it interactively trying the [animation authoring example](https://threejs.org/examples/#misc_animation_authoring).

Note that we currently don't have a [smooth Quaternion interpolant](http://run.usc.edu/cs520-s13/assign2/p245-shoemake.pdf) for general smooth *rotations* (recently, someone asked about keyframing Euler angles IIRC, but those do not provide a general solution and must be carefully picked for whatever you want to do).

**Comment by fatbird** [comment] 2017-06-12 16:22
The issue here and with the OP's question is ultimately a convenience one, because with the CubicInterpolant you need to figure out your keyframes, while copying the functionality of the cubic-bezier function from CSS allows you to just specify two x,y points.  Until CSS actually got the cubic-bezier function for transform, various online utilities for getting the curve would just generate all the tweened CSS transforms for you.

So maybe the best approach here is to provide cubic-bezier as a utility function that takes two control points and a number of keyframes, and returns two arrays, the times and the values, to use in specifying the KeyframeTrack.  I'll try that out.  Would something like that fit in under Helpers or Animation/Helpers?

**Comment by tschw** [comment] 2017-06-16 22:27
I'm not much familiar with latest state-of-the-art CSS to be honest. From your description

>  utility function that takes two control points and a number of keyframes

I can't quite figure out what you mean and how that would be any different/simpler/better than the existing interface.

> CubicInterpolant you need to figure out your keyframes,

Every "keyframe" is a control point of the spline and splines are usually much easier to control (and connect) than Bezier curves, so I don't really see the improvement. An API that is restricted to two control points sends the user down the wrong track IMO: Towards patchwork animations that, once they exceed a total of two keyframes, either don't look smooth or not steady.

As mentioned above, there's a file with exemplary utility code. Your idea might fit into https://github.com/mrdoob/three.js/blob/dev/examples/js/AnimationClipCreator.js . Again, as said, (unless the situation has changed recently), there's no example using that code, so it's untested and an example should be welcome.

**Comment by donmccurdy** [comment] 2017-12-28 04:31
FWIW it's also possible to create custom interpolants for AnimationClip using a small hack. See https://github.com/mrdoob/three.js/pull/12907 for an example, which creates a GLTFCubicSplineInterpolant that uses not just control points as inputs, but in- and out-tangents for each keyframe.

**Comment by donmccurdy** [comment] 2018-03-03 00:38
I think this could be a duplicate of https://github.com/mrdoob/three.js/issues/8747, or even closed? It is possible to create custom interpolants now, although there are probably things we could do to make that easier.

**Comment by Mugen87** [comment] 2020-02-18 20:13
> I think this could be a duplicate of #8747, or even closed?

👍

**Closed by Mugen87** 2020-02-18 20:13 UTC
Labels: Suggestion
