### ISSUE TITLE
GodRays postprocessing is not working with a SkinnedMesh with animation playing

### ISSUE THREAD

**Issue by iefreer** [mrdoob/three.js#19406] opened 2020-05-21 09:58 UTC
##### Description of the problem

Godrays postprocessing is demonstrated in the following official example link:
https://threejs.org/examples/?q=god#webgl_postprocessing_godrays

But if we replace the obj model with a skinnedmesh for example a sambadance fbx model, 
the light effect can not follow the moving.

here is a demo link for this issue:
https://wow.techbrood.com/static/20200521/57769.html

this probably is a similar issue as OutlinePass.

##### Three.js version

- [ ] r116

##### Browser

- [ ] Chrome

##### OS

- [ ] Windows

**Comment by Mugen87** [comment] 2020-05-21 10:06
This is actually a duplicate of #14577. It's a general restriction and unrelated to individual post-processing passes.

**Closed** 2020-05-21 10:07 UTC
Labels: Duplicate
