### ISSUE TITLE
THREE.ShaderMaterial  kills animation.

### ISSUE THREAD

**Issue by AlexeyGapon** [mrdoob/three.js#6574] opened 2015-05-18 13:43 UTC
Unable to use ShaderMaterial on skinned models.

**Comment by benaadams** [comment] 2015-05-18 13:47
This is a dupe of #6567 that you raised previously

**Comment by AlexeyGapon** [comment] 2015-05-18 13:51
Sorry! I didn`t see the answer! Delete this issue.

Cheers.

**Closed** 2015-05-18 14:36 UTC
