### ISSUE TITLE
three/nodes requires package.json#exports or import maps, consider relative imports

### ISSUE THREAD

**Issue by hybridherbst** [mrdoob/three.js#27354] opened 2023-12-11 11:00 UTC
### Description

I'm somewhat confused why some import references are done this way:
- https://github.com/mrdoob/three.js/blob/ca7261b12e3caebce06958bc08e8cc386dc333d4/examples/jsm/loaders/MaterialXLoader.js#L22

This code seems to assume that _something_ defines what `three/nodes` is.
In practice, that means that a `importmap` is required – and that it's hard to use this code at all when importmaps are not available (e.g. in most bundlers/frameworks).

In vite one needs to do something like this:
```
        resolve: {
            alias: {
                "three/nodes": "three/examples/jsm/nodes/Nodes.js",
            },
        },
```
and then in Next it's different, in bun it's different, ...

I know that previously great care was taken to use relative references throughout the codebase, e.g. here:
- https://github.com/mrdoob/three.js/blob/ca7261b12e3caebce06958bc08e8cc386dc333d4/examples/jsm/loaders/GLTFLoader.js#L68

Is there a specific reason for when "indirect" references are used (not sure what the right name is) vs. when relative references are used? Are absolute references considered a bug / could I make PRs to fix them?

### Version

r159

**Comment by Mugen87** [comment] 2023-12-11 11:06
> In practice, that means that a sourcemap is required

You mean _import map_, right?

**Comment by hybridherbst** [comment] 2023-12-11 11:21
Yes, I mean importmaps :)

**Comment by marcofugaro** [comment] 2023-12-14 17:46
> In vite one needs to do something like this: ... and then in Next it's different, in bun it's different, ...

Wrong, we have the [export namespace](https://github.com/mrdoob/three.js/blob/64467c0166e3a7a36f513052882519c15a3ece95/package.json#L18), so doing `import { ... } from 'three/nodes'` already works by default with modern tools.

Could you test it and report the actual issue if you have it?

**Comment by hybridherbst** [comment] 2023-12-15 15:31
I would not have opened an issue if I had not tested this and came to the conclusion that this is the underlying issue.
I will double-check what's going on – simply removing the alias and letting vite do its thing results in `three/nodes` imports not being resolved at all.

**Comment by donmccurdy** [comment] 2023-12-15 15:39
Framing this the way around... is there a reason we need to use bare module names like `three/nodes` within our source files? It'd be nice for our imports to be consistent, most are relative, I'm not sure why `three/nodes` is the exception currently.

I agree that most modern tools support `package.json#exports` today, but not all, or not in all configurations. I've hit this occasionally and I usually work around it by just importing `three/examples` instead of `three/addons`, but the workaround is not so easy when our source files depend on the alias.

**Comment by marcofugaro** [comment] 2023-12-15 16:06
> simply removing the alias and letting vite do its thing results in three/nodes imports not being resolved at all in the particular project that I noticed the issue in

The problem is not related to this, it's something else in your setup.
Vite works fine with `three/nodes`: https://codesandbox.io/p/devbox/kr6x2c?file=%2Fmain.js%3A8%2C15

> Framing this the way around... is there a reason we need to use bare module names like three/nodes within our source files? It'd be nice for our imports to be consistent, most are relative, I'm not sure why three/nodes is the exception currently.

Not really, I think it was done without much tought about it.
Any tool in particular that doesn't support `package.json#exports`?

**Comment by donmccurdy** [comment] 2023-12-15 16:22
Parcel doesn't, for one. They've got support upcoming in v3 (not sure when that will be released), and some workarounds you can do in v3, but it's not out of the box last I checked.

Vite can handle `exports` sometimes, but still depends on your configuration. A default Vite+TypeScript configuration will fail to handle `exports` as described here:

https://stackoverflow.com/questions/58990498/package-json-exports-field-not-working-with-typescript

That can be worked around (I have not tested this) by upgrading to TypeScript 4.7 and setting your module resolution to "nodenext". But that's not a trivial workaround today, I'm not sure we want to require it from users without a clear reason.

**Comment by marcofugaro** [comment] 2023-12-15 17:10
> Parcel doesn't, for one. They've got support upcoming in v3 (not sure when that will be released), and some workarounds you can do in v2, but it's not out of the box last I checked.

Yikes, then yeah if there are some "modern" tool that still don't support it, it makes sense to use relative paths.

> Vite can handle exports sometimes, but still depends on your configuration. Add TypeScript to Vite and it will fail to handle exports as described here:

[Doesn't happen with the default config](https://codesandbox.io/p/devbox/nostalgic-http-forked-74cs8r?file=%2Fsrc%2Fmain.ts%3A1%2C1-10%2C1), I believe it happens with a custom `tsconfig.json`, which is what might be happening in @hybridherbst's case.

**Comment by donmccurdy** [comment] 2023-12-15 17:33
@marcofugaro interesting! Is that the default tsconfig from `npm create vite@latest`, or something else? I wasn't aware of `"moduleResolution": "bundler"`.

**Comment by marcofugaro** [comment] 2023-12-15 18:04
@donmccurdy I used the preset sandboxes here: https://vitejs.dev/guide/#trying-vite-online
I also created a new project locally with `npm create vite@latest` and it still works the same.

> I wasn't aware of "moduleResolution": "bundler".

It's in vite's setup tsconfig. Removing it has no effect. Not sure honestly how to reproduce the error in vite.

**Comment by donmccurdy** [comment] 2023-12-15 19:00
Here's my tsconfig from the (closed-source) project hitting the issue with Vite+TypeScript:

```jsonc
{
	"extends": "@tsconfig/svelte/tsconfig.json",
	"compilerOptions": {
		"target": "ES2020",
		"module": "ES2020",
		"lib": ["ES2020", "DOM"]
	},
	"include": [ ... ],
	"exclude": [ ... ]
}
```

Not hugely important to me though, that is working fine with `three/examples/jsm` imports. If we are able to just avoid hard dependencies on `exports` for now, while still generally encouraging users to use `three/nodes` and `three/addons` in their own code, I think that's ideal.

**Comment by hybridherbst** [comment] 2023-12-18 09:39
Thanks for the additional investigation. We're also using Typescript, and depending on what's used around it (e.g. svelte, next.js, ...) the resulting config can be totally different and not even always under our control (e.g. when sveltekit is used they're overriding a ton of stuff).

We're using `three/examples/jsm` imports everywhere instead of `three/addons` but when trying to use nodes stuff it does run into the issue I described at the top.

So are we aligned on Don's suggestion of using relative imports in the three.js codebase and generally encouraging people to use the shortcuts in their own code?

**Comment by marcofugaro** [comment] 2023-12-18 20:31
Ok I was able to reproduce using [`npm create vite@latest` + svelte + ts](https://codesandbox.io/p/devbox/three-js-vite-plugin-svelte-kvpyms?file=%2Fsrc%2Flib%2Fscene.ts%3A8%2C22) on codesandbox (in local it works fine somehow).
With [`npm create svelte@latest` there is no error at all](https://codesandbox.io/p/devbox/sveltekit-three-js-rsqk3k?file=%2Fsrc%2Flib%2Fscene.ts%3A10%2C1).

However this problem doesn't seem to be related to the issue @hybridherbst is having, since https://github.com/mrdoob/three.js/pull/27381 would not solve the issue, and also typescript is ignoring the `three/nodes` alias inside the node_modules because it just takes into consideration `@types/three`.

But yeah, if there are some bundlers out there that don't like `three/nodes` in the `node_modules`, it makes sense to use relative paths.
I was just asking @hybridherbst for more context about the error since no details about tooling (or a way ro reproduce) were mentioned in the issue description. But it looks like he is just using an outdated version of vite which doesn't support `package.json#exports`?

**Closed** 2023-12-20 01:38 UTC
Labels: Nodes
