### ISSUE TITLE
Memory not released, when a loading image is NOT power of two

### ISSUE THREAD

**Issue by feabauer** [mrdoob/three.js#12469] opened 2017-10-22 17:21 UTC
##### Description of the problem 

Loading textures with a texture loader and loadManager, if the loading image is power of two, memory will be released, if NOT power of two, memory NOT released.

Here's the code:

	var mesh0;
	function testme(){
		var manager = new THREE.LoadingManager(function(){
			mesh0 = new THREE.Mesh( new THREE.PlaneBufferGeometry( 3, 3 ), new THREE.MeshBasicMaterial( { map: map0 } ) );
			scene.add( mesh0 );
		});

		var texloader = new THREE.TextureLoader(manager);				
		var map0 = texloader.load("textures/1.png"); 	
	}

	function delme(){			
		scene.remove(mesh0);
		
		mesh0.geometry.dispose();
		mesh0.material.map.dispose();
		mesh0.material.dispose();
		mesh0 = null;		
	}

1.png (900x598), memory not released;
2.png (1024x256), memory released

##### Three.js version

- [x] Dev
- [x] r87
- [x] r86

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment] 2017-10-22 18:13
Do you have this problem with the recent `dev` version, too?

**Comment by feabauer** [comment] 2017-10-23 06:32
Yes, the same problem with dev version.

**Comment by takahirox** [comment] 2017-10-23 09:22
I haven't looked into so much yet but Three.js generates 'power of two' size canvas if image is not power of two.

https://github.com/mrdoob/three.js/blob/c67fbdcc64ffc970d732d9d3ce77a930761f7f31/src/renderers/webgl/WebGLTextures.js#L46-L65

It'd be related, maybe?
I'll check the code in the detail later...

**Comment by feabauer** [comment] 2017-10-23 11:35
Thanks, takahirox .

It's a BIG leak, not only the leak of mesh or material, even loadManager and texture loader are not released. The leak is terrible, I checked it with "take snapshop" in the Profiles, of the Chrome dev console.

**Comment by takahirox** [comment] 2017-10-23 15:09
About the example code, does this issue occur even without `renderer.render()` call?

**Comment by feabauer** [comment] 2017-10-23 17:10
Sure.

Just pick any example from three.js code, type the code in Chrome console, run!   That's it.
Those examples run renderer.render all along.

You just have a small try, it's rather rather simple.

**Comment by mrdoob** [comment] 2017-10-23 20:52
> It's a BIG leak, not only the leak of mesh or material, even loadManager and texture loader are not released. The leak is terrible, I checked it with "take snapshop" in the Profiles, of the Chrome dev console.

Have you considered making your textures power of two? 😅

**Comment by takahirox** [comment] 2017-10-23 23:02
> Those examples run renderer.render all along.

So, you meant this issue occurs with `renderer.render()` call, correct?

**Comment by takahirox** [comment] 2017-10-24 01:12
> if NOT power of two, memory NOT released.

What isn't released? `Mesh`? `Material`? `Texture`? Would you be more specific?

**Comment by feabauer** [comment] 2017-10-25 14:28
@mrdoob  
Yes, actually, they're all "power of two" in my code, but i think it's a defect or a bug.  :-D

@takahirox   
Yes, all rendered.  If we called the function in Chrome console, it's very clear.
"A big leak" means that, not only all of meshes, materials, and textures, are not released, but also the load manager, the texture loader, also webGL-related objects, are all not released.

**Comment by feabauer** [comment] 2017-10-25 14:40
@takahirox

You can try it with any examples in three.js.

Open the console,  and capture objects staying in memory after dispose, with "Take snapshot" in the Tab "Memory" of Chrome Developer-tools, before or after call the function, then compare two snapshots, the comparision list will show all the details how memory leaks. 

var mesh0;
function testme(){
	var manager = new THREE.LoadingManager(function(){
		mesh0 = new THREE.Mesh( new THREE.PlaneBufferGeometry( 3, 3 ), new THREE.MeshBasicMaterial( { map: map0 } ) );
		scene.add( mesh0 );
	});

	var texloader = new THREE.TextureLoader(manager);				
	var map0 = texloader.load("textures/1.png"); 	
}


function delme(){			
	scene.remove(mesh0);
	
	mesh0.geometry.dispose();
	mesh0.material.map.dispose();
	mesh0.material.dispose();
	mesh0 = null;		
}

**Comment by takahirox** [comment] 2017-10-25 22:26
I knew how to take snapshot and check leak. I wanted you to first explain the detail, not just "try this code",  because it helps other devs to debug. And I don't recommend "run this code 'on any example'". It'd be better to make complete example because it's simpler to reproduce the issue and other devs can focus on the code which can cause the issue. Please always try to help other devs to figure out and fix the issue as much as possible when you report.

**Comment by zdddrszj** [comment] 2018-01-09 11:09
I have the same problem. But the old version of 52 is well.

**Comment by alinhulea** [comment] 2018-01-22 09:14
Any update on this issue guys ?

**Comment by alinhulea** [comment] 2018-01-25 12:27
I have tried the webgl_test_memory example as it is and the memory seems to be released properly. 
However, using the canvas size of about 1000X1000 instead of 256X256 in the same example in Firefox will result in GPU memory greater that 3GB in a matter of seconds ...and crash

Tried the solution with a single POT canvas and it seems to work better, no crash.
However the single POT canvas solution is not usable when multiple textures are created in a single frame, because all of the created textures share the same "image" reference at the point the texture is uploaded to the GPU. 
If you can force the texture upload when creating it immediately then the single POT canvas solution could work, given that you do not need to re-upload the texture, as it would use the current canvas content not the initial one uploaded

**Comment by Mugen87** [comment] 2018-01-26 20:15
@alinhulea So you suggesting something like this?
```javascript
var _canvas = document.createElementNS( 'http://www.w3.org/1999/xhtml', 'canvas' );
var _context = _canvas.getContext( '2d' );

function makePowerOfTwo( image ) {

   if ( image instanceof HTMLImageElement || image instanceof HTMLCanvasElement || image instanceof ImageBitmap ) {

      _canvas.width = _Math.floorPowerOfTwo( image.width );
      _canvas.height = _Math.floorPowerOfTwo( image.height );

      _context.drawImage( image, 0, 0, _canvas.width, _canvas.height );

      console.warn( 'THREE.WebGLRenderer: image is not power of two (' + image.width + 'x' + image.height + '). Resized to ' + _canvas.width + 'x' + _canvas.height, image );

      return _canvas;

   }

   return image;

}
```
I think this should work since `makePowerOfTwo()` is only used inside `uploadTexture()`. When the generated image data are uploaded to the GPU memory via `texImage2D()`, there should be no problem to overwrite the canvas with other data. A new upload should also be no problem since this triggers the recreation of the POT image data.

@mrdoob Do I overlook something obvious? 😅

**Comment by alinhulea** [comment] 2018-01-29 10:05
@Mugen87  In the webgl_test_memory example the images are created using a canvas like so: 

> function createImage() {
> 				var canvas = document.createElement( 'canvas' );
> 				canvas.width = 1000; //initial 256
> 				canvas.height = 1000; //initial 256
> ....
> 				return canvas;
> 			} 

As I mentioned, with the canvas size changed from 256x256 to 1000x1000 in this example will result in GPU memory greater that 3GB in Firefox in couple of seconds ...and crash. 
In this example I have tried to reuse the same canvas (not the canvas in Three.js makePowerOfTwo code)  and it seems to work better.

So, I tried the solution/change you mentioned in the Three.js code, same example with 1000x1000 dimensions, same problem, memory goes beyond 3GB fast.
I tried a small change that has managed to maintain acceptable amount of GPU memory and avoid crash, I commented this warning : 

> console.warn( 'THREE.WebGLRenderer: image is not power of two...

**Comment by Mugen87** [comment] 2018-01-29 10:10
So the huge amount of logs produced by `console.warn` is responsible for your memory problem?

**Comment by Mugen87** [comment] 2018-01-29 11:58
BTW: I suggest to close this issue and mark it as a duplicate.

#11378 should be the leading issue.

**Comment by mrdoob** [comment] 2018-01-30 03:48
@Mugen87 sounds good 👍

**Closed** 2018-01-30 13:42 UTC
Labels: Duplicate
