### ISSUE TITLE
blender exporter not exporting textures

### ISSUE THREAD

**Issue by jesseolssondirt** [mrdoob/three.js#5927] opened 2015-01-18 21:28 UTC
i'm trying the new r70 blender exporter and it is working great except that when i try to export a texture the following error is displayed and no file is exported. correct me if i'm wrong, but this seems to be a bug.
![screen shot 2015-01-18 at 4 24 46 pm](https://cloud.githubusercontent.com/assets/10490452/5794131/9c184e58-9f2e-11e4-8427-e29eed21861a.png)

**Comment by yomotsu** [comment] 2015-01-18 21:35
It may be caused by unused material. remove it if it exists.
![screen shot 2015-01-19 at 4 21 59 am](https://cloud.githubusercontent.com/assets/212837/5793759/34d43d1e-9f93-11e4-8885-099e4e8b311c.png)

**Comment by jesseolssondirt** [comment] 2015-01-18 21:39
no, its not that. im worried that i didn't configure the exporter options correctly, but i tried pretty much every configuration.

**Comment by repsac** [comment] 2015-01-18 22:02
Hmm may be something about your scene. I ran one of my test scripts and there was no issue. Doesn't mean there isn't a bug I just don't know the details of how your scene is setup.

FYI for everyone, the exporter writes everything to log. The path prints in your shell. Just look for something like this:
```
Log: /var/folders/0s/d7365qbn5gv76sj266_9qqs00000gn/T/io_three.export.log
```

Thinking of just having people upload (http://pastebin.com/ maybe?) or email those logs since it contains for more useful information than what is shown in the Blender dialog. It also logs all the parameters that are set making it much easier to see exactly what you set in Blender.

**Comment by jesseolssondirt** [comment] 2015-01-18 22:31
@repsac i dont know if you have time to look at this but if you want to: [http://pastebin.com/djCMxxFq](http://pastebin.com/djCMxxFq)

**Comment by jesseolssondirt** [comment] 2015-01-19 01:28
okay i think i identified the problem, you only get the error if the texture is in the same folder and you leave "copy textures" checked. it would be nice to fix this for future users. unfortunately i now have the texture in my json file, but it isn't loading in my scene with ObjectLoader. Does anyone have a tip?

**Comment by repsac** [comment] 2015-01-19 05:31
OK yeah. I wonder if it should attempt to delete the destination file first, you know just in case the texture itself was updated. I never hit this because my workflow is to use other addons that actually dump everything to a temp directory in `$TMPDIR`, perform a QC (ensures each texture in the JSON is accounted for), move to staging directory (another temp dir) to review in WebGL before publishing.

Concerning the ObjectLoader(); the loader isn't up to date with all the features the exporter has (textures, non-embedded geometry, etc). Unfortunately the ObjectLoader() is not something I am working on.

**Comment by repsac** [comment] 2015-01-19 05:32
@mrdoob can you assign this issue to me so I can remember to check for existing texture files?

**Comment by repsac** [comment] 2015-01-19 05:33
@jesseolssondirt thanks for the pastebin, that helps a lot

**Comment by mrdoob** [comment] 2015-01-19 09:52
@repsac Uh... doesn't let  me assign to anyone than me. I suspect that that requires adding you as collaborator. Never tried that before. Just make sure you don't push to my master/dev branches ;)

**Comment by mrdoob** [comment] 2015-01-19 09:57
Actually, feel free to push to the `dev` branch directly. just don't push to `master`.

**Comment by repsac** [comment] 2015-01-19 09:59
haha OK, well if that is the case don't feel you need to add me as collaborator. I will just do this the old fashioned way. It's too bad because there are so many issues being looked at by so many contributors it would be nice way to handle tracking in a bit more organized manner.

**Comment by mrdoob** [comment] 2015-01-19 10:07
Yep. I'm just worried about people pushing to master/dev by mistake. I'll try to suggest some fixes for this to github.

**Comment by poofik** [comment] 2015-01-19 20:11
I think you need to uncheck Skinning and uncheck Colors during export.

**Comment by poofik** [comment] 2015-01-19 20:15
As for ObjectLoader loading textures ...I have found partial solution here  https://github.com/denzp/three.js/commit/c069ec1b26014b55bc961846feaf7f7554fc2bb2 but it only works for some models ...needs work.

**Comment by repsac** [comment] 2015-01-27 04:52
@jesseolssondirt I implemented a check if the destination exists. If it does then the destination is removed first.
I haven't submitted a PR yet but this is the current branch if you wish to try it.
https://github.com/repsac/three.js/tree/io_three

**Comment by Akfreak** [comment] 2015-01-27 21:51
I have the same exact problem. No materials exported from blender http://pastebin.com/ZwcaJz5L. However I was able to get metadata by deleting unused an unused material before export.

**Comment by repsac** [comment] 2015-01-27 22:04
Actually that isn't the exact same problem. He was having tracebacks from texture copying, yours is an empty materials array.

**Comment by Akfreak** [comment] 2015-01-27 22:10
Sorry for my mistake.

**Comment by jesseolssondirt** [comment] 2015-01-28 22:35
@repsac i was away i'll try it as soon as i can

**Comment by repsac** [comment] 2015-01-29 00:58
@jesseolssondirt no rush, don't think I will make a PR until early next week

**Comment by jesseolssondirt** [comment] 2015-01-29 03:41
@repsac erm... it didn't work, i got an error again when "copy textures" was checked. i looked at the log ([http://pastebin.com/cTm3ZqMi](http://pastebin.com/cTm3ZqMi)) and it looks like maybe it was trying to remove the Desktop folder instead of the file? Or I might be doing something wrong.

**Comment by repsac** [comment] 2015-01-29 07:39
@jesseolssondirt No you're not, it's my fault. I thought I had pushed my latest commit but turns out I hadn't. It is pushed now https://github.com/repsac/three.js/tree/io_three

**Comment by repsac** [comment] 2015-01-29 07:42
And I did run a test export and the texture copied fine for me
```
2015-01-28 23:37:05,989 - Three.Export - INFO: Destination file exists, attempting to remove /Users/ed/work/temp/io_three/cloud.png
...
$ ll /Users/ed/work/temp/io_three/cloud.png
-rw-r--r--  1 ed  staff  609936 Jan 28 23:37 /Users/ed/work/temp/io_three/cloud.png
```

**Comment by ocurir** [comment] 2015-02-08 17:57
@repsac (i used to be @jesseolssondirt ) i tried it and still got an error, but now the image file was deleted and not replaced. [pastebin](http://pastebin.com/skEZ07Zq)

**Comment by repsac** [comment] 2015-02-08 23:20
Looking at the log it was trying to copy the file to the same destination it lives in
```
2015-02-08 12:53:21,181 - Three.Export - DEBUG: io.copy_registered_textures(/Users/jesseolsson/Desktop, {'d927341613b2080973fdecd9be927a6b': {'file_name': 'box.jpg', 'file_path': '/Users/jesseolsson/Desktop/box.jpg', 'maps': ['mapDiffuse']}})
2015-02-08 12:53:21,181 - Three.Export - DEBUG: io.copy(/Users/jesseolsson/Desktop/box.jpg, /Users/jesseolsson/Desktop)
```

I had logic that would delete the destination first so sorry about the lost file. You would have still had an error, example:
```
>>> shutil.copy('untitled.js', os.getcwd())
shutil.Error: `untitled.js` and `/Users/ed/untitled.js` are the same file
```

Am making some changes. There will be no removal of files, but only if the source and destination are not matching paths.

Sorry again about the deleted file.

**Comment by ocurir** [comment] 2015-02-09 00:19
@repsac haha no i made sure to use a test file

**Comment by repsac** [comment] 2015-02-11 02:38
https://github.com/mrdoob/three.js/pull/6048/

**Comment by repsac** [comment] 2015-02-12 05:27
This is merged, can you confirm it works?

**Comment by ocurir** [comment] 2015-02-14 02:05
yes it works. i like the new options menu by the way.

**Comment by repsac** [comment] 2015-02-14 02:33
Good to hear, thanks!

**Closed by repsac** 2015-02-14 02:33 UTC
Labels: Enhancement
