### ISSUE TITLE
Flipping BufferGeometry through BufferGeometryUtils

### ISSUE THREAD

**Issue by reimund** [mrdoob/three.js#18683] opened 2020-02-20 05:15 UTC
I was doing some buffer geo flippin' yesterday when I came across this nice utility function:
https://stackoverflow.com/questions/16824650/#answer-54496265

Wouldn't this be handy to have in BufferGeometryUtils? Or is there a more convenient way to flip BufferGeometries?

**Comment by Mugen87** [comment] 2020-02-20 09:40
Related #17361.

**Comment by Mugen87** [comment] 2020-03-16 12:33
Closing as duplicate of #17361.

**Closed by Mugen87** 2020-03-16 12:33 UTC
