### ISSUE TITLE
`MeshStandardMaterial().skinning = true` doesn't work with `scene.overrideMaterial`.

### ISSUE THREAD

**Issue by will-ca** [mrdoob/three.js#19912] opened 2020-07-23 05:22 UTC
##### Description of the problem

Assigning `.skinning = true` doesn't work when the material is assigned to `scene.overrideMaterial`:

`scene.overrideMaterial = new THREE.MeshPhysicalMaterial({skinning: true})`

The material and rendered image behave identically to as if `.skinning === false`.

##### Three.js version

- [ x ] r118

##### Browser

- [x] All of them
- [x] Chrome
- [x] Firefox
- [x] Webkit

**Comment by WestLangley** [comment] 2020-07-23 05:30
Likely a duplicate of #14577. See links for additional related post.

**Comment by will-ca** [comment] 2020-07-23 05:41
@WestLangley I saw and read that issue, and from my understanding, it's completely different.

#14577 is about *selectively* preserving effects from the *originally assigned, un-overridden* materials on each object while doing the final shading using the new override material. I.E. It's about combining arbitrary materials by processing the override material as if the shaded surfaces had modifications to their normal, depth, and other properties that would originally have been accounted for by the original, unoverriden material.

This issue is about *properly handling a property of the new, override material*. Resolving this issue does not require cleverly combining behaviours from multiple arbitrary materials; it only requires properly handling the already-implemented properties of one material. Likewise, issue #14577 is at most an enhancement in severity because it describes a desired behaviour that extends *beyond* the documented behaviour of *overriding* materials; whereas I believe this is more of an "issue" because it describes a situation where the presently documented behaviour of overriding materials *fails*, by failing to properly handle an already-existing feature of the override material.

**Comment by WestLangley** [comment] 2020-07-23 17:49
>scene.overrideMaterial = new THREE.MeshPhysicalMaterial( { skinning: true } )

Is everything in your scene a skinned mesh?

I think more info about your use case would be helpful. A simple live example may help to clarify your use case.

**Comment by will-ca** [comment] 2020-07-24 01:29
@WestLangley 

> Is everything in your scene a skinned mesh?

In the scene I've tested, I believe every mesh object is a skinned mesh, yes.

That is not true of the `Object3D`s, `Group`s, or scene background, however, the last of which also seems to be affected by `scene.overrideMaterial`.

> I think more info about your use case would be helpful. A simple live example may help to clarify your use case.

I'm not sure my specific use case actually matters for this issue, so much as does the deviation from documented, expected, and self-consistent behaviour.

I'm also not sure what more relevant information there is:

There is a property that is documented as "forc[ing] everything in the scene to be rendered with that material", and another property that is documented as "Defin[ing] whether the material uses skinning".

When these two properties are used together, one of them breaks, to the effect that the material is always rendered as if skinning were disabled.

That is all there is to it.

A "simple live example" is also a bit tricky to me, because any live example of this must necessarily go through all the boilerplate of loading and animating a skinned mesh.

The reproducer I included in the original post is already only a single line long, and can be pasted into any scene with skinned meshes to show the issue.

However, here's an example based on the official example for skinned meshes:

https://jsfiddle.net/q8vm4tbd/

The first checkbox in the first section of the `dat.gui` window toggles the conditions of the issue.

**Comment by WestLangley** [comment] 2020-07-24 02:50
I think it is still true that Materials cannot be shared between skinned and non-skinned meshes. That would apply to `overrideMaterial`, too.  In your fiddle, removing the ground plane solves the problem.

https://jsfiddle.net/pv3aLoc5/

>Is everything in your scene a skinned mesh?
>>In the scene I've tested, I believe every mesh object is a skinned mesh, yes.

Can you please check again?

**Comment by will-ca** [comment] 2020-07-24 08:22
Huh. It looks like there are a bunch of Object3D's, especially at the ends of each bone chain:

`JSON.stringify((function hierarchy(obj) {return [obj.constructor.name, obj.children.map(hierarchy)];} )(scene), null, 0)`

`
["Scene",[["Group",[["Object3D",[["Bone",[["Bone",[["Bone",[["Bone",[["Bone",[["Bone",[["Object3D",[]]]]]],["Bone",[["Bone",[["Bone",[["Bone",[["Bone",[["Bone",[["Object3D",[["Object3D",[]]]]]]]],["Bone",[["Bone",[["Bone",[["Object3D",[]]]]]]]],["Bone",[["Bone",[["Bone",[["Object3D",[]]]]]]]],["Bone",[["Bone",[["Bone",[["Object3D",[]]]]]]]],["Bone",[["Bone",[["Object3D",[["Object3D",[]]]]]]]]]]]]]]]],["Bone",[["Bone",[["Bone",[["Bone",[["Bone",[["Bone",[["Bone",[["Object3D",[]]]]]]]],["Bone",[["Bone",[["Bone",[["Object3D",[]]]]]]]],["Bone",[["Bone",[["Bone",[["Object3D",[]]]]]]]],["Bone",[["Bone",[["Bone",[["Object3D",[]]]]]]]],["Bone",[["Bone",[["Object3D",[["Object3D",[]]]]]]]]]]]]]]]]]]]]]],["Bone",[["Bone",[["Bone",[["Bone",[["Object3D",[]]]]]]]]]],["Bone",[["Bone",[["Bone",[["Bone",[["Object3D",[]]]]]]]]]]]],["SkinnedMesh",[]],["SkinnedMesh",[]]]]]],["PerspectiveCamera",[]]]]
`

(This is actually the same model as in the JSFiddle example, just re-exported from Blender and loaded a bit differently, I think.)

It doesn't look like there are any `Mesh` objects, or any objects that contain renderable geometry, except for the two `SkinnedMesh`es, however.

**Comment by rchee** [comment] 2021-03-16 09:46
Same issue when I using SSAOPass. It looks like threejs cached a Program which not incolude `#define USE_SKINNING
#define BONE_TEXTURE` and use it in randering Skinning Mash.

For my useage, I add below code [here](https://github.com/mrdoob/three.js/blob/0b1d595df49039b5bf83e1ab84c571100944d025/src/renderers/WebGLRenderer.js#L1527) to temporarily fix the issue.
`````js
		if(material.type === "MeshNormalMaterial"){
			needsProgramChange = true 
		}
`````

**Closed** 2021-05-05 15:50 UTC
Labels: Needs Investigation
