### ISSUE TITLE
Allow GLTFLoader to import tangents or make BufferGeometryUtils.computeTangents use the Mikktspace algorithm

### ISSUE THREAD

**Issue by stephenhurleyjpl** [mrdoob/three.js#15428] opened 2018-12-13 20:12 UTC
##### Description of the problem

Right now, the GLTFLoader does not import tangents, but the user can instead use one of two options (that I'm aware of):

* Use `THREE.BufferGeometryUtils.computeTangents` to compute the tangents and create an `tangent` attribute, which can then be used to show tangents.
* Use the fragment shader tangent creation code found in [/src/renderers/shaders/ShaderChunk/normalmap_pars_fragment.glsl.js](https://github.com/mrdoob/three.js/blob/master/src/renderers/shaders/ShaderChunk/normalmap_pars_fragment.glsl.js) via various materials.

The problem with both of these methods is that they do not always reliably calculate the tangent space, since different programs use different tangent spaces. There are two solutions to this problem that I can think of so far:

* Convert `THREE.BufferGeometryUtils.computeTangents` to use the Mikktspace algorithm, which is becoming a standard for generating tangent spaces. See [Blender's Notes](https://en.blender.org/index.php/Dev:Shading/Tangent_Space_Normal_Maps), the [Houdini implementation (see the mikktspace.c file)](https://github.com/teared/mikktspace-for-houdini/tree/master/source), the [suggestion by the Khronos Group to use Mikktspace](https://github.com/KhronosGroup/glTF/issues/1252), and the [original paper](http://image.diku.dk/projects/media/morten.mikkelsen.08.pdf).
* Allow GLTFLoader to import tangents that are stored in GLTF files so that model programs can do the heavy work of creating tangents instead of Three.js applications. Currently GLTFLoader ignores tangents and instead relies on the fragment shader generation method, which can cause its own artifacts because the dFdx and dFdy functions don't work well with uv coordinates that have discontinuities at vertices.

##### Three.js version

- [ ] Dev
- [x] r99
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by donmccurdy** [comment] 2018-12-13 21:53
If it's helpful, I previously attempted to re-implement support for a 'tangent' attribute here: https://github.com/mrdoob/three.js/compare/dev...donmccurdy:feat-attribute-tangents. The issue I was trying to solve there was fixed by improving the fragment shader computations, instead, so I never opened a PR for it.

**Comment by stephenhurleyjpl** [comment] 2018-12-13 23:41
I'm seeing if I can get a good example for you to look at. In the mean time, I've done a bit more research, and this is what I have so far.

Using the fragment shader option, if I modify the material.normalScale to instead be (-1, 1) instead of (1, -1), the normal map on my model works well. #13784 has a lot of good conversation about it all, and I'm trying to wrap my head around it. But I unfortunately get artifacts such as this:

<img width="431" alt="image" src="https://user-images.githubusercontent.com/3408852/49971378-1ea59700-fee3-11e8-8b81-ed2691c1eede.png">

If I use THREE.BufferGeometryUtils.computeTangents, then I remove the artifacts that you see above, but I find the vertical component of the normal map needs to be flipped (just like the fragment shade does, using normalScale). If I don't flip it, it looks like this:

<img width="442" alt="image" src="https://user-images.githubusercontent.com/3408852/49971652-0a15ce80-fee4-11e8-9853-c3850ec3b245.png">

So, I think I've found a solution that works, to generate the tangents via `BufferGeometryUtils.computeTangents` after the GLTF mesh is loaded, and then use some custom shader code just like in your PR that uses the tangent attribute rather than fragment shader generated tangents, and then do the flip of the y component of the normal map like in the fragment shader code. The result is this:

<img width="463" alt="image" src="https://user-images.githubusercontent.com/3408852/49974076-8a403200-feec-11e8-8154-c35879cf648e.png">

The last seam shown is just an artifact of the texturing itself and is visible in Blender as well.

So I don't know if there needs to be any change in Three.JS or not, except that the built-in fragment shader tangent space function produces artifacts. I believe this has something to do with the dFdx functions, that they don't take into account the interpolation of the coordinates passed into them (maybe just for uv), and so produce artifacts when there are discontinuities in the coordinates, although I'm not completely sure.

I do believe your PR would be a good addition to Three.JS, as it would enable app developers to use the pre-computed tangents instead of generating them when the GLTF is loaded, saving a bit of computation time, especially for GLTF files with larger vertex counts.

**Comment by pailhead** [comment] 2018-12-18 20:16
>Support for stored tangents was removed from this library three years ago (see #7094) and since then no one has presented an argument for bringing that back.

Not entirely true :)

[I've been arguing for those three years that it's **simply impossible** to render any baked normal map with three.js :)
](http://192.241.199.119:8080/dev/testwp/)

It would be nice to just be able to provide generic GLSL (mikkspace, max, maya etc) for normal mapping. It's actually possible to do this with `onBeforeCompile` since it's pretty self contained, but it could be more explicit.

**Comment by pailhead** [comment] 2018-12-18 20:17
>which can cause its own artifacts because the dFdx and dFdy functions don't work well with uv coordinates that have discontinuities at vertices.

This is not the issue, the issue is the tangent's are usually not derived from uvs alone, especially in the case of something as complex as mikkspace. The same way vertices are weighted (or in a different way depending on the space) tangents need to be computed, possibly binormals as well.

**Comment by mrdoob** [comment] 2018-12-18 23:43
> Support for stored tangents was removed from this library three years ago (see #7094) and since then no one has presented an argument for bringing that back.

At the time, tangents were a bit too much that we were able to chew. Since then gltf has taken care of that part of the workflow and we could give it another go.

> If it's helpful, I previously attempted to re-implement support for a 'tangent' attribute here: https://github.com/mrdoob/three.js/compare/dev...donmccurdy:feat-attribute-tangents.

Glad to see that you did the work already! I think we should land this. It'll help to make sure we render like other engines.

**Comment by stephenhurleyjpl** [comment] 2019-01-07 18:34
Thanks for all of the great input guys. In the mean time I was able to use `THREE.BufferGeometryUtils.computeTangents` to compute the tangents, use a custom shader that takes a tangent attribute and compute the bitangent vectors (using w to flip if necessary). While the results may not be a robust as a mikkspace algorithm or whatever tangents are in the GLTF file, it looks good right now. I look forward to the GLTF tangent importing!

**Comment by donmccurdy** [comment] 2019-02-07 20:13
Some updates: https://github.com/mrdoob/three.js/compare/dev...donmccurdy:feat-attribute-tangents-v2

**Closed** 2019-02-15 03:03 UTC
Labels: Loaders, Suggestion

**Comment by donmccurdy** [comment] 2021-02-25 18:56
Just FYI, I've set up a WASM library for computing MikkTSpace tangents: https://github.com/donmccurdy/mikktspace-wasm. You can apply it to an existing glTF file with the `tangents` command from https://gltf-transform.donmccurdy.com/cli.html.
