### ISSUE TITLE
WebGLRenderer.setSize affects other instances in Chrome for Android

### ISSUE THREAD

**Issue by LasseD** [mrdoob/three.js#19866] opened 2020-07-17 17:19 UTC
##### Description of the problem

There is a bug in Chrome for Android when using multiple renderers and calling .setSize() on one of them. 

`  renderer1 = new THREE.WebGLRenderer(); renderer1.setSize(200, 200); // Set the size to 200 x 200`

`renderer2 = new THREE.WebGLRenderer(); renderer2.setSize(100, 100);  // Sets the shown region of renderer1 to the 100 x 100 region in the lower left corner. The remainder of the canvas will no longer render. renderer2 still works fine.`

The bug appears on Chrome for Android only. Other browsers behave as expected (Edge, Safari, Chrome, Firefox for Win10, WinXP, iOS, Mac).

Expected as observed in Chrome for MAC:

![Expected output](https://i.imgur.com/wBvpD7y.png)

Observed in emulator of Chrome for Android:

![Incorrect rendering](https://i.imgur.com/T2p8aAm.png)

Live examples:

* [jsfiddle](https://jsfiddle.net/LasseD/7fx9atkL/) (latest release branch)
* [jsfiddle](https://jsfiddle.net/LasseD/1u8Loyft/) (dev branch)

Please note that there also appears to be a culling issue in the emulator when showing the simple geometries, such as BoxGeometry and SphereGeometry. I am using BoxGeometry in the example in other to keep them as simple as possible. The culling issue does not appear when using the custom geometries in the original bug report. Please tell me if you prefer other types of examples where the culling issue is not present.

Original bug report: [https://github.com/LasseD/buildinginstructions.js/issues/39](https://github.com/LasseD/buildinginstructions.js/issues/39)

##### Three.js version

- [X] Dev
- [X] r118

##### Browser

- [ ] All of them
- [X] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [X] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

Emulated in Android Studio with Pixel XL API 30

**Comment by Mugen87** [comment] 2020-07-17 17:26
I'm unable to reproduce the issue on a Pixel 1 with latest Chrome. 

This seems to be an issue of the android emulator.

**Comment by LasseD** [comment] 2020-07-17 17:40
@mfeldt observed the original bug on "Android 9". My own Android device is version 2.3 which lost support for three.js a long time ago, so I don't have a physical device at hand for reproduction. 

I have tried crowdsourcing this bug on facebook to see which Android devices (if any) are affected. If the setSize bug turns out to be emuator only, then I have to get back to the drawing board.

**Comment by LasseD** [comment] 2020-07-17 17:52
@Mugen87 Thanks for looking into it. I have downloaded the emulator corresponding to Pixel 1 which shows the bug. This indicates that the reported bug is emulator-specific and that I have to get a new-ish Android device in order to perform proper debugging.

**Comment by Mugen87** [comment] 2020-07-17 18:40
Closing for now then.

**Closed by Mugen87** 2020-07-17 18:40 UTC
