### ISSUE TITLE
Adding a BufferAttribute from a regular array causes glDrawArrays to fail

### ISSUE THREAD

**Issue by Doeke** [mrdoob/three.js#7896] opened 2016-01-02 16:14 UTC
Docs says "The array can either be a regular Array or a Typed Array.", but unless I use a typed array I get the following error:

    glDrawArrays: attempt to access out of range vertices in attribute 0

Is this a bug? It's convenient to be able to use regular arrays because then the buffer is expanded as needed when you use `BufferGeometry.merge`. Otherwise I'll have to precalculate the final vertex count or convert the regular array in BufferAttribute to a typedarray somehow.

**Comment by WestLangley** [comment] 2016-01-02 18:19
Duplicate of #7820

**Comment by mrdoob** [comment] 2016-01-13 11:56
> Is this a bug? It's convenient to be able to use regular arrays because then the buffer is expanded as needed when you use `BufferGeometry.merge`. Otherwise I'll have to precalculate the final vertex count or convert the regular array in BufferAttribute to a typedarray somehow.

I don't think we should support that. Otherwise the renderer will need to check every frame if the array is a typedarray and if check if it changed if previously created it. I think `BufferAttribute` should be as dumb as possible.

**Closed by mrdoob** 2016-01-13 11:56 UTC
Labels: Suggestion
