### ISSUE TITLE
The `Zero-ScrColor` material is flashing in `webgl_materials_blending_custom.html`.

### ISSUE THREAD

**Issue by linbingquan** [mrdoob/three.js#23244] opened 2022-01-15 10:25 UTC
**Describe the bug**

The `Zero-ScrColor` material is flashing in webgl_materials_blending_custom.html

**To Reproduce**

1. Open `webgl_materials_blending_custom.html` in brower.

**Expected behavior**

The `Zero-ScrColor` material should not be flashing.

**Screenshots**

![flash](https://user-images.githubusercontent.com/23699926/149618204-3246e629-8229-4457-a833-50bf037087d4.gif)

![bug](https://user-images.githubusercontent.com/23699926/149618222-3202329f-2c38-41a1-b31e-911eff4a040f.png)

**Platform:**

 - Device: [Desktop]
 - OS: [Windows11]
 - Browser: [Edge97]
 - Three.js version: [dev]

PS: In Chrome, Firefox can't be reproduce with dev code. In Edge97 can't be reproduce with prod code.

**Comment by Mugen87** [comment] 2022-01-15 11:42
Do you still see the flashing with this link:

https://raw.githack.com/Mugen87/three.js/be508ae54d620f6410bb27af75b74eb9a1765776/examples/webgl_materials_blending_custom.html

**Comment by linbingquan** [comment] 2022-01-15 12:28
> Do you still see the flashing with this link:
> https://raw.githack.com/Mugen87/three.js/be508ae54d620f6410bb27af75b74eb9a1765776/examples/webgl_materials_blending_custom.html

TBH, I can't open your link. but I found you changed this code. I still see the flashing with this code.

```diff
-const context = canvas.getContext( 'webgl', { alpha: false } );
+const context = canvas.getContext( 'webgl2', { alpha: false } );
```

**Comment by Mugen87** [comment] 2022-01-15 15:01
I've tested the link on a Windows 10 laptop with Edge 97 and can't reproduce the issue.

**Comment by Mugen87** [comment] 2022-01-20 11:15
Closing. Please report this issue to the Edge team.

**Closed by Mugen87** 2022-01-20 11:15 UTC

**Comment by linbingquan** [comment] 2022-01-22 02:51
It doesn't flashing with #23246
