### ISSUE TITLE
Implement Bounding Boxes in Groups to improve the frustum culling performance.

### ISSUE THREAD

**Issue by eipporko** [mrdoob/three.js#23670] opened 2022-03-07 18:43 UTC
**Is your feature request related to a problem? Please describe.**

I'm struggling with a poor performance when certain number of meshes are being rendered.

Doing some research about the inner working of the threejs pipeline, I found that in the render process is being performed a filtering with the purpose of renders only visible objects laying within the camera frustum. But despite to be nesting the meshes in groups, the process of filtering is performed only in Mesh, Line or Point objects.

**Describe the solution you'd like**

Could be interesting to implement the possibility of computing bounding boxes in Groups to avoid to check their children if them are laying outside the camera frustum.

For example if you have a scene with 100 groups of 10 meshes each, with the actual way there are performed a 1000 of checks to know what meshes are laying within the camera frustum. Implementing bounding boxes in groups, only 100 checks would be needed to know what groups are laying within the camera frustum and then checks the children of groups which tested positive.

The bounding box of the group could be updated by the user or each time a children is added or removed, performing an union with the children's bounding box.

And the same could be applied in Raycaster

**Describe alternatives you've considered**

I have structured the scene in chunks, so my idea is to perform a pre filter before call the render method.

**Additional context**

-

**Comment by mrdoob** [comment] 2022-03-07 19:36
Why did you ignored the issues template?

**Comment by eipporko** [comment] 2022-03-07 19:53
I tried to answer all the questions presented in the template, but I can edit the issue and copy paste each paragraph.

**Comment by mrdoob** [comment] 2022-03-07 20:18
Make sure to create a jsfiddle showing how your scene is not performing.

**Comment by LeviPesin** [comment] 2022-03-08 05:41
Is this related to https://github.com/mrdoob/three.js/issues/7071?

**Comment by eipporko** [comment] 2022-03-08 07:59
I think that #7071 refers to [BufferGeometry](https://threejs.org/docs/?q=BufferGeometry#api/en/core/BufferGeometry.groups) objects where the geometries were splitted and that bounding sphere refers internally to the same BufferGeometry object. 

In my proposal I was refering to the possibility of compute bounding boxes into the [Group](https://threejs.org/docs/?q=Group#api/en/objects/Group) object in order to try to easiest the task of frustum culling.

**Comment by Mugen87** [comment] 2022-03-08 08:42
This issue is a duplicate of #7071. They are about the same thing.

**Comment by eipporko** [comment] 2022-03-08 08:56
I really think that is not a duplicate in the way that, as I metioned before, both issues are dealing about different components.

**Comment by Mugen87** [comment] 2022-03-08 09:10
Oh, you are right. The group terminology actually confused me.

Instead of implementing something in `three.js` have you considered to improve your performance with a separate structure like a BVH?

**Comment by eipporko** [comment] 2022-03-08 10:03
Yep, I was reading in some threads that were metioned another projects like [three-mesh-bvh](https://github.com/gkjohnson/three-mesh-bvh) or [threeoctree](https://github.com/collinhover/threeoctree)

But finally I think that in my personal case, as I have actually structured the scene with some kind of spatial hashing is easy for me perform a pre render process to update the visibility value of the groups outside from the camera frustum and avoid to send all the scene to render.

The reason of my proposal was because meanwhile I was reading the method `projectObject( object, camera, groupOrder, sortObjects )` in the `WebGLRenderer` to understand what was happening, I notice that the method was performing a test for all the meshes presented in the scene. And could be interesting to avoid to test meshes which were grouped as children of a Group with a hierarchically superior bounding box performing outside de camera frustum. If the parent is outside the camera frustum no make sense to test their children.

Was only an idea to discuss if make sense or not, but I think that could improve the general performance. Maybe it has some handycaps or headaches with dynamic groups where the children are changing the position, scale or something else forcing to the parent to update the bounding box. But with static scenes could be interesting.

**Comment by Mugen87** [comment] 2022-03-10 11:24
If this feature is implemented such that group bounding volumes are static, there will be a lot of complaints and bug reports because the bounding volumes will be quickly considered to be out of date. A dynamic approach requires to keep track of descendants or to recompute the bounding volumes every frame. Both solutions are not ideal.

It's better for now to keep this complexity out of the renderer and manage/sort objects on app level instead.

**Closed by Mugen87** 2022-03-10 11:24 UTC

**Comment by arpu** [comment] 2022-03-10 11:51
would be nice to have a example on this, to disable the normal threejs frustum culling and using [three-mesh-bvh](https://github.com/gkjohnson/three-mesh-bvh)
