### ISSUE TITLE
InstancedGeometryBuffer not updated property between render calls

### ISSUE THREAD

**Issue by Usnul** [mrdoob/three.js#22843] opened 2021-11-16 11:16 UTC
When you use `InstancedBufferGeometry` without using `InstancedMesh`, your geometry attributes are not updated properly. Here's the culprit:

https://github.com/mrdoob/three.js/blob/0d7fb8d74f3c4d4e465b5a92ada65e1c789708e1/src/renderers/webgl/WebGLBindingStates.js#L50

Part of the fix would be to check the `geometry` and not the `object`. That is if the `geometry.isInstancedBufferGeometry` instead of checking for `InstancedMesh` specifically.

Frankly, looking in the binding states implementation - I'm puzzled by the fact that version of the attribute is never checked against the cache, it basically says "oh, look, it's the same object reference, no update needed". Or I'm missing something.

**Comment by Usnul** [comment] 2021-11-16 11:51
I don't have a demo, because my code is quite complex and I'm not sure I can produce a reduced example quickly. But I will try to explain what I'm doing, so the issue is a bit more clear.

I'm updating geometry based on the camera state, rebuilding instance attributes as necessary. During rendering of a single frame, I do this twice:
* once for the shadow camera, to render shadow map
* once for the main camera, to render the main view

Here's what I get on r133, note that the floor plane is not part of the issue, it's there simply to help show the shadows:
![image](https://user-images.githubusercontent.com/5939063/141978392-d6584c86-0f75-4994-bb53-2f5cd3852975.png)

Here's what the correct result should look like, I get it by forcibly re-constructing new geometry object (brand new reference) every time:
![image](https://user-images.githubusercontent.com/5939063/141978576-c3e6adb0-273c-45aa-adb5-e112673c9c59.png)

**Comment by Usnul** [comment] 2021-11-16 11:56
Another interesting bit here, if you look at `WebGLShadowMap`, it has a bit that updates geometries:
https://github.com/mrdoob/three.js/blob/0d7fb8d74f3c4d4e465b5a92ada65e1c789708e1/src/renderers/webgl/WebGLShadowMap.js#L334

Curiously, I can't find anywhere else that does this.

**Comment by Mugen87** [comment] 2021-11-16 13:43
Since we have no example that dynamically updates instances per frame when using `InstancedBufferGeometry`, I've created the following fiddle: https://jsfiddle.net/6vwd0n4t/1/

I can't not reproduce a missing buffer update. Do you mind updating the example code so the issue becomes apparent?

> Frankly, looking in the binding states implementation - I'm puzzled by the fact that version of the attribute is never checked against the cache, it basically says "oh, look, it's the same object reference, no update needed". Or I'm missing something.

Binding setups is something different than buffer updates. A binding state describes what buffer attributes should be used for rendering. This is unrelated to when and how buffer data are updated.

**Comment by Usnul** [comment] 2021-11-16 14:02
> Do you mind updating the example code so the issue becomes apparent?

I'll try, there are a number of things that go into it. I don't see how right now, but I'll try.

I did manage to find a workaround, which requires a minor change to three.js code. I don't fully understand how buffers are updated yet, so I don't believe that my workaround is a good solution.

Here's what I did:

* add `.data` property to the `InstancedBufferAttribute`, set it to the same value as `.version` every time something is updated.
* add a line to `WebGLBindingStates` inside `setupVertexAttributes` function that invokes `attributes.update` like so:

```js
				if ( geometryAttribute !== undefined ) {

					const normalized = geometryAttribute.normalized;
					const size = geometryAttribute.itemSize;

                    attributes.update( geometryAttribute, gl.ARRAY_BUFFER ); // <- new line
                    const attribute = attributes.get( geometryAttribute );
```

then it works, the change is detected, and attribute is updated.

Meanwhile, the only workaround I see that doesn't require me to change three.js itself is to basically manage the attribute completely outside of three.js, directly via GL api.


> Binding setups is something different than buffer updates. A binding state describes what buffer attributes should be used for rendering. This is unrelated to when and how buffer data are updated.

If someone could help explain how/when the upload of attribute buffers happens I would be grateful.

**Comment by Mugen87** [comment] 2021-11-16 14:20
> If someone could help explain how/when the upload of attribute buffers happens I would be grateful.

This happens here:

https://github.com/mrdoob/three.js/blob/0d7fb8d74f3c4d4e465b5a92ada65e1c789708e1/src/renderers/WebGLRenderer.js#L1125

It is done once per frame for all geometries which are going to be rendered. The call of `WebGLObjects.update()` is done in `WebGLShadowMap`, too, since render items might be only visible for shadow cameras. Even if the call happens multiple times, the logic ensures buffer attributes are only updated once if they are marked for an update.

**Comment by Usnul** [comment] 2021-11-16 15:22
found the problem. The issue lies in the fact that renderer relies on `renderer.info.render.frame` index which can be incremented manually (and I do use it in that way, to keep track of overall frame stats). This index is incremented when you call `info.reset()`.

Inside `WebGLObjects.update` there's a cache that identifies whether a geometry needs to be updated or not based on this frame index.

Why does shadowmap renderer of three.js not break? - easy, because it explicitly updated geometries, skipping `WebGLObjects`. I guess this is something worth investigating. For now, the fix is to increment `info.render.frame` manually to trigger proper geometry updates.

**Comment by Mugen87** [comment] 2021-11-16 15:30
> Why does shadowmap renderer of three.js not break? - easy, because it explicitly updates geometries, skipping WebGLObjects.

I'm afraid that's not true. `WebGLShadowMap` does use `WebGLObjects`. `WebGLObjects` also does not increase the frame counter. This is done in `WebGLRenderer.render()`:

https://github.com/mrdoob/three.js/blob/0d7fb8d74f3c4d4e465b5a92ada65e1c789708e1/src/renderers/WebGLRenderer.js#L967

**Comment by Usnul** [comment] 2021-11-16 15:42
> I'm afraid that's not true. WebGLShadowMap does use WebGLObjects. WebGLObjects also does not increase the frame counter. This is done in WebGLRenderer.render():

You're absolutely right, I guess I'm the first person to have a use-case to modify geometry while assembling a single frame.

For the case of shadow map in three.js - geometry is assumed to remain the same, which is a perfectly valid assumption.

In case anyone's interested, the reason why it matters for me - is because of the [virtual geometry](https://discourse.threejs.org/t/virtually-geometric/28420), that is, depending on the view geometry might be drastically simplified, so shadowmaps and the main view may render drastically different number of triangles for the same mesh, depending on the shadowmap resolution, size of the object in the view and a few other factors.

**Comment by Mugen87** [comment] 2021-11-16 19:10
Since `InstancedGeometryBuffer ` is updated as expected I think it's okay to close the issue.

**Closed by Mugen87** 2021-11-16 19:10 UTC
