### ISSUE TITLE
import error from cdn in version 0.128

### ISSUE THREAD

**Issue by x1911** [mrdoob/three.js#21764] opened 2021-05-01 09:25 UTC
**Describe the bug**

import error in version 128 

***Code***

```
export default class LoadLib {
    constructor() {
        const _base = 'https://cdn.jsdelivr.net/npm/three@0.128.0/'
        this.url = _base + 'build/three.module.js'

        this._base = _base + 'examples/jsm/'
        this._obj = {
            BufferGeometryUtils: this._base + 'utils/BufferGeometryUtils.js',
            CopyShader: this._base + "shaders/CopyShader.js",
            EffectComposer: this._base + "postprocessing/EffectComposer.js",
            RenderPass: this._base + "postprocessing/RenderPass.js",
            ShaderPass: this._base + "postprocessing/ShaderPass.js",
            VignetteShader: this._base + "shaders/VignetteShader.js",
            UnrealBloomPass: this._base + "postprocessing/UnrealBloomPass.js",
        }

        this.start().then()
     }
           
   async start() {
        const THREE = await import(this.url) 

        const T3 = {}   
        for (let i in THREE) {
            T3[i] = THREE[i]
        }
        window.THREE = T3 

        for (let i in this._obj) {  
            const f = await import(this._obj[i])
            window.THREE = { ...window.THREE, ...f }
        }
    }

```

it runs very good until ver: 0.128

the error shows 
![image](https://user-images.githubusercontent.com/8219031/116777948-d7afa080-aaa1-11eb-96eb-6d3d5c9b5909.png)

it is the import script error, in version 0.128
![image](https://user-images.githubusercontent.com/8219031/116777967-f44bd880-aaa1-11eb-98d0-4c5f3fbc1597.png)

in ver 0.127 it works correctly
![image](https://user-images.githubusercontent.com/8219031/116777989-10e81080-aaa2-11eb-8a48-d67f6c6f83d2.png)

**Comment by Mugen87** [comment] 2021-05-01 09:28
Duplicate of #21707.

**Closed by Mugen87** 2021-05-01 09:28 UTC

**Comment by x1911** [comment] 2021-05-01 14:41
thanks for the example, it works now

**Comment by suryavsa1978-ui** [comment] 2026-07-14 06:41
https://cdn.jsdelivr.net/npm/three@0.128.0/
