### ISSUE TITLE
Donations for THREEjs Development?

### ISSUE THREAD

**Issue by OtterFamily** [mrdoob/three.js#11318] opened 2017-05-11 10:05 UTC
I work at a company where we make use of a lot of open source libraries and tools and where possible, we try to make a donation to their further development whenever we use them in our projects just as a way to materially contribute to the projects we love and need.

I was scanning around trying to find a way to put money in the pockets of THREEjs, but couldn't find anything. Is there a way to donate funds? or is that antithetical to the THREEjs project? I can see how there would be issues with how to share with everyone who contributes, but there are some fixed costs like hosting, etc that could be payed with donations.

Thanks for all the great work!

**Comment by mrdoob** [comment] 2017-05-11 14:48
Yeah, I wouldn't know how to distribute the money... so I tend to stay away from these things. Also, hosting is free.

**Comment by pailhead** [comment] 2017-05-11 17:42
Just hire three.js devs, and it will be developed :)

**Comment by fernandojsg** [comment] 2017-05-11 18:05
I think I agree with @pailhead let's say a person is working/has worked on a feature you like, you could donate to him directly to thanks him for that or to help him taking time to develop more features.

But I understand @mrdoob concerns about how to properly distribute the money around the huge amount of contributors that are doing/have done a great work. What about using the money to host simple competitions from time to time? Like a competition of demos done with threejs following some specific theme or so? :)

**Comment by fernandojsg** [comment] 2017-05-11 18:10
Or you could use the money to create threejs merchandising (tshirst, stickers...) and send them to the contributors :)

**Comment by pailhead** [comment] 2017-05-11 18:24
Where would you host this though? Things like this already happen in forms of various hackatons, 3d web fest etc.

**Comment by fernandojsg** [comment] 2017-05-11 18:26
Something more informal and simple. Let's say something like the ludum dare, to implement some effect or feature or demo with a theme and it could be even something that could be needed for the core itself.

**Comment by takahirox** [comment] 2017-05-13 09:29
(BTW I'm still looking for a job 😅)

**Comment by makc** [comment] 2017-05-16 17:57
> I wouldn't know how to distribute the money

https://www.bountysource.com/ comes to mind

**Comment by jaygarcia** [comment] 2017-05-31 19:34
@mrdoob have you considered making a business out of ThreeJS?

**Comment by pailhead** [comment] 2017-06-06 17:26
@jaygarcia How would that work? Considering 800 contributors?

**Comment by jaygarcia** [comment] 2017-06-06 18:30
@pailhead if there is enough demand, there are lots of models where ThreeJS itself could be monetized while staying open source.  Monetizing ThreeJS would ensure that it has funding to continue development with N+ dedicated staff members.

**Comment by pailhead** [comment] 2017-06-08 23:38
i dont understand, it seems like it already has N+ dedicated staff members, and probably a queue of people who'd be willing to collaborate. The user base is only going to grow. Could you give an example model of how this could work?

**Comment by makc** [comment] 2017-06-09 02:15
I totally gave it right there above. Someone (shall we say 3js foundation) collects donations and posts bounties for issues. Case closed

**Comment by mrdoob** [comment] 2017-06-13 18:29
@makc are you offering yourself for start and running the 3js foundation? 😉

**Comment by mrdoob** [comment] 2017-06-13 18:32
@jaygarcia It's already a business, every three.js app is mining bitcoin. You didn't read the small print? 🤡

**Comment by fernandojsg** [comment] 2017-06-13 18:52
I always thought that threejs was created by some huge hardware corporation, and they designed it to be slow on purpose just to keep selling faster CPU/GPU from time to time :D

**Comment by makc** [comment] 2017-06-13 19:29
@mrdoob one would think someone on the team would be more trust-worthy. after all, it does not have to be The Foundation, it could be paypal account or something. we probably are not talking millions of $$ here, so there will not be an option for people to cheat everyone and buy themselves a house.

**Comment by pailhead** [comment] 2017-06-13 22:33
Err, based on recent experience with a PR im convinced that this couldnt work.

**Comment by makc** [comment] 2017-06-13 23:00
@pailhead not sure what you mean, I had to go to page 2 of closed PRs to find rejected ones.

**Comment by OtterFamily** [comment] 2017-06-14 07:55
I'm glad this has spawned an interesting discussion, and I understand the hesitation to take on the task of centralizing the project, and being held accountable for any money coming in - it's a big task, and could easily create a dynamic like in steam early access, where people who have given money to something under development sprinkle their own salty tears onto the development process because their pet issue isn't being addressed. Managing those people (and who would do that?) would be a job.

The project is flourishing under the current model, so i understand the trepidation. I initially posted this just because I love the project, my company asked if there was any avenue to build a dollar amount into the budget for a project to help THREEjs development. I've been answering stackexchange threejs questions on company time every now and then to try and give back to the community where i can.

I guess i'll just have to try and help development when i can find the time, and I'm moving to a different country soon, and i'll probably find some free time to help out where possible. Thanks for the interesting input on this question. cheers!

**Comment by pailhead** [comment] 2017-06-15 00:54
How different is that bounty thing from just putting up an ad like this?

>Looking for a three.js developer to implement FOO into three. 
Result has to be submitted back to three, as a patch. 
Willing to pay SF rates. 

If you really want to part with some money, and get something like this in return, it seems like this approach would distribute the reward management. 

@makc

FOO does PR1, BAR does PR2, BAZ does PR3, but they all solve the same issue and do the same thing. Who gets the glory?

@OtterFamily 
>I've been answering stackexchange threejs questions on **company time** every now and then to try and give back to the community where i can.

This to me seems like the way to go. Except that i would spend those limited resources on issues and pull requests. Even just discussing a PR would be beneficial because it brings different experience and use cases to the table. The quality of three.js related questions on stackexchange seems pretty appalling to me. Even though i try to answer as much questions as i can, it seems like a waste of time, as it seems to benefit few people afterwards.

**Comment by makc** [comment] 2017-06-15 01:00
@pailhead whoever has their PR merged, obviously

**Comment by makc** [comment] 2017-06-15 01:01
@pailhead Kat, Sheila and Rose all love you, who gets married?

**Comment by pailhead** [comment] 2017-06-15 01:03
It would be Kat or Sheila, because Rose is my mother, and she only wants to marry me because Kat and Sheila do.  😆

**Comment by makc** [comment] 2017-06-15 01:03
> How different is that bounty thing from just putting up an ad like this?

no different at al, that _is_ bounty ad

**Comment by pailhead** [comment] 2017-06-15 01:06
That could totally work.

**Comment by makc** [comment] 2017-06-15 01:09
the thing is, we have 100 people who are willing to pay $5 each

**Comment by pailhead** [comment] 2017-06-15 01:09
Some issues are showing through https://www.bountysource.com/, but have no bounty, or a bounty that is zero dollars (if im reading it correctly). Say that i don't care about the money, so i'm willing to accept $0, what happens then, seems like it still has to go through the same framework?

**Comment by pailhead** [comment] 2017-06-15 01:10
I'm willing to take $0 for [this one ](https://api.bountysource.com/badge/issue?issue_id=3576670), what now lol :)

**Comment by makc** [comment] 2017-06-15 01:11
dont see this as some kind of ad for bountysource dot com, it was just an example.

**Comment by pailhead** [comment] 2017-06-15 01:12
What im trying to say is that it seems more like money/time is needed for reviews and dialog, than for the initial implementation. 100 people pitching $5 worth of time wont help at all, but a couple pitching in $250 might be worth something.

**Comment by makc** [comment] 2017-06-15 01:15
which is why I suggested that everybody just give $5 to single entity that can then post $500 bounties in everyone's interest

**Comment by pailhead** [comment] 2017-06-15 01:22
I think we're going in circles. There are 178 open pull requests atm, the supply seems to be much higher than demand. From that, it seems to me that people are spending time developing three, but there is no time to review it and merge it (just look at @mrdoob 's comments). The money, seems to me, should be spent on people reviewing the PRs. What's the use for more open pull requests. No idea how you'd divide it though. If a 100 people say that they've read the code and that they think it's ok, it's probably much easier to merge.

**Comment by makc** [comment] 2017-06-15 01:25
I had like 5 PRs that went through, and like 3 that did not; from that experience PR does not go through if 1 it needs more work but you dont do it, or 2 mrdoob does not like it (probably can be considered a special case of 1).

**Comment by makc** [comment] 2017-06-15 01:28
(ok, I am a bit off in those numbers, actually there were 2 pages of PRs... no way. that much already?)

**Comment by booxie** [comment] 2017-06-15 08:02
I pulled three J's and found out it doesn't work on all platforms and stopped using it

**Comment by makc** [comment] 2017-06-15 09:55
Yes, it totally does not work on my fridge.

**Comment by pailhead** [comment] 2017-06-15 17:02
Im sure theres a fridge out there where it works.

**Comment by makc** [comment] 2017-06-15 17:10
Samsung Family Hub Refrigerator probably can run it.

**Comment by cecilemuller** [comment] 2017-06-15 17:18
It wouldn't help for distribution, but [Patreon](https://www.patreon.com) would be useful for recurring donations to create a somewhat stable revenue stream at least.

**Comment by pailhead** [comment] 2017-06-15 20:00
@makc here's a personal example:

I've got [this](https://www.npmjs.com/package/three-instanced-mesh) npm package, it seems that people are [downloading it](https://npm-stat.com/charts.html?package=three-instanced-mesh&from=2017-02-01&to=2017-06-06). It got scraped and ended up on the [bounty site](https://www.bountysource.com/issues/3576670-three-instances?utm_source=3576670&utm_medium=shield&utm_campaign=ISSUE_BADGE).

>it needs more work but you dont do it, 

Not valid in this case, needed work (and probably needs more) but i'm constantly doing it. **Without feedback i don't know which route to take when making decisions**. The current state of this particular pr (https://github.com/mrdoob/three.js/pull/10750) is that it works, it solves the problem of using various default materials with instances (none of the other attempts seem to have tackled that). BUT, it does some funky stuff pattern wise, which would require feedback to address.

> 2 mrdoob does not like it 

Not valid in this case. I think he actually commented somewhere explicitely that he "likes". I've also seen it mentioned and shown at a meetup during GDC as an upcoming feature in the new version of three.js. I was under the impression that he liked it. 

It's been open since February. Seems like all your items have been checked, but the PR is still in limbo. 
In this particular case, with this particular PR, pretending it's not pure %$#%$, what needs to be addressed?

**Comment by makc** [comment] 2017-06-15 20:41
or maybe @mrdoob is working on his very own implementation that was mentioned during gdc meetup, that just happened to have the same name? in any case it does not hurt to ask "what's up with my pr" :)

**Comment by pailhead** [comment] 2017-06-15 20:48
Ermm, it was mine implementation that was shown during the gdc meetup.

**Comment by makc** [comment] 2017-06-15 22:00
wait, are you saying we should just pay mr doob to accept PRs )

**Comment by pailhead** [comment] 2017-06-15 22:05
no, i'm saying instead of having this discussion, we should both be looking at PRs and issues.

**Comment by mrdoob** [comment] 2017-06-15 22:08
For that particular PR, I remember finding the way the transforms were being sent to the shader a bit over complicated. I asked if there was a better way and I was told there wasn't so I decided to study the subject to double-check. I reported my findings and left the rest of the PR for another time (as WebVR is a bigger problem to solve right now).

If PRs are simple and beautiful they get merged straight away. If PRs remove more code than it adds, they get merged straight away. If PRs require review, feedback and/or I need to study the subject then they get delayed.

@pailhead I understand I'm the bottle neck, but having to justify over and over why PRs don't get merged straight away doesn't really help the cause. I could have used the time it took me to write this post to review (and maybe merge) a PR.

**Comment by pailhead** [comment] 2017-06-15 22:23
I know, i'm not trying to bash you here and i understand how overwhelming this can get. I know i may be going over the top with activity, but i think there is a sweet spot between this and no activity. 

Would it help you if more people reviewed?

**Comment by fernandojsg** [comment] 2017-06-15 22:25
We could do something like in the old days of the BBS: if you wanted to download 1MB of games,music,data, you needed to upload 2MB.
So if you want to push a PR you should review 2 😄

**Comment by pailhead** [comment] 2017-06-15 22:26
Dunno if it j/k but i like the idea 🍡

**Comment by fernandojsg** [comment] 2017-06-15 22:31
At the beginning I was writing it like a joke but now that I think about it, it not that crazy yep :) I just hope it won't end with plenty of random LGTM everywhere hehe
Another way to move old PRs could be to have a "PR of the week/month", chosen by the community and encourage people to comment on it, test it, to try to get it done more efficiently.

**Comment by Bsheridan12** [comment] 2017-09-21 18:38
If at some point in the future you do decide to accept donations [Open Collective](https://opencollective.com/) might be a good option to facilitate that.
For the amount of work and support you offer for the project I'd be happy to contribute something - I'll keep an eye out for a donate button on the site!

**Comment by pailhead** [comment] 2017-09-21 23:29
what are the 230k for webpack going to?

**Closed** 2018-03-01 20:07 UTC
Labels: Suggestion
