### ISSUE TITLE
Firefox mobile can't play videoTexture examples

### ISSUE THREAD

**Issue by optimus007** [mrdoob/three.js#22406] opened 2021-08-24 12:41 UTC
**Describe the bug**

The [video/kinect](https://threejs.org/examples/?q=vide#webgl_video_kinect) and [video/panorama](https://threejs.org/examples/?q=vide#webgl_video_panorama_equirectangular) examples are not working on firefox on android 

The [sintel video](https://threejs.org/examples/?q=vide#webgl_materials_video) works but only with the ogv video  with mp4 file it still shows black

Using usb debugging i got these messages
![three js video](https://user-images.githubusercontent.com/6885294/130616810-04253e20-8cca-48f3-86c7-43f3561fd7ce.png)

**Screenshots**

![Screenshot_20210824-173420_Firefox](https://user-images.githubusercontent.com/6885294/130618000-d2a9634a-4da2-4219-bceb-c753d3b67d2a.jpg)
![Screenshot_20210824-181233_Firefox](https://user-images.githubusercontent.com/6885294/130618526-43721660-1dc2-49dc-830f-a53421c6f91f.jpg)

**Platform:**

 - Device: [Mobile : samsung galaxy m30]
 - OS: [Android]
 - Browser: [Firefox]
 - Three.js version: [ r131]

**Comment by Mugen87** [comment] 2021-08-24 13:21
I can confirm on a Pixel 4a with Android 11 and the same Firefox version.

It seems it is possible to play WebM and MP4 files embedded in websites. But using them as video textures does not work.

https://www.webmfiles.org/demo-files/

**Comment by Mugen87** [comment] 2021-08-24 13:33
Um, when I remember correctly the mentioned examples used to work on mobile FF 🤔 .

TBH, it's a while since I have used the browser on my phone but I've verified former web audio related changes with this browser.

**Comment by mrdoob** [comment] 2021-08-24 14:37
@optimus007 Have you reported this to Mozilla?

**Comment by optimus007** [comment] 2021-08-24 14:57
> 
> 
> @optimus007 Have you reported this to Mozilla?

nope, just discovered this recently

i had sent a tweet to firefox support, doubt that's helpful

**Comment by Mugen87** [comment] 2021-08-24 15:14
> let me know if i should report it on https://bugzilla.mozilla.org/home

That would be great. I don't think we are able to fix this on engine level. Apart from just using OGV.

**Comment by mrdoob** [comment] 2021-08-24 15:57
Yep! Better to report to Mozilla directly.
I'll close this in the meantime.

**Closed by mrdoob** 2021-08-24 15:57 UTC
Labels: Browser Issue

**Comment by takahirox** [comment] 2021-08-24 16:17
It's a known issue. The ticket has already been opened https://bugzilla.mozilla.org/show_bug.cgi?id=1709726
