### ISSUE TITLE
Vector3.applyQuaternion--- The floating-point precision issue 

### ISSUE THREAD

**Issue by Philweix** [mrdoob/three.js#27334] opened 2023-12-07 03:57 UTC
### Description

I have observed that in the r158 version of Three.js, the Vector3.applyQuaternion() method has been optimized. Both of these functions are theoretically correct. Although the first method might be superior in terms of performance as it utilizes some mathematical equivalences, allowing for simpler computations to achieve the same rotation effect, there could be slight differences in certain cases due to floating-point precision issues. Occasionally, a discrepancy of 0 and -3.552713678800501e-15 may occur, especially when calculating tx, ty, tz by performing cross-products on two vectors. This operation can introduce some floating-point errors.

For instance, when q is (w: 0.7071067811865475, x: -0.7071067811865475, y: 0, z: 0), and Vector3 is (x: 1.3691967456605068e-15, y: 0, z: -11.180339887498949), the optimized calculation results in (x: 1.3691967456605068e-15, y: -11.180339887498947, z: -1.7763568394002505e-15), whereas the expected result is (x: 1.3691967456605068e-15, y: -11.180339887498947, z: 0). The difference in the z component, specifically -1.7763568394002505e-15, can lead to errors in specific scenarios, such as when using OrbitControls to control the camera with up set to (0, 0, 1), the camera positioned at (0, 0, -1), and looking at (0, 0, 0). In such cases, a rotation of the view angle might occur when zooming the camera.

### Reproduction steps

1、in THREE r157: let vector157 =  new THREE.Vector3(1.3691967456605068e-15, 0, -11.180339887498949)
2、in THREE r158: let vector158 =  new THREE.Vector3(1.3691967456605068e-15, 0, -11.180339887498949)
3、let q = new THREE.Quaternion(-0.7071067811865475,  0, 0， 0.7071067811865475);
4、 vector157.applyQuaternion(q) !== vector158.applyQuaternion(q)

### Code

```js
// code goes here
//1、in THREE r157:
 let vector157 =  new THREE.Vector3(1.3691967456605068e-15, 0, -11.180339887498949)
// 2、in THREE r158: 
let vector158 =  new THREE.Vector3(1.3691967456605068e-15, 0, -11.180339887498949)
let q = new THREE.Quaternion(-0.7071067811865475,  0, 0， 0.7071067811865475);
vector157.applyQuaternion(q) !== vector158.applyQuaternion(q)
```

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/g3atw6k5/)
* [jsfiddle-dev](https://jsfiddle.net/hjqw94c5/)

https://github.com/mrdoob/three.js/assets/82513007/b94e423e-d977-4d26-a658-9cd95efe4d3a

### Version

158

**Comment by Philweix** [comment] 2023-12-07 05:16
When I choose the approach(vector3.applyQuaternion()) from version 157, there is no rotation bug when scaling the view at the same position.

**Comment by WestLangley** [comment] 2023-12-07 05:51
>when using OrbitControls to control the camera with up set to (0, 0, 1), the camera positioned at (0, 0, -1), and looking at (0, 0, 0). In such cases, a rotation of the view angle might occur when zooming the camera.

That is not valid. See #27104, and in particular https://github.com/mrdoob/three.js/issues/27104#issuecomment-1791237396.

**Comment by Philweix** [comment] 2023-12-07 06:55
> > when using OrbitControls to control the camera with up set to (0, 0, 1), the camera positioned at (0, 0, -1), and looking at (0, 0, 0). In such cases, a rotation of the view angle might occur when zooming the camera.
> 
> That is not valid. See #27104, and in particular [#27104 (comment)](https://github.com/mrdoob/three.js/issues/27104#issuecomment-1791237396).

But I didn't change anything, I just changed the method：vector3.applyQuaternion（） and everything was fine.

**Comment by Philweix** [comment] 2023-12-07 07:14
> > when using OrbitControls to control the camera with up set to (0, 0, 1), the camera positioned at (0, 0, -1), and looking at (0, 0, 0). In such cases, a rotation of the view angle might occur when zooming the camera.
> 
> That is not valid. See #27104, and in particular [#27104 (comment)](https://github.com/mrdoob/three.js/issues/27104#issuecomment-1791237396).

https://github.com/mrdoob/three.js/assets/82513007/8edc09cb-fc94-4e87-98c6-aebee6907ff8
Thank you very much ， But all I did was change the method（vector3.applyQuaternion()）, and everything was fine.

**Comment by WestLangley** [comment] 2023-12-07 20:15
>a rotation of the view angle might occur when zooming the camera

You have not provided a live example, so it is not clear (to me) what you are doing.

You can provide a live example by editing the above fiddle.

**Comment by Philweix** [comment] 2023-12-08 02:10
> > a rotation of the view angle might occur when zooming the camera
> 
> You have not provided a live example, so it is not clear (to me) what you are doing.
> 
> You can provide a live example by editing the above fiddle.

Thank you very much for your continuous attention, this is my example, for the sake of z - up I just changed the editor. js camera, Using OrbitControls instead of EditorControls in viewport js, and modify the examples/jsm/ViewHelper. js. 
In build/three.module.js I wrote a comparison of the r157 and r158 versions of the vector3.applyQuaternion () method. You can switch between the different versions as I did in the video and see what the editor's camera looks like.
https://github.com/Philweix/three.js-sourceCode-parsing.git

**Comment by WestLangley** [comment] 2023-12-08 03:24
In your example, the r158 version produces an answer that differs from the r157 version in the 15th decimal place. That is due to roundoff and it is unavoidable.

Is there a visual problem, or a problem with the rendering? If so, please explain.

https://raw.githack.com/Philweix/three.js-sourceCode-parsing/dev/editor/index.html

**Comment by Philweix** [comment] 2023-12-09 02:04
> In your example, the r158 version produces an answer that differs from the r157 version in the 15th decimal place. That is due to roundoff and it is unavoidable.
> 
> Is there a visual problem, or a problem with the rendering? If so, please explain.
> 
> https://raw.githack.com/Philweix/three.js-sourceCode-parsing/dev/editor/index.html
spherical.theta （2.4849） -  spherical.theta （ 1.5707 ） = 0.91  Radians are converted to angles = 52°  。Error amplification。

**Comment by WestLangley** [comment] 2023-12-09 03:21
`OrbitControls` calls `camera.lookAt()`, and `camera.lookAt()` is very sensitive to the camera position when the camera look-direction is close to `camera.up`. (For example, in your case, when the camera remains very close to the coordinate axis, and moves to a different quadrant.)

To avoid this sensitivity, `OrbitControls` calls `spherical.makeSafe()`. This keeps the camera away from the poles, where this sensitivity occurs -- or at least, that was the objective.

//

So far, I have been unable to replicate your "rotation when zooming" issue.

Please provide a link to a live example demonstrating the issue. (I am not going to fork, edit, or rebuild your project.)

I'd like to see an explanation as to why the recent change to `Vector3.applyQuaternion()` is making this sensitivity worse.

Does the issue only occur when `camera.up` is the z-axis?

**Comment by Philweix** [comment] 2023-12-09 05:28
> `OrbitControls` calls `camera.lookAt()`, and `camera.lookAt()` is very sensitive to the camera position when the camera look-direction is close to `camera.up`. (For example, in your case, when the camera remains very close to the coordinate axis, and moves to a different quadrant.)
> 
> To avoid this sensitivity, `OrbitControls` calls `spherical.makeSafe()`. This keeps the camera away from the poles, where this sensitivity occurs -- or at least, that was the objective.
> 
> //
> 
> So far, I have been unable to replicate your "rotation when zooming" issue.
> 
> Please provide a link to a live example demonstrating the issue. (I am not going to fork, edit, or rebuild your project.)
> 
> I'd like to see an explanation as to why the recent change to `Vector3.applyQuaternion()` is making this sensitivity worse.
> 
> Does the issue only occur when `camera.up` is the z-axis?

YES ,the issue only occur when camera. up is the z-axis, camera.position(0,0,-num), So here's my example, you can click on -z of viewportHelper, and then scale the scene, and then the scene will rotate about 50 degrees, and you can open the console, and I made console.log where the document appears
https://raw.githack.com/Philweix/three.js-sourceCode-parsing/dev/editor/index.html

**Comment by WestLangley** [comment] 2023-12-09 21:06
>you can click on -z of viewportHelper, and then scale [zoom] the scene, and then the scene will rotate about 50 degrees

That is true, but as I said several times, looking in the direction of `camera.up` is not valid using `OrbitControls`. The gizmo probably should be modified to avoid doing that.

See https://github.com/mrdoob/three.js/issues/27104#issuecomment-1793889556 and the source code for `Matrix4.lookAt()`. It is `lookAt()` that is the cause of the arbitrary 50-degree rotation in your example.

It remains to understand if the recent change to `Vector3.applyQuaternion()` is making this sensitivity worse.

That is possible, but you should not be doing what you're doing in the first place.

**Comment by Mugen87** [comment] 2023-12-12 10:13
When the new implementation in `Vector3.applyQuaternion()` causes troubles with a _valid use case_, we can closer investigate the issue. But since this is not true here, closing the issue.

**Closed by Mugen87** 2023-12-12 10:13 UTC
