### ISSUE TITLE
Inline grayscaling in materials

### ISSUE THREAD

**Issue by Jaliborc** [mrdoob/three.js#11308] opened 2017-05-09 17:00 UTC
##### Description of the problem 
It would be great to have the option to render in grayscale. It could be implemented as a new tonemapping type and set in renderer.tonemapping.

**Comment by looeee** [comment] 2017-05-09 17:22
That is implemented with postprocessing. See [this example](https://threejs.org/examples/#webgl_postprocessing_nodes), and set saturation to 0.

**Comment by Mugen87** [comment] 2017-05-09 18:11
@looeee is right. Such features should be implemented with post processing.

**Comment by Jaliborc** [comment] 2017-05-10 11:56
Of course it can be implemented in postprocessing. But would be much more efficient to have the option to do it inline. Tone-mapping could also be done in postprocessing, yet you still made it available inline.

**Comment by WestLangley** [comment] 2017-05-10 14:42
For reference, adding inline color-correction -- and possibly LUTs -- was mentioned in https://github.com/mrdoob/three.js/pull/11076#issuecomment-293570510. Perhaps we could call it _color-remapping_.

**Comment by Mugen87** [comment] 2017-05-10 15:30
Sry, i've missed this discussion.

**Comment by Jaliborc** [comment] 2017-05-10 15:58
_color-remapping_ sounds like a good term for it.

**Comment by pailhead** [comment] 2017-05-11 23:58
Another thing that can easily be done with:

https://github.com/mrdoob/three.js/pull/10791

for example you could just add
```glsl
gl_FragColor.xyz = dot( gl_FragColor.xyz , 1.);
```

to `fog_fragment.glsl`

**Comment by Mugen87** [comment] 2020-07-24 11:42
Duplicate of #19457.

**Closed by Mugen87** 2020-07-24 11:42 UTC
Labels: Enhancement
