### ISSUE TITLE
r72: messed up OBJMTL loader 

### ISSUE THREAD

**Issue by wizztjh** [mrdoob/three.js#7252] opened 2015-09-28 03:59 UTC
loader.load( this.properties.geometrySrc , this.properties.materialSrc)

The only warning i got is 

```
THREE.MeshPhongMaterial: 'diffuse' is not a property of this material.
```

![screen shot 2015-09-28 at 11 56 39 am](https://cloud.githubusercontent.com/assets/462417/10127654/2672ba00-65d8-11e5-8638-f549f87a6207.png)

This is the mtl file that we load

```
newmtl material_0
Ka 1.000000 0.000000 0.000000
Kd 1.000000 1.000000 1.000000
Ks 0.000000 0.000000 0.000000
Tr 1.000000
illum 0
Ns 0.000000
map_Kd model_texture.jpg
```

**Comment by mrdoob** [comment] 2015-10-01 01:51
How is it supposed to look?

**Comment by wizztjh** [comment] 2015-10-01 02:51
It should look like this.

This is the demo with r71

http://metaroommarkup.github.io/MetaRoomMarkup/demo/metaroom-markup-standard-spec.html

<img width="934" alt="screen shot 2015-10-01 at 10 50 13 am" src="https://cloud.githubusercontent.com/assets/462417/10211851/42c738bc-682a-11e5-8fc7-7c9f4be307da.png">

**Comment by wizztjh** [comment] 2015-10-01 02:57
This is the mtl file

http://metaroommarkup.github.io/MetaRoomMarkup/demo/model/pokka/model_mesh.obj.mtl

This is the obj file
http://metaroommarkup.github.io/MetaRoomMarkup/demo/model/pokka/model_mesh.obj


It seems to be the face3 normal inverted. What do you think?

**Comment by WestLangley** [comment] 2015-10-01 08:53
Your model files work fine for me on r.72.

![screen shot 2015-10-01 at 4 47 20 am](https://cloud.githubusercontent.com/assets/1000017/10216565/10866652-67f8-11e5-86e1-6e105018f1d5.png)

**Comment by wizztjh** [comment] 2015-10-01 14:28
must be some of my settings then. Will look it up and update you guys.

**Comment by nickjs** [comment] 2015-10-05 02:00
@WestLangley I'm also seeing the same behavior as @wizztjh that also worked fine in r71. Here's my code that I'm using to load it:

```javascript
  load(objPath, mtlPath, texPath) {
    var loader = new THREE.OBJMTLLoader
    loader.setCrossOrigin('anonymous')
    loader.load(objPath, mtlPath, this.onLoadCompleted.bind(this), this.onLoadProgress, this.onLoadFailed)
  }

  initializeObject() {
    var mesh = this.obj.children[0]
    mesh.castShadow = true
    mesh.geometry.mergeVertices()
    mesh.geometry.center()

    var height = mesh.geometry.boundingBox.max.y
    var scale = MODEL_SCALE / height

    this.obj.scale.set(scale, scale, scale)
    this.obj.position.add(MODEL_OFFSET)

    this.add(this.obj)
  }

  onLoadCompleted(obj) {
    this.obj = obj
    this.initializeObject()
  }
```

Is there something different you're doing in your tests?

**Comment by wizztjh** [comment] 2015-10-05 02:24
@nickjs I am using castShadow too. Can you disable that and see if that effects the outcome?

**Comment by nickjs** [comment] 2015-10-05 02:27
Nope, I removed all the extra code and just stuck it in my scene as is, same issue :(

**Comment by WestLangley** [comment] 2015-10-05 15:31
@nickjs I don't know what to tell you. If you provide a link to a live example (of the bottle only) demonstrating the issue it may be helpful. Remove `mergeVertices`, shadows, and anything else that seems unrelated to the issue.

Please see "How to report a bug" in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md).

**Comment by mrdoob** [comment] 2015-10-05 16:09
Yeah... Guys, we need working links that we can inspect, both for r71 and r72. We can't do much with screenshots.

**Comment by nickjs** [comment] 2015-10-06 21:25
Sorry about that! I was just wondering if @WestLangley was doing anything different. Here's two pens:

r71 (renders ok): http://codepen.io/nickjs/pen/vNmjdJ
r72 (renders with artifacts): http://codepen.io/nickjs/pen/rOmvOb

The culprit seems to be having two directional lights in the scene, although this may be a placebo. I was also able to replicate by setting the mesh's material shininess to `0`.

**Comment by WestLangley** [comment] 2015-10-07 00:25
@nickjs I would be surprised if the directional lights have anything to do with it. However, shininess of zero is an invalid value. See #6057 and #5222. Also see the `MeshPhongMaterial` docs.

By the way, I am not able to replicate the issue in your examples, either. I am on OSX.

@mrdoob I also see that it appears that `MTLLoader` is assigning a string value to `shininess`. For example, `"0.00000"`. It should be a float.

It is still not clear to me why `r71` and `r72` would produce different results.

**Comment by nickjs** [comment] 2015-10-07 02:09
Very strange. Here's what I see in both Safari and Chrome on the r72 version:

![screen shot 2015-10-06 at 10 06 39 pm](https://cloud.githubusercontent.com/assets/22133/10327549/9177b9aa-6c76-11e5-814c-b5ce69164481.png)

I'm on El Capitan, maybe it's GPU driver related? What version are you on?

I agree that `0` or `"0.0000"` are invalid values, but it also didn't cause this issue in r71, at least for me. In that other issue it seems like people were experiencing this behavior back in r68. So I wonder if it's a problem with the material or the MTLLoader?

**Comment by wizztjh** [comment] 2015-10-07 02:32
i am using yosmite. i am seeing this also

On Wed, Oct 7, 2015 at 10:10 AM, Nicholas J. Small <notifications@github.com
> wrote:

> Very strange. Here's what I see in both Safari and Chrome on the r72
> version:
>
> [image: screen shot 2015-10-06 at 10 06 39 pm]
> <https://cloud.githubusercontent.com/assets/22133/10327549/9177b9aa-6c76-11e5-814c-b5ce69164481.png>
>
> I'm on El Capitan, maybe it's GPU driver related? What version are you on?
>
> I agree that 0 or "0.0000" are invalid values, but it also didn't cause
> this issue in r71, at least for me. In that other issue it seems like
> people were experiencing this behavior back in r68. So I wonder if it's a
> problem with the material or the MTLLoader?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mrdoob/three.js/issues/7252#issuecomment-146057983>.
>



-- 

Tee Jia Hen
CTO of VRcollab, VRcollab.com <http://vrcollab.com/>
+6598144461
sg.linkedin.com/in/wizztjh

**Comment by WestLangley** [comment] 2015-10-07 02:34
Does the problem go away if `shininess = 1`?

**Comment by nickjs** [comment] 2015-10-07 02:40
@WestLangley Yup, indeed it does, as does setting it to `0.001`. However just setting it to `0` (not a string) the issue persists, so it's not necessarily an artifact of just being a string.

So I guess we can close this as a duplicate of the existing issues. Still very strange that it just started happening in r72. It doesn't look like anything has changed in the MTLLoader. Any other thoughts? In the meantime I can just set shininess to 0.001. Thanks for your help!

**Comment by mrdoob** [comment] 2015-10-07 02:42
I'm seeing that too. It's probably depends on the GPU.

@WestLangley We probably lost a `max()` somewhere in the lighting code refactoring.

**Comment by mrdoob** [comment] 2015-10-07 02:45
@WestLangley Confirmed:

r71: https://github.com/mrdoob/three.js/blob/r71/src/renderers/shaders/ShaderChunk/lights_phong_fragment.glsl#L68
r72: https://github.com/mrdoob/three.js/blob/dev/src/renderers/shaders/ShaderChunk/common.glsl#L79

**Comment by mrdoob** [comment] 2015-10-07 02:48
Should we add a `max()` in this line?
https://github.com/mrdoob/three.js/blob/dev/src/renderers/shaders/ShaderChunk/common.glsl#L96 

```glsl
float D = max( D_BlinnPhong( shininess, dotNH ), 0.0 );
```

Or should we add it inside `D_BlinnPhong`.

/cc @bhouston

**Comment by WestLangley** [comment] 2015-10-07 03:08
> We probably lost a max() somewhere in the lighting code refactoring.

Nice conjecture!

Yes, we did. But the `max` that was removed was not required, and adding a `max` is not the proper fix for handling the `pow( 0.0, 0.0 )` issue.

We have specified in the docs to keep `shininess` greater than 0. That should be sufficient.

As a rule, we do not do parameter checking in three.js. It is up to @mrdoob if we want to start doing so.

We need to also fix `MTLLoader` to set `shininess` as a float and not a string.

**Comment by bhouston** [comment] 2015-10-07 07:13
I believe most people that use the BlinnPhong model do a max on the shininess before it is passed into a shader with a small value like 1e-4.  So I would recommend doing this max in JavaScript so you do it once and just before you set the uniform values on the shader.

```
shininess = Math.max( shininess, 1e-4 );
```

This is both fairly correct and efficient.

**Comment by bhouston** [comment] 2015-10-07 07:29
On a related topic, I believe that *.mtl files specify a Phong illumination exponent, Ns, according to Wikipedia:

https://en.wikipedia.org/wiki/Wavefront_.obj_file#Material_template_library

Three.JS though uses a BlinnPhong illumination model when rendering.  The BlinnPhong illumination model's exponent should be 4x the Phong illumination model exponent for the same effect according to Wikipedia:

https://en.wikipedia.org/wiki/Blinn%E2%80%93Phong_shading_model#Description

**Comment by WestLangley** [comment] 2015-10-07 14:23
>  So I would recommend doing this max in JavaScript so you do it once and just before you set the uniform values on the shader.

I agree with @bhouston.

> I believe that *.mtl files specify a Phong illumination exponent, Ns

[This link](http://www.fileformat.info/format/material/) indicates that the `illum` paramater in the MTL file specifies one of 10 models.

**Comment by bhouston** [comment] 2015-10-07 14:27
@WestLangley:
> This link indicates that the illum paramater in the MTL file specifies one of 10 models.

You are right that the "illum" parameter is hugely important, but they do not switch from the Phong illumination model as the method for doing the specular highlights if there are specular highlights.  Rather the illum parameter turns on and off ambient, highlight, reflections, transparency, fresnel, etc.  But the highlight exponent is always, at least according to what I have read, based on the archaic Phong illumination model.

**Comment by WestLangley** [comment] 2015-10-07 15:11
> But the highlight exponent is always, at least according to what I have read, based on the archaic Phong illumination model.

@bhouston The link I referenced claims it is "Blinns's interpretation", however. The formulas in the link appear to have typos, but do use the half-vector. I am not sure what the truth is.

**Comment by bhouston** [comment] 2015-10-07 15:19
@WestLangley I wouldn't be surprised if Ns interpretation varied based on the tool that exported the OBJ/MTL.  Corona believes it is Phong: https://corona-renderer.com/wiki/standalone/mtl  But this page, which actually seems very authoritative: http://paulbourke.net/dataformats/mtl/  http://paulbourke.net/dataformats/obj/  (Paul Bourke knows his stuff) says that it is Blinn's interpretation: https://design.osu.edu/carlson/history/PDFs/blinn-light.pdf

So Wikipedia is wrong, as it often is.  Sorry about the noise.

**Comment by WestLangley** [comment] 2015-10-07 15:46
@mrdoob So the recommendation is:

1. fix `MTLLoader` to set `shininess` as a float and not as a string.
2. In `WebGLRenderer` set:
```javascript
uniforms.shininess.value = Math.max( material.shininess, 1e-4 ); // to prevent pow( 0.0, 0.0 )
```

**Comment by mrdoob** [comment] 2015-10-07 16:48
Fixed. Many thanks guys! 😊

**Closed by mrdoob** 2015-10-07 16:48 UTC

**Comment by nickjs** [comment] 2015-10-07 18:27
This is awesome, thanks so much guys!
