### ISSUE TITLE
Add LogLuv Encoding in PMREM Generator

### ISSUE THREAD

**Issue by repalash** [mrdoob/three.js#22757] opened 2021-10-29 15:38 UTC
The PMREM Generator manages encoding by itself and there is no support for input textures with LogLuv.

**Comment by WestLangley** [comment] 2021-10-29 18:52
>it would break a lot of projects.

Really? Yours is the first use of `THREE.LogLuvEncoding` I am aware of in 10 years.

**Comment by repalash** [comment] 2021-10-29 19:12
It would break some of our projects definitely. 

Is there some issue with LogLuv encoding that I am not aware of? Apart from extra instructions in the fragment shader?

**Comment by Mugen87** [comment] 2021-10-30 10:55
I think removing `LogLuv` just to simplify the shaders seems not comprehensible for users who rely on this format. 

And I agree that we should provide more arguments against `LogLuv`. This will make it easier to convince devs to switch to other (potentially better) formats.

**Comment by WestLangley** [comment] 2021-10-30 10:56
Let's discuss whether this feature is appropriate -- or not.

What other engines support textures in this format?

/ping @bhouston

**Comment by WestLangley** [comment] 2021-10-30 11:00
>Removing LogLuv just to simplify shaders is not comprehensible for users who rely on this format.

I do not think there are any three.js users who rely on this format. If there are, then I agree, removing support would not be nice.

**Comment by Mugen87** [comment] 2021-10-30 11:05
Well, to be fair @repalash is one user.

**Comment by WestLangley** [comment] 2021-10-30 11:16
>Well, to be fair @repalash is one user.

No, he is _thinking_ of using it, and he said he has alternatives.

**Comment by Mugen87** [comment] 2021-10-30 11:17
@repalash Would you please clarify this? I think it's best if you speak for yourself.

**Comment by mrdoob** [comment] 2021-10-30 11:46
@repalash said they have a database of f files using `LogLuv`. Would it be possible to convert these files to a different encoding? Or is `Logluv` superior somehow?

**Comment by WestLangley** [comment] 2021-10-30 11:51
What is the file extension? What three.js loader is used to load the LogLuv files?

**Comment by Mugen87** [comment] 2021-10-30 12:28
It seems LogLuv textures are usually TIFF files. Some example texture can be found here:

http://www.anyhere.com/gward/pixformat/tiffluvimg.html

TIFF files can only be loaded with `DataTextureLoader`. In order to have a "ready-to-use" texture, an app needs to perform the decode with custom code e.g. by using `UTIF.js`.

**Comment by Mugen87** [comment] 2021-10-30 12:28
It seems LogLuv textures are usually TIFF files. Some example texture can be found here:

http://www.anyhere.com/gward/pixformat/tiffluvimg.html

TIFF files can only be loaded with `DataTextureLoader`. In order to have a "ready-to-use" texture, an app needs to perform the decode with custom code e.g. by using `UTIF.js`.

**Comment by repalash** [comment] 2021-10-30 13:06
We already use it in our projects, and thinking of using it in the projects I am working on right now.

We have a 2-year-old tool to generate prefiltered environment map files to be used on the web with threejs. It's a lot slower than PMREM but the blurring quality is better and we can sample envmap by just a `textureCubeLod` call instead of the whole `textureCubeUV`. It writes to a custom format and we use a custom js loader to load the files.

This tool is being used by some of our clients for quite some time now, and the default encoding is set to be LogLuv, so we have a lot of files being used with LogLuv, and we have been getting good results without any issues.

I have been told by the previous dev that LogLuv files are smaller in size and (somewhat) better in linear interpolation than RGBM/RGBE.
I will write a few tests in the coming days to test that and figure out what we should use in the future.

Even if you guys decide to remove the encoding I can anyway patch the shaders to support it in our projects, but it will definitely be a lot of work. 
I cannot say the same for others who might be using it.

Again, instead of just removing the support, couldn't we make it dynamic like `texelToLinear` type of functions? It would remove not just LogLuv from the shaders but any that are not used. (And it might be possible to support custom encoding functions easily).
Or are there any other reasons for not using LogLuv specifically?

**Comment by WestLangley** [comment] 2021-10-30 13:09
@Mugen87. Would adding `examples/webgl_loader_texture_tif.html` make sense to you? I don't think so, personally.

`DataTextureLoader` is an abstract class, so a custom `tif` loader would be required, no? In that case, decoding to linear at load time is far superior to retaining logluv.

**Comment by WestLangley** [comment] 2021-10-30 13:18
@repalash Thank you for your reply. Are you using the latest revision of three.js?

**Comment by repalash** [comment] 2021-10-30 13:31
> Are you using the latest revision of three.js?
Yes.

On another note, we started with around r90, and have been upgrading regularly. But since the last few versions, it seems that migrating is a lot more work, especially with shaders and merging any custom code. Are you guys working towards something or I am just thinking too much?

**Comment by Mugen87** [comment] 2021-10-30 13:53
> DataTextureLoader is an abstract class, so a custom tif loader would be required, no?

@WestLangley Yes, that's what I meant and why you need `UTIF.js` or a similar library.

**Comment by WestLangley** [comment] 2021-10-30 13:55
@repalash  You are using custom loaders, custom code, custom shaders, and you are asking us to modify the library to accommodate you. Unfortunately, I do not have a clear understanding of your workflow. Nor do I understand why you prefer to decode LogLuv per pixel per frame rather than decoding to linear at load time.

three.js does not fully support LogLuv tif files, and I question the advisability of heading further down that path.

**Comment by Mugen87** [comment] 2021-10-30 13:56
> Would adding examples/webgl_loader_texture_tif.html make sense to you?

No. This would only make sense if we provide `LOGLUVLoader`.

**Comment by WestLangley** [comment] 2021-10-30 14:01
@Mugen87 Agreed. And do you think we should provide either?

**Comment by Mugen87** [comment] 2021-10-30 14:02
Well, if we want to proper support LogLuv then yes. It depends on how @mrdoob decides.

**Comment by mrdoob** [comment] 2021-10-30 14:07
I like the idea of doing a `LOGLUVLoader` that converts to linear at load time so we can remove the logluv code path from shaders 👍

**Comment by WestLangley** [comment] 2021-10-30 14:15
Are LogLuv or tiff environment maps used in the industry? Or supported by any engine?

**Comment by repalash** [comment] 2021-10-30 14:57
> You are using custom loaders, custom code, custom shaders, and you are asking us to modify the library to accommodate you.

@WestLangley I just raised a feature request of adding the encoding to PMREM as it's already supported throughout three.js. What you guys want to do is totally up to you, and as I mentioned earlier, I can patch the shaders even if you remove the support. 

Plus, I never asked to specially modify the library to accommodate me, was just taking part in the discussion of whether LogLuv can be useful, and asking why you think it isn't.



> Nor do I understand why you prefer to decode LogLuv per pixel per frame rather than decoding to linear at load time.

We would need half-float for linear which uses double memory and is not supported everywhere yet.

**Comment by Mugen87** [comment] 2021-10-30 15:45
@repalash Your request was totally fine, don't worry. It's indeed confusing how LogLuv is supported right now. It's good to reconsider the implementation in this issue.

**Comment by Mugen87** [comment] 2021-10-31 19:23
I've like to share my today's findings about implementing `LogLuvLoader`:

- LogLuv HDR images are stored in the TIFF file format.
- The LogLuv encoding is embedded in a special compression types which are SGILog (34676) or SGILog24 (34677)
- Unfortunately, `UTIF.js` does not support this compression type (it reports "Unknown compression") so we can't use it for `LogLuvLoader`.
- I've tried `tiff.js` next which is an Emscripten port of C library `LibTIFF`.
- Unfortunately, it only uses a subset of the `LibTIFF` API. The main method is `TIFFReadRGBAImage` which returns an unsigned byte RGBA buffer. According to the `man` page the method scales down the HDR texels to produce a 8-bit image (in linear color space). So the result can't be used as an HDR texture anymore.
- The C method that we have to use in the loader to read actual float values is `TIFFReadScanline`. However, this method is no part of `tiff.js`. There is a feature request to add the method (https://github.com/seikichi/tiff.js/issues/20) but it seems the project is not maintained anymore.
- One way to solve the issue is to create a custom Emscripten build for the loader which includes the required interface of `LibTIFF` so we can read actual float data. Unfortunately, I'm not very familiar with Emscripten so I'm not sure if I can make progress in the next time.
- Alternatively, one could consider to write everything from scratch. However, it seems more robust to reuse `LibTIFF` in the loader. It's more a matter of using Emscripten correctly^^.

**Comment by bhouston** [comment] 2021-11-01 16:54
TIFF is a horrible run-time format because it is really a container of a multitude, or even infinite number of sub formats.  LogLuv is a very rarely used encoding.

I think you should just reencode it to FP16 upon load or change to format to RGBE or RGBM16 or something.  I believe doing logs at run-time is not efficient on the GPU anyhow.

Thus I can understand why you are asking for it, but I honestly think just reencoding is easer.  That said, it should have been possible to add it with a few lines of code -- I believe the way I did the encoding/decoding is just via injectors and this is an alternative injector.

**Comment by Mugen87** [comment] 2021-11-05 09:54
So I've invested some time this week to get more familiar with LogLuv TIFF files and implemented a simple C++ parser which loads a HDR file and converts the decoded data from CIE XYZ to linear RGB color space (single precision floating point). Here is a Gist with the code:

https://gist.github.com/Mugen87/fc666214c7ef4010443a946d785e1491

However I did not manage to compile this code or `LibTiff` itself via Emscripten to JS/WASM. To me (a more or less pure JS developer) Emscripten is not really accessible and quite hard to use, especially under Windows. On macOS I did not even manage to compile LibTIFF without Emscripten. Seems there are some incompatibilities between `LibTIff` and the latest XCode toolchain.

**Comment by mrdoob** [comment] 2021-11-05 21:01
@photopea any plans on adding SGILog (34676) or SGILog24 (34677) support to `UTIF.js`?

**Comment by photopea** [comment] 2021-11-05 21:54
@mrdoob what kind of image data would you like to get out of the file? You shold be able to get the raw data from it already using UTIF.js

**Comment by Mugen87** [comment] 2021-11-06 08:59
A LogLuv HDR image looks like so: [memorial.tif.zip](https://github.com/mrdoob/three.js/files/7490133/memorial.tif.zip)

It would be ideal if UTIF.js would return the HDR texels as RGB floating point values in linear space. It's important that no downscaling of texels into the 8-bit range happens.`TIFFReadRGBAImage` does this which makes it impossible to use the file as a HDR texture.

**Comment by photopea** [comment] 2021-11-11 22:50
I have implemented the support for LogLuv into UTIF.js . The new UTIF.js is not published yet, but you can open LUV TIFFs in www.Photopea.com .

Could you try it out, to see, if all your files work? 

Also, in what format would you like to get the pixel data? Do you want HDR or "clamped" to 0..1 ? What color space? Currently, I convert Luv > xyY > XYZ > RGB. Do you want it before or after the gamma correction?

**Comment by Mugen87** [comment] 2021-11-12 09:27
> Do you want HDR or "clamped" to 0..1 ?

It should be HDR in linear RGB. No gamma correction.

**Comment by Mugen87** [comment] 2021-11-12 09:33
> Could you try it out, to see, if all your files work?

I've tested with my local sample images and all worked!

**Comment by Mugen87** [comment] 2021-11-17 20:44
@photopea You are converting here from XYZ to RGB linear.

https://github.com/photopea/UTIF.js/blob/6a26a54581bfdf89813488bca05c348519238e6e/UTIF.js#L1151-L1153

Why are you using the CIE RGB matrix and not the sRGB one? 

For reference, the respective matrices are listed here: http://www.brucelindbloom.com/Eqn_RGB_XYZ_Matrix.html

The wikipedia entry also uses the sRGB matrix to convert from XYZ to RGB linear (section `From CIE XYZ to sRGB`, https://en.wikipedia.org/wiki/SRGB).

**Comment by Mugen87** [comment] 2021-11-18 21:17
@photopea Using the color conversion matrix from the paper solved our issue 👍 .

**Comment by photopea** [comment] 2021-11-18 22:06
What do you consider to be a correct LogLuv TIFF viewer? I tried to open LogLuv TIFF files in Adobe Photoshop, but none of these matrices was able to achieve colors similar to Adobe Photoshop, CIE RGB was the closest one.

**Comment by Mugen87** [comment] 2021-11-19 08:59
After some readings I suppose there is no "right" RGB color space. It really depends on what is most appropriate for your software.

I found out that the conversion matrix (standard CCIR 709 RGB/neutral white point ) used in the official [paper](http://www.anyhere.com/gward/papers/jgtpap1.pdf) works best to produce a result that is similar to our EXR, HDR and RGBM loaders.

**Comment by photopea** [comment] 2021-11-20 09:02
So Gregory Ward Larson made his own matrix, which basically corresponds to creating his own RGB color space (because the XYZ space is a standard). Or is that a matrix for Rec. 709 space? I was not able to find it anywhere else.

But in practice, images are converted from sRGB with the matrix from that article, which basically means defining a custom XYZ space, which is a bit different from the standard XYZ.

**Comment by Mugen87** [comment] 2021-11-20 09:17
> Or is that a matrix for Rec. 709 space?

Yes. The primary chromaticities of chapter 4.1 are the same like the ones listed in: https://en.wikipedia.org/wiki/Rec._709

**Comment by mrdoob** [comment] 2021-11-23 20:46
Now that https://github.com/mrdoob/three.js/pull/22857 has been merged, I guess we can remove the logluv code from the shaders?

**Closed** 2021-11-24 03:18 UTC
Labels: Enhancement
