### ISSUE TITLE
macOS/iOS instancing with multi-materials issue

### ISSUE THREAD

**Issue by AnotherHermit** [mrdoob/three.js#17223] opened 2019-08-09 17:10 UTC
macOS and iOS seems to have an issue drawing instanced geometries with multiple materials. I am unsure whether this is an issue in Three.js or if the problem lies deeper than that. 

Some older macbooks does not display the faulty behavior but I have limited access to different hardware to test on, so I am not sure exactly which generations are affected. I have tested on Safari and Chrome on MacOS and iOS.

Correct render on Linux (Chrome) [image](https://ibb.co/Y0x0w1F)
Faulty render on Macbook Air (Chrome) [image](https://ibb.co/DGjf4XN)

Live example [codepen](https://codepen.io/AnotherHermit/pen/GVBPQw)

##### Three.js version

- [ ] Dev
- [x] r107

##### Browser

- [x] All of them (probably)
- [x] Chrome
- [x] Safari
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [x] iOS

**Comment by Mugen87** [comment] 2019-08-10 11:57
I'm not able to reproduce this issue on my iMac with macOS 10.14.5 and latest Chrome (76.0.3809.100) and Safari (12.1.1). The iMac is from end of 2014 and uses an AMD Radeon R9 M295X 4 GB.

![image](https://user-images.githubusercontent.com/12612165/62821505-53ebad00-bb76-11e9-90a7-3e134ded737d.png)

> I am unsure whether this is an issue in Three.js or if the problem lies deeper than that.

I'm convinced it's not a `three.js` issue but rather a hardware or driver problem. Does it work if you upgrade to the latest macOS or iOS version?

**Comment by Mugen87** [comment] 2019-08-15 08:52
Closing. Please update to the latest version of iOS or macOS. If it does not help, try to report this to Apple. However, I assume this issue will never be fixed on these old devices.

**Comment by AnotherHermit** [comment] 2019-08-15 09:57
I agree with closing this issue since it is not related to three.js. For clarification though, this is **not** a problem on **old** devices, the issue is with the **newer** devices. I went through my local electronics store to try their line-up of macs and most of them displayed the faulty behavior. Even the new macbook pro (2019) with a Radeon card showed the same issue.

**Comment by mrdoob** [comment] 2019-08-16 04:28
Reopening this for further investigation...

**Comment by Mugen87** [comment] 2019-08-16 09:04
@AnotherHermit Can you please verify if the following both unit tests work on your Apple devices?

https://www.khronos.org/registry/webgl/sdk/tests/conformance/extensions/angle-instanced-arrays.html
https://www.khronos.org/registry/webgl/sdk/tests/conformance/extensions/angle-instanced-arrays-out-of-bounds.html

Both tests are part of a bigger conformance test suite used to verify WebGL implementations.

**Comment by AnotherHermit** [comment] 2019-08-16 09:28
The first link fails at the following tests
![image](https://user-images.githubusercontent.com/2399407/63158104-d3ff9000-c018-11e9-9920-6138770a74d3.png)

The second one succeeds.

**Comment by Mugen87** [comment] 2019-08-16 13:24
Interesting, both tests works on my iMac.

Maybe it's a good idea to report this issue to Webkit Bugzilla (https://bugs.webkit.org/) and mentioned the failing unit test.

**Comment by Mugen87** [comment] 2019-10-03 09:42
@AnotherHermit If you can still reproduce the issue, please report it to https://bugs.webkit.org/. `three.js` is not able to provide a fix here. Please mention the failing WebGL conformance tests in the report. I suppose if the tests are going to pass, the `three.s` codepen will also work.

I ask you to report the issue since I'm unable to reproduce it on my machines. It has to be a person how can actually verify a fix with a webkit nightly build.

**Comment by AnotherHermit** [comment] 2019-10-03 13:52
I still get the same failures. I have reported the bug now, https://bugs.webkit.org/show_bug.cgi?id=202522.

**Comment by Mugen87** [comment] 2019-10-03 14:06
Thanks!

**Closed** 2019-11-01 10:15 UTC
Labels: Device Issue
