### ISSUE TITLE
Models appear washed out/metallic on certain android devices

### ISSUE THREAD

**Issue by MotiejusO** [mrdoob/three.js#20997] opened 2021-01-04 12:52 UTC
**Description of problem**

Models appear to be washed out/metallic when they are loaded on certain Android devices.
From the tested devices Google Pixel and OnePlus phones display this issue. 
Models are loaded in .glb format (packed with PBR textures), the scene contains an HDRI environment map.

This issue may be related to #19479

**Example Screenshots**
![Preview-1](https://user-images.githubusercontent.com/31434858/103416517-cad07e00-4b8f-11eb-87e4-511caab12e78.png)
![Preview-2](https://user-images.githubusercontent.com/31434858/103416597-1b47db80-4b90-11eb-8ae4-e61bf7d1eb3c.png)

**Viewers used for testing**
- https://gltf-viewer.donmccurdy.com/ (r123)
- https://gltf.insimo.com/ (r88)

**THREE.js Versions tested**
- [x] r123 (issue appears)
- [x] r121.1 (issue appers)
- [x] r88 (works correctly)

**Browser**

- [ ] All of them
- [x] Chrome
- [ ] FireFox
- [ ] Internet Explorer

**OS**

- [ ] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [x] Android
- [ ] iOS

**Devices used for testing**
- Google Pixel 4a (Android 11, 2 separate devices) - issue appears
- Google Pixel 4xl (Android 11) - issue appears
- OnePlus 6 (Android 10) - issue appears
- Samsung Galaxy Note 9 (Android 10)
- Samsung Glaxy S20+ (Android 10)
- Samsung a50 (Android 9)

**Comment by Mugen87** [comment] 2021-01-04 13:35
Can you please share your glTF asset in this thread?

**Comment by makc** [comment] 2021-01-05 03:26
Oh I think I might have a model for this issue later, if topicstarter does not deliver. I have maybe same issue on Pixel, where normally brown surface becomes silver like T-2000

**Comment by makc** [comment] 2021-01-05 03:31
Might be irrelevant, but the page where I saw the issue spams the console with shader warnings on desktop:
![pow](https://user-images.githubusercontent.com/242577/103603418-dbc21c00-4f0e-11eb-91f1-5c355734b36c.png)

**Comment by MotiejusO** [comment] 2021-01-05 08:28
I couldn't attach the original model files due to NDA, so I've prepared a demo suzanne, that performs (as far as I can tell) identically. I've only tested it using https://gltf-viewer.donmccurdy.com/ so far with Note 9, Pixel 4xl and windows 10 (Chrome). 

glTF and glb files were exported using Blender 2.90. 

**Preview image**

![Suzanne-preview](https://user-images.githubusercontent.com/31434858/103622769-d204dc80-4f3f-11eb-88ff-05b62ff19a31.png)

**Suzanne model files**
[Suzanne.zip](https://github.com/mrdoob/three.js/files/5768938/Suzanne.zip)

**Comment by Mugen87** [comment] 2021-01-05 10:42
I can reproduce this on a Pixel 4a. Here is a temporary link to a live example (link expires in 5 days):

https://flash-orange-flyaway.glitch.me

**Comment by Mugen87** [comment] 2021-01-05 10:44
> Might be irrelevant, but the page where I saw the issue spams the console with shader warnings on desktop:

You are on Windows, right? These are DirectX warnings and can be ignored. When I remember correctly, it was considered that browser suppress this warnings because they constantly confuse users. Definitely not relevant for this issue.

**Comment by Mugen87** [comment] 2021-01-05 10:57
After some more investigating, I have found out that `r110` is the last release where the live demo produces the expected result on a Pixel 4a.

https://legend-gifted-bongo.glitch.me

Since `r111` the demo is broken.

**Comment by Mugen87** [comment] 2021-01-05 11:04
Okay, this issue is actually a duplicate of #17804.

It can be solved by computing tangents for each mesh and set `vertexTangents` to `true`. I've updated with this approach. It fixes the model on my Pixel 4a.

https://flash-orange-flyaway.glitch.me

**Comment by makc** [comment] 2021-01-05 11:30
Mugens hack does fix pixel for me as well

**Comment by Mugen87** [comment] 2021-01-05 11:34
It is actually not a hack 😅 . It was considered to always  precompute tangents if they are missing but we never decided to do so (https://github.com/mrdoob/three.js/issues/17804#issuecomment-557181604). Sketchfab does this, too.

One open issue is to implement MikkTSpace in `BufferGeometryUtils.computeTangents()`.

**Comment by MotiejusO** [comment] 2021-01-05 12:29
I was also able to get the model working correctly by computing vertex tangents when exporting the glTF asset as @Mugen87 suggested.

So if I understand correctly the issue should be handled by the author during asset creation or when setting up the viewer- in which case we can consider this issue closed. Thank you for the quick reply!

**Comment by Mugen87** [comment] 2021-01-05 12:42
> So if I understand correctly the issue should be handled by the author during asset creation or when setting up the viewer

I think we should discuss whether `GLTFLoader` or maybe even the engine core should compute tangents. I guess only a few app developers are aware about this issue. It might be more reliable to find a solution in the library.

**Comment by makc** [comment] 2021-01-05 14:19
but the gist is that gl_FrontFacing does not work reliably, right? so at best, only the users who have double-sided or back-sided materials should pay the price?

**Comment by mrdoob** [comment] 2021-01-07 11:04
> so at best, only the users who have double-sided or back-sided materials should pay the price?

I think this only happens when is double-sided?

Maybe computing the tangents when we try to render a model double-sided is the best solution for this?

**Comment by Mugen87** [comment] 2021-01-07 12:17
> I think this only happens when is double-sided?

As far as I understand, yes. It seems all materials that support normal maps can produce the visual glitch. However, only `MeshStandardMaterial` has a `vertexTangents` property right now.

> Maybe computing the tangents when we try to render a model double-sided is the best solution for this?

That sounds reasonable. I just wonder which component should contain the detection for double-sided materials. Maybe `GLTFLoader` is a good start?

**Comment by mrdoob** [comment] 2021-01-07 19:22
> Maybe `GLTFLoader` is a good start? It seems all users reporting the issue are loading glTF assets.

That sounds good to me.

/cc @donmccurdy @takahirox

**Closed** 2021-01-13 12:35 UTC
Labels: Device Issue

**Comment by donmccurdy** [comment] 2021-01-13 19:21
This does add a bit of per-vertex processing, which we've mostly avoided in GLTFLoader so far. Blender sets double-sided to true _by default_ (unfortunate, but unsure how to fix it) so this may affect a lot of models. If it's really only affecting a narrow set of devices I'm not sure we should add that cost for all model loading.

What do you think of (a) making it an option on GLTFLoader, or (b) just leaving it an opt-in optimization? I keep meaning to implement an offline tool for adding tangents to glTF models but haven't gotten to that yet. (https://github.com/donmccurdy/glTF-Transform/issues/88)

**Comment by Mugen87** [comment] 2021-01-13 19:36
> If it's really only affecting a narrow set of devices I'm not sure we should add that cost for all model loading.

Since also modern phones are affected by this issue (like for example a Pixel 4a), I tend to favor an automatic solution in the library. Making it optional mean things won't "just work" and users have to search again for a solution.

**Comment by donmccurdy** [comment] 2021-01-13 19:56
I'm worried this will make nearly all glTF models load considerably more slowly, for an error that (so far) appears to be very rare. I don't think this can safely be an automatic thing unless we can detect when it is necessary more accurately.

**Comment by donmccurdy** [comment] 2021-01-13 20:09
Taking `animation / keyframes` as an example — it happens to already have tangents, but if it didn't, this change would add 120ms to the loading time.

**Comment by Mugen87** [comment] 2021-01-13 20:19
>  this change would add 120ms to the loading time.

This is of course a noticeable overhead. 

@mrdoob What do you think? I would love to hide this issue from users a good as possible but on the other hand the additional computational overhead could disappoint more advanced users who already know to mitigate this issue.

**Comment by donmccurdy** [comment] 2021-01-30 01:33
I think I may have found a way to compile MikkTSpace to WASM. It's not something I would advise doing at loading time, but I would like to bundle it into an offline tool that adds tangents to a glTF file in place. Or Blender should be able to do that already. Would that help with your concerns?

/cc #11438

**Comment by donmccurdy** [comment] 2021-02-02 02:01
Could someone test this model on a Pixel 4a or other affected device? It contains the original `Suzanne.glb` above, as well as a version with (hopefully correct?) MikkTSpace vertex tangents.

[SuzanneTangents.zip](https://github.com/mrdoob/three.js/files/5908110/SuzanneTangents.zip)
