### ISSUE TITLE
Rendering to a renderTarget with outputEncoding causes shader compilation on every frame

### ISSUE THREAD

**Issue by brianpeiris** [mrdoob/three.js#18354] opened 2020-01-09 19:49 UTC
##### Description of the problem

Setting a renderer's `outputEncoding` and then rendering the scene to a WebGLRenderTarget causes shaders to be recompiled on every frame, reducing the framerate to ~5fps. I believe this bug was actually introduced in r110 with https://github.com/mrdoob/three.js/pull/17651 where outputEncoding was added to the WebGLProgram cache key.
Oddly, setting the now deprecated `gammaOutput` option to true seems to fix the issue. Not sure why.
You can also reproduce the bug by using the default renderer options and setting the renderTarget's `encoding` option to `sRGBEncoding`.

Here's a simplified reproduction: https://jsfiddle.net/brianpeiris/50eofuc6/

##### Three.js version

- [x] Dev
- [x] r112
- [x] r111
- [x] r110
- [ ] r109

##### Browser

- [x] All of them

##### OS

- [x] All of them

**Comment by Mugen87** [comment] 2020-01-09 20:06
You can fix the issue by setting `WebGLRenderer.outputEncoding` to `THREE.sRGBEncoding`. If you not do this, you effectively render with different encodings which explains the shader compilations. I also think it's not correct to do this anyway.

> Oddly, setting the now deprecated gammaOutput option to true seems to fix the issue.

When  you still set `gammaOutput` to `true`, the rendere internally configures `WebGLRenderer.outputEncoding` to be `THREE.sRGBEncoding`
.

https://github.com/mrdoob/three.js/blob/a8e93ecf28e593a478ae1da4d4710813e8075564/src/Three.Legacy.js#L1746

Fixed fiddle: https://jsfiddle.net/L7k2veg9/

**Comment by Mugen87** [comment] 2020-01-09 20:11
However, this does not fix #18354. This seems to be a separate issue.

**Comment by brianpeiris** [comment] 2020-01-09 20:24
Ah, I see. Thanks for the explanation! Feel free to close this issue if this is the expected behavior.

**Comment by Mugen87** [comment] 2020-01-09 20:30
> Feel free to close this issue if this is the expected behavior.

I would say it is the expected behavior since we can only achieve the result with a new shader program. I guess it would require some refactoring in order to make this more flexibel. However, I'm not sure how important that is. In your app is definitely more correct to use a common encoding.

**Comment by Mugen87** [comment] 2020-01-11 12:09
Closing for now.

**Closed by Mugen87** 2020-01-11 12:09 UTC
