### ISSUE TITLE
Memory leak in WebGL Renderer when resizing the renderer in WebKit on MacOS

### ISSUE THREAD

**Issue by arilotter** [mrdoob/three.js#11736] opened 2017-07-10 16:44 UTC
##### Description of the problem 
When `renderer.setSize` is called, some memory leaks. This isn't visible in the Chrome profiling tools, but in the MacOS Activity monitor, the statistic labeled "Memory Used" increases. The amount of memory leaked seems to somehow scale with the complexity of the scene - resizing [the cube demo](https://threejs.org/examples/webgl_geometry_cube.html) for 30 seconds leaks 4-5GB of memory, while resizing a complex project can leak 16GB in a few seconds

Somehow, this memory stays allocated after the tab or window is closed, and only appears to be cleared upon termination of the main browser process. Could this be a WebKit/Blink bug?

To reproduce: go to any ThreeJS project ([example](https://threejs.org/examples/webgl_geometry_cube.html))
grab the corner of the window and resize it continuously for ~30s, and watch "Memory Used" in Activity Monitor grow.

##### Three.js version
- [x] r86
##### Browser
Anything WebKit/Blink based, so
- [x] Chrome
- [x] Opera
- [x] Safari
- [ ] Firefox
##### OS
- [x] macOS Sierra
- [ ] macOS El Capitan
- [ ] Windows
- [ ] Android

**Comment by Mugen87** [comment] 2017-12-09 20:28
I'm unable to reproduce this with Chrome 63.0.3239.84, macOS 10.13.1 and `R88`. Closing for now.

**Closed by Mugen87** 2017-12-09 20:28 UTC
