### ISSUE TITLE
WebGL + Video + Android = NO

### ISSUE THREAD

**Issue by Villmer** [mrdoob/three.js#6606] opened 2015-05-27 07:23 UTC
Video files used as textures do NOT display on (any) Android browsers. Period.
Image files load fine but video is just black. Works fine on iOS and all desktop browsers so the WebGL renderer is doing its job. Not sure if this can be resolved using three.js or if it has to be fixed in Chromium. 

You can see an example of this (not working) here:
(open this on Chrome Android or Firefox android)

1) http://www.villmer.com/tools (heavy)
2) http://www.villmer.com/tools/test.html (light)

Bug has been filed with the Chromium team: https://code.google.com/p/chromium/issues/detail?id=488802

Bug has been reported with the Crosswalk team (for developing hybrid mobile apps using Cordova and an embedded Chromium WebView): https://crosswalk-project.org/jira/browse/XWALK-4143

Regards,
Mr. Villmer
www.villmer.com

**Comment by mrdoob** [comment] 2015-05-29 10:52
In Android (and iOS) videos don't autoplay. They can only play from a user action (tap screen).

**Comment by Villmer** [comment] 2015-05-29 11:00
Yes, I'm aware of some of the autoplay issues. My app, however, does use a tap action to play the videos. If you view www.villmer.com/tools on an iPad, the website works just fine. The issue is only on Android browsers.

Notes:

• This issue persists across ALL Android Chrome versions:
  - Chrome 42.0
  - Chrome Beta 43.0
  - Chrome Dev 44.0

• Multiple video formats have been tested (nothing works)
  - mp4 (h.264)
  - webm

• Multiple video sizes have been tested (nothing works)
  ** files with a power of 2 have been tested as well
  - 1024 x 512
  - 2048 x 1024
  - etc

• Multiple Bit Rates and Frame Rates have been tested (nothing works)

• In the HTML file, the crossOrigin attribute has been set to 'anonymous'
  - video.crossOrigin='anonymous'; //crossOrigin='';
  - video.setAttribute('crossorigin', 'anonymous');

• You can see this issue by viewing the following web pages on Android Chrome:
  - http://www.villmer.com/tools

**Comment by arscan** [comment] 2015-06-02 19:19
I had this problem suddenly show up too @Villmer (it was working a few weeks ago)... looks like it's a recent regression in chrome on android and they have a fix pending.  Is this the conclusion that you reached as well?  

https://code.google.com/p/chromium/issues/detail?id=494620
https://code.google.com/p/chromium/issues/detail?id=485482

**Comment by makc** [comment] 2015-06-04 11:22
@Villmer ha ha, so you went all the way to make adobe introduce video textures on ios/android, only to go back to webgl ?

**Comment by Villmer** [comment] 2015-06-04 11:25
@makc 
Yep.
:-)

**Comment by arscan** [comment] 2015-06-16 02:40
This appears to be fixed on the chrome android beta and dev channels, though it doesn't look like the fix has hit the stable channel yet.  I think it's safe to say this isn't a three.js issue.

**Comment by Villmer** [comment] 2015-06-16 06:54
@arscan 
Does this work on your Android device using Chrome Dev? --> www.villmer.com/tools

**Comment by Villmer** [comment] 2015-06-16 07:30
By the way, I didn't 'go back' to WebGL. It was quite the contrary. WebGL
simply picked up where Adobe and Flash and AIR left off.

**Comment by makc** [comment] 2015-06-16 09:52
@Villmer air now has video textures on both ios and android, what does webgl have?

**Comment by Villmer** [comment] 2015-06-16 09:59
I’m very happy to see Adobe now provides this feature. It only took me 4 years to get them to do it.
WebGL on iOS 8 runs remarkably well. Android is still behind but catching up.

**Comment by Villmer** [comment] 2015-06-16 10:31
@arscan 
Yes, I can confirm that video textures now work on Chrome Dev Version 45. (Very fast I might add)
Waaayy Cool!

**Comment by arscan** [comment] 2015-06-16 13:19
@villmer I'm not able to get the video sphere to work on your site.  Do I just slide over to the 4th sphere?  Should it just play?  I'm just seeing black inside of the 4th sphere.  I'm on a Galaxy S5

The thing that I was working on now is fixed (on chrome beta & dev at least), so I'm happy: http://www.robscanlon.com/about

**Comment by Villmer** [comment] 2015-06-16 13:52
@ Rob

Actually www.villmer.com/tools/min.html <http://www.villmer.com/tools/min.html> should be easier to handle on a mobile device. The first sphere is a video texture, the second is an image texture. What I’ve noticed is that the 1st frame does not automatically render as it does on iOS (I’ve coded three.js to render the 1st frame when it’s ready). On Android Chrome Dev, you have to enter the sphere (pinch out) and tap to get it playing (rendering). So, it does work but it isn’t as fluid and automatic as iOS or the desktop. As least it’s a light at the end of the tunnel. Here’s a video of it working on a low end phone: www.villmer.com/tools/dev_android.mp4

Nice site by the way.

**Comment by arscan** [comment] 2015-06-16 14:19
Ah, very cool, yeah that worked for me.

**Comment by makc** [comment] 2015-06-16 20:48
@Villmer I'm sure webgl is doing fine, but what I mean is, video decoding is still forced to make round trips, isn't it? when you call gl.texImage2D, do things actually happen in gpu?

**Comment by Cy-Bo-Rg** [comment] 2015-07-02 03:19
@Villmer 
Could it be a "cross-origin resource sharing" problem (not working locally) ?
I have a blacklisted device and I have a problem running multiple command line options but did you try with     --xwalk-command-line='--disable-web-security'  as the last argument for make_apk.py?

**Comment by Cy-Bo-Rg** [comment] 2015-07-04 17:08
ok, whatever...I'm sorry guys but it works...
At least on firefox latest beta build for android.
But upside-down...
three.js rev 65
![screenshot_2015-07-04-18-47-57](https://cloud.githubusercontent.com/assets/5455606/8508783/2eb8c14c-227f-11e5-9720-6d7a7cb73e40.png)
three.js rev 65
![screenshot_2015-07-04-18-49-01](https://cloud.githubusercontent.com/assets/5455606/8508785/3a7ef3f2-227f-11e5-9368-2d7e28fb7085.png)
three.js rev 71 master
![screenshot_2015-07-04-18-52-49](https://cloud.githubusercontent.com/assets/5455606/8508787/45ba9e42-227f-11e5-84a7-cf8a44879ca6.png)
three.js rev71 master
![screenshot_2015-07-04-18-54-03](https://cloud.githubusercontent.com/assets/5455606/8508790/5f186978-227f-11e5-97dc-405cac945f32.png)
three.js rev 71 master
![screenshot_2015-07-04-18-54-36](https://cloud.githubusercontent.com/assets/5455606/8508791/6de27b60-227f-11e5-884a-6d09c920a9cf.png)
three.js rev71 master
![screenshot_2015-07-04-18-55-09](https://cloud.githubusercontent.com/assets/5455606/8508793/76e14f84-227f-11e5-942a-487632c74235.png)

All demos working with audio.
I couldn't try chrome because I'm on a blacklisted device.
GT P3110, android 4.1.2, PowerVR SGX540.

If that's a bug, that's a browser bug since three.js works 99%.

**Comment by user972611** [comment] 2015-07-20 05:11
@Cy-Bo-Rg Same result here, 2 Samsung devices, ```Chrome``` and ```Stock``` browser does not display anything, just sound, ```Firefox``` upside down like your image

**Comment by makc** [comment] 2015-07-20 11:10
@Cy-Bo-Rg @user972611 not really relevant to the thread, but if you could post a script that returns true/false for your device (navigator.userAgent based or whatever else) that might help people to flip textures in their content ;)

**Comment by arscan** [comment] 2015-08-12 14:38
Looks like the fix for Chrome on Android hit the stable channel (version 44.0.2403.133), and it now works for me.

**Closed** 2015-08-12 15:09 UTC
Labels: Bug

**Comment by chanibal** [comment] 2015-08-13 11:24
Please reopen, the chrome update did not fix this.

Log from: http://threejs.org/examples/webgl_video_panorama_equirectangular:
```
THREE.WebGLRenderer 71
three.min.js:2 THREE.WebGLRenderer: OES_texture_float_linear extension not supported.
navigator.appVersion
"5.0 (Linux; Android 5.1.1; GT-I9505 Build/LMY48B) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.133 Mobile Safari/537.36"
```

**Comment by chanibal** [comment] 2015-08-13 11:31
Confirmed on Nexus 7, stock build

```
THREE.WebGLRenderer 71
three.min.js:2 THREE.WebGLRenderer: OES_texture_float_linear extension not supported.
three.min.js:2 THREE.WebGLProgram: gl.getProgramInfoLog()--From Vertex Shader:
--From Fragment Shader:
Link was successful.

favicon.ico:1 GET http://threejs.org/favicon.ico 404 (Not Found)
navigator.appVersion
"5.0 (Linux; Android 5.1.1; Nexus 7 Build/LMY47V) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.133 Safari/537.36"
```

**Comment by chanibal** [comment] 2015-08-13 11:41
Not working confirmed on Samsung Galaxy s6, stock build:
```
THREE.WebGLRenderer 71
three.min.js:2 THREE.WebGLRenderer: OES_texture_float extension not supported.
three.min.js:2 THREE.WebGLRenderer: OES_texture_float_linear extension not supported.
three.min.js:2 THREE.WebGLRenderer: OES_texture_half_float extension not supported.
three.min.js:2 THREE.WebGLRenderer: OES_texture_half_float_linear extension not supported.
favicon.ico:1 GET http://threejs.org/favicon.ico 404 (Not Found)
three.min.js:2 THREE.WebGLRenderer: EXT_texture_filter_anisotropic extension not supported.
navigator.appVersion
"5.0 (Linux; Android 5.1.1; SM-G920F Build/LMY47X) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.133 Mobile Safari/537.36"
```

**Comment by chanibal** [comment] 2015-08-13 11:56
Not working confirmed on Samsung Galaxy Tab SM-T705, stock build. This one is a bit more interesting:

```
THREE.WebGLRenderer 71
three.min.js:2 THREE.WebGLRenderer: Error creating WebGL context.THREE.error @ three.min.js:2
three.min.js:527 Uncaught TypeError: Cannot read property 'getShaderPrecisionFormat' of null
http://threejs.org/favicon.ico Failed to load resource: the server responded with a status of 404 (Not Found)
navigator.appVersion
"5.0 (Linux; Android 5.0.2; SM-T705 Build/LRX22G) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.133 Safari/537.36"
```

On an older chrome, the same thing happens:

```
three.min.js:523 THREE.WebGLRenderer 71
three.min.js:2 THREE.WebGLRenderer: Error creating WebGL context.
three.min.js:527 Uncaught TypeError: Cannot read property 'getShaderPrecisionFormat' of null
navigator.appVersion
"5.0 (Linux; Android 5.0.2; SM-T705 Build/LRX22G) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.93 Safari/537.36"
```

But the error is a bit more normal on the built-in "internet" app by samsung:
```
THREE.WebGLRenderer: OES_texture_float extension not supported. three.min.js:2
THREE.WebGLRenderer: OES_texture_float_linear extension not supported. three.min.js:2
THREE.WebGLRenderer: OES_texture_half_float extension not supported. three.min.js:2
THREE.WebGLRenderer: OES_texture_half_float_linear extension not supported. three.min.js:2
THREE.WebGLRenderer: EXT_texture_filter_anisotropic extension not supported. three.min.js:2
navigator.appVersion
"5.0 (Linux; Android 5.0.2; SAMSUNG SM-T705 Build/LRX22G) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/3.0 Chrome/38.0.2125.102 Safari/537.36"
```

@mrdoob, please reopen

**Comment by makc** [comment] 2015-08-13 12:31
@chanibal,
> Error creating WebGL context

how would they fix that?

**Comment by benaadams** [comment] 2015-08-13 12:33
@chanibal what does this tell you? http://webglreport.com/

**Comment by chanibal** [comment] 2015-08-13 13:10
I only have the SGS4 (i9505) with me at the moment, if you want more devices, ask and i'll arrange that:
![chrome-sgs4-webgl2](https://cloud.githubusercontent.com/assets/697605/9250415/0052be6c-41cd-11e5-9d5c-92d232498354.png)
![chrome-sgs4-webgl1](https://cloud.githubusercontent.com/assets/697605/9250416/005521fc-41cd-11e5-8954-93fbb47e4818.png)

What is most interesting is that the bears demo from http://vr.chromeexperiments.com **works on these devices**. Currently reverse engineering that and searching for what is changed. It's using and older THREEjs (WebGLRenderer 68).

**Comment by chanibal** [comment] 2015-08-13 13:21
@makc interesting does not mean fixable, though their built in browser supports webgl so it might be some kind of a blacklist for this tablet.

**Comment by arscan** [comment] 2015-08-13 15:11
Sorry for generalizing the fix across all phones and sites.  Specifically, it now works on my galaxy s5 running chrome 44.0.2403.133 on my site http://robscanlon.com/about/ which uses threejs v71

**Comment by chanibal** [comment] 2015-08-13 15:26
OK, just checked your page, @arscan and it actually does work also on my galaxy s4!
The log is a bit lengthy and only some warnings, but for completeness: https://gist.github.com/chanibal/709d35766ce14e45080b

So now the question is: *why doesn't the example in the gallery work?* Also why doesn't it work on my script as well as on most other sites on the web that use THREE.VideoTexture?

**Comment by mrdoob** [comment] 2015-08-13 15:37
It may be a texture size limitation.

**Comment by arscan** [comment] 2015-08-13 15:46
Sorry about those warnings spamming the log; I just never got around to properly scale my textures.

I didn't really do anything special on the page... just the standard "please click here" stuff to make sure that the video would start playing, but that is a pretty well known issue and I would expect other sites to have implemented that properly.

**Comment by benaadams** [comment] 2015-08-13 16:11
@chanibal are you testing against the fixed but unreleased dev branch (v72) and or the currently released live version (v71)?

**Comment by chanibal** [comment] 2015-08-13 16:37
Uhm... i have just been able to run movies up to 1920x1080 on my SGS4 (2048x1024 did not work). @mrdoob  is correct then.

Looks like this was actually closed for a good reason and i suck at testing.

And about other sites implementing that properly, the http://threejs.org/examples/webgl_video_panorama_equirectangular does not ask for a user initiated play event :/

**Comment by joshuacimino** [comment] 2015-08-30 00:26
could someone point me to: what is meant by 'properly scale my textures'

**Comment by chanibal** [comment] 2015-09-01 09:02
@joshuacimino using POT (power of two) textures, like 256x256, 1024x512 etc. In some cases that requires adding padding or using spritesheets.

**Comment by tbalouet** [comment] 2015-12-08 12:05
Just in case somebody fall here like I did, I had the same problem on r73 when loading a cubemap of 2048x2048 textures (6 times). It didn't work on Moto X 2nd gen and Nexus 5 but did on Galaxy s6 and iphone 6.
By resizing the images to 256x256 each, it works fine now. So it might be a problem of texture size loaded at once
