### ISSUE TITLE
Broken css3d renderer in Safari (r150-r155)

### ISSUE THREAD

**Issue by arslc** [mrdoob/three.js#26529] opened 2023-08-02 14:26 UTC
### Description

Hey every one! 
Firstly: thx for awesome 3d library!

Secondly: starting with release 150 css3drenderer in Safari browser was broken. I think this PR (https://github.com/mrdoob/three.js/pull/25508) was the source of the bug migrating for 5 releases now.

I haven't looked into this issue in detail, but rolling back to 149 release fixes it.

I made a minimally reproducible example on jsfiddle, take a look at it via google chrome as well as safari and compare.

This example shows slight shifting of elements and incorrect rendering. But if the created application is complex, then these shifts will become catastrophic.

Perhaps I misunderstood something and I forgot to do something, but it's strange that everything is fine in google chrome. And also when you roll back to version 149 everything becomes normal

### Reproduction steps

1. Open jsfiddle in google chrome
2. Open jsfiddle in Safari
3. Compare

### Code

```html
<script async src="https://unpkg.com/es-module-shims@1.3.6/dist/es-module-shims.js"></script>
<script type="importmap">
	{
		"imports": {
			"three": "https://unpkg.com/three/build/three.module.js",
      "three/addons/": "https://unpkg.com/three/examples/jsm/"
		}
	}
</script>
```
```js
import * as THREE from 'three'
import { CSS3DRenderer, CSS3DObject } from 'three/addons/renderers/CSS3DRenderer.js'

let cssRenderer, cssScene, camera

init()
render()
  
function init() {
  cssScene = new THREE.Scene()
  camera = new THREE.PerspectiveCamera(45, window.innerWidth / window.innerHeight, 0.1, 1000)
  cssRenderer = new CSS3DRenderer()

  cssRenderer.setSize(window.innerWidth, window.innerHeight)
  document.body.appendChild(cssRenderer.domElement)

  camera.position.z = 1000
  camera.lookAt(cssScene.position)

  const cssElement = createCSS3DObject('<div></div>')
  cssScene.add(cssElement)
}
function createCSS3DObject(content)  {
  const wrapper = document.createElement('div')
  wrapper.innerHTML = content
  const div = wrapper.firstChild

  div.style.width = '100px'
  div.style.height = '100px'
  div.style.background = 'red'

  const object = new CSS3DObject(div)
  return object
}
function render() {
  requestAnimationFrame(render)
  cssRenderer.render(cssScene, camera)
}
```

### Live example

* [Minimally reproducible example](https://jsfiddle.net/4937qkhf/)

### Screenshots

<img width="1182" alt="Google chrome" src="https://github.com/mrdoob/three.js/assets/117154548/680f2b3a-ca39-43dd-af09-5ab60dabe747">
<img width="1180" alt="Safari" src="https://github.com/mrdoob/three.js/assets/117154548/c5a8f6da-06ea-4e17-a914-147c9edfbb09">

### Version

150-155

### Device

Desktop

### Browser

Chrome, Safari

### OS

MacOS

**Comment by arslc** [comment] 2023-08-02 17:34
Hm, weird...

- macOS 12.6.6 | Safari 15.6.1

I also tried on my iPhone (iOS 15.3.1) and see exactly the same problem

| r149 | r150-r155|
|--|--|
|<img src="https://github.com/mrdoob/three.js/assets/117154548/9c1fcf44-db7b-4eef-ab10-61d233d0e3db" width="200"> | <img src="https://github.com/mrdoob/three.js/assets/117154548/05dbbbc4-a70c-4ba3-8c55-a98e7fbe1717" width="200"> |


I got this results using same code

**Comment by arslc** [comment] 2023-08-02 18:15
Okay, I tried to make some changes to that code.

If I comment out the line or change the value to 50%, then it starts centering correctly and works as it should.

```js
viewElement.style.transformOrigin = '0 0'; // <-- disable this line
```
or set 50%
```js
viewElement.style.transformOrigin = '50% 50%';
```

I don't know if that functionality will work because of such changes, because did not check in detail and this is the first attempt to find out what's wrong

**Comment by Mugen87** [comment] 2023-08-02 19:00
`transform-origin` should theoretically be supported in Safari: https://caniuse.com/?search=transform-origin

Does it work if you keep the line as it is but add the following:
```js
viewElement.style.transformBox = 'fill-box';
```

**Comment by arslc** [comment] 2023-08-02 19:15
No, unfortunately it doesn't change anything.

Yes, Safari supports transform-origin so I can set any supported values like:
- center center
- top center
- top center
- 10% 20%
- 200px 100%
- etc.

but any value other than `center center`/`50% 50%` moves this cube from the center

**Comment by Mugen87** [comment] 2023-08-02 19:18
@yomotsu Are you able to check the @arslc's live example (https://jsfiddle.net/4937qkhf/) in Safari? Is the quad centered on your device?

**Comment by yomotsu** [comment] 2023-08-02 23:06
Thanks for the detailed report.
I tried the live example (https://jsfiddle.net/4937qkhf/) in Safari, but I can't reproduce the problem.
Is there any missing to reproduce?

in Desktop Safari 16.5
<img width="1709" alt="Screenshot 2023-08-03 at 7 50 29" src="https://github.com/mrdoob/three.js/assets/212837/b1f06a2b-005f-48c0-a4cb-6c321abee111">
<img width="754" alt="Screenshot 2023-08-03 at 7 52 08" src="https://github.com/mrdoob/three.js/assets/212837/aaffbde3-af99-4c56-893d-c8dd20b0d803">
<img width="1710" alt="Screenshot 2023-08-03 at 7 52 24" src="https://github.com/mrdoob/three.js/assets/212837/2a02807b-7e68-4188-bea3-83335b4b7b67">

in OS Safari 16.5.2

![IMG_7293](https://github.com/mrdoob/three.js/assets/212837/e8593b06-960c-4119-80b1-b4fbb979ec6d)

**Comment by WestLangley** [comment] 2023-08-03 00:31
@arslc Is your page zoom set to 100%?

**Comment by arslc** [comment] 2023-08-03 10:12
@WestLangley yes, of course my zoom is 100%

Guys, i tried out another:

---

- Simulator iPhone 14 Pro (iOS 16.2) and real iPhone 12 mini (iOS 16.3) – All right

| Simulator (16.2) | Real (16.3) |
|--|--|
| <img width="250" src="https://github.com/mrdoob/three.js/assets/117154548/0118d747-3d71-4043-a71b-1b80b97e64db"> | <img width="200" src="https://github.com/mrdoob/three.js/assets/117154548/6b96fada-e62a-4ce7-871a-785c3e5ed221"> |

---

- Real MacBook Pro (macOS 12.5.1/Safari 15.6.1) - Same problem

<img width="500" alt="Снимок экрана 2023-08-03 в 12 13 37" src="https://github.com/mrdoob/three.js/assets/117154548/2979567f-2ea1-450e-9476-ec231c99a8d1">

---

- Real iPhone 11 (Safari 15.6.1/Google chrome v115.0.5790.130) - Same problem

| Safari | Chrome |
|--|--|
| <img width="200" src="https://github.com/mrdoob/three.js/assets/117154548/61402097-7e72-4e52-a53f-88418d6051ee"> | <img width="200" src="https://github.com/mrdoob/three.js/assets/117154548/00b7090f-4f65-4189-b8c8-e0beea166ff8"> |

---

- Browserstack Safari iOS 14/iOS 15.2 - Same problem

| Safari (iOS 14) | Chrome ( iOS 14.7) | Safari (iOS 15.4) |
|--|--|--|
| <img width="600" src="https://github.com/mrdoob/three.js/assets/117154548/71c233fe-6410-4113-9c1d-19daf5a378ca"> | <img width="600" src="https://github.com/mrdoob/three.js/assets/117154548/899049b9-2cd9-4084-b03b-8b384d2d2ba4"> | <img width="600" src="https://github.com/mrdoob/three.js/assets/117154548/c5d5d211-d7f3-4474-b81a-229ee875feda"> |

---

- Browserstack Safari iOS 16.2 - All right

<img width="500" src="https://github.com/mrdoob/three.js/assets/117154548/de8ebfbb-bf6e-45ad-95db-3fe7610fa507">

**Comment by Mugen87** [comment] 2023-08-03 10:20
It seems the Safari issue has been fixed since iOS 16 (and newer version of macOS).

**Comment by arslc** [comment] 2023-08-03 10:50
What about Google Chrome and Google App on iOS < 16?

<img width="1000" src="https://user-images.githubusercontent.com/117154548/258078361-899049b9-2cd9-4084-b03b-8b384d2d2ba4.png">

<img width="200" src="https://user-images.githubusercontent.com/117154548/258076623-00b7090f-4f65-4189-b8c8-e0beea166ff8.PNG"> <img width="200" src="https://github.com/mrdoob/three.js/assets/117154548/44bef8d1-4795-469b-8a08-2fe67a08d5e7">

It's weird...

**Comment by Mugen87** [comment] 2023-08-03 11:25
Chrome like all other browser on iOS are based on Webkit (so the browser engine of Safari).

**Comment by Mugen87** [comment] 2023-08-03 11:33
This issue is fixed in the iOS 16 and iOS 17 we will release next month. The adoption rate of iOS 16 is as follows:

- 90 % of all devices introduced in the last four years use iOS 16.
- 81 % of all devices use iOS 16.

There data are from May 30, 2023 and directly from Apple: https://developer.apple.com/support/app-store/

Sorry, but we will not provide a fix for this in order to support older Apple devices. If you still need to support them, please use an older release of `three.js` or a custom version of `CSS3DRenderer`.

**Closed by Mugen87** 2023-08-03 11:33 UTC
Labels: Browser Issue, Needs Investigation
