### ISSUE TITLE
EnvMap artifacting with 'mediump' precision on Quest 2 after upgrade from r132->r147

### ISSUE THREAD

**Issue by davehill00** [mrdoob/three.js#25071] opened 2022-12-04 04:22 UTC
**Describe the bug**

I recently upgraded a project from r132 -> r147. In r147, applying envmap to a MeshStandardMaterial shader set to 'mediump' precision causes cubemap artifacting on Quest 2 hardware.

**To Reproduce**

1. Go to [this jsfiddle](https://jsfiddle.net/zyxdbkvo/7/)
2. Observe reflections on the cylinder from the envmap.
3. When the Precision option (in the GUI) is set to mediump or lowp, visible banding artifacts are visible.

When I dig in further, it appears that the `vec3 bilinearCubeUV( sampler2D envMap, vec3 direction, float mipInt )`  function in cube_uv_reflection_fragment.js is the cause of this artifacting. If I add a `precision highp float;` to the start of that function, which sets floating point precision to high just for the scope of that function IIUC, the issue goes away.

I'm not sure if this also reproduces on Android devices, as I don't have easy access to one to test.

**Screenshots**
![no_artifacts_at_highp](https://user-images.githubusercontent.com/59743491/205474268-6460ea3b-4c7b-440c-84a2-70200b2120a4.jpg)
![banding_artifacts_at_mediump](https://user-images.githubusercontent.com/59743491/205474269-ae05d25e-9e6c-46e4-8893-f0ce0b51900b.jpg)

**Platform:**

 - Device: [Quest 2]
 - OS: [Quest VR OS]
 - Browser: [Meta Quest Browser]
 - Three.js version: [r147]

**Comment by CodyJasonBennett** [comment] 2022-12-04 06:05
I can reproduce this on a Pixel 3, Chrome 107 Android 12.

| Mediump     | Highp       |
| ----------- | ----------- |
| ![image](https://cdn.discordapp.com/attachments/525294361391398932/1048841841925165056/Screenshot_20221204-000236.png) | ![image](https://user-images.githubusercontent.com/23324155/205477046-6cc8a5cb-6d29-45c2-b37e-9144521bfa77.png) |

**Comment by Mugen87** [comment] 2022-12-04 09:17
Related: #14570

There is no real `mediump` support for built-in materials right now. At least `MeshStandardMaterial` does not produce correct output on `mediump` devices, even with no environment map applied. 

However, it was always assumed that only single code sections in the shaders require updates to make them work on `mediump`. The mentioned `vec3 bilinearCubeUV( sampler2D envMap, vec3 direction, float mipInt )` is obviously one of them.

**Comment by mrdoob** [comment] 2022-12-07 05:48
@davehill00 Any chance you can figure out the exact version of the library that produced this change?

**Comment by davehill00** [comment] 2022-12-07 14:37
> @davehill00 Any chance you can figure out the exact version of the library that produced this change?

Yep, I may not get to it until the weekend but I'll see if I can pinpoint the version.

**Comment by davehill00** [comment] 2022-12-08 03:14
@mrdoob - took a quick look this evening. It works properly on r135, then EXR loading appears to be broken (at least for the format of EXR file I happen to have) through r140. In r141, EXR loading starts working again, and the `mediump` issue is present.

Was EXR loading actually broken all that time (r136->r140), or was it just certain formats of EXR? If I can figure out how to generate a working EXR, I can check those last few versions to nail down which version the `mediump` issue appeared.

**Comment by Mugen87** [comment] 2022-12-08 09:25
> Was EXR loading actually broken all that time (r136->r140), or was it just certain formats of EXR?

Since `r136`, `EXRLoader` relies on half precision floating point textures. Previously, it was possible to store RGBE encoded texels in the unsigned byte format. We were aware that this change potentially broke WebGL 1 devices with no half float texture support. However, could this change be responsible for the problems on a Quest 2?

Sidenote:  HDR workflows in `three.js` require half float texture support since `r136`. That's why we have updated all HDR loaders.

**Comment by davehill00** [comment] 2022-12-08 14:23
@Mugen87 FWIW, I'm seeing the failure to load in r136-r140 on Google Chrome on Mac. 

The EXR I am trying to load is the one referenced in the jsFiddle referenced in the original issue I opened. It's one that I rendered out in Blender. When I open it in Photoshop, it looks like it's 32bpp, which I assume means 32-but float. I also rendered out a half-float version in Blender yesterday and saw the same errors in r136-r140.

**Comment by Mugen87** [comment] 2022-12-08 14:37
> I'm seeing the failure to load in r136-r140 on Google Chrome on Mac.

This particular EXR issue you are mentioning has been fixed via #24049 in `r141`. It was indeed an issue in the loader.

**Comment by Mugen87** [comment] 2022-12-08 14:48
Can you please make a test and verify if the same banding artifacts occur with `r136` and `RGBELoader`? Is it possible to render out a `.hdr` texture from Blender?

**Comment by davehill00** [comment] 2022-12-09 02:39
> Can you please make a test and verify if the same banding artifacts occur with `r136` and `RGBELoader`? Is it possible to render out a `.hdr` texture from Blender? I just want to make sure the banding is not related to `EXRLoader`.

Okay -- created a `.hdr` of the same texture. On r135, there are no banding artifacts. On r136, the banding artifacts appear. Setting the shader precision to `highp` makes the artifacts go away. So, it looks like the change came in with r136.

**Comment by Mugen87** [comment] 2022-12-09 09:19
Thanks for testing. So the issue is unrelated to `EXRLoader`.

@elalish I suspect #22998 has introduced the regression. Do you have any ideas why `bilinearCubeUV()` has problems with `mediump` after this change?

**Comment by elalish** [comment] 2022-12-12 09:43
As best I can tell it's not that it has problems with `mediump` generally, but specifically on this device. I would guess it's some kind of GPU driver bug. Maybe too little precision during an intermediate computation?

**Comment by Mugen87** [comment] 2022-12-12 09:51
I can reproduce the issue with Chrome on a Pixel 4a, too. It seems to happen on a 3a as well, see https://github.com/mrdoob/three.js/issues/25071#issuecomment-1336329936.

**Comment by Mugen87** [comment] 2022-12-12 10:16
I could narrow down the issue a bit. It seems changing the following line:
https://github.com/mrdoob/three.js/blob/17386766a77b7916bbaa45aba9e9922d5b81d728/src/renderers/shaders/ShaderChunk/cube_uv_reflection_fragment.glsl.js#L88
to 
```
highp vec2 uv = getUV( direction, face ) * ( faceSize - 2.0 ) + 1.0; 
```
Demo: https://jsfiddle.net/6wxabnkq/4/
So it seems the uv computation breaks in some way with `mediump`.

**Comment by elalish** [comment] 2022-12-12 10:56
Good find! That seems like a reasonable work-around.

**Comment by Mugen87** [comment] 2022-12-12 11:37
Maybe we figure out at some point a new way of computation that is compatible for `mediump`. For now, the `highp` workaround should be sufficient.

**Closed** 2022-12-12 11:42 UTC
Labels: Needs Investigation
