### ISSUE TITLE
Property lights throws an error in the console

### ISSUE THREAD

**Issue by enheit** [mrdoob/three.js#15317] opened 2018-11-26 12:41 UTC
Setting `lights: false` for `MeshStandardMaterial` throws an error in the console
```javascript
var material = new MeshStandardMaterial({ color: 0x28292d, side: DoubleSide, lights: false });
```
![image](https://user-images.githubusercontent.com/8645216/49014587-4f6a9a00-f189-11e8-94e1-39b07f3446ab.png)

- [ ] Dev
- [x] r98
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

**Comment by Mugen87** [comment] 2018-11-26 13:18
It's not intended that users change this property for built-in materials. Why do you set it to `false`?

**Comment by Mugen87** [comment] 2018-11-26 13:31
Duplicate of #13896

**Closed by Mugen87** 2018-11-26 13:31 UTC
