### ISSUE TITLE
Object3D.toJSON() not working for Points

### ISSUE THREAD

**Issue by mamun4122** [mrdoob/three.js#14035] opened 2018-05-10 11:56 UTC
##### Description of the problem

I have created some points using the following code.
```
    let geometry = new THREE.Geometry();
    geometry.vertices.push(new THREE.Vector3( 5, 5, 0));
    geometry.vertices.push(new THREE.Vector3( 10, 5, 0));
    geometry.vertices.push(new THREE.Vector3( 15, 5, 0));

    geometry.colors.push(new THREE.Color(1, 0, 0));
    geometry.colors.push(new THREE.Color(0, 1, 0));
    geometry.colors.push(new THREE.Color(0, 0, 1));

    let material = new THREE.PointsMaterial({size: 2,  alphaTest: 0.5, vertexColors: THREE.VertexColors});
    let mesh =  new THREE.Points(geometry, material);
``` 
Now when i want to convert it using `mesh.toJSON()` the resulting json doesn't contain the colors for the vertices.

Here is the working [jsfiddle](http://jsfiddle.net/hp5bhf3y/3/).

##### Three.js version

- [ ] Dev
- [x] r92
- [ ] ...

**Comment by Mugen87** [comment] 2018-05-10 12:11
It seems that `Geometry.toJSON()` does not respect `Geometry.colors` so far.

But you can use `BufferGeometry` as a workaround: http://jsfiddle.net/hp5bhf3y/4/

**Comment by gooderist** [comment] 2018-08-10 09:46
Hello, hope you don't mind I put in a PR for this. It seemed like an easy change.

**Comment by Mugen87** [comment] 2018-08-17 11:02
Closing. Duplicate of #7149.

**Closed by Mugen87** 2018-08-17 11:02 UTC
Labels: Bug
