### ISSUE TITLE
OrbitControls get stuck on Meta Quest 3 using both hands / controllers

### ISSUE THREAD

**Issue by MatteoL-W** [mrdoob/three.js#27333] opened 2023-12-07 02:38 UTC
### Description

Hello,

After applying the "intuitive zoom gesture" using both hands/controllers on my Meta Quest 3, OrbitControls sometimes get stuck. 
I didn't find any way to get out of this stuck state, even by resetting the controls (reset method). 
As you can see in the linked videos, it's probably about the gesture interpreted as a translation. But I don't know why it breaks the controls.

Additionally, the canvas may go blank because the controls matrix is filled with NaN values. But this is something I haven't reproduced on the THREE.js example so it's maybe an issue from my personal code. It's totally unclear whether these two phenomena are related.

Thank you for your time !

### Reproduction steps

1. Open the "Meta Quest Browser" on the Meta Quest 3
2. Open an orbit controls app
3. Try the "zoom gesture" (see the videos)

### Code

https://threejs.org/examples/#misc_controls_orbit

### Live example

* [Three.js orbit controls example](https://threejs.org/examples/#misc_controls_orbit)

### Screenshots

[Controls get stuck - video](https://github.com/mrdoob/three.js/assets/60264973/f243bf37-bbdc-4a48-8e71-ea72f595597a)
[Controls get stuck (interpreted as a translation?) - video](https://github.com/mrdoob/three.js/assets/60264973/a15402fa-5fb1-4458-8148-dc8326ca65e1)
[Controls get stuck - Controller example video](https://github.com/mrdoob/three.js/assets/60264973/72662554-6297-4571-97bf-c7be7cded3bc)

![Controls matrix filled by NaN](https://github.com/mrdoob/three.js/assets/60264973/81898fd7-0666-4aa9-8571-8f4a7f821177)

### Version

r156

### Device

Headset

**Comment by Mugen87** [comment] 2023-12-08 10:51
I can confirm the issue on a Quest 2. As soon as you use both hands or both controls for interaction, `OrbitControls` breaks. The behavior is exactly like documented in your videos. The controls can get stuck or pan in unexpected ways such that the camera is translated out of the scene.

Not sure what happens here but it seems that dual pointers are not properly processed right now. Maybe we can start to investigate this issue by logging the pointer events to the browser console. Could you help use here an put `console.log( event );` to `onPointerDown()` and `pointerup()` and check if there is something unexpected? Next, `pointermove` can be checked although this will put way more entries into the console. 

This requires remote debugging though. If the setup is too complicated, one could also print the event data into a separate box on the example website. We could then inspect the data while wearing the headset.

**Comment by MatteoL-W** [comment] 2023-12-11 06:55
Hello Mugen87,

I made quickly a [jsfiddle](https://jsfiddle.net/MatteoLW/sad641mu/12/) with an OrbitControls, logging the event as you asked. The property displayed on the screen can be easily modified.

Nothing seemed strange to me about the pointer and pointer down. But I noticed something very interesting.
It appears that zooming can occur if both hands touch the screen in this order: right hand THEN left hand.
The controls go wrong if I touch the screen with the two hands at the same time, or in the inverse order.
Can anyone confirm this phenomenon on their device? Thank you so much !

**Comment by MatteoL-W** [comment] 2023-12-18 05:21
Hello again, 

It seems that the touch order is not a consistent thing for the scale gesture; I still sometimes have the issue.
Sorry, I can't really create a general rule about it.

Sometimes, I have an issue where the regular rotation with the right hand controller leads to the same white screen.
It seems not to happen when I use the left controller.

Thanks again,

**Comment by Mugen87** [comment] 2023-12-28 09:57
Test link: https://rawcdn.githack.com/mrdoob/three.js/dev/examples/misc_controls_orbit.html

**Comment by Mugen87** [comment] 2023-12-28 10:02
@MatteoL-W After the latest PRs on `dev` the behavior on my Quest 2 is now different. I don't get sudden jumps anymore however the controls feel now stuck. Even orbiting (so the usage with just one controller/hand) does not work properly anymore. Can you make a test on your Quest 3 as well?

**Comment by cabanier** [comment] 2023-12-28 14:53
> /ping @cabanier

Is this new functionality? Do you think this is a bug in the zoom controls or browser?
I will take a look today to see if I can reproduce and fix

**Comment by sciecode** [comment] 2023-12-28 14:53
I've been trying to explore possible causes for the reported problem, but I can't find anything out of order on our regular `touch` implementation, which leads me to believe this could be caused by quest dispatching `mouse` events or possibly a mix of `mouse` and `touch` events. Both which are assumed to never happen.

That is the only scenario I can think that could lead to the problems showing here, I've setup a debug example which logs `pointerType`, `pointerId` and `button` properties on `pointerdown` and `pointercancel` events. This could help validate if my assumption is correct, if someone would be so kind to confirm this.


[debug - controls_orbit](https://rawcdn.githack.com/sciecode/three.js/716b94ea00ade737b5351048a53e63c43759cf51/examples/misc_controls_orbit.html)

**Comment by Mugen87** [comment] 2023-12-28 15:16
> Is this new functionality? 

`OrbitControls` is based on pointer events since `r120`. The pointer implementation wasn't 100% complete (and correct) so created a few PRs to fix things. We had no luck so far to get things right with the Quest.

> Do you think this is a bug in the zoom controls or browser?

`OrbitControls` should work with mouse, trackpad or touch devices as intended now. The issues reported here can only be reproduced with Quest hardware so we assume this looks like a browser bug. 

After some more testing, it seems the whole page zooms in when I apply the zoom gesture (meaning holding both triggers and then move the pointers away from each other).

**Comment by cabanier** [comment] 2023-12-28 15:25
Ah. This isn't WebXR!
Someone on my team added multitouch and that has some bugs associated with it. I'll reproduce and contact them (or fix it)

**Comment by cabanier** [comment] 2023-12-28 17:59
@sciecode this is a bug on the browser side. The pointer ids are not sent correctly. I will try to fix this.

**Comment by sciecode** [comment] 2023-12-28 18:05
> @sciecode this is a bug on the browser side. The pointer ids are not sent correctly. I will try to fix this.

That makes sense, we rely on `pointerId` to differentiate and recall previous positions. Thank you for letting us know, and taking your time to take a look at it. ❤️

**Comment by cabanier** [comment] 2023-12-28 18:15
> > @sciecode this is a bug on the browser side. The pointer ids are not sent correctly. I will try to fix this.
> 
> That makes sense, we rely on `pointerId` to differentiate and recall previous positions.

This will be fixed in the next browser release. The Chromium 116 integration broke this.
I can send you a private build if you want to test the fix yourself.

**Comment by sciecode** [comment] 2023-12-28 18:20
I don't have Quest hardware with me at the moment, perhaps @Mugen87 would be able to validate. Eitherway, we can get back to it once this lands in the next release. Appreciate the help once again.

**Comment by Mugen87** [comment] 2024-01-25 09:56
I have tested the controls today with a Quest 2 and the dev version of [misc_controls_orbit](https://rawcdn.githack.com/mrdoob/three.js/dev/examples/misc_controls_orbit.html). 

Unfortunately, the interaction with both controllers is still broken. _Sometimes_ the first and second zoom work but on the next interaction the camera flies out of the scene and the controls seem to be in an invalid state.

**Comment by cabanier** [comment] 2024-01-25 16:44
> I have tested the controls today with a Quest 2 (with recent software updates) and the dev version of [misc_controls_orbit](https://rawcdn.githack.com/mrdoob/three.js/dev/examples/misc_controls_orbit.html).
> 
> Unfortunately, the interaction with both controllers is still broken. _Sometimes_ the first and second zoom work but on the next interaction the camera flys out of the scene and the controls seem to be in an invalid state. And the controls can become unresponsive like described in the initial post.
> 
> Maybe the Meta browser does still not have the mentioned fix?

There were more issues with touch events so we decided not to release it. Hopefully the next version will have it.
Do you want me to notify you if/when it's released?

**Comment by Mugen87** [comment] 2024-01-25 17:02
> Do you want me to notify you if/when it's released?

Yes, thanks! A ping in this issue would be perfect.

**Comment by Mugen87** [comment] 2024-02-13 14:38
I've used my Quest 2 for a help request today and used the opportunity to test again with the latest Meta Quest browser (31.3.0.11.57.563651913) I can confirm the issue is now fixed 🎉 !

**Closed by Mugen87** 2024-02-13 14:38 UTC
Labels: Browser Issue, Addons
