### ISSUE TITLE
npm/bower: do not ignore src/ and examples/ to enable automatic custom builds

### ISSUE THREAD

**Issue by simonihmig** [mrdoob/three.js#8071] opened 2016-02-04 11:22 UTC
Just a suggestion: do not ignore the src and examples folders when installing three.js from npm and/or bower. 

This would not break compatibility with existing projects that use npm or bower to install three.js, but provide a valid use case: it would allow to integrate a custom build process for three.js into our existing build pipelines for our apps. 

The current way for custom builds as outlined in https://github.com/mrdoob/three.js/wiki/build.py,-or-how-to-generate-a-compressed-Three.js-file is focused on a manual process: clone the repo, run the build, and add the finished custom JS file to your app's git repo. However that cannot be automated conveniently within the context of existing build processes for our own apps. Upon updates of three.js you have to repeat these steps every time.

On the other hand if the src and examples files would not be excluded, one could use the package managing power of npm or bower to include your three.js dependency in your project (with the ability to target specific versions, version ranges, the dev branch...), and have your build workflow of choice (gulp, grunt, whatever) automate the custom build process, as it would be able to pick the individual src files from the installed package (node_modules/bower_components) now. This would allow for effortless updates, integration in CI server workflows etc.

I can file a PR (easy enough ;)), just wanted to know if there might be objections?

**Comment by bhouston** [comment] 2016-02-08 17:11
Right now in the current npm project /src and /eamples/js are included.  It isn't automatically built though.  If you wanted to add a PR to add that to the npm build.js script, that would be appreciated.

**Comment by simonihmig** [comment] 2016-02-09 00:57
@bhouston I see you have some custom build scripts for npm. Didn't notice before. However that leads to some inconsistent package contents:
When installing from the npm repository (`npm install three`), you get this package contents, resulting form the npm build.js script:

```
README.md
examples
package.json
src
three.js
three.min.js
```

However when referencing a git branch/commit (`npm install mrdoob/three.js#dev`, which is what I did in my project), you get (matching the file structure in the git repo):

```
CONTRIBUTING.md
LICENSE
README.md
bower.json
build
examples
package.json
``` 

And apparently `three.js` in the first case is not the same as `build/three.js`in the second, as it has the header.js and footer.js added during the npm build step, which is missing when having npm pull the package content directly from git...

Is there a reason for that, or wouldn't it be possible to have the normal build produce a file which is suitable for npm as well (just adding the module.exports stuff), and `npm publish` directly from the root?

Anyway, back to my case: as I was pulling the package from git (was using dev features), I was getting a different package, which is missing the src folder, because it is excluded in the `.npmignore` on the root folder, see https://github.com/mrdoob/three.js/blob/master/.npmignore#L3

Any objections to remove that exclusion from `.npmignore` (and likewise from `bower.json`)?

**Comment by bhouston** [comment] 2016-02-09 15:41
@simonihmig I am fine with whatever you want to do as long as it works for everyone -- I am okay pulling in more into the npm module to make people's lives easier -- the only issue is that we do not a huge package to be downloaded -- so I would really not like to include all of /examples as it contains 200MB of binary assets.

Please submit a PR for the build.js script and we can use that to generate the new modules.

Strange thought: Would it be even possible to have the npm module pull in github.com/mrdoob/three.js directly as a submodule so that the npm module for three is a shim?  That would sort of be cool as well, but maybe not practical -- just I would love a lazy always up to date solution.

**Comment by tbroyer** [comment] 2016-02-18 13:05
Not directly related to this issue, but the `package.json` at the root of the repo has `"name": "three.js"` rather than `"name": "three"` which makes it impractical to switch from `three@0.74.0` as published on the NPM registry to `mrdoob/three.js#dev`.

I echo @simonihmig's request (correct me if I misunderstood) that it would be great if the package content was the same in both cases: same name (first), and same `three.js` content (ideally, having the `three` package in the NPM registry coming right from an `npm publish` at the root of the repo).
I don't need the `src/` or `examples/` (except for `examples/js/`, but it's included already) folders though.

**Comment by donmccurdy** [comment] 2017-12-28 04:58
As `examples` is not ignored in npm builds, I think the only other open item here is perhaps pulling examples into the npm builds. As that's a duplicate of https://github.com/mrdoob/three.js/issues/9562 and https://github.com/mrdoob/three.js/issues/9403, closing this issue.

**Closed by donmccurdy** 2017-12-28 04:58 UTC
