### ISSUE TITLE
prune repo maybe?

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#6922] opened 2015-07-29 22:02 UTC
Do you guys realize that to fork 3js you need over 500MB of space? Maybe it's time to let everything older than, say, r70 go? Maybe store that in three.js.history repo or something?

**Comment by mrdoob** [comment] 2015-07-30 00:10
Isn't that the git history? I don't think we can prune that...?

**Comment by dmtaub** [comment] 2015-07-30 03:49
There are various ways. Here is a older one.
http://web.archive.org/web/20130116195128/http://bogdan.org.ua/2011/03/28/how-to-truncate-git-history-sample-script-included.html

**Comment by benaadams** [comment] 2015-07-30 04:13
Not sure the contributors would be happy with history loss.

200MB is the samples directory
25MB is utils
300MB is .git

So it would still be over 225MB + 225MB = 450MB as .git would still contain the samples?

**Comment by CodingFabian** [comment] 2015-07-30 07:51
Hi,
the request is reasonable. I took the freedom to check the repo according to instructions here: http://naleid.com/blog/2012/01/17/finding-and-purging-big-files-from-git-history

```
25c3fa6e1c50e51d71d30fd6e33536b404f7df33 31558148 examples/models/gltf/rambler/Rambler.dae
12f8b72dca42723590f738e7cd0e6d5a6c880e05 25753188 examples/models/skinned/marine/marine_anims.blend
5f3e456ea134fd71e3e5ea569069cf44a5c5ad13 11541972 examples/models/gltf/rambler/Rambler.bin
a3838dce3d1379641db143e8b1400395ce68575d 9802796 examples/geometry/WaltHead.blend
ad89fd36208d173ca0c9308d3ac9464f6a518ade 7649458 examples/models/skinned/UCS/skins/Caucasion_Male.jpg
d07fab28f42909b12f40d344aaf26c713480785a 7068912 examples/models/skinned/marine/marine_fbx.blend
f119c04ad6579e6e990cdafcd88cad1749cd11a0 6837360 examples/models/skinned/UCS/skins/Caucasion_Female.jpg
393fde80a7e45614490ec294a0df202059a001f0 6699886 utils/build/compiler/compiler.jar
1654189e775768d2069575f889adb76ac4019ca3 6417316 examples/models/skinned/UCS/skins/Black_Female.jpg
a12f24be30b353f27a75e4496f25768f4f6a21fc 6007184 utils/build/compiler/compiler.jar
bf210501997e2abf06de0a431ebf6a8c76e9ad10 5874479 examples/sounds/376737_Skullbeatz___Bad_Cat_Maste.mp3
e23352ff0bdbf35d7711c9f49520ef13b4ded3e5 5856710 utils/build/compiler/compiler.jar
1af9a2fbd748c0447e8edecc905fe6ae68e7f4f9 5508167 examples/models/skinned/UCS/skins/Indian_Male.jpg
d958a61882cfaf5a425e8cb6470b01a8e0f5598d 5378434 utils/compiler/compiler.jar
8962c4f0e1679b4a4fed7a82b3e997808f149092 5266129 utils/compiler/compiler.jar
```
I see that the google closure compiler is checked in. Maybe this could be changed to a script which downloads it instead? There are also multiple versions of it which could be safely pruned.

Also in the history, there are big examples (this rambler thing especially with over 50mb). I suppose that could be also pruned from the history.

The main Issue I personally see with pruning the history, is that while it works, it is so easy to undo the whole pruning with an accidental commit. This can easily happen any time in the future.
If you have means to avoid that, I would say it is reasonable to at least get rid of a couple of big binary files in the history.

**Comment by makc** [comment] 2015-07-30 10:16
> 200MB is the samples directory

which I guess makes it good idea to keep them in separate repository as well.

**Comment by makc** [comment] 2015-07-30 10:19
if these same megabytes make the majority of .git content, this alone would significantly help the problem. the only problem then are commits that change both the source and the examples, I guess you could keep those commits as long as they do not reference large files?

**Comment by benaadams** [comment] 2015-07-30 14:02
This has some interesting info around that: https://git-scm.com/book/en/v2/Git-Internals-Maintenance-and-Data-Recovery

Also warnings:

> **Be warned: this technique is destructive to your commit history** It rewrites every commit object since the earliest tree you have to modify to remove a large file reference. If you do this immediately after an import, before anyone has started to base work on the commit, you’re fine – otherwise, you have to notify all contributors that they must rebase their work onto your new commits.

**Comment by Cy-Bo-Rg** [comment] 2015-07-31 01:03
Quote from wiki.
History:
29 July 2015: GitHub announced it had raised $250 million in funding in a round led by Sequoia Capital. The round valued the company at approximately $2 billion.[24]

As long as it doesn't affect us personally, that's not a problem imo.
Not only that, but the repo. history has an enormous value.
Deleting it is a crime! X)

**Comment by makc** [comment] 2015-07-31 01:38
I was not implying that we should save github space, lol :) But, having to download 500MBs to edit one file is kind of not friendly thing. Also, here I had to move a couple of git repos to free some SSD space, and 3js was one of them (the other one was ~6GB, for example, so it's not _that_ bad yet with 3js).

**Comment by bhouston** [comment] 2015-07-31 01:48
You can do shallow clones:

https://github.com/git/git/blob/82fba2b9d39163a0c9b7a3a2f35964cbc039e1aa/Documentation/git-clone.txt#L182-L184

**Comment by mrdoob** [comment] 2015-07-31 02:12
@bhouston to the rescue!

**Closed** 2015-07-31 02:11 UTC

**Comment by dmtaub** [comment] 2015-07-31 05:57
shallow clones aren't an acceptable solution for many cases. they cause
some problems when you have multiple branches (fails to find the reference)
and they don't work on older git clients (for deployments that depend on
older versions of linux). this has been a pain point for our deployments
which is a disincentive for a unified development/production environment
using NPM.

**Comment by Cy-Bo-Rg** [comment] 2015-07-31 16:19
I don't want to look like the annoying guy, but, to make an example, check this out :P

http://www.newegg.com/Product/Product.aspx?Item=9SIA5AD1P56740&nm_mc=OTC-Froogle8&cm_mmc=OTC-Froogle8-_-Hard%20Drives-_-Seagate-_-9SIA5AD1P56740&ved=0CAsQrUNqFQoTCO-6-qDihccCFUE7FAodTNgIqA&ei=V5-7Va-zJcH2UMywo8AK

**Comment by dmtaub** [comment] 2015-07-31 17:05
That's orthogonal to this conversation. The problem is bandwidth and speed
of deployment--not storage space.

**Comment by Cy-Bo-Rg** [comment] 2015-07-31 17:11
@dmtaub bandwidth is always relative to github' servers, speed of deployment is developer dependent.
Also, I doubt that someone will make megabytes of commits so easily, considering that the vast majority of them are code, so, we're talking about kilobytes. :/

**Comment by CodingFabian** [comment] 2015-07-31 17:18
The concern from the OP is valid. The git repo is too big because of binaries. This slows down fresh forks and wastes unnecessary disk space.

This can be fixed by the project by removing the binaries from history. I listed which ones that are. If the project decides not to do that for whatever reason thats fine, but discussions about prices of hard discs and such are not bringing us anywhere.

**Comment by Cy-Bo-Rg** [comment] 2015-07-31 17:39
@CodingFabian  I'm freely expressing my opinion; the meaning is that the problem is personal and doesn't affect everybody in the same manner.

**Comment by makc** [comment] 2015-07-31 18:36
@Cy-Bo-Rg Good idea, let's put "you will need to buy 1TB drive from [here] before contributing" into readme :)

**Comment by bhouston** [comment] 2015-07-31 18:47
I did a quick survey of the repos on my HD.

ThreeJS is 315MB, ExocortexCrate is 261MB, ProjectX is 1.2GB, ProjectY is 1.07GB, and ProjectZ is 150MB, and ProjectW is 320MB.

I do not think that ThreeJS is so out of line for a highly active and serious project.

**Comment by Cy-Bo-Rg** [comment] 2015-07-31 19:19
@makc I've found those on google shopping just for the sake of the point, don't blame me for referrals :P
But yeah,that might be something.. x)

@bhouston same line of thought.

**Comment by makc** [comment] 2015-07-31 19:32
@bhouston so what you're saying is, since others repos are huge it is okay for three.js to be huge, too. well, I can't say this kind of logic ever convinced me.
