### ISSUE TITLE
AudioListener browser bug ?!

### ISSUE THREAD

**Issue by osov** [mrdoob/three.js#17705] opened 2019-10-10 07:30 UTC
#Three.js version
- [x] r109

Browser
- [x] Chrome

OS
- [x] Windows

the problems are pretty similar:
#https://github.com/mrdoob/three.js/issues/15344
#https://github.com/mrdoob/three.js/issues/15422

if you create a AudioListener, add to the scene, but no sound is created, then after some time the FPS will begin to fall.
The reason seems to be in the browser implementation, as the load is on the "linearRampToValueAtTime" method.
If you remove the listener from the scene, then the FPS is normalized, or if you add sound and play it, the problem will also be solved.
I do not know how best to solve this problem, I just report on its presence.
[perfomance linearRampToValueAtTime](https://imgur.com/77cm0zw)
Minimum part sample:
```
var listener = new THREE.AudioListener(); 
camera.add( listener ); 
```

**Comment by Mugen87** [comment] 2019-10-10 09:19
Can you please provide more information about this issue?

- Which browsers are affected?
- What do you mean with: "after some time"? 10 seconds, 1 min, 1 hour?
- Can you reproduce the issue with this live example? https://jsfiddle.net/nxyjaLqv/ (I can't see a framedrop even after 10 minutes).
- Can you reproduce the issue with plain Web Audio?

**Comment by osov** [comment] 2019-10-10 10:15
> Which browsers are affected?

Chrome 77.0.3865.90

> What do you mean with: "after some time"? 10 seconds, 1 min, 1 hour?

Over 5 minutes.

> Can you reproduce the issue with this live example? https://jsfiddle.net/nxyjaLqv/ (I can't see a framedrop even after 10 minutes).

There is no AudioListener component in this demo

> Can you reproduce the issue with plain Web Audio?

I have not tried it. The problem appears if there is a AudioListener, but there is no active sound.

**Comment by osov** [comment] 2019-10-10 10:49
the problem is relevant from the very start, you do not even have to wait.
[perfomance](https://imgur.com/n7O7GZK)
I did not send a report to Google.

**Comment by Mugen87** [comment] 2019-10-10 12:13
Sorry, I can' reproduce this on my machine. Besides, your screenshot shows the frametime, not FPS. Are you aware of that? 16.7ms (or ≈17ms) corresponds to 60 FPS.

I vote to close the issue. If anything, this needs to be reported to Chromium.

**Comment by osov** [comment] 2019-10-10 12:58
> Besides, your screenshot shows the frametime, not FPS. Are you aware of that?
Yes. under normal conditions on other demos it shows me 1-2 ms.

**Comment by Mugen87** [comment] 2019-10-10 13:18
> Yes. under normal conditions on other demos it shows me 1-2 ms.

So you have a framerate of 1000 FPS?!?

**Comment by osov** [comment] 2019-10-10 14:18
No, 60 FPS. 1-2ms.

**Comment by mrdoob** [comment] 2019-10-11 07:46
So the issue here is that @osov was not understanding that 17ms ≈ 60fps, correct?

**Comment by Mugen87** [comment] 2019-10-11 09:21
I'm not sure. The stats from his performance measurement (https://imgur.com/n7O7GZK) looked indeed strange. However, I could not reproduce this on my iMac.

**Comment by manthrax** [comment] 2019-10-16 14:17
I am having a similar issue on windows chrome.

![image](https://user-images.githubusercontent.com/350247/66927241-53431d00-efe4-11e9-9fee-21fb7082efe9.png)

There's the performance graph showing linearRampToValueAtTime dominating the frame time.

If I pause the app at renderer.render() and remove the audioListener from my scene.. the frametime goes back to 60hz.

Looking at the code, I have some ideas about what could be going wrong... and that the API design might be trying to solve an impossible problem, or at least trying to automate something inherently troublesome.

**Comment by Mugen87** [comment] 2019-10-16 14:30
Do you have the same issue with Firefox?

**Comment by FlorentMasson** [comment] 2020-05-19 15:34
I can confirm I have this issue too (on Windows and Chrome OS)
It raises so slowly it needs a while to reach 16ms on a powerful computer and then, affect framerate.
Here's an update to @Mugen87's fiddle showing rendering time in ms (averaged over 5s).
https://jsfiddle.net/mk1wauvp/12/
It takes about 3 minutes for me to go from 0.5ms to 1ms (the tab needs to be in foreground obviously)

**Comment by BeardScript** [comment] 2020-07-12 20:34
Hello! I can confirm I have the same issue with PositionalAudio as well. Normal Audio has no issues it seems. With offscreen canvas it helps to make it less painful on PC but on Android is really bad in both Edge and Chrome. Firefox has persistently bad performance but not incremental and not related to this. On PC neither Firefox nor Edge show this issue, being the later the one which provides the smoothest experience overall.

I really need this so if there's something we can do on three.js end I'd be happy to help.

**Comment by Mugen87** [comment] 2020-07-13 21:21
I have investigated this issue today and I believe I have found the root cause. There seems to be a drop in performance if `linearRampToValueAtTime()` is called with a suspended audio context. If the audio context is properly started with a use interaction, there is no performance issue on my system. Here are both fiddle for comparison (iMac + Chrome):

Bad: https://jsfiddle.net/mk1wauvp/12/
Good: https://jsfiddle.net/1j798645/

Notice how the "bad" fiddle produces the warning:

> The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page.

@mrdoob I'm unsure how to proceed from this point. I'm not sure what's happening under the hood but for some reasons the browser has problems with proceed `linearRampToValueAtTime()` calls when the audio context is suspended. At first glance, it looks like a browser bug. However, we could handle this on engine level by checking `this.context.state` and only invoke the Web Audio API if its value is `running`. What do you think?

**Comment by BeardScript** [comment] 2020-07-14 00:21
Thank you so much for looking into this @Mugen87. I can confirm that I don't see any issues in the "Good" demo (Windows + Chrome). I've done some testing as well and I've found that, at least with an Audio object, if the listener is referenced within it but is not present in the scene, there are no issues. I haven't tested this with PositionalAudio though.

**Comment by hoch** [comment] 2020-07-16 15:54
This sounds like a bug, or something we can improve in Chrome. Could anyone file an issue on crbug.com (with `Bad` link above) and cc me (hongchan@chromium)?

**Comment by Mugen87** [comment] 2020-07-16 16:28
Done: https://bugs.chromium.org/p/chromium/issues/detail?id=1106389

Sorry, I don't know how to add your email to the bug report.

**Comment by hoch** [comment] 2020-07-16 16:37
No worries. You added Blink>WebAudio component correctly! Thank you for filing the issue and we will investigate.

**Closed** 2020-08-17 02:37 UTC
Labels: Browser Issue, Bug
