### ISSUE TITLE
WebGL2 asynchronous readback implementation.

### ISSUE THREAD

**Issue by sciecode** [mrdoob/three.js#23550] opened 2022-02-21 19:21 UTC
While working on the `EXRExporter` implementation, I realized that we do not have an option for async readbacks using `gl.readPixels`. This option becomes available on WebGL2 contexts with specialized fencing for determining when data is ready to be read, and a new buffer type of `PIXEL_PACK_BUFFER`.

I can't overstate how important this feature is. It's used in plenty of real user applications, from gpu-picking, render processing, general purpose GPU computing, so on and so forth. The main setback for most of these is how WebGL1 readPixels blocking nature completely kills performance and use in real-time applications.

[MDN WebGL best practices](https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/WebGL_best_practices#use_non-blocking_async_data_readback) has a great section about how this process can be done. I believe we should be looking into integrating this alternative workflow into our GL2 renderer.

The main concern is introducing fences for the first time into threejs' workflow. We could just handle specific fences on methods that expect them. or we could setup a proper internal interface for fences that could be expanded and used in other aspects of the library, like shader linking and compiling, framebuffer completing, etc. However, that's a much larger endeavour.

I'm willing to work on a PR for this feature, but I would like to discuss options and decide what's the best course of action. So I encourage others to chime in with suggestions.

**Comment by Mugen87** [comment] 2022-02-22 08:36
Seems this is a duplicate of #22779.

**Closed** 2022-02-22 12:49 UTC
Labels: Enhancement, WebGL2
