### ISSUE TITLE
Sprite: Raycasting with offscreen sprites fails

### ISSUE THREAD

**Issue by Mugen87** [mrdoob/three.js#14624] opened 2018-08-02 20:50 UTC
##### Description of the problem

A user in the forum reported a bug in `Sprite.raycast()`.

https://discourse.threejs.org/t/problematic-raycasting-of-offscreen-three-sprite-object/3644

The method depends on `Object3D.modelViewMatrix`. But this matrix is only updated if the sprite is actually rendered. If not, `modelViewMatrix` does not regard the actual object's transformation. This means that `Sprite.raycast()` detects intersections of sprites outside the view frustum.

https://github.com/mrdoob/three.js/blob/1ffaa41a4b5f053ad62da1682844b53b041e63ca/src/objects/Sprite.js#L99

##### Three.js version

- [x] Dev
- [x] r95
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment] 2018-08-02 20:51
Test case: https://jsfiddle.net/f2Lommf5/10724/

**Comment by 06wj** [comment] 2018-08-03 07:26
The problem is how to get the reference of the camera to calculate ```modelViewMatrix```.

**Comment by Mugen87** [comment] 2018-08-03 07:58
One solution is to calculate `modelViewMatrix` for sprites in `projectObject()`.

**Comment by Mugen87** [comment] 2019-05-09 19:17
Another user ran into this bug: https://discourse.threejs.org/t/cannot-get-the-object-of-the-click/7451

Unfortunately, I can't think of another "easy" fix than proposed in #14679.

**Comment by WestLangley** [comment] 2019-05-09 20:02
I would not consider this a bug if user is frustum-culling the sprite.

The user should set:
```js
sprite.frustumCulled = false;
```
if the user expects raycasting to work on a sprite outside of the frustum.

**Comment by Sayid1** [comment] 2019-05-10 01:32
> I would not consider this a bug if user is frustum-culling the sprite.
> 
> The user should set:
> 
> ```js
> sprite.frustumCulled = false;
> ```
> 
> if the user expects raycasting to work on a sprite outside of the frustum.

How do you konw a sprite at outside of the frustum?

**Comment by Mugen87** [comment] 2019-05-10 10:14
> I would not consider this a bug if user is frustum-culling the sprite.

I don't think so. The fiddle from the forum clearly demonstrates a bug since `Raycaster.intersectObjects()` returns intersections although the ray visually misses all objects. The problem is that sprites outside the view frustum have an initial `modelViewMatrix` which lead to the wrong result.

**Comment by WestLangley** [comment] 2019-05-10 17:16
Thanks, @Mugen87. I agree with you that generating false positives is not acceptable.

Is it true that sprite raycasting works correctly when `sprite.frustumCulled = false;`?

**Comment by Mugen87** [comment] 2019-05-10 18:33
Yes, that is correct.

**Comment by WestLangley** [comment] 2019-05-10 20:29
Raycasting does not require a camera, obviously, but raycasting against a sprite only makes sense if it is with respect to a camera. So we have a design limitation.

The only solutions I can think of seem hacky to me, but then again, what is hacky is subjective.

Setting `sprite.frustumCulled = false;` is a work-around, but I agree with @Mugen87 that is not very appealing.

**Comment by Mugen87** [comment] 2019-05-11 09:39
> The only solutions I can think of seem hacky to me, but then again, what is hacky is subjective.

Can you please explain your solution? I'm afraid this issue will frequently pop up and I do prefer a fix in the library. #14679 would definitely work.

**Comment by WestLangley** [comment] 2019-05-11 14:53
>The only solutions I can think of seem hacky to me
>>Can you please explain your solutions?

1. Pass camera to raycast.

2. Add `sprite.supportRaycast` flag.

3. #14679 - not really appealing to me - most sprites do not require raycast support.

Also, this `Sprite.raycast()` code is computing `camera.matrixWorld`.
```js
viewWorldMatrix.getInverse( this.modelViewMatrix ).premultiply( this.matrixWorld );
```
It would be nice if that code could be replaced.

**Comment by Mugen87** [comment] 2019-05-11 15:39
I vote for option 1 then.

**Comment by 06wj** [comment] 2019-05-11 15:46
I vote for 1 too.It will also fix #14936

**Comment by WestLangley** [comment] 2019-05-11 20:21
@06wj Do you want to propose a PR, since you have been working on this issue?

**Comment by WestLangley** [comment] 2019-05-11 20:35
Oh man, this is really going to be ugly IMO, but I won't fight it because I don't have a better solution...

Maybe option 3 is better after all...

**Comment by Mugen87** [comment] 2019-05-12 09:33
Unfortunately, option 3 does not fix #14936. Sooner or later this issue will also be reported by users.

@06wj A PR with option 1 would be great 😊

**Comment by 06wj** [comment] 2019-05-13 03:10
https://github.com/mrdoob/three.js/blob/93e72ba7b24958ddb0652bd33171edd14ed2d693/src/core/Raycaster.js#L96

Should ```raycaster.intersectObject``` add```camera``` param?

**Comment by WestLangley** [comment] 2019-05-13 04:10
>Should raycaster.intersectObject add camera param?

I don't think so. I experimented with #16423 and it seems to work -- but it was just a quick test...

**Comment by WestLangley** [comment] 2019-06-06 19:48
Closing. Should be fixed in #16423.

**Closed by WestLangley** 2019-06-06 19:48 UTC
Labels: Bug
