### ISSUE TITLE
Meshes render incorrectly on Chrome Windows

### ISSUE THREAD

**Issue by migsantos121** [mrdoob/three.js#17431] opened 2019-09-05 01:25 UTC
##### Description of the problem

I have built a three.js sphere mesh and it looks good on MacOS chrome browser. like below.
![image](https://user-images.githubusercontent.com/36492625/64304534-7a8ddf80-cf8c-11e9-863f-e39f7eeafd28.png)

but it crashes and shows strange object in Windows Chrome browser.
![image (2)](https://user-images.githubusercontent.com/36492625/64304581-b0cb5f00-cf8c-11e9-8650-590cfad2ba13.png)

I have checked all the mesh details including the geometry and material, but all the values are exactly the same.
What's wrong with the Windows?

Could you please help?

##### Three.js version

- [ ] Dev
- [ ] r108
- [x] r106

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [x] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment] 2019-09-05 08:55
Maybe a corrupt GPU driver? Does it also happen with Firefox? What version of Windows and what GPU are you using?

**Comment by Mugen87** [comment] 2019-09-10 08:59
Closing due to lack of feedback from the OP.

**Comment by migsantos121** [comment] 2019-09-10 10:09
> Maybe a corrupt GPU driver? Does it also happen with Firefox? What version of Windows and what GPU are you using?

Thanks for the update, @Mugen87 
No corrupt GPU driver.
I already tested with several different computers that are used for graphical purpose.
The results are same.
It also happens with Firefox.
Windows 10, and Nvidia are used for the computers.

**Comment by Mugen87** [comment] 2019-09-10 10:28
So even this example is not rendered correctly?

https://threejs.org/examples/webgl_geometry_cube

We need a test cases in order to reproduce the issue. Consider to provide a [live example](https://jsfiddle.net/f2Lommf5/) that demonstrates the issue if the mentioned example does work.

**Comment by mrdoob** [comment] 2019-09-11 05:43
We also need to know the specific **graphics card model** you're using and the what **driver version** you are running.

**Comment by migsantos121** [comment] 2019-09-11 14:14
graphics model is not a problem.
This is caused after I add the SSAOPass to the project.

**Comment by migsantos121** [comment] 2019-09-11 14:14
Before I add SSAOPass, everything is perfect.
But after I add ssaopass, it doesn't affect any ssao features but makes that ugly objects.
Can you please advice?

**Comment by migsantos121** [comment] 2019-09-11 14:15
```let ssaoPass: any = new SSAOPass( this.scene, this.camera, this.width, this.height )
    ssaoPass.kernelRadius = 32
    ssaoPass.minDistance = 0.001
    ssaoPass.maxDistance = 0.3
    ssaoPass.output = SSAOPass.OUTPUT.Depth
    ssaoPass.renderToScreen = true;```

**Comment by migsantos121** [comment] 2019-09-11 14:21
I have one question.
Should I use SSAOPass or SSAOShader?

**Comment by mrdoob** [comment] 2019-09-11 15:16
Closing as @migsantos121 clearly doesn't want to cooperate.

**Closed by mrdoob** 2019-09-11 15:16 UTC

**Comment by migsantos121** [comment] 2019-09-11 15:59
@Mugen87 @mrdoob 
Those examples work perfectly.
Only my project looks like that.

**Comment by migsantos121** [comment] 2019-09-11 16:08
![image](https://user-images.githubusercontent.com/36492625/64714558-2076a800-d4bf-11e9-89ba-2dee4605411c.png)
I copied the same ssaopass code from https://threejs.org/examples/webgl_postprocessing_ssao.
The result is this image. @Mugen87  @mrdoob

**Comment by migsantos121** [comment] 2019-09-11 16:11
And this what I am seeing from the original example: https://threejs.org/examples/webgl_postprocessing_ssao

![image](https://user-images.githubusercontent.com/36492625/64714790-8400d580-d4bf-11e9-9ec3-da3d52b0d0d5.png)

**Comment by migsantos121** [comment] 2019-09-11 16:13
SSAO doesn't work and it produces the glitches.

**Comment by mrdoob** [comment] 2019-09-11 16:15
Please, use the forum for help requests.

**Comment by migsantos121** [comment] 2019-09-11 16:20
How to use it?

**Comment by mrdoob** [comment] 2019-09-11 16:33
https://discourse.threejs.org/
