### ISSUE TITLE
Couldn't create Texture from resized DOM Image

### ISSUE THREAD

**Issue by akella** [mrdoob/three.js#23164] opened 2022-01-06 23:54 UTC
**Describe the bug**
If the DOM image is resized with CSS, like: `width: 10%`, and you try to create texture with THREE.Texture(DOM_ELEMENT) class, that will result in:
```GL ERROR :GL_INVALID_VALUE : glTexSubImage2D: bad dimensions.```
The behaviour appears since v135. It is not present in v134.

**To Reproduce**

1. Create a DOM image in HTML
2. Resize it with CSS: img{width: 10%}
3. Create a texture from image with THREE.Texture(DomElement) class
4. Use texture on any material
5. You will get: GL ERROR :GL_INVALID_VALUE : glTexSubImage2D: bad dimensions. in latest Chrome.

***Code***

```js
  let material = new THREE.MeshBasicMaterial();
  let img = document.querySelector('img')
  let texture = new THREE.Texture(img)
  texture.needsUpdate = true;
  material.map = texture;
  mesh = new THREE.Mesh( geometry, material );
  scene.add( mesh );
```

***Live example***

* ~[jsfiddle-latest-release](https://jsfiddle.net/akella/roncdu7g/1/) (forgot to set display:block here, hence new demo)~
* [bug](https://jsfiddle.net/akella/roncdu7g/4/)

**Expected behavior**

To see sphere with kitten texture.

**Screenshots**

This is the expected result of demo.
<img width="409" alt="Screenshot 2022-01-07 at 01 51 56" src="https://user-images.githubusercontent.com/76031/148468670-a5a25c9e-9764-4a82-b219-f9ded762ef2a.png">

**Platform:**

 - Device: Desktop
 - OS: MacOs
 - Browser: Chrome
 - Three.js version: r136

**Comment by Mugen87** [comment] 2022-01-07 08:31
As stated in the [docs](https://threejs.org/docs/index.html#api/en/textures/Texture), the dimensions of a texture can not be changed after its initial use. This policy was introduced with `r135`.

You have to create a new texture with the resized image and call `dispose()` on the previous texture object.

**Comment by akella** [comment] 2022-01-07 08:46
Thank you for fast response! But just to be clear, what does this mean exactly in CSS context?
Its not like i resize texture after its being created. The error is present even with **inline CSS**. So you can not create a texture from this DOM element:
```<img src="img/3.jpg" style="width:10%" alt="">```
Could you help with general approach advice, at which point to actually dispose and re-create texture in this case?

**Comment by Mugen87** [comment] 2022-01-07 09:17
Oh okay, the issue is now more clear.

After a second look, it seems this kind of image scaling is not supported with the new WebGL 2 texture API anymore. The data buffer is smaller than the actual image dimension which is actually invalid.

**Comment by Mugen87** [comment] 2022-01-07 09:18
Sorry, but it was necessary to trade some flexibility for more modern code paths.

**Comment by MickeyMiao7** [comment] 2022-01-07 09:20
> Oh okay, the issue is now more clear.
> 
> After a second look, it seems this kind of image scaling is not supported with the new WebGL 2 texture API anymore. The data buffer is smaller than the actual image dimension which is actually invalid.

Hi, I take a look at it. Does it make sense to use the original size of image for gl.texStorage2D.

```

				if ( useTexStorage ) {

					if ( allocateMemory ) {

						state.texStorage2D( _gl.TEXTURE_2D, levels, glInternalFormat, **image.naturalWidth, image.naturalHeight** );

					}

					state.texSubImage2D( _gl.TEXTURE_2D, 0, 0, 0, glFormat, glType, image );

				} else {

					state.texImage2D( _gl.TEXTURE_2D, 0, glInternalFormat, glFormat, glType, image );

				}
```

**Comment by akella** [comment] 2022-01-07 09:22
@MickeyMiao7 Yes, definitely! I think in general people would like to use original texture size. If not they could use getBoundingClientRect to get the CSS one anyway.  
Thats what i've been doing with this case myself.

**Comment by Mugen87** [comment] 2022-01-07 09:26
@MickeyMiao7 I'm not sure about the side effects of such a change. Honestly, I would prefer to not support this use case at all.

**Comment by MickeyMiao7** [comment] 2022-01-07 09:30
> @MickeyMiao7 I'm not sure about the side effects of such a change. Honestly, I would prefer to not support this use case at all.

ok, i understand. 

Anyway, it seems annoying that `texSubImage2D` does support the image scaling but `texStorage2D` only supports to use **a fixed size of image**, that is why this problem occurs:
https://developer.mozilla.org/en-US/docs/Web/API/WebGL2RenderingContext/texStorage2D
https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/texSubImage2D

**Comment by akella** [comment] 2022-01-07 09:33
i will just add my 2c: the current change from v135 is actually breaking a lot of code. 
Common use case: Converting DOM Images into WebGL layer to animate them. With this case you have images in HTML, and you convert them to textures, and now it doesnt work if you have any sizing CSS applied to them. Which will *always* be because web is responsive now. So this makes texture creation from DOM element kind of useless in most cases, does it?

What would be the alternative way? To copy all the <img> into hidden DIV and strip all CSS from them before converting to Texture?

**Comment by Mugen87** [comment] 2022-01-07 09:46
It's best if you always derive the dimensions of the texture from its image data (meaning what is assigned to `src`).

**Comment by akella** [comment] 2022-01-07 10:45
> It's best if you always derive the dimensions of the texture from its image data (meaning what is assigned to `src`).

This means @MickeyMiao7 fix is good, right? To use image.naturalWidth instead if width and fix this case?

**Comment by Mugen87** [comment] 2022-01-07 10:48
I'm not sure about this, sorry. The real problem to me is the usage of CSS to modify texture dimensions.

**Comment by akella** [comment] 2022-01-07 10:55
could asking other developers on discord be a way to make up a decision? For me as one of three.js dev-users it is obvious that i expect three.js to disregard any CSS, when i convert DOM element to WebGL Texture. And my hypothesis is its like that for 99% people. 
Because those are two different mental models/concepts/coordinate-systems, and i dont want them to interfere.

What are the possible drawbacks of using naturalWidth here?

**Comment by WestLangley** [comment] 2022-01-07 14:55
This approach appears to work regardless of the CSS.

https://jsfiddle.net/wh9g0dqn/

@Mugen87 Any idea what is going on?

**Comment by Mugen87** [comment] 2022-01-07 15:36
No sorry. Seems both fiddles use different browser code paths for image processing.

**Comment by Mugen87** [comment] 2022-01-07 15:43
Reopening until the difference in behavior is understood.

**Comment by mrdoob** [comment] 2022-01-07 19:47
It seems like using `image.naturalWidth` should be safe?
https://stackoverflow.com/questions/28167137/whats-the-difference-between-width-naturalwidth-and-clientwidth

**Comment by Mugen87** [comment] 2022-01-07 21:00
The mentioned code path in `WebGLTextures` is not only relevant for `HTMLImageElement`. `ImageBitmap` also uses it which has no `naturalWidth` and `naturalHeight` properties.

It might be also necessary to update other logic in `WebGLTextures` like the resize logic for WebGL 1. Working with two different image dimension properties tends to be more error prone so a change must verify many uses cases.

**Comment by mrdoob** [comment] 2022-01-07 21:39
Hmm.... `image.naturalWidth || image.width`? 😅

It sure makes things a bit more complicated...

**Comment by ranbuch** [comment] 2022-04-13 13:12
Happened for me when `ImageBitmapLoader` loaded a texture from cache, in case it helps anyone.

**Comment by gfnool** [comment] 2022-05-17 15:55
Any news about this issue?
Or any workaround to prevent the second load from TextureLoader?

@akella are you using any fix on your side? 

Thanks!

**Comment by gfnool** [comment] 2022-05-18 08:16
Thanks @akella!

The first way is similar to use THREE.TextureLoader, and in both we're still having the problem of a possibile double request if the browser had already loaded the image.

What we're completely loosing is the advantage of using the srcset and letting the browser decide which is the correct image for that element at the given resolution and layout.

I guess I have to build something custom to find the correct candidate from a srcset string and hide the image to prevent the initial load of the image.

**Comment by monokee** [comment] 2022-11-03 18:17
> The mentioned code path in `WebGLTextures` is not only relevant for `HTMLImageElement`. `ImageBitmap` also uses it which has no `naturalWidth` and `naturalHeight` properties.
> 
> It might be also necessary to update other logic in `WebGLTextures` like the resize logic for WebGL 1. Working with two different image dimension properties tends to be more error prone so a change must verify many uses cases.

The current implementation is inconsistent because it doesn't work around the inconsistent property behaviour in the spec:

The `width` and `height` properties of both `HTMLCanvasElement` and `ImageBitmap` reflect the logical pixels of their intrinsic ImageData container.  Changing the display properties of a canvas via CSS does not affect its intrinsic `width` and `height` properties. 

The correct equivalents for HTMLImageElement are `naturalWidth` and `naturalHeight` because, like `width` and `height` for `HTMLCanvasElement` and `ImageBitmap`, these properties reflect the logical pixels of the intrinsic imageData and are not affected by changes in display logic.

I guess the question is whether or not Three.js should correct for this inconsistency by internally mapping `width` to `naturalWidth` and `height` to `naturalHeight` when `image instanceof HTMLImageElement`, instead of using `image.width` and `image.height` regardless of the constructor.

**Comment by robpataki** [comment] 2023-10-13 10:09
I have exactly this issue when trying to load images from the DOM as textures in **r157** (same scenario as @akella's using THREE.Texture). I am surprised that under the bonnet Three is thrown due to some CSS applied to the image - as @mrdoob suggested I agree that image.naturalWidth and image.naturalHeight should be used instead the current mechanism - it would be amazing to see a fix for this.

**Closed** 2024-02-26 11:03 UTC
Labels: Enhancement
