### ISSUE TITLE
Mirrored textures in latest chrome / threejs

### ISSUE THREAD

**Issue by demanzonderjas** [mrdoob/three.js#16027] opened 2019-03-21 09:32 UTC
##### Description of the problem

All textures are loaded in mirror. 
![Screenshot 2019-03-21 at 10 28 40](https://user-images.githubusercontent.com/18641723/54743330-2355a780-4bc4-11e9-8a4a-ad6bf9a349ac.png)

When I switch to the 103dev version, this doesn't happen:
![Screenshot 2019-03-21 at 10 29 46](https://user-images.githubusercontent.com/18641723/54743389-4b450b00-4bc4-11e9-9fa3-2d4eda99ad10.png)

Super weird, right?

##### Three.js version

THREE.JS version: 102

##### Browser

Chrome: Version 72.0.3626.121 - It doesn't happen in Firefox.

##### OS

macOS Mojave 10.14.3

**Comment by Mugen87** [comment] 2019-03-21 10:09
Thanks for reporting! However, your issue is another duplicate of #15896

Definitely fixed with the next release `R103`. (Or you just use the current `dev` version).

**Closed by Mugen87** 2019-03-21 10:09 UTC

**Comment by demanzonderjas** [comment] 2019-03-21 10:55
Ah apologies, didn't think of the word flip when checking the existing issues. Thanks for fixing it.
