### ISSUE TITLE
CSS3DRenderer issue on Chrome, depending on camera position.

### ISSUE THREAD

**Issue by novogrammer** [mrdoob/three.js#11135] opened 2017-04-05 11:25 UTC
iframe is not displayed depending on camera position.
![css3drenderer_chrome01](https://cloud.githubusercontent.com/assets/912810/24703012/4c23b1a4-1a3c-11e7-84cd-da4039247152.png)

Even DOM elements are not displayed in the lower part.
![css3drenderer_chrome02](https://cloud.githubusercontent.com/assets/912810/24703018/5422f89c-1a3c-11e7-952b-58c92f328922.png)

It looks like Chrome's paint invalidation calculation is failed.

http://codepen.io/novogrammer/pen/LWMQxd
Setting GO_WRONG_WITH_CHROME to false will work fine.

##### Three.js version

- [x] Dev
- [x] r84

##### Browser

- [x] Chrome

##### OS

- [x] macOS

**Comment by Mugen87** [comment] 2017-04-05 16:00
Maybe @yomotsu can help here.

**Comment by mrdoob** [comment] 2017-04-05 16:40
I can reproduce in Chrome 57.0.2987.133.
Seems to be fixed in Chrome Canary though! (59.0.3063.0)

**Comment by Mugen87** [comment] 2017-04-05 16:44
> Seems to be fixed in Chrome Canary though! (59.0.3063.0)

I can confirm that! 😊

**Comment by yomotsu** [comment] 2017-04-05 16:50
Reproduce even in Chrome for windows.

Seems chrome can not handle of elements are far...
![default](https://cloud.githubusercontent.com/assets/212837/24716500/3449a51a-1a6a-11e7-85ff-b9400198cf33.PNG)

IE mode (flat mode) can be quick workaround.
![2](https://cloud.githubusercontent.com/assets/212837/24716762/ff2a0450-1a6a-11e7-896c-795b65ecc381.PNG)

see
http://codepen.io/anon/pen/bqJQmV?editors=1010

@mrdoob Should CSS Renderer take "mode" option?

**Comment by yomotsu** [comment] 2017-04-05 16:55
actually flat mode can solve other issues. such as sprites blinking on Firefox.

**Comment by novogrammer** [comment] 2017-04-26 14:22
Thank you all!
It was fixed in Chrome Stable.
58.0.3029.81 (64-bit)

<img width="378" alt="2017-04-26 23 13 43" src="https://cloud.githubusercontent.com/assets/912810/25439061/5925a0e2-2ad6-11e7-9de3-cbc3cc340623.png">

**Closed** 2017-04-26 14:27 UTC
Labels: Bug
