### ISSUE TITLE
Mipmaps are not generated correctly

### ISSUE THREAD

**Issue by devotwo** [mrdoob/three.js#11503] opened 2017-06-13 15:59 UTC
##### Description of the problem 

To reproduce this issue 
- Create PlaneGeometry
- Upload any non-power of 2 texture eg 1600 x 1200

When mipmaping is disabled:
material.map.minFilter = THREE.LinearFilter;
material.map.magFilter = THREE.LinearFilter;
texture is displayed properly.

When mipmapping is enabled (default) , looking close up (first mipmap) is looks ok, with angel, distance texture looks wrong, mipmaps are scaled, stretched.

Textures 1024 x 1024 are working properly.

As far as we can see problem occurs only on Windows 7 64bit and Chrome. In Internet Explorer works fine.
Tested in latest version of Three.js editor r85 but issue is present in other versions (tested r77).

Disabled mipmaps
![img_13062017_172239_0](https://user-images.githubusercontent.com/29403180/27091471-801b05b6-5060-11e7-929b-7392194ba642.png)

Enabled mipmaps (default)
![img_13062017_171942_0](https://user-images.githubusercontent.com/29403180/27091470-80133f16-5060-11e7-9822-e9261a2b8dee.png)

##### Three.js version

- [ ] Dev
- [x] r85
- [x] r77

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows 7 64 bit
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)
Intel Core i7 , Nvidia 1080 GTX
Chrome Version 58.0.3029.110 (64-bit)

**Comment by mrdoob** [comment] 2017-06-13 17:54
Could you create a jsfiddle?

**Comment by mrdoob** [comment] 2017-06-13 17:56
Seems to be a duplicate of #11466 actually.

**Comment by mrdoob** [comment] 2017-06-13 18:01
Could you create a jsfiddle though?

**Comment by devotwo** [comment] 2017-06-14 12:16
Sorry, it may be  duplicate of #11466 

jsfiddle: 
https://jsfiddle.net/kdkjrte8/20/

Just upload texture NPOT. When mipmaping is enabled we get incorrect results.

**Closed** 2017-06-15 10:15 UTC
Labels: Duplicate
