### ISSUE TITLE
MeshPhysicalMaterial.aoMap does not contribute to envMap occlusion 

### ISSUE THREAD

**Issue by arodic** [mrdoob/three.js#20448] opened 2020-10-01 22:35 UTC
MeshPhysicalMaterial.aoMap does not contribute to envMap occlusion 

1. Go to https://threejs.org/examples/webgl_materials_displacementmap.html
2. Remove ambient intensity and increase roughness and environment intensity to max.
3. Notice that occlusion map is not visible like it is with ambient lighting.

Similar issues have emerged before like #8107 fixed by #8152 and possibly others.

Perhaps I'm unaware and this is expected behavior. But I imagine ambient occlusion should also occlude environment map. At least when the surface completely diffuse when the physics of light is pretty much the same as ambient lighting.

<img width="1263" alt="Screen Shot 2020-10-02 at 1 43 16 PM" src="https://user-images.githubusercontent.com/708984/94968182-5402e680-04b5-11eb-8c5b-081baab80506.png">

**Comment by mrdoob** [comment] 2020-10-06 07:12
I think I recall @WestLangley saying that `aoMap` shouldn't affect `envMap`, but maybe my memory is failing me.

**Comment by Mugen87** [comment] 2020-10-07 13:31
Duplicate of #8107.

**Comment by donmccurdy** [comment] 2020-10-08 02:40
Related: https://github.com/KhronosGroup/glTF/issues/915. An envMap's diffuse lighting contributions should be affected by aoMap, specular contributions should not.

**Closed** 2020-10-09 07:43 UTC
