### ISSUE TITLE
Adreno 300 series GPU black texture flickering

### ISSUE THREAD

**Issue by gauravrane** [mrdoob/three.js#9988] opened 2016-11-02 08:58 UTC
When loading the website on an Android phone with a Adreno 300 series, get a weird black glitch in diffuse textures causing black flickering. I am using MeshPhongMaterial for the meshes with point lights.

The same is reproduced in the threejs examples from the website, which i am giving links for instead of a jsfiddle.
[https://threejs.org/examples/?q=texture#webgl_materials_texture_filters](url)
[https://threejs.org/examples/?q=texture#webgl_materials_texture_manualmipmap](url)

Screenshots - 
![motog3](https://cloud.githubusercontent.com/assets/5513319/19922029/b463684a-a106-11e6-9742-7a7d08944680.jpg)
![oneplusx_2](https://cloud.githubusercontent.com/assets/5513319/19922034/c58f52dc-a106-11e6-9798-38f84dbca52f.jpg)

From my application -
![car_1](https://cloud.githubusercontent.com/assets/5513319/19922246/c9a07e90-a107-11e6-97ab-febb4c377db1.jpg)
![car_2](https://cloud.githubusercontent.com/assets/5513319/19922252/cfdcf3ec-a107-11e6-91bf-c6f7e5dbf8c8.jpg)

In my project, the floor outside which is a Plane Geometry does not have this issue. Only the mesh I have loaded using the SEA3d loader.
![car_3](https://cloud.githubusercontent.com/assets/5513319/19928866/821105ee-a126-11e6-8e1c-582d59f0aac3.jpg)

Strangely there was no issue when viewing the anisotropy example too.

It is a major issue because a lot of phones use Adreno 300 series GPU's. 

##### Three.js version

- [ ] Dev
- [x] r81
- [ ] ...

##### Browser

- [] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [] All of them
- [ ] Windows
- [ ] Linux
- [x] Android
- [ ] IOS

##### Hardware Requirements (graphics card, VR Device, ...)
Tested with the following android devices. Work fine on other GPU series.
Oneplus X - Adreno 330
Moto G3 - Adreno 306
Moto G2 - Adreno 305

**Comment by mrdoob** [comment] 2016-11-02 23:35
Have you tried with Android's Chrome Dev, Chrome Canary and Firefox?

**Comment by gauravrane** [comment] 2016-11-03 06:21
Same results with Chrome Dev, Canary and Firefox as well.

**Comment by mrdoob** [comment] 2016-11-05 00:01
@kenrussell is this a known issue?

**Comment by kenrussell** [comment] 2016-11-05 04:39
@mrdoob it's hard to know. As you remember we filed ~4 driver bugs with Qualcomm against the Adreno 330 last year - the GPU in the Nexus 5. We were told that that device was not going to receive the Android N update, so no graphics driver updates, and the bugs were closed as "won't fix".

I don't remember exactly which of the WebGL conformance tests in https://github.com/KhronosGroup/WebGL/tree/master/sdk/tests/conformance/glsl/bugs were created for these cases.

If this is a serious issue then I recommend iteratively simplifying the shader and figuring out what part of it is executing incorrectly on the Adreno 300 series GPUs. This would only be in order to figure out a workaround -- there is no point in filing a driver bug about it since the driver will never be updated. We will gladly add a reduced test case to the WebGL conformance suite if you can come up with one and if it doesn't already exist.

**Comment by gauravrane** [comment] 2016-11-05 10:49
@mrdoob it seems that adding a normal map to the phong material is causing the issue in my project on some meshes. The flicker still exists on the other materials, Basic and Lambert as well unlike my initial observations. I have tested with a lot of devices with the 300 series GPU just to be sure.

**Comment by mrdoob** [comment] 2016-11-05 23:41
Does this example render correctly on those devices?
https://threejs.org/examples/#webgl_materials_normalmap

**Comment by gauravrane** [comment] 2016-11-06 07:48
Yes so far it is rendering fine without any flicker for this link.

**Comment by gauravrane** [comment] 2016-11-07 15:21
Any chance there's a workaround for this ?

**Comment by mrdoob** [comment] 2016-11-07 16:42
The example I mentioned uses `MeshPhongMaterial` and `normalMap`. If that one renders fine then we need to find what's the actual reason the glitches appear.

**Comment by gauravrane** [comment] 2016-11-07 19:19
I am using MeshPhongMaterial with a normalMap for the render. How do we go about identifying the reason for the glitch ?

**Comment by mrdoob** [comment] 2016-11-07 20:05
Basically enabling/disabling things. Compare how is your code different from the one in the example

**Comment by gauravrane** [comment] 2016-11-08 03:27
At the moment, short of using a different format for loading my meshes, i cannot think of anything. Will still test and keep you updated. Currently I am using the Open3DGC for SEA3D loader for the extra compression.

**Comment by mrdoob** [comment] 2016-11-08 17:16
@sunag any ideas?

**Comment by sunag** [comment] 2016-11-08 19:17
@gauravrane You can send me the door in `.sea` with `Normal Map` for me to do some tests?

**Comment by gauravrane** [comment] 2016-11-09 06:23
Hi @sunag , here is the file with the normal map included. In the project i am not adding the map directly onto the object and exporting, instead applying a custom material at runtime. I tried using this object on the Adreno 330 with only the normal map exported from the SEA3d exporter but was getting the same results. One observation though, at a certain angle of the camera the flicker seems to disappear (ideally when the object and camera are almost in a straight line) but all other angles its still present. I am using Orbitcontrols for the camera controller.

[L_Door_inside.zip](https://github.com/mrdoob/three.js/files/580046/L_Door_inside.zip)

**Comment by sunag** [comment] 2016-11-09 14:17
Hi @gauravrane 

I fix the problem in `webgl_materials_texture_filters` disabling `antialiasing`.
Another thing I noticed is some GPU not initializes `webgl` context with `antialiasing` enabled.

![Fixed with antialiasing disabled](https://cloud.githubusercontent.com/assets/5513319/19922034/c58f52dc-a106-11e6-9798-38f84dbca52f.jpg)

**Comment by gauravrane** [comment] 2016-11-09 17:46
@sunag @mrdoob disabling `antialias ` also solves the issue with the fog distance. But it is a feature that will be required for the project. I have also tried the FXAA shader from the normalMap material example with the same results.
No luck with the texture filter example for me, though on an Adreno 330 it flickers and settles because the movement of the camera stops. On an Adreno 305/306 the flicker continues for a while.

**Comment by gauravrane** [comment] 2016-11-12 15:20
Hi guys, there has been no solution to this yet. Is there an alternate shader you could point me to, for use instead of phong, i'm very bad with shader programming. I am assuming that the main fix here will be changing the normal part of the shader.

**Comment by mrdoob** [comment] 2016-11-13 03:43
Sounds like for those GPUs we'll have to force disable antialias...

**Comment by gauravrane** [comment] 2016-11-13 17:18
But the normal map flicker still persists.

**Comment by bhouston** [comment] 2016-11-22 17:23
This is a duplicate of this bug: https://github.com/mrdoob/three.js/issues/9515  There is basically an issue with the physical shader somewhere.

**Comment by mrdoob** [comment] 2017-01-19 14:30
Seems to be kind of resolution dependent...
Setting `renderer.setPixelRatio( 1 )` reduces the glitch (Nexus 5 `devicePixelRatio` is `3`).

**Comment by gauravrane** [comment] 2017-05-22 12:13
Hey guys, as an update for a quick workaround i implemented normal calculation from the ShaderSkin file. It does not give accurate per pixel mapping, but it gets the job done for me.
If anyone is interested then here is the perturbNormal2Arb function 
`normal = perturbNormal2Arb( -vViewPosition );`
`	vec3 perturbNormal2Arb( vec3 eye_pos ) 
	{

		vec4 posAndU = vec4( -eye_pos, vUv.x );
		vec4 posAndU_dx = dFdx( posAndU ),  posAndU_dy = dFdy( posAndU );
		vec3 tangent = posAndU_dx.w * posAndU_dx.xyz + posAndU_dy.w * posAndU_dy.xyz;
		tangent += 0.00000001;
		vec3 thenormal = normalize( vNormal );
		vec3 binormal = normalize( cross( tangent, thenormal ) );
		tangent = cross( thenormal, binormal );
		mat3 tsb = mat3( tangent, binormal, thenormal );

		vec3 mapN = texture2D( normalMap, vUv ).xyz * 2.0 - 1.0;
		mapN.xy = normalScale * mapN.xy;
		mapN = normalize(mapN);

		return normalize( tsb * mapN );
	}`

**Comment by gauravrane** [comment] 2017-05-22 20:14
@mrdoob should we say that the per pixel tangent space calculation is causing the flicker and close this with the alternate solution ? Or is there another workaround expected based on observations.

**Comment by mrdoob** [comment] 2017-05-22 21:13
@gauravrane do you have a test link with and without your code that we can test?

**Comment by gauravrane** [comment] 2017-05-24 08:57
@mrdoob here are the links

[http://carconfigurator.in/test/brezza/r84.html](url) - With the original r84 
[http://carconfigurator.in/test/brezza/r84_edited.html](url) - With the above edited normal code.

Also attaching some screenshots, tested on a Nexus 5 (Adreno 330, android 7.1.1) One Plus X (Adreno 330, android 6.0.1) and Moto G3 (Adreno 306, android 6.0.1)

![1](https://cloud.githubusercontent.com/assets/5513319/26395118/c303d3fa-408c-11e7-9670-15881d46c8b7.jpg)
![2](https://cloud.githubusercontent.com/assets/5513319/26395180/ea4a8760-408c-11e7-8e69-08679c8c0410.jpg)


Strangely though where i am using a repeatable texture the issue does not come up with the unedited version.

![3](https://cloud.githubusercontent.com/assets/5513319/26395203/f8937a3e-408c-11e7-8542-6e245d52da7d.jpg)

**Comment by mrdoob** [comment] 2017-05-25 00:18
As a recap...

You've replaced  [normalmap_pars_fragment.glsl](https://github.com/mrdoob/three.js/blob/dev/src/renderers/shaders/ShaderChunk/normalmap_pars_fragment.glsl) `perturbNormal2Arb()`:

```js
vec3 perturbNormal2Arb( vec3 eye_pos, vec3 surf_norm ) {

	vec3 q0 = dFdx( eye_pos.xyz );
	vec3 q1 = dFdy( eye_pos.xyz );
	vec2 st0 = dFdx( vUv.st );
	vec2 st1 = dFdy( vUv.st );

	vec3 S = normalize( q0 * st1.t - q1 * st0.t );
	vec3 T = normalize( -q0 * st1.s + q1 * st0.s );
	vec3 N = normalize( surf_norm );

	vec3 mapN = texture2D( normalMap, vUv ).xyz * 2.0 - 1.0;
	mapN.xy = normalScale * mapN.xy;
	mat3 tsn = mat3( S, T, N );
	return normalize( tsn * mapN );

}
```

With this code from [ShaderSkin.js](https://github.com/mrdoob/three.js/blob/dev/examples/js/ShaderSkin.js#L426-L441):

```js
// normal mapping

"vec4 posAndU = vec4( -vViewPosition, vUv.x );",
"vec4 posAndU_dx = dFdx( posAndU ),  posAndU_dy = dFdy( posAndU );",
"vec3 tangent = posAndU_dx.w * posAndU_dx.xyz + posAndU_dy.w * posAndU_dy.xyz;",
"vec3 normal = normalize( vNormal );",
"vec3 binormal = normalize( cross( tangent, normal ) );",
"tangent = cross( normal, binormal );",	// no normalization required
"mat3 tsb = mat3( tangent, binormal, normal );",

"vec3 normalTex = texture2D( tNormal, vUv ).xyz * 2.0 - 1.0;",
"normalTex.xy *= uNormalScale;",
"normalTex = normalize( normalTex );",

"vec3 finalNormal = tsb * normalTex;",
"normal = normalize( finalNormal );",
```

With some modifications though:

```js
vec3 perturbNormal2Arb( vec3 eye_pos ) 
{

	vec4 posAndU = vec4( -eye_pos, vUv.x );
	vec4 posAndU_dx = dFdx( posAndU ),  posAndU_dy = dFdy( posAndU );
	vec3 tangent = posAndU_dx.w * posAndU_dx.xyz + posAndU_dy.w * posAndU_dy.xyz;
	tangent += 0.00000001;
	vec3 thenormal = normalize( vNormal );
	vec3 binormal = normalize( cross( tangent, thenormal ) );
	tangent = cross( thenormal, binormal );
	mat3 tsb = mat3( tangent, binormal, thenormal );

	vec3 mapN = texture2D( normalMap, vUv ).xyz * 2.0 - 1.0;
	mapN.xy = normalScale * mapN.xy;
	mapN = normalize(mapN);

	return normalize( tsb * mapN );
}
```

However, if `texture.wrapS` and(?) `texture.wrapT` are set to `THREE.RepeatWrapping` the existing code doesn't produce artifacts on these devices.

Correct?

**Comment by mrdoob** [comment] 2017-05-25 00:23
Reminds me that we have this work-around in [normal_fragment.glsl](
https://github.com/mrdoob/three.js/blob/dev/src/renderers/shaders/ShaderChunk/normal_fragment.glsl)

```glsl
	// Workaround for Adreno/Nexus5 not able able to do dFdx( vViewPosition ) ...

	vec3 fdx = vec3( dFdx( vViewPosition.x ), dFdx( vViewPosition.y ), dFdx( vViewPosition.z ) );
	vec3 fdy = vec3( dFdy( vViewPosition.x ), dFdy( vViewPosition.y ), dFdy( vViewPosition.z ) );
	vec3 normal = normalize( cross( fdx, fdy ) );
```

Could you try this code on those devices?

```glsl
vec3 perturbNormal2Arb( vec3 eye_pos, vec3 surf_norm ) {

	vec3 q0 = vec3( dFdx( eye_pos.x ), dFdx( eye_pos.y ), dFdx( eye_pos.z ) );
	vec3 q1 = vec3( dFdy( eye_pos.x ), dFdy( eye_pos.y ), dFdy( eye_pos.z ) );
	vec2 st0 = vec2( dFdx( vUv.s ), dFdx( vUv.t ) );
	vec2 st1 = vec2( dFdy( vUv.s ), dFdy( vUv.t ) );

	vec3 S = normalize( q0 * st1.t - q1 * st0.t );
	vec3 T = normalize( -q0 * st1.s + q1 * st0.s );
	vec3 N = normalize( surf_norm );

	vec3 mapN = texture2D( normalMap, vUv ).xyz * 2.0 - 1.0;
	mapN.xy = normalScale * mapN.xy;
	mat3 tsn = mat3( S, T, N );
	return normalize( tsn * mapN );

}
```

**Comment by mrdoob** [comment] 2017-05-25 00:42
My suspicion is that Adreno has issues with `dFdx` and `dFdy` used on `vec3`, but the problem doesn't apply with `float`, `vec2` and `vec4`.

**Comment by gauravrane** [comment] 2017-05-25 07:00
@mrdoob Yes, you're right. That was the issue the above code works perfectly, just one thing needs to get added to it is the line 
st0 += 0.0000001;
which is a quick fix for a UV problem, solution from  [#8901](https://github.com/mrdoob/three.js/issues/8901)

The artifacts are obvious and worse on mobile devices.
![accuracy](https://cloud.githubusercontent.com/assets/5513319/26439428/b6e940d2-4145-11e7-916c-65574a70e101.jpg)

**Comment by mrdoob** [comment] 2017-05-25 18:25
> @mrdoob Yes, you're right. That was the issue, the above code works perfectly, just one thing needs to get added to it is the line 
st0 += 0.0000001;

Does that only happen when `texture.wrapS` and/or `texture.wrapT` are set to `THREE.RepeatWrapping`?

**Comment by mrdoob** [comment] 2017-05-25 21:12
@gauravrane I think you should be able to achieve the same doing this:

```js
texture.offset.set( 0.0000001, 0.0000001 );
```

**Comment by mrdoob** [comment] 2017-05-25 21:28
Done! I've also added it to [bumpmap_pars_fragment.glsl](https://github.com/mrdoob/three.js/blob/dev/src/renderers/shaders/ShaderChunk/normalmap_pars_fragment.glsl)

**Closed** 2017-05-25 21:35 UTC

**Comment by mrdoob** [comment] 2017-05-25 22:37
By the way, I've looked into these artifact too...

![screenshot_20170525-232627](https://cloud.githubusercontent.com/assets/5513319/19922029/b463684a-a106-11e6-9742-7a7d08944680.jpg)

They have nothing to do with the Adreno bug, it's just an issue with 2 planes being too close to each other and the mobile not having enough precision on the depth buffer.
