### ISSUE TITLE
css3d label enlarged text is jagged，blur

### ISSUE THREAD

**Issue by xuchaozou** [mrdoob/three.js#27061] opened 2023-10-26 08:04 UTC
### Description

The css3d label can be rendered to the correct position in the scene. When the camera is far away from the label, the font of the label does not look blurred and there is no jagged feeling. However, when I move the camera to the label relatively close, the font of the label has obvious jagged feeling

### Reproduction steps

1.When the camera is close to the tag

### Code

```js
// code goes here
```

### Live example

The label works normally. When the camera is close, the label is fuzzy

### Screenshots

![J)~2XS(2Y$XK94X)0A@$7MS](https://github.com/mrdoob/three.js/assets/52873083/e544a7ba-5b38-481c-89f3-efca8838b98a)
![H%59`L$WF1)ME3%B}L157IT](https://github.com/mrdoob/three.js/assets/52873083/43fd1dd2-9730-46ce-a21d-6492f333cf74)

### Version

0.152.2

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by xuchaozou** [comment] 2023-10-26 08:04
i need to you help, thanks!!!

**Comment by Mugen87** [comment] 2023-10-26 08:51
I'm not sure this is related to #26950 but this is not the first time users complain about blurry text when using `CSS3DRenderer` or the CSS transform or translate3d properties in general (e.g. https://discourse.threejs.org/t/css3drenderer-gets-blurry-in-some-situations-what-might-be-the-problem/50179) . Multiple sources report this happens due to fractional numbers assigned to CSS properties. Rounding seems to solve the issue.

https://github.com/Leaflet/Leaflet/issues/6069

It would be interesting to see if the OPs issue could be fixed like that as well.

@xuchaozou Would you mind sharing a small live example that demonstrate the issue like in your screenshot? Use https://jsfiddle.net/g3atw6k5/ as a starter template.

**Comment by xuchaozou** [comment] 2023-10-26 08:57
css attribute allocation, which attribute should I change, is it to change his matrix matrix, or what? Please make it clear, I will test it, thank you

**Comment by xuchaozou** [comment] 2023-10-26 08:57
css attribute allocation, which attribute should I change, is it to change his matrix matrix, or what? Please make it clear, I will test it, thank you

**Comment by Mugen87** [comment] 2023-10-26 09:00
TBH, it's better if you share a live example first so it's possible for use to investigate the issue. It would be best to find a fix in `CSS3DRenderer` instead of applying individual patches to apps.

**Comment by xuchaozou** [comment] 2023-10-26 11:03
[https://jsfiddle.net/zouxuchao/epc6kb8g/4/](url)
This is a simple demo. As the camera gets closer to the tag, the tag starts to blur

**Comment by Mugen87** [comment] 2023-10-26 11:19
Slightly simplified example: https://jsfiddle.net/2xesczuw/1/

**Comment by Mugen87** [comment] 2023-10-26 11:21
When testing with Chrome, Firefox and Safari on macOS, only Chrome suddenly switches form a sharp to blurred text.

**Comment by Mugen87** [comment] 2023-10-26 11:31
@xuchaozou The following fiddle is a simple hack that rounds all elements in the CSS transformation matrix. So only dollying is possible with this setup. It is just for testing so you can't use it in prod but it should be possible to verify the above assumption: https://jsfiddle.net/25azkv7m/

With this live example, no blurring happens when zooming into the text. Can you also make a test on your Windows device?

**Comment by xuchaozou** [comment] 2023-10-26 13:47
![image](https://github.com/mrdoob/three.js/assets/52873083/ea37209c-70d9-471d-8919-8b5ac67af6f2)
Thanks, it looks much better, but in this perspective, the label will still have an obvious jagged feeling, could you please tell me how to solve this, thank you以上翻译结果来自有道神经网络翻译（YNMT）· 通用场景

**Comment by xuchaozou** [comment] 2023-10-26 13:52
I'm running windows 10, and I'm using chrome118 for my browser

**Comment by Mugen87** [comment] 2023-10-26 14:11
The problem is that on this angle we have no integers again so the blurring starts happen again. I'm afraid there is no way to solve this issue in `CSS3DRenderer`. This needs to be reported to the browser vendor.

**Comment by xuchaozou** [comment] 2023-10-27 01:05
ok, thanks!!!

**Comment by xuchaozou** [comment] 2023-10-27 02:40
![image](https://github.com/mrdoob/three.js/assets/52873083/a1260bb7-bc70-48e3-b48f-1befe2ffee4a)
Why in this relatively large viewport, the main element uses translate, and the child element restores translate, and the element will not be blurred in any perspective

**Comment by xuchaozou** [comment] 2023-10-27 02:41
I don't know why, please help to answer, thank you @Mugen87

**Comment by xuchaozou** [comment] 2023-10-27 02:42
https://jsfiddle.net/onjbL8td/5/
Here is the link to the demo

**Comment by Mugen87** [comment] 2023-10-27 08:26
I don't see a different behavior compared to the original fiddle. The element still blurs if you zoom in. Maybe there is some sort of numerical threshold that when exceeded, the elements gets blurry in Chromium based browsers.

Again, this issue needs to be reported at the Chromium bug tracker: https://bugs.chromium.org/p/chromium/issues/list

**Comment by mrdoob** [comment] 2023-10-27 08:48
Indeed. Please report to Chromium instead.

**Closed by mrdoob** 2023-10-27 08:48 UTC
Labels: Browser Issue

**Comment by Mugen87** [comment] 2023-10-27 08:57
I have filed a bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1496742

**Comment by xuchaozou** [comment] 2023-10-27 09:27
Thank you so much for your help
