### ISSUE TITLE
Crashing on closing VR View (WebXRManager)

### ISSUE THREAD

**Issue by Simontaga** [mrdoob/three.js#24046] opened 2022-05-11 15:39 UTC
**Closing the WebXR view on android causes crash**

When I close the WebXR viewer on any android phone it causes a crash in the code mentioned below, seemingly there are no controllers to disconnect. If I do comment out the code for disconnecting controllers and the clear function, everything works fine and there is no crash upon closing the VR view.
**To Reproduce**

1. Open WebXR session on android
2. Close it

***Code***

```js
function onSessionEnd() {

   inputSourcesMap.forEach( function ( controller, inputSource ) {
   controller.disconnect( inputSource );
			} );

			inputSourcesMap.clear();
```

**Comment by Mugen87** [comment] 2022-05-11 15:56
Duplicate of #23983.

**Closed by Mugen87** 2022-05-11 15:56 UTC
