### ISSUE TITLE
BasisTextureLoader: Texture "fades over" its boundaries

### ISSUE THREAD

**Issue by nh2** [mrdoob/three.js#17597] opened 2019-09-27 21:04 UTC
##### Description of the problem

`BasisTextureLoader` produces different results for me on iOS than for other platforms.

Repro: https://nh2.me/webgl-basis-problem/

I get a weird "glow over" effect at the edge where the texture wraps around the sphere.

On any other platform, like Android or Chromium on Linux with Intel Mesa, it looks like this:

![image](https://user-images.githubusercontent.com/399535/65801489-7e6ee500-e179-11e9-99be-f7dbde43b2aa.png)

Notice the clear edge.

In contrast, on iOS, I get:

![image](https://user-images.githubusercontent.com/399535/65801553-a78f7580-e179-11e9-9847-50712312a4bf.png)

Here, the bright part of the left side of the texture somehow "glows over" into the right side.

I can't tell whether this is a bug in three.js or in the basis decompressor.

##### Three.js version

- [x] r108

##### Browser

- [x] Safari

##### OS

- [x] iOS

**Comment by mrdoob** [comment] 2019-09-27 21:09
Rather that a "glow" I think it's more like a "fade".

**Comment by nh2** [comment] 2019-09-27 21:12
> Rather that a "glow" I think it's more like a "fade".

I guess that's accurate, will update the title.

**Comment by shrekshao** [comment] 2019-09-27 21:18
Is your original texture image with a size of power of 2?

**Comment by nh2** [comment] 2019-09-27 21:31
> Is your original texture image with a size of power of 2?

Yes.

**Comment by nh2** [comment] 2019-09-27 21:37
I also just realised (inspecting my repro, and another test I have locally that uses two half-spheres with 1 texture each) that apparently the "faded" colours are exactly the ones from the opposing edge on the X-axis. As if it had some wrap-around logic when decoding.

This suggests that it might be a decoder issue, but I'm still not sure.

I filed https://github.com/BinomialLLC/basis_universal/issues/78 to get some insight from Basis's side.

**Comment by nh2** [comment] 2019-09-28 07:00
I've posted an update on https://github.com/BinomialLLC/basis_universal/issues/78#issuecomment-536159690 -- screenshots included there.

It shows the wrapping-around problem with a non-spinning cube.

**Comment by donmccurdy** [comment] 2021-01-23 01:06
The upstream issue was fixed according to https://github.com/BinomialLLC/basis_universal/issues/78. I'm not sure if we need to change our usage of the Basis transcoder to enable an option, or if it's just fixed in the latest version of the transcoder — r125 will update three.js to the latest version of the transcoder, so let's check this issue again then.

**Comment by donmccurdy** [comment] 2021-03-18 00:23
Our copy of the transcoder has been updated, and BasisTextureLoader significantly refactored – is this issue still happening?

**Comment by Mugen87** [comment] 2021-03-18 09:33
I've tested the OP's link on a iPad 8 with iOS 14 and I can't reproduce the issue. I see a clear edge just like with my iMac.

**Closed** 2021-03-19 21:26 UTC
Labels: Loaders
