### ISSUE TITLE
normal chanel texture transformation is ignored 

### ISSUE THREAD

**Issue by orenmiron** [mrdoob/three.js#23758] opened 2022-03-21 21:13 UTC
**Describe the bug**

hi
my gltf contains a texture transformation for the normals chanel.

```
  "materials": [
    {
      "name": "Material_0",
      "normalTexture": {
        "extensions": {
          "KHR_texture_transform": {
            "scale": [
              0.1,
              0.1
            ]
          }
        },
        "index": 1
      },
```

the transformation is ignored by Three.js editor
my normals map contains a white polygon.
see snapshots from from Three.js (wrong) and khronos viewer (correct)
normals polygon is marked with red
after snapshot, I attached the gltf inside a zip file.
please advise
**To Reproduce**

1. open https://threejs.org/editor/
2. import attached rectangle.gltf (extracted from rectangle.zip)
3. in the scene dialog, double click rectangle.gltf
4. in the Environment, select MODELVIEWER
5. ERROR - The normal image should be much larger becase the KHR_texture_transform scale is 0.1

***Code***

```js
// code goes here
```

***Live example***

* [jsfiddle-latest-release](https://jsfiddle.net/hyok6tvj/)
* [jsfiddle-dev](https://jsfiddle.net/c5m1kazu/)

**Expected behavior**
Since i was using scale transformation for the normal chanel in the material, i was expecting the normal texture to be much bigger, as viewd in khronos viewer.
ד

**Screenshots**
![1](https://user-images.githubusercontent.com/7829843/159364156-20ede746-7445-4e76-ae75-fb1a1a1a3e35.jpg)

[Rectangle.zip](https://github.com/mrdoob/three.js/files/8319203/Rectangle.zip)

**Platform:**

 - Device: [Desktop]
 - OS: [Windows]
 - Browser: [Chrome]
 - Three.js version: [dev, r138]

**Comment by WestLangley** [comment] 2022-03-21 21:43
If you remove `baseColorTexture`, is the texture transformation honored?

The three.js built-in materials currently only supports a single offset-repeat setting per material.

**Comment by mrdoob** [comment] 2022-03-22 02:40
I'm currently working on a PR that enables offset-repeat in all maps 🤓

**Comment by orenmiron** [comment] 2022-03-22 05:55
hi mrdoob.
I am happy to see that you are working on this issue.
Please note that Three.js already supports different offset-repeat in 
baseColorTexture and occlusionTexture.
or in 
occlusionTexture and normalTexture.
Please share your PR number. can you estimate when it will be ready?
Thanks.

**Comment by Mugen87** [comment] 2022-03-22 08:42
Duplicate of #9457.

**Closed by Mugen87** 2022-03-22 08:42 UTC
