### ISSUE TITLE
Box3.setFromObject() on empty Mesh with children

### ISSUE THREAD

**Issue by luruke** [mrdoob/three.js#8175] opened 2016-02-19 13:04 UTC
Hi All,
I've discovered an anomaly using `Box3.setFromObject` with a `Mesh` which has children.

Here you can find a jsFiddle: https://jsfiddle.net/luruke/xcexjt0r/3/

As you can see from the jsfiddle, the box `.min` and .`max` contains `Vector3(NaN, NaN, NaN)`
This happens if the `parentObj` is `Mesh` (it works correctly with `Object3D`).

As dirty/temporary solution in my code i've overwrite the function adding my piece of code:
```javascript
if(!Number.isFinite(geometry.boundingBox.min.x)) {
 return;
}
```

Is this the correct behavior or it's a bug?

**Comment by Mugen87** [comment] 2016-02-19 14:47
I think the problem in `Box3.setFromObject` occurs, because your `parentObj` is a mesh with an initial geometry object. In this case the computation of a bounding box result in `min, `max` vectors with (-)`Infinity` values. The following line (from `Box3.setFromObject`) then causes the `NaN` values.

```javascript
box.applyMatrix4( node.matrixWorld );
```

If your parent object has no geometry, i recommend to use an instance of `Object3D`. The usage of `Mesh` makes only sense, if your object has an material and a geometry...

**Comment by Mugen87** [comment] 2016-02-19 14:53
IMO it's not a bug.

**Comment by WestLangley** [comment] 2016-02-19 19:28
>because your parentObj is a mesh with an initial geometry object.

You mean _without_ an initial geometry object.

**Comment by Mugen87** [comment] 2016-02-19 21:06
I just wanted to say that the example code calls the constructor of `Mesh`without any parameters. Because of the following line of the constructor function, `this.geometry` is not `undefined` but "initial" or "empty". Well, "initial" is maybe not the correct expression, but i hope, you know what i mean :wink:

```javascript
this.geometry = geometry !== undefined ? geometry : new THREE.Geometry();
```

**Comment by Mugen87** [comment] 2016-03-16 19:19
@luruke Do you mind if you close the issue?

**Closed** 2016-03-17 07:51 UTC
