### ISSUE TITLE
TrackballControls: Object becomes unresponsive after zooming.

### ISSUE THREAD

**Issue by tejaspchordiya** [mrdoob/three.js#11499] opened 2017-06-13 07:03 UTC
In TrackballControls.js, it is observed that when we increase the zoom speed, these lines get executed to adjust the zooming of camera-

```
factor = 1.0 + ( _zoomEnd.y - _zoomStart.y ) * _this.zoomSpeed;
if ( factor !== 1.0 && factor > 0.0 ) {
    _eye.multiplyScalar( factor );
}
```
##### Steps to reproduce:
1. Default zoom speed is 1.2, user increases it to 35.
2. Zoom-in the object. Observe that the object becomes unresponsive after zooming-in to some extent.

##### Reason for unresponsiveness:
The zoom factor goes into negative and hence, the if statement never returns true. Hence, camera is not set properly and make 3d object unresponsive.

**Comment by tejaspchordiya** [comment] 2017-06-19 08:44
I tried resetting the zoom factor as 0.0 when it goes in negative. Even it is not helping to resolve the issue.

**Comment by tejaspchordiya** [comment] 2017-07-31 12:42
Any updates on this?

**Comment by Mugen87** [comment] 2019-07-10 15:33
> Observe that the object becomes unresponsive after zooming-in to some extent.

I've experimented a bit with `TrackballControls` but I'm not able to reproduce the issue. Any ideas how to achieve this "unresponsive"  state?

https://jsfiddle.net/rmzsya49/1/

**Comment by Mugen87** [comment] 2019-07-18 11:43
Closing for now. We can reopen when reproducing is possible.

**Closed** 2019-07-18 11:42 UTC
