### ISSUE TITLE
EmissiveMap texture error when using the MMDAnimationHelper and MMDLoader (maybe is texture error

### ISSUE THREAD

**Issue by ChenZihan-sudo** [mrdoob/three.js#23855] opened 2022-04-06 20:29 UTC
**Describe the bug**
**Same question at #23190**   

   
![image](https://user-images.githubusercontent.com/64928288/162061087-9870ee10-4420-4a48-a5f9-a530668807d6.png)
![O_3F@%Z%E$2%UG } YB3NFS](https://user-images.githubusercontent.com/64928288/162064727-9c9a6cc9-626c-49ec-be8e-d01bd1e0d6dd.jpg)

**But If I turn off the pointLight and only open the ambient light it can display the emissiveMap silghtly**
![X}629QQ%`HJVTB DMXN22S](https://user-images.githubusercontent.com/64928288/162064657-3c385a67-c3fd-4c83-8d5b-306d3ef86084.jpg)
![)SZX}91@81{TL9WY~J6Y7NJ](https://user-images.githubusercontent.com/64928288/162064861-c73d994b-5acd-4efa-83d7-14a4cbeecba8.jpg)

I found some solutions ways like 
https://zhuanlan.zhihu.com/p/350136476
and
https://blog.csdn.net/qq_34272760/article/details/120530944
Then I follow their ways found this
```js
//try to type this in console to find that emissiveMap
test.mesh.material[9].uniforms.emissiveMap
```
Surprisingly found this
![image](https://user-images.githubusercontent.com/64928288/162062856-2a3fb94c-2fbf-47d8-bcbe-7cbb58cec589.png)
So I thought that might be the texture error when parse the PMX file
then I 
```js
test.mesh.material[9].uniforms.emissiveMap = test.mesh.material[9].uniforms.emissiveMap
```
nothing helped   

**To Reproduce**

1. Go to download https://drive.google.com/drive/folders/1XkZkIqJa8zMwbunGL4XFAmNvDY_JZzcG?usp=sharing
2. Drag the package which named three.js-r139 into the folder MMDLoaderTest
3. Open VSCode and switch to test.html 
4. Click right button select "Open with Live Server"
5. Drag canvas to back of the character to see the problem

***Code***

```js
//use this function in console to play and pause the motion
PlayPause()
```

**Expected behavior**
I hope this can displayed rightly

**Platform:**

 - Device: [Desktop]
 - OS: [Windows11]
 - Browser: [Chrome 99.0.4844.84]
 - Three.js version: [r139]
 - IDE: [VSCode]
 - VSCodeExtension: [Live Server]

**Comment by ChenZihan-sudo** [comment] 2022-04-06 20:33
Sorry for the wrong writing
correct=>

```
test.mesh.material[9].uniforms.emissiveMap = test.mesh.material[9].uniforms.map
```

**Comment by ChenZihan-sudo** [comment] 2022-04-06 20:35
Use WebGL1Renderer or WebGLRenderer both nothing helped

**Comment by Mugen87** [comment] 2022-04-07 07:59
I don't think #23190 (which was about morph targets) is related to your issue. #23190 is also fixed with the latest version of `three.js`.

**Comment by Mugen87** [comment] 2022-04-11 08:31
> But if you compare the error with https://github.com/mrdoob/three.js/issues/23190 you will found they are very similar.

No sorry, I don't think so. Your issue looks unrelated to any kind of vertex displacement. TBH, I also don't understand the visual issue you have reported above. The screenshots looks like the expected result of the model's toon shader. 

It might be easier to understand your issue if you share two screenshots. One that shows the _expected_ result and the other the _actual_ one.

**Comment by ChenZihan-sudo** [comment] 2022-04-11 10:11
> > But if you compare the error with #23190 you will found they are very similar.
> 
> No sorry, I don't think so. Your issue looks unrelated to any kind of vertex displacement. TBH, I also don't understand the visual issue you have reported above. The screenshots look like the expected result of the model's toon shader.
> 
> It might be easier to understand your issue if you share two screenshots. One that shows the _expected_ result and the other the _actual_ one.

I mean when I load a pmx model. Add a light except ambient light to scene. The back of model where some area not illuminated by that light displayed a very black shadow. It showed like  this.
The red mark is the position of a point light.  
Look this model have very black shadow which is **actual one**.  
<img width="1053" alt="Snipaste_2022-04-11_18-02-31" src="https://user-images.githubusercontent.com/64928288/162715520-499cf3d9-f047-400b-bab7-0c4c95587a27.png">

What I **expected result** is let this model displayed like MikuMikuDance which don't have this black shadow when adding a light to the scene.  
<img width="424" alt="Snipaste_2022-04-11_18-08-09" src="https://user-images.githubusercontent.com/64928288/162716414-d7333620-a346-4b0d-99f8-010f80465e0d.png">

**Comment by ChenZihan-sudo** [comment] 2022-04-11 10:20
> > But if you compare the error with #23190 you will found they are very similar.
> 
> No sorry, I don't think so. Your issue looks unrelated to any kind of vertex displacement. TBH, I also don't understand the visual issue you have reported above. The screenshots look like the expected result of the model's toon shader.
> 
> It might be easier to understand your issue if you share two screenshots. One that shows the _expected_ result and the other the _actual_ one.

**I tested some models found a few models when it Illuminated by light source except ambient light will appear the black shadow.   
But these model display correctly in MikuMikuDance.**  
I also found some models don't have this issue when it Illuminated by light source except ambient light

**Comment by Mugen87** [comment] 2022-04-11 10:50
>  Add a light except ambient light to scene. The back of model where some area not illuminated by that light displayed a very black shadow

It seems I have missed this detail in your original post.

What you describe is actually the expected result. To avoid black areas of your model, you should combine your directional, point or spot  light with an ambient or hemisphere light like in the official [MMD demo](https://threejs.org/examples/webgl_loader_mmd). 

Can you please try the same lighting setup like in the official demo? Does it look better now?

> I also found some models don't have this issue when it Illuminated by light source except ambient light when using three.js.

That is strange. The toon shader should produce the same result for all assets.

**Comment by ChenZihan-sudo** [comment] 2022-04-11 11:36
> > Add a light except ambient light to scene. The back of model where some area not illuminated by that light displayed a very black shadow
> 
> It seems I have missed this detail in your original post.
> 
> What you describe is actually the expected result. To avoid black areas of your model, you should combine your directional, point or spot light with an ambient or hemisphere light like in the official [MMD demo](https://threejs.org/examples/webgl_loader_mmd).
> 
> Can you please try the same lighting setup like in the official demo? Does it look better now?
> 
> > I also found some models don't have this issue when it Illuminated by light source except ambient light when using three.js.
> 
> That is strange. The toon shader should produce the same result for all assets. Do you mind sharing one of these assets?

**Same issue.**
So that's why I think it's the same issue at https://github.com/mrdoob/three.js/issues/23190
I also test it on Mac. Both test used vsc extension live server to be the web server.
![image](https://user-images.githubusercontent.com/64928288/162730500-2d7382bf-e60f-4de0-a3dc-faf567334f45.png)
I only changed this path.
![image](https://user-images.githubusercontent.com/64928288/162730580-cf5949ab-8cc8-42f3-b499-2d0ee59c2855.png)

**Here is two model which have the black shadow[Issue one], which displayed correctly[displayed correctly]**
https://drive.google.com/drive/folders/1sjNjAyeJcrc3Su8t1pgFghjvR_B5x_uA?usp=sharing
![image](https://user-images.githubusercontent.com/64928288/162731224-e55ca47c-f464-46c2-8485-9e16fac1485a.png)


**Here is my code with a issued code.**
 https://drive.google.com/drive/folders/1XkZkIqJa8zMwbunGL4XFAmNvDY_JZzcG?usp=sharing

Sincere thanks for your help.

**Comment by Mugen87** [comment] 2022-04-11 11:48
I can reproduce now the lighting issue with the first model. I hope @takahirox can help here since I'm not sure what's going wrong so far.

**Comment by ChenZihan-sudo** [comment] 2022-04-11 11:50
Thanks a lot.

**Comment by ChenZihan-sudo** [comment] 2022-04-12 06:45
@takahirox  Just wait a moment, I am not sure I can make a web demo like this. What I can sure is that what kind of demo we use to load a specific MMD model which can loaded rightly in MikuMikuDance, It can't load the right shadow in three like this model.
https://drive.google.com/drive/folders/1sjNjAyeJcrc3Su8t1pgFghjvR_B5x_uA?usp=sharing
I will try to make a web demo, but maybe my server can't offer to provide global web, so it will have low speed to transmit.

**Comment by takahirox** [comment] 2022-04-12 07:23
@ChenZihan-sudo

Nevermind, I locally made a test by myself. It seems that specular isn't applied correctly. I will investigate more.

**Comment by takahirox** [comment] 2022-04-12 07:38
OK, figured out the root issue. `shininess` parameter is not handled properly. I will make a PR hopefully tomorrow.

**Comment by ChenZihan-sudo** [comment] 2022-04-12 13:24
Thanks for your help! :)

**Closed** 2022-04-12 17:47 UTC
Labels: Loaders, Needs Investigation

**Comment by takahirox** [comment] 2022-04-13 23:53
@ChenZihan-sudo #23889 has been merged. Just in case, would you mind if testing on your end, too, to check if the problem has been gone away?

**Comment by ChenZihan-sudo** [comment] 2022-04-14 01:16
@takahirox Thanks! It works very well!
I test it yesterday and didn't found any black shadow.   

I see you only merge the change to the jsm folder but js folder in example. However I am not use module. So I just copy your change to modify mmd loader in js folder. It still works! Thanks!

[Screenshot_20220414_090936_com.tencent.mobileqq.jpg](https://user-images.githubusercontent.com/64928288/163294391-bf8ef788-9346-46b2-9a8a-a2d104f00f00.jpg)
