### ISSUE TITLE
`GLTFExporter` <> `GLTFLoader` round trip `TypeError: Cannot set properties of undefined (setting 'isBone')`

### ISSUE THREAD

**Issue by trusktr** [mrdoob/three.js#28651] opened 2024-06-13 19:49 UTC
### Description

When I use `GLTFExporter` to export create a glTF JSON object and then try to round trip that back through `GLTFLoader` I get this error:

```
TypeError: Cannot set properties of undefined (setting 'isBone')
    at GLTFParser._markDefs (GLTFLoader.js:2714:36)
    at GLTFLoader.js:2643:32
    at GLTFParser._invokeAll (GLTFLoader.js:2834:19)
    at GLTFParser.parse (GLTFLoader.js:2641:8)
    at GLTFLoader.parse (GLTFLoader.js:437:10)
    at Object.onLoad (GLTFLoader.js:245:11)
    at three.module.js:44019:38
```

Reproduction: [codepen example with r165](https://codepen.io/trusktr/pen/KKLyorO)

Note, if we do not `clone` the `model.scene`, then the round trip works. Maybe the `model.scene.clone(true)` is failing to clone some information?

I want to clone because I want to ensure that I export the original tree and not the tree after it has been transformed by any animation (for example, I need bones in their original pose, not an animated pose).

Possibly related:

https://discourse.threejs.org/t/gltfloader-cannot-read-property-isbone-of-undefined/7245

### Reproduction steps

1. Visit [codepen example with r165](https://codepen.io/trusktr/pen/KKLyorO)
2. See the error in the console
3. try using `model.scene` instead of `model.scene.clone(true)` and there is no error

### Code

```js
new GLTFExporter().parseAsync(model.scene.clone(true), {animations: model.animations, binary: false})
```

(see the pen)

### Version

165

**Comment by Mugen87** [comment] 2024-06-13 20:32
Duplicate of #19419.

**Closed by Mugen87** 2024-06-13 20:32 UTC
